CARLA: CarlaRecorderPhysicsControl Struct Reference
CarlaRecorderPhysicsControl Struct Reference
#include <CarlaRecorderPhysicsControl.h>
Public Member Functions
void Read (std::ifstream &InFile)
void Write (std::ofstream &OutFile)
Public Attributes
uint32_t DatabaseId
FVehiclePhysicsControl VehiclePhysicsControl
Detailed Description
Definition at line 15 of file CarlaRecorderPhysicsControl.h.
Member Function Documentation
Read()
void CarlaRecorderPhysicsControl::Read (std::ifstream & InFile)
Definition at line 45 of file CarlaRecorderPhysicsControl.cpp.
References carla::rpc::VehiclePhysicsControl::center_of_mass, carla::rpc::VehiclePhysicsControl::clutch_strength, carla::rpc::VehiclePhysicsControl::damping_rate_full_throttle, carla::rpc::VehiclePhysicsControl::damping_rate_zero_throttle_clutch_disengaged, carla::rpc::VehiclePhysicsControl::damping_rate_zero_throttle_clutch_engaged, DatabaseId, carla::rpc::VehiclePhysicsControl::drag_coefficient, carla::rpc::VehiclePhysicsControl::final_ratio, carla::rpc::VehiclePhysicsControl::forward_gears, carla::rpc::VehiclePhysicsControl::mass, carla::rpc::VehiclePhysicsControl::max_rpm, carla::rpc::VehiclePhysicsControl::moi, ReadStdVector(), ReadValue(), carla::rpc::VehiclePhysicsControl::steering_curve, carla::rpc::VehiclePhysicsControl::torque_curve, carla::rpc::VehiclePhysicsControl::use_gear_autobox, VehiclePhysicsControl, and carla::rpc::VehiclePhysicsControl::wheels.
Referenced by CarlaRecorderQuery::QueryInfo().
Write()
void CarlaRecorderPhysicsControl::Write (std::ofstream & OutFile)
Definition at line 16 of file CarlaRecorderPhysicsControl.cpp.
References carla::rpc::VehiclePhysicsControl::center_of_mass, carla::rpc::VehiclePhysicsControl::clutch_strength, carla::rpc::VehiclePhysicsControl::damping_rate_full_throttle, carla::rpc::VehiclePhysicsControl::damping_rate_zero_throttle_clutch_disengaged, carla::rpc::VehiclePhysicsControl::damping_rate_zero_throttle_clutch_engaged, DatabaseId, carla::rpc::VehiclePhysicsControl::drag_coefficient, carla::rpc::VehiclePhysicsControl::final_ratio, carla::rpc::VehiclePhysicsControl::forward_gears, carla::rpc::VehiclePhysicsControl::mass, carla::rpc::VehiclePhysicsControl::max_rpm, carla::rpc::VehiclePhysicsControl::moi, carla::rpc::VehiclePhysicsControl::steering_curve, carla::rpc::VehiclePhysicsControl::torque_curve, carla::rpc::VehiclePhysicsControl::use_gear_autobox, VehiclePhysicsControl, carla::rpc::VehiclePhysicsControl::wheels, WriteStdVector(), and WriteValue().
Member Data Documentation
DatabaseId
uint32_t CarlaRecorderPhysicsControl::DatabaseId
Definition at line 17 of file CarlaRecorderPhysicsControl.h.
Referenced by ACarlaRecorder::AddPhysicsControl(), CarlaRecorderQuery::QueryInfo(), Read(), and Write().
VehiclePhysicsControl
FVehiclePhysicsControl CarlaRecorderPhysicsControl::VehiclePhysicsControl
Definition at line 18 of file CarlaRecorderPhysicsControl.h.
Referenced by ACarlaRecorder::AddPhysicsControl(), CarlaRecorderQuery::QueryInfo(), Read(), and Write().
The documentation for this struct was generated from the following files:
CarlaRecorderPhysicsControl.h
CarlaRecorderPhysicsControl.cpp