CARLA: carla::ros2::CarlaEgoVehicleControlSubscriber Class Reference
carla::ros2::CarlaEgoVehicleControlSubscriber Class Reference
#include <CarlaEgoVehicleControlSubscriber.h>
Public Member Functions
CarlaEgoVehicleControlSubscriber (void *vehicle, const char *ros_name="", const char *parent="")
CarlaEgoVehicleControlSubscriber (const CarlaEgoVehicleControlSubscriber &)
CarlaEgoVehicleControlSubscriber (CarlaEgoVehicleControlSubscriber &&)
void DestroySubscriber ()
void ForwardMessage (VehicleControl control)
VehicleControl GetMessage ()
void * GetVehicle ()
bool HasNewMessage ()
bool Init ()
bool IsAlive ()
CarlaEgoVehicleControlSubscriber & operator= (const CarlaEgoVehicleControlSubscriber &)
CarlaEgoVehicleControlSubscriber & operator= (CarlaEgoVehicleControlSubscriber &&)
bool Read ()
const char * type () const override
~CarlaEgoVehicleControlSubscriber ()
Public Member Functions inherited from carla::ros2::CarlaSubscriber
CarlaSubscriber ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaSubscriber ()=default
Private Member Functions
void SetData (int32_t seconds, uint32_t nanoseconds, uint32_t actor_id, std::vector< float > &&data)
Private Attributes
std::shared_ptr< CarlaEgoVehicleControlSubscriberImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaSubscriber
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 19 of file CarlaEgoVehicleControlSubscriber.h.
Constructor & Destructor Documentation
CarlaEgoVehicleControlSubscriber() [1/3]
carla::ros2::CarlaEgoVehicleControlSubscriber::CarlaEgoVehicleControlSubscriber (void * vehicle, const char * ros_name = "", const char * parent = "")
Definition at line 182 of file CarlaEgoVehicleControlSubscriber.cpp.
References _impl, carla::ros2::CarlaSubscriber::_name, carla::ros2::CarlaSubscriber::_parent, and carla::ros2::CarlaSubscriber::parent().
~CarlaEgoVehicleControlSubscriber()
carla::ros2::CarlaEgoVehicleControlSubscriber::~CarlaEgoVehicleControlSubscriber ()
Definition at line 190 of file CarlaEgoVehicleControlSubscriber.cpp.
References _impl.
CarlaEgoVehicleControlSubscriber() [2/3]
carla::ros2::CarlaEgoVehicleControlSubscriber::CarlaEgoVehicleControlSubscriber (const CarlaEgoVehicleControlSubscriber & other)
Definition at line 207 of file CarlaEgoVehicleControlSubscriber.cpp.
References carla::ros2::CarlaSubscriber::_frame_id, _impl, carla::ros2::CarlaSubscriber::_name, and carla::ros2::CarlaSubscriber::_parent.
CarlaEgoVehicleControlSubscriber() [3/3]
carla::ros2::CarlaEgoVehicleControlSubscriber::CarlaEgoVehicleControlSubscriber (CarlaEgoVehicleControlSubscriber && other)
Definition at line 225 of file CarlaEgoVehicleControlSubscriber.cpp.
References carla::ros2::CarlaSubscriber::_frame_id, _impl, carla::ros2::CarlaSubscriber::_name, and carla::ros2::CarlaSubscriber::_parent.
Member Function Documentation
DestroySubscriber()
void carla::ros2::CarlaEgoVehicleControlSubscriber::DestroySubscriber ()
Definition at line 161 of file CarlaEgoVehicleControlSubscriber.cpp.
Referenced by carla::ros2::CarlaSubscriberListenerImpl::on_subscription_matched(), and type().
ForwardMessage()
void carla::ros2::CarlaEgoVehicleControlSubscriber::ForwardMessage (VehicleControl control)
Definition at line 156 of file CarlaEgoVehicleControlSubscriber.cpp.
Referenced by carla::ros2::CarlaSubscriberListenerImpl::on_data_available(), and type().
GetMessage()
VehicleControl carla::ros2::CarlaEgoVehicleControlSubscriber::GetMessage ()
Definition at line 165 of file CarlaEgoVehicleControlSubscriber.cpp.
GetVehicle()
void * carla::ros2::CarlaEgoVehicleControlSubscriber::GetVehicle ()
Definition at line 178 of file CarlaEgoVehicleControlSubscriber.cpp.
HasNewMessage()
bool carla::ros2::CarlaEgoVehicleControlSubscriber::HasNewMessage ()
Definition at line 174 of file CarlaEgoVehicleControlSubscriber.cpp.
Init()
bool carla::ros2::CarlaEgoVehicleControlSubscriber::Init ()
Definition at line 47 of file CarlaEgoVehicleControlSubscriber.cpp.
IsAlive()
bool carla::ros2::CarlaEgoVehicleControlSubscriber::IsAlive ()
Definition at line 170 of file CarlaEgoVehicleControlSubscriber.cpp.
operator=() [1/2]
CarlaEgoVehicleControlSubscriber & carla::ros2::CarlaEgoVehicleControlSubscriber::operator= (const CarlaEgoVehicleControlSubscriber & other)
Definition at line 215 of file CarlaEgoVehicleControlSubscriber.cpp.
References carla::ros2::CarlaSubscriber::_frame_id, _impl, carla::ros2::CarlaSubscriber::_name, and carla::ros2::CarlaSubscriber::_parent.
operator=() [2/2]
CarlaEgoVehicleControlSubscriber & carla::ros2::CarlaEgoVehicleControlSubscriber::operator= (CarlaEgoVehicleControlSubscriber && other)
Definition at line 233 of file CarlaEgoVehicleControlSubscriber.cpp.
References carla::ros2::CarlaSubscriber::_frame_id, _impl, carla::ros2::CarlaSubscriber::_name, and carla::ros2::CarlaSubscriber::_parent.
Read()
bool carla::ros2::CarlaEgoVehicleControlSubscriber::Read ()
Definition at line 94 of file CarlaEgoVehicleControlSubscriber.cpp.
SetData()
void carla::ros2::CarlaEgoVehicleControlSubscriber::SetData (int32_t seconds, uint32_t nanoseconds, uint32_t actor_id, std::vector< float > && data) private
Referenced by type().
type()
const char* carla::ros2::CarlaEgoVehicleControlSubscriber::type () const inline override virtual
Implements carla::ros2::CarlaSubscriber.
Definition at line 35 of file CarlaEgoVehicleControlSubscriber.h.
References DestroySubscriber(), ForwardMessage(), and SetData().
Member Data Documentation
_impl
std::shared_ptr<CarlaEgoVehicleControlSubscriberImpl> carla::ros2::CarlaEgoVehicleControlSubscriber::_impl private
Definition at line 44 of file CarlaEgoVehicleControlSubscriber.h.
Referenced by CarlaEgoVehicleControlSubscriber(), operator=(), and ~CarlaEgoVehicleControlSubscriber().
The documentation for this class was generated from the following files:
CarlaEgoVehicleControlSubscriber.h
CarlaEgoVehicleControlSubscriber.cpp