CARLA: AVegetationManager Class Reference
AVegetationManager Class Reference
#include <VegetationManager.h>
Public Member Functions
void AddVehicle (ACarlaWheeledVehicle *Vehicle)
void RemoveVehicle (ACarlaWheeledVehicle *Vehicle)
Public Attributes
int32 InitialPoolSize {5}
bool SpawnBushes {true}
bool SpawnPlants {true}
bool SpawnRocks {true}
float SpawnScale {1.0f}
bool SpawnTrees {true}
Overriden from AActor
TArray< ACarlaWheeledVehicle * > VehiclesInLevel {}
TMap< FString, FFoliageBlueprint > FoliageBlueprintCache {}
TMap< FString, TArray< FPooledActor > > ActorPool {}
TMap< FString, FTileData > TileDataCache {}
virtual void BeginPlay () override
virtual void Tick (float DeltaTime) override
bool IsFoliageTypeEnabled (const FString &Path) const
bool CheckIfAnyVehicleInLevel () const
bool CheckForNewTiles () const
TArray< FString > GetTilesInUse ()
void UpdateVehiclesDetectionBoxes ()
void UpdateMaterials (TArray< FString > &Tiles)
TArray< TPair< FFoliageBlueprint, TArray< FTransform > > > GetElementsToSpawn (const TArray< FString > &Tiles)
void SpawnSkeletalFoliages (TArray< TPair< FFoliageBlueprint, TArray< FTransform >>> &ElementsToSpawn)
void DestroySkeletalFoliages ()
bool EnableActorFromPool (const FTransform &Transform, TArray< FPooledActor > &Pool)
void UpdateTileDataCache ()
void UpdateFoliageBlueprintCache ()
void GenerateTileDataInternals ()
void InitializeInstancedStaticMeshComponentCache (FTileData &TileData)
void InitializeMaterialCache (FTileData &TileData)
void CreatePoolForBPClass (const FFoliageBlueprint &BP)
AActor * CreateFoliage (const FFoliageBlueprint &BP, const FTransform &Transform) const
Detailed Description
Definition at line 67 of file VegetationManager.h.
Member Function Documentation
AddVehicle()
void AVegetationManager::AddVehicle (ACarlaWheeledVehicle * Vehicle)
Definition at line 178 of file VegetationManager.cpp.
References IsValid().
Referenced by ACarlaWheeledVehicle::AddReferenceToManager().
BeginPlay()
void AVegetationManager::BeginPlay () override protected virtual
Definition at line 142 of file VegetationManager.cpp.
CheckForNewTiles()
bool AVegetationManager::CheckForNewTiles () const private
Definition at line 602 of file VegetationManager.cpp.
References FPooledActor::Actor, and IsValid().
CheckIfAnyVehicleInLevel()
bool AVegetationManager::CheckIfAnyVehicleInLevel () const private
Definition at line 578 of file VegetationManager.cpp.
CreateFoliage()
AActor * AVegetationManager::CreateFoliage (const FFoliageBlueprint & BP, const FTransform & Transform) const private
Definition at line 562 of file VegetationManager.cpp.
References FPooledActor::Actor, and FFoliageBlueprint::SpawnedClass.
CreatePoolForBPClass()
void AVegetationManager::CreatePoolForBPClass (const FFoliageBlueprint & BP) private
Definition at line 539 of file VegetationManager.cpp.
References FPooledActor::Actor, FFoliageBlueprint::BPClassName, FPooledActor::DisableActor(), and IsValid().
DestroySkeletalFoliages()
void AVegetationManager::DestroySkeletalFoliages () private
Definition at line 491 of file VegetationManager.cpp.
References FPooledActor::Actor, and UCarlaStatics::GetLargeMapManager().
EnableActorFromPool()
bool AVegetationManager::EnableActorFromPool (const FTransform & Transform, TArray< FPooledActor > & Pool) private
Definition at line 514 of file VegetationManager.cpp.
References UCarlaStatics::GetLargeMapManager(), and ALargeMapManager::GlobalToLocalTransform().
GenerateTileDataInternals()
void AVegetationManager::GenerateTileDataInternals () private
Definition at line 287 of file VegetationManager.cpp.
GetElementsToSpawn()
TArray< TPair< FFoliageBlueprint, TArray< FTransform > > > AVegetationManager::GetElementsToSpawn (const TArray< FString > & Tiles) private
Definition at line 384 of file VegetationManager.cpp.
References UCarlaStatics::GetLargeMapManager(), FPooledActor::GlobalTransform, FTileMeshComponent::IndicesInUse, FTileMeshComponent::InstancedStaticMeshComponent, FFoliageBlueprint::IsValid(), ALargeMapManager::LocalToGlobalTransform(), and FTileData::TileMeshesCache.
GetTilesInUse()
TArray< FString > AVegetationManager::GetTilesInUse () private
Definition at line 620 of file VegetationManager.cpp.
References FTileData::InstancedFoliageActor, IsValid(), FTileData::ProceduralFoliageVolume, and Vehicle.
InitializeInstancedStaticMeshComponentCache()
void AVegetationManager::InitializeInstancedStaticMeshComponentCache (FTileData & TileData) private
Definition at line 299 of file VegetationManager.cpp.
References FTileData::InstancedFoliageActor, FTileMeshComponent::InstancedStaticMeshComponent, IsValid(), FFoliageBlueprint::IsValid(), and FTileData::TileMeshesCache.
InitializeMaterialCache()
void AVegetationManager::InitializeMaterialCache (FTileData & TileData) private
Definition at line 331 of file VegetationManager.cpp.
References FTileMeshComponent::InstancedStaticMeshComponent, FTileData::MaterialInstanceDynamicCache, and FTileData::TileMeshesCache.
IsFoliageTypeEnabled()
bool AVegetationManager::IsFoliageTypeEnabled (const FString & Path) const private
Definition at line 584 of file VegetationManager.cpp.
RemoveVehicle()
void AVegetationManager::RemoveVehicle (ACarlaWheeledVehicle * Vehicle)
Definition at line 189 of file VegetationManager.cpp.
References IsValid().
Referenced by ACarlaWheeledVehicle::RemoveReferenceToManager().
SpawnSkeletalFoliages()
void AVegetationManager::SpawnSkeletalFoliages (TArray< TPair< FFoliageBlueprint, TArray< FTransform >>> & ElementsToSpawn) private
Definition at line 453 of file VegetationManager.cpp.
References FPooledActor::Actor, FFoliageBlueprint::BPClassName, FPooledActor::EnableActor(), UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalTransform(), FPooledActor::GlobalTransform, IsValid(), and FFoliageBlueprint::IsValid().
Tick()
void AVegetationManager::Tick (float DeltaTime) override protected virtual
Definition at line 148 of file VegetationManager.cpp.
UpdateFoliageBlueprintCache()
void AVegetationManager::UpdateFoliageBlueprintCache () private
Definition at line 247 of file VegetationManager.cpp.
References FPooledActor::Actor, FFoliageBlueprint::BPClassName, IsValid(), FFoliageBlueprint::IsValid(), FFoliageBlueprint::SetBPClassName(), and FFoliageBlueprint::SetSpawnedClass().
UpdateMaterials()
void AVegetationManager::UpdateMaterials (TArray< FString > & Tiles) private
Definition at line 371 of file VegetationManager.cpp.
References Position, and FTileData::UpdateMaterialCache().
UpdateTileDataCache()
void AVegetationManager::UpdateTileDataCache () private
Definition at line 203 of file VegetationManager.cpp.
References FPooledActor::Actor, FTileData::InstancedFoliageActor, IsValid(), and FTileData::ProceduralFoliageVolume.
UpdateVehiclesDetectionBoxes()
void AVegetationManager::UpdateVehiclesDetectionBoxes () private
Definition at line 364 of file VegetationManager.cpp.
References Vehicle.
Member Data Documentation
ActorPool
TMap<FString, TArray<FPooledActor> > AVegetationManager::ActorPool {} private
Definition at line 130 of file VegetationManager.h.
FoliageBlueprintCache
TMap<FString, FFoliageBlueprint> AVegetationManager::FoliageBlueprintCache {} private
Definition at line 129 of file VegetationManager.h.
InitialPoolSize
int32 AVegetationManager::InitialPoolSize {5}
Definition at line 94 of file VegetationManager.h.
SpawnBushes
bool AVegetationManager::SpawnBushes {true}
Definition at line 79 of file VegetationManager.h.
SpawnPlants
bool AVegetationManager::SpawnPlants {true}
Definition at line 88 of file VegetationManager.h.
SpawnRocks
bool AVegetationManager::SpawnRocks {true}
Definition at line 85 of file VegetationManager.h.
SpawnScale
float AVegetationManager::SpawnScale {1.0f}
Definition at line 91 of file VegetationManager.h.
SpawnTrees
bool AVegetationManager::SpawnTrees {true}
Definition at line 82 of file VegetationManager.h.
TileDataCache
TMap<FString, FTileData> AVegetationManager::TileDataCache {} private
Definition at line 131 of file VegetationManager.h.
VehiclesInLevel
TArray<ACarlaWheeledVehicle*> AVegetationManager::VehiclesInLevel {} private
Definition at line 128 of file VegetationManager.h.
The documentation for this class was generated from the following files:
VegetationManager.h
VegetationManager.cpp