CARLA: CarlaRecorderWalkerBones Struct Reference
CarlaRecorderWalkerBones Struct Reference
#include <CarlaRecorderWalkerBones.h>
Public Member Functions
void Clear ()
void Read (std::ifstream &InFile)
void Write (std::ofstream &OutFile)
Public Attributes
std::vector< CarlaRecorderWalkerBone > Bones
uint32_t DatabaseId
Detailed Description
Definition at line 23 of file CarlaRecorderWalkerBones.h.
Member Function Documentation
Clear()
void CarlaRecorderWalkerBones::Clear (void)
Definition at line 49 of file CarlaRecorderWalkerBones.cpp.
References Bones.
Referenced by CarlaRecorderQuery::QueryInfo().
Read()
void CarlaRecorderWalkerBones::Read (std::ifstream & InFile)
Definition at line 27 of file CarlaRecorderWalkerBones.cpp.
References Bones, DatabaseId, ReadFString(), and ReadFVector().
Referenced by CarlaReplayer::ProcessWalkerBones(), and CarlaRecorderQuery::QueryInfo().
Write()
void CarlaRecorderWalkerBones::Write (std::ofstream & OutFile)
Definition at line 11 of file CarlaRecorderWalkerBones.cpp.
References Bones, DatabaseId, WriteFString(), and WriteFVector().
Referenced by CarlaRecorderWalkersBones::Write().
Member Data Documentation
Bones
std::vector<CarlaRecorderWalkerBone> CarlaRecorderWalkerBones::Bones
Definition at line 26 of file CarlaRecorderWalkerBones.h.
Referenced by ACarlaRecorder::AddActorBones(), Clear(), CarlaReplayerHelper::ProcessReplayerWalkerBones(), CarlaRecorderQuery::QueryInfo(), Read(), and Write().
DatabaseId
uint32_t CarlaRecorderWalkerBones::DatabaseId
Definition at line 25 of file CarlaRecorderWalkerBones.h.
Referenced by ACarlaRecorder::AddActorBones(), CarlaReplayerHelper::ProcessReplayerWalkerBones(), CarlaReplayer::ProcessWalkerBones(), CarlaRecorderQuery::QueryInfo(), Read(), and Write().
The documentation for this struct was generated from the following files:
CarlaRecorderWalkerBones.h
CarlaRecorderWalkerBones.cpp