CARLA: ARoadPainterWrapper Class Reference
ARoadPainterWrapper Class Reference
#include <RoadPainterWrapper.h>
Public Member Functions
ARoadPainterWrapper ()
void BeginPlay () override
void ReadConfigFile (const FString &CurrentMapName, const TMap< FString, FString > &DecalNamesMap)
Function for reading the decals configuration file (in JSON format)
void SetBlueprintVariables ()
Event for setting the necessary variables in blueprint in order to paint the roads.
void SpawnDecalsEvent ()
Event used for spawning decals via blueprint.
void SpawnMeshesEvent ()
Event used for spawning meshes via blueprint.
Public Attributes
FDecalsProperties DecalPropertiesConfig
Variable used for storing the JSON values of the decals so it can be later used by the blueprint (Road Painter Preset)
Private Member Functions
FVector ReadVectorFromJsonObject (TSharedPtr< FJsonObject > JsonObject)
Function to read 3D vectors from a JSON file.
Detailed Description
Definition at line 52 of file RoadPainterWrapper.h.
Constructor & Destructor Documentation
ARoadPainterWrapper()
ARoadPainterWrapper::ARoadPainterWrapper ()
Definition at line 22 of file RoadPainterWrapper.cpp.
Member Function Documentation
BeginPlay()
void ARoadPainterWrapper::BeginPlay () override
Definition at line 45 of file RoadPainterWrapper.cpp.
ReadConfigFile()
void ARoadPainterWrapper::ReadConfigFile (const FString & CurrentMapName, const TMap< FString, FString > & DecalNamesMap)
Function for reading the decals configuration file (in JSON format)
Definition at line 51 of file RoadPainterWrapper.cpp.
References FDecalsProperties::DecalMaterials, FDecalsProperties::DecalMaxScale, FDecalsProperties::DecalMinScale, FDecalsProperties::DecalNumToSpawn, DecalPropertiesConfig, FDecalsProperties::DecalRandomYaw, FDecalsProperties::DecalScale, FDecalsProperties::FixedDecalOffset, carla::client::detail::Get(), FDecalsProperties::RandomOffset, and ReadVectorFromJsonObject().
ReadVectorFromJsonObject()
FVector ARoadPainterWrapper::ReadVectorFromJsonObject (TSharedPtr< FJsonObject > JsonObject) private
Function to read 3D vectors from a JSON file.
Definition at line 100 of file RoadPainterWrapper.cpp.
Referenced by ReadConfigFile().
SetBlueprintVariables()
void ARoadPainterWrapper::SetBlueprintVariables ()
Event for setting the necessary variables in blueprint in order to paint the roads.
SpawnDecalsEvent()
void ARoadPainterWrapper::SpawnDecalsEvent ()
Event used for spawning decals via blueprint.
SpawnMeshesEvent()
void ARoadPainterWrapper::SpawnMeshesEvent ()
Event used for spawning meshes via blueprint.
Member Data Documentation
DecalPropertiesConfig
FDecalsProperties ARoadPainterWrapper::DecalPropertiesConfig
Variable used for storing the JSON values of the decals so it can be later used by the blueprint (Road Painter Preset)
Definition at line 81 of file RoadPainterWrapper.h.
Referenced by ReadConfigFile().
The documentation for this class was generated from the following files:
RoadPainterWrapper.h
RoadPainterWrapper.cpp