CARLA: sensor_msgs::msg::CameraInfo Class Reference
sensor_msgs::msg::CameraInfo Class Reference
This class represents the structure CameraInfo defined by the user in the IDL file.
#include <CameraInfo.h>
Public Member Functions
eProsima_user_DllExport uint32_t & binning_x ()
This function returns a reference to member binning_x.
eProsima_user_DllExport uint32_t binning_x () const
This function returns the value of member binning_x.
eProsima_user_DllExport void binning_x (uint32_t _binning_x)
This function sets a value in member binning_x.
eProsima_user_DllExport uint32_t & binning_y ()
This function returns a reference to member binning_y.
eProsima_user_DllExport uint32_t binning_y () const
This function returns the value of member binning_y.
eProsima_user_DllExport void binning_y (uint32_t _binning_y)
This function sets a value in member binning_y.
eProsima_user_DllExport CameraInfo (CameraInfo &&x) noexcept
Move constructor.
eProsima_user_DllExport CameraInfo (const CameraInfo &x)
Copy constructor.
eProsima_user_DllExport CameraInfo (uint32_t height=0, uint32_t width=0, double fov=0.0)
Default constructor.
eProsima_user_DllExport std::vector< double > & D ()
This function returns a reference to member D.
const eProsima_user_DllExport std::vector< double > & D () const
This function returns a constant reference to member D.
eProsima_user_DllExport void D (const std::vector< double > &_D)
This function copies the value in member D.
eProsima_user_DllExport void D (std::vector< double > &&_D)
This function moves the value in member D.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport std::string & distortion_model ()
This function returns a reference to member distortion_model.
const eProsima_user_DllExport std::string & distortion_model () const
This function returns a constant reference to member distortion_model.
eProsima_user_DllExport void distortion_model (const std::string &_distortion_model)
This function copies the value in member distortion_model.
eProsima_user_DllExport void distortion_model (std::string &&_distortion_model)
This function moves the value in member distortion_model.
eProsima_user_DllExport std_msgs::msg::Header & header ()
This function returns a reference to member header.
const eProsima_user_DllExport std_msgs::msg::Header & header () const
This function returns a constant reference to member header.
eProsima_user_DllExport void header (const std_msgs::msg::Header &_header)
This function copies the value in member header.
eProsima_user_DllExport void header (std_msgs::msg::Header &&_header)
This function moves the value in member header.
eProsima_user_DllExport uint32_t & height ()
This function returns a reference to member height.
eProsima_user_DllExport uint32_t height () const
This function returns the value of member height.
eProsima_user_DllExport void height (uint32_t _height)
This function sets a value in member height.
eProsima_user_DllExport std::array< double, 9 > & k ()
This function returns a reference to member k.
const eProsima_user_DllExport std::array< double, 9 > & k () const
This function returns a constant reference to member k.
eProsima_user_DllExport void k (const std::array< double, 9 > &_k)
This function copies the value in member K.
eProsima_user_DllExport void k (std::array< double, 9 > &&_k)
This function moves the value in member k.
eProsima_user_DllExport bool operator!= (const CameraInfo &x) const
Comparison operator.
eProsima_user_DllExport CameraInfo & operator= (CameraInfo &&x) noexcept
Move assignment.
eProsima_user_DllExport CameraInfo & operator= (const CameraInfo &x)
Copy assignment.
eProsima_user_DllExport bool operator== (const CameraInfo &x) const
Comparison operator.
eProsima_user_DllExport std::array< double, 12 > & p ()
This function returns a reference to member p.
const eProsima_user_DllExport std::array< double, 12 > & p () const
This function returns a constant reference to member p.
eProsima_user_DllExport void p (const std::array< double, 12 > &_p)
This function copies the value in member p.
eProsima_user_DllExport void p (std::array< double, 12 > &&_p)
This function moves the value in member p.
eProsima_user_DllExport std::array< double, 9 > & r ()
This function returns a reference to member r.
const eProsima_user_DllExport std::array< double, 9 > & r () const
This function returns a constant reference to member r.
eProsima_user_DllExport void r (const std::array< double, 9 > &_r)
This function copies the value in member r.
eProsima_user_DllExport void r (std::array< double, 9 > &&_r)
This function moves the value in member r.
eProsima_user_DllExport sensor_msgs::msg::RegionOfInterest & roi ()
This function returns a reference to member roi.
const eProsima_user_DllExport sensor_msgs::msg::RegionOfInterest & roi () const
This function returns a constant reference to member roi.
eProsima_user_DllExport void roi (const sensor_msgs::msg::RegionOfInterest &_roi)
This function copies the value in member roi.
eProsima_user_DllExport void roi (sensor_msgs::msg::RegionOfInterest &&_roi)
This function moves the value in member roi.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport uint32_t & width ()
This function returns a reference to member width.
eProsima_user_DllExport uint32_t width () const
This function returns the value of member width.
eProsima_user_DllExport void width (uint32_t _width)
This function sets a value in member width.
eProsima_user_DllExport ~CameraInfo ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const sensor_msgs::msg::CameraInfo &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
uint32_t m_binning_x
uint32_t m_binning_y
std::vector< double > m_d
std::string m_distortion_model
std_msgs::msg::Header m_header
uint32_t m_height
std::array< double, 9 > m_k
std::array< double, 12 > m_p
std::array< double, 9 > m_r
sensor_msgs::msg::RegionOfInterest m_roi
uint32_t m_width
Detailed Description
This class represents the structure CameraInfo defined by the user in the IDL file.
Definition at line 73 of file CameraInfo.h.
Constructor & Destructor Documentation
CameraInfo() [1/3]
sensor_msgs::msg::CameraInfo::CameraInfo (uint32_t height = 0, uint32_t width = 0, double fov = 0.0)
Default constructor.
Definition at line 47 of file CameraInfo.cpp.
References m_binning_x, m_binning_y, m_d, m_distortion_model, m_height, m_k, m_p, m_r, and m_width.
~CameraInfo()
sensor_msgs::msg::CameraInfo::~CameraInfo ()
Default destructor.
Definition at line 68 of file CameraInfo.cpp.
CameraInfo() [2/3]
sensor_msgs::msg::CameraInfo::CameraInfo (const CameraInfo & x)
Copy constructor.
Parameters
x Reference to the object sensor_msgs::msg::CameraInfo that will be copied.
Definition at line 72 of file CameraInfo.cpp.
References m_binning_x, m_binning_y, m_d, m_distortion_model, m_header, m_height, m_k, m_p, m_r, m_roi, and m_width.
CameraInfo() [3/3]
sensor_msgs::msg::CameraInfo::CameraInfo (CameraInfo && x) noexcept
Move constructor.
Parameters
x Reference to the object sensor_msgs::msg::CameraInfo that will be copied.
Definition at line 88 of file CameraInfo.cpp.
Member Function Documentation
binning_x() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::CameraInfo::binning_x ()
This function returns a reference to member binning_x.
Returns
Reference to member binning_x
binning_x() [2/3]
uint32_t & sensor_msgs::msg::CameraInfo::binning_x () const
This function returns the value of member binning_x.
This function returns a reference to member binning_x.
Returns
Value of member binning_x
Reference to member binning_x
Definition at line 532 of file CameraInfo.cpp.
binning_x() [3/3]
void sensor_msgs::msg::CameraInfo::binning_x (uint32_t _binning_x)
This function sets a value in member binning_x.
Parameters
_binning_x New value for member binning_x
Definition at line 522 of file CameraInfo.cpp.
binning_y() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::CameraInfo::binning_y ()
This function returns a reference to member binning_y.
Returns
Reference to member binning_y
binning_y() [2/3]
uint32_t & sensor_msgs::msg::CameraInfo::binning_y () const
This function returns the value of member binning_y.
This function returns a reference to member binning_y.
Returns
Value of member binning_y
Reference to member binning_y
Definition at line 560 of file CameraInfo.cpp.
binning_y() [3/3]
void sensor_msgs::msg::CameraInfo::binning_y (uint32_t _binning_y)
This function sets a value in member binning_y.
Parameters
_binning_y New value for member binning_y
Definition at line 550 of file CameraInfo.cpp.
D() [1/4]
eProsima_user_DllExport std::vector<double>& sensor_msgs::msg::CameraInfo::D ()
This function returns a reference to member D.
Returns
Reference to member D
D() [2/4]
std::vector< double > & sensor_msgs::msg::CameraInfo::D () const
This function returns a constant reference to member D.
This function returns a reference to member D.
Returns
Constant reference to member D
Reference to member D
Definition at line 391 of file CameraInfo.cpp.
D() [3/4]
void sensor_msgs::msg::CameraInfo::D (const std::vector< double > & _D)
This function copies the value in member D.
Parameters
_D New value to be copied in member D
Definition at line 371 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
D() [4/4]
void sensor_msgs::msg::CameraInfo::D (std::vector< double > && _D)
This function moves the value in member D.
Parameters
_D New value to be moved in member D
Definition at line 381 of file CameraInfo.cpp.
deserialize()
void sensor_msgs::msg::CameraInfo::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 220 of file CameraInfo.cpp.
Referenced by sensor_msgs::msg::CameraInfoPubSubType::deserialize().
distortion_model() [1/4]
eProsima_user_DllExport std::string& sensor_msgs::msg::CameraInfo::distortion_model ()
This function returns a reference to member distortion_model.
Returns
Reference to member distortion_model
distortion_model() [2/4]
std::string & sensor_msgs::msg::CameraInfo::distortion_model () const
This function returns a constant reference to member distortion_model.
This function returns a reference to member distortion_model.
Returns
Constant reference to member distortion_model
Reference to member distortion_model
Definition at line 353 of file CameraInfo.cpp.
distortion_model() [3/4]
void sensor_msgs::msg::CameraInfo::distortion_model (const std::string & _distortion_model)
This function copies the value in member distortion_model.
Parameters
_distortion_model New value to be copied in member distortion_model
Definition at line 333 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
distortion_model() [4/4]
void sensor_msgs::msg::CameraInfo::distortion_model (std::string && _distortion_model)
This function moves the value in member distortion_model.
Parameters
_distortion_model New value to be moved in member distortion_model
Definition at line 343 of file CameraInfo.cpp.
getCdrSerializedSize()
size_t sensor_msgs::msg::CameraInfo::getCdrSerializedSize (const sensor_msgs::msg::CameraInfo & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 159 of file CameraInfo.cpp.
References D(), distortion_model(), std_msgs::msg::Header::getCdrSerializedSize(), sensor_msgs::msg::RegionOfInterest::getCdrSerializedSize(), header(), k(), p(), r(), and roi().
Referenced by sensor_msgs::msg::CameraInfoPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t sensor_msgs::msg::CameraInfo::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 612 of file CameraInfo.cpp.
References sensor_msgs_msg_CameraInfo_max_key_cdr_typesize.
Referenced by sensor_msgs::msg::CameraInfoPubSubType::CameraInfoPubSubType(), and sensor_msgs::msg::CameraInfoPubSubType::getKey().
getMaxCdrSerializedSize()
size_t sensor_msgs::msg::CameraInfo::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 152 of file CameraInfo.cpp.
References sensor_msgs_msg_CameraInfo_max_cdr_typesize.
Referenced by sensor_msgs::msg::CameraInfoPubSubType::CameraInfoPubSubType().
header() [1/4]
eProsima_user_DllExport std_msgs::msg::Header& sensor_msgs::msg::CameraInfo::header ()
This function returns a reference to member header.
Returns
Reference to member header
header() [2/4]
std_msgs::msg::Header & sensor_msgs::msg::CameraInfo::header () const
This function returns a constant reference to member header.
This function returns a reference to member header.
Returns
Constant reference to member header
Reference to member header
Definition at line 260 of file CameraInfo.cpp.
header() [3/4]
void sensor_msgs::msg::CameraInfo::header (const std_msgs::msg::Header & _header)
This function copies the value in member header.
Parameters
_header New value to be copied in member header
Definition at line 240 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
header() [4/4]
void sensor_msgs::msg::CameraInfo::header (std_msgs::msg::Header && _header)
This function moves the value in member header.
Parameters
_header New value to be moved in member header
Definition at line 250 of file CameraInfo.cpp.
height() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::CameraInfo::height ()
This function returns a reference to member height.
Returns
Reference to member height
height() [2/3]
uint32_t & sensor_msgs::msg::CameraInfo::height () const
This function returns the value of member height.
This function returns a reference to member height.
Returns
Value of member height
Reference to member height
Definition at line 287 of file CameraInfo.cpp.
height() [3/3]
void sensor_msgs::msg::CameraInfo::height (uint32_t _height)
This function sets a value in member height.
Parameters
_height New value for member height
Definition at line 277 of file CameraInfo.cpp.
isKeyDefined()
bool sensor_msgs::msg::CameraInfo::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 619 of file CameraInfo.cpp.
Referenced by sensor_msgs::msg::CameraInfoPubSubType::CameraInfoPubSubType().
k() [1/4]
eProsima_user_DllExport std::array<double, 9>& sensor_msgs::msg::CameraInfo::k ()
This function returns a reference to member k.
Returns
Reference to member k
k() [2/4]
std::array< double, 9 > & sensor_msgs::msg::CameraInfo::k () const
This function returns a constant reference to member k.
This function returns a reference to member k.
Returns
Constant reference to member k
Reference to member k
Definition at line 429 of file CameraInfo.cpp.
k() [3/4]
void sensor_msgs::msg::CameraInfo::k (const std::array< double, 9 > & _k)
This function copies the value in member K.
This function copies the value in member k.
Parameters
_K New value to be copied in member K
_k New value to be copied in member k
Definition at line 409 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
k() [4/4]
void sensor_msgs::msg::CameraInfo::k (std::array< double, 9 > && _k)
This function moves the value in member k.
Parameters
_k New value to be moved in member k
Definition at line 419 of file CameraInfo.cpp.
operator!=()
bool sensor_msgs::msg::CameraInfo::operator!= (const CameraInfo & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::CameraInfo object to compare.
Definition at line 146 of file CameraInfo.cpp.
operator=() [1/2]
sensor_msgs::msg::CameraInfo & sensor_msgs::msg::CameraInfo::operator= (CameraInfo && x) noexcept
Move assignment.
Parameters
x Reference to the object sensor_msgs::msg::CameraInfo that will be copied.
Definition at line 122 of file CameraInfo.cpp.
operator=() [2/2]
sensor_msgs::msg::CameraInfo & sensor_msgs::msg::CameraInfo::operator= (const CameraInfo & x)
Copy assignment.
Parameters
x Reference to the object sensor_msgs::msg::CameraInfo that will be copied.
Definition at line 104 of file CameraInfo.cpp.
References m_binning_x, m_binning_y, m_d, m_distortion_model, m_header, m_height, m_k, m_p, m_r, m_roi, and m_width.
operator==()
bool sensor_msgs::msg::CameraInfo::operator== (const CameraInfo & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::CameraInfo object to compare.
Definition at line 140 of file CameraInfo.cpp.
References m_binning_x, m_binning_y, m_d, m_distortion_model, m_header, m_height, m_k, m_p, m_r, m_roi, and m_width.
p() [1/4]
eProsima_user_DllExport std::array<double, 12>& sensor_msgs::msg::CameraInfo::p ()
This function returns a reference to member p.
Returns
Reference to member p
p() [2/4]
std::array< double, 12 > & sensor_msgs::msg::CameraInfo::p () const
This function returns a constant reference to member p.
This function returns a reference to member p.
Returns
Constant reference to member p
Reference to member p
Definition at line 504 of file CameraInfo.cpp.
p() [3/4]
void sensor_msgs::msg::CameraInfo::p (const std::array< double, 12 > & _p)
This function copies the value in member p.
Parameters
_p New value to be copied in member p
Definition at line 484 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
p() [4/4]
void sensor_msgs::msg::CameraInfo::p (std::array< double, 12 > && _p)
This function moves the value in member p.
Parameters
_p New value to be moved in member p
Definition at line 494 of file CameraInfo.cpp.
r() [1/4]
eProsima_user_DllExport std::array<double, 9>& sensor_msgs::msg::CameraInfo::r ()
This function returns a reference to member r.
Returns
Reference to member r
r() [2/4]
std::array< double, 9 > & sensor_msgs::msg::CameraInfo::r () const
This function returns a constant reference to member r.
This function returns a reference to member r.
Returns
Constant reference to member r
Reference to member r
Definition at line 466 of file CameraInfo.cpp.
r() [3/4]
void sensor_msgs::msg::CameraInfo::r (const std::array< double, 9 > & _r)
This function copies the value in member r.
Parameters
_r New value to be copied in member r
Definition at line 446 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
r() [4/4]
void sensor_msgs::msg::CameraInfo::r (std::array< double, 9 > && _r)
This function moves the value in member r.
Parameters
_r New value to be moved in member r
Definition at line 456 of file CameraInfo.cpp.
roi() [1/4]
eProsima_user_DllExport sensor_msgs::msg::RegionOfInterest& sensor_msgs::msg::CameraInfo::roi ()
This function returns a reference to member roi.
Returns
Reference to member roi
roi() [2/4]
sensor_msgs::msg::RegionOfInterest & sensor_msgs::msg::CameraInfo::roi () const
This function returns a constant reference to member roi.
This function returns a reference to member roi.
Returns
Constant reference to member roi
Reference to member roi
Definition at line 598 of file CameraInfo.cpp.
roi() [3/4]
void sensor_msgs::msg::CameraInfo::roi (const sensor_msgs::msg::RegionOfInterest & _roi)
This function copies the value in member roi.
Parameters
_roi New value to be copied in member roi
Definition at line 578 of file CameraInfo.cpp.
Referenced by getCdrSerializedSize().
roi() [4/4]
void sensor_msgs::msg::CameraInfo::roi (sensor_msgs::msg::RegionOfInterest && _roi)
This function moves the value in member roi.
Parameters
_roi New value to be moved in member roi
Definition at line 588 of file CameraInfo.cpp.
serialize()
void sensor_msgs::msg::CameraInfo::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 204 of file CameraInfo.cpp.
Referenced by sensor_msgs::msg::CameraInfoPubSubType::serialize().
serializeKey()
void sensor_msgs::msg::CameraInfo::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 624 of file CameraInfo.cpp.
Referenced by sensor_msgs::msg::CameraInfoPubSubType::getKey().
width() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::CameraInfo::width ()
This function returns a reference to member width.
Returns
Reference to member width
width() [2/3]
uint32_t & sensor_msgs::msg::CameraInfo::width () const
This function returns the value of member width.
This function returns a reference to member width.
Returns
Value of member width
Reference to member width
Definition at line 315 of file CameraInfo.cpp.
width() [3/3]
void sensor_msgs::msg::CameraInfo::width (uint32_t _width)
This function sets a value in member width.
Parameters
_width New value for member width
Definition at line 305 of file CameraInfo.cpp.
Member Data Documentation
m_binning_x
uint32_t sensor_msgs::msg::CameraInfo::m_binning_x private
Definition at line 444 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_binning_y
uint32_t sensor_msgs::msg::CameraInfo::m_binning_y private
Definition at line 445 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_d
std::vector<double> sensor_msgs::msg::CameraInfo::m_d private
Definition at line 440 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_distortion_model
std::string sensor_msgs::msg::CameraInfo::m_distortion_model private
Definition at line 439 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_header
std_msgs::msg::Header sensor_msgs::msg::CameraInfo::m_header private
Definition at line 436 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_height
uint32_t sensor_msgs::msg::CameraInfo::m_height private
Definition at line 437 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_k
std::array<double, 9> sensor_msgs::msg::CameraInfo::m_k private
Definition at line 441 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_p
std::array<double, 12> sensor_msgs::msg::CameraInfo::m_p private
Definition at line 443 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_r
std::array<double, 9> sensor_msgs::msg::CameraInfo::m_r private
Definition at line 442 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_roi
sensor_msgs::msg::RegionOfInterest sensor_msgs::msg::CameraInfo::m_roi private
Definition at line 446 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
m_width
uint32_t sensor_msgs::msg::CameraInfo::m_width private
Definition at line 438 of file CameraInfo.h.
Referenced by CameraInfo(), operator=(), and operator==().
The documentation for this class was generated from the following files:
CameraInfo.h
CameraInfo.cpp