CARLA: traffic_manager::CollisionStage Class Reference
traffic_manager::CollisionStage Class Reference
This class is the thread executable for the collision detection stage.
#include <CollisionStage.h>
Public Member Functions
void Action () override
Implement this method with logic to process data inside the stage.
CollisionStage (std::string stage_name, std::shared_ptr< LocalizationToCollisionMessenger > localization_messenger, std::shared_ptr< CollisionToPlannerMessenger > planner_messenger, cc::World &world, Parameters &parameters, cc::DebugHelper &debug_helper)
void DataReceiver () override
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
void DataSender () override
Implement this method with logic to gather results from the action threads and send to next stage(s).
~CollisionStage ()
Public Member Functions inherited from traffic_manager::PipelineStage
PipelineStage (std::string stage_name)
void Start ()
void Stop ()
virtual ~PipelineStage ()
Private Member Functions
void DrawBoundary (const LocationList &boundary) const
A simple method used to draw bounding boxes around vehicles.
LocationList GetBoundary (const Actor &actor) const
Returns the bounding box corners of the vehicle passed to the method.
float GetBoundingBoxExtention (const Actor &ego_vehicle) const
Method to calculate the speed dependent bounding box extention for a vehicle.
LocationList GetGeodesicBoundary (const Actor &actor) const
Returns the extrapolated bounding box of the vehicle along its trajectory.
Polygon GetPolygon (const LocationList &boundary) const
Method to construct a boost polygon object.
std::unordered_set< ActorId > GetPotentialVehicleObstacles (const Actor &ego_vehicle)
Method to retreive the set of vehicles around the path of the given vehicle.
bool NegotiateCollision (const Actor &ego_vehicle, const Actor &other_vehicle) const
The method returns true if ego_vehicle should stop and wait for other_vehicle to pass.
Private Attributes
cc::DebugHelper & debug_helper
Reference to Carla's debug helper object.
bool frame_selector
Selection key for switching between output frames.
chr::time_point< chr::_V2::system_clock, chr::nanoseconds > last_world_actors_pass_instance
An object used to keep track of time between checking for all world actors.
std::shared_ptr< LocalizationToCollisionFrame > localization_frame
Pointer to data received from localization stage.
std::shared_ptr< LocalizationToCollisionMessenger > localization_messenger
Pointers to messenger objects.
int localization_messenger_state
Variables to remember messenger states.
uint number_of_vehicles
Number of vehicles registered with the traffic manager.
Parameters & parameters
Runtime parameterization object.
std::shared_ptr< CollisionToPlannerFrame > planner_frame_a
Pointers to output frames to be shared with motion planner stage.
std::shared_ptr< CollisionToPlannerFrame > planner_frame_b
std::shared_ptr< CollisionToPlannerMessenger > planner_messenger
int planner_messenger_state
std::unordered_map< ActorId, Actor > unregistered_actors
A structure used to keep track of actors spawned outside of traffic manager.
std::unordered_map< ActorId, uint > vehicle_id_to_index
The map used to connect actor ids to the array index of data frames.
VicinityGrid vicinity_grid
An object used for grid binning vehicles for faster proximity detection.
cc::World & world
Reference to Carla's world object.
Additional Inherited Members
Detailed Description
This class is the thread executable for the collision detection stage.
The class is responsible for checking possible collisions with other vehicles along the vehicle's trajectory.
Definition at line 54 of file CollisionStage.h.
Constructor & Destructor Documentation
traffic_manager::CollisionStage::CollisionStage (std::string stage_name, std::shared_ptr< LocalizationToCollisionMessenger > localization_messenger, std::shared_ptr< CollisionToPlannerMessenger > planner_messenger, cc::World & world, Parameters & parameters, cc::DebugHelper & debug_helper)
Definition at line 27 of file CollisionStage.cpp.
References frame_selector, last_world_actors_pass_instance, localization_messenger_state, number_of_vehicles, and planner_messenger_state.
traffic_manager::CollisionStage::~CollisionStage ()
Definition at line 54 of file CollisionStage.cpp.
Member Function Documentation
void traffic_manager::CollisionStage::Action () override virtual
Implement this method with logic to process data inside the stage.
Implements traffic_manager::PipelineStage.
Definition at line 56 of file CollisionStage.cpp.
References traffic_manager::LocalizationToCollisionData::actor, carla::geom::Math::DistanceSquared(), traffic_manager::VicinityGrid::EraseActor(), frame_selector, carla::client::World::GetActors(), traffic_manager::Parameters::GetCollisionDetection(), traffic_manager::Parameters::GetPercentageIgnoreActors(), GetPotentialVehicleObstacles(), traffic_manager::CollisionToPlannerData::hazard, last_world_actors_pass_instance, localization_frame, carla::log_info(), carla::log_warning(), traffic_manager::CollisionStageConstants::MAX_COLLISION_RADIUS, NegotiateCollision(), number_of_vehicles, parameters, planner_frame_a, planner_frame_b, unregistered_actors, traffic_manager::VicinityGrid::UpdateGrid(), vehicle_id_to_index, traffic_manager::CollisionStageConstants::VERTICAL_OVERLAP_THRESHOLD, vicinity_grid, world, and carla::geom::Vector3D::z.
void traffic_manager::CollisionStage::DataReceiver () override virtual
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
Implements traffic_manager::PipelineStage.
Definition at line 158 of file CollisionStage.cpp.
References localization_frame, localization_messenger, localization_messenger_state, number_of_vehicles, planner_frame_a, planner_frame_b, and vehicle_id_to_index.
void traffic_manager::CollisionStage::DataSender () override virtual
Implement this method with logic to gather results from the action threads and send to next stage(s).
Implements traffic_manager::PipelineStage.
Definition at line 185 of file CollisionStage.cpp.
References frame_selector, planner_frame_a, planner_frame_b, planner_messenger, and planner_messenger_state.
void traffic_manager::CollisionStage::DrawBoundary (const LocationList & boundary) const private
A simple method used to draw bounding boxes around vehicles.
Definition at line 434 of file CollisionStage.cpp.
References debug_helper, and carla::client::DebugHelper::DrawLine().
LocationList traffic_manager::CollisionStage::GetBoundary (const Actor & actor) const private
Returns the bounding box corners of the vehicle passed to the method.
Definition at line 397 of file CollisionStage.cpp.
References carla::geom::BoundingBox::extent, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by GetGeodesicBoundary(), and NegotiateCollision().
float traffic_manager::CollisionStage::GetBoundingBoxExtention (const Actor & ego_vehicle) const private
Method to calculate the speed dependent bounding box extention for a vehicle.
Definition at line 361 of file CollisionStage.cpp.
References traffic_manager::CollisionStageConstants::BOUNDARY_EXTENSION_MINIMUM, traffic_manager::CollisionStageConstants::CRAWL_SPEED, traffic_manager::CollisionStageConstants::EXTENSION_SQUARE_POINT, traffic_manager::CollisionStageConstants::HIGHWAY_SPEED, traffic_manager::CollisionStageConstants::HIGHWAY_TIME_HORIZON, and traffic_manager::CollisionStageConstants::TIME_HORIZON.
Referenced by GetGeodesicBoundary(), and NegotiateCollision().
LocationList traffic_manager::CollisionStage::GetGeodesicBoundary (const Actor & actor) const private
Returns the extrapolated bounding box of the vehicle along its trajectory.
Definition at line 280 of file CollisionStage.cpp.
References traffic_manager::CollisionStageConstants::BOUNDARY_EDGE_LENGTH, carla::geom::BoundingBox::extent, GetBoundary(), carla::client::detail::ActorState::GetBoundingBox(), GetBoundingBoxExtention(), traffic_manager::Parameters::GetDistanceToLeadingVehicle(), localization_frame, carla::geom::Vector3D::MakeUnitVector(), parameters, reverse(), vehicle_id_to_index, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by NegotiateCollision().
traffic_manager::Polygon traffic_manager::CollisionStage::GetPolygon (const LocationList & boundary) const private
Method to construct a boost polygon object.
Definition at line 266 of file CollisionStage.cpp.
Referenced by NegotiateCollision().
std::unordered_set< ActorId > traffic_manager::CollisionStage::GetPotentialVehicleObstacles (const Actor & ego_vehicle) private
Method to retreive the set of vehicles around the path of the given vehicle.
Definition at line 379 of file CollisionStage.cpp.
References traffic_manager::VicinityGrid::GetActors(), traffic_manager::CollisionStageConstants::HIGHWAY_SPEED, localization_frame, traffic_manager::VicinityGrid::UpdateGrid(), vehicle_id_to_index, and vicinity_grid.
Referenced by Action().
bool traffic_manager::CollisionStage::NegotiateCollision (const Actor & ego_vehicle, const Actor & other_vehicle) const private
The method returns true if ego_vehicle should stop and wait for other_vehicle to pass.
Definition at line 195 of file CollisionStage.cpp.
References carla::geom::Math::DistanceSquared(), carla::geom::Math::Dot(), GetBoundary(), GetBoundingBoxExtention(), GetGeodesicBoundary(), GetPolygon(), localization_frame, carla::geom::Vector3D::MakeUnitVector(), vehicle_id_to_index, and carla::geom::Vector3D::x.
Referenced by Action().
Member Data Documentation
cc::DebugHelper& traffic_manager::CollisionStage::debug_helper private
Reference to Carla's debug helper object.
Definition at line 76 of file CollisionStage.h.
Referenced by DrawBoundary().
bool traffic_manager::CollisionStage::frame_selector private
Selection key for switching between output frames.
Definition at line 62 of file CollisionStage.h.
Referenced by Action(), CollisionStage(), and DataSender().
chr::time_point<chr::_V2::system_clock, chr::nanoseconds> traffic_manager::CollisionStage::last_world_actors_pass_instance private
An object used to keep track of time between checking for all world actors.
Definition at line 86 of file CollisionStage.h.
Referenced by Action(), and CollisionStage().
std::shared_ptr<LocalizationToCollisionFrame> traffic_manager::CollisionStage::localization_frame private
Pointer to data received from localization stage.
Definition at line 64 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), GetGeodesicBoundary(), GetPotentialVehicleObstacles(), and NegotiateCollision().
std::shared_ptr<LocalizationToCollisionMessenger> traffic_manager::CollisionStage::localization_messenger private
Pointers to messenger objects.
Definition at line 69 of file CollisionStage.h.
Referenced by DataReceiver().
int traffic_manager::CollisionStage::localization_messenger_state private
Variables to remember messenger states.
Definition at line 59 of file CollisionStage.h.
Referenced by CollisionStage(), and DataReceiver().
uint traffic_manager::CollisionStage::number_of_vehicles private
Number of vehicles registered with the traffic manager.
Definition at line 88 of file CollisionStage.h.
Referenced by Action(), CollisionStage(), and DataReceiver().
Parameters& traffic_manager::CollisionStage::parameters private
Runtime parameterization object.
Definition at line 74 of file CollisionStage.h.
Referenced by Action(), and GetGeodesicBoundary().
std::shared_ptr<CollisionToPlannerFrame> traffic_manager::CollisionStage::planner_frame_a private
Pointers to output frames to be shared with motion planner stage.
Definition at line 66 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<CollisionToPlannerFrame> traffic_manager::CollisionStage::planner_frame_b private
Definition at line 67 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<CollisionToPlannerMessenger> traffic_manager::CollisionStage::planner_messenger private
Definition at line 70 of file CollisionStage.h.
Referenced by DataSender().
int traffic_manager::CollisionStage::planner_messenger_state private
Definition at line 60 of file CollisionStage.h.
Referenced by CollisionStage(), and DataSender().
std::unordered_map<ActorId, Actor> traffic_manager::CollisionStage::unregistered_actors private
A structure used to keep track of actors spawned outside of traffic manager.
Definition at line 83 of file CollisionStage.h.
Referenced by Action().
std::unordered_map<ActorId, uint> traffic_manager::CollisionStage::vehicle_id_to_index private
The map used to connect actor ids to the array index of data frames.
Definition at line 80 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), GetGeodesicBoundary(), GetPotentialVehicleObstacles(), and NegotiateCollision().
VicinityGrid traffic_manager::CollisionStage::vicinity_grid private
An object used for grid binning vehicles for faster proximity detection.
Definition at line 78 of file CollisionStage.h.
Referenced by Action(), and GetPotentialVehicleObstacles().
cc::World& traffic_manager::CollisionStage::world private
Reference to Carla's world object.
Definition at line 72 of file CollisionStage.h.
Referenced by Action().
The documentation for this class was generated from the following files:
CollisionStage.h
CollisionStage.cpp