CARLA: carla::learning::NeuralModel Class Reference
carla::learning::NeuralModel Class Reference
#include <pytorch.h>
Public Member Functions
void Forward ()
void ForwardCUDATensors ()
void ForwardDynamic ()
Outputs & GetOutputs ()
void LoadModel (char *filename, int device)
NeuralModel ()
void SetInputs (Inputs input)
~NeuralModel ()
Private Attributes
Inputs _input
Outputs _output
std::unique_ptr< NeuralModelImpl > Model
Detailed Description
Definition at line 61 of file pytorch.h.
Constructor & Destructor Documentation
NeuralModel()
carla::learning::NeuralModel::NeuralModel ()
Definition at line 167 of file pytorch.cpp.
~NeuralModel()
carla::learning::NeuralModel::~NeuralModel ()
Definition at line 301 of file pytorch.cpp.
Member Function Documentation
Forward()
void carla::learning::NeuralModel::Forward ()
Definition at line 190 of file pytorch.cpp.
References carla::learning::GetWheelTensorInputs(), and carla::learning::GetWheelTensorOutput().
ForwardCUDATensors()
void carla::learning::NeuralModel::ForwardCUDATensors ()
Definition at line 263 of file pytorch.cpp.
References carla::learning::GetWheelTensorOutput().
ForwardDynamic()
void carla::learning::NeuralModel::ForwardDynamic ()
Definition at line 223 of file pytorch.cpp.
References carla::learning::GetWheelTensorInputs(), and carla::learning::GetWheelTensorOutputDynamic().
GetOutputs()
Outputs & carla::learning::NeuralModel::GetOutputs ()
Definition at line 297 of file pytorch.cpp.
LoadModel()
void carla::learning::NeuralModel::LoadModel (char * filename, int device)
Definition at line 170 of file pytorch.cpp.
SetInputs()
void carla::learning::NeuralModel::SetInputs (Inputs input)
Definition at line 185 of file pytorch.cpp.
Member Data Documentation
_input
Inputs carla::learning::NeuralModel::_input private
Definition at line 77 of file pytorch.h.
_output
Outputs carla::learning::NeuralModel::_output private
Definition at line 78 of file pytorch.h.
Model
std::unique_ptr<NeuralModelImpl> carla::learning::NeuralModel::Model private
Definition at line 76 of file pytorch.h.
The documentation for this class was generated from the following files:
pytorch.h
pytorch.cpp