CARLA: geometry_msgs::msg::TransformStampedPubSubType Class Reference
geometry_msgs::msg::TransformStampedPubSubType Class Reference
This class represents the TopicDataType of the type TransformStamped defined by the user in the IDL file.
#include <TransformStampedPubSubTypes.h>
Public Types
typedef TransformStamped type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport TransformStampedPubSubType ()
virtual eProsima_user_DllExport ~TransformStampedPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type TransformStamped defined by the user in the IDL file.
Definition at line 47 of file TransformStampedPubSubTypes.h.
Member Typedef Documentation
type
typedef TransformStamped geometry_msgs::msg::TransformStampedPubSubType::type
Definition at line 51 of file TransformStampedPubSubTypes.h.
Constructor & Destructor Documentation
TransformStampedPubSubType()
geometry_msgs::msg::TransformStampedPubSubType::TransformStampedPubSubType ()
Definition at line 32 of file TransformStampedPubSubTypes.cpp.
References geometry_msgs::msg::TransformStamped::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::TransformStamped::getMaxCdrSerializedSize(), geometry_msgs::msg::TransformStamped::isKeyDefined(), and m_keyBuffer.
~TransformStampedPubSubType()
geometry_msgs::msg::TransformStampedPubSubType::~TransformStampedPubSubType () override virtual
Definition at line 45 of file TransformStampedPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::TransformStampedPubSubType::createData () override virtual
Definition at line 122 of file TransformStampedPubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::TransformStampedPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file TransformStampedPubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::TransformStampedPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file TransformStampedPubSubTypes.cpp.
References geometry_msgs::msg::TransformStamped::deserialize().
getKey()
bool geometry_msgs::msg::TransformStampedPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file TransformStampedPubSubTypes.cpp.
References geometry_msgs::msg::TransformStamped::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::TransformStamped::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::TransformStampedPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file TransformStampedPubSubTypes.cpp.
References geometry_msgs::msg::TransformStamped::getCdrSerializedSize().
serialize()
bool geometry_msgs::msg::TransformStampedPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file TransformStampedPubSubTypes.cpp.
References geometry_msgs::msg::TransformStamped::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::TransformStampedPubSubType::m_keyBuffer
Definition at line 104 of file TransformStampedPubSubTypes.h.
Referenced by getKey(), TransformStampedPubSubType(), and ~TransformStampedPubSubType().
m_md5
MD5 geometry_msgs::msg::TransformStampedPubSubType::m_md5
Definition at line 103 of file TransformStampedPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
TransformStampedPubSubTypes.h
TransformStampedPubSubTypes.cpp