CARLA: carla::road::element::RoadInfoSignal Class Reference
carla::road::element::RoadInfoSignal Class Reference final
#include <RoadInfoSignal.h>
Public Member Functions
void AcceptVisitor (RoadInfoVisitor &v) final
SignalOrientation GetOrientation () const
RoadId GetRoadId () const
double GetS () const
const Signal * GetSignal () const
SignId GetSignalId () const
double GetT () const
const std::vector< LaneValidity > & GetValidities () const
bool IsDynamic () const
RoadInfoSignal (SignId signal_id, Signal *signal, RoadId road_id, double s, double t, std::string orientation)
RoadInfoSignal (SignId signal_id, RoadId road_id, double s, double t, std::string orientation)
Public Member Functions inherited from carla::road::element::RoadInfo
double GetDistance () const
Distance from road's start location.
virtual ~RoadInfo ()=default
Private Attributes
std::string _orientation
RoadId _road_id
double _s
Signal * _signal
SignId _signal_id
double _t
std::vector< LaneValidity > _validities
friend MapBuilder
Additional Inherited Members
Protected Member Functions inherited from carla::road::element::RoadInfo
RoadInfo (double distance=0.0)
Detailed Description
Definition at line 16 of file RoadInfoSignal.h.
Constructor & Destructor Documentation
carla::road::element::RoadInfoSignal::RoadInfoSignal (SignId signal_id, Signal * signal, RoadId road_id, double s, double t, std::string orientation) inline
Definition at line 19 of file RoadInfoSignal.h.
carla::road::element::RoadInfoSignal::RoadInfoSignal (SignId signal_id, RoadId road_id, double s, double t, std::string orientation) inline
Definition at line 34 of file RoadInfoSignal.h.
Member Function Documentation
void carla::road::element::RoadInfoSignal::AcceptVisitor (RoadInfoVisitor & v) inline final virtual
Implements carla::road::element::RoadInfo.
Definition at line 47 of file RoadInfoSignal.h.
SignalOrientation carla::road::element::RoadInfoSignal::GetOrientation () const inline
Definition at line 75 of file RoadInfoSignal.h.
References _orientation, carla::road::Both, carla::road::Negative, and carla::road::Positive.
Referenced by carla::client::Landmark::GetOrientation().
RoadId carla::road::element::RoadInfoSignal::GetRoadId () const inline
Definition at line 59 of file RoadInfoSignal.h.
References _road_id.
Referenced by carla::client::Landmark::GetRoadId().
double carla::road::element::RoadInfoSignal::GetS () const inline
Definition at line 67 of file RoadInfoSignal.h.
References _s.
Referenced by ACarlaGameModeBase::DebugShowSignals(), and carla::client::Landmark::GetS().
const Signal* carla::road::element::RoadInfoSignal::GetSignal () const inline
Definition at line 55 of file RoadInfoSignal.h.
References _signal.
Referenced by carla::client::Landmark::GetCountry(), carla::client::Landmark::GetHeight(), carla::client::Landmark::GethOffset(), carla::client::Map::GetLandmarkGroup(), carla::client::Landmark::GetName(), carla::client::Landmark::GetPitch(), carla::client::Landmark::GetRoll(), carla::client::Landmark::GetSubType(), carla::client::Landmark::GetText(), carla::client::Landmark::GetTransform(), carla::client::Landmark::GetType(), carla::client::Landmark::GetUnit(), carla::client::Landmark::GetValue(), carla::client::Landmark::GetWidth(), and carla::client::Landmark::GetZOffset().
SignId carla::road::element::RoadInfoSignal::GetSignalId () const inline
Definition at line 51 of file RoadInfoSignal.h.
References _signal_id.
Referenced by carla::client::Landmark::GetId().
double carla::road::element::RoadInfoSignal::GetT () const inline
Definition at line 71 of file RoadInfoSignal.h.
References _t.
Referenced by carla::client::Landmark::GetT().
const std::vector<LaneValidity>& carla::road::element::RoadInfoSignal::GetValidities () const inline
Definition at line 85 of file RoadInfoSignal.h.
References _validities.
Referenced by carla::client::Landmark::GetValidities().
bool carla::road::element::RoadInfoSignal::IsDynamic () const inline
Definition at line 63 of file RoadInfoSignal.h.
References _signal, and carla::road::Signal::GetDynamic().
Referenced by carla::client::Landmark::IsDynamic().
Member Data Documentation
std::string carla::road::element::RoadInfoSignal::_orientation private
Definition at line 102 of file RoadInfoSignal.h.
Referenced by GetOrientation().
RoadId carla::road::element::RoadInfoSignal::_road_id private
Definition at line 96 of file RoadInfoSignal.h.
Referenced by GetRoadId().
double carla::road::element::RoadInfoSignal::_s private
Definition at line 98 of file RoadInfoSignal.h.
Referenced by GetS().
Signal* carla::road::element::RoadInfoSignal::_signal private
Definition at line 94 of file RoadInfoSignal.h.
Referenced by GetSignal(), and IsDynamic().
SignId carla::road::element::RoadInfoSignal::_signal_id private
Definition at line 92 of file RoadInfoSignal.h.
Referenced by GetSignalId().
double carla::road::element::RoadInfoSignal::_t private
Definition at line 100 of file RoadInfoSignal.h.
Referenced by GetT().
std::vector<LaneValidity> carla::road::element::RoadInfoSignal::_validities private
Definition at line 104 of file RoadInfoSignal.h.
Referenced by carla::road::MapBuilder::AddValidityToSignalReference(), and GetValidities().
friend carla::road::element::RoadInfoSignal::MapBuilder private
Definition at line 90 of file RoadInfoSignal.h.
The documentation for this class was generated from the following file:
RoadInfoSignal.h