CARLA: ASensorFactory Class Reference
ASensorFactory Class Reference
Factory in charge of spawning sensors.
#include <SensorFactory.h>
Private Member Functions
TArray< FActorDefinition > GetDefinitions () final
Retrieve the definitions of all the sensors registered in the SensorRegistry.
FActorSpawnResult SpawnActor (const FTransform &SpawnAtTransform, const FActorDescription &ActorDescription) final
Spawn an actor based on ActorDescription and Transform.
Additional Inherited Members
Public Member Functions inherited from ACarlaActorFactory
ACarlaActorFactory (const FObjectInitializer &ObjectInitializer)
Detailed Description
Factory in charge of spawning sensors.
This factory is able to spawn every sensor registered in carla::sensor::SensorRegistry.
Definition at line 17 of file SensorFactory.h.
Member Function Documentation
GetDefinitions()
TArray< FActorDefinition > ASensorFactory::GetDefinitions () final private virtual
Retrieve the definitions of all the sensors registered in the SensorRegistry.
Sensors must implement a GetSensorDefinition() static method.
Reimplemented from ACarlaActorFactory.
Definition at line 100 of file SensorFactory.cpp.
References FSensorDefinitionGatherer::GetSensorDefinitions().
SpawnActor()
FActorSpawnResult ASensorFactory::SpawnActor (const FTransform & SpawnAtTransform, const FActorDescription & ActorDescription) final private virtual
Spawn an actor based on ActorDescription and Transform.
Precondition
ActorDescription is expected to be derived from one of the definitions retrieved with GetDefinitions.
Reimplemented from ACarlaActorFactory.
Definition at line 105 of file SensorFactory.cpp.
References ASceneCaptureSensor::CameraGBuffers, FActorDescription::Class, ASceneCaptureSensor::CustomDepth, ASceneCaptureSensor::CustomStencil, ASceneCaptureSensor::GBufferA, ASceneCaptureSensor::GBufferB, ASceneCaptureSensor::GBufferC, ASceneCaptureSensor::GBufferD, ASceneCaptureSensor::GBufferE, ASceneCaptureSensor::GBufferF, UCarlaGameInstance::GetCarlaEpisode(), UCarlaStatics::GetGameInstance(), UCarlaGameInstance::GetServer(), FCarlaServer::OpenStream(), ASceneCaptureSensor::SceneColor, ASceneCaptureSensor::SceneDepth, ASceneCaptureSensor::SceneStencil, FCameraGBufferUint8::SetDataStream(), ASceneCaptureSensor::SSAO, and ASceneCaptureSensor::Velocity.
The documentation for this class was generated from the following files:
SensorFactory.h
SensorFactory.cpp