CARLA: traffic_manager::LocalizationStage Class Reference
traffic_manager::LocalizationStage Class Reference
This class is responsible for maintaining a horizon of waypoints ahead of the vehicle for it to follow.
#include <LocalizationStage.h>
Public Member Functions
void Action () override
Implement this method with logic to process data inside the stage.
void DataReceiver () override
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
void DataSender () override
Implement this method with logic to gather results from the action threads and send to next stage(s).
LocalizationStage (std::string stage_name, std::shared_ptr< LocalizationToPlannerMessenger > planner_messenger, std::shared_ptr< LocalizationToCollisionMessenger > collision_messenger, std::shared_ptr< LocalizationToTrafficLightMessenger > traffic_light_messenger, AtomicActorSet &registered_actors, InMemoryMap &local_map, Parameters &parameters, cc::DebugHelper &debug_helper)
~LocalizationStage ()
Public Member Functions inherited from traffic_manager::PipelineStage
PipelineStage (std::string stage_name)
void Start ()
void Stop ()
virtual ~PipelineStage ()
Private Member Functions
SimpleWaypointPtr AssignLaneChange (Actor vehicle, bool force, bool direction)
Method to determine lane change and obtain target lane waypoint.
void DrawBuffer (Buffer &buffer)
A simple method used to draw waypoint buffer ahead of a vehicle.
void PopWaypoint (Buffer &buffer, ActorId actor_id)
void PushWaypoint (Buffer &buffer, ActorId actor_id, SimpleWaypointPtr &waypoint)
Methods to modify waypoint buffer and track traffic.
Private Attributes
std::vector< Actor > actor_list
List of actors registered with the traffic manager in current update cycle.
std::map< carla::ActorId, bool > approached
Used to only calculate the extended buffer once at junctions.
std::shared_ptr< BufferList > buffer_list
Structures to hold waypoint buffers for all vehicles.
std::shared_ptr< LocalizationToCollisionFrame > collision_frame_a
Output data frames to be shared with the collision stage.
std::shared_ptr< LocalizationToCollisionFrame > collision_frame_b
bool collision_frame_ready
bool collision_frame_selector
std::shared_ptr< LocalizationToCollisionMessenger > collision_messenger
Pointer to messenger to collision stage.
int collision_messenger_state
cc::DebugHelper & debug_helper
Reference to Carla's debug helper object.
std::map< carla::ActorId, SimpleWaypointPtr > final_points
Final Waypoint of the bounding box at intersections, amps to their respective IDs.
std::unordered_map< ActorId, chr::time_point< chr::_V2::system_clock, chr::nanoseconds > > idle_time
Map of all vehicles' idle time.
InMemoryMap & local_map
Reference to local map-cache object.
uint number_of_vehicles
Number of vehicles currently registered with the traffic manager.
Parameters & parameters
Runtime parameterization object.
std::shared_ptr< LocalizationToPlannerFrame > planner_frame_a
Output data frames to be shared with the motion planner stage.
std::shared_ptr< LocalizationToPlannerFrame > planner_frame_b
bool planner_frame_selector
Section keys to switch between the output data frames.
std::shared_ptr< LocalizationToPlannerMessenger > planner_messenger
Pointer to messenger to motion planner stage.
int planner_messenger_state
Variables to remember messenger states.
AtomicActorSet & registered_actors
Reference to set of all actors registered with the traffic manager.
int registered_actors_state
State counter to track changes in registered actors.
TrackTraffic track_traffic
Object for tracking paths of the traffic vehicles.
std::shared_ptr< LocalizationToTrafficLightFrame > traffic_light_frame_a
Output data frames to be shared with the traffic light stage.
std::shared_ptr< LocalizationToTrafficLightFrame > traffic_light_frame_b
bool traffic_light_frame_selector
std::shared_ptr< LocalizationToTrafficLightMessenger > traffic_light_messenger
Pointer to messenger to traffic light stage.
int traffic_light_messenger_state
std::unordered_map< ActorId, uint > vehicle_id_to_index
Map connecting actor ids to indices of data arrays.
Additional Inherited Members
Detailed Description
This class is responsible for maintaining a horizon of waypoints ahead of the vehicle for it to follow.
The class is also responsible for managing lane change decisions and modify the waypoint trajectory appropriately.
Definition at line 47 of file LocalizationStage.h.
Constructor & Destructor Documentation
traffic_manager::LocalizationStage::LocalizationStage (std::string stage_name, std::shared_ptr< LocalizationToPlannerMessenger > planner_messenger, std::shared_ptr< LocalizationToCollisionMessenger > collision_messenger, std::shared_ptr< LocalizationToTrafficLightMessenger > traffic_light_messenger, AtomicActorSet & registered_actors, InMemoryMap & local_map, Parameters & parameters, cc::DebugHelper & debug_helper)
Definition at line 26 of file LocalizationStage.cpp.
References collision_frame_ready, collision_frame_selector, collision_messenger_state, number_of_vehicles, planner_frame_selector, planner_messenger_state, registered_actors_state, traffic_light_frame_selector, and traffic_light_messenger_state.
traffic_manager::LocalizationStage::~LocalizationStage ()
Definition at line 62 of file LocalizationStage.cpp.
Member Function Documentation
void traffic_manager::LocalizationStage::Action () override virtual
Implement this method with logic to process data inside the stage.
Implements traffic_manager::PipelineStage.
Definition at line 64 of file LocalizationStage.cpp.
References traffic_manager::LocalizationToPlannerData::actor, traffic_manager::LocalizationToCollisionData::actor, traffic_manager::LocalizationToTrafficLightData::actor, actor_list, traffic_manager::LocalizationToPlannerData::approaching_true_junction, AssignLaneChange(), traffic_manager::LocalizationToCollisionData::buffer, buffer_list, traffic_manager::ChangeLaneInfo::change_lane, traffic_manager::LocalizationToTrafficLightData::closest_waypoint, collision_frame_a, collision_frame_b, collision_frame_ready, collision_frame_selector, collision_messenger, collision_messenger_state, traffic_manager::LocalizationToPlannerData::deviation, traffic_manager::DeviationCrossProduct(), traffic_manager::DeviationDotProduct(), traffic_manager::ChangeLaneInfo::direction, carla::geom::Location::Distance(), traffic_manager::LocalizationToPlannerData::distance, carla::geom::Math::DistanceSquared(), traffic_manager::Parameters::GetAutoLaneChange(), traffic_manager::Parameters::GetForceLaneChange(), traffic_manager::TrackTraffic::GetOverlappingVehicles(), carla::client::Vehicle::GetSpeedLimit(), traffic_manager::InMemoryMap::GetWaypoint(), traffic_manager::InMemoryMap::GetWaypointInVicinity(), traffic_manager::LocalizationConstants::HIGHWAY_SPEED, idle_time, traffic_manager::LocalizationToTrafficLightData::junction_look_ahead_waypoint, carla::geom::Vector3D::Length(), local_map, traffic_manager::LocalizationConstants::MINIMUM_HORIZON_LENGTH, traffic_manager::LocalizationConstants::MINIMUM_JUNCTION_LOOK_AHEAD, traffic_manager::LocalizationToCollisionData::overlapping_actors, parameters, planner_frame_a, planner_frame_b, planner_frame_selector, PopWaypoint(), PushWaypoint(), traffic_manager::TrackTraffic::RemoveOverlappingVehicle(), traffic_manager::LocalizationConstants::TARGET_WAYPOINT_HORIZON_LENGTH, traffic_manager::LocalizationConstants::TARGET_WAYPOINT_TIME_HORIZON, track_traffic, traffic_light_frame_a, traffic_light_frame_b, traffic_light_frame_selector, vehicle_id_to_index, and traffic_manager::LocalizationConstants::WAYPOINT_TIME_HORIZON.
SimpleWaypointPtr traffic_manager::LocalizationStage::AssignLaneChange (Actor vehicle, bool force, bool direction) private
Method to determine lane change and obtain target lane waypoint.
Definition at line 403 of file LocalizationStage.cpp.
References buffer_list, traffic_manager::DeviationDotProduct(), carla::geom::Math::DistanceSquared(), carla::geom::Math::Dot(), traffic_manager::TrackTraffic::GetOverlappingVehicles(), traffic_manager::TrackTraffic::GetPassingVehicles(), traffic_manager::LocalizationConstants::HIGHWAY_SPEED, carla::geom::Vector3D::Length(), traffic_manager::LocalizationConstants::MAXIMUM_LANE_OBSTACLE_CURVATURE, traffic_manager::LocalizationConstants::MINIMUM_LANE_CHANGE_DISTANCE, track_traffic, and vehicle_id_to_index.
Referenced by Action().
void traffic_manager::LocalizationStage::DataReceiver () override virtual
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
Implements traffic_manager::PipelineStage.
Definition at line 258 of file LocalizationStage.cpp.
References actor_list, buffer_list, collision_frame_a, collision_frame_b, traffic_manager::AtomicActorSet::GetList(), traffic_manager::AtomicActorSet::GetState(), number_of_vehicles, planner_frame_a, planner_frame_b, registered_actors, registered_actors_state, traffic_light_frame_a, traffic_light_frame_b, and vehicle_id_to_index.
void traffic_manager::LocalizationStage::DataSender () override virtual
Implement this method with logic to gather results from the action threads and send to next stage(s).
Implements traffic_manager::PipelineStage.
Definition at line 296 of file LocalizationStage.cpp.
References collision_frame_a, collision_frame_b, collision_frame_ready, collision_frame_selector, collision_messenger, collision_messenger_state, planner_frame_a, planner_frame_b, planner_frame_selector, planner_messenger, planner_messenger_state, traffic_light_frame_a, traffic_light_frame_b, traffic_light_frame_selector, traffic_light_messenger, and traffic_light_messenger_state.
void traffic_manager::LocalizationStage::DrawBuffer (Buffer & buffer) private
A simple method used to draw waypoint buffer ahead of a vehicle.
Definition at line 340 of file LocalizationStage.cpp.
References debug_helper, and carla::client::DebugHelper::DrawPoint().
void traffic_manager::LocalizationStage::PopWaypoint (Buffer & buffer, ActorId actor_id) private
Definition at line 370 of file LocalizationStage.cpp.
References traffic_manager::TrackTraffic::GetOverlappingVehicles(), traffic_manager::TrackTraffic::GetPassingVehicles(), traffic_manager::TrackTraffic::RemoveOverlappingVehicle(), traffic_manager::TrackTraffic::RemovePassingVehicle(), and track_traffic.
Referenced by Action().
void traffic_manager::LocalizationStage::PushWaypoint (Buffer & buffer, ActorId actor_id, SimpleWaypointPtr & waypoint) private
Methods to modify waypoint buffer and track traffic.
Definition at line 347 of file LocalizationStage.cpp.
References traffic_manager::TrackTraffic::GetPassingVehicles(), track_traffic, traffic_manager::TrackTraffic::UpdateOverlappingVehicle(), and traffic_manager::TrackTraffic::UpdatePassingVehicle().
Referenced by Action().
Member Data Documentation
std::vector<Actor> traffic_manager::LocalizationStage::actor_list private
List of actors registered with the traffic manager in current update cycle.
Definition at line 79 of file LocalizationStage.h.
Referenced by Action(), and DataReceiver().
std::map<carla::ActorId, bool> traffic_manager::LocalizationStage::approached private
Used to only calculate the extended buffer once at junctions.
Definition at line 96 of file LocalizationStage.h.
std::shared_ptr<BufferList> traffic_manager::LocalizationStage::buffer_list private
Structures to hold waypoint buffers for all vehicles.
These are shared with the collisions stage.
Definition at line 90 of file LocalizationStage.h.
Referenced by Action(), AssignLaneChange(), and DataReceiver().
std::shared_ptr<LocalizationToCollisionFrame> traffic_manager::LocalizationStage::collision_frame_a private
Output data frames to be shared with the collision stage.
Definition at line 64 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<LocalizationToCollisionFrame> traffic_manager::LocalizationStage::collision_frame_b private
Definition at line 65 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
bool traffic_manager::LocalizationStage::collision_frame_ready private
Definition at line 58 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
bool traffic_manager::LocalizationStage::collision_frame_selector private
Definition at line 57 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
std::shared_ptr<LocalizationToCollisionMessenger> traffic_manager::LocalizationStage::collision_messenger private
Pointer to messenger to collision stage.
Definition at line 72 of file LocalizationStage.h.
Referenced by Action(), and DataSender().
int traffic_manager::LocalizationStage::collision_messenger_state private
Definition at line 53 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
cc::DebugHelper& traffic_manager::LocalizationStage::debug_helper private
Reference to Carla's debug helper object.
Definition at line 87 of file LocalizationStage.h.
Referenced by DrawBuffer().
std::map<carla::ActorId, SimpleWaypointPtr> traffic_manager::LocalizationStage::final_points private
Final Waypoint of the bounding box at intersections, amps to their respective IDs.
Definition at line 98 of file LocalizationStage.h.
std::unordered_map<ActorId, chr::time_point<chr::_V2::system_clock, chr::nanoseconds> > traffic_manager::LocalizationStage::idle_time private
Map of all vehicles' idle time.
Definition at line 102 of file LocalizationStage.h.
Referenced by Action().
InMemoryMap& traffic_manager::LocalizationStage::local_map private
Reference to local map-cache object.
Definition at line 83 of file LocalizationStage.h.
Referenced by Action().
uint traffic_manager::LocalizationStage::number_of_vehicles private
Number of vehicles currently registered with the traffic manager.
Definition at line 94 of file LocalizationStage.h.
Referenced by DataReceiver(), and LocalizationStage().
Parameters& traffic_manager::LocalizationStage::parameters private
Runtime parameterization object.
Definition at line 85 of file LocalizationStage.h.
Referenced by Action().
std::shared_ptr<LocalizationToPlannerFrame> traffic_manager::LocalizationStage::planner_frame_a private
Output data frames to be shared with the motion planner stage.
Definition at line 61 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<LocalizationToPlannerFrame> traffic_manager::LocalizationStage::planner_frame_b private
Definition at line 62 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
bool traffic_manager::LocalizationStage::planner_frame_selector private
Section keys to switch between the output data frames.
Definition at line 56 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
std::shared_ptr<LocalizationToPlannerMessenger> traffic_manager::LocalizationStage::planner_messenger private
Pointer to messenger to motion planner stage.
Definition at line 70 of file LocalizationStage.h.
Referenced by DataSender().
int traffic_manager::LocalizationStage::planner_messenger_state private
Variables to remember messenger states.
Definition at line 52 of file LocalizationStage.h.
Referenced by DataSender(), and LocalizationStage().
AtomicActorSet& traffic_manager::LocalizationStage::registered_actors private
Reference to set of all actors registered with the traffic manager.
Definition at line 76 of file LocalizationStage.h.
Referenced by DataReceiver().
int traffic_manager::LocalizationStage::registered_actors_state private
State counter to track changes in registered actors.
Definition at line 81 of file LocalizationStage.h.
Referenced by DataReceiver(), and LocalizationStage().
TrackTraffic traffic_manager::LocalizationStage::track_traffic private
Object for tracking paths of the traffic vehicles.
Definition at line 100 of file LocalizationStage.h.
Referenced by Action(), AssignLaneChange(), PopWaypoint(), and PushWaypoint().
std::shared_ptr<LocalizationToTrafficLightFrame> traffic_manager::LocalizationStage::traffic_light_frame_a private
Output data frames to be shared with the traffic light stage.
Definition at line 67 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<LocalizationToTrafficLightFrame> traffic_manager::LocalizationStage::traffic_light_frame_b private
Definition at line 68 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
bool traffic_manager::LocalizationStage::traffic_light_frame_selector private
Definition at line 59 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
std::shared_ptr<LocalizationToTrafficLightMessenger> traffic_manager::LocalizationStage::traffic_light_messenger private
Pointer to messenger to traffic light stage.
Definition at line 74 of file LocalizationStage.h.
Referenced by DataSender().
int traffic_manager::LocalizationStage::traffic_light_messenger_state private
Definition at line 54 of file LocalizationStage.h.
Referenced by DataSender(), and LocalizationStage().
std::unordered_map<ActorId, uint> traffic_manager::LocalizationStage::vehicle_id_to_index private
Map connecting actor ids to indices of data arrays.
Definition at line 92 of file LocalizationStage.h.
Referenced by Action(), AssignLaneChange(), and DataReceiver().
The documentation for this class was generated from the following files:
LocalizationStage.h
LocalizationStage.cpp