CARLA: test_msgpack.cpp File Reference
test_msgpack.cpp File Reference
#include "test.h"
#include <carla/MsgPackAdaptors.h>
#include <carla/rpc/Actor.h>
#include <carla/rpc/Response.h>
#include <thread>
Functions
TEST (msgpack, response)
TEST (msgpack, actor)
TEST (msgpack, variant)
TEST (msgpack, optional)
Function Documentation
TEST (msgpack , response)
Definition at line 17 of file test_msgpack.cpp.
References carla::rpc::Response< T >::Get(), carla::rpc::Response< T >::GetError(), carla::rpc::Response< T >::HasError(), carla::rpc::Response< T >::Reset(), carla::rpc::Response< T >::SetError(), and carla::rpc::ResponseError::What().
TEST (msgpack , actor)
Definition at line 56 of file test_msgpack.cpp.
References carla::rpc::Actor::bounding_box, carla::rpc::Actor::description, carla::rpc::Actor::id, carla::rpc::ActorDescription::id, and carla::rpc::ActorDescription::uid.
TEST (msgpack , variant)
Definition at line 74 of file test_msgpack.cpp.
TEST (msgpack , optional)
Definition at line 95 of file test_msgpack.cpp.