CARLA: carla_msgs::msg::CarlaEgoVehicleControlPubSubType Class Reference
carla_msgs::msg::CarlaEgoVehicleControlPubSubType Class Reference
This class represents the TopicDataType of the type CarlaEgoVehicleControl defined by the user in the IDL file.
#include <CarlaEgoVehicleControlPubSubTypes.h>
Public Types
typedef CarlaEgoVehicleControl type
Public Member Functions
eProsima_user_DllExport CarlaEgoVehicleControlPubSubType ()
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~CarlaEgoVehicleControlPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type CarlaEgoVehicleControl defined by the user in the IDL file.
Definition at line 45 of file CarlaEgoVehicleControlPubSubTypes.h.
Member Typedef Documentation
type
typedef CarlaEgoVehicleControl carla_msgs::msg::CarlaEgoVehicleControlPubSubType::type
Definition at line 49 of file CarlaEgoVehicleControlPubSubTypes.h.
Constructor & Destructor Documentation
CarlaEgoVehicleControlPubSubType()
carla_msgs::msg::CarlaEgoVehicleControlPubSubType::CarlaEgoVehicleControlPubSubType ()
Definition at line 32 of file CarlaEgoVehicleControlPubSubTypes.cpp.
References carla_msgs::msg::CarlaEgoVehicleControl::getKeyMaxCdrSerializedSize(), carla_msgs::msg::CarlaEgoVehicleControl::getMaxCdrSerializedSize(), carla_msgs::msg::CarlaEgoVehicleControl::isKeyDefined(), and m_keyBuffer.
~CarlaEgoVehicleControlPubSubType()
carla_msgs::msg::CarlaEgoVehicleControlPubSubType::~CarlaEgoVehicleControlPubSubType () override virtual
Definition at line 45 of file CarlaEgoVehicleControlPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * carla_msgs::msg::CarlaEgoVehicleControlPubSubType::createData () override virtual
Definition at line 122 of file CarlaEgoVehicleControlPubSubTypes.cpp.
deleteData()
void carla_msgs::msg::CarlaEgoVehicleControlPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file CarlaEgoVehicleControlPubSubTypes.cpp.
deserialize()
bool carla_msgs::msg::CarlaEgoVehicleControlPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file CarlaEgoVehicleControlPubSubTypes.cpp.
References carla_msgs::msg::CarlaEgoVehicleControl::deserialize().
getKey()
bool carla_msgs::msg::CarlaEgoVehicleControlPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file CarlaEgoVehicleControlPubSubTypes.cpp.
References carla_msgs::msg::CarlaEgoVehicleControl::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and carla_msgs::msg::CarlaEgoVehicleControl::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> carla_msgs::msg::CarlaEgoVehicleControlPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file CarlaEgoVehicleControlPubSubTypes.cpp.
References carla_msgs::msg::CarlaEgoVehicleControl::getCdrSerializedSize().
serialize()
bool carla_msgs::msg::CarlaEgoVehicleControlPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file CarlaEgoVehicleControlPubSubTypes.cpp.
References carla_msgs::msg::CarlaEgoVehicleControl::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* carla_msgs::msg::CarlaEgoVehicleControlPubSubType::m_keyBuffer
Definition at line 102 of file CarlaEgoVehicleControlPubSubTypes.h.
Referenced by CarlaEgoVehicleControlPubSubType(), getKey(), and ~CarlaEgoVehicleControlPubSubType().
m_md5
MD5 carla_msgs::msg::CarlaEgoVehicleControlPubSubType::m_md5
Definition at line 101 of file CarlaEgoVehicleControlPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
CarlaEgoVehicleControlPubSubTypes.h
CarlaEgoVehicleControlPubSubTypes.cpp