CARLA: carla::sensor::s11n::LidarRawSerializer Class Reference
carla::sensor::s11n::LidarRawSerializer Class Reference
Serializes the data generated by Lidar sensors.
#include <LidarRawSerializer.h>
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static LidarRawHeaderView DeserializeHeader (const RawData &data)
static size_t GetHeaderOffset (const RawData &data)
template<typename Sensor >
static Buffer Serialize (const Sensor &sensor, const data::LidarRawData &measurement, Buffer &&output)
Detailed Description
Serializes the data generated by Lidar sensors.
Definition at line 59 of file LidarRawSerializer.h.
Member Function Documentation
SharedPtr< SensorData > carla::sensor::s11n::LidarRawSerializer::Deserialize (RawData && data) static
Definition at line 14 of file LidarRawSerializer.cpp.
static LidarRawHeaderView carla::sensor::s11n::LidarRawSerializer::DeserializeHeader (const RawData & data) inline static
Definition at line 62 of file LidarRawSerializer.h.
References carla::sensor::RawData::begin().
Referenced by carla::sensor::data::LidarRawMeasurement::GetHeader().
static size_t carla::sensor::s11n::LidarRawSerializer::GetHeaderOffset (const RawData & data) inline static
Definition at line 66 of file LidarRawSerializer.h.
References PropAttributes::SIZE.
Referenced by carla::sensor::data::LidarRawMeasurement::LidarRawMeasurement().
template<typename Sensor > Buffer carla::sensor::s11n::LidarRawSerializer::Serialize (const Sensor & sensor, const data::LidarRawData & measurement, Buffer && output) inline static
Definition at line 85 of file LidarRawSerializer.h.
References carla::sensor::data::LidarRawData::_header, carla::sensor::data::LidarRawData::_ser_points, and carla::Buffer::copy_from().
The documentation for this class was generated from the following files:
LidarRawSerializer.h
LidarRawSerializer.cpp