CARLA: ActorRegistry.cpp File Reference
ActorRegistry.cpp File Reference
#include "Carla.h"
#include "Carla/Actor/ActorRegistry.h"
#include "Carla/Game/Tagger.h"
#include "Carla/Traffic/TrafficLightBase.h"
#include "Carla/Util/BoundingBoxCalculator.h"
#include "Carla/Sensor/Sensor.h"
Functions
static FCarlaActor::ActorType FActorRegistry_GetActorType (const AActor *Actor)
static FString GetRelevantTagAsString (const TSet< crp::CityObjectLabel > &SemanticTags)
Function Documentation
FActorRegistry_GetActorType()
static FCarlaActor::ActorType FActorRegistry_GetActorType (const AActor * Actor) static
Definition at line 21 of file ActorRegistry.cpp.
References FCarlaActor::INVALID, FCarlaActor::Other, FCarlaActor::Sensor, FCarlaActor::TrafficLight, FCarlaActor::TrafficSign, FCarlaActor::Vehicle, and FCarlaActor::Walker.
Referenced by FActorRegistry::MakeCarlaActor().
GetRelevantTagAsString()
static FString GetRelevantTagAsString (const TSet< crp::CityObjectLabel > & SemanticTags) static
Definition at line 54 of file ActorRegistry.cpp.
References ATagger::GetTagAsString(), carla::rpc::None, and carla::rpc::Other.
Referenced by FActorRegistry::MakeCarlaActor().