CARLA: carla::sensor::s11n::RadarData Class Reference
carla::sensor::s11n::RadarData Class Reference
#include <RadarData.h>
Public Member Functions
size_t GetDetectionCount () const
Returns the number of current detections.
RadarData & operator= (RadarData &&)=default
RadarData ()=default
void Reset ()
Deletes the current detections.
void SetResolution (uint32_t resolution)
Set a new resolution for the RadarData.
void WriteDetection (RadarDetection detection)
Adds a new detection.
Static Public Attributes
static constexpr auto detection_size = sizeof(RadarDetection)
Private Attributes
std::vector< RadarDetection > _detections
Friends
class RadarSerializer
Detailed Description
Definition at line 24 of file RadarData.h.
Constructor & Destructor Documentation
carla::sensor::s11n::RadarData::RadarData () explicit default
Member Function Documentation
size_t carla::sensor::s11n::RadarData::GetDetectionCount () const inline
Returns the number of current detections.
Definition at line 51 of file RadarData.h.
RadarData& carla::sensor::s11n::RadarData::operator= (RadarData &&) default
void carla::sensor::s11n::RadarData::Reset (void) inline
Deletes the current detections.
It doesn't change the resolution nor the allocated memory.
Definition at line 57 of file RadarData.h.
Referenced by ARadar::Tick().
void carla::sensor::s11n::RadarData::SetResolution (uint32_t resolution) inline
Set a new resolution for the RadarData.
Allocates / Deallocates space in memory if needed.
Warning
This is expensive, not to be called each tick!
Definition at line 42 of file RadarData.h.
Referenced by ARadar::SetPointsPerSecond().
void carla::sensor::s11n::RadarData::WriteDetection (RadarDetection detection) inline
Adds a new detection.
Definition at line 62 of file RadarData.h.
Referenced by ARadar::SendLineTraces().
Friends And Related Function Documentation
friend class RadarSerializer friend
Definition at line 25 of file RadarData.h.
Member Data Documentation
std::vector<RadarDetection> carla::sensor::s11n::RadarData::_detections private
Definition at line 68 of file RadarData.h.
Referenced by carla::sensor::s11n::RadarSerializer::Serialize().
constexpr auto carla::sensor::s11n::RadarData::detection_size = sizeof(RadarDetection) static
Definition at line 34 of file RadarData.h.
The documentation for this class was generated from the following file:
RadarData.h