CARLA: ATagger Class Reference
ATagger Class Reference
Sets actors' custom depth stencil value for semantic segmentation according to their meshes.
#include <Tagger.h>
Public Member Functions
ATagger ()
Static Public Member Functions
static FLinearColor GetActorLabelColor (const AActor &Actor, const crp::CityObjectLabel &Label)
static crp::CityObjectLabel GetLabelByFolderName (const FString &String)
Method that computes the label corresponding to a folder path.
template<typename T >
static crp::CityObjectLabel GetLabelByPath (const T *Object)
Method that computes the label corresponding to an specific object using the folder path in which it is stored.
static FString GetTagAsString (crp::CityObjectLabel Tag)
Retrieve the tags of an already tagged actor.
static crp::CityObjectLabel GetTagOfTaggedComponent (const UPrimitiveComponent &Component)
Retrieve the tag of an already tagged component.
static void GetTagsOfTaggedActor (const AActor &Actor, TSet< crp::CityObjectLabel > &Tags)
Retrieve the tags of an already tagged actor.
static bool IsThing (const crp::CityObjectLabel &Label)
static bool MatchComponent (const UPrimitiveComponent &Component, crp::CityObjectLabel Tag)
Return true if Component has been tagged with the given Tag.
static void SetStencilValue (UPrimitiveComponent &Component, const crp::CityObjectLabel &Label, const bool bSetRenderCustomDepth)
static void TagActor (const AActor &Actor, bool bTagForSemanticSegmentation)
Set the tag of an actor.
static void TagActorsInLevel (UWorld &World, bool bTagForSemanticSegmentation)
Set the tag of every actor in level.
static void TagActorsInLevel (ULevel &Level, bool bTagForSemanticSegmentation)
Private Attributes
bool bTagForSemanticSegmentation = false
bool bTriggerTagObjects = false
Detailed Description
Sets actors' custom depth stencil value for semantic segmentation according to their meshes.
Non-static functions present so it can be dropped into the scene for testing purposes.
Definition at line 26 of file Tagger.h.
Constructor & Destructor Documentation
ATagger()
ATagger::ATagger ()
Definition at line 288 of file Tagger.cpp.
References bTagForSemanticSegmentation, bTriggerTagObjects, and TagActorsInLevel().
Member Function Documentation
GetActorLabelColor()
FLinearColor ATagger::GetActorLabelColor (const AActor & Actor, const crp::CityObjectLabel & Label) static
Definition at line 80 of file Tagger.cpp.
References CastEnum().
Referenced by TagActor().
GetLabelByFolderName()
crp::CityObjectLabel ATagger::GetLabelByFolderName (const FString & String) static
Method that computes the label corresponding to a folder path.
Definition at line 26 of file Tagger.cpp.
References carla::rpc::None, carla::rpc::Other, carla::rpc::TrafficLight, and carla::rpc::TrafficSigns.
GetLabelByPath()
template<typename T > static crp::CityObjectLabel ATagger::GetLabelByPath (const T * Object) inline static
Method that computes the label corresponding to an specific object using the folder path in which it is stored.
Definition at line 77 of file Tagger.h.
References carla::rpc::None.
Referenced by TagActor().
GetTagAsString()
FString ATagger::GetTagAsString (crp::CityObjectLabel Tag) static
Retrieve the tags of an already tagged actor.
CityObjectLabel::None is not added to the array.
Definition at line 246 of file Tagger.cpp.
References CARLA_GET_LABEL_STR, Other, and TrafficLight.
Referenced by GetRelevantTagAsString(), UObjectRegister::RegisterTrafficLight(), and TagActor().
GetTagOfTaggedComponent()
static crp::CityObjectLabel ATagger::GetTagOfTaggedComponent (const UPrimitiveComponent & Component) inline static
Retrieve the tag of an already tagged component.
Definition at line 52 of file Tagger.h.
Referenced by URayTracer::CastRay(), ACarlaGameModeBase::EnableOverlapEvents(), UBoundingBoxCalculator::GetBBsOfActor(), UBoundingBoxCalculator::GetBBsOfSkeletalMeshComponents(), UBoundingBoxCalculator::GetBBsOfStaticMeshComponents(), GetTagsOfTaggedActor(), UBoundingBoxCalculator::GetVehicleBoundingBox(), URayTracer::ProjectPoint(), UObjectRegister::RegisterISMComponents(), and UObjectRegister::RegisterVehicle().
GetTagsOfTaggedActor()
void ATagger::GetTagsOfTaggedActor (const AActor & Actor, TSet< crp::CityObjectLabel > & Tags) static
Retrieve the tags of an already tagged actor.
CityObjectLabel::None is not added to the array.
Definition at line 232 of file Tagger.cpp.
References GetTagOfTaggedComponent(), and carla::rpc::None.
Referenced by FActorRegistry::MakeCarlaActor(), and UCarlaEpisode::SerializeActor().
IsThing()
bool ATagger::IsThing (const crp::CityObjectLabel & Label) static
Definition at line 67 of file Tagger.cpp.
References carla::rpc::TrafficLight, and carla::rpc::TrafficSigns.
MatchComponent()
static bool ATagger::MatchComponent (const UPrimitiveComponent & Component, crp::CityObjectLabel Tag) inline static
Return true if Component has been tagged with the given Tag.
Definition at line 62 of file Tagger.h.
References String.
Referenced by LineTrace().
SetStencilValue()
void ATagger::SetStencilValue (UPrimitiveComponent & Component, const crp::CityObjectLabel & Label, const bool bSetRenderCustomDepth) static
Definition at line 57 of file Tagger.cpp.
References CastEnum(), and carla::rpc::None.
Referenced by TagActor().
TagActor()
void ATagger::TagActor (const AActor & Actor, bool bTagForSemanticSegmentation) static
Set the tag of an actor.
If bTagForSemanticSegmentation true, activate the custom depth pass. This pass is necessary for rendering the semantic segmentation. However, it may add a performance penalty since occlusion doesn't seem to be applied to objects having this value active.
Definition at line 100 of file Tagger.cpp.
References GetActorLabelColor(), GetLabelByPath(), GetTagAsString(), IsValid(), UTaggedComponent::SetColor(), and SetStencilValue().
Referenced by UTaggerDelegate::OnActorSpawned(), UActorDispatcher::SpawnActor(), and TagActorsInLevel().
TagActorsInLevel() [1/2]
void ATagger::TagActorsInLevel (UWorld & World, bool bTagForSemanticSegmentation) static
Set the tag of every actor in level.
If bTagForSemanticSegmentation true, activate the custom depth pass. This pass is necessary for rendering the semantic segmentation. However, it may add a performance penalty since occlusion doesn't seem to be applied to objects having this value active.
Definition at line 218 of file Tagger.cpp.
References TagActor().
Referenced by ATagger(), ACarlaGameModeBase::BeginPlay(), ACityMapGenerator::GenerateRoadMap(), ALargeMapManager::OnLevelAddedToWorld(), and ACarlaGameModeBase::OnLoadStreamLevel().
TagActorsInLevel() [2/2]
void ATagger::TagActorsInLevel (ULevel & Level, bool bTagForSemanticSegmentation) static
Definition at line 225 of file Tagger.cpp.
References TagActor().
Member Data Documentation
bTagForSemanticSegmentation
bool ATagger::bTagForSemanticSegmentation = false private
Definition at line 105 of file Tagger.h.
Referenced by ATagger().
bTriggerTagObjects
bool ATagger::bTriggerTagObjects = false private
Definition at line 102 of file Tagger.h.
Referenced by ATagger().
The documentation for this class was generated from the following files:
Tagger.h
Tagger.cpp