CARLA: AWeather Class Reference
AWeather Class Reference
#include <Weather.h>
Public Member Functions
void ApplyWeather (const FWeatherParameters &WeatherParameters)
Update the weather parameters and notifies it to the blueprint's event.
AWeather (const FObjectInitializer &ObjectInitializer)
const FWeatherParameters & GetCurrentWeather () const
Returns the current WeatherParameters.
const bool & GetDayNightCycle () const
Returns whether the day night cycle is active (automatic on/off switch when changin to night mode)
void NotifyWeather (ASensor *Sensor=nullptr)
Notifing the weather to the blueprint's event.
void SetDayNightCycle (const bool &active)
Update the day night cycle.
void SetWeather (const FWeatherParameters &WeatherParameters)
Update the weather parameters without notifing it to the blueprint's event.
Protected Member Functions
void RefreshWeather (const FWeatherParameters &WeatherParameters)
Private Member Functions
void CheckWeatherPostProcessEffects ()
Private Attributes
TMap< UMaterial *, float > ActiveBlendables
bool DayNightCycle = true
UMaterial * DustStormPostProcessMaterial
UMaterial * PrecipitationPostProcessMaterial
TArray< ASceneCaptureCamera * > Sensors
FWeatherParameters Weather
Detailed Description
Definition at line 18 of file Weather.h.
Constructor & Destructor Documentation
AWeather()
AWeather::AWeather (const FObjectInitializer & ObjectInitializer)
Definition at line 14 of file Weather.cpp.
References DustStormPostProcessMaterial, and PrecipitationPostProcessMaterial.
Member Function Documentation
ApplyWeather()
void AWeather::ApplyWeather (const FWeatherParameters & WeatherParameters)
Update the weather parameters and notifies it to the blueprint's event.
Definition at line 55 of file Weather.cpp.
References CheckWeatherPostProcessEffects(), FWeatherParameters::Cloudiness, FWeatherParameters::DustStorm, FWeatherParameters::FogDensity, FWeatherParameters::FogDistance, FWeatherParameters::FogFalloff, FWeatherParameters::MieScatteringScale, FWeatherParameters::Precipitation, FWeatherParameters::PrecipitationDeposits, FWeatherParameters::RayleighScatteringScale, RefreshWeather(), FWeatherParameters::ScatteringIntensity, SetWeather(), FWeatherParameters::SunAltitudeAngle, FWeatherParameters::SunAzimuthAngle, Weather, FWeatherParameters::Wetness, and FWeatherParameters::WindIntensity.
Referenced by ACarlaGameModeBase::BeginPlay().
CheckWeatherPostProcessEffects()
void AWeather::CheckWeatherPostProcessEffects () private
Definition at line 27 of file Weather.cpp.
References ActiveBlendables, FWeatherParameters::DustStorm, DustStormPostProcessMaterial, IsValid(), FWeatherParameters::Precipitation, PrecipitationPostProcessMaterial, Sensors, and Weather.
Referenced by ApplyWeather(), and NotifyWeather().
GetCurrentWeather()
const FWeatherParameters& AWeather::GetCurrentWeather () const inline
Returns the current WeatherParameters.
Definition at line 39 of file Weather.h.
GetDayNightCycle()
const bool& AWeather::GetDayNightCycle () const inline
Returns whether the day night cycle is active (automatic on/off switch when changin to night mode)
Definition at line 46 of file Weather.h.
NotifyWeather()
void AWeather::NotifyWeather (ASensor * Sensor = nullptr)
Notifing the weather to the blueprint's event.
Definition at line 82 of file Weather.cpp.
References CheckWeatherPostProcessEffects(), RefreshWeather(), Sensors, and Weather.
Referenced by ASceneCaptureSensor::BeginPlay().
RefreshWeather()
void AWeather::RefreshWeather (const FWeatherParameters & WeatherParameters) protected
Referenced by ApplyWeather(), and NotifyWeather().
SetDayNightCycle()
void AWeather::SetDayNightCycle (const bool & active)
Update the day night cycle.
Definition at line 99 of file Weather.cpp.
References DayNightCycle.
SetWeather()
void AWeather::SetWeather (const FWeatherParameters & WeatherParameters)
Update the weather parameters without notifing it to the blueprint's event.
Definition at line 94 of file Weather.cpp.
References Weather.
Referenced by ApplyWeather().
Member Data Documentation
ActiveBlendables
TMap<UMaterial*, float> AWeather::ActiveBlendables private
Definition at line 70 of file Weather.h.
Referenced by CheckWeatherPostProcessEffects().
DayNightCycle
bool AWeather::DayNightCycle = true private
Definition at line 76 of file Weather.h.
Referenced by SetDayNightCycle().
DustStormPostProcessMaterial
UMaterial* AWeather::DustStormPostProcessMaterial private
Definition at line 68 of file Weather.h.
Referenced by AWeather(), and CheckWeatherPostProcessEffects().
PrecipitationPostProcessMaterial
UMaterial* AWeather::PrecipitationPostProcessMaterial private
Definition at line 66 of file Weather.h.
Referenced by AWeather(), and CheckWeatherPostProcessEffects().
Sensors
TArray<ASceneCaptureCamera*> AWeather::Sensors private
Definition at line 73 of file Weather.h.
Referenced by CheckWeatherPostProcessEffects(), and NotifyWeather().
Weather
FWeatherParameters AWeather::Weather private
Definition at line 64 of file Weather.h.
Referenced by ApplyWeather(), CheckWeatherPostProcessEffects(), NotifyWeather(), and SetWeather().
The documentation for this class was generated from the following files:
Weather.h
Weather.cpp