CARLA: ULoadAssetMaterialsCommandlet Class Reference
ULoadAssetMaterialsCommandlet Class Reference
#include <LoadAssetMaterialsCommandlet.h>
Public Member Functions
ULoadAssetMaterialsCommandlet ()
Default constructor.
Private Member Functions
FString GetFirstPackagePath (const FString &PackageName) const
Gets the first .Package.json file found in Unreal Content Directory with PackageName.
Private Attributes
TArray< FAssetData > AssetDatas
Loaded assets from any object library.
TMap< FString, FString > DecalNamesMap
Dictionary for translating the JSON file "decal_names" array to already loaded Material Instances, which are used to apply on the roads.
FDecalsProperties DecalsProperties
bool FilledData
UObjectLibrary * MapObjectLibrary
Used for loading maps in object library.
UWorld * NewWorldToLoad
bool ReadConfigFile
TSubclassOf< ARoadPainterWrapper > RoadPainterSubclass
Subclass for acquiring the RoadPainter blueprint.
FLargeMapTileData TileData
UWorld * World
boost::optional< carla::road::Map > XODRMap
Detailed Description
Definition at line 42 of file LoadAssetMaterialsCommandlet.h.
Constructor & Destructor Documentation
ULoadAssetMaterialsCommandlet()
ULoadAssetMaterialsCommandlet::ULoadAssetMaterialsCommandlet ()
Default constructor.
Definition at line 23 of file LoadAssetMaterialsCommandlet.cpp.
References AssetDatas, FMapData::bUseCarlaMapMaterials, FDecalsProperties::DecalMaterials, FDecalsProperties::DecalMaxScale, FDecalsProperties::DecalMinScale, DecalNamesMap, FDecalsProperties::DecalNumToSpawn, FDecalsProperties::DecalRandomYaw, FDecalsProperties::DecalScale, DecalsProperties, FilledData, FLargeMapTileData::FirstTileCenterX, FLargeMapTileData::FirstTileCenterY, FDecalsProperties::FixedDecalOffset, carla::client::detail::Get(), GetFirstPackagePath(), carla::opendrive::OpenDriveParser::Load(), UOpenDrive::LoadXODR(), MapObjectLibrary, FAssetsPaths::MapsPaths, FPackageParams::Name, FMapData::Name, FMapData::Path, FAssetsPaths::PropsPaths, FDecalsProperties::RandomOffset, ReadConfigFile, RoadPainterSubclass, FLargeMapTileData::Size, TileData, World, carla::geom::Vector3D::x, XODRMap, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Member Function Documentation
GetFirstPackagePath()
FString ULoadAssetMaterialsCommandlet::GetFirstPackagePath (const FString & PackageName) const private
Gets the first .Package.json file found in Unreal Content Directory with PackageName.
Referenced by ULoadAssetMaterialsCommandlet().
Member Data Documentation
AssetDatas
TArray<FAssetData> ULoadAssetMaterialsCommandlet::AssetDatas private
Loaded assets from any object library.
Definition at line 77 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
DecalNamesMap
TMap<FString, FString> ULoadAssetMaterialsCommandlet::DecalNamesMap private
Dictionary for translating the JSON file "decal_names" array to already loaded Material Instances, which are used to apply on the roads.
Definition at line 97 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
DecalsProperties
FDecalsProperties ULoadAssetMaterialsCommandlet::DecalsProperties private
Definition at line 110 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
FilledData
bool ULoadAssetMaterialsCommandlet::FilledData private
Definition at line 112 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
MapObjectLibrary
UObjectLibrary* ULoadAssetMaterialsCommandlet::MapObjectLibrary private
Used for loading maps in object library.
Loaded Data is stored in AssetDatas.
Definition at line 88 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
NewWorldToLoad
UWorld* ULoadAssetMaterialsCommandlet::NewWorldToLoad private
Definition at line 83 of file LoadAssetMaterialsCommandlet.h.
ReadConfigFile
bool ULoadAssetMaterialsCommandlet::ReadConfigFile private
Definition at line 114 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
RoadPainterSubclass
TSubclassOf<ARoadPainterWrapper> ULoadAssetMaterialsCommandlet::RoadPainterSubclass private
Subclass for acquiring the RoadPainter blueprint.
Definition at line 92 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
TileData
FLargeMapTileData ULoadAssetMaterialsCommandlet::TileData private
Definition at line 108 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
World
UWorld* ULoadAssetMaterialsCommandlet::World private
Definition at line 80 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
XODRMap
boost::optional<carla::road::Map> ULoadAssetMaterialsCommandlet::XODRMap private
Definition at line 102 of file LoadAssetMaterialsCommandlet.h.
Referenced by ULoadAssetMaterialsCommandlet().
The documentation for this class was generated from the following files:
LoadAssetMaterialsCommandlet.h
LoadAssetMaterialsCommandlet.cpp