CARLA: BoundingBoxCalculator.cpp File Reference
BoundingBoxCalculator.cpp File Reference
#include "Carla.h"
#include "Carla/Game/Tagger.h"
#include "Carla/Util/BoundingBoxCalculator.h"
#include "Carla/Traffic/TrafficSignBase.h"
#include "Carla/Vehicle/CarlaWheeledVehicle.h"
#include "Carla/Traffic/TrafficLightBase.h"
#include <compiler/disable-ue4-macros.h>
#include <carla/rpc/ObjectLabel.h>
#include <compiler/enable-ue4-macros.h>
#include "Components/CapsuleComponent.h"
#include "GameFramework/Character.h"
#include "Components/BoxComponent.h"
#include "Rendering/SkeletalMeshRenderData.h"
#include "Engine/SkeletalMeshSocket.h"
Functions
static FBoundingBox ApplyTransformToBB (const FBoundingBox &InBoundingBox, const FTransform &Transform)
Function Documentation
ApplyTransformToBB()
static FBoundingBox ApplyTransformToBB (const FBoundingBox & InBoundingBox, const FTransform & Transform) static
Definition at line 29 of file BoundingBoxCalculator.cpp.
References BoundingBox, FBoundingBox::Extent, FBoundingBox::Origin, and FBoundingBox::Rotation.
Referenced by UBoundingBoxCalculator::GetBBsOfSkeletalMeshComponents(), UBoundingBoxCalculator::GetBBsOfStaticMeshComponents(), UBoundingBoxCalculator::GetCharacterBoundingBox(), UBoundingBoxCalculator::GetISMBoundingBox(), and UBoundingBoxCalculator::GetVehicleBoundingBox().