CARLA: carla::streaming Namespace Reference
carla::streaming Namespace Reference
Namespaces
detail
low_level
Classes
class Client
A client able to subscribe to multiple streams.
class Server
A streaming server.
class Token
A token that uniquely identify a stream.
Typedefs
using Stream = detail::Stream< detail::MultiStreamState >
A stream represents an unidirectional channel for sending data from server to client.
using stream_token = detail::token_type
Functions
static auto make_address (const std::string &address)
template<typename Protocol >
static auto make_endpoint (boost::asio::ip::basic_endpoint< Protocol > ep)
template<typename Protocol >
static auto make_endpoint (const char *address, uint16_t port)
template<typename Protocol >
static auto make_endpoint (const std::string &address, uint16_t port)
template<typename Protocol >
static auto make_endpoint (uint16_t port)
static auto make_localhost_address ()
Typedef Documentation
using carla::streaming::Stream = typedef detail::Stream<detail::MultiStreamState>
A stream represents an unidirectional channel for sending data from server to client.
Multiple clients can subscribe to this stream using the stream token. If no client is subscribed, the data flushed down the stream is discarded.
Definition at line 19 of file Stream.h.
using carla::streaming::stream_token = typedef detail::token_type
Definition at line 20 of file streaming/Client.h.
Function Documentation
static auto carla::streaming::make_address (const std::string & address) inline static
Definition at line 75 of file EndPoint.h.
Referenced by make_endpoint(), and make_localhost_address().
template<typename Protocol > static auto carla::streaming::make_endpoint (boost::asio::ip::basic_endpoint< Protocol > ep) inline static
Definition at line 90 of file EndPoint.h.
template<typename Protocol > static auto carla::streaming::make_endpoint (const char * address, uint16_t port) inline static
Definition at line 95 of file EndPoint.h.
References make_address().
template<typename Protocol > static auto carla::streaming::make_endpoint (const std::string & address, uint16_t port) inline static
Definition at line 100 of file EndPoint.h.
template<typename Protocol > static auto carla::streaming::make_endpoint (uint16_t port) inline static
Definition at line 105 of file EndPoint.h.
static auto carla::streaming::make_localhost_address () inline static
Definition at line 71 of file EndPoint.h.
References make_address().