CARLA: carla::client::detail::ActorState Class Reference
carla::client::detail::ActorState Class Reference
Internal state of an Actor.
#include <ActorState.h>
Public Member Functions
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Protected Member Functions
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Private Attributes
std::vector< ActorAttributeValue > _attributes
rpc::Actor _description
std::string _display_id
EpisodeProxy _episode
Friends
class Simulator
Additional Inherited Members
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Detailed Description
Internal state of an Actor.
Definition at line 22 of file ActorState.h.
Constructor & Destructor Documentation
carla::client::detail::ActorState::ActorState (rpc::Actor description, EpisodeProxy episode) explicit protected
Referenced by GetAttributes().
Member Function Documentation
const rpc::Actor& carla::client::detail::ActorState::GetActorDescription () const inline protected
Definition at line 64 of file ActorState.h.
References _description.
Referenced by carla::client::Actor::Serialize(), carla::client::detail::Simulator::SubscribeToSensor(), and carla::client::detail::Simulator::UnSubscribeFromSensor().
const std::vector<ActorAttributeValue>& carla::client::detail::ActorState::GetAttributes () const inline
Definition at line 51 of file ActorState.h.
References _attributes, and ActorState().
const geom::BoundingBox& carla::client::detail::ActorState::GetBoundingBox () const inline protected
Definition at line 60 of file ActorState.h.
References _description, and carla::rpc::Actor::bounding_box.
Referenced by carla::traffic_manager::DeviationDotProduct(), carla::traffic_manager::CollisionStage::GetGeodesicBoundary(), carla::rss::RssCheck::getVehicleBounds(), and carla::traffic_manager::CollisionStage::NegotiateCollision().
const std::string& carla::client::detail::ActorState::GetDisplayId () const inline
Definition at line 33 of file ActorState.h.
References _display_id.
Referenced by carla::client::Actor::Destroy(), carla::client::detail::Simulator::DestroyActor(), carla::client::ServerSideSensor::Listen(), carla::client::RssSensor::Listen(), carla::client::detail::Simulator::RegisterAIController(), carla::client::ServerSideSensor::Stop(), carla::client::detail::Simulator::UnregisterAIController(), and carla::client::ServerSideSensor::~ServerSideSensor().
EpisodeProxy& carla::client::detail::ActorState::GetEpisode () inline protected
Definition at line 68 of file ActorState.h.
References _episode.
Referenced by carla::client::Actor::AddImpulse(), carla::client::Walker::ApplyControl(), carla::client::Vehicle::ApplyControl(), carla::client::Vehicle::ApplyPhysicsControl(), carla::client::Actor::Destroy(), carla::client::detail::Simulator::DestroyActor(), carla::client::TrafficLight::Freeze(), carla::client::Actor::GetAcceleration(), carla::client::Actor::GetAngularVelocity(), carla::client::Vehicle::GetControl(), carla::client::TrafficLight::GetElapsedTime(), carla::client::TrafficLight::GetGreenTime(), carla::client::TrafficLight::GetGroupTrafficLights(), carla::client::Vehicle::GetLightState(), carla::client::Actor::GetLocation(), carla::client::Vehicle::GetPhysicsControl(), carla::client::TrafficLight::GetPoleIndex(), carla::client::WalkerAIController::GetRandomLocation(), carla::client::TrafficLight::GetRedTime(), carla::client::Vehicle::GetSpeedLimit(), carla::client::TrafficLight::GetState(), carla::client::Vehicle::GetTrafficLight(), carla::client::Vehicle::GetTrafficLightState(), carla::client::Actor::GetTransform(), carla::client::Actor::GetVelocity(), carla::client::Walker::GetWalkerControl(), carla::client::TrafficLight::GetYellowTime(), carla::client::WalkerAIController::GoToLocation(), carla::client::Actor::IsAlive(), carla::client::Vehicle::IsAtTrafficLight(), carla::client::TrafficLight::IsFrozen(), carla::client::ServerSideSensor::Listen(), carla::client::RssSensor::Listen(), carla::client::Actor::SetAngularVelocity(), carla::client::TrafficLight::SetGreenTime(), carla::client::Vehicle::SetLightState(), carla::client::Actor::SetLocation(), carla::client::WalkerAIController::SetMaxSpeed(), carla::client::TrafficLight::SetRedTime(), carla::client::Actor::SetSimulatePhysics(), carla::client::TrafficLight::SetState(), carla::client::Actor::SetTransform(), carla::client::Actor::SetVelocity(), carla::client::TrafficLight::SetYellowTime(), carla::client::WalkerAIController::Start(), carla::client::WalkerAIController::Stop(), carla::client::ServerSideSensor::Stop(), and carla::client::ServerSideSensor::~ServerSideSensor().
const EpisodeProxy& carla::client::detail::ActorState::GetEpisode () const inline protected
Definition at line 72 of file ActorState.h.
References _episode.
ActorId carla::client::detail::ActorState::GetId () const inline
Definition at line 25 of file ActorState.h.
References _description, and carla::rpc::Actor::id.
Referenced by carla::client::detail::Simulator::AddActorImpulse(), carla::client::detail::Simulator::ApplyBoneControlToWalker(), carla::client::detail::Simulator::ApplyControlToVehicle(), carla::client::detail::Simulator::ApplyControlToWalker(), carla::client::detail::Simulator::ApplyPhysicsControlToVehicle(), carla::client::detail::Simulator::DestroyActor(), carla::client::detail::Simulator::FreezeTrafficLight(), carla::client::detail::Simulator::GetActorSnapshot(), carla::client::detail::Simulator::GetGroupTrafficLights(), carla::client::detail::Simulator::GetVehicleLightState(), carla::client::detail::Simulator::GetVehiclePhysicsControl(), carla::client::detail::Simulator::RegisterAIController(), carla::client::detail::Simulator::SetActorAngularVelocity(), carla::client::detail::Simulator::SetActorLocation(), carla::client::detail::Simulator::SetActorSimulatePhysics(), carla::client::detail::Simulator::SetActorTransform(), carla::client::detail::Simulator::SetActorVelocity(), carla::client::detail::Simulator::SetLightStateToVehicle(), carla::client::detail::Simulator::SetLightsToVehicle(), carla::client::detail::Simulator::SetTrafficLightGreenTime(), carla::client::detail::Simulator::SetTrafficLightRedTime(), carla::client::detail::Simulator::SetTrafficLightState(), carla::client::detail::Simulator::SetTrafficLightYellowTime(), carla::client::detail::Simulator::SetVehicleAutopilot(), carla::client::detail::Simulator::SpawnActor(), and carla::client::detail::Simulator::UnregisterAIController().
SharedPtr< Actor > carla::client::detail::ActorState::GetParent () const
Definition at line 31 of file ActorState.cpp.
Referenced by GetSemanticTags(), carla::client::WalkerAIController::GoToLocation(), carla::client::RssSensor::Listen(), carla::client::detail::Simulator::RegisterAIController(), carla::client::WalkerAIController::SetMaxSpeed(), carla::client::WalkerAIController::Start(), carla::client::WalkerAIController::Stop(), carla::client::RssSensor::TickRssSensor(), and carla::client::detail::Simulator::UnregisterAIController().
ActorId carla::client::detail::ActorState::GetParentId () const inline
Definition at line 37 of file ActorState.h.
References _description, and carla::rpc::Actor::parent_id.
const std::vector<uint8_t>& carla::client::detail::ActorState::GetSemanticTags () const inline
Definition at line 41 of file ActorState.h.
References _description, GetParent(), and carla::rpc::Actor::semantic_tags.
const std::string& carla::client::detail::ActorState::GetTypeId () const inline
Definition at line 29 of file ActorState.h.
References _description, carla::rpc::Actor::description, and carla::rpc::ActorDescription::id.
World carla::client::detail::ActorState::GetWorld () const inline
Definition at line 47 of file ActorState.h.
References _episode.
Referenced by carla::client::TrafficLight::GetGroupTrafficLights(), carla::client::Vehicle::GetTrafficLight(), carla::client::RssSensor::Listen(), and carla::client::RssSensor::TickRssSensor().
Friends And Related Function Documentation
friend class Simulator friend
Definition at line 78 of file ActorState.h.
Member Data Documentation
std::vector<ActorAttributeValue> carla::client::detail::ActorState::_attributes private
Definition at line 86 of file ActorState.h.
Referenced by GetAttributes().
rpc::Actor carla::client::detail::ActorState::_description private
Definition at line 80 of file ActorState.h.
Referenced by GetActorDescription(), GetBoundingBox(), GetId(), GetParentId(), GetSemanticTags(), and GetTypeId().
std::string carla::client::detail::ActorState::_display_id private
Definition at line 84 of file ActorState.h.
Referenced by GetDisplayId().
EpisodeProxy carla::client::detail::ActorState::_episode private
Definition at line 82 of file ActorState.h.
Referenced by GetEpisode(), and GetWorld().
The documentation for this class was generated from the following files:
ActorState.h
ActorState.cpp