CARLA: carla::client::RssSensor Class Reference
carla::client::RssSensor Class Reference
The RSS Sensor class implementing the carla::client::Sensor interface This class is a proxy to the RssCheck class.
#include <RssSensor.h>
Public Types
using ActorConstellationCallbackFunctionType = std::function<::carla::rss::ActorConstellationResult(carla::SharedPtr<::carla::rss::ActorConstellationData >)>
Public Types inherited from carla::client::Sensor
using CallbackFunctionType = std::function< void(SharedPtr< sensor::SensorData >)>
Public Member Functions
void AppendRoutingTarget (const ::carla::geom::Transform &routing_target)
appends a routing target to the current routing target list (
void DropRoute ()
drop the current route (
const ::ad::rss::world::RssDynamics & GetEgoVehicleDynamics () const
const ::ad::rss::world::RssDynamics & GetOtherVehicleDynamics () const
const ::ad::rss::world::RssDynamics & GetPedestrianDynamics () const
const ::carla::rss::RoadBoundariesMode & GetRoadBoundariesMode () const
const std::vector<::carla::geom::Transform > GetRoutingTargets () const
bool IsListening () const override
Return whether this Sensor instance is currently listening to the associated sensor in the simulator.
void Listen (CallbackFunctionType callback) override
Register a callback to be executed each time a new measurement is received.
void RegisterActorConstellationCallback (ActorConstellationCallbackFunctionType callback)
Register a callback to be executed for each actor within each measurement to be processed to decide on the operation of the RSS sensor in respect to the ego vehicle to actor constellation.
void ResetRoutingTargets ()
resets the current routing target (
RssSensor (ActorInitializer init)
constructor
void SetEgoVehicleDynamics (const ::ad::rss::world::RssDynamics &ego_dynamics)
sets the ego vehicle dynamics to be used by the ego vehicle (
void SetLogLevel (const uint8_t &log_level)
sets the current log level
void SetMapLogLevel (const uint8_t &map_log_level)
sets the current map log level
void SetOtherVehicleDynamics (const ::ad::rss::world::RssDynamics &other_vehicle_dynamics)
sets the ego vehicle dynamics to be used by other vehicles (
void SetPedestrianDynamics (const ::ad::rss::world::RssDynamics &pedestrian_dynamics)
sets the ego vehicle dynamics to be used by pedestrians (
void SetRoadBoundariesMode (const ::carla::rss::RoadBoundariesMode &road_boundaries_mode)
sets the current mode for respecting the road boundaries (
void Stop () override
Stop listening for new measurements.
~RssSensor ()
destructor
Public Member Functions inherited from carla::client::Actor
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddForce (const geom::Vector3D &force)
Add force to the actor at its center of mass.
void AddForce (const geom::Vector3D &force, const geom::Vector3D &location)
Add force to the actor at certain location.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor at its center of mass.
void AddImpulse (const geom::Vector3D &impulse, const geom::Vector3D &location)
Add impulse to the actor at certain location.
void AddTorque (const geom::Vector3D &vector)
Add a torque to the actor.
virtual bool Destroy ()
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
void DisableConstantVelocity ()
Disable the constant velocity mode.
void EnableConstantVelocity (const geom::Vector3D &vector)
Enable a constant velocity mode.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
geom::Location GetLocation () const
Return the current location of the actor.
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsAlive () const
const auto & Serialize () const
void SetEnableGravity (bool enabled=true)
Enable or disable gravity on this actor.
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTargetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor before applying physics.
void SetTargetVelocity (const geom::Vector3D &vector)
Set the actor velocity before applying physics.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Private Member Functions
SharedPtr< sensor::SensorData > TickRssSensor (const Timestamp &timestamp)
the acutal sensor tick callback function
Private Attributes
bool _drop_route
reqired to store DropRoute() requests until next sensor tick
std::size_t _last_processed_frame
last processed frame
std::size_t _on_tick_register_id
the id got when registering for the on tick event
std::mutex _processing_lock
the mutex to protect the actual RSS processing and in case it takes too long to process ever frame
ActorConstellationCallbackFunctionType _rss_actor_constellation_callback
std::shared_ptr<::carla::rss::RssCheck > _rss_check
Additional Inherited Members
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Detailed Description
The RSS Sensor class implementing the carla::client::Sensor interface This class is a proxy to the RssCheck class.
Definition at line 42 of file LibCarla/source/carla/rss/RssSensor.h.
Member Typedef Documentation
ActorConstellationCallbackFunctionType
using carla::client::RssSensor::ActorConstellationCallbackFunctionType = std::function<::carla::rss::ActorConstellationResult(carla::SharedPtr<::carla::rss::ActorConstellationData>)>
Definition at line 47 of file LibCarla/source/carla/rss/RssSensor.h.
Constructor & Destructor Documentation
RssSensor()
carla::client::RssSensor::RssSensor (ActorInitializer init) explicit
constructor
Definition at line 25 of file LibCarla/source/carla/rss/RssSensor.cpp.
~RssSensor()
carla::client::RssSensor::~RssSensor ()
destructor
Definition at line 27 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _processing_lock, and _rss_check.
Member Function Documentation
AppendRoutingTarget()
void carla::client::RssSensor::AppendRoutingTarget (const ::carla::geom::Transform & routing_target)
appends a routing target to the current routing target list (
See also
also RssCheck::AppendRoutingTarget())
Definition at line 239 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
DropRoute()
void carla::client::RssSensor::DropRoute ()
drop the current route (
See also
also RssCheck::DropRoute())
Definition at line 266 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _drop_route.
GetEgoVehicleDynamics()
const ::ad::rss::world::RssDynamics & carla::client::RssSensor::GetEgoVehicleDynamics () const
Returns
the currently used dynamics of the ego vehicle (
See also
also RssCheck::GetEgoVehicleDynamics())
Definition at line 133 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, _rss_check, carla::rss::RssCheck::GetDefaultVehicleDynamics(), carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
GetOtherVehicleDynamics()
const ::ad::rss::world::RssDynamics & carla::client::RssSensor::GetOtherVehicleDynamics () const
Returns
the currently used dynamics of other vehicles (
See also
also RssCheck::GetOtherVehicleDynamics())
Definition at line 162 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, _rss_check, carla::rss::RssCheck::GetDefaultVehicleDynamics(), carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
GetPedestrianDynamics()
const ::ad::rss::world::RssDynamics & carla::client::RssSensor::GetPedestrianDynamics () const
Returns
the currently used dynamics of pedestrians (
See also
also RssCheck::GetPedestrianDynamics())
Definition at line 191 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, _rss_check, carla::rss::RssCheck::GetDefaultPedestrianDynamics(), carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
GetRoadBoundariesMode()
const ::carla::rss::RoadBoundariesMode & carla::client::RssSensor::GetRoadBoundariesMode () const
Returns
the current mode for respecting the road boundaries (
See also
also RssCheck::GetRoadBoundariesMode())
Definition at line 220 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::rss::RssCheck::GetDefaultRoadBoundariesMode(), carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
GetRoutingTargets()
const std::vector<::carla::geom::Transform > carla::client::RssSensor::GetRoutingTargets () const
Returns
the current routing targets (
See also
also RssCheck::GetRoutingTargets())
Definition at line 248 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
IsListening()
bool carla::client::RssSensor::IsListening () const inline override virtual
Return whether this Sensor instance is currently listening to the associated sensor in the simulator.
Implements carla::client::Sensor.
Definition at line 73 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by Listen(), RegisterActorConstellationCallback(), and Stop().
Listen()
void carla::client::RssSensor::Listen (CallbackFunctionType callback) override virtual
Register a callback to be executed each time a new measurement is received.
Warning
Calling this function on a sensor that is already listening steals the data stream from the previously set callback. Note that several instances of Sensor (even in different processes) may point to the same sensor in the simulator.
Implements carla::client::Sensor.
Definition at line 43 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _on_tick_register_id, _rss_actor_constellation_callback, _rss_check, DEBUG_ASSERT, carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), carla::client::World::GetMap(), carla::client::detail::ActorState::GetParent(), carla::client::detail::ActorState::GetWorld(), IsListening(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::log_debug(), carla::log_error(), and carla::throw_exception().
RegisterActorConstellationCallback()
void carla::client::RssSensor::RegisterActorConstellationCallback (ActorConstellationCallbackFunctionType callback)
Register a callback to be executed for each actor within each measurement to be processed to decide on the operation of the RSS sensor in respect to the ego vehicle to actor constellation.
Definition at line 33 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, carla::client::detail::ActorState::GetDisplayId(), IsListening(), and carla::log_error().
ResetRoutingTargets()
void carla::client::RssSensor::ResetRoutingTargets ()
resets the current routing target (
See also
also RssCheck::ResetRoutingTargets())
Definition at line 257 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
SetEgoVehicleDynamics()
void carla::client::RssSensor::SetEgoVehicleDynamics (const ::ad::rss::world::RssDynamics & ego_dynamics)
sets the ego vehicle dynamics to be used by the ego vehicle (
See also
also RssCheck::SetEgoVehicleDynamics())
Definition at line 148 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
SetLogLevel()
void carla::client::RssSensor::SetLogLevel (const uint8_t & log_level)
sets the current log level
Definition at line 111 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
SetMapLogLevel()
void carla::client::RssSensor::SetMapLogLevel (const uint8_t & map_log_level)
sets the current map log level
Definition at line 122 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
SetOtherVehicleDynamics()
void carla::client::RssSensor::SetOtherVehicleDynamics (const ::ad::rss::world::RssDynamics & other_vehicle_dynamics)
sets the ego vehicle dynamics to be used by other vehicles (
See also
also RssCheck::SetOtherVehicleDynamics())
Definition at line 177 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
SetPedestrianDynamics()
void carla::client::RssSensor::SetPedestrianDynamics (const ::ad::rss::world::RssDynamics & pedestrian_dynamics)
sets the ego vehicle dynamics to be used by pedestrians (
See also
also RssCheck::SetPedestrianDynamics())
Definition at line 206 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_actor_constellation_callback, _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
SetRoadBoundariesMode()
void carla::client::RssSensor::SetRoadBoundariesMode (const ::carla::rss::RoadBoundariesMode & road_boundaries_mode)
sets the current mode for respecting the road boundaries (
See also
also RssCheck::SetRoadBoundariesMode())
Definition at line 230 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _rss_check, carla::client::detail::ActorState::GetDisplayId(), and carla::log_error().
Stop()
void carla::client::RssSensor::Stop (void) override virtual
Stop listening for new measurements.
Implements carla::client::Sensor.
Definition at line 100 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _on_tick_register_id, carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), IsListening(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::log_debug(), and carla::log_error().
TickRssSensor()
SharedPtr< sensor::SensorData > carla::client::RssSensor::TickRssSensor (const Timestamp & timestamp) private
the acutal sensor tick callback function
Todo:
do we need to unsubscribe the sensor here?
Definition at line 272 of file LibCarla/source/carla/rss/RssSensor.cpp.
References _drop_route, _last_processed_frame, _processing_lock, _rss_check, carla::client::Timestamp::elapsed_seconds, carla::client::Timestamp::frame, carla::client::World::GetActors(), carla::client::detail::ActorState::GetParent(), carla::client::Actor::GetTransform(), carla::client::detail::ActorState::GetWorld(), carla::rss::EgoDynamicsOnRoute::time_since_epoch_check_end_ms, and carla::rss::EgoDynamicsOnRoute::time_since_epoch_check_start_ms.
Member Data Documentation
_drop_route
bool carla::client::RssSensor::_drop_route private
reqired to store DropRoute() requests until next sensor tick
Definition at line 141 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by DropRoute(), and TickRssSensor().
_last_processed_frame
std::size_t carla::client::RssSensor::_last_processed_frame private
last processed frame
Definition at line 144 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by TickRssSensor().
_on_tick_register_id
std::size_t carla::client::RssSensor::_on_tick_register_id private
the id got when registering for the on tick event
Definition at line 129 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by Listen(), and Stop().
_processing_lock
std::mutex carla::client::RssSensor::_processing_lock private
the mutex to protect the actual RSS processing and in case it takes too long to process ever frame
Definition at line 132 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by TickRssSensor(), and ~RssSensor().
_rss_actor_constellation_callback
ActorConstellationCallbackFunctionType carla::client::RssSensor::_rss_actor_constellation_callback private
Definition at line 138 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by GetEgoVehicleDynamics(), GetOtherVehicleDynamics(), GetPedestrianDynamics(), Listen(), RegisterActorConstellationCallback(), SetEgoVehicleDynamics(), SetOtherVehicleDynamics(), and SetPedestrianDynamics().
_rss_check
std::shared_ptr<::carla::rss::RssCheck> carla::client::RssSensor::_rss_check private
Definition at line 135 of file LibCarla/source/carla/rss/RssSensor.h.
Referenced by AppendRoutingTarget(), GetEgoVehicleDynamics(), GetOtherVehicleDynamics(), GetPedestrianDynamics(), GetRoadBoundariesMode(), GetRoutingTargets(), Listen(), ResetRoutingTargets(), SetEgoVehicleDynamics(), SetLogLevel(), SetMapLogLevel(), SetOtherVehicleDynamics(), SetPedestrianDynamics(), SetRoadBoundariesMode(), TickRssSensor(), and ~RssSensor().
The documentation for this class was generated from the following files:
LibCarla/source/carla/rss/RssSensor.h
LibCarla/source/carla/rss/RssSensor.cpp