CARLA: CarlaRecorderHelpers.cpp File Reference
CarlaRecorderHelpers.cpp File Reference
#include <fstream>
#include <vector>
#include "UnrealString.h"
#include "CarlaRecorderHelpers.h"
Functions
std::string GetRecorderFilename (std::string Filename)
void ReadFString (std::istream &InFile, FString &OutObj)
void ReadFTransform (std::ifstream &InFile, FTransform &OutObj)
void ReadFVector (std::istream &InFile, FVector &OutObj)
void WriteFString (std::ostream &OutFile, const FString &InObj)
void WriteFTransform (std::ofstream &OutFile, const FTransform &InObj)
void WriteFVector (std::ostream &OutFile, const FVector &InObj)
Variables
static std::vector< uint8_t > CarlaRecorderHelperBuffer
Function Documentation
GetRecorderFilename()
std::string GetRecorderFilename (std::string Filename)
Definition at line 17 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderQuery::QueryBlocked(), CarlaRecorderQuery::QueryCollisions(), CarlaRecorderQuery::QueryInfo(), CarlaReplayer::ReplayFile(), and ACarlaRecorder::Start().
ReadFString()
void ReadFString (std::istream & InFile, FString & OutObj)
Definition at line 86 of file CarlaRecorderHelpers.cpp.
References CarlaRecorderHelperBuffer.
Referenced by CarlaRecorderInfo::Read(), CarlaRecorderWalkerBones::Read(), CarlaRecorderEventAdd::Read(), and ReadTArray().
ReadFTransform()
void ReadFTransform (std::ifstream & InFile, FTransform & OutObj)
Definition at line 76 of file CarlaRecorderHelpers.cpp.
References ReadFVector().
ReadFVector()
void ReadFVector (std::istream & InFile, FVector & OutObj)
Definition at line 68 of file CarlaRecorderHelpers.cpp.
Referenced by FDenseTile::InitializeTile(), CarlaRecorderBoundingBox::Read(), CarlaRecorderKinematics::Read(), CarlaRecorderPosition::Read(), CarlaRecorderWalkerBones::Read(), CarlaRecorderEventAdd::Read(), ReadFTransform(), and ReadTArray().
WriteFString()
void WriteFString (std::ostream & OutFile, const FString & InObj)
Definition at line 53 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderInfo::Write(), CarlaRecorderWalkerBones::Write(), CarlaRecorderEventAdd::Write(), and WriteTArray().
WriteFTransform()
void WriteFTransform (std::ofstream & OutFile, const FTransform & InObj)
Definition at line 46 of file CarlaRecorderHelpers.cpp.
References WriteFVector().
Referenced by WriteTArray().
WriteFVector()
void WriteFVector (std::ostream & OutFile, const FVector & InObj)
Definition at line 38 of file CarlaRecorderHelpers.cpp.
Referenced by FSparseHighDetailMap::SaveMap(), FSparseHighDetailMap::UpdateMaps(), CarlaRecorderBoundingBox::Write(), CarlaRecorderKinematics::Write(), CarlaRecorderPosition::Write(), CarlaRecorderWalkerBones::Write(), CarlaRecorderEventAdd::Write(), WriteFTransform(), and WriteTArray().
Variable Documentation
CarlaRecorderHelperBuffer
std::vector<uint8_t> CarlaRecorderHelperBuffer static
Definition at line 14 of file CarlaRecorderHelpers.cpp.
Referenced by ReadFString().