CARLA: carla_msgs::msg::LaneInvasionEventPubSubType Class Reference
carla_msgs::msg::LaneInvasionEventPubSubType Class Reference
This class represents the TopicDataType of the type LaneInvasionEvent defined by the user in the IDL file.
#include <CarlaLineInvasionPubSubTypes.h>
Public Types
typedef LaneInvasionEvent type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport LaneInvasionEventPubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~LaneInvasionEventPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type LaneInvasionEvent defined by the user in the IDL file.
Definition at line 44 of file CarlaLineInvasionPubSubTypes.h.
Member Typedef Documentation
type
typedef LaneInvasionEvent carla_msgs::msg::LaneInvasionEventPubSubType::type
Definition at line 47 of file CarlaLineInvasionPubSubTypes.h.
Constructor & Destructor Documentation
LaneInvasionEventPubSubType()
carla_msgs::msg::LaneInvasionEventPubSubType::LaneInvasionEventPubSubType ()
Definition at line 32 of file CarlaLineInvasionPubSubTypes.cpp.
References carla_msgs::msg::LaneInvasionEvent::getKeyMaxCdrSerializedSize(), carla_msgs::msg::LaneInvasionEvent::getMaxCdrSerializedSize(), carla_msgs::msg::LaneInvasionEvent::isKeyDefined(), and m_keyBuffer.
~LaneInvasionEventPubSubType()
carla_msgs::msg::LaneInvasionEventPubSubType::~LaneInvasionEventPubSubType () override virtual
Definition at line 45 of file CarlaLineInvasionPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * carla_msgs::msg::LaneInvasionEventPubSubType::createData () override virtual
Definition at line 122 of file CarlaLineInvasionPubSubTypes.cpp.
deleteData()
void carla_msgs::msg::LaneInvasionEventPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file CarlaLineInvasionPubSubTypes.cpp.
deserialize()
bool carla_msgs::msg::LaneInvasionEventPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file CarlaLineInvasionPubSubTypes.cpp.
References carla_msgs::msg::LaneInvasionEvent::deserialize().
getKey()
bool carla_msgs::msg::LaneInvasionEventPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file CarlaLineInvasionPubSubTypes.cpp.
References carla_msgs::msg::LaneInvasionEvent::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and carla_msgs::msg::LaneInvasionEvent::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> carla_msgs::msg::LaneInvasionEventPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file CarlaLineInvasionPubSubTypes.cpp.
References carla_msgs::msg::LaneInvasionEvent::getCdrSerializedSize().
serialize()
bool carla_msgs::msg::LaneInvasionEventPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file CarlaLineInvasionPubSubTypes.cpp.
References carla_msgs::msg::LaneInvasionEvent::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* carla_msgs::msg::LaneInvasionEventPubSubType::m_keyBuffer
Definition at line 100 of file CarlaLineInvasionPubSubTypes.h.
Referenced by getKey(), LaneInvasionEventPubSubType(), and ~LaneInvasionEventPubSubType().
m_md5
MD5 carla_msgs::msg::LaneInvasionEventPubSubType::m_md5
Definition at line 99 of file CarlaLineInvasionPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
CarlaLineInvasionPubSubTypes.h
CarlaLineInvasionPubSubTypes.cpp