CARLA: geometry_msgs::msg::TwistWithCovariance Class Reference
geometry_msgs::msg::TwistWithCovariance Class Reference
This class represents the structure TwistWithCovariance defined by the user in the IDL file.
#include <TwistWithCovariance.h>
Public Member Functions
eProsima_user_DllExport geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 & covariance ()
This function returns a reference to member covariance.
const eProsima_user_DllExport geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 & covariance () const
This function returns a constant reference to member covariance.
eProsima_user_DllExport void covariance (const geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 &_covariance)
This function copies the value in member covariance.
eProsima_user_DllExport void covariance (geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 &&_covariance)
This function moves the value in member covariance.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const TwistWithCovariance &x) const
Comparison operator.
eProsima_user_DllExport TwistWithCovariance & operator= (const TwistWithCovariance &x)
Copy assignment.
eProsima_user_DllExport TwistWithCovariance & operator= (TwistWithCovariance &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const TwistWithCovariance &x) const
Comparison operator.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport geometry_msgs::msg::Twist & twist ()
This function returns a reference to member twist.
const eProsima_user_DllExport geometry_msgs::msg::Twist & twist () const
This function returns a constant reference to member twist.
eProsima_user_DllExport void twist (const geometry_msgs::msg::Twist &_twist)
This function copies the value in member twist.
eProsima_user_DllExport void twist (geometry_msgs::msg::Twist &&_twist)
This function moves the value in member twist.
eProsima_user_DllExport TwistWithCovariance ()
Default constructor.
eProsima_user_DllExport TwistWithCovariance (const TwistWithCovariance &x)
Copy constructor.
eProsima_user_DllExport TwistWithCovariance (TwistWithCovariance &&x) noexcept
Move constructor.
eProsima_user_DllExport ~TwistWithCovariance ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::TwistWithCovariance &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 m_covariance
geometry_msgs::msg::Twist m_twist
Detailed Description
This class represents the structure TwistWithCovariance defined by the user in the IDL file.
Definition at line 74 of file TwistWithCovariance.h.
Constructor & Destructor Documentation
TwistWithCovariance() [1/3]
geometry_msgs::msg::TwistWithCovariance::TwistWithCovariance ()
Default constructor.
Definition at line 44 of file TwistWithCovariance.cpp.
~TwistWithCovariance()
geometry_msgs::msg::TwistWithCovariance::~TwistWithCovariance ()
Default destructor.
Definition at line 52 of file TwistWithCovariance.cpp.
TwistWithCovariance() [2/3]
geometry_msgs::msg::TwistWithCovariance::TwistWithCovariance (const TwistWithCovariance & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::TwistWithCovariance that will be copied.
Definition at line 56 of file TwistWithCovariance.cpp.
References m_covariance, and m_twist.
TwistWithCovariance() [3/3]
geometry_msgs::msg::TwistWithCovariance::TwistWithCovariance (TwistWithCovariance && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::TwistWithCovariance that will be copied.
Definition at line 63 of file TwistWithCovariance.cpp.
Member Function Documentation
covariance() [1/4]
eProsima_user_DllExport geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36& geometry_msgs::msg::TwistWithCovariance::covariance ()
This function returns a reference to member covariance.
Returns
Reference to member covariance
covariance() [2/4]
geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 & geometry_msgs::msg::TwistWithCovariance::covariance () const
This function returns a constant reference to member covariance.
This function returns a reference to member covariance.
Returns
Constant reference to member covariance
Reference to member covariance
Definition at line 194 of file TwistWithCovariance.cpp.
covariance() [3/4]
void geometry_msgs::msg::TwistWithCovariance::covariance (const geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 & _covariance)
This function copies the value in member covariance.
Parameters
_covariance New value to be copied in member covariance
Definition at line 174 of file TwistWithCovariance.cpp.
covariance() [4/4]
void geometry_msgs::msg::TwistWithCovariance::covariance (geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 && _covariance)
This function moves the value in member covariance.
Parameters
_covariance New value to be moved in member covariance
Definition at line 184 of file TwistWithCovariance.cpp.
deserialize()
void geometry_msgs::msg::TwistWithCovariance::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 125 of file TwistWithCovariance.cpp.
Referenced by geometry_msgs::msg::TwistWithCovariancePubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::TwistWithCovariance::getCdrSerializedSize (const geometry_msgs::msg::TwistWithCovariance & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 107 of file TwistWithCovariance.cpp.
References geometry_msgs::msg::Twist::getCdrSerializedSize(), and twist().
Referenced by nav_msgs::msg::Odometry::getCdrSerializedSize(), and geometry_msgs::msg::TwistWithCovariancePubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::TwistWithCovariance::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 208 of file TwistWithCovariance.cpp.
References geometry_msgs_msg_TwistWithCovariance_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::TwistWithCovariancePubSubType::getKey(), and geometry_msgs::msg::TwistWithCovariancePubSubType::TwistWithCovariancePubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::TwistWithCovariance::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 100 of file TwistWithCovariance.cpp.
References geometry_msgs_msg_TwistWithCovariance_max_cdr_typesize.
Referenced by geometry_msgs::msg::TwistWithCovariancePubSubType::TwistWithCovariancePubSubType().
isKeyDefined()
bool geometry_msgs::msg::TwistWithCovariance::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 215 of file TwistWithCovariance.cpp.
Referenced by geometry_msgs::msg::TwistWithCovariancePubSubType::TwistWithCovariancePubSubType().
operator!=()
bool geometry_msgs::msg::TwistWithCovariance::operator!= (const TwistWithCovariance & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::TwistWithCovariance object to compare.
Definition at line 94 of file TwistWithCovariance.cpp.
operator=() [1/2]
geometry_msgs::msg::TwistWithCovariance & geometry_msgs::msg::TwistWithCovariance::operator= (const TwistWithCovariance & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::TwistWithCovariance that will be copied.
Definition at line 70 of file TwistWithCovariance.cpp.
References m_covariance, and m_twist.
operator=() [2/2]
geometry_msgs::msg::TwistWithCovariance & geometry_msgs::msg::TwistWithCovariance::operator= (TwistWithCovariance && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::TwistWithCovariance that will be copied.
Definition at line 79 of file TwistWithCovariance.cpp.
operator==()
bool geometry_msgs::msg::TwistWithCovariance::operator== (const TwistWithCovariance & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::TwistWithCovariance object to compare.
Definition at line 88 of file TwistWithCovariance.cpp.
References m_covariance, and m_twist.
serialize()
void geometry_msgs::msg::TwistWithCovariance::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 118 of file TwistWithCovariance.cpp.
Referenced by geometry_msgs::msg::TwistWithCovariancePubSubType::serialize().
serializeKey()
void geometry_msgs::msg::TwistWithCovariance::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 220 of file TwistWithCovariance.cpp.
Referenced by geometry_msgs::msg::TwistWithCovariancePubSubType::getKey().
twist() [1/4]
eProsima_user_DllExport geometry_msgs::msg::Twist& geometry_msgs::msg::TwistWithCovariance::twist ()
This function returns a reference to member twist.
Returns
Reference to member twist
twist() [2/4]
geometry_msgs::msg::Twist & geometry_msgs::msg::TwistWithCovariance::twist () const
This function returns a constant reference to member twist.
This function returns a reference to member twist.
Returns
Constant reference to member twist
Reference to member twist
Definition at line 156 of file TwistWithCovariance.cpp.
twist() [3/4]
void geometry_msgs::msg::TwistWithCovariance::twist (const geometry_msgs::msg::Twist & _twist)
This function copies the value in member twist.
Parameters
_twist New value to be copied in member twist
Definition at line 136 of file TwistWithCovariance.cpp.
Referenced by getCdrSerializedSize().
twist() [4/4]
void geometry_msgs::msg::TwistWithCovariance::twist (geometry_msgs::msg::Twist && _twist)
This function moves the value in member twist.
Parameters
_twist New value to be moved in member twist
Definition at line 146 of file TwistWithCovariance.cpp.
Member Data Documentation
m_covariance
geometry_msgs::msg::geometry_msgs__TwistWithCovariance__double_array_36 geometry_msgs::msg::TwistWithCovariance::m_covariance private
Definition at line 237 of file TwistWithCovariance.h.
Referenced by operator=(), operator==(), and TwistWithCovariance().
m_twist
geometry_msgs::msg::Twist geometry_msgs::msg::TwistWithCovariance::m_twist private
Definition at line 236 of file TwistWithCovariance.h.
Referenced by operator=(), operator==(), and TwistWithCovariance().
The documentation for this class was generated from the following files:
TwistWithCovariance.h
TwistWithCovariance.cpp