CARLA: carla::rpc::VehicleLightState Class Reference
carla::rpc::VehicleLightState Class Reference
Defines the physical appearance of a vehicle whitch is obtained by the sensors.
#include <VehicleLightState.h>
Public Types
using flag_type = uint32_t
enum LightState : flag_type {
LightState::None = 0, LightState::Position = 0x1, LightState::LowBeam = 0x1 << 1, LightState::HighBeam = 0x1 << 2,
LightState::Brake = 0x1 << 3, LightState::RightBlinker = 0x1 << 4, LightState::LeftBlinker = 0x1 << 5, LightState::Reverse = 0x1 << 6,
LightState::Fog = 0x1 << 7, LightState::Interior = 0x1 << 8, LightState::Special1 = 0x1 << 9, LightState::Special2 = 0x1 << 10,
LightState::All = 0xFFFFFFFF
}
Can be used as flags.
Public Member Functions
flag_type GetLightStateAsValue () const
Returns the current light state as a value type.
LightState GetLightStateEnum () const
Returns the current light state as an enum type.
VehicleLightState ()=default
VehicleLightState (flag_type light_state)
VehicleLightState (LightState light_state)
Public Attributes
flag_type light_state = static_cast<flag_type>(LightState::None)
Lights state flag, all turned off by default.
Detailed Description
Defines the physical appearance of a vehicle whitch is obtained by the sensors.
Definition at line 26 of file LibCarla/source/carla/rpc/VehicleLightState.h.
Member Typedef Documentation
flag_type
using carla::rpc::VehicleLightState::flag_type = uint32_t
Definition at line 29 of file LibCarla/source/carla/rpc/VehicleLightState.h.
Member Enumeration Documentation
LightState
enum carla::rpc::VehicleLightState::LightState : flag_type strong
Can be used as flags.
Enumerator
None
Position
LowBeam
HighBeam
Brake
RightBlinker
LeftBlinker
Reverse
Fog
Interior
Special1
Special2
All
Definition at line 32 of file LibCarla/source/carla/rpc/VehicleLightState.h.
Constructor & Destructor Documentation
VehicleLightState() [1/3]
carla::rpc::VehicleLightState::VehicleLightState () default
VehicleLightState() [2/3]
carla::rpc::VehicleLightState::VehicleLightState (LightState light_state) inline
Definition at line 50 of file LibCarla/source/carla/rpc/VehicleLightState.h.
VehicleLightState() [3/3]
carla::rpc::VehicleLightState::VehicleLightState (flag_type light_state) inline
Definition at line 53 of file LibCarla/source/carla/rpc/VehicleLightState.h.
Member Function Documentation
GetLightStateAsValue()
flag_type carla::rpc::VehicleLightState::GetLightStateAsValue () const inline
Returns the current light state as a value type.
Definition at line 97 of file LibCarla/source/carla/rpc/VehicleLightState.h.
References light_state.
GetLightStateEnum()
LightState carla::rpc::VehicleLightState::GetLightStateEnum () const inline
Returns the current light state as an enum type.
Definition at line 92 of file LibCarla/source/carla/rpc/VehicleLightState.h.
References light_state.
Member Data Documentation
light_state
flag_type carla::rpc::VehicleLightState::light_state = static_cast<flag_type>(LightState::None)
Lights state flag, all turned off by default.
Definition at line 102 of file LibCarla/source/carla/rpc/VehicleLightState.h.
Referenced by FFrameData::AddVehicleLight(), ACarlaRecorder::AddVehicleLight(), GetLightStateAsValue(), and GetLightStateEnum().
The documentation for this class was generated from the following file:
LibCarla/source/carla/rpc/VehicleLightState.h