CARLA: Benchmark Class Reference
Benchmark Class Reference
Public Member Functions
void AddStream ()
void AddStreams (size_t count)
Benchmark (uint16_t port, size_t message_size, double success_ratio)
void Run (size_t number_of_messages)
Private Attributes
Client _client
boost::asio::io_context _client_callback
const carla::Buffer _message
std::atomic_size_t _number_of_messages_received {0u}
Server _server
std::vector< Stream > _streams
const double _success_ratio
carla::ThreadGroup _threads
boost::asio::io_context::work _work_to_do
Detailed Description
Definition at line 24 of file test_benchmark_streaming.cpp.
Constructor & Destructor Documentation
Benchmark::Benchmark (uint16_t port, size_t message_size, double success_ratio) inline
Definition at line 27 of file test_benchmark_streaming.cpp.
Member Function Documentation
void Benchmark::AddStream () inline
Definition at line 35 of file test_benchmark_streaming.cpp.
References CARLA_PROFILE_FPS, DEBUG_ASSERT, DEBUG_ASSERT_EQ, DEBUG_ONLY, and carla::streaming::detail::Stream< StreamStateT >::token().
void Benchmark::AddStreams (size_t count) inline
Definition at line 50 of file test_benchmark_streaming.cpp.
Referenced by benchmark_image().
void Benchmark::Run (size_t number_of_messages) inline
Definition at line 56 of file test_benchmark_streaming.cpp.
References CARLA_PROFILE_SCOPE, carla::log_warning(), and carla::logging::write_to_stream().
Referenced by benchmark_image().
Member Data Documentation
Client Benchmark::_client private
Definition at line 110 of file test_benchmark_streaming.cpp.
boost::asio::io_context Benchmark::_client_callback private
Definition at line 114 of file test_benchmark_streaming.cpp.
const carla::Buffer Benchmark::_message private
Definition at line 112 of file test_benchmark_streaming.cpp.
std::atomic_size_t Benchmark::_number_of_messages_received {0u} private
Definition at line 122 of file test_benchmark_streaming.cpp.
Server Benchmark::_server private
Definition at line 108 of file test_benchmark_streaming.cpp.
std::vector<Stream> Benchmark::_streams private
Definition at line 120 of file test_benchmark_streaming.cpp.
const double Benchmark::_success_ratio private
Definition at line 118 of file test_benchmark_streaming.cpp.
carla::ThreadGroup Benchmark::_threads private
Definition at line 106 of file test_benchmark_streaming.cpp.
boost::asio::io_context::work Benchmark::_work_to_do private
Definition at line 116 of file test_benchmark_streaming.cpp.
The documentation for this class was generated from the following file:
test_benchmark_streaming.cpp