CARLA: ATriggerFactory Class Reference
ATriggerFactory Class Reference
Factory in charge of spawning sensors.
#include <TriggerFactory.h>
Private Member Functions
TArray< FActorDefinition > GetDefinitions () final
Retrieve the definitions of all the sensors registered in the SensorRegistry.
FActorSpawnResult SpawnActor (const FTransform &SpawnAtTransform, const FActorDescription &ActorDescription) final
Spawn an actor based on ActorDescription and Transform.
Additional Inherited Members
Public Member Functions inherited from ACarlaActorFactory
ACarlaActorFactory (const FObjectInitializer &ObjectInitializer)
Detailed Description
Factory in charge of spawning sensors.
This factory is able to spawn every sensor registered in carla::sensor::SensorRegistry.
Definition at line 17 of file TriggerFactory.h.
Member Function Documentation
TArray< FActorDefinition > ATriggerFactory::GetDefinitions () final private virtual
Retrieve the definitions of all the sensors registered in the SensorRegistry.
Sensors must implement a GetSensorDefinition() static method.
Reimplemented from ACarlaActorFactory.
Definition at line 18 of file TriggerFactory.cpp.
References FActorDefinition::Class, and UActorBlueprintFunctionLibrary::MakeTriggerDefinition().
FActorSpawnResult ATriggerFactory::SpawnActor (const FTransform & SpawnAtTransform, const FActorDescription & ActorDescription) final private virtual
Spawn an actor based on ActorDescription and Transform.
Precondition
ActorDescription is expected to be derived from one of the definitions retrieved with GetDefinitions.
Reimplemented from ACarlaActorFactory.
Definition at line 33 of file TriggerFactory.cpp.
References FActorDescription::Class, UCarlaGameInstance::GetCarlaEpisode(), UCarlaStatics::GetGameInstance(), UActorBlueprintFunctionLibrary::RetrieveActorAttributeToFloat(), and FActorDescription::Variations.
The documentation for this class was generated from the following files:
TriggerFactory.h
TriggerFactory.cpp