CARLA: carla::client::DebugHelper Class Reference
carla::client::DebugHelper Class Reference
#include <DebugHelper.h>
Public Types
using Color = sensor::data::Color
Public Member Functions
DebugHelper (detail::EpisodeProxy episode)
void DrawArrow (const geom::Location &begin, const geom::Location &end, float thickness=0.1f, float arrow_size=0.1f, Color color=Color{255u, 0u, 0u}, float life_time=-1.0f, bool persistent_lines=true)
void DrawBox (const geom::BoundingBox &box, const geom::Rotation &rotation, float thickness=0.1f, Color color=Color{255u, 0u, 0u}, float life_time=-1.0f, bool persistent_lines=true)
void DrawLine (const geom::Location &begin, const geom::Location &end, float thickness=0.1f, Color color=Color{255u, 0u, 0u}, float life_time=-1.0f, bool persistent_lines=true)
void DrawPoint (const geom::Location &location, float size=0.1f, Color color=Color{255u, 0u, 0u}, float life_time=-1.0f, bool persistent_lines=true)
void DrawString (const geom::Location &location, const std::string &text, bool draw_shadow=false, Color color=Color{255u, 0u, 0u}, float life_time=-1.0f, bool persistent_lines=true)
Private Attributes
detail::EpisodeProxy _episode
Detailed Description
Definition at line 18 of file DebugHelper.h.
Member Typedef Documentation
using carla::client::DebugHelper::Color = sensor::data::Color
Definition at line 21 of file DebugHelper.h.
Constructor & Destructor Documentation
carla::client::DebugHelper::DebugHelper (detail::EpisodeProxy episode) inline explicit
Definition at line 23 of file DebugHelper.h.
References DrawArrow(), DrawBox(), DrawLine(), DrawPoint(), and DrawString().
Member Function Documentation
void carla::client::DebugHelper::DrawArrow (const geom::Location & begin, const geom::Location & end, float thickness = 0.1f, float arrow_size = 0.1f, Color color = Color{255u, 0u, 0u}, float life_time = -1.0f, bool persistent_lines = true)
Definition at line 49 of file DebugHelper.cpp.
References _episode, and carla::client::DrawShape().
Referenced by DebugHelper().
void carla::client::DebugHelper::DrawBox (const geom::BoundingBox & box, const geom::Rotation & rotation, float thickness = 0.1f, Color color = Color{255u, 0u, 0u}, float life_time = -1.0f, bool persistent_lines = true)
Definition at line 62 of file DebugHelper.cpp.
References _episode, and carla::client::DrawShape().
Referenced by DebugHelper().
void carla::client::DebugHelper::DrawLine (const geom::Location & begin, const geom::Location & end, float thickness = 0.1f, Color color = Color{255u, 0u, 0u}, float life_time = -1.0f, bool persistent_lines = true)
Definition at line 38 of file DebugHelper.cpp.
References _episode, and carla::client::DrawShape().
Referenced by DebugHelper(), carla::traffic_manager::CollisionStage::DrawBoundary(), carla::traffic_manager::LocalizationStage::DrawBuffer(), and carla::rss::RssCheck::visualizeRssResults().
void carla::client::DebugHelper::DrawPoint (const geom::Location & location, float size = 0.1f, Color color = Color{255u, 0u, 0u}, float life_time = -1.0f, bool persistent_lines = true)
Definition at line 28 of file DebugHelper.cpp.
References _episode, and carla::client::DrawShape().
Referenced by DebugHelper(), and carla::rss::RssCheck::visualizeRssResults().
void carla::client::DebugHelper::DrawString (const geom::Location & location, const std::string & text, bool draw_shadow = false, Color color = Color{255u, 0u, 0u}, float life_time = -1.0f, bool persistent_lines = true)
Definition at line 73 of file DebugHelper.cpp.
References _episode, and carla::client::DrawShape().
Referenced by DebugHelper(), carla::traffic_manager::TrafficLightStage::DrawLight(), and carla::traffic_manager::MotionPlannerStage::DrawPIDValues().
Member Data Documentation
detail::EpisodeProxy carla::client::DebugHelper::_episode private
Definition at line 68 of file DebugHelper.h.
Referenced by DrawArrow(), DrawBox(), DrawLine(), DrawPoint(), and DrawString().
The documentation for this class was generated from the following files:
DebugHelper.h
DebugHelper.cpp