CARLA: WorldObserver.cpp File Reference
WorldObserver.cpp File Reference
#include "Carla.h"
#include "Carla/Sensor/WorldObserver.h"
#include "Carla/Actor/ActorData.h"
#include "Carla/Traffic/TrafficLightBase.h"
#include "Carla/Traffic/TrafficLightComponent.h"
#include "Carla/Traffic/TrafficLightController.h"
#include "Carla/Traffic/TrafficLightGroup.h"
#include "Carla/Traffic/TrafficSignBase.h"
#include "Carla/Traffic/SignComponent.h"
#include "Carla/Walker/WalkerController.h"
#include "CoreGlobals.h"
#include <compiler/disable-ue4-macros.h>
#include <carla/rpc/String.h>
#include <carla/sensor/SensorRegistry.h>
#include <carla/sensor/data/ActorDynamicState.h>
#include <compiler/enable-ue4-macros.h>
Functions
static carla::geom::Vector3D FWorldObserver_GetAcceleration (const FCarlaActor &View, const FVector &Velocity, const float DeltaSeconds)
static auto FWorldObserver_GetActorState (const FCarlaActor &View, const FActorRegistry &Registry)
static carla::geom::Vector3D FWorldObserver_GetAngularVelocity (const AActor &Actor)
static auto FWorldObserver_GetDormantActorState (const FCarlaActor &View, const FActorRegistry &Registry)
static carla::Buffer FWorldObserver_Serialize (carla::Buffer &&buffer, const UCarlaEpisode &Episode, float DeltaSeconds, bool MapChange, bool PendingLightUpdates)
Function Documentation
FWorldObserver_GetAcceleration()
static carla::geom::Vector3D FWorldObserver_GetAcceleration (const FCarlaActor & View, const FVector & Velocity, const float DeltaSeconds) static
Definition at line 251 of file WorldObserver.cpp.
References FCarlaActor::GetActorInfo(), and FActorInfo::Velocity.
Referenced by FWorldObserver_Serialize().
FWorldObserver_GetActorState()
static auto FWorldObserver_GetActorState (const FCarlaActor & View, const FActorRegistry & Registry) static
Definition at line 27 of file WorldObserver.cpp.
References FActorRegistry::FindCarlaActor(), FCarlaActor::GetActor(), FCarlaActor::GetActorId(), FCarlaActor::GetActorType(), UTrafficLightController::GetElapsedTime(), UTrafficLightController::GetGreenTime(), UTrafficLightController::GetRedTime(), UTrafficLightController::GetYellowTime(), ATrafficLightGroup::IsFrozen(), TrafficLight, and Vehicle.
Referenced by FWorldObserver_Serialize().
FWorldObserver_GetAngularVelocity()
static carla::geom::Vector3D FWorldObserver_GetAngularVelocity (const AActor & Actor) static
Definition at line 241 of file WorldObserver.cpp.
Referenced by FWorldObserver_Serialize().
FWorldObserver_GetDormantActorState()
static auto FWorldObserver_GetDormantActorState (const FCarlaActor & View, const FActorRegistry & Registry) static
Definition at line 162 of file WorldObserver.cpp.
References FVehicleData::Control, FTrafficLightData::Controller, FCarlaActor::GetActorData(), FCarlaActor::GetActorType(), ATrafficLightGroup::IsFrozen(), FTrafficLightData::PoleIndex, FTrafficSignData::SignId, FTrafficLightData::SignId, FVehicleData::SpeedLimit, TrafficLight, Vehicle, and FWalkerData::WalkerControl.
Referenced by FWorldObserver_Serialize().
FWorldObserver_Serialize()
static carla::Buffer FWorldObserver_Serialize (carla::Buffer && buffer, const UCarlaEpisode & Episode, float DeltaSeconds, bool MapChange, bool PendingLightUpdates) static
Definition at line 262 of file WorldObserver.cpp.
References FActorData::AngularVelocity, FWorldObserver_GetAcceleration(), FWorldObserver_GetActorState(), FWorldObserver_GetAngularVelocity(), FWorldObserver_GetDormantActorState(), FCarlaActor::GetActor(), FCarlaActor::GetActorData(), FCarlaActor::GetActorGlobalTransform(), FCarlaActor::GetActorId(), FCarlaActor::GetActorInfo(), UCarlaEpisode::GetActorRegistry(), FCarlaActor::GetActorState(), UCarlaEpisode::GetCurrentMapOrigin(), UCarlaEpisode::GetId(), FCarlaActor::IsDormant(), FActorRegistry::Num(), State, and FActorData::Velocity.
Referenced by FWorldObserver::BroadcastTick().