CARLA: test_image.cpp File Reference
test_image.cpp File Reference
#include "test.h"
#include <carla/image/ImageConverter.h>
#include <carla/image/ImageIO.h>
#include <carla/image/ImageView.h>
#include <memory>
Classes
struct TestImage< ViewT, PixelT >
Functions
template<typename PixelT >
static auto MakeTestImage (size_t width, size_t height)
TEST (image, support)
TEST (image, depth)
TEST (image, semantic_segmentation)
Function Documentation
template<typename PixelT > static auto MakeTestImage (size_t width, size_t height) static
Definition at line 24 of file test_image.cpp.
References TestImage< ViewT, PixelT >::data, and TestImage< ViewT, PixelT >::view.
TEST (image , support)
Definition at line 35 of file test_image.cpp.
References carla::image::io::has_jpeg_support(), carla::image::io::has_png_support(), carla::image::io::has_tiff_support(), and carla::logging::log().
TEST (image , depth)
Definition at line 43 of file test_image.cpp.
References carla::log_info().
TEST (image , semantic_segmentation)
Definition at line 124 of file test_image.cpp.
References carla::road::element::GetColor().