CARLA: carla::traffic_manager::TrafficManagerRemote Class Reference
carla::traffic_manager::TrafficManagerRemote Class Reference
The function of this class is to integrate all the various stages of the traffic manager appropriately using messengers.
#include <TrafficManagerRemote.h>
Public Member Functions
ActionBuffer GetActionBuffer (const ActorId &actor_id)
Method to get the vehicle's action buffer.
carla::client::detail::EpisodeProxy & GetEpisodeProxy ()
Get CARLA episode information.
Action GetNextAction (const ActorId &actor_id)
Method to get the vehicle's next action.
void HealthCheckRemoteTM ()
Method to check server is alive or not.
void RegisterVehicles (const std::vector< ActorPtr > &actor_list)
This method registers a vehicle with the traffic manager.
void Release ()
To release the traffic manager.
void RemoveImportedRoute (const ActorId &actor_id, const bool remove_path)
Method to remove a route.
void RemoveUploadPath (const ActorId &actor_id, const bool remove_path)
Method to remove a path.
void Reset ()
To reset the traffic manager.
void SetAutoLaneChange (const ActorPtr &actor, const bool enable)
Enable/disable automatic lane change on a vehicle.
void SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound)
Method to set boundaries for respawning vehicles.
void SetCollisionDetection (const ActorPtr &reference_actor, const ActorPtr &other_actor, const bool detect_collision)
Method to set collision detection rules between vehicles.
void SetCustomPath (const ActorPtr &actor, const Path path, const bool empty_buffer)
Method to set our own imported path.
void SetDesiredSpeed (const ActorPtr &actor, const float value)
Set a vehicle's exact desired velocity.
void SetDistanceToLeadingVehicle (const ActorPtr &actor, const float distance)
Method to specify how much distance a vehicle should maintain to the leading vehicle.
void SetForceLaneChange (const ActorPtr &actor, const bool direction)
Method to force lane change on a vehicle.
void SetGlobalDistanceToLeadingVehicle (const float distance)
Method to specify Global Distance.
void SetGlobalLaneOffset (float const offset)
Method to set a global lane offset displacement from the center line.
void SetGlobalPercentageSpeedDifference (float const percentage)
Method to set a global % decrease in velocity with respect to the speed limit.
void SetHybridPhysicsMode (const bool mode_switch)
Method to set hybrid physics mode.
void SetHybridPhysicsRadius (const float radius)
Method to set hybrid physics radius.
void SetImportedRoute (const ActorPtr &actor, const Route route, const bool empty_buffer)
Method to set our own imported route.
void SetKeepRightPercentage (const ActorPtr &actor, const float percentage)
Method to set % to keep on the right lane.
void SetLaneOffset (const ActorPtr &actor, const float offset)
Method to set a lane offset displacement from the center line.
void SetMaxBoundaries (const float lower, const float upper)
Method to set limits for boundaries when respawning vehicles.
void SetOSMMode (const bool mode_switch)
Method to set Open Street Map mode.
void SetPercentageIgnoreVehicles (const ActorPtr &actor, const float perc)
Method to specify the % chance of ignoring collisions with any vehicle.
void SetPercentageIgnoreWalkers (const ActorPtr &actor, const float perc)
Method to specify the % chance of ignoring collisions with any walker.
void SetPercentageRunningLight (const ActorPtr &actor, const float perc)
Method to specify the % chance of running any traffic light.
void SetPercentageRunningSign (const ActorPtr &actor, const float perc)
Method to specify the % chance of running any traffic sign.
void SetPercentageSpeedDifference (const ActorPtr &actor, const float percentage)
Method to set a vehicle's % decrease in velocity with respect to the speed limit.
void SetRandomDeviceSeed (const uint64_t seed)
Method to set randomization seed.
void SetRandomLeftLaneChangePercentage (const ActorPtr &actor, const float percentage)
Method to set % to randomly do a left lane change.
void SetRandomRightLaneChangePercentage (const ActorPtr &actor, const float percentage)
Method to set % to randomly do a right lane change.
void SetRespawnDormantVehicles (const bool mode_switch)
Method to set automatic respawn of dormant vehicles.
void SetSynchronousMode (bool mode)
Method to switch traffic manager into synchronous execution.
void SetSynchronousModeTimeOutInMiliSecond (double time)
Method to set Tick timeout for synchronous execution.
void SetUpdateVehicleLights (const ActorPtr &actor, const bool do_update)
Method to set the automatic management of the vehicle lights.
virtual void ShutDown ()
void Start ()
To start the TrafficManager.
void Stop ()
To stop the TrafficManager.
bool SynchronousTick ()
Method to provide synchronous tick.
TrafficManagerRemote (const std::pair< std::string, uint16_t > &_serverTM, carla::client::detail::EpisodeProxy &episodeProxy)
Constructor store remote location information.
void UnregisterVehicles (const std::vector< ActorPtr > &actor_list)
This method unregisters a vehicle from traffic manager.
void UpdateImportedRoute (const ActorId &actor_id, const Route route)
Method to update an already set route.
void UpdateUploadPath (const ActorId &actor_id, const Path path)
Method to update an already set path.
virtual ~TrafficManagerRemote ()
Destructor.
Public Member Functions inherited from carla::traffic_manager::TrafficManagerBase
TrafficManagerBase ()
Protected constructor for singleton lifecycle management.
virtual ~TrafficManagerBase ()
Destructor.
Private Attributes
std::condition_variable _cv
bool _keep_alive = true
std::mutex _mutex
TrafficManagerClient client
Remote client using the IP and port information it connects to as remote RPC traffic manager server.
carla::client::detail::EpisodeProxy episodeProxyTM
CARLA client connection object.
Detailed Description
The function of this class is to integrate all the various stages of the traffic manager appropriately using messengers.
Definition at line 28 of file TrafficManagerRemote.h.
Constructor & Destructor Documentation
TrafficManagerRemote()
carla::traffic_manager::TrafficManagerRemote::TrafficManagerRemote (const std::pair< std::string, uint16_t > & _serverTM, carla::client::detail::EpisodeProxy & episodeProxy)
Constructor store remote location information.
Definition at line 16 of file TrafficManagerRemote.cpp.
References Start().
~TrafficManagerRemote()
carla::traffic_manager::TrafficManagerRemote::~TrafficManagerRemote () virtual
Destructor.
Definition at line 27 of file TrafficManagerRemote.cpp.
References Release().
Member Function Documentation
GetActionBuffer()
ActionBuffer carla::traffic_manager::TrafficManagerRemote::GetActionBuffer (const ActorId & actor_id) virtual
Method to get the vehicle's action buffer.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 280 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::GetActionBuffer().
GetEpisodeProxy()
carla::client::detail::EpisodeProxy & carla::traffic_manager::TrafficManagerRemote::GetEpisodeProxy () virtual
Get CARLA episode information.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 292 of file TrafficManagerRemote.cpp.
References episodeProxyTM.
GetNextAction()
Action carla::traffic_manager::TrafficManagerRemote::GetNextAction (const ActorId & actor_id) virtual
Method to get the vehicle's next action.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 276 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::GetNextAction().
HealthCheckRemoteTM()
void carla::traffic_manager::TrafficManagerRemote::HealthCheckRemoteTM ()
Method to check server is alive or not.
Definition at line 288 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::HealthCheckRemoteTM().
Referenced by carla::traffic_manager::TrafficManager::CreateTrafficManagerClient().
RegisterVehicles()
void carla::traffic_manager::TrafficManagerRemote::RegisterVehicles (const std::vector< ActorPtr > & actor_list) virtual
This method registers a vehicle with the traffic manager.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 92 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::RegisterVehicle().
Release()
void carla::traffic_manager::TrafficManagerRemote::Release () virtual
To release the traffic manager.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 79 of file TrafficManagerRemote.cpp.
References Stop().
Referenced by ~TrafficManagerRemote().
RemoveImportedRoute()
void carla::traffic_manager::TrafficManagerRemote::RemoveImportedRoute (const ActorId & actor_id, const bool remove_path) virtual
Method to remove a route.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 244 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::RemoveImportedRoute().
RemoveUploadPath()
void carla::traffic_manager::TrafficManagerRemote::RemoveUploadPath (const ActorId & actor_id, const bool remove_path) virtual
Method to remove a path.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 230 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::RemoveUploadPath().
Reset()
void carla::traffic_manager::TrafficManagerRemote::Reset (void) virtual
To reset the traffic manager.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 83 of file TrafficManagerRemote.cpp.
References episodeProxyTM, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), Start(), and Stop().
SetAutoLaneChange()
void carla::traffic_manager::TrafficManagerRemote::SetAutoLaneChange (const ActorPtr & actor, const bool enable) virtual
Enable/disable automatic lane change on a vehicle.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 153 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetAutoLaneChange().
SetBoundariesRespawnDormantVehicles()
void carla::traffic_manager::TrafficManagerRemote::SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound) virtual
Method to set boundaries for respawning vehicles.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 256 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetBoundariesRespawnDormantVehicles().
SetCollisionDetection()
void carla::traffic_manager::TrafficManagerRemote::SetCollisionDetection (const ActorPtr & reference_actor, const ActorPtr & other_actor, const bool detect_collision) virtual
Method to set collision detection rules between vehicles.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 140 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetCollisionDetection().
SetCustomPath()
void carla::traffic_manager::TrafficManagerRemote::SetCustomPath (const ActorPtr & actor, const Path path, const bool empty_buffer) virtual
Method to set our own imported path.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 224 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetCustomPath().
SetDesiredSpeed()
void carla::traffic_manager::TrafficManagerRemote::SetDesiredSpeed (const ActorPtr & actor, const float value) virtual
Set a vehicle's exact desired velocity.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 114 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetDesiredSpeed().
SetDistanceToLeadingVehicle()
void carla::traffic_manager::TrafficManagerRemote::SetDistanceToLeadingVehicle (const ActorPtr & actor, const float distance) virtual
Method to specify how much distance a vehicle should maintain to the leading vehicle.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 159 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetDistanceToLeadingVehicle().
SetForceLaneChange()
void carla::traffic_manager::TrafficManagerRemote::SetForceLaneChange (const ActorPtr & actor, const bool direction) virtual
Method to force lane change on a vehicle.
Direction flag can be set to true for left and false for right.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 147 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetForceLaneChange().
SetGlobalDistanceToLeadingVehicle()
void carla::traffic_manager::TrafficManagerRemote::SetGlobalDistanceToLeadingVehicle (const float distance) virtual
Method to specify Global Distance.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 165 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetGlobalDistanceToLeadingVehicle().
SetGlobalLaneOffset()
void carla::traffic_manager::TrafficManagerRemote::SetGlobalLaneOffset (float const offset) virtual
Method to set a global lane offset displacement from the center line.
Positive values imply a right offset while negative ones mean a left one.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 130 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetGlobalLaneOffset().
SetGlobalPercentageSpeedDifference()
void carla::traffic_manager::TrafficManagerRemote::SetGlobalPercentageSpeedDifference (float const percentage) virtual
Method to set a global % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 120 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetGlobalPercentageSpeedDifference().
SetHybridPhysicsMode()
void carla::traffic_manager::TrafficManagerRemote::SetHybridPhysicsMode (const bool mode_switch) virtual
Method to set hybrid physics mode.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 212 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetHybridPhysicsMode().
SetHybridPhysicsRadius()
void carla::traffic_manager::TrafficManagerRemote::SetHybridPhysicsRadius (const float radius) virtual
Method to set hybrid physics radius.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 216 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetHybridPhysicsRadius().
SetImportedRoute()
void carla::traffic_manager::TrafficManagerRemote::SetImportedRoute (const ActorPtr & actor, const Route route, const bool empty_buffer) virtual
Method to set our own imported route.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 238 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetImportedRoute().
SetKeepRightPercentage()
void carla::traffic_manager::TrafficManagerRemote::SetKeepRightPercentage (const ActorPtr & actor, const float percentage) virtual
Method to set % to keep on the right lane.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 194 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetKeepRightPercentage().
SetLaneOffset()
void carla::traffic_manager::TrafficManagerRemote::SetLaneOffset (const ActorPtr & actor, const float offset) virtual
Method to set a lane offset displacement from the center line.
Positive values imply a right offset while negative ones mean a left one.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 124 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetLaneOffset().
SetMaxBoundaries()
void carla::traffic_manager::TrafficManagerRemote::SetMaxBoundaries (const float lower, const float upper) virtual
Method to set limits for boundaries when respawning vehicles.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 260 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetMaxBoundaries().
SetOSMMode()
void carla::traffic_manager::TrafficManagerRemote::SetOSMMode (const bool mode_switch) virtual
Method to set Open Street Map mode.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 220 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetOSMMode().
SetPercentageIgnoreVehicles()
void carla::traffic_manager::TrafficManagerRemote::SetPercentageIgnoreVehicles (const ActorPtr & actor, const float perc) virtual
Method to specify the % chance of ignoring collisions with any vehicle.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 176 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetPercentageIgnoreVehicles().
SetPercentageIgnoreWalkers()
void carla::traffic_manager::TrafficManagerRemote::SetPercentageIgnoreWalkers (const ActorPtr & actor, const float perc) virtual
Method to specify the % chance of ignoring collisions with any walker.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 170 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetPercentageIgnoreWalkers().
SetPercentageRunningLight()
void carla::traffic_manager::TrafficManagerRemote::SetPercentageRunningLight (const ActorPtr & actor, const float perc) virtual
Method to specify the % chance of running any traffic light.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 182 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetPercentageRunningLight().
SetPercentageRunningSign()
void carla::traffic_manager::TrafficManagerRemote::SetPercentageRunningSign (const ActorPtr & actor, const float perc) virtual
Method to specify the % chance of running any traffic sign.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 188 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetPercentageRunningSign().
SetPercentageSpeedDifference()
void carla::traffic_manager::TrafficManagerRemote::SetPercentageSpeedDifference (const ActorPtr & actor, const float percentage) virtual
Method to set a vehicle's % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 108 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetPercentageSpeedDifference().
SetRandomDeviceSeed()
void carla::traffic_manager::TrafficManagerRemote::SetRandomDeviceSeed (const uint64_t seed) virtual
Method to set randomization seed.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 296 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetRandomDeviceSeed().
SetRandomLeftLaneChangePercentage()
void carla::traffic_manager::TrafficManagerRemote::SetRandomLeftLaneChangePercentage (const ActorPtr & actor, const float percentage) virtual
Method to set % to randomly do a left lane change.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 200 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetRandomLeftLaneChangePercentage().
SetRandomRightLaneChangePercentage()
void carla::traffic_manager::TrafficManagerRemote::SetRandomRightLaneChangePercentage (const ActorPtr & actor, const float percentage) virtual
Method to set % to randomly do a right lane change.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 206 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetRandomRightLaneChangePercentage().
SetRespawnDormantVehicles()
void carla::traffic_manager::TrafficManagerRemote::SetRespawnDormantVehicles (const bool mode_switch) virtual
Method to set automatic respawn of dormant vehicles.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 252 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetRespawnDormantVehicles().
SetSynchronousMode()
void carla::traffic_manager::TrafficManagerRemote::SetSynchronousMode (bool mode) virtual
Method to switch traffic manager into synchronous execution.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 268 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetSynchronousMode().
SetSynchronousModeTimeOutInMiliSecond()
void carla::traffic_manager::TrafficManagerRemote::SetSynchronousModeTimeOutInMiliSecond (double time) virtual
Method to set Tick timeout for synchronous execution.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 272 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetSynchronousModeTimeOutInMiliSecond().
SetUpdateVehicleLights()
void carla::traffic_manager::TrafficManagerRemote::SetUpdateVehicleLights (const ActorPtr & actor, const bool do_update) virtual
Method to set the automatic management of the vehicle lights.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 134 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::SetUpdateVehicleLights().
ShutDown()
void carla::traffic_manager::TrafficManagerRemote::ShutDown () virtual
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 264 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::ShutDown().
Start()
void carla::traffic_manager::TrafficManagerRemote::Start () virtual
To start the TrafficManager.
Until connection active
Create error msg
TSet the error message
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 31 of file TrafficManagerRemote.cpp.
References _cv, _keep_alive, client, episodeProxyTM, carla::traffic_manager::TrafficManagerClient::getServerDetails(), carla::traffic_manager::TrafficManagerClient::HealthCheckRemoteTM(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::traffic_manager::constants::Networking::TM_TIMEOUT.
Referenced by Reset(), and TrafficManagerRemote().
Stop()
void carla::traffic_manager::TrafficManagerRemote::Stop (void) virtual
To stop the TrafficManager.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 70 of file TrafficManagerRemote.cpp.
References _cv, _keep_alive, _mutex, and carla::traffic_manager::constants::Networking::TM_TIMEOUT.
Referenced by Release(), and Reset().
SynchronousTick()
bool carla::traffic_manager::TrafficManagerRemote::SynchronousTick () virtual
Method to provide synchronous tick.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 284 of file TrafficManagerRemote.cpp.
UnregisterVehicles()
void carla::traffic_manager::TrafficManagerRemote::UnregisterVehicles (const std::vector< ActorPtr > & actor_list) virtual
This method unregisters a vehicle from traffic manager.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 100 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::UnregisterVehicle().
UpdateImportedRoute()
void carla::traffic_manager::TrafficManagerRemote::UpdateImportedRoute (const ActorId & actor_id, const Route route) virtual
Method to update an already set route.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 248 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::UpdateImportedRoute().
UpdateUploadPath()
void carla::traffic_manager::TrafficManagerRemote::UpdateUploadPath (const ActorId & actor_id, const Path path) virtual
Method to update an already set path.
Implements carla::traffic_manager::TrafficManagerBase.
Definition at line 234 of file TrafficManagerRemote.cpp.
References client, and carla::traffic_manager::TrafficManagerClient::UpdateUploadPath().
Member Data Documentation
_cv
std::condition_variable carla::traffic_manager::TrafficManagerRemote::_cv private
Definition at line 187 of file TrafficManagerRemote.h.
Referenced by Start(), and Stop().
_keep_alive
bool carla::traffic_manager::TrafficManagerRemote::_keep_alive = true private
Definition at line 191 of file TrafficManagerRemote.h.
Referenced by Start(), and Stop().
_mutex
std::mutex carla::traffic_manager::TrafficManagerRemote::_mutex private
Definition at line 189 of file TrafficManagerRemote.h.
Referenced by Stop().
client
TrafficManagerClient carla::traffic_manager::TrafficManagerRemote::client private
Remote client using the IP and port information it connects to as remote RPC traffic manager server.
Definition at line 182 of file TrafficManagerRemote.h.
Referenced by GetActionBuffer(), GetNextAction(), HealthCheckRemoteTM(), RegisterVehicles(), RemoveImportedRoute(), RemoveUploadPath(), SetAutoLaneChange(), SetBoundariesRespawnDormantVehicles(), SetCollisionDetection(), SetCustomPath(), SetDesiredSpeed(), SetDistanceToLeadingVehicle(), SetForceLaneChange(), SetGlobalDistanceToLeadingVehicle(), SetGlobalLaneOffset(), SetGlobalPercentageSpeedDifference(), SetHybridPhysicsMode(), SetHybridPhysicsRadius(), SetImportedRoute(), SetKeepRightPercentage(), SetLaneOffset(), SetMaxBoundaries(), SetOSMMode(), SetPercentageIgnoreVehicles(), SetPercentageIgnoreWalkers(), SetPercentageRunningLight(), SetPercentageRunningSign(), SetPercentageSpeedDifference(), SetRandomDeviceSeed(), SetRandomLeftLaneChangePercentage(), SetRandomRightLaneChangePercentage(), SetRespawnDormantVehicles(), SetSynchronousMode(), SetSynchronousModeTimeOutInMiliSecond(), SetUpdateVehicleLights(), ShutDown(), Start(), UnregisterVehicles(), UpdateImportedRoute(), and UpdateUploadPath().
episodeProxyTM
carla::client::detail::EpisodeProxy carla::traffic_manager::TrafficManagerRemote::episodeProxyTM private
CARLA client connection object.
Definition at line 185 of file TrafficManagerRemote.h.
Referenced by GetEpisodeProxy(), Reset(), and Start().
The documentation for this class was generated from the following files:
TrafficManagerRemote.h
TrafficManagerRemote.cpp