CARLA: FPixelReader Class Reference
FPixelReader Class Reference
Utils for reading pixels from UTextureRenderTarget2D.
#include <PixelReader.h>
Static Public Member Functions
static TUniquePtr< TImagePixelData< FColor > > DumpPixels (UTextureRenderTarget2D &RenderTarget)
Dump the pixels in RenderTarget.
static TFuture< bool > SavePixelsToDisk (UTextureRenderTarget2D &RenderTarget, const FString &FilePath)
Asynchronously save the pixels in RenderTarget to disk.
static TFuture< bool > SavePixelsToDisk (TUniquePtr< TImagePixelData< FColor >> PixelData, const FString &FilePath)
Asynchronously save the pixels in PixelData to disk.
template<typename TSensor >
static void SendPixelsInRenderThread (TSensor &Sensor)
Convenience function to enqueue a render command that sends the pixels down the Sensor's data stream.
static bool WritePixelsToArray (UTextureRenderTarget2D &RenderTarget, TArray< FColor > &BitMap)
Copy the pixels in RenderTarget into BitMap.
Static Private Member Functions
static void WritePixelsToBuffer (UTextureRenderTarget2D &RenderTarget, carla::Buffer &Buffer, uint32 Offset, FRHICommandListImmediate &InRHICmdList)
Copy the pixels in RenderTarget into Buffer.
Detailed Description
Utils for reading pixels from UTextureRenderTarget2D.
Todo:
This class only supports PF_R8G8B8A8 format.
Definition at line 25 of file PixelReader.h.
Member Function Documentation
TUniquePtr< TImagePixelData< FColor > > FPixelReader::DumpPixels (UTextureRenderTarget2D & RenderTarget) static
Dump the pixels in RenderTarget.
Precondition
To be called from game-thread.
Definition at line 98 of file PixelReader.cpp.
TFuture< bool > FPixelReader::SavePixelsToDisk (UTextureRenderTarget2D & RenderTarget, const FString & FilePath) static
Asynchronously save the pixels in RenderTarget to disk.
Precondition
To be called from game-thread.
Definition at line 110 of file PixelReader.cpp.
Referenced by URoadMap::SaveAsPNG(), and ASceneCaptureSensor::SaveCaptureToDisk().
TFuture< bool > FPixelReader::SavePixelsToDisk (TUniquePtr< TImagePixelData< FColor >> PixelData, const FString & FilePath) static
Asynchronously save the pixels in PixelData to disk.
Precondition
To be called from game-thread.
Definition at line 117 of file PixelReader.cpp.
template<typename TSensor > void FPixelReader::SendPixelsInRenderThread (TSensor & Sensor) static
Convenience function to enqueue a render command that sends the pixels down the Sensor's data stream.
It expects a sensor derived from ASceneCaptureSensor or compatible.
Note that the serializer needs to define a "header_offset" that it's allocated in front of the buffer.
Precondition
To be called from game-thread.
Todo:
Can we make sure the sensor is not going to be destroyed?
Definition at line 85 of file PixelReader.h.
References WritePixelsToBuffer().
Referenced by ADepthCamera::Tick(), ASemanticSegmentationCamera::Tick(), and ASceneCaptureCamera::Tick().
bool FPixelReader::WritePixelsToArray (UTextureRenderTarget2D & RenderTarget, TArray< FColor > & BitMap) static
Copy the pixels in RenderTarget into BitMap.
Precondition
To be called from game-thread.
Definition at line 81 of file PixelReader.cpp.
Referenced by ASceneCaptureSensor::ReadPixels().
void FPixelReader::WritePixelsToBuffer (UTextureRenderTarget2D & RenderTarget, carla::Buffer & Buffer, uint32 Offset, FRHICommandListImmediate & InRHICmdList) static private
Copy the pixels in RenderTarget into Buffer.
Precondition
To be called from render-thread.
Definition at line 133 of file PixelReader.cpp.
References carla::Buffer::begin(), carla::Buffer::copy_from(), carla::Buffer::reset(), LockTexture::Source, LockTexture::Texture, and WritePixelsToBuffer_Vulkan().
Referenced by SendPixelsInRenderThread().
The documentation for this class was generated from the following files:
PixelReader.h
PixelReader.cpp