CARLA: traffic_manager::AtomicActorSet Class Reference
traffic_manager::AtomicActorSet Class Reference
#include <AtomicActorSet.h>
Public Member Functions
AtomicActorSet ()
bool Contains (ActorId id)
void Destroy (ActorPtr actor)
std::vector< ActorPtr > GetList ()
int GetState ()
void Insert (std::vector< ActorPtr > actor_list)
void Remove (std::vector< ActorPtr > actor_list)
Private Attributes
std::unordered_map< ActorId, ActorPtr > actor_set
std::mutex modification_mutex
int state_counter
Detailed Description
Definition at line 22 of file AtomicActorSet.h.
Constructor & Destructor Documentation
traffic_manager::AtomicActorSet::AtomicActorSet () inline
Definition at line 32 of file AtomicActorSet.h.
Member Function Documentation
bool traffic_manager::AtomicActorSet::Contains (ActorId id) inline
Definition at line 76 of file AtomicActorSet.h.
void traffic_manager::AtomicActorSet::Destroy (ActorPtr actor) inline
Definition at line 62 of file AtomicActorSet.h.
References state_counter.
Referenced by traffic_manager::TrafficManager::DestroyVehicle().
std::vector<ActorPtr> traffic_manager::AtomicActorSet::GetList () inline
Definition at line 34 of file AtomicActorSet.h.
Referenced by traffic_manager::LocalizationStage::DataReceiver().
int traffic_manager::AtomicActorSet::GetState () inline
Definition at line 70 of file AtomicActorSet.h.
References state_counter.
Referenced by traffic_manager::LocalizationStage::DataReceiver().
void traffic_manager::AtomicActorSet::Insert (std::vector< ActorPtr > actor_list) inline
Definition at line 44 of file AtomicActorSet.h.
References state_counter.
Referenced by traffic_manager::TrafficManager::RegisterVehicles().
void traffic_manager::AtomicActorSet::Remove (std::vector< ActorPtr > actor_list) inline
Definition at line 53 of file AtomicActorSet.h.
References state_counter.
Referenced by traffic_manager::TrafficManager::UnregisterVehicles().
Member Data Documentation
std::unordered_map<ActorId, ActorPtr> traffic_manager::AtomicActorSet::actor_set private
Definition at line 27 of file AtomicActorSet.h.
std::mutex traffic_manager::AtomicActorSet::modification_mutex private
Definition at line 26 of file AtomicActorSet.h.
int traffic_manager::AtomicActorSet::state_counter private
Definition at line 28 of file AtomicActorSet.h.
Referenced by Destroy(), GetState(), Insert(), and Remove().
The documentation for this class was generated from the following file:
AtomicActorSet.h