CARLA: carla::traffic_manager::TrackTraffic Class Reference
carla::traffic_manager::TrackTraffic Class Reference
#include <LocalizationUtils.h>
Public Member Functions
void DeleteActor (ActorId actor_id)
Method to delete actor data from tracking.
std::unordered_map< GeoGridId, ActorIdSet > GetGridActors ()
std::unordered_set< GeoGridId > GetGridIds (ActorId actor_id)
ActorIdSet GetOverlappingVehicles (ActorId actor_id)
ActorIdSet GetPassingVehicles (uint64_t waypoint_id)
std::pair< SimpleWaypointPtr, uint64_t > GetTargetWaypoint (const Buffer &waypoint_buffer, const float &target_point_distance)
Method to return the wayPoints from the waypoint Buffer by using target point distance.
void RemovePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
TrackTraffic ()
void UpdateGridPosition (const ActorId actor_id, const Buffer &buffer)
void UpdatePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
Methods to update, remove and retrieve vehicles passing through a waypoint.
void UpdateUnregisteredGridPosition (const ActorId actor_id, const SimpleWaypointPtr &waypoint)
Private Types
using WaypointOverlap = std::unordered_map< uint64_t, ActorIdSet >
Structure to keep track of overlapping waypoints between vehicles.
Private Attributes
ActorIdSet actor_id_set_record
Stored vehicle id set record.
std::unordered_map< ActorId, std::unordered_set< GeoGridId > > actor_to_grids
Geodesic grids occupied by actors's paths.
std::unordered_map< GeoGridId, ActorIdSet > grid_to_actors
Actors currently passing through grids.
WaypointOverlap waypoint_overlap_tracker
Detailed Description
Definition at line 31 of file LocalizationUtils.h.
Member Typedef Documentation
using carla::traffic_manager::TrackTraffic::WaypointOverlap = std::unordered_map<uint64_t, ActorIdSet> private
Structure to keep track of overlapping waypoints between vehicles.
Definition at line 35 of file LocalizationUtils.h.
Constructor & Destructor Documentation
carla::traffic_manager::TrackTraffic::TrackTraffic ()
Definition at line 63 of file LocalizationUtils.cpp.
Member Function Documentation
void carla::traffic_manager::TrackTraffic::DeleteActor (ActorId actor_id)
Method to delete actor data from tracking.
Definition at line 167 of file LocalizationUtils.cpp.
Referenced by carla::traffic_manager::LocalizationStage::CleanActor(), carla::traffic_manager::LocalizationStage::DataReceiver(), and carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles().
std::unordered_map< GeoGridId, ActorIdSet > carla::traffic_manager::TrackTraffic::GetGridActors ()
Definition at line 194 of file LocalizationUtils.cpp.
std::unordered_set< GeoGridId > carla::traffic_manager::TrackTraffic::GetGridIds (ActorId actor_id)
Definition at line 183 of file LocalizationUtils.cpp.
ActorIdSet carla::traffic_manager::TrackTraffic::GetOverlappingVehicles (ActorId actor_id)
Definition at line 150 of file LocalizationUtils.cpp.
Referenced by carla::traffic_manager::LocalizationStage::Action(), and carla::traffic_manager::LocalizationStage::AssignLaneChange().
ActorIdSet carla::traffic_manager::TrackTraffic::GetPassingVehicles (uint64_t waypoint_id)
Definition at line 227 of file LocalizationUtils.cpp.
Referenced by carla::traffic_manager::LocalizationStage::AssignLaneChange().
std::pair< SimpleWaypointPtr, uint64_t > carla::traffic_manager::TrackTraffic::GetTargetWaypoint (const Buffer & waypoint_buffer, const float & target_point_distance)
Method to return the wayPoints from the waypoint Buffer by using target point distance.
Condition to determine forward or backward scanning of WayPoint Buffer.
Definition at line 237 of file LocalizationUtils.cpp.
References carla::traffic_manager::LocalizationConstants::SAMPLING_RESOLUTION.
Referenced by carla::traffic_manager::LocalizationStage::Action().
void carla::traffic_manager::TrackTraffic::RemovePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
Definition at line 212 of file LocalizationUtils.cpp.
Referenced by carla::traffic_manager::LocalizationStage::CleanActor(), and carla::traffic_manager::LocalizationStage::PopWaypoint().
void carla::traffic_manager::TrackTraffic::UpdateGridPosition (const ActorId actor_id, const Buffer & buffer)
Definition at line 106 of file LocalizationUtils.cpp.
References carla::traffic_manager::LocalizationConstants::BUFFER_STEP_THROUGH.
Referenced by carla::traffic_manager::LocalizationStage::Action().
void carla::traffic_manager::TrackTraffic::UpdatePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
Methods to update, remove and retrieve vehicles passing through a waypoint.
Definition at line 198 of file LocalizationUtils.cpp.
Referenced by carla::traffic_manager::LocalizationStage::PushWaypoint().
void carla::traffic_manager::TrackTraffic::UpdateUnregisteredGridPosition (const ActorId actor_id, const SimpleWaypointPtr & waypoint)
Definition at line 65 of file LocalizationUtils.cpp.
Referenced by carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles().
Member Data Documentation
ActorIdSet carla::traffic_manager::TrackTraffic::actor_id_set_record private
Stored vehicle id set record.
Definition at line 38 of file LocalizationUtils.h.
std::unordered_map<ActorId, std::unordered_set<GeoGridId> > carla::traffic_manager::TrackTraffic::actor_to_grids private
Geodesic grids occupied by actors's paths.
Definition at line 40 of file LocalizationUtils.h.
std::unordered_map<GeoGridId, ActorIdSet> carla::traffic_manager::TrackTraffic::grid_to_actors private
Actors currently passing through grids.
Definition at line 42 of file LocalizationUtils.h.
WaypointOverlap carla::traffic_manager::TrackTraffic::waypoint_overlap_tracker private
Definition at line 36 of file LocalizationUtils.h.
The documentation for this class was generated from the following files:
LocalizationUtils.h
LocalizationUtils.cpp