CARLA: test_streaming.cpp File Reference
test_streaming.cpp File Reference
#include "test.h"
#include <carla/ThreadGroup.h>
#include <carla/streaming/Client.h>
#include <carla/streaming/Server.h>
#include <carla/streaming/detail/Dispatcher.h>
#include <carla/streaming/detail/tcp/Client.h>
#include <carla/streaming/detail/tcp/Server.h>
#include <carla/streaming/low_level/Client.h>
#include <carla/streaming/low_level/Server.h>
#include <atomic>
Classes
struct DoneGuard
class io_context_running
Functions
TEST (streaming, low_level_sending_strings)
TEST (streaming, low_level_unsubscribing)
TEST (streaming, low_level_tcp_small_message)
TEST (streaming, stream_outlives_server)
TEST (streaming, multi_stream)
Function Documentation
TEST (streaming , low_level_sending_strings)
Definition at line 45 of file test_streaming.cpp.
References util::buffer::as_string(), carla::streaming::low_level::Server< T >::MakeStream(), io_context_running::service, carla::streaming::low_level::Server< T >::SetTimeout(), carla::streaming::Client::Subscribe(), and TESTING_PORT.
TEST (streaming , low_level_unsubscribing)
Definition at line 80 of file test_streaming.cpp.
References util::buffer::as_string(), carla::streaming::low_level::Server< T >::MakeStream(), io_context_running::service, carla::streaming::low_level::Server< T >::SetTimeout(), carla::streaming::Client::Subscribe(), TESTING_PORT, and carla::streaming::Client::UnSubscribe().
TEST (streaming , low_level_tcp_small_message)
Definition at line 123 of file test_streaming.cpp.
References util::buffer::as_string(), carla::ThreadGroup::CreateThreads(), carla::streaming::detail::tcp::Server::GetLocalEndpoint(), carla::streaming::detail::tcp::Server::Listen(), carla::streaming::detail::Dispatcher::MakeStream(), carla::streaming::detail::tcp::Server::SetTimeout(), and TESTING_PORT.
TEST (streaming , stream_outlives_server)
Definition at line 176 of file test_streaming.cpp.
References util::buffer::as_string(), carla::streaming::Client::AsyncRun(), carla::ThreadGroup::CreateThread(), carla::streaming::low_level::Server< T >::MakeStream(), carla::streaming::Client::Subscribe(), and TESTING_PORT.
TEST (streaming , multi_stream)
Definition at line 220 of file test_streaming.cpp.
References util::buffer::as_string(), carla::streaming::low_level::Server< T >::MakeMultiStream(), and TESTING_PORT.