CARLA: carla::sensor::s11n::GBufferUint8Serializer Class Reference
carla::sensor::s11n::GBufferUint8Serializer Class Reference
Serializes image buffers generated by camera sensors.
#include <GBufferUint8Serializer.h>
Classes
struct ImageHeader
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static const ImageHeader & DeserializeHeader (const RawData &data)
template<typename Sensor >
static Buffer Serialize (const Sensor &sensor, Buffer &&bitmap, uint32_t ImageWidth, uint32_t ImageHeight, float FovAngle)
Static Public Attributes
static constexpr auto header_offset = sizeof(ImageHeader)
Detailed Description
Serializes image buffers generated by camera sensors.
Definition at line 23 of file GBufferUint8Serializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::GBufferUint8Serializer::Deserialize (RawData && data) static
Definition at line 15 of file GBufferUint8Serializer.cpp.
Referenced by DeserializeHeader().
DeserializeHeader()
static const ImageHeader& carla::sensor::s11n::GBufferUint8Serializer::DeserializeHeader (const RawData & data) inline static
Definition at line 36 of file GBufferUint8Serializer.h.
References carla::sensor::RawData::begin(), Deserialize(), and Serialize().
Serialize()
template<typename Sensor > Buffer carla::sensor::s11n::GBufferUint8Serializer::Serialize (const Sensor & sensor, Buffer && bitmap, uint32_t ImageWidth, uint32_t ImageHeight, float FovAngle) inline static
Definition at line 48 of file GBufferUint8Serializer.h.
References DEBUG_ASSERT.
Referenced by DeserializeHeader().
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::GBufferUint8Serializer::header_offset = sizeof(ImageHeader) static
Definition at line 34 of file GBufferUint8Serializer.h.
The documentation for this class was generated from the following files:
GBufferUint8Serializer.h
GBufferUint8Serializer.cpp