CARLA: ARayCastRawLidar Class Reference
ARayCastRawLidar Class Reference
A ray-cast based Lidar sensor.
#include <RayCastRawLidar.h>
Public Member Functions
ARayCastRawLidar (const FObjectInitializer &ObjectInitializer)
virtual void Set (const FActorDescription &Description) override
virtual void Set (const FLidarDescription &LidarDescription)
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
Static Public Member Functions
static FActorDefinition GetSensorDefinition ()
Protected Types
using FLidarRawData = carla::sensor::data::LidarRawData
using FRawDetection = carla::sensor::data::LidarRawDetection
Protected Member Functions
virtual void ComputeAndSaveDetections (const FTransform &SensorTransform)
This method uses all the saved FHitResults, compute the RawDetections and then send it to the LidarData structure.
void ComputeRawDetection (const FHitResult &HitInfo, const FTransform &SensorTransf, FRawDetection &Detection) const
Compute all raw detection information.
void CreateLasers ()
Creates a Laser for each channel.
virtual bool PreprocessRay () const
Method that allow to preprocess the ray before shoot it.
void ResetRecordedHits (uint32_t Channels, uint32_t MaxPointsPerChannel)
Clear the recorded data structure.
bool ShootLaser (const float VerticalAngle, float HorizontalAngle, FHitResult &RawData) const
Shoot a laser ray-trace, return whether the laser hit something.
void SimulateLidar (float DeltaTime)
Updates LidarMeasurement with the points read in DeltaTime.
virtual void Tick (float DeltaTime) override
void WritePointAsync (uint32_t Channel, FHitResult &Detection)
Saving the hits the raycast returns per channel.
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
const UCarlaEpisode & GetEpisode () const
void PostActorCreated () override
Protected Attributes
FLidarDescription Description
TArray< float > LaserAngles
std::vector< uint32_t > PointsPerChannel
std::vector< std::vector< FHitResult > > RecordedHits
Protected Attributes inherited from ASensor
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Private Attributes
FLidarRawData LidarRawData
Detailed Description
A ray-cast based Lidar sensor.
Definition at line 25 of file RayCastRawLidar.h.
Member Typedef Documentation
using ARayCastRawLidar::FLidarRawData = carla::sensor::data::LidarRawData protected
Definition at line 31 of file RayCastRawLidar.h.
using ARayCastRawLidar::FRawDetection = carla::sensor::data::LidarRawDetection protected
Definition at line 32 of file RayCastRawLidar.h.
Constructor & Destructor Documentation
ARayCastRawLidar::ARayCastRawLidar (const FObjectInitializer & ObjectInitializer)
Definition at line 27 of file RayCastRawLidar.cpp.
Member Function Documentation
void ARayCastRawLidar::ComputeAndSaveDetections (const FTransform & SensorTransform) protected virtual
This method uses all the saved FHitResults, compute the RawDetections and then send it to the LidarData structure.
Reimplemented in ARayCastLidar.
Definition at line 141 of file RayCastRawLidar.cpp.
References FLidarDescription::Channels, ComputeRawDetection(), Description, LidarRawData, PointsPerChannel, RecordedHits, carla::sensor::data::LidarRawData::ResetSerPoints(), and carla::sensor::data::LidarRawData::WritePointSync().
Referenced by SimulateLidar().
void ARayCastRawLidar::ComputeRawDetection (const FHitResult & HitInfo, const FTransform & SensorTransf, FRawDetection & Detection) const protected
Compute all raw detection information.
Definition at line 155 of file RayCastRawLidar.cpp.
References carla::sensor::data::LidarRawDetection::cos_inc_angle, FActorInfo::Description, FActorRegistry::Find(), FActorView::GetActorInfo(), UCarlaEpisode::GetActorRegistry(), ASensor::GetEpisode(), FActorView::IsValid(), None, carla::sensor::data::LidarRawDetection::object_idx, carla::sensor::data::LidarRawDetection::object_tag, carla::sensor::data::LidarRawDetection::point, and FActorDescription::UId.
Referenced by ComputeAndSaveDetections().
void ARayCastRawLidar::CreateLasers () protected
Creates a Laser for each channel.
Definition at line 49 of file RayCastRawLidar.cpp.
References FLidarDescription::Channels, Description, LaserAngles, FLidarDescription::LowerFovLimit, and FLidarDescription::UpperFovLimit.
Referenced by ARayCastLidar::Set(), and Set().
FActorDefinition ARayCastRawLidar::GetSensorDefinition () static
Definition at line 22 of file RayCastRawLidar.cpp.
References UActorBlueprintFunctionLibrary::MakeLidarDefinition().
virtual bool ARayCastRawLidar::PreprocessRay () const inline protected virtual
Method that allow to preprocess the ray before shoot it.
Reimplemented in ARayCastLidar.
Definition at line 55 of file RayCastRawLidar.h.
Referenced by SimulateLidar().
void ARayCastRawLidar::ResetRecordedHits (uint32_t Channels, uint32_t MaxPointsPerChannel) protected
Clear the recorded data structure.
Definition at line 128 of file RayCastRawLidar.cpp.
References RecordedHits.
Referenced by SimulateLidar().
void ARayCastRawLidar::Set (const FActorDescription & Description) override virtual
Reimplemented from ASensor.
Reimplemented in ARayCastLidar.
Definition at line 33 of file RayCastRawLidar.cpp.
References UActorBlueprintFunctionLibrary::SetLidar().
void ARayCastRawLidar::Set (const FLidarDescription & LidarDescription) virtual
Reimplemented in ARayCastLidar.
Definition at line 41 of file RayCastRawLidar.cpp.
References FLidarDescription::Channels, CreateLasers(), Description, LidarRawData, and PointsPerChannel.
bool ARayCastRawLidar::ShootLaser (const float VerticalAngle, float HorizontalAngle, FHitResult & RawData) const protected
Shoot a laser ray-trace, return whether the laser hit something.
Definition at line 188 of file RayCastRawLidar.cpp.
References Description, and FLidarDescription::Range.
Referenced by SimulateLidar().
void ARayCastRawLidar::SimulateLidar (float DeltaTime) protected
Updates LidarMeasurement with the points read in DeltaTime.
Definition at line 75 of file RayCastRawLidar.cpp.
References FLidarDescription::Channels, ComputeAndSaveDetections(), Description, carla::sensor::data::LidarRawData::GetHorizontalAngle(), LaserAngles, LidarRawData, FLidarDescription::PointsPerSecond, PreprocessRay(), ResetRecordedHits(), FLidarDescription::RotationFrequency, carla::sensor::data::LidarRawData::SetHorizontalAngle(), ShootLaser(), carla::geom::Math::ToDegrees(), carla::geom::Math::ToRadians(), and WritePointAsync().
Referenced by Tick(), and ARayCastLidar::Tick().
void ARayCastRawLidar::Tick (float DeltaTime) override protected virtual
Reimplemented in ARayCastLidar.
Definition at line 65 of file RayCastRawLidar.cpp.
References ASensor::GetDataStream(), LidarRawData, and SimulateLidar().
void ARayCastRawLidar::WritePointAsync (uint32_t Channel, FHitResult & Detection) protected
Saving the hits the raycast returns per channel.
Definition at line 136 of file RayCastRawLidar.cpp.
References DEBUG_ASSERT, and RecordedHits.
Referenced by SimulateLidar().
Member Data Documentation
FLidarDescription ARayCastRawLidar::Description protected
Definition at line 75 of file RayCastRawLidar.h.
Referenced by ARayCastLidar::ComputeAndSaveDetections(), ComputeAndSaveDetections(), ARayCastLidar::ComputeDetection(), ARayCastLidar::ComputeIntensity(), CreateLasers(), ARayCastLidar::PostprocessDetection(), ARayCastLidar::PreprocessRay(), ARayCastLidar::Set(), Set(), ShootLaser(), and SimulateLidar().
TArray<float> ARayCastRawLidar::LaserAngles protected
Definition at line 77 of file RayCastRawLidar.h.
Referenced by CreateLasers(), and SimulateLidar().
FLidarRawData ARayCastRawLidar::LidarRawData private
Definition at line 83 of file RayCastRawLidar.h.
Referenced by ComputeAndSaveDetections(), Set(), SimulateLidar(), and Tick().
std::vector<uint32_t> ARayCastRawLidar::PointsPerChannel protected
Definition at line 80 of file RayCastRawLidar.h.
Referenced by ARayCastLidar::ComputeAndSaveDetections(), ComputeAndSaveDetections(), ARayCastLidar::Set(), and Set().
std::vector<std::vector<FHitResult> > ARayCastRawLidar::RecordedHits protected
Definition at line 79 of file RayCastRawLidar.h.
Referenced by ARayCastLidar::ComputeAndSaveDetections(), ComputeAndSaveDetections(), ResetRecordedHits(), and WritePointAsync().
The documentation for this class was generated from the following files:
RayCastRawLidar.h
RayCastRawLidar.cpp