CARLA: carla::geom::Location Class Reference
carla::geom::Location Class Reference
#include <Location.h>
Public Member Functions
auto Distance (const Location &loc) const
Location ()=default
Location (const Vector3D &rhs)
Location (const Vector3DInt &rhs)
bool operator!= (const Location &rhs) const
Location & operator+= (const Location &rhs)
Location & operator-= (const Location &rhs)
bool operator== (const Location &rhs) const
Public Member Functions inherited from carla::geom::Vector3D
Vector3D Abs () const
float Length () const
Vector3D MakeSafeUnitVector (const float epsilon) const
Vector3D MakeUnitVector () const
template<typename MSGPACK_OBJECT >
void msgpack_object (MSGPACK_OBJECT *o, clmdep_msgpack::zone &sneaky_variable_that_shadows_z) const
template<typename Packer >
void msgpack_pack (Packer &pk) const
void msgpack_unpack (clmdep_msgpack::object const &o)
bool operator!= (const Vector3D &rhs) const
Vector3D & operator*= (float rhs)
Vector3D & operator+= (const Vector3D &rhs)
Vector3D & operator-= (const Vector3D &rhs)
Vector3D & operator/= (float rhs)
bool operator== (const Vector3D &rhs) const
float SquaredLength () const
Vector3D ()=default
Vector3D (float ix, float iy, float iz)
Friends
Location operator+ (Location lhs, const Location &rhs)
Location operator- (Location lhs, const Location &rhs)
Additional Inherited Members
Public Attributes inherited from carla::geom::Vector3D
float x = 0.0f
float y = 0.0f
float z = 0.0f
Detailed Description
Definition at line 20 of file geom/Location.h.
Constructor & Destructor Documentation
Location() [1/3]
carla::geom::Location::Location () default
Referenced by operator!=().
Location() [2/3]
carla::geom::Location::Location (const Vector3D & rhs) inline
Definition at line 31 of file geom/Location.h.
Location() [3/3]
carla::geom::Location::Location (const Vector3DInt & rhs) inline
Definition at line 33 of file geom/Location.h.
Member Function Documentation
Distance()
auto carla::geom::Location::Distance (const Location & loc) const inline
Definition at line 42 of file geom/Location.h.
References carla::geom::Math::Distance().
Referenced by carla::traffic_manager::SimpleWaypoint::Distance(), and carla::traffic_manager::MotionPlanStage::Update().
operator!=()
bool carla::geom::Location::operator!= (const Location & rhs) const inline
Definition at line 78 of file geom/Location.h.
References Location(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
operator+=()
Location& carla::geom::Location::operator+= (const Location & rhs) inline
Definition at line 50 of file geom/Location.h.
operator-=()
Location& carla::geom::Location::operator-= (const Location & rhs) inline
Definition at line 60 of file geom/Location.h.
operator==()
bool carla::geom::Location::operator== (const Location & rhs) const inline
Definition at line 74 of file geom/Location.h.
Friends And Related Function Documentation
operator+
Location operator+ (Location lhs, const Location & rhs) friend
Definition at line 55 of file geom/Location.h.
operator-
Location operator- (Location lhs, const Location & rhs) friend
Definition at line 65 of file geom/Location.h.
The documentation for this class was generated from the following file:
geom/Location.h