CARLA: FDenseTile Struct Reference
FDenseTile Struct Reference
#include <CustomTerrainPhysicsComponent.h>
Public Member Functions
std::vector< FParticle * > GetParticlesInRadius (FDVector Position, float Radius)
void InitializeTile (float ParticleSize, float Depth, FDVector TileOrigin, FDVector TileEnd, const FString &SavePath, const FHeightMapData &HeightMap)
void ModifyDataFromString (const std::string &BaseString)
std::string ToString () const
Public Attributes
std::vector< FParticle > Particles
FDVector TilePosition
Detailed Description
Definition at line 48 of file CustomTerrainPhysicsComponent.h.
Member Function Documentation
GetParticlesInRadius()
std::vector< FParticle * > FDenseTile::GetParticlesInRadius (FDVector Position, float Radius)
Definition at line 143 of file CustomTerrainPhysicsComponent.cpp.
References FParticle::Radius.
Referenced by FSparseHighDetailMap::GetParticlesInRadius().
InitializeTile()
void FDenseTile::InitializeTile (float ParticleSize, float Depth, FDVector TileOrigin, FDVector TileEnd, const FString & SavePath, const FHeightMapData & HeightMap)
Definition at line 102 of file CustomTerrainPhysicsComponent.cpp.
References ReadFVector(), FDVector::ToString(), FDVector::X, FDVector::Y, and FDVector::Z.
Referenced by FSparseHighDetailMap::InitializeRegion().
ModifyDataFromString()
void FDenseTile::ModifyDataFromString (const std::string & BaseString)
Definition at line 166 of file CustomTerrainPhysicsComponent.cpp.
References FSparseHighDetailMap::GetParticlesInRadius(), and FParticle::ModifyDataFromString().
ToString()
std::string FDenseTile::ToString () const
Definition at line 156 of file CustomTerrainPhysicsComponent.cpp.
Member Data Documentation
Particles
std::vector<FParticle> FDenseTile::Particles
Definition at line 61 of file CustomTerrainPhysicsComponent.h.
TilePosition
FDVector FDenseTile::TilePosition
Definition at line 62 of file CustomTerrainPhysicsComponent.h.
The documentation for this struct was generated from the following files:
CustomTerrainPhysicsComponent.h
CustomTerrainPhysicsComponent.cpp