CARLA: carla::sensor::s11n::OpticalFlowImageSerializer Class Reference
carla::sensor::s11n::OpticalFlowImageSerializer Class Reference
Serializes image buffers generated by camera sensors.
#include <OpticalFlowImageSerializer.h>
Classes
struct ImageHeader
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static const ImageHeader & DeserializeHeader (const RawData &data)
template<typename Sensor >
static Buffer Serialize (const Sensor &sensor, Buffer &&bitmap)
Static Public Attributes
static constexpr auto header_offset = sizeof(ImageHeader)
Detailed Description
Serializes image buffers generated by camera sensors.
Definition at line 21 of file OpticalFlowImageSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::OpticalFlowImageSerializer::Deserialize (RawData && data) static
Definition at line 14 of file OpticalFlowImageSerializer.cpp.
Referenced by DeserializeHeader().
DeserializeHeader()
static const ImageHeader& carla::sensor::s11n::OpticalFlowImageSerializer::DeserializeHeader (const RawData & data) inline static
Definition at line 34 of file OpticalFlowImageSerializer.h.
References carla::sensor::RawData::begin(), Deserialize(), and Serialize().
Serialize()
template<typename Sensor > Buffer carla::sensor::s11n::OpticalFlowImageSerializer::Serialize (const Sensor & sensor, Buffer && bitmap) inline static
Definition at line 45 of file OpticalFlowImageSerializer.h.
References DEBUG_ASSERT.
Referenced by DeserializeHeader().
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::OpticalFlowImageSerializer::header_offset = sizeof(ImageHeader) static
Definition at line 32 of file OpticalFlowImageSerializer.h.
The documentation for this class was generated from the following files:
OpticalFlowImageSerializer.h
OpticalFlowImageSerializer.cpp