CARLA: CarlaRecorderAnimWalkers Class Reference
CarlaRecorderAnimWalkers Class Reference
#include <CarlaRecorderAnimWalker.h>
Public Member Functions
void Add (const CarlaRecorderAnimWalker &InObj)
void Clear (void)
const std::vector< CarlaRecorderAnimWalker > & GetWalkers ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderAnimWalker > Walkers
Detailed Description
Definition at line 25 of file CarlaRecorderAnimWalker.h.
Member Function Documentation
Add()
void CarlaRecorderAnimWalkers::Add (const CarlaRecorderAnimWalker & InObj)
Definition at line 31 of file CarlaRecorderAnimWalker.cpp.
Referenced by FFrameData::AddAnimWalker(), and ACarlaRecorder::AddAnimWalker().
Clear()
void CarlaRecorderAnimWalkers::Clear (void)
Definition at line 26 of file CarlaRecorderAnimWalker.cpp.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetWalkers()
const std::vector< CarlaRecorderAnimWalker > & CarlaRecorderAnimWalkers::GetWalkers ()
Definition at line 71 of file CarlaRecorderAnimWalker.cpp.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderAnimWalkers::Read (std::istream & InFile)
Definition at line 57 of file CarlaRecorderAnimWalker.cpp.
References CarlaRecorderAnimWalker::Read().
Referenced by FFrameData::Read().
Write()
void CarlaRecorderAnimWalkers::Write (std::ostream & OutFile)
Definition at line 36 of file CarlaRecorderAnimWalker.cpp.
References AnimWalker.
Referenced by FFrameData::Write(), and ACarlaRecorder::Write().
Member Data Documentation
Walkers
std::vector<CarlaRecorderAnimWalker> CarlaRecorderAnimWalkers::Walkers private
Definition at line 41 of file CarlaRecorderAnimWalker.h.
The documentation for this class was generated from the following files:
CarlaRecorderAnimWalker.h
CarlaRecorderAnimWalker.cpp