CARLA: test_rpc.cpp File Reference
test_rpc.cpp File Reference
#include "test.h"
#include <carla/MsgPackAdaptors.h>
#include <carla/ThreadGroup.h>
#include <carla/rpc/Actor.h>
#include <carla/rpc/Client.h>
#include <carla/rpc/Response.h>
#include <carla/rpc/Server.h>
#include <thread>
Functions
TEST (rpc, compilation_tests)
TEST (rpc, server_bind_sync_run_on_game_thread)
Function Documentation
TEST() [1/2]
TEST (rpc , compilation_tests)
Definition at line 21 of file test_rpc.cpp.
References carla::rpc::Server::BindSync(), and TESTING_PORT.
TEST() [2/2]
TEST (rpc , server_bind_sync_run_on_game_thread)
Definition at line 29 of file test_rpc.cpp.
References carla::rpc::Server::AsyncRun(), carla::rpc::Server::BindSync(), carla::rpc::Client::call(), carla::ThreadGroup::CreateThread(), carla::rpc::Server::SyncRunFor(), and TESTING_PORT.