CARLA: UOpenDriveMap_Private Namespace Reference
UOpenDriveMap_Private Namespace Reference
Functions
template<typename RangeT >
static auto GetSize (const RangeT &Range)
template<typename T >
static auto GetSize (const TArray< T > &Array)
template<typename T , typename RangeT , typename FuncT >
static TArray< T > TransformToTArray (RangeT &&Range, FuncT &&TransformFunction)
template<typename T , typename RangeT >
static TArray< T > TransformToTArray (RangeT &&Range)
Function Documentation
template<typename RangeT > static auto UOpenDriveMap_Private::GetSize (const RangeT & Range) static
Definition at line 18 of file OpenDriveMap.cpp.
Referenced by UActorBlueprintFunctionLibrary::MakePropDefinition(), and TransformToTArray().
template<typename T > static auto UOpenDriveMap_Private::GetSize (const TArray< T > & Array) static
Definition at line 24 of file OpenDriveMap.cpp.
template<typename T , typename RangeT , typename FuncT > static TArray<T> UOpenDriveMap_Private::TransformToTArray (RangeT && Range, FuncT && TransformFunction) static
Definition at line 31 of file OpenDriveMap.cpp.
References GetSize().
template<typename T , typename RangeT > static TArray<T> UOpenDriveMap_Private::TransformToTArray (RangeT && Range) static
Definition at line 43 of file OpenDriveMap.cpp.