CARLA: FSensorDefinitionGatherer Class Reference
FSensorDefinitionGatherer Class Reference
Retrieve the definitions of all the sensors registered in the SensorRegistry by calling their static method SensorType::GetSensorDefinition().
Classes
struct is_spawnable
struct is_spawnable< T, typename void_type< typename T::not_spawnable >::type >
struct void_type
Static Public Member Functions
static auto GetSensorDefinitions ()
Private Types
using Registry = carla::sensor::SensorRegistry
Static Private Member Functions
template<typename SensorType >
static std::enable_if< is_spawnable< SensorType >::value, void >::type AppendDefinitions (TArray< FActorDefinition > &Definitions)
template<typename SensorType >
static std::enable_if<!is_spawnable< SensorType >::value, void >::type AppendDefinitions (TArray< FActorDefinition > &)
template<size_t Index>
static void AppendDefinitions (TArray< FActorDefinition > &Definitions)
template<size_t... Is>
static void AppendDefinitions (TArray< FActorDefinition > &Definitions, std::index_sequence< Is... >)
Detailed Description
Retrieve the definitions of all the sensors registered in the SensorRegistry by calling their static method SensorType::GetSensorDefinition().
Note
To make this class ignore a given sensor, define a public member "not_spawnable" that defines a type. If so, the sensor won't be spawned by this factory.
Definition at line 35 of file SensorFactory.cpp.
Member Typedef Documentation
Registry
using FSensorDefinitionGatherer::Registry = carla::sensor::SensorRegistry private
Definition at line 37 of file SensorFactory.cpp.
Member Function Documentation
AppendDefinitions() [1/4]
template<typename SensorType > static std::enable_if<is_spawnable<SensorType>::value, void>::type FSensorDefinitionGatherer::AppendDefinitions (TArray< FActorDefinition > & Definitions) inline static private
Definition at line 66 of file SensorFactory.cpp.
Referenced by GetSensorDefinitions().
AppendDefinitions() [2/4]
template<typename SensorType > static std::enable_if<!is_spawnable<SensorType>::value, void>::type FSensorDefinitionGatherer::AppendDefinitions (TArray< FActorDefinition > &) inline static private
Definition at line 76 of file SensorFactory.cpp.
AppendDefinitions() [3/4]
template<size_t Index> static void FSensorDefinitionGatherer::AppendDefinitions (TArray< FActorDefinition > & Definitions) inline static private
Definition at line 79 of file SensorFactory.cpp.
AppendDefinitions() [4/4]
template<size_t... Is> static void FSensorDefinitionGatherer::AppendDefinitions (TArray< FActorDefinition > & Definitions, std::index_sequence< Is... >) inline static private
Definition at line 87 of file SensorFactory.cpp.
GetSensorDefinitions()
static auto FSensorDefinitionGatherer::GetSensorDefinitions () inline static
Definition at line 41 of file SensorFactory.cpp.
References AppendDefinitions(), and carla::sensor::CompileTimeTypeMap< Items... >::size().
Referenced by ASensorFactory::GetDefinitions().
The documentation for this class was generated from the following file:
SensorFactory.cpp