CARLA: AGnssSensor Class Reference
AGnssSensor Class Reference
Gnss sensor representation The actual position calculation is done one server side.
#include <GnssSensor.h>
Public Member Functions
AGnssSensor (const FObjectInitializer &ObjectInitializer)
float GetAltitudeBias () const
float GetAltitudeDeviation () const
float GetLatitudeBias () const
float GetLatitudeDeviation () const
float GetLongitudeBias () const
float GetLongitudeDeviation () const
void Set (const FActorDescription &ActorDescription)
void SetAltitudeBias (float Value)
void SetAltitudeDeviation (float Value)
void SetLatitudeBias (float Value)
void SetLatitudeDeviation (float Value)
void SetLongitudeBias (float Value)
void SetLongitudeDeviation (float Value)
void Tick (float DeltaSeconds) override
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
Static Public Member Functions
static FActorDefinition GetSensorDefinition ()
Protected Member Functions
virtual void BeginPlay () override
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
const UCarlaEpisode & GetEpisode () const
void PostActorCreated () override
Private Attributes
float AltitudeBias
float AltitudeDeviation
carla::geom::GeoLocation CurrentGeoReference
float LatitudeBias
float LatitudeDeviation
float LongitudeBias
float LongitudeDeviation
Additional Inherited Members
Protected Attributes inherited from ASensor
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Detailed Description
Gnss sensor representation The actual position calculation is done one server side.
Definition at line 23 of file GnssSensor.h.
Constructor & Destructor Documentation
AGnssSensor::AGnssSensor (const FObjectInitializer & ObjectInitializer)
Definition at line 15 of file GnssSensor.cpp.
References ASensor::RandomEngine.
Member Function Documentation
void AGnssSensor::BeginPlay () override protected virtual
Definition at line 111 of file GnssSensor.cpp.
References CurrentGeoReference, UCarlaStatics::GetCurrentEpisode(), and UCarlaEpisode::GetGeoReference().
float AGnssSensor::GetAltitudeBias () const
Definition at line 106 of file GnssSensor.cpp.
References AltitudeBias.
float AGnssSensor::GetAltitudeDeviation () const
Definition at line 93 of file GnssSensor.cpp.
References AltitudeDeviation.
float AGnssSensor::GetLatitudeBias () const
Definition at line 98 of file GnssSensor.cpp.
References LatitudeBias.
float AGnssSensor::GetLatitudeDeviation () const
Definition at line 85 of file GnssSensor.cpp.
References LatitudeDeviation.
float AGnssSensor::GetLongitudeBias () const
Definition at line 102 of file GnssSensor.cpp.
References LongitudeBias.
float AGnssSensor::GetLongitudeDeviation () const
Definition at line 89 of file GnssSensor.cpp.
References LongitudeDeviation.
FActorDefinition AGnssSensor::GetSensorDefinition () static
Definition at line 22 of file GnssSensor.cpp.
References UActorBlueprintFunctionLibrary::MakeGnssDefinition().
void AGnssSensor::Set (const FActorDescription & ActorDescription) virtual
Reimplemented from ASensor.
Definition at line 27 of file GnssSensor.cpp.
References UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::SetAltitudeBias (float Value)
Definition at line 80 of file GnssSensor.cpp.
References AltitudeBias.
Referenced by UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::SetAltitudeDeviation (float Value)
Definition at line 65 of file GnssSensor.cpp.
References AltitudeDeviation.
Referenced by UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::SetLatitudeBias (float Value)
Definition at line 70 of file GnssSensor.cpp.
References LatitudeBias.
Referenced by UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::SetLatitudeDeviation (float Value)
Definition at line 55 of file GnssSensor.cpp.
References LatitudeDeviation.
Referenced by UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::SetLongitudeBias (float Value)
Definition at line 75 of file GnssSensor.cpp.
References LongitudeBias.
Referenced by UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::SetLongitudeDeviation (float Value)
Definition at line 60 of file GnssSensor.cpp.
References LongitudeDeviation.
Referenced by UActorBlueprintFunctionLibrary::SetGnss().
void AGnssSensor::Tick (float DeltaSeconds) override
Definition at line 33 of file GnssSensor.cpp.
References carla::geom::GeoLocation::altitude, AltitudeBias, AltitudeDeviation, CurrentGeoReference, ASensor::GetDataStream(), URandomEngine::GetNormalDistribution(), carla::geom::GeoLocation::latitude, LatitudeBias, LatitudeDeviation, carla::geom::GeoLocation::longitude, LongitudeBias, LongitudeDeviation, ASensor::RandomEngine, ASensor::Stream, and carla::geom::GeoLocation::Transform().
Member Data Documentation
float AGnssSensor::AltitudeBias private
Definition at line 67 of file GnssSensor.h.
Referenced by GetAltitudeBias(), SetAltitudeBias(), and Tick().
float AGnssSensor::AltitudeDeviation private
Definition at line 63 of file GnssSensor.h.
Referenced by GetAltitudeDeviation(), SetAltitudeDeviation(), and Tick().
carla::geom::GeoLocation AGnssSensor::CurrentGeoReference private
Definition at line 59 of file GnssSensor.h.
Referenced by BeginPlay(), and Tick().
float AGnssSensor::LatitudeBias private
Definition at line 65 of file GnssSensor.h.
Referenced by GetLatitudeBias(), SetLatitudeBias(), and Tick().
float AGnssSensor::LatitudeDeviation private
Definition at line 61 of file GnssSensor.h.
Referenced by GetLatitudeDeviation(), SetLatitudeDeviation(), and Tick().
float AGnssSensor::LongitudeBias private
Definition at line 66 of file GnssSensor.h.
Referenced by GetLongitudeBias(), SetLongitudeBias(), and Tick().
float AGnssSensor::LongitudeDeviation private
Definition at line 62 of file GnssSensor.h.
Referenced by GetLongitudeDeviation(), SetLongitudeDeviation(), and Tick().
The documentation for this class was generated from the following files:
GnssSensor.h
GnssSensor.cpp