CARLA: carla::sensor::data::RawEpisodeState Class Reference
carla::sensor::data::RawEpisodeState Class Reference
State of the episode at a given frame.
#include <RawEpisodeState.h>
Public Member Functions
double GetDeltaSeconds () const
Simulated seconds elapsed since previous frame.
uint64_t GetEpisodeId () const
Unique id of the episode at which this data was generated.
double GetGameTimeStamp () const
Simulation time-stamp, simulated seconds elapsed since the beginning of the current episode.
geom::Vector3DInt GetMapOrigin () const
double GetPlatformTimeStamp () const
Time-stamp of the frame at which this measurement was taken, in seconds as given by the OS.
Serializer::SimulationState GetSimulationState () const
Simulation state flags.
Public Member Functions inherited from carla::sensor::data::Array< ActorDynamicState >
reference at (size_type pos)
const_reference at (size_type pos) const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
value_type * data ()
const value_type * data () const
bool empty () const
iterator end ()
const_iterator end () const
reference operator[] (size_type pos)
const_reference operator[] (size_type pos) const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
Public Member Functions inherited from carla::sensor::SensorData
size_t GetFrame () const
Frame count when the data was generated.
const rpc::Transform & GetSensorTransform () const
Sensor's transform when the data was generated.
double GetTimestamp () const
Simulation-time when the data was generated.
virtual ~SensorData ()=default
Protected Types
using Serializer = s11n::EpisodeStateSerializer
Protected Member Functions
RawEpisodeState (RawData &&data)
Protected Member Functions inherited from carla::sensor::data::Array< ActorDynamicState >
Array (RawData &&data, FuncT get_offset)
Array (size_t offset, RawData &&data)
const RawData & GetRawData () const
Protected Member Functions inherited from carla::sensor::SensorData
const auto & GetEpisode () const
SensorData (size_t frame, double timestamp, const rpc::Transform &sensor_transform)
SensorData (const RawData &data)
Protected Attributes
friend Serializer
Private Types
using Super = Array< ActorDynamicState >
Private Member Functions
auto GetHeader () const
Additional Inherited Members
Public Types inherited from carla::sensor::data::Array< ActorDynamicState >
using const_iterator = typename std::add_const< value_type >::type *
using const_pointer = typename std::add_const< value_type >::type *
using const_reference = typename std::add_const< value_type >::type &
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using iterator = value_type *
using pointer = value_type *
using reference = value_type &
using reverse_iterator = std::reverse_iterator< iterator >
using size_type = size_t
using value_type = ActorDynamicState
Detailed Description
State of the episode at a given frame.
Definition at line 19 of file RawEpisodeState.h.
Member Typedef Documentation
Serializer
using carla::sensor::data::RawEpisodeState::Serializer = s11n::EpisodeStateSerializer protected
Definition at line 23 of file RawEpisodeState.h.
Super
using carla::sensor::data::RawEpisodeState::Super = Array<ActorDynamicState> private
Definition at line 20 of file RawEpisodeState.h.
Constructor & Destructor Documentation
RawEpisodeState()
carla::sensor::data::RawEpisodeState::RawEpisodeState (RawData && data) inline explicit protected
Definition at line 27 of file RawEpisodeState.h.
Member Function Documentation
GetDeltaSeconds()
double carla::sensor::data::RawEpisodeState::GetDeltaSeconds () const inline
Simulated seconds elapsed since previous frame.
Definition at line 56 of file RawEpisodeState.h.
References GetHeader().
GetEpisodeId()
uint64_t carla::sensor::data::RawEpisodeState::GetEpisodeId () const inline
Unique id of the episode at which this data was generated.
Definition at line 39 of file RawEpisodeState.h.
References GetHeader().
GetGameTimeStamp()
double carla::sensor::data::RawEpisodeState::GetGameTimeStamp () const inline
Simulation time-stamp, simulated seconds elapsed since the beginning of the current episode.
Definition at line 45 of file RawEpisodeState.h.
References carla::sensor::SensorData::GetTimestamp().
GetHeader()
auto carla::sensor::data::RawEpisodeState::GetHeader () const inline private
Definition at line 32 of file RawEpisodeState.h.
References carla::sensor::s11n::EpisodeStateSerializer::DeserializeHeader(), and carla::sensor::data::Array< ActorDynamicState >::GetRawData().
Referenced by GetDeltaSeconds(), GetEpisodeId(), GetMapOrigin(), GetPlatformTimeStamp(), and GetSimulationState().
GetMapOrigin()
geom::Vector3DInt carla::sensor::data::RawEpisodeState::GetMapOrigin () const inline
Definition at line 60 of file RawEpisodeState.h.
References GetHeader().
GetPlatformTimeStamp()
double carla::sensor::data::RawEpisodeState::GetPlatformTimeStamp () const inline
Time-stamp of the frame at which this measurement was taken, in seconds as given by the OS.
Definition at line 51 of file RawEpisodeState.h.
References GetHeader().
GetSimulationState()
Serializer::SimulationState carla::sensor::data::RawEpisodeState::GetSimulationState () const inline
Simulation state flags.
Definition at line 65 of file RawEpisodeState.h.
References GetHeader().
Member Data Documentation
Serializer
friend carla::sensor::data::RawEpisodeState::Serializer protected
Definition at line 25 of file RawEpisodeState.h.
The documentation for this class was generated from the following file:
RawEpisodeState.h