CARLA: SpringBasedVegetationComponent.cpp File Reference
SpringBasedVegetationComponent.cpp File Reference
#include "SpringBasedVegetationComponent.h"
#include "Carla/Walker/WalkerAnim.h"
#include "Math/Matrix.h"
#include "Components/CapsuleComponent.h"
#include "DrawDebugHelpers.h"
#include "Kismet/KismetMathLibrary.h"
#include <unordered_set>
#include <vector>
#include "carla/rpc/String.h"
#include <cmath>
#include <sstream>
Macros
#define ACC_LOG(...)
#define ACCUMULATIONLOGS 0
#define COLLISION_LOG(...)
#define COLLISIONLOGS 0
#define FICT_LOG(...)
#define FICTITIOUSFORCELOGS 0
#define OTHER_LOG(...)
#define OTHERLOGS 0
#define SOLVER_LOG(...)
#define SOLVERLOGS 0
#define SPRINGVEGETATIONLOGS 0
Functions
template<class T >
static FString EigenToFString (T &t)
static FRotator EigenVectorToRotator (const Eigen::Vector3d &Vector)
FRotator GetDeltaRotator (const FRotator &Rotator1, const FRotator &Rotator2)
template<class T >
static T GetSign (T n)
static Eigen::Matrix3d OuterProduct (const Eigen::Vector3d &V1, const Eigen::Vector3d &V2)
static Eigen::Matrix3d OuterProduct (const Eigen::Vector3d &V1)
static Eigen::Vector3d RotatorToEigenVector (const FRotator &Rotator)
static Eigen::Matrix3d ToEigenMatrix (const FMatrix &Matrix)
static Eigen::Matrix3d ToEigenMatrix (const FTransform &Transform)
static Eigen::Vector3d ToEigenVector (const FVector &V1)
static FVector ToUnrealVector (const Eigen::Vector3d &V1)
Macro Definition Documentation
ACC_LOG
#define ACC_LOG (...)
Definition at line 39 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
ACCUMULATIONLOGS
#define ACCUMULATIONLOGS 0
Definition at line 22 of file SpringBasedVegetationComponent.cpp.
COLLISION_LOG
#define COLLISION_LOG (...)
Definition at line 34 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
COLLISIONLOGS
#define COLLISIONLOGS 0
Definition at line 21 of file SpringBasedVegetationComponent.cpp.
FICT_LOG
#define FICT_LOG (...)
Definition at line 44 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
FICTITIOUSFORCELOGS
#define FICTITIOUSFORCELOGS 0
Definition at line 23 of file SpringBasedVegetationComponent.cpp.
OTHER_LOG
#define OTHER_LOG (...)
Definition at line 49 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces(), FSkeletonHierarchy::ComputeChildrenJointsAndBones(), and FSkeletonHierarchy::ComputeEndJoints().
OTHERLOGS
#define OTHERLOGS 0
Definition at line 24 of file SpringBasedVegetationComponent.cpp.
SOLVER_LOG
#define SOLVER_LOG (...)
Definition at line 29 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
SOLVERLOGS
#define SOLVERLOGS 0
Definition at line 20 of file SpringBasedVegetationComponent.cpp.
SPRINGVEGETATIONLOGS
#define SPRINGVEGETATIONLOGS 0
Definition at line 19 of file SpringBasedVegetationComponent.cpp.
Function Documentation
EigenToFString()
template<class T > static FString EigenToFString (T & t) static
Definition at line 84 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
EigenVectorToRotator()
static FRotator EigenVectorToRotator (const Eigen::Vector3d & Vector) static
Definition at line 127 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
GetDeltaRotator()
FRotator GetDeltaRotator (const FRotator & Rotator1, const FRotator & Rotator2)
Definition at line 53 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
GetSign()
template<class T > static T GetSign (T n) static
Definition at line 79 of file SpringBasedVegetationComponent.cpp.
OuterProduct() [1/2]
static Eigen::Matrix3d OuterProduct (const Eigen::Vector3d & V1, const Eigen::Vector3d & V2) static
Definition at line 90 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
OuterProduct() [2/2]
static Eigen::Matrix3d OuterProduct (const Eigen::Vector3d & V1) static
Definition at line 94 of file SpringBasedVegetationComponent.cpp.
RotatorToEigenVector()
static Eigen::Vector3d RotatorToEigenVector (const FRotator & Rotator) static
Definition at line 120 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
ToEigenMatrix() [1/2]
static Eigen::Matrix3d ToEigenMatrix (const FMatrix & Matrix) static
Definition at line 107 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces(), and ToEigenMatrix().
ToEigenMatrix() [2/2]
static Eigen::Matrix3d ToEigenMatrix (const FTransform & Transform) static
Definition at line 115 of file SpringBasedVegetationComponent.cpp.
References ToEigenMatrix().
ToEigenVector()
static Eigen::Vector3d ToEigenVector (const FVector & V1) static
Definition at line 99 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().
ToUnrealVector()
static FVector ToUnrealVector (const Eigen::Vector3d & V1) static
Definition at line 103 of file SpringBasedVegetationComponent.cpp.
Referenced by FSkeletonHierarchy::ClearExternalForces().