CARLA: pugi::xpath_node_set Class Reference
pugi::xpath_node_set Class Reference
#include <pugixml.hpp>
Public Types
typedef const xpath_node * const_iterator
typedef const xpath_node * iterator
enum type_t { type_unsorted, type_sorted, type_sorted_reverse }
Public Member Functions
const_iterator begin () const
bool empty () const
const_iterator end () const
xpath_node first () const
xpath_node_set & operator= (const xpath_node_set &ns)
const xpath_node & operator[] (size_t index) const
size_t size () const
void sort (bool reverse=false)
type_t type () const
xpath_node_set ()
xpath_node_set (const_iterator begin, const_iterator end, type_t type=type_unsorted)
xpath_node_set (const xpath_node_set &ns)
~xpath_node_set ()
Private Member Functions
void _assign (const_iterator begin, const_iterator end, type_t type)
void _move (xpath_node_set &rhs) PUGIXML_NOEXCEPT
Private Attributes
xpath_node * _begin
xpath_node * _end
xpath_node _storage
type_t _type
Detailed Description
Definition at line 1317 of file pugixml.hpp.
Member Typedef Documentation
const_iterator
typedef const xpath_node* pugi::xpath_node_set::const_iterator
Definition at line 1329 of file pugixml.hpp.
iterator
typedef const xpath_node* pugi::xpath_node_set::iterator
Definition at line 1332 of file pugixml.hpp.
Member Enumeration Documentation
type_t
enum pugi::xpath_node_set::type_t
Enumerator
type_unsorted
type_sorted
type_sorted_reverse
Definition at line 1321 of file pugixml.hpp.
Constructor & Destructor Documentation
xpath_node_set() [1/3]
PUGI__FN pugi::xpath_node_set::xpath_node_set ()
Definition at line 12074 of file pugixml.cpp.
Referenced by operator=().
xpath_node_set() [2/3]
PUGI__FN pugi::xpath_node_set::xpath_node_set (const_iterator begin, const_iterator end, type_t type = type_unsorted)
Definition at line 12078 of file pugixml.cpp.
References _assign().
~xpath_node_set()
PUGI__FN pugi::xpath_node_set::~xpath_node_set ()
Definition at line 12083 of file pugixml.cpp.
References _begin, and _storage.
xpath_node_set() [3/3]
PUGI__FN pugi::xpath_node_set::xpath_node_set (const xpath_node_set & ns)
Definition at line 12089 of file pugixml.cpp.
References _assign(), _begin, _end, and _type.
Member Function Documentation
_assign()
PUGI__FN void pugi::xpath_node_set::_assign (const_iterator begin, const_iterator end, type_t type) private
Definition at line 12016 of file pugixml.cpp.
References _begin, _end, _move(), _storage, _type, PUGI__FN, and PUGIXML_NOEXCEPT.
Referenced by operator=(), and xpath_node_set().
_move()
void pugi::xpath_node_set::_move (xpath_node_set & rhs) private
Referenced by _assign(), and operator=().
begin()
PUGI__FN xpath_node_set::const_iterator pugi::xpath_node_set::begin () const
Definition at line 12143 of file pugixml.cpp.
References _begin.
empty()
PUGI__FN bool pugi::xpath_node_set::empty () const
Definition at line 12132 of file pugixml.cpp.
References _begin, and _end.
end()
PUGI__FN xpath_node_set::const_iterator pugi::xpath_node_set::end () const
Definition at line 12148 of file pugixml.cpp.
References _end.
first()
PUGI__FN xpath_node pugi::xpath_node_set::first () const
Definition at line 12158 of file pugixml.cpp.
References _begin, _end, _type, and xpath_first().
operator=()
PUGI__FN xpath_node_set & pugi::xpath_node_set::operator= (const xpath_node_set & ns)
Definition at line 12094 of file pugixml.cpp.
References _assign(), _begin, _end, _move(), _storage, _type, PUGI__FN, PUGIXML_NOEXCEPT, type_unsorted, and xpath_node_set().
operator[]()
PUGI__FN const xpath_node & pugi::xpath_node_set::operator[] (size_t index) const
Definition at line 12137 of file pugixml.cpp.
References _begin, and size().
size()
PUGI__FN size_t pugi::xpath_node_set::size () const
Definition at line 12127 of file pugixml.cpp.
References _begin, and _end.
Referenced by operator[]().
sort()
PUGI__FN void pugi::xpath_node_set::sort (bool reverse = false)
Definition at line 12153 of file pugixml.cpp.
References _begin, _end, _type, and xpath_sort().
type()
PUGI__FN xpath_node_set::type_t pugi::xpath_node_set::type () const
Definition at line 12122 of file pugixml.cpp.
References _type.
Member Data Documentation
_begin
xpath_node* pugi::xpath_node_set::_begin private
Definition at line 1380 of file pugixml.hpp.
Referenced by _assign(), begin(), empty(), first(), operator=(), operator[](), size(), sort(), xpath_node_set(), and ~xpath_node_set().
_end
xpath_node* pugi::xpath_node_set::_end private
Definition at line 1381 of file pugixml.hpp.
Referenced by _assign(), empty(), end(), first(), operator=(), size(), sort(), and xpath_node_set().
_storage
xpath_node pugi::xpath_node_set::_storage private
Definition at line 1378 of file pugixml.hpp.
Referenced by _assign(), operator=(), and ~xpath_node_set().
_type
type_t pugi::xpath_node_set::_type private
Definition at line 1376 of file pugixml.hpp.
Referenced by _assign(), first(), operator=(), sort(), type(), and xpath_node_set().
The documentation for this class was generated from the following files:
pugixml.hpp
pugixml.cpp