CARLA: UPrepareAssetsForCookingCommandlet Class Reference
UPrepareAssetsForCookingCommandlet Class Reference
#include <PrepareAssetsForCookingCommandlet.h>
Public Member Functions
UPrepareAssetsForCookingCommandlet ()
Default constructor.
Private Member Functions
FString GetFirstPackagePath (const FString &PackageName) const
Gets the first .Package.json file found in Unreal Content Directory with PackageName.
bool SavePackage (const FString &PackagePath, UPackage *Package) const
Saves Package in .umap format in path PackagePath inside Unreal Content folder.
Private Attributes
TArray< FAssetData > AssetDatas
Loaded assets from any object library.
UObjectLibrary * AssetsObjectLibrary
Used for loading assets in object library.
TArray< FAssetData > MapContents
Loaded map content from any object library.
UObjectLibrary * MapObjectLibrary
Used for loading maps in object library.
UMaterial * MarkingNodeMaterial
Workaround material for MarkingNodes mesh.
UMaterial * MarkingNodeMaterialAux
Workaround material for the second material for the MarkingNodes.
UMaterial * RoadNodeMaterial
Workaround material for the RoadNode mesh.
UMaterial * SidewalkNodeMaterial
Workaround material for the SidewalkNodes.
UMaterial * TerrainNodeMaterial
Workaround material for the TerrainNodes.
UWorld * World
Base map world loaded from Carla Content.
Detailed Description
Definition at line 55 of file PrepareAssetsForCookingCommandlet.h.
Constructor & Destructor Documentation
UPrepareAssetsForCookingCommandlet::UPrepareAssetsForCookingCommandlet ()
Default constructor.
Definition at line 15 of file PrepareAssetsForCookingCommandlet.cpp.
References AOpenDriveActor::AddSpawners(), AssetDatas, AssetsObjectLibrary, FPackageParams::bOnlyPrepareMaps, AOpenDriveActor::BuildRoutes(), FMapData::bUseCarlaMapMaterials, carla::client::detail::Get(), GetFirstPackagePath(), MapContents, MapObjectLibrary, FAssetsPaths::MapsPaths, MarkingNodeMaterial, MarkingNodeMaterialAux, FPackageParams::Name, FMapData::Name, FMapData::Path, FAssetsPaths::PropsPaths, AOpenDriveActor::RemoveRoutes(), AOpenDriveActor::RemoveSpawners(), RoadNodeMaterial, SavePackage(), SidewalkNodeMaterial, TerrainNodeMaterial, and World.
Member Function Documentation
FString UPrepareAssetsForCookingCommandlet::GetFirstPackagePath (const FString & PackageName) const private
Gets the first .Package.json file found in Unreal Content Directory with PackageName.
Referenced by UPrepareAssetsForCookingCommandlet().
bool UPrepareAssetsForCookingCommandlet::SavePackage (const FString & PackagePath, UPackage * Package) const private
Saves Package in .umap format in path PackagePath inside Unreal Content folder.
Referenced by UPrepareAssetsForCookingCommandlet().
Member Data Documentation
TArray<FAssetData> UPrepareAssetsForCookingCommandlet::AssetDatas private
Loaded assets from any object library.
Definition at line 127 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UObjectLibrary* UPrepareAssetsForCookingCommandlet::AssetsObjectLibrary private
Used for loading assets in object library.
Loaded Data is stored in AssetDatas.
Definition at line 141 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
TArray<FAssetData> UPrepareAssetsForCookingCommandlet::MapContents private
Loaded map content from any object library.
Definition at line 131 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UObjectLibrary* UPrepareAssetsForCookingCommandlet::MapObjectLibrary private
Used for loading maps in object library.
Loaded Data is stored in AssetDatas.
Definition at line 136 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UMaterial* UPrepareAssetsForCookingCommandlet::MarkingNodeMaterial private
Workaround material for MarkingNodes mesh.
Definition at line 149 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UMaterial* UPrepareAssetsForCookingCommandlet::MarkingNodeMaterialAux private
Workaround material for the second material for the MarkingNodes.
Definition at line 157 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UMaterial* UPrepareAssetsForCookingCommandlet::RoadNodeMaterial private
Workaround material for the RoadNode mesh.
Definition at line 153 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UMaterial* UPrepareAssetsForCookingCommandlet::SidewalkNodeMaterial private
Workaround material for the SidewalkNodes.
Definition at line 165 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UMaterial* UPrepareAssetsForCookingCommandlet::TerrainNodeMaterial private
Workaround material for the TerrainNodes.
Definition at line 161 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
UWorld* UPrepareAssetsForCookingCommandlet::World private
Base map world loaded from Carla Content.
Definition at line 145 of file PrepareAssetsForCookingCommandlet.h.
Referenced by UPrepareAssetsForCookingCommandlet().
The documentation for this class was generated from the following files:
PrepareAssetsForCookingCommandlet.h
PrepareAssetsForCookingCommandlet.cpp