CARLA: carla::client::Landmark Class Reference
carla::client::Landmark Class Reference
Class containing a reference to RoadInfoSignal.
#include <Landmark.h>
Public Member Functions
std::string GetCountry () const
double GetDistance () const
double GetHeight () const
double GethOffset () const
std::string GetId () const
std::string GetName () const
road::SignalOrientation GetOrientation () const
double GetPitch () const
road::RoadId GetRoadId () const
double GetRoll () const
double GetS () const
std::string GetSubType () const
double GetT () const
std::string GetText () const
const geom::Transform & GetTransform () const
std::string GetType () const
std::string GetUnit () const
const auto & GetValidities () const
double GetValue () const
SharedPtr< Waypoint > GetWaypoint () const
double GetWidth () const
double GetZOffset () const
bool IsDynamic () const
Private Member Functions
Landmark (SharedPtr< Waypoint > waypoint, const road::element::RoadInfoSignal *signal, double distance_from_search=0)
Private Attributes
double _distance_from_search
const road::element::RoadInfoSignal * _signal
SharedPtr< Waypoint > _waypoint
waypoint where the signal is affecting
friend Waypoint
Detailed Description
Class containing a reference to RoadInfoSignal.
Definition at line 22 of file Landmark.h.
Constructor & Destructor Documentation
carla::client::Landmark::Landmark (SharedPtr< Waypoint > waypoint, const road::element::RoadInfoSignal * signal, double distance_from_search = 0) inline private
Definition at line 121 of file Landmark.h.
Member Function Documentation
std::string carla::client::Landmark::GetCountry () const inline
Definition at line 69 of file Landmark.h.
References _signal, carla::road::Signal::GetCountry(), and carla::road::element::RoadInfoSignal::GetSignal().
double carla::client::Landmark::GetDistance () const inline
Definition at line 37 of file Landmark.h.
References _distance_from_search.
double carla::client::Landmark::GetHeight () const inline
Definition at line 89 of file Landmark.h.
References _signal, carla::road::Signal::GetHeight(), and carla::road::element::RoadInfoSignal::GetSignal().
double carla::client::Landmark::GethOffset () const inline
Definition at line 101 of file Landmark.h.
References _signal, carla::road::Signal::GetHOffset(), and carla::road::element::RoadInfoSignal::GetSignal().
std::string carla::client::Landmark::GetId () const inline
Definition at line 49 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetSignalId().
Referenced by carla::client::World::GetTrafficLight(), and carla::client::World::GetTrafficSign().
std::string carla::client::Landmark::GetName () const inline
Definition at line 53 of file Landmark.h.
References _signal, carla::road::Signal::GetName(), and carla::road::element::RoadInfoSignal::GetSignal().
road::SignalOrientation carla::client::Landmark::GetOrientation () const inline
Definition at line 61 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetOrientation().
double carla::client::Landmark::GetPitch () const inline
Definition at line 105 of file Landmark.h.
References _signal, carla::road::Signal::GetPitch(), and carla::road::element::RoadInfoSignal::GetSignal().
road::RoadId carla::client::Landmark::GetRoadId () const inline
Definition at line 33 of file Landmark.h.
References _signal, carla::road::Signal::GetRoadId(), and carla::road::element::RoadInfoSignal::GetSignal().
double carla::client::Landmark::GetRoll () const inline
Definition at line 109 of file Landmark.h.
References _signal, carla::road::Signal::GetRoll(), and carla::road::element::RoadInfoSignal::GetSignal().
double carla::client::Landmark::GetS () const inline
Definition at line 41 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetS().
std::string carla::client::Landmark::GetSubType () const inline
Definition at line 77 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetSubtype().
double carla::client::Landmark::GetT () const inline
Definition at line 45 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetT().
std::string carla::client::Landmark::GetText () const inline
Definition at line 97 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetText().
const geom::Transform& carla::client::Landmark::GetTransform () const inline
Definition at line 29 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetTransform().
std::string carla::client::Landmark::GetType () const inline
Definition at line 73 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetType().
std::string carla::client::Landmark::GetUnit () const inline
Definition at line 85 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetUnit().
const auto& carla::client::Landmark::GetValidities () const inline
Definition at line 113 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetValidities().
double carla::client::Landmark::GetValue () const inline
Definition at line 81 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetValue().
SharedPtr<Waypoint> carla::client::Landmark::GetWaypoint () const inline
Definition at line 25 of file Landmark.h.
References _waypoint.
double carla::client::Landmark::GetWidth () const inline
Definition at line 93 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetWidth().
double carla::client::Landmark::GetZOffset () const inline
Definition at line 65 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetZOffset().
bool carla::client::Landmark::IsDynamic () const inline
Definition at line 57 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::IsDynamic().
Member Data Documentation
double carla::client::Landmark::_distance_from_search private
Definition at line 134 of file Landmark.h.
Referenced by GetDistance().
const road::element::RoadInfoSignal* carla::client::Landmark::_signal private
Definition at line 132 of file Landmark.h.
Referenced by GetCountry(), GetHeight(), GethOffset(), GetId(), GetName(), GetOrientation(), GetPitch(), GetRoadId(), GetRoll(), GetS(), GetSubType(), GetT(), GetText(), GetTransform(), GetType(), GetUnit(), GetValidities(), GetValue(), GetWidth(), GetZOffset(), and IsDynamic().
SharedPtr<Waypoint> carla::client::Landmark::_waypoint private
waypoint where the signal is affecting
Definition at line 130 of file Landmark.h.
Referenced by GetWaypoint().
friend carla::client::Landmark::Waypoint private
Definition at line 119 of file Landmark.h.
The documentation for this class was generated from the following file:
Landmark.h