CARLA: carla::ros2::CarlaSemanticLidarPublisher Class Reference
carla::ros2::CarlaSemanticLidarPublisher Class Reference
#include <CarlaSemanticLidarPublisher.h>
Public Member Functions
CarlaSemanticLidarPublisher (CarlaSemanticLidarPublisher &&)
CarlaSemanticLidarPublisher (const CarlaSemanticLidarPublisher &)
CarlaSemanticLidarPublisher (const char *ros_name="", const char *parent="")
bool Init ()
CarlaSemanticLidarPublisher & operator= (CarlaSemanticLidarPublisher &&)
CarlaSemanticLidarPublisher & operator= (const CarlaSemanticLidarPublisher &)
bool Publish ()
void SetData (int32_t seconds, uint32_t nanoseconds, size_t elements, size_t height, size_t width, float *data)
const char * type () const override
~CarlaSemanticLidarPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Member Functions
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > &&data)
Private Attributes
std::shared_ptr< CarlaSemanticLidarPublisherImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 18 of file CarlaSemanticLidarPublisher.h.
Constructor & Destructor Documentation
CarlaSemanticLidarPublisher() [1/3]
carla::ros2::CarlaSemanticLidarPublisher::CarlaSemanticLidarPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 217 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaSemanticLidarPublisher()
carla::ros2::CarlaSemanticLidarPublisher::~CarlaSemanticLidarPublisher ()
Definition at line 223 of file CarlaSemanticLidarPublisher.cpp.
References _impl.
CarlaSemanticLidarPublisher() [2/3]
carla::ros2::CarlaSemanticLidarPublisher::CarlaSemanticLidarPublisher (const CarlaSemanticLidarPublisher & other)
Definition at line 240 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaSemanticLidarPublisher() [3/3]
carla::ros2::CarlaSemanticLidarPublisher::CarlaSemanticLidarPublisher (CarlaSemanticLidarPublisher && other)
Definition at line 256 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
Init()
bool carla::ros2::CarlaSemanticLidarPublisher::Init ()
Definition at line 43 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [1/2]
CarlaSemanticLidarPublisher & carla::ros2::CarlaSemanticLidarPublisher::operator= (CarlaSemanticLidarPublisher && other)
Definition at line 263 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaSemanticLidarPublisher & carla::ros2::CarlaSemanticLidarPublisher::operator= (const CarlaSemanticLidarPublisher & other)
Definition at line 247 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaSemanticLidarPublisher::Publish ()
Definition at line 89 of file CarlaSemanticLidarPublisher.cpp.
References _impl.
SetData() [1/2]
void carla::ros2::CarlaSemanticLidarPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t elements, size_t height, size_t width, float * data)
Definition at line 151 of file CarlaSemanticLidarPublisher.cpp.
SetData() [2/2]
void carla::ros2::CarlaSemanticLidarPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > && data) private
Definition at line 165 of file CarlaSemanticLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, sensor_msgs::msg::PointField::count(), sensor_msgs::msg::PointField::datatype(), std_msgs::msg::Header::frame_id(), sensor_msgs::msg::PointField::name(), builtin_interfaces::msg::Time::nanosec(), sensor_msgs::msg::PointField::offset(), sensor_msgs::msg::PointField__FLOAT32, sensor_msgs::msg::PointField__UINT32, builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
type()
const char* carla::ros2::CarlaSemanticLidarPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 30 of file CarlaSemanticLidarPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaSemanticLidarPublisherImpl> carla::ros2::CarlaSemanticLidarPublisher::_impl private
Definition at line 36 of file CarlaSemanticLidarPublisher.h.
Referenced by CarlaSemanticLidarPublisher(), Init(), operator=(), Publish(), SetData(), and ~CarlaSemanticLidarPublisher().
The documentation for this class was generated from the following files:
CarlaSemanticLidarPublisher.h
CarlaSemanticLidarPublisher.cpp