CARLA: carla::sensor::data::LidarRawData Class Reference
carla::sensor::data::LidarRawData Class Reference
#include <LidarRawData.h>
Public Member Functions
uint32_t GetChannelCount () const
float GetHorizontalAngle () const
LidarRawData (uint32_t ChannelCount=0u)
LidarRawData & operator= (LidarRawData &&)=default
virtual void ResetSerPoints (std::vector< uint32_t > points_per_channel)
void SetHorizontalAngle (float angle)
virtual void WritePointSync (LidarRawDetection &detection)
virtual ~LidarRawData ()
Protected Types
enum Index : size_t { HorizontalAngle, ChannelCount, SIZE }
Protected Attributes
std::vector< uint32_t > _header
uint32_t _max_channel_points
Private Attributes
std::vector< LidarRawDetection > _ser_points
Friends
class s11n::LidarRawHeaderView
class s11n::LidarRawSerializer
Detailed Description
Definition at line 81 of file LidarRawData.h.
Member Enumeration Documentation
enum carla::sensor::data::LidarRawData::Index : size_t protected
Enumerator
HorizontalAngle
ChannelCount
SIZE
Definition at line 85 of file LidarRawData.h.
Constructor & Destructor Documentation
carla::sensor::data::LidarRawData::LidarRawData (uint32_t ChannelCount = 0u) inline explicit
Definition at line 92 of file LidarRawData.h.
virtual carla::sensor::data::LidarRawData::~LidarRawData () inline virtual
Definition at line 99 of file LidarRawData.h.
Member Function Documentation
uint32_t carla::sensor::data::LidarRawData::GetChannelCount () const inline
Definition at line 109 of file LidarRawData.h.
float carla::sensor::data::LidarRawData::GetHorizontalAngle () const inline
Definition at line 101 of file LidarRawData.h.
Referenced by ARayCastRawLidar::SimulateLidar().
LidarRawData& carla::sensor::data::LidarRawData::operator= (LidarRawData &&) default
virtual void carla::sensor::data::LidarRawData::ResetSerPoints (std::vector< uint32_t > points_per_channel) inline virtual
Reimplemented in carla::sensor::data::LidarData.
Definition at line 113 of file LidarRawData.h.
References DEBUG_ASSERT, and PropAttributes::SIZE.
Referenced by ARayCastRawLidar::ComputeAndSaveDetections().
void carla::sensor::data::LidarRawData::SetHorizontalAngle (float angle) inline
Definition at line 105 of file LidarRawData.h.
Referenced by ARayCastRawLidar::SimulateLidar().
virtual void carla::sensor::data::LidarRawData::WritePointSync (LidarRawDetection & detection) inline virtual
Reimplemented in carla::sensor::data::LidarData.
Definition at line 127 of file LidarRawData.h.
Referenced by ARayCastRawLidar::ComputeAndSaveDetections().
Friends And Related Function Documentation
friend class s11n::LidarRawHeaderView friend
Definition at line 138 of file LidarRawData.h.
friend class s11n::LidarRawSerializer friend
Definition at line 139 of file LidarRawData.h.
Member Data Documentation
std::vector<uint32_t> carla::sensor::data::LidarRawData::_header protected
Definition at line 132 of file LidarRawData.h.
Referenced by carla::sensor::s11n::LidarSerializer::Serialize(), and carla::sensor::s11n::LidarRawSerializer::Serialize().
uint32_t carla::sensor::data::LidarRawData::_max_channel_points protected
Definition at line 133 of file LidarRawData.h.
std::vector<LidarRawDetection> carla::sensor::data::LidarRawData::_ser_points private
Definition at line 136 of file LidarRawData.h.
Referenced by carla::sensor::s11n::LidarRawSerializer::Serialize().
The documentation for this class was generated from the following file:
LidarRawData.h