CARLA: TrafficLightBase.cpp File Reference
TrafficLightBase.cpp File Reference
#include "Carla.h"
#include "TrafficLightBase.h"
#include "Carla/Game/CarlaStatics.h"
#include "Vehicle/CarlaWheeledVehicle.h"
#include "Vehicle/WheeledVehicleAIController.h"
Functions
static bool IsValid (const ACarlaWheeledVehicle *Vehicle)
static ETrafficSignState ToTrafficSignState (ETrafficLightState State)
Function Documentation
IsValid()
static bool IsValid (const ACarlaWheeledVehicle * Vehicle) static
Definition at line 17 of file TrafficLightBase.cpp.
Referenced by ACarlaWheeledVehicle::AddReferenceToManager(), AVegetationManager::AddVehicle(), UCarlaSettingsDelegate::ApplyQualityLevelPreRestart(), ASceneCaptureSensor::BeginPlay(), UCarlaSettingsDelegate::CheckCarlaSettings(), AVegetationManager::CheckForNewTiles(), ALargeMapManager::CheckIfRebaseIsNeeded(), AWeather::CheckWeatherPostProcessEffects(), FSkeletonHierarchy::ClearExternalForces(), AVegetationManager::CreateOrUpdateTileCache(), AVegetationManager::CreatePoolForBPClass(), UTaggedComponent::CreateSceneProxy(), AVegetationManager::FreeTileCache(), URoadMap::GetDataAt(), ALargeMapManager::GetHeroVehicle(), AVegetationManager::GetTilesInUse(), carla::geom::Mesh::Mesh(), ATrafficLightBase::NotifyWheeledVehicle(), UCarlaSettingsDelegate::OnActorSpawned(), ALargeMapManager::OnActorSpawned(), UTaggedComponent::OnRegister(), ACityMapMeshHolder::PostInitializeComponents(), ALargeMapManager::PrintMapInfo(), ACarlaWheeledVehicle::RemoveReferenceToManager(), AVegetationManager::RemoveVehicle(), UCarlaSettingsDelegate::SetActorComponentsDrawDistance(), UCarlaSettingsDelegate::SetAllActorsDrawDistance(), UCarlaSettingsDelegate::SetAllLights(), UCarlaSettingsDelegate::SetAllRoads(), UTaggedComponent::SetColor(), AVegetationManager::SetInstancedStaticMeshComponentCache(), AVegetationManager::SetMaterialCache(), UCarlaSettingsDelegate::SetPostProcessEffectsEnabled(), AVegetationManager::SpawnSkeletalFoliages(), ATagger::TagActor(), AVegetationManager::Tick(), ATrafficLightBase::UnNotifyWheeledVehicle(), AVegetationManager::UpdateFoliageBlueprintCache(), ALargeMapManager::UpdateTilesState(), and carla::client::ServerSideSensor::~ServerSideSensor().
ToTrafficSignState()
static ETrafficSignState ToTrafficSignState (ETrafficLightState State) static
Definition at line 22 of file TrafficLightBase.cpp.
References TrafficLightGreen, TrafficLightRed, and TrafficLightYellow.