CARLA: carla::geom::Math Class Reference
carla::geom::Math Class Reference
#include <Math.h>
Static Public Member Functions
template<typename T >
static T Clamp (T a, T min=T(0), T max=T(1))
static auto Distance (const Vector3D &a, const Vector3D &b)
static auto Distance2D (const Vector3D &a, const Vector3D &b)
static std::pair< float, float > DistanceArcToPoint (Vector3D p, Vector3D start_pos, float length, float heading, float curvature)
Returns a pair containing:
static std::pair< float, float > DistanceSegmentToPoint (const Vector3D &p, const Vector3D &v, const Vector3D &w)
Returns a pair containing:
static auto DistanceSquared (const Vector3D &a, const Vector3D &b)
static auto DistanceSquared2D (const Vector3D &a, const Vector3D &b)
static auto Dot (const Vector3D &a, const Vector3D &b)
static auto Dot2D (const Vector3D &a, const Vector3D &b)
static std::vector< int > GenerateRange (int a, int b)
static Vector3D GetForwardVector (const Rotation &rotation)
Compute the unit vector pointing towards the X-axis of rotation.
static Vector3D GetRightVector (const Rotation &rotation)
Compute the unit vector pointing towards the Y-axis of rotation.
static Vector3D GetUpVector (const Rotation &rotation)
Compute the unit vector pointing towards the Y-axis of rotation.
static double GetVectorAngle (const Vector3D &a, const Vector3D &b)
Returns the angle between 2 vectors in radians.
template<typename T >
static constexpr T Pi ()
template<typename T >
static constexpr T Pi2 ()
static Vector3D RotatePointOnOrigin2D (Vector3D p, float angle)
template<typename T >
static T Square (const T &a)
template<typename T >
static constexpr T ToDegrees (T rad)
template<typename T >
static constexpr T ToRadians (T deg)
Detailed Description
Definition at line 21 of file Math.h.
Member Function Documentation
template<typename T > static T carla::geom::Math::Clamp (T a, T min = T(0), T max = T(1)) inline static
Definition at line 49 of file Math.h.
Referenced by carla::road::MapBuilder::AddSignalReference(), carla::traffic_manager::LocalizationStage::AssignLaneChange(), DistanceSegmentToPoint(), carla::road::Road::GetDirectedPointIn(), carla::road::element::GeometryLine::PosFromDist(), carla::road::element::GeometryArc::PosFromDist(), carla::road::element::GeometrySpiral::PosFromDist(), carla::traffic_manager::Parameters::SetPercentageIgnoreVehicles(), carla::traffic_manager::Parameters::SetPercentageIgnoreWalkers(), carla::traffic_manager::Parameters::SetPercentageRunningLight(), and carla::traffic_manager::Parameters::SetPercentageRunningSign().
static auto carla::geom::Math::Distance (const Vector3D & a, const Vector3D & b) inline static
Definition at line 74 of file Math.h.
References DistanceSquared().
Referenced by carla::geom::ComputeVertexWeight(), carla::geom::Location::Distance(), carla::road::Road::GetNearestLane(), and TEST().
static auto carla::geom::Math::Distance2D (const Vector3D & a, const Vector3D & b) inline static
Definition at line 78 of file Math.h.
References DistanceArcToPoint(), DistanceSegmentToPoint(), DistanceSquared2D(), GenerateRange(), GetForwardVector(), GetRightVector(), GetUpVector(), GetVectorAngle(), and RotatePointOnOrigin2D().
Referenced by DistanceArcToPoint(), DistanceSegmentToPoint(), and carla::road::Map::GetWaypoint().
std::pair< float, float > carla::geom::Math::DistanceArcToPoint (Vector3D p, Vector3D start_pos, float length, float heading, float curvature) static
Returns a pair containing:
first: distance across the arc from start_pos to p' where p' = p projected on Arc
second: Euclidean distance from p to p'
Todo:
: Because Unreal's coordinates, hacky way to correct the -y, this must be changed in the future
Definition at line 33 of file Math.cpp.
References DEBUG_ASSERT, Distance2D(), RotatePointOnOrigin2D(), carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by Distance2D(), carla::road::element::GeometryArc::DistanceTo(), and TEST().
std::pair< float, float > carla::geom::Math::DistanceSegmentToPoint (const Vector3D & p, const Vector3D & v, const Vector3D & w) static
Returns a pair containing:
first: distance from v to p' where p' = p projected on segment (w - v)
second: Euclidean distance from p to p'
Parameters
p point to calculate distance
v first point of the segment
w second point of the segment
Definition at line 18 of file Math.cpp.
References Clamp(), Distance2D(), DistanceSquared2D(), and Dot2D().
Referenced by Distance2D(), carla::road::element::GeometryLine::DistanceTo(), carla::road::Map::GetClosestWaypointOnRoad(), and TEST().
static auto carla::geom::Math::DistanceSquared (const Vector3D & a, const Vector3D & b) inline static
Definition at line 66 of file Math.h.
References Square(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::traffic_manager::LocalizationStage::AssignLaneChange(), Distance(), carla::traffic_manager::SimpleWaypoint::DistanceSquared(), carla::traffic_manager::CollisionStage::NegotiateCollision(), carla::traffic_manager::MotionPlanStage::SafeAfterJunction(), carla::traffic_manager::InMemoryMap::SetUp(), carla::traffic_manager::LocalizationStage::Update(), carla::traffic_manager::CollisionStage::Update(), and carla::traffic_manager::ALSM::UpdateRegisteredActorsData().
static auto carla::geom::Math::DistanceSquared2D (const Vector3D & a, const Vector3D & b) inline static
Definition at line 70 of file Math.h.
References Square(), carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by Distance2D(), and DistanceSegmentToPoint().
static auto carla::geom::Math::Dot (const Vector3D & a, const Vector3D & b) inline static
Definition at line 58 of file Math.h.
References carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::traffic_manager::LocalizationStage::AssignLaneChange(), carla::traffic_manager::MotionPlanStage::CollisionHandling(), carla::traffic_manager::DeviationDotProduct(), carla::traffic_manager::CollisionStage::GetBoundingBoxExtention(), carla::traffic_manager::CollisionStage::GetGeodesicBoundary(), GetVectorAngle(), and carla::traffic_manager::CollisionStage::NegotiateCollision().
static auto carla::geom::Math::Dot2D (const Vector3D & a, const Vector3D & b) inline static
Definition at line 62 of file Math.h.
References carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by DistanceSegmentToPoint().
std::vector< int > carla::geom::Math::GenerateRange (int a, int b) static
Definition at line 151 of file Math.cpp.
Referenced by Distance2D().
Vector3D carla::geom::Math::GetForwardVector (const Rotation & rotation) static
Compute the unit vector pointing towards the X-axis of rotation.
Definition at line 117 of file Math.cpp.
References carla::geom::Rotation::pitch, ToRadians(), and carla::geom::Rotation::yaw.
Referenced by Distance2D(), and carla::geom::Rotation::GetForwardVector().
Vector3D carla::geom::Math::GetRightVector (const Rotation & rotation) static
Compute the unit vector pointing towards the Y-axis of rotation.
Definition at line 125 of file Math.cpp.
References carla::geom::Rotation::pitch, carla::geom::Rotation::roll, ToRadians(), and carla::geom::Rotation::yaw.
Referenced by Distance2D(), and carla::geom::Rotation::GetRightVector().
Vector3D carla::geom::Math::GetUpVector (const Rotation & rotation) static
Compute the unit vector pointing towards the Y-axis of rotation.
Definition at line 138 of file Math.cpp.
References carla::geom::Rotation::pitch, carla::geom::Rotation::roll, ToRadians(), and carla::geom::Rotation::yaw.
Referenced by Distance2D(), and carla::geom::Rotation::GetUpVector().
double carla::geom::Math::GetVectorAngle (const Vector3D & a, const Vector3D & b) static
Returns the angle between 2 vectors in radians.
Definition at line 14 of file Math.cpp.
References Dot(), and carla::geom::Vector3D::Length().
Referenced by carla::road::Map::CreateRtree(), and Distance2D().
template<typename T > static constexpr T carla::geom::Math::Pi () inline static
Definition at line 25 of file Math.h.
template<typename T > static constexpr T carla::geom::Math::Pi2 () inline static
Definition at line 31 of file Math.h.
Vector3D carla::geom::Math::RotatePointOnOrigin2D (Vector3D p, float angle) static
Definition at line 111 of file Math.cpp.
References carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by carla::nav::Navigation::AddOrUpdateVehicle(), Distance2D(), and DistanceArcToPoint().
template<typename T > static T carla::geom::Math::Square (const T & a) inline static
Definition at line 54 of file Math.h.
Referenced by DistanceSquared(), and DistanceSquared2D().
template<typename T > static constexpr T carla::geom::Math::ToDegrees (T rad) inline static
Definition at line 37 of file Math.h.
Referenced by carla::road::MapBuilder::ComputeSignalTransform(), carla::road::Lane::ComputeTransform(), and ARayCastLidar::ReadPoints().
template<typename T > static constexpr T carla::geom::Math::ToRadians (T deg) inline static
Definition at line 43 of file Math.h.
Referenced by carla::nav::Navigation::AddOrUpdateVehicle(), GetForwardVector(), GetRightVector(), GetUpVector(), carla::geom::Rotation::InverseRotateVector(), carla::geom::LatLonToMercator(), carla::geom::LatToScale(), ARayCastLidar::ReadPoints(), and carla::geom::Rotation::RotateVector().
The documentation for this class was generated from the following files:
Math.h
Math.cpp