CARLA: carla::road::MapData Class Reference
carla::road::MapData Class Reference
#include <MapData.h>
Public Member Functions
bool ContainsRoad (RoadId id) const
const std::unordered_map< ContId, std::unique_ptr< Controller > > & GetControllers () const
const geom::GeoLocation & GetGeoReference () const
Junction * GetJunction (JuncId id)
const Junction * GetJunction (JuncId id) const
std::unordered_map< JuncId, Junction > & GetJunctions ()
const std::unordered_map< JuncId, Junction > & GetJunctions () const
template<typename T >
auto GetLaneInfo (const RoadId road_id, const SectionId section_id, const LaneId lane_id, const double s)
Road & GetRoad (const RoadId id)
const Road & GetRoad (const RoadId id) const
size_t GetRoadCount () const
template<typename T >
auto GetRoadInfo (const RoadId id, const double s)
std::unordered_map< RoadId, Road > & GetRoads ()
const std::unordered_map< RoadId, Road > & GetRoads () const
const std::unordered_map< SignId, std::unique_ptr< Signal > > & GetSignals () const
Private Member Functions
MapData ()=default
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Private Attributes
std::unordered_map< ContId, std::unique_ptr< Controller > > _controllers
geom::GeoLocation _geo_reference
std::unordered_map< JuncId, Junction > _junctions
std::unordered_map< RoadId, Road > _roads
std::unordered_map< SignId, std::unique_ptr< Signal > > _signals
Friends
class MapBuilder
Detailed Description
Definition at line 29 of file MapData.h.
Constructor & Destructor Documentation
MapData()
carla::road::MapData::MapData () private default
Member Function Documentation
ContainsRoad()
bool carla::road::MapData::ContainsRoad (RoadId id) const inline
Definition at line 48 of file MapData.h.
References _roads, GetJunction(), and GetRoad().
GetControllers()
const std::unordered_map<ContId, std::unique_ptr<Controller> >& carla::road::MapData::GetControllers () const inline
Definition at line 82 of file MapData.h.
References _controllers.
Referenced by carla::road::Map::GetControllers().
GetGeoReference()
const geom::GeoLocation& carla::road::MapData::GetGeoReference () const inline
Definition at line 32 of file MapData.h.
References _geo_reference, and GetRoads().
Referenced by carla::road::Map::GetGeoReference().
GetJunction() [1/2]
Junction * carla::road::MapData::GetJunction (JuncId id)
Definition at line 29 of file MapData.cpp.
References _junctions.
Referenced by ContainsRoad().
GetJunction() [2/2]
const Junction * carla::road::MapData::GetJunction (JuncId id) const
Definition at line 37 of file MapData.cpp.
References _junctions.
GetJunctions() [1/2]
std::unordered_map< JuncId, Junction > & carla::road::MapData::GetJunctions ()
Definition at line 17 of file MapData.cpp.
References _junctions.
Referenced by carla::road::MapBuilder::ComputeJunctionRoadConflicts(), carla::road::MapBuilder::CreateJunctionBoundingBoxes(), and GetRoads().
GetJunctions() [2/2]
const std::unordered_map<JuncId, Junction>& carla::road::MapData::GetJunctions () const inline
Definition at line 44 of file MapData.h.
References _junctions.
GetLaneInfo()
template<typename T > auto carla::road::MapData::GetLaneInfo (const RoadId road_id, const SectionId section_id, const LaneId lane_id, const double s) inline
Definition at line 66 of file MapData.h.
References carla::road::Road::GetLaneById(), and GetRoad().
GetRoad() [1/2]
Road & carla::road::MapData::GetRoad (const RoadId id)
Definition at line 21 of file MapData.cpp.
References _roads.
Referenced by carla::road::MapBuilder::ComputeSignalTransform(), ContainsRoad(), GetLaneInfo(), GetRoad(), GetRoadInfo(), and carla::road::IsLanePresent().
GetRoad() [2/2]
const Road & carla::road::MapData::GetRoad (const RoadId id) const
Definition at line 25 of file MapData.cpp.
References GetRoad().
GetRoadCount()
size_t carla::road::MapData::GetRoadCount () const inline
Definition at line 74 of file MapData.h.
References _roads.
GetRoadInfo()
template<typename T > auto carla::road::MapData::GetRoadInfo (const RoadId id, const double s) inline
Definition at line 61 of file MapData.h.
References GetRoad().
GetRoads() [1/2]
std::unordered_map< RoadId, Road > & carla::road::MapData::GetRoads ()
Definition at line 13 of file MapData.cpp.
References _roads.
Referenced by GetGeoReference().
GetRoads() [2/2]
const std::unordered_map<RoadId, Road>& carla::road::MapData::GetRoads () const inline
Definition at line 38 of file MapData.h.
References _roads, and GetJunctions().
GetSignals()
const std::unordered_map<SignId, std::unique_ptr<Signal> >& carla::road::MapData::GetSignals () const inline
Definition at line 78 of file MapData.h.
References _signals.
Referenced by carla::road::Map::GetSignals().
Friends And Related Function Documentation
MapBuilder
friend class MapBuilder friend
Definition at line 88 of file MapData.h.
Member Data Documentation
_controllers
std::unordered_map<ContId, std::unique_ptr<Controller> > carla::road::MapData::_controllers private
Definition at line 100 of file MapData.h.
Referenced by GetControllers().
_geo_reference
geom::GeoLocation carla::road::MapData::_geo_reference private
Definition at line 92 of file MapData.h.
Referenced by GetGeoReference(), and carla::road::MapBuilder::SetGeoReference().
_junctions
std::unordered_map<JuncId, Junction> carla::road::MapData::_junctions private
Definition at line 96 of file MapData.h.
Referenced by GetJunction(), and GetJunctions().
_roads
std::unordered_map<RoadId, Road> carla::road::MapData::_roads private
Definition at line 94 of file MapData.h.
Referenced by ContainsRoad(), GetRoad(), GetRoadCount(), and GetRoads().
_signals
std::unordered_map<SignId, std::unique_ptr<Signal> > carla::road::MapData::_signals private
Definition at line 98 of file MapData.h.
Referenced by carla::road::MapBuilder::CheckSignalsOnRoads(), and GetSignals().
The documentation for this class was generated from the following files:
MapData.h
MapData.cpp