CARLA: carla::rss::RssCheck::RssObjectChecker Class Reference
carla::rss::RssCheck::RssObjectChecker Class Reference
Public Member Functions
void operator() (const carla::SharedPtr< carla::client::Actor > other_traffic_participant) const
RssObjectChecker (RssCheck const &rss_check, ::ad::rss::map::RssSceneCreation &scene_creation, carla::client::Vehicle const &carla_ego_vehicle, CarlaRssState const &carla_rss_state, ::ad::map::landmark::LandmarkIdSet const &green_traffic_lights)
Private Attributes
carla::client::Vehicle const & _carla_ego_vehicle
CarlaRssState const & _carla_rss_state
::ad::map::landmark::LandmarkIdSet const & _green_traffic_lights
RssCheck const & _rss_check
::ad::rss::map::RssSceneCreation & _scene_creation
Detailed Description
Definition at line 278 of file RssCheck.h.
Constructor & Destructor Documentation
RssObjectChecker()
carla::rss::RssCheck::RssObjectChecker::RssObjectChecker (RssCheck const & rss_check, ::ad::rss::map::RssSceneCreation & scene_creation, carla::client::Vehicle const & carla_ego_vehicle, CarlaRssState const & carla_rss_state, ::ad::map::landmark::LandmarkIdSet const & green_traffic_lights)
Definition at line 811 of file RssCheck.cpp.
Referenced by carla::rss::RssCheck::CreateWorldModel().
Member Function Documentation
operator()()
void carla::rss::RssCheck::RssObjectChecker::operator() (const carla::SharedPtr< carla::client::Actor > other_traffic_participant) const
Definition at line 822 of file RssCheck.cpp.
References carla::rss::RssCheck::_actor_constellation_callback, _carla_ego_vehicle, _carla_rss_state, _green_traffic_lights, carla::rss::RssCheck::_logger, _rss_check, _scene_creation, carla::rss::RssCheck::CarlaRssState::ego_dynamics_on_route, carla::rss::EgoDynamicsOnRoute::ego_heading_change, carla::rss::RssCheck::CarlaRssState::ego_match_object, carla::rss::RssCheck::CarlaRssState::ego_route, carla::rss::EgoDynamicsOnRoute::ego_speed, carla::rss::EgoDynamicsOnRoute::ego_steering_angle, carla::rss::RssCheck::GetHeadingChange(), carla::client::detail::ActorState::GetId(), carla::rss::RssCheck::GetMatchObject(), and carla::rss::RssCheck::GetSpeed().
Member Data Documentation
_carla_ego_vehicle
carla::client::Vehicle const& carla::rss::RssCheck::RssObjectChecker::_carla_ego_vehicle private
Definition at line 288 of file RssCheck.h.
Referenced by operator()().
_carla_rss_state
CarlaRssState const& carla::rss::RssCheck::RssObjectChecker::_carla_rss_state private
Definition at line 289 of file RssCheck.h.
Referenced by carla::rss::RssCheck::CreateWorldModel(), and operator()().
_green_traffic_lights
::ad::map::landmark::LandmarkIdSet const& carla::rss::RssCheck::RssObjectChecker::_green_traffic_lights private
Definition at line 290 of file RssCheck.h.
Referenced by operator()().
_rss_check
RssCheck const& carla::rss::RssCheck::RssObjectChecker::_rss_check private
Definition at line 286 of file RssCheck.h.
Referenced by operator()().
_scene_creation
::ad::rss::map::RssSceneCreation& carla::rss::RssCheck::RssObjectChecker::_scene_creation private
Definition at line 287 of file RssCheck.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
RssCheck.h
RssCheck.cpp