CARLA: FSensorManager Class Reference
FSensorManager Class Reference
#include <SensorManager.h>
Public Member Functions
void DeRegisterSensor (ASensor *Sensor)
void PostPhysTick (UWorld *World, ELevelTick TickType, float DeltaSeconds)
void RegisterSensor (ASensor *Sensor)
Private Attributes
TArray< ASensor * > SensorList
Detailed Description
Definition at line 11 of file SensorManager.h.
Member Function Documentation
DeRegisterSensor()
void FSensorManager::DeRegisterSensor (ASensor * Sensor)
Definition at line 15 of file SensorManager.cpp.
References SensorList.
Referenced by ASensor::EndPlay().
PostPhysTick()
void FSensorManager::PostPhysTick (UWorld * World, ELevelTick TickType, float DeltaSeconds)
Definition at line 20 of file SensorManager.cpp.
References SensorList.
Referenced by FCarlaEngine::OnPostTick().
RegisterSensor()
void FSensorManager::RegisterSensor (ASensor * Sensor)
Definition at line 10 of file SensorManager.cpp.
References SensorList.
Referenced by ASensor::BeginPlay().
Member Data Documentation
SensorList
TArray<ASensor*> FSensorManager::SensorList private
Definition at line 24 of file SensorManager.h.
Referenced by DeRegisterSensor(), PostPhysTick(), and RegisterSensor().
The documentation for this class was generated from the following files:
SensorManager.h
SensorManager.cpp