CARLA: traffic_manager::Parameters Class Reference
traffic_manager::Parameters Class Reference
#include <Parameters.h>
Public Member Functions
bool GetAutoLaneChange (const ActorPtr &actor)
Method to query auto lane change rule for a vehicle.
bool GetCollisionDetection (const ActorPtr &reference_actor, const ActorPtr &other_actor)
Method to query collision avoidance rule between a pair of vehicles.
float GetDistanceToLeadingVehicle (const ActorPtr &actor)
Method to query distance to leading vehicle for a given vehicle.
ChangeLaneInfo GetForceLaneChange (const ActorPtr &actor)
Method to query lane change command for a vehicle.
float GetPercentageIgnoreActors (const ActorPtr &actor)
Method to get % to ignore any actor.
float GetPercentageRunningLight (const ActorPtr &actor)
Method to get % to run any traffic light.
float GetVehicleTargetVelocity (const ActorPtr &actor)
Method to query target velocity for a vehicle.
Parameters ()
void SetAutoLaneChange (const ActorPtr &actor, const bool enable)
Enable / disable automatic lane change on a vehicle.
void SetCollisionDetection (const ActorPtr &reference_actor, const ActorPtr &other_actor, const bool detect_collision)
Set collision detection rules between vehicles.
void SetDistanceToLeadingVehicle (const ActorPtr &actor, const float distance)
Method to specify how much distance a vehicle should maintain to the leading vehicle.
void SetForceLaneChange (const ActorPtr &actor, const bool direction)
Method to force lane change on a vehicle.
void SetGlobalPercentageSpeedDifference (float const percentage)
Set global target velocity.
void SetPercentageIgnoreActors (const ActorPtr &actor, const float perc)
Method to set % to ignore any actor.
void SetPercentageRunningLight (const ActorPtr &actor, const float perc)
Method to set % to run any traffic light.
void SetPercentageSpeedDifference (const ActorPtr &actor, const float percentage)
Set target velocity specific to a vehicle.
~Parameters ()
Private Attributes
AtomicMap< ActorId, bool > auto_lane_change
Map containing auto lane change commands.
AtomicMap< ActorId, float > distance_to_leading_vehicle
Map containing distance to leading vehicle command.
AtomicMap< ActorId, ChangeLaneInfo > force_lane_change
Map containing force lane change commands.
float global_percentage_difference_from_limit = 0
Global target velocity limit % difference.
AtomicMap< ActorId, std::shared_ptr< AtomicActorSet > > ignore_collision
Map containing a set of actors to be ignored during collision detection.
AtomicMap< ActorId, float > perc_ignore_actors
Map containing % of ignoring actors.
AtomicMap< ActorId, float > perc_run_traffic_light
Map containing % of running a traffic light.
AtomicMap< ActorId, float > percentage_difference_from_speed_limit
Target velocity map for individual vehicles.
Detailed Description
Definition at line 28 of file Parameters.h.
Constructor & Destructor Documentation
traffic_manager::Parameters::Parameters ()
Definition at line 13 of file Parameters.cpp.
traffic_manager::Parameters::~Parameters ()
Definition at line 15 of file Parameters.cpp.
Member Function Documentation
bool traffic_manager::Parameters::GetAutoLaneChange (const ActorPtr & actor)
Method to query auto lane change rule for a vehicle.
Definition at line 119 of file Parameters.cpp.
References auto_lane_change, traffic_manager::AtomicMap< Key, Value >::Contains(), and traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by traffic_manager::LocalizationStage::Action().
bool traffic_manager::Parameters::GetCollisionDetection (const ActorPtr & reference_actor, const ActorPtr & other_actor)
Method to query collision avoidance rule between a pair of vehicles.
Definition at line 91 of file Parameters.cpp.
References ignore_collision.
Referenced by traffic_manager::CollisionStage::Action().
float traffic_manager::Parameters::GetDistanceToLeadingVehicle (const ActorPtr & actor)
Method to query distance to leading vehicle for a given vehicle.
Definition at line 131 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::Contains(), distance_to_leading_vehicle, and traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by traffic_manager::CollisionStage::GetGeodesicBoundary().
ChangeLaneInfo traffic_manager::Parameters::GetForceLaneChange (const ActorPtr & actor)
Method to query lane change command for a vehicle.
Definition at line 105 of file Parameters.cpp.
References force_lane_change.
Referenced by traffic_manager::LocalizationStage::Action().
float traffic_manager::Parameters::GetPercentageIgnoreActors (const ActorPtr & actor)
Method to get % to ignore any actor.
Definition at line 169 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::Contains(), traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_ignore_actors.
Referenced by traffic_manager::CollisionStage::Action().
float traffic_manager::Parameters::GetPercentageRunningLight (const ActorPtr & actor)
Method to get % to run any traffic light.
Definition at line 157 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::Contains(), traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_run_traffic_light.
Referenced by traffic_manager::TrafficLightStage::Action().
float traffic_manager::Parameters::GetVehicleTargetVelocity (const ActorPtr & actor)
Method to query target velocity for a vehicle.
Definition at line 77 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::Contains(), carla::client::Vehicle::GetSpeedLimit(), traffic_manager::AtomicMap< Key, Value >::GetValue(), global_percentage_difference_from_limit, and percentage_difference_from_speed_limit.
Referenced by traffic_manager::MotionPlannerStage::Action().
void traffic_manager::Parameters::SetAutoLaneChange (const ActorPtr & actor, const bool enable)
Enable / disable automatic lane change on a vehicle.
Definition at line 64 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::AddEntry(), and auto_lane_change.
Referenced by traffic_manager::TrafficManager::SetAutoLaneChange().
void traffic_manager::Parameters::SetCollisionDetection (const ActorPtr & reference_actor, const ActorPtr & other_actor, const bool detect_collision)
Set collision detection rules between vehicles.
Definition at line 25 of file Parameters.cpp.
References ignore_collision.
Referenced by traffic_manager::TrafficManager::SetCollisionDetection().
void traffic_manager::Parameters::SetDistanceToLeadingVehicle (const ActorPtr & actor, const float distance)
Method to specify how much distance a vehicle should maintain to the leading vehicle.
Definition at line 70 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::AddEntry(), and distance_to_leading_vehicle.
Referenced by traffic_manager::TrafficManager::SetDistanceToLeadingVehicle().
void traffic_manager::Parameters::SetForceLaneChange (const ActorPtr & actor, const bool direction)
Method to force lane change on a vehicle.
Direction flag can be set to true for left and false for right.
Definition at line 57 of file Parameters.cpp.
References force_lane_change.
Referenced by traffic_manager::TrafficManager::SetForceLaneChange().
void traffic_manager::Parameters::SetGlobalPercentageSpeedDifference (float const percentage)
Set global target velocity.
Definition at line 21 of file Parameters.cpp.
References global_percentage_difference_from_limit.
Referenced by traffic_manager::TrafficManager::SetGlobalPercentageSpeedDifference(), and traffic_manager::TrafficManager::TrafficManager().
void traffic_manager::Parameters::SetPercentageIgnoreActors (const ActorPtr & actor, const float perc)
Method to set % to ignore any actor.
Definition at line 150 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::AddEntry(), and perc_ignore_actors.
Referenced by traffic_manager::TrafficManager::SetPercentageIgnoreActors().
void traffic_manager::Parameters::SetPercentageRunningLight (const ActorPtr & actor, const float perc)
Method to set % to run any traffic light.
Definition at line 143 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::AddEntry(), and perc_run_traffic_light.
Referenced by traffic_manager::TrafficManager::SetPercentageRunningLight().
void traffic_manager::Parameters::SetPercentageSpeedDifference (const ActorPtr & actor, const float percentage)
Set target velocity specific to a vehicle.
Definition at line 17 of file Parameters.cpp.
References traffic_manager::AtomicMap< Key, Value >::AddEntry(), and percentage_difference_from_speed_limit.
Referenced by traffic_manager::TrafficManager::SetPercentageSpeedDifference().
Member Data Documentation
AtomicMap<ActorId, bool> traffic_manager::Parameters::auto_lane_change private
Map containing auto lane change commands.
Definition at line 43 of file Parameters.h.
Referenced by GetAutoLaneChange(), and SetAutoLaneChange().
AtomicMap<ActorId, float> traffic_manager::Parameters::distance_to_leading_vehicle private
Map containing distance to leading vehicle command.
Definition at line 39 of file Parameters.h.
Referenced by GetDistanceToLeadingVehicle(), and SetDistanceToLeadingVehicle().
AtomicMap<ActorId, ChangeLaneInfo> traffic_manager::Parameters::force_lane_change private
Map containing force lane change commands.
Definition at line 41 of file Parameters.h.
Referenced by GetForceLaneChange(), and SetForceLaneChange().
float traffic_manager::Parameters::global_percentage_difference_from_limit = 0 private
Global target velocity limit % difference.
Definition at line 35 of file Parameters.h.
Referenced by GetVehicleTargetVelocity(), and SetGlobalPercentageSpeedDifference().
AtomicMap<ActorId, std::shared_ptr<AtomicActorSet> > traffic_manager::Parameters::ignore_collision private
Map containing a set of actors to be ignored during collision detection.
Definition at line 37 of file Parameters.h.
Referenced by GetCollisionDetection(), and SetCollisionDetection().
AtomicMap<ActorId, float> traffic_manager::Parameters::perc_ignore_actors private
Map containing % of ignoring actors.
Definition at line 47 of file Parameters.h.
Referenced by GetPercentageIgnoreActors(), and SetPercentageIgnoreActors().
AtomicMap<ActorId, float> traffic_manager::Parameters::perc_run_traffic_light private
Map containing % of running a traffic light.
Definition at line 45 of file Parameters.h.
Referenced by GetPercentageRunningLight(), and SetPercentageRunningLight().
AtomicMap<ActorId, float> traffic_manager::Parameters::percentage_difference_from_speed_limit private
Target velocity map for individual vehicles.
Definition at line 33 of file Parameters.h.
Referenced by GetVehicleTargetVelocity(), and SetPercentageSpeedDifference().
The documentation for this class was generated from the following files:
Parameters.h
Parameters.cpp