CARLA: geometry_msgs::msg::PosePubSubType Class Reference
geometry_msgs::msg::PosePubSubType Class Reference
This class represents the TopicDataType of the type Pose defined by the user in the IDL file.
#include <PosePubSubTypes.h>
Public Types
typedef Pose type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport PosePubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~PosePubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type Pose defined by the user in the IDL file.
Definition at line 75 of file PosePubSubTypes.h.
Member Typedef Documentation
type
typedef Pose geometry_msgs::msg::PosePubSubType::type
Definition at line 79 of file PosePubSubTypes.h.
Constructor & Destructor Documentation
PosePubSubType()
geometry_msgs::msg::PosePubSubType::PosePubSubType ()
Definition at line 32 of file PosePubSubTypes.cpp.
References geometry_msgs::msg::Pose::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::Pose::getMaxCdrSerializedSize(), geometry_msgs::msg::Pose::isKeyDefined(), and m_keyBuffer.
~PosePubSubType()
geometry_msgs::msg::PosePubSubType::~PosePubSubType () override virtual
Definition at line 45 of file PosePubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::PosePubSubType::createData () override virtual
Definition at line 122 of file PosePubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::PosePubSubType::deleteData (void * data) override virtual
Definition at line 127 of file PosePubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::PosePubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file PosePubSubTypes.cpp.
References geometry_msgs::msg::Pose::deserialize().
getKey()
bool geometry_msgs::msg::PosePubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file PosePubSubTypes.cpp.
References geometry_msgs::msg::Pose::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::Pose::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::PosePubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file PosePubSubTypes.cpp.
References geometry_msgs::msg::Pose::getCdrSerializedSize().
is_plain_impl()
static constexpr bool geometry_msgs::msg::PosePubSubType::is_plain_impl () inline static constexpr private
Definition at line 134 of file PosePubSubTypes.h.
serialize()
bool geometry_msgs::msg::PosePubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file PosePubSubTypes.cpp.
References geometry_msgs::msg::Pose::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::PosePubSubType::m_keyBuffer
Definition at line 132 of file PosePubSubTypes.h.
Referenced by getKey(), PosePubSubType(), and ~PosePubSubType().
m_md5
MD5 geometry_msgs::msg::PosePubSubType::m_md5
Definition at line 131 of file PosePubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
PosePubSubTypes.h
PosePubSubTypes.cpp