CARLA: geometry_msgs::msg::Quaternion Class Reference
geometry_msgs::msg::Quaternion Class Reference
This class represents the structure Quaternion defined by the user in the IDL file.
#include <Quaternion.h>
Public Member Functions
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const Quaternion &x) const
Comparison operator.
eProsima_user_DllExport Quaternion & operator= (const Quaternion &x)
Copy assignment.
eProsima_user_DllExport Quaternion & operator= (Quaternion &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Quaternion &x) const
Comparison operator.
eProsima_user_DllExport Quaternion ()
Default constructor.
eProsima_user_DllExport Quaternion (const Quaternion &x)
Copy constructor.
eProsima_user_DllExport Quaternion (Quaternion &&x) noexcept
Move constructor.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport double & w ()
This function returns a reference to member w.
eProsima_user_DllExport double w () const
This function returns the value of member w.
eProsima_user_DllExport void w (double _w)
This function sets a value in member w.
eProsima_user_DllExport double & x ()
This function returns a reference to member x.
eProsima_user_DllExport double x () const
This function returns the value of member x.
eProsima_user_DllExport void x (double _x)
This function sets a value in member x.
eProsima_user_DllExport double & y ()
This function returns a reference to member y.
eProsima_user_DllExport double y () const
This function returns the value of member y.
eProsima_user_DllExport void y (double _y)
This function sets a value in member y.
eProsima_user_DllExport double & z ()
This function returns a reference to member z.
eProsima_user_DllExport double z () const
This function returns the value of member z.
eProsima_user_DllExport void z (double _z)
This function sets a value in member z.
eProsima_user_DllExport ~Quaternion ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::Quaternion &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
double m_w
double m_x
double m_y
double m_z
Detailed Description
This class represents the structure Quaternion defined by the user in the IDL file.
Definition at line 70 of file Quaternion.h.
Constructor & Destructor Documentation
Quaternion() [1/3]
geometry_msgs::msg::Quaternion::Quaternion ()
Default constructor.
Definition at line 40 of file Quaternion.cpp.
~Quaternion()
geometry_msgs::msg::Quaternion::~Quaternion ()
Default destructor.
Definition at line 52 of file Quaternion.cpp.
Quaternion() [2/3]
geometry_msgs::msg::Quaternion::Quaternion (const Quaternion & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::Quaternion that will be copied.
Definition at line 56 of file Quaternion.cpp.
References m_w, m_x, m_y, and m_z.
Quaternion() [3/3]
geometry_msgs::msg::Quaternion::Quaternion (Quaternion && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::Quaternion that will be copied.
Definition at line 65 of file Quaternion.cpp.
Member Function Documentation
deserialize()
void geometry_msgs::msg::Quaternion::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 138 of file Quaternion.cpp.
Referenced by geometry_msgs::msg::QuaternionPubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::Quaternion::getCdrSerializedSize (const geometry_msgs::msg::Quaternion & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 115 of file Quaternion.cpp.
Referenced by geometry_msgs::msg::Pose::getCdrSerializedSize(), geometry_msgs::msg::Transform::getCdrSerializedSize(), sensor_msgs::msg::Imu::getCdrSerializedSize(), and geometry_msgs::msg::QuaternionPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::Quaternion::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 259 of file Quaternion.cpp.
References geometry_msgs_msg_Quaternion_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::QuaternionPubSubType::getKey(), and geometry_msgs::msg::QuaternionPubSubType::QuaternionPubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::Quaternion::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 108 of file Quaternion.cpp.
References geometry_msgs_msg_Quaternion_max_cdr_typesize.
Referenced by geometry_msgs::msg::QuaternionPubSubType::QuaternionPubSubType().
isKeyDefined()
bool geometry_msgs::msg::Quaternion::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 266 of file Quaternion.cpp.
Referenced by geometry_msgs::msg::QuaternionPubSubType::QuaternionPubSubType().
operator!=()
bool geometry_msgs::msg::Quaternion::operator!= (const Quaternion & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Quaternion object to compare.
Definition at line 102 of file Quaternion.cpp.
operator=() [1/2]
geometry_msgs::msg::Quaternion & geometry_msgs::msg::Quaternion::operator= (const Quaternion & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::Quaternion that will be copied.
Definition at line 74 of file Quaternion.cpp.
References m_w, m_x, m_y, and m_z.
operator=() [2/2]
geometry_msgs::msg::Quaternion & geometry_msgs::msg::Quaternion::operator= (Quaternion && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::Quaternion that will be copied.
Definition at line 85 of file Quaternion.cpp.
References m_x.
operator==()
bool geometry_msgs::msg::Quaternion::operator== (const Quaternion & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Quaternion object to compare.
Definition at line 96 of file Quaternion.cpp.
References m_w, m_x, m_y, and m_z.
serialize()
void geometry_msgs::msg::Quaternion::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 129 of file Quaternion.cpp.
Referenced by geometry_msgs::msg::QuaternionPubSubType::serialize().
serializeKey()
void geometry_msgs::msg::Quaternion::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 271 of file Quaternion.cpp.
Referenced by geometry_msgs::msg::QuaternionPubSubType::getKey().
w() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Quaternion::w ()
This function returns a reference to member w.
Returns
Reference to member w
w() [2/3]
double & geometry_msgs::msg::Quaternion::w () const
This function returns the value of member w.
This function returns a reference to member w.
Returns
Value of member w
Reference to member w
Definition at line 245 of file Quaternion.cpp.
w() [3/3]
void geometry_msgs::msg::Quaternion::w (double _w)
This function sets a value in member w.
Parameters
_w New value for member w
Definition at line 235 of file Quaternion.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData().
x() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Quaternion::x ()
This function returns a reference to member x.
Returns
Reference to member x
x() [2/3]
double & geometry_msgs::msg::Quaternion::x () const
This function returns the value of member x.
This function returns a reference to member x.
Returns
Value of member x
Reference to member x
Definition at line 161 of file Quaternion.cpp.
x() [3/3]
void geometry_msgs::msg::Quaternion::x (double _x)
This function sets a value in member x.
Parameters
_x New value for member x
Definition at line 151 of file Quaternion.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData().
y() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Quaternion::y ()
This function returns a reference to member y.
Returns
Reference to member y
y() [2/3]
double & geometry_msgs::msg::Quaternion::y () const
This function returns the value of member y.
This function returns a reference to member y.
Returns
Value of member y
Reference to member y
Definition at line 189 of file Quaternion.cpp.
y() [3/3]
void geometry_msgs::msg::Quaternion::y (double _y)
This function sets a value in member y.
Parameters
_y New value for member y
Definition at line 179 of file Quaternion.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData().
z() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Quaternion::z ()
This function returns a reference to member z.
Returns
Reference to member z
z() [2/3]
double & geometry_msgs::msg::Quaternion::z () const
This function returns the value of member z.
This function returns a reference to member z.
Returns
Value of member z
Reference to member z
Definition at line 217 of file Quaternion.cpp.
z() [3/3]
void geometry_msgs::msg::Quaternion::z (double _z)
This function sets a value in member z.
Parameters
_z New value for member z
Definition at line 207 of file Quaternion.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData().
Member Data Documentation
m_w
double geometry_msgs::msg::Quaternion::m_w private
Definition at line 260 of file Quaternion.h.
Referenced by operator=(), operator==(), and Quaternion().
m_x
double geometry_msgs::msg::Quaternion::m_x private
Definition at line 257 of file Quaternion.h.
Referenced by operator=(), operator==(), and Quaternion().
m_y
double geometry_msgs::msg::Quaternion::m_y private
Definition at line 258 of file Quaternion.h.
Referenced by operator=(), operator==(), and Quaternion().
m_z
double geometry_msgs::msg::Quaternion::m_z private
Definition at line 259 of file Quaternion.h.
Referenced by operator=(), operator==(), and Quaternion().
The documentation for this class was generated from the following files:
Quaternion.h
Quaternion.cpp