CARLA: carla::client::detail::EpisodeProxyImpl< PointerT > Class Template Reference
carla::client::detail::EpisodeProxyImpl< PointerT > Class Template Reference
Provides access to the Simulator during a given episode.
#include <EpisodeProxy.h>
Public Types
using SharedPtrType = EpisodeProxyPointerType::Shared
Public Member Functions
void Clear () noexcept
EpisodeProxyImpl ()=default
EpisodeProxyImpl (SharedPtrType simulator)
template<typename T >
EpisodeProxyImpl (EpisodeProxyImpl< T > other)
auto GetId () const noexcept
bool IsValid () const noexcept
SharedPtrType Lock () const
Same as TryLock but never return nullptr.
SharedPtrType TryLock () const noexcept
Private Attributes
uint64_t _episode_id
PointerT _simulator
Friends
template<typename T >
class EpisodeProxyImpl
Detailed Description
template<typename PointerT>
class carla::client::detail::EpisodeProxyImpl< PointerT >
Provides access to the Simulator during a given episode.
After the episode is ended any access to the simulator throws an std::runtime_error.
Definition at line 28 of file EpisodeProxy.h.
Member Typedef Documentation
SharedPtrType
template<typename PointerT> using carla::client::detail::EpisodeProxyImpl< PointerT >::SharedPtrType = EpisodeProxyPointerType::Shared
Definition at line 31 of file EpisodeProxy.h.
Constructor & Destructor Documentation
EpisodeProxyImpl() [1/3]
template<typename PointerT> carla::client::detail::EpisodeProxyImpl< PointerT >::EpisodeProxyImpl () default
EpisodeProxyImpl() [2/3]
template<typename T > carla::client::detail::EpisodeProxyImpl< T >::EpisodeProxyImpl (SharedPtrType simulator)
Definition at line 27 of file EpisodeProxy.cpp.
EpisodeProxyImpl() [3/3]
template<typename PointerT> template<typename T > carla::client::detail::EpisodeProxyImpl< PointerT >::EpisodeProxyImpl (EpisodeProxyImpl< T > other) inline
Definition at line 38 of file EpisodeProxy.h.
Member Function Documentation
Clear()
template<typename T > void carla::client::detail::EpisodeProxyImpl< T >::Clear (void) noexcept
Definition at line 50 of file EpisodeProxy.cpp.
Referenced by carla::client::detail::Simulator::DestroyActor().
GetId()
template<typename PointerT> auto carla::client::detail::EpisodeProxyImpl< PointerT >::GetId () const inline noexcept
Definition at line 42 of file EpisodeProxy.h.
Referenced by carla::client::World::GetId(), and carla::client::detail::Simulator::LoadEpisode().
IsValid()
template<typename PointerT> bool carla::client::detail::EpisodeProxyImpl< PointerT >::IsValid () const inline noexcept
Definition at line 53 of file EpisodeProxy.h.
Referenced by carla::client::Actor::IsActive(), carla::client::Actor::IsAlive(), and carla::client::Actor::IsDormant().
Lock()
template<typename T > EpisodeProxyImpl< T >::SharedPtrType carla::client::detail::EpisodeProxyImpl< T >::Lock () const
Same as TryLock but never return nullptr.
Exceptions
std::runtime_error if episode is gone.
Definition at line 39 of file EpisodeProxy.cpp.
Referenced by carla::client::Actor::AddAngularImpulse(), carla::client::Actor::AddForce(), carla::client::Actor::AddImpulse(), carla::client::Actor::AddTorque(), carla::client::Vehicle::ApplyAckermannControl(), carla::client::Vehicle::ApplyAckermannControllerSettings(), carla::client::World::ApplyColorTextureToObject(), carla::client::World::ApplyColorTextureToObjects(), carla::client::Walker::ApplyControl(), carla::client::Vehicle::ApplyControl(), carla::client::World::ApplyFloatColorTextureToObject(), carla::client::World::ApplyFloatColorTextureToObjects(), carla::client::Vehicle::ApplyPhysicsControl(), carla::client::World::ApplySettings(), carla::client::Walker::BlendPose(), carla::client::World::CastRay(), carla::client::Vehicle::CloseDoor(), carla::traffic_manager::TrafficManager::CreateTrafficManagerClient(), carla::traffic_manager::TrafficManager::CreateTrafficManagerServer(), carla::client::Actor::Destroy(), carla::client::Actor::DisableConstantVelocity(), carla::client::DrawShape(), carla::client::Vehicle::EnableCarSim(), carla::client::Vehicle::EnableChronoPhysics(), carla::client::Actor::EnableConstantVelocity(), carla::client::World::EnableEnvironmentObjects(), carla::client::TrafficLight::Freeze(), carla::client::World::FreezeAllTrafficLights(), carla::client::Actor::GetAcceleration(), carla::client::Vehicle::GetAckermannControllerSettings(), carla::client::World::GetActor(), carla::client::World::GetActors(), carla::client::Actor::GetActorState(), carla::client::TrafficLight::GetAffectedLaneWaypoints(), carla::client::Actor::GetAngularVelocity(), carla::client::World::GetBlueprintLibrary(), carla::client::Walker::GetBonesTransform(), carla::client::Vehicle::GetControl(), carla::client::TrafficLight::GetElapsedTime(), carla::client::World::GetEnvironmentObjects(), carla::client::Vehicle::GetFailureState(), carla::client::TrafficLight::GetGreenTime(), carla::client::TrafficLight::GetGroupTrafficLights(), carla::client::World::GetLevelBBs(), carla::client::TrafficLight::GetLightBoxes(), carla::client::World::GetLightManager(), carla::client::Vehicle::GetLightState(), carla::client::Actor::GetLocation(), carla::client::World::GetMap(), carla::client::World::GetNamesOfAllObjects(), carla::client::TrafficLight::GetOpenDRIVEID(), carla::client::Vehicle::GetPhysicsControl(), carla::client::TrafficLight::GetPoleIndex(), carla::client::Walker::GetPoseFromAnimation(), carla::client::WalkerAIController::GetRandomLocation(), carla::client::World::GetRandomLocationFromNavigation(), carla::client::TrafficLight::GetRedTime(), carla::client::World::GetSettings(), carla::client::World::GetSnapshot(), carla::client::World::GetSpectator(), carla::client::Vehicle::GetSpeedLimit(), carla::client::TrafficLight::GetState(), carla::client::TrafficLight::GetStopWaypoints(), carla::client::Vehicle::GetTrafficLight(), carla::client::Vehicle::GetTrafficLightState(), carla::client::Actor::GetTransform(), carla::client::World::GetVehiclesLightStates(), carla::client::Actor::GetVelocity(), carla::client::Walker::GetWalkerControl(), carla::client::World::GetWeather(), carla::client::Vehicle::GetWheelSteerAngle(), carla::client::TrafficLight::GetYellowTime(), carla::client::WalkerAIController::GoToLocation(), carla::client::Vehicle::IsAtTrafficLight(), carla::client::TrafficLight::IsFrozen(), carla::client::ServerSideSensor::Listen(), carla::client::RssSensor::Listen(), carla::client::World::LoadLevelLayer(), carla::client::World::OnTick(), carla::client::Vehicle::OpenDoor(), carla::client::World::ProjectPoint(), carla::client::World::RemoveOnTick(), carla::traffic_manager::TrafficManagerRemote::Reset(), carla::traffic_manager::TrafficManagerLocal::Reset(), carla::client::World::ResetAllTrafficLights(), carla::client::TrafficLight::ResetGroup(), carla::traffic_manager::TrafficManagerLocal::Run(), carla::client::Walker::SetBonesTransform(), carla::client::Actor::SetEnableGravity(), carla::client::TrafficLight::SetGreenTime(), carla::client::Vehicle::SetLightState(), carla::client::Actor::SetLocation(), carla::client::WalkerAIController::SetMaxSpeed(), carla::client::World::SetPedestriansCrossFactor(), carla::client::World::SetPedestriansSeed(), carla::client::TrafficLight::SetRedTime(), carla::client::Actor::SetSimulatePhysics(), carla::client::TrafficLight::SetState(), carla::client::Actor::SetTargetAngularVelocity(), carla::client::Actor::SetTargetVelocity(), carla::client::Actor::SetTransform(), carla::traffic_manager::TrafficManagerLocal::SetupLocalMap(), carla::client::World::SetWeather(), carla::client::Vehicle::SetWheelSteerDirection(), carla::client::TrafficLight::SetYellowTime(), carla::client::Vehicle::ShowDebugTelemetry(), carla::client::World::SpawnActor(), carla::client::WalkerAIController::Start(), carla::traffic_manager::TrafficManagerRemote::Start(), carla::client::WalkerAIController::Stop(), carla::client::ServerSideSensor::Stop(), carla::client::RssSensor::Stop(), carla::client::World::Tick(), carla::client::World::UnloadLevelLayer(), carla::client::Vehicle::UseCarSimRoad(), carla::client::World::WaitForTick(), and carla::traffic_manager::TrafficManagerLocal::~TrafficManagerLocal().
TryLock()
template<typename T > EpisodeProxyImpl< T >::SharedPtrType carla::client::detail::EpisodeProxyImpl< T >::TryLock () const noexcept
Definition at line 32 of file EpisodeProxy.cpp.
Friends And Related Function Documentation
EpisodeProxyImpl
template<typename PointerT> template<typename T > friend class EpisodeProxyImpl friend
Definition at line 62 of file EpisodeProxy.h.
Member Data Documentation
_episode_id
template<typename PointerT> uint64_t carla::client::detail::EpisodeProxyImpl< PointerT >::_episode_id private
Definition at line 64 of file EpisodeProxy.h.
_simulator
template<typename PointerT> PointerT carla::client::detail::EpisodeProxyImpl< PointerT >::_simulator private
Definition at line 66 of file EpisodeProxy.h.
The documentation for this class was generated from the following files:
EpisodeProxy.h
EpisodeProxy.cpp