CARLA: carla::traffic_manager::LocalizationStage Class Reference
carla::traffic_manager::LocalizationStage Class Reference
This class is responsible for maintaining a horizon of waypoints ahead of the vehicle for it to follow.
#include <LocalizationStage.h>
Public Member Functions
void Action () override
Implement this method with logic to process data inside the stage.
void DataReceiver () override
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
void DataSender () override
Implement this method with logic to gather results from the action threads and send to next stage(s).
LocalizationStage (std::string stage_name, std::shared_ptr< LocalizationToPlannerMessenger > planner_messenger, std::shared_ptr< LocalizationToCollisionMessenger > collision_messenger, std::shared_ptr< LocalizationToTrafficLightMessenger > traffic_light_messenger, AtomicActorSet &registered_actors, InMemoryMap &local_map, Parameters &parameters, carla::client::DebugHelper &debug_helper, carla::client::detail::EpisodeProxy &episodeProxy)
~LocalizationStage ()
Public Member Functions inherited from carla::traffic_manager::PipelineStage
PipelineStage (const std::string &stage_name)
void Start ()
void Stop ()
virtual ~PipelineStage ()
Private Member Functions
SimpleWaypointPtr AssignLaneChange (Actor vehicle, const cg::Location &vehicle_location, bool force, bool direction)
Method to determine lane change and obtain target lane waypoint.
void CleanActor (const ActorId actor_id)
void DrawBuffer (Buffer &buffer)
A simple method used to draw waypoint buffer ahead of a vehicle.
SimpleWaypointPtr GetSafeLocationAfterJunction (const Vehicle &vehicle, Buffer &waypoint_buffer)
bool IsVehicleStuck (const Actor &actor)
void PopWaypoint (Buffer &buffer, ActorId actor_id)
void PushWaypoint (Buffer &buffer, ActorId actor_id, SimpleWaypointPtr &waypoint)
Methods to modify waypoint buffer and track traffic.
void ScanUnregisteredVehicles ()
Method to scan for unregistered actors and update their grid positioning.
bool TryDestroyVehicle (const Actor &actor)
void UpdateIdleTime (const Actor &actor)
Methods for idle vehicle elimination.
Private Attributes
std::vector< Actor > actor_list
List of actors registered with the traffic manager in current update cycle.
std::map< carla::ActorId, bool > approached
Used to only calculate the extended buffer once at junctions.
std::shared_ptr< BufferList > buffer_list
Structures to hold waypoint buffers for all vehicles.
std::shared_ptr< LocalizationToCollisionFrame > collision_frame_a
Output data frames to be shared with the collision stage.
std::shared_ptr< LocalizationToCollisionFrame > collision_frame_b
bool collision_frame_selector
std::shared_ptr< LocalizationToCollisionMessenger > collision_messenger
Pointer to messenger to collision stage.
cc::Timestamp current_timestamp
Variable to hold current timestamp from the world snapshot.
cc::DebugHelper & debug_helper
Reference to Carla's debug helper object.
double elapsed_last_actor_destruction = 0.0
Simulated seconds since the beginning of the current episode when the last actor was destroyed.
carla::client::detail::EpisodeProxy episode_proxy_ls
Reference to carla client connection object.
std::map< carla::ActorId, SimpleWaypointPtr > final_safe_points
Point used to know if the junction has free space after its end, mapped to their respective actor id.
std::unordered_map< ActorId, double > idle_time
Map of all vehicles' idle time.
std::unordered_map< ActorId, cg::Location > last_lane_change_location
Map to keep track of last lane change location.
InMemoryMap & local_map
Reference to local map-cache object.
std::pair< Actor, double > maximum_idle_time
Structure to hold the actor with the maximum idle time at each iteration.
uint64_t number_of_vehicles
Number of vehicles currently registered with the traffic manager.
Parameters & parameters
Runtime parameterization object.
std::shared_ptr< LocalizationToPlannerFrame > planner_frame_a
Output data frames to be shared with the motion planner stage.
std::shared_ptr< LocalizationToPlannerFrame > planner_frame_b
bool planner_frame_selector
Section keys to switch between the output data frames.
std::shared_ptr< LocalizationToPlannerMessenger > planner_messenger
Pointer to messenger to motion planner stage.
AtomicActorSet & registered_actors
Reference to set of all actors registered with the traffic manager.
int registered_actors_state
State counter to track changes in registered actors.
SnippetProfiler snippet_profiler
Code snippet execution time profiler.
TrackTraffic track_traffic
Object for tracking paths of the traffic vehicles.
std::shared_ptr< LocalizationToTrafficLightFrame > traffic_light_frame_a
Output data frames to be shared with the traffic light stage.
std::shared_ptr< LocalizationToTrafficLightFrame > traffic_light_frame_b
bool traffic_light_frame_selector
std::shared_ptr< LocalizationToTrafficLightMessenger > traffic_light_messenger
Pointer to messenger to traffic light stage.
std::unordered_map< ActorId, Actor > unregistered_actors
A structure used to keep track of actors spawned outside of traffic manager.
uint64_t unregistered_scan_duration = 0
Counter to track unregistered actors' scan interval.
std::unordered_map< ActorId, uint64_t > vehicle_id_to_index
Map connecting actor ids to indices of data arrays.
Additional Inherited Members
Protected Attributes inherited from carla::traffic_manager::PipelineStage
std::atomic< bool > run_stage
Flag to start/stop stage.
std::string stage_name
Stage name string.
Detailed Description
This class is responsible for maintaining a horizon of waypoints ahead of the vehicle for it to follow.
The class is also responsible for managing lane change decisions and modify the waypoint trajectory appropriately.
Definition at line 57 of file LocalizationStage.h.
Constructor & Destructor Documentation
carla::traffic_manager::LocalizationStage::LocalizationStage (std::string stage_name, std::shared_ptr< LocalizationToPlannerMessenger > planner_messenger, std::shared_ptr< LocalizationToCollisionMessenger > collision_messenger, std::shared_ptr< LocalizationToTrafficLightMessenger > traffic_light_messenger, AtomicActorSet & registered_actors, InMemoryMap & local_map, Parameters & parameters, carla::client::DebugHelper & debug_helper, carla::client::detail::EpisodeProxy & episodeProxy)
Definition at line 34 of file LocalizationStage.cpp.
References buffer_list, collision_frame_selector, maximum_idle_time, number_of_vehicles, planner_frame_selector, registered_actors_state, and traffic_light_frame_selector.
carla::traffic_manager::LocalizationStage::~LocalizationStage ()
Definition at line 71 of file LocalizationStage.cpp.
Member Function Documentation
void carla::traffic_manager::LocalizationStage::Action () override virtual
Implement this method with logic to process data inside the stage.
Implements carla::traffic_manager::PipelineStage.
Definition at line 73 of file LocalizationStage.cpp.
References carla::traffic_manager::LocalizationToPlannerData::actor, carla::traffic_manager::LocalizationToCollisionData::actor, carla::traffic_manager::LocalizationToTrafficLightData::actor, actor_list, approached, carla::traffic_manager::LocalizationToPlannerData::approaching_true_junction, AssignLaneChange(), carla::traffic_manager::LocalizationToCollisionData::buffer, buffer_list, carla::traffic_manager::ChangeLaneInfo::change_lane, carla::traffic_manager::LocalizationToCollisionData::closest_waypoint, carla::traffic_manager::LocalizationToTrafficLightData::closest_waypoint, collision_frame_a, collision_frame_b, collision_frame_selector, current_timestamp, carla::traffic_manager::LocalizationToPlannerData::deviation, carla::traffic_manager::DeviationCrossProduct(), carla::traffic_manager::DeviationDotProduct(), carla::traffic_manager::ChangeLaneInfo::direction, carla::traffic_manager::LocalizationToPlannerData::distance, carla::geom::Math::DistanceSquared(), carla::client::Timestamp::elapsed_seconds, episode_proxy_ls, final_safe_points, carla::traffic_manager::Parameters::GetAutoLaneChange(), carla::traffic_manager::Parameters::GetForceLaneChange(), carla::traffic_manager::Parameters::GetKeepRightPercentage(), carla::traffic_manager::TrackTraffic::GetOverlappingVehicles(), GetSafeLocationAfterJunction(), carla::client::Vehicle::GetSpeedLimit(), carla::traffic_manager::InMemoryMap::GetWaypoint(), carla::traffic_manager::InMemoryMap::GetWaypointInVicinity(), carla::traffic_manager::LocalizationConstants::HIGHWAY_SPEED, idle_time, carla::traffic_manager::LocalizationConstants::INTER_LANE_CHANGE_DISTANCE, IsVehicleStuck(), carla::traffic_manager::LocalizationToCollisionData::junction_look_ahead_waypoint, carla::traffic_manager::LocalizationToTrafficLightData::junction_look_ahead_waypoint, last_lane_change_location, carla::geom::Vector3D::Length(), local_map, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), maximum_idle_time, carla::traffic_manager::LocalizationConstants::MINIMUM_HORIZON_LENGTH, carla::traffic_manager::LocalizationConstants::MINIMUM_JUNCTION_LOOK_AHEAD, carla::traffic_manager::LocalizationToCollisionData::overlapping_actors, parameters, planner_frame_a, planner_frame_b, planner_frame_selector, PopWaypoint(), PushWaypoint(), carla::traffic_manager::LocalizationToCollisionData::safe_point_after_junction, ScanUnregisteredVehicles(), carla::traffic_manager::LocalizationConstants::TARGET_WAYPOINT_HORIZON_LENGTH, carla::traffic_manager::LocalizationConstants::TARGET_WAYPOINT_TIME_HORIZON, track_traffic, traffic_light_frame_a, traffic_light_frame_b, traffic_light_frame_selector, TryDestroyVehicle(), unregistered_actors, carla::traffic_manager::TrackTraffic::UpdateGridPosition(), UpdateIdleTime(), vehicle_id_to_index, and carla::traffic_manager::LocalizationConstants::WAYPOINT_TIME_HORIZON.
SimpleWaypointPtr carla::traffic_manager::LocalizationStage::AssignLaneChange (Actor vehicle, const cg::Location & vehicle_location, bool force, bool direction) private
Method to determine lane change and obtain target lane waypoint.
Definition at line 505 of file LocalizationStage.cpp.
References approached, buffer_list, carla::geom::Math::Clamp(), carla::geom::Math::DistanceSquared(), carla::geom::Math::Dot(), carla::traffic_manager::TrackTraffic::GetOverlappingVehicles(), carla::traffic_manager::TrackTraffic::GetPassingVehicles(), carla::traffic_manager::LocalizationConstants::MAXIMUM_LANE_OBSTACLE_CURVATURE, carla::traffic_manager::LocalizationConstants::MAXIMUM_LANE_OBSTACLE_DISTANCE, carla::traffic_manager::LocalizationConstants::MINIMUM_LANE_CHANGE_DISTANCE, track_traffic, and vehicle_id_to_index.
Referenced by Action().
void carla::traffic_manager::LocalizationStage::CleanActor (const ActorId actor_id) private
Definition at line 763 of file LocalizationStage.cpp.
References buffer_list, carla::traffic_manager::TrackTraffic::DeleteActor(), idle_time, carla::traffic_manager::TrackTraffic::RemovePassingVehicle(), and track_traffic.
Referenced by TryDestroyVehicle().
void carla::traffic_manager::LocalizationStage::DataReceiver () override virtual
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
Implements carla::traffic_manager::PipelineStage.
Definition at line 320 of file LocalizationStage.cpp.
References actor_list, collision_frame_a, collision_frame_b, carla::traffic_manager::TrackTraffic::DeleteActor(), episode_proxy_ls, carla::traffic_manager::AtomicActorSet::GetList(), carla::traffic_manager::AtomicActorSet::GetState(), last_lane_change_location, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::StringUtil::Match(), number_of_vehicles, planner_frame_a, planner_frame_b, registered_actors, registered_actors_state, carla::traffic_manager::AtomicActorSet::Remove(), track_traffic, traffic_light_frame_a, traffic_light_frame_b, and vehicle_id_to_index.
void carla::traffic_manager::LocalizationStage::DataSender () override virtual
Implement this method with logic to gather results from the action threads and send to next stage(s).
Implements carla::traffic_manager::PipelineStage.
Definition at line 395 of file LocalizationStage.cpp.
References collision_frame_a, collision_frame_b, collision_frame_selector, collision_messenger, planner_frame_a, planner_frame_b, planner_frame_selector, planner_messenger, traffic_light_frame_a, traffic_light_frame_b, traffic_light_frame_selector, and traffic_light_messenger.
void carla::traffic_manager::LocalizationStage::DrawBuffer (Buffer & buffer) private
A simple method used to draw waypoint buffer ahead of a vehicle.
Definition at line 408 of file LocalizationStage.cpp.
References debug_helper, and carla::client::DebugHelper::DrawPoint().
SimpleWaypointPtr carla::traffic_manager::LocalizationStage::GetSafeLocationAfterJunction (const Vehicle & vehicle, Buffer & waypoint_buffer) private
Definition at line 644 of file LocalizationStage.cpp.
References PushWaypoint().
Referenced by Action().
bool carla::traffic_manager::LocalizationStage::IsVehicleStuck (const Actor & actor) private
Definition at line 749 of file LocalizationStage.cpp.
References carla::traffic_manager::LocalizationConstants::BLOCKED_TIME_THRESHOLD, current_timestamp, carla::client::Timestamp::elapsed_seconds, and idle_time.
Referenced by Action().
void carla::traffic_manager::LocalizationStage::PopWaypoint (Buffer & buffer, ActorId actor_id) private
Definition at line 426 of file LocalizationStage.cpp.
References carla::traffic_manager::TrackTraffic::RemovePassingVehicle(), and track_traffic.
Referenced by Action().
void carla::traffic_manager::LocalizationStage::PushWaypoint (Buffer & buffer, ActorId actor_id, SimpleWaypointPtr & waypoint) private
Methods to modify waypoint buffer and track traffic.
Definition at line 419 of file LocalizationStage.cpp.
References track_traffic, and carla::traffic_manager::TrackTraffic::UpdatePassingVehicle().
Referenced by Action(), and GetSafeLocationAfterJunction().
void carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles () private
Method to scan for unregistered actors and update their grid positioning.
Get all actors of the world
Filter based on wildcard_pattern
Definition at line 435 of file LocalizationStage.cpp.
References carla::traffic_manager::AtomicActorSet::Contains(), carla::traffic_manager::TrackTraffic::DeleteActor(), episode_proxy_ls, carla::traffic_manager::InMemoryMap::GetPedWaypoint(), carla::traffic_manager::InMemoryMap::GetWaypoint(), carla::traffic_manager::InMemoryMap::GetWaypointInVicinity(), local_map, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::StringUtil::Match(), registered_actors, track_traffic, unregistered_actors, carla::traffic_manager::LocalizationConstants::UNREGISTERED_ACTORS_SCAN_INTERVAL, unregistered_scan_duration, carla::traffic_manager::TrackTraffic::UpdateUnregisteredGridPosition(), and vehicle_id_to_index.
Referenced by Action().
bool carla::traffic_manager::LocalizationStage::TryDestroyVehicle (const Actor & actor) private
Definition at line 773 of file LocalizationStage.cpp.
References CleanActor(), current_timestamp, carla::traffic_manager::LocalizationConstants::DELTA_TIME_BETWEEN_DESTRUCTIONS, carla::traffic_manager::AtomicActorSet::Destroy(), elapsed_last_actor_destruction, carla::client::Timestamp::elapsed_seconds, and registered_actors.
Referenced by Action().
void carla::traffic_manager::LocalizationStage::UpdateIdleTime (const Actor & actor) private
Methods for idle vehicle elimination.
Definition at line 733 of file LocalizationStage.cpp.
References current_timestamp, carla::client::Timestamp::elapsed_seconds, carla::rpc::Green, idle_time, maximum_idle_time, and carla::traffic_manager::LocalizationConstants::STOPPED_VELOCITY_THRESHOLD.
Referenced by Action().
Member Data Documentation
std::vector<Actor> carla::traffic_manager::LocalizationStage::actor_list private
List of actors registered with the traffic manager in current update cycle.
Definition at line 84 of file LocalizationStage.h.
Referenced by Action(), and DataReceiver().
std::map<carla::ActorId, bool> carla::traffic_manager::LocalizationStage::approached private
Used to only calculate the extended buffer once at junctions.
Definition at line 103 of file LocalizationStage.h.
Referenced by Action(), and AssignLaneChange().
std::shared_ptr<BufferList> carla::traffic_manager::LocalizationStage::buffer_list private
Structures to hold waypoint buffers for all vehicles.
These are shared with the collisions stage.
Definition at line 97 of file LocalizationStage.h.
Referenced by Action(), AssignLaneChange(), CleanActor(), and LocalizationStage().
std::shared_ptr<LocalizationToCollisionFrame> carla::traffic_manager::LocalizationStage::collision_frame_a private
Output data frames to be shared with the collision stage.
Definition at line 69 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<LocalizationToCollisionFrame> carla::traffic_manager::LocalizationStage::collision_frame_b private
Definition at line 70 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
bool carla::traffic_manager::LocalizationStage::collision_frame_selector private
Definition at line 63 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
std::shared_ptr<LocalizationToCollisionMessenger> carla::traffic_manager::LocalizationStage::collision_messenger private
Pointer to messenger to collision stage.
Definition at line 77 of file LocalizationStage.h.
Referenced by DataSender().
cc::Timestamp carla::traffic_manager::LocalizationStage::current_timestamp private
Variable to hold current timestamp from the world snapshot.
Definition at line 113 of file LocalizationStage.h.
Referenced by Action(), IsVehicleStuck(), TryDestroyVehicle(), and UpdateIdleTime().
cc::DebugHelper& carla::traffic_manager::LocalizationStage::debug_helper private
Reference to Carla's debug helper object.
Definition at line 92 of file LocalizationStage.h.
Referenced by DrawBuffer().
double carla::traffic_manager::LocalizationStage::elapsed_last_actor_destruction = 0.0 private
Simulated seconds since the beginning of the current episode when the last actor was destroyed.
Definition at line 115 of file LocalizationStage.h.
Referenced by TryDestroyVehicle().
carla::client::detail::EpisodeProxy carla::traffic_manager::LocalizationStage::episode_proxy_ls private
Reference to carla client connection object.
Definition at line 94 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and ScanUnregisteredVehicles().
std::map<carla::ActorId, SimpleWaypointPtr> carla::traffic_manager::LocalizationStage::final_safe_points private
Point used to know if the junction has free space after its end, mapped to their respective actor id.
Definition at line 105 of file LocalizationStage.h.
Referenced by Action().
std::unordered_map<ActorId, double> carla::traffic_manager::LocalizationStage::idle_time private
Map of all vehicles' idle time.
Definition at line 109 of file LocalizationStage.h.
Referenced by Action(), CleanActor(), IsVehicleStuck(), and UpdateIdleTime().
std::unordered_map<ActorId, cg::Location> carla::traffic_manager::LocalizationStage::last_lane_change_location private
Map to keep track of last lane change location.
Definition at line 124 of file LocalizationStage.h.
Referenced by Action(), and DataReceiver().
InMemoryMap& carla::traffic_manager::LocalizationStage::local_map private
Reference to local map-cache object.
Definition at line 88 of file LocalizationStage.h.
Referenced by Action(), and ScanUnregisteredVehicles().
std::pair<Actor, double> carla::traffic_manager::LocalizationStage::maximum_idle_time private
Structure to hold the actor with the maximum idle time at each iteration.
Definition at line 111 of file LocalizationStage.h.
Referenced by Action(), LocalizationStage(), and UpdateIdleTime().
uint64_t carla::traffic_manager::LocalizationStage::number_of_vehicles private
Number of vehicles currently registered with the traffic manager.
Definition at line 101 of file LocalizationStage.h.
Referenced by DataReceiver(), and LocalizationStage().
Parameters& carla::traffic_manager::LocalizationStage::parameters private
Runtime parameterization object.
Definition at line 90 of file LocalizationStage.h.
Referenced by Action().
std::shared_ptr<LocalizationToPlannerFrame> carla::traffic_manager::LocalizationStage::planner_frame_a private
Output data frames to be shared with the motion planner stage.
Definition at line 66 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<LocalizationToPlannerFrame> carla::traffic_manager::LocalizationStage::planner_frame_b private
Definition at line 67 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
bool carla::traffic_manager::LocalizationStage::planner_frame_selector private
Section keys to switch between the output data frames.
Definition at line 62 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
std::shared_ptr<LocalizationToPlannerMessenger> carla::traffic_manager::LocalizationStage::planner_messenger private
Pointer to messenger to motion planner stage.
Definition at line 75 of file LocalizationStage.h.
Referenced by DataSender().
AtomicActorSet& carla::traffic_manager::LocalizationStage::registered_actors private
Reference to set of all actors registered with the traffic manager.
Definition at line 81 of file LocalizationStage.h.
Referenced by DataReceiver(), ScanUnregisteredVehicles(), and TryDestroyVehicle().
int carla::traffic_manager::LocalizationStage::registered_actors_state private
State counter to track changes in registered actors.
Definition at line 86 of file LocalizationStage.h.
Referenced by DataReceiver(), and LocalizationStage().
SnippetProfiler carla::traffic_manager::LocalizationStage::snippet_profiler private
Code snippet execution time profiler.
Definition at line 122 of file LocalizationStage.h.
TrackTraffic carla::traffic_manager::LocalizationStage::track_traffic private
Object for tracking paths of the traffic vehicles.
Definition at line 107 of file LocalizationStage.h.
Referenced by Action(), AssignLaneChange(), CleanActor(), DataReceiver(), PopWaypoint(), PushWaypoint(), and ScanUnregisteredVehicles().
std::shared_ptr<LocalizationToTrafficLightFrame> carla::traffic_manager::LocalizationStage::traffic_light_frame_a private
Output data frames to be shared with the traffic light stage.
Definition at line 72 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<LocalizationToTrafficLightFrame> carla::traffic_manager::LocalizationStage::traffic_light_frame_b private
Definition at line 73 of file LocalizationStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
bool carla::traffic_manager::LocalizationStage::traffic_light_frame_selector private
Definition at line 64 of file LocalizationStage.h.
Referenced by Action(), DataSender(), and LocalizationStage().
std::shared_ptr<LocalizationToTrafficLightMessenger> carla::traffic_manager::LocalizationStage::traffic_light_messenger private
Pointer to messenger to traffic light stage.
Definition at line 79 of file LocalizationStage.h.
Referenced by DataSender().
std::unordered_map<ActorId, Actor> carla::traffic_manager::LocalizationStage::unregistered_actors private
A structure used to keep track of actors spawned outside of traffic manager.
Definition at line 120 of file LocalizationStage.h.
Referenced by Action(), and ScanUnregisteredVehicles().
uint64_t carla::traffic_manager::LocalizationStage::unregistered_scan_duration = 0 private
Counter to track unregistered actors' scan interval.
Definition at line 117 of file LocalizationStage.h.
Referenced by ScanUnregisteredVehicles().
std::unordered_map<ActorId, uint64_t> carla::traffic_manager::LocalizationStage::vehicle_id_to_index private
Map connecting actor ids to indices of data arrays.
Definition at line 99 of file LocalizationStage.h.
Referenced by Action(), AssignLaneChange(), DataReceiver(), and ScanUnregisteredVehicles().
The documentation for this class was generated from the following files:
LocalizationStage.h
LocalizationStage.cpp