CARLA: carla::multigpu::Router Class Reference
carla::multigpu::Router Class Reference
#include <router.h>
Public Member Functions
void AsyncRun (size_t worker_threads)
PrimaryCommands & GetCommander ()
boost::asio::ip::tcp::endpoint GetLocalEndpoint () const
bool HasClientsConnected ()
Router (void)
Router (uint16_t port)
void SetCallbacks ()
void SetNewConnectionCallback (std::function< void(void)>)
void Stop ()
void Write (MultiGPUCommand id, Buffer &&buffer)
std::future< SessionInfo > WriteToNext (MultiGPUCommand id, Buffer &&buffer)
~Router ()
Private Member Functions
void ClearSessions ()
void ConnectSession (std::shared_ptr< Primary > session)
void DisconnectSession (std::shared_ptr< Primary > session)
Private Attributes
std::function< void(void)> _callback
PrimaryCommands _commander
boost::asio::ip::tcp::endpoint _endpoint
std::shared_ptr< Listener > _listener
std::mutex _mutex
uint32_t _next
ThreadPool _pool
std::unordered_map< Primary *, std::shared_ptr< std::promise< SessionInfo > > > _promises
std::vector< std::shared_ptr< Primary > > _sessions
Detailed Description
Definition at line 35 of file router.h.
Constructor & Destructor Documentation
Router() [1/2]
carla::multigpu::Router::Router (void)
Definition at line 15 of file router.cpp.
Router() [2/2]
carla::multigpu::Router::Router (uint16_t port) explicit
Definition at line 29 of file router.cpp.
References _endpoint, _listener, _pool, and carla::ThreadPool::io_context().
~Router()
carla::multigpu::Router::~Router ()
Definition at line 18 of file router.cpp.
References Stop().
Member Function Documentation
AsyncRun()
void carla::multigpu::Router::AsyncRun (size_t worker_threads)
Definition at line 78 of file router.cpp.
References _pool, and carla::ThreadPool::AsyncRun().
ClearSessions()
void carla::multigpu::Router::ClearSessions () private
Definition at line 106 of file router.cpp.
References _mutex, _sessions, and carla::log_info().
Referenced by Stop().
ConnectSession()
void carla::multigpu::Router::ConnectSession (std::shared_ptr< Primary > session) private
Definition at line 86 of file router.cpp.
References _callback, _mutex, _sessions, DEBUG_ASSERT, and carla::log_info().
DisconnectSession()
void carla::multigpu::Router::DisconnectSession (std::shared_ptr< Primary > session) private
Definition at line 96 of file router.cpp.
References _mutex, _sessions, DEBUG_ASSERT, and carla::log_info().
GetCommander()
PrimaryCommands& carla::multigpu::Router::GetCommander () inline
Definition at line 57 of file router.h.
References carla::multigpu::SessionInfo::session.
GetLocalEndpoint()
boost::asio::ip::tcp::endpoint carla::multigpu::Router::GetLocalEndpoint () const
Definition at line 82 of file router.cpp.
References _endpoint.
HasClientsConnected()
bool carla::multigpu::Router::HasClientsConnected () inline
Definition at line 53 of file router.h.
SetCallbacks()
void carla::multigpu::Router::SetCallbacks ()
Definition at line 36 of file router.cpp.
References _commander, _endpoint, _listener, _promises, carla::log_info(), and carla::multigpu::PrimaryCommands::set_router().
SetNewConnectionCallback()
void carla::multigpu::Router::SetNewConnectionCallback (std::function< void(void)> func)
Definition at line 73 of file router.cpp.
References _callback.
Stop()
void carla::multigpu::Router::Stop (void)
Definition at line 22 of file router.cpp.
References _listener, _pool, ClearSessions(), and carla::ThreadPool::Stop().
Referenced by ~Router().
Write()
void carla::multigpu::Router::Write (MultiGPUCommand id, Buffer && buffer)
Definition at line 112 of file router.cpp.
References _mutex, _sessions, carla::multigpu::CommandHeader::id, carla::multigpu::Primary::MakeMessage(), and carla::multigpu::CommandHeader::size.
WriteToNext()
std::future< SessionInfo > carla::multigpu::Router::WriteToNext (MultiGPUCommand id, Buffer && buffer)
Definition at line 130 of file router.cpp.
References _mutex, _next, _promises, _sessions, carla::multigpu::CommandHeader::id, carla::multigpu::Primary::MakeMessage(), and carla::multigpu::CommandHeader::size.
Member Data Documentation
_callback
std::function<void(void)> carla::multigpu::Router::_callback private
Definition at line 75 of file router.h.
Referenced by ConnectSession(), and SetNewConnectionCallback().
_commander
PrimaryCommands carla::multigpu::Router::_commander private
Definition at line 74 of file router.h.
Referenced by SetCallbacks().
_endpoint
boost::asio::ip::tcp::endpoint carla::multigpu::Router::_endpoint private
Definition at line 69 of file router.h.
Referenced by GetLocalEndpoint(), Router(), and SetCallbacks().
_listener
std::shared_ptr<Listener> carla::multigpu::Router::_listener private
Definition at line 71 of file router.h.
Referenced by Router(), SetCallbacks(), and Stop().
_mutex
std::mutex carla::multigpu::Router::_mutex private
Definition at line 67 of file router.h.
Referenced by ClearSessions(), ConnectSession(), DisconnectSession(), Write(), and WriteToNext().
_next
uint32_t carla::multigpu::Router::_next private
Definition at line 72 of file router.h.
Referenced by WriteToNext().
_pool
ThreadPool carla::multigpu::Router::_pool private
Definition at line 68 of file router.h.
Referenced by AsyncRun(), Router(), and Stop().
_promises
std::unordered_map<Primary *, std::shared_ptr<std::promise<SessionInfo> > > carla::multigpu::Router::_promises private
Definition at line 73 of file router.h.
Referenced by SetCallbacks(), and WriteToNext().
_sessions
std::vector<std::shared_ptr<Primary> > carla::multigpu::Router::_sessions private
Definition at line 70 of file router.h.
Referenced by ClearSessions(), ConnectSession(), DisconnectSession(), Write(), and WriteToNext().
The documentation for this class was generated from the following files:
router.h
router.cpp