CARLA: carla::sensor::s11n::LidarSerializer Class Reference
carla::sensor::s11n::LidarSerializer Class Reference
Serializes the data generated by Lidar sensors.
#include <LidarSerializer.h>
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static LidarHeaderView DeserializeHeader (const RawData &data)
static size_t GetHeaderOffset (const RawData &data)
template<typename Sensor >
static Buffer Serialize (const Sensor &sensor, const LidarMeasurement &measurement, Buffer &&output)
Detailed Description
Serializes the data generated by Lidar sensors.
Definition at line 59 of file LidarSerializer.h.
Member Function Documentation
SharedPtr< SensorData > carla::sensor::s11n::LidarSerializer::Deserialize (RawData && data) static
Definition at line 15 of file LidarSerializer.cpp.
static LidarHeaderView carla::sensor::s11n::LidarSerializer::DeserializeHeader (const RawData & data) inline static
Definition at line 62 of file LidarSerializer.h.
References carla::sensor::RawData::begin().
Referenced by carla::sensor::data::LidarMeasurement::GetHeader().
static size_t carla::sensor::s11n::LidarSerializer::GetHeaderOffset (const RawData & data) inline static
Definition at line 66 of file LidarSerializer.h.
References PropAttributes::SIZE.
Referenced by carla::sensor::data::LidarMeasurement::LidarMeasurement().
template<typename Sensor > Buffer carla::sensor::s11n::LidarSerializer::Serialize (const Sensor & sensor, const LidarMeasurement & measurement, Buffer && output) inline static
Definition at line 85 of file LidarSerializer.h.
References carla::sensor::s11n::LidarMeasurement::_header, carla::sensor::s11n::LidarMeasurement::_points, and carla::Buffer::copy_from().
The documentation for this class was generated from the following files:
LidarSerializer.h
LidarSerializer.cpp