CARLA: FHttpDownloader Class Reference
FHttpDownloader Class Reference
#include <CustomFileDownloader.h>
Public Member Functions
FHttpDownloader (const FString &InVerb, const FString &InUrl, const FString &InFilename, FDownloadComplete &Delegate)
void RequestComplete (FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded)
Delegate called when the request completes.
void Run (void)
Private Attributes
FDownloadComplete DelegateToCall
FString Filename
FString Url
FString Verb
Detailed Description
Definition at line 36 of file CustomFileDownloader.h.
Constructor & Destructor Documentation
FHttpDownloader()
FHttpDownloader::FHttpDownloader (const FString & InVerb, const FString & InUrl, const FString & InFilename, FDownloadComplete & Delegate)
Parameters
Verb - verb to use for request (GET,POST,DELETE,etc)
Url - url address to connect to
Definition at line 62 of file CustomFileDownloader.cpp.
Member Function Documentation
RequestComplete()
void FHttpDownloader::RequestComplete (FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded)
Delegate called when the request completes.
Parameters
HttpRequest - object that started/processed the request
HttpResponse - optional response object if request completed
bSucceeded - true if Url connection was made and response was received
Definition at line 77 of file CustomFileDownloader.cpp.
References DelegateToCall, Filename, and carla::client::detail::Get().
Referenced by Run().
Run()
void FHttpDownloader::Run (void)
Definition at line 67 of file CustomFileDownloader.cpp.
References carla::client::detail::Get(), RequestComplete(), Url, and Verb.
Referenced by UCustomFileDownloader::StartDownload().
Member Data Documentation
DelegateToCall
FDownloadComplete FHttpDownloader::DelegateToCall private
Definition at line 62 of file CustomFileDownloader.h.
Referenced by RequestComplete().
Filename
FString FHttpDownloader::Filename private
Definition at line 61 of file CustomFileDownloader.h.
Referenced by RequestComplete().
Url
FString FHttpDownloader::Url private
Definition at line 60 of file CustomFileDownloader.h.
Referenced by Run().
Verb
FString FHttpDownloader::Verb private
Definition at line 59 of file CustomFileDownloader.h.
Referenced by Run().
The documentation for this class was generated from the following files:
CustomFileDownloader.h
CustomFileDownloader.cpp