CARLA: ACollisionSensor Class Reference
ACollisionSensor Class Reference
A sensor to register collisions.
#include <CollisionSensor.h>
Public Member Functions
ACollisionSensor (const FObjectInitializer &ObjectInitializer)
void SetOwner (AActor *NewOwner) override
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
virtual void Set (const FActorDescription &Description)
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
Static Public Member Functions
static FActorDefinition GetSensorDefinition ()
Private Member Functions
void OnCollisionEvent (AActor *Actor, AActor *OtherActor, FVector NormalImpulse, const FHitResult &Hit)
Additional Inherited Members
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
const UCarlaEpisode & GetEpisode () const
void PostActorCreated () override
Protected Attributes inherited from ASensor
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Detailed Description
A sensor to register collisions.
Definition at line 19 of file CollisionSensor.h.
Constructor & Destructor Documentation
ACollisionSensor::ACollisionSensor (const FObjectInitializer & ObjectInitializer)
Definition at line 16 of file CollisionSensor.cpp.
Member Function Documentation
FActorDefinition ACollisionSensor::GetSensorDefinition () static
Definition at line 22 of file CollisionSensor.cpp.
References UActorBlueprintFunctionLibrary::MakeGenericSensorDefinition().
void ACollisionSensor::OnCollisionEvent (AActor * Actor, AActor * OtherActor, FVector NormalImpulse, const FHitResult & Hit) private
Definition at line 41 of file CollisionSensor.cpp.
References ACarlaRecorder::AddCollision(), ASensor::Episode, UCarlaEpisode::FindOrFakeActor(), ASensor::GetDataStream(), ASensor::GetEpisode(), UCarlaEpisode::GetRecorder(), ACarlaRecorder::IsEnabled(), FAsyncDataStreamTmpl< T >::Send(), and UCarlaEpisode::SerializeActor().
Referenced by SetOwner().
void ACollisionSensor::SetOwner (AActor * NewOwner) override
Todo:
Deregister previous owner if there was one.
Definition at line 29 of file CollisionSensor.cpp.
References OnCollisionEvent().
The documentation for this class was generated from the following files:
CollisionSensor.h
CollisionSensor.cpp