CARLA: CarlaEngine.cpp File Reference
CarlaEngine.cpp File Reference
#include "Carla.h"
#include "Carla/Game/CarlaEngine.h"
#include "Carla/Game/CarlaEpisode.h"
#include "Carla/Game/CarlaStaticDelegates.h"
#include "Carla/Lights/CarlaLightSubsystem.h"
#include "Carla/Recorder/CarlaRecorder.h"
#include "Carla/Settings/CarlaSettings.h"
#include "Carla/Settings/EpisodeSettings.h"
#include "Runtime/Core/Public/Misc/App.h"
#include "PhysicsEngine/PhysicsSettings.h"
#include <thread>
Functions
static TOptional< double > FCarlaEngine_GetFixedDeltaSeconds ()
static uint32 FCarlaEngine_GetNumberOfThreadsForRPCServer ()
static void FCarlaEngine_SetFixedDeltaSeconds (TOptional< double > FixedDeltaSeconds)
Function Documentation
FCarlaEngine_GetFixedDeltaSeconds()
static TOptional<double> FCarlaEngine_GetFixedDeltaSeconds () static
Definition at line 34 of file CarlaEngine.cpp.
Referenced by FCarlaEngine::NotifyBeginEpisode().
FCarlaEngine_GetNumberOfThreadsForRPCServer()
static uint32 FCarlaEngine_GetNumberOfThreadsForRPCServer () static
Definition at line 29 of file CarlaEngine.cpp.
Referenced by FCarlaEngine::NotifyInitGame().
FCarlaEngine_SetFixedDeltaSeconds()
static void FCarlaEngine_SetFixedDeltaSeconds (TOptional< double > FixedDeltaSeconds) static
Definition at line 39 of file CarlaEngine.cpp.
Referenced by FCarlaEngine::OnEpisodeSettingsChanged().