CARLA: UCarlaGameInstance Class Reference
UCarlaGameInstance Class Reference
The game instance contains elements that must be kept alive in between levels.
#include <CarlaGameInstance.h>
Public Member Functions
UCarlaEpisode * GetCarlaEpisode ()
UCarlaSettings & GetCarlaSettings ()
const UCarlaSettings & GetCarlaSettings () const
UCarlaSettings * GetCARLASettings ()
int32 GetCurrentMapLayer () const
const carla::rpc::OpendriveGenerationParameters & GetOpendriveGenerationParameters () const
const FCarlaServer & GetServer () const
void NotifyBeginEpisode (UCarlaEpisode &Episode)
void NotifyEndEpisode ()
void NotifyInitGame ()
void SetMapLayer (int32 MapLayer)
void SetOpendriveGenerationParameters (const carla::rpc::OpendriveGenerationParameters &Parameters)
UCarlaGameInstance ()
~UCarlaGameInstance ()
Private Attributes
FString _MapPath
FCarlaEngine CarlaEngine
UCarlaSettings * CarlaSettings = nullptr
int32 CurrentMapLayer = static_cast<int32>(carla::rpc::MapLayer::All)
carla::rpc::OpendriveGenerationParameters GenerationParameters
ACarlaRecorder * Recorder = nullptr
Detailed Description
The game instance contains elements that must be kept alive in between levels.
It is instantiate once per game.
Definition at line 27 of file CarlaGameInstance.h.
Constructor & Destructor Documentation
UCarlaGameInstance()
UCarlaGameInstance::UCarlaGameInstance ()
Definition at line 12 of file CarlaGameInstance.cpp.
References CarlaEngine, CarlaSettings, UCarlaSettings::LoadSettings(), UCarlaSettings::LogSettings(), Recorder, FCarlaEngine::SetRecorder(), and ~UCarlaGameInstance().
~UCarlaGameInstance()
UCarlaGameInstance::~UCarlaGameInstance () default
Referenced by UCarlaGameInstance().
Member Function Documentation
GetCarlaEpisode()
UCarlaEpisode* UCarlaGameInstance::GetCarlaEpisode () inline
Definition at line 57 of file CarlaGameInstance.h.
Referenced by ASensorFactory::SpawnActor(), and ATriggerFactory::SpawnActor().
GetCarlaSettings() [1/2]
UCarlaSettings& UCarlaGameInstance::GetCarlaSettings () inline
Definition at line 37 of file CarlaGameInstance.h.
GetCarlaSettings() [2/2]
const UCarlaSettings& UCarlaGameInstance::GetCarlaSettings () const inline
Definition at line 43 of file CarlaGameInstance.h.
GetCARLASettings()
UCarlaSettings* UCarlaGameInstance::GetCARLASettings () inline
Definition at line 51 of file CarlaGameInstance.h.
GetCurrentMapLayer()
int32 UCarlaGameInstance::GetCurrentMapLayer () const inline
Definition at line 101 of file CarlaGameInstance.h.
References UCarlaSettings::UPROPERTY().
Referenced by ACarlaGameModeBase::BeginPlay().
GetOpendriveGenerationParameters()
const carla::rpc::OpendriveGenerationParameters& UCarlaGameInstance::GetOpendriveGenerationParameters () const inline
Definition at line 89 of file CarlaGameInstance.h.
Referenced by AOpenDriveGenerator::GenerateRoadMesh().
GetServer()
const FCarlaServer& UCarlaGameInstance::GetServer () const inline
Definition at line 77 of file CarlaGameInstance.h.
Referenced by ASensorFactory::SpawnActor().
NotifyBeginEpisode()
void UCarlaGameInstance::NotifyBeginEpisode (UCarlaEpisode & Episode) inline
Definition at line 67 of file CarlaGameInstance.h.
Referenced by ACarlaGameModeBase::BeginPlay().
NotifyEndEpisode()
void UCarlaGameInstance::NotifyEndEpisode () inline
Definition at line 72 of file CarlaGameInstance.h.
Referenced by ACarlaGameModeBase::EndPlay().
NotifyInitGame()
void UCarlaGameInstance::NotifyInitGame () inline
Definition at line 62 of file CarlaGameInstance.h.
Referenced by ACarlaGameModeBase::InitGame().
SetMapLayer()
void UCarlaGameInstance::SetMapLayer (int32 MapLayer) inline
Definition at line 95 of file CarlaGameInstance.h.
Referenced by FCarlaServer::FPimpl::BindActions().
SetOpendriveGenerationParameters()
void UCarlaGameInstance::SetOpendriveGenerationParameters (const carla::rpc::OpendriveGenerationParameters & Parameters) inline
Definition at line 82 of file CarlaGameInstance.h.
Referenced by UCarlaEpisode::LoadNewOpendriveEpisode().
Member Data Documentation
_MapPath
FString UCarlaGameInstance::_MapPath private
Definition at line 122 of file CarlaGameInstance.h.
CarlaEngine
FCarlaEngine UCarlaGameInstance::CarlaEngine private
Definition at line 111 of file CarlaGameInstance.h.
Referenced by UCarlaGameInstance().
CarlaSettings
UCarlaSettings* UCarlaGameInstance::CarlaSettings = nullptr private
Definition at line 109 of file CarlaGameInstance.h.
Referenced by UCarlaGameInstance().
CurrentMapLayer
int32 UCarlaGameInstance::CurrentMapLayer = static_cast<int32>(carla::rpc::MapLayer::All) private
Definition at line 119 of file CarlaGameInstance.h.
GenerationParameters
carla::rpc::OpendriveGenerationParameters UCarlaGameInstance::GenerationParameters private
Definition at line 116 of file CarlaGameInstance.h.
Recorder
ACarlaRecorder* UCarlaGameInstance::Recorder = nullptr private
Definition at line 114 of file CarlaGameInstance.h.
Referenced by UCarlaGameInstance().
The documentation for this class was generated from the following files:
CarlaGameInstance.h
CarlaGameInstance.cpp