CARLA: carla::sensor::s11n::LidarMeasurement Class Reference
carla::sensor::s11n::LidarMeasurement Class Reference
Helper class to store and serialize the data generated by a Lidar.
#include <LidarMeasurement.h>
Public Member Functions
uint32_t GetChannelCount () const
float GetHorizontalAngle () const
LidarMeasurement (uint32_t ChannelCount=0u)
LidarMeasurement & operator= (LidarMeasurement &&)=default
void Reset (uint32_t total_point_count)
void SetHorizontalAngle (float angle)
void WritePoint (uint32_t channel, rpc::Location point)
Private Types
enum Index : size_t { HorizontalAngle, ChannelCount, SIZE }
Private Attributes
std::vector< uint32_t > _header
std::vector< float > _points
Friends
class LidarHeaderView
class LidarSerializer
Detailed Description
Helper class to store and serialize the data generated by a Lidar.
The header of a Lidar measurement consists of an array of uint32_t's in the following layout
{ Horizontal angle (float), Channel count, Point count of channel 0, ... Point count of channel n, }
The points are stored in an array of floats
{ X0, Y0, Z0, ... Xn, Yn, Zn, }
Warning
WritePoint should be called sequentially in the order in which the points are going to be stored, i.e., starting at channel zero and increasing steadily.
Definition at line 42 of file s11n/LidarMeasurement.h.
Member Enumeration Documentation
enum carla::sensor::s11n::LidarMeasurement::Index : size_t private
Enumerator
HorizontalAngle
ChannelCount
SIZE
Definition at line 48 of file s11n/LidarMeasurement.h.
Constructor & Destructor Documentation
carla::sensor::s11n::LidarMeasurement::LidarMeasurement (uint32_t ChannelCount = 0u) inline explicit
Definition at line 56 of file s11n/LidarMeasurement.h.
References _header, ChannelCount, and operator=().
Member Function Documentation
uint32_t carla::sensor::s11n::LidarMeasurement::GetChannelCount () const inline
Definition at line 71 of file s11n/LidarMeasurement.h.
References _header.
Referenced by Reset(), and WritePoint().
float carla::sensor::s11n::LidarMeasurement::GetHorizontalAngle () const inline
Definition at line 63 of file s11n/LidarMeasurement.h.
References _header.
Referenced by ARayCastLidar::ReadPoints().
LidarMeasurement& carla::sensor::s11n::LidarMeasurement::operator= (LidarMeasurement &&) default
Referenced by LidarMeasurement().
void carla::sensor::s11n::LidarMeasurement::Reset (uint32_t total_point_count) inline
Definition at line 75 of file s11n/LidarMeasurement.h.
References _header, _points, GetChannelCount(), and PropAttributes::SIZE.
Referenced by ARayCastLidar::ReadPoints().
void carla::sensor::s11n::LidarMeasurement::SetHorizontalAngle (float angle) inline
Definition at line 67 of file s11n/LidarMeasurement.h.
References _header.
Referenced by ARayCastLidar::ReadPoints().
void carla::sensor::s11n::LidarMeasurement::WritePoint (uint32_t channel, rpc::Location point) inline
Definition at line 81 of file s11n/LidarMeasurement.h.
References _header, _points, DEBUG_ASSERT, GetChannelCount(), PropAttributes::SIZE, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by ARayCastLidar::ReadPoints().
Friends And Related Function Documentation
friend class LidarHeaderView friend
Definition at line 46 of file s11n/LidarMeasurement.h.
friend class LidarSerializer friend
Definition at line 43 of file s11n/LidarMeasurement.h.
Member Data Documentation
std::vector<uint32_t> carla::sensor::s11n::LidarMeasurement::_header private
Definition at line 91 of file s11n/LidarMeasurement.h.
Referenced by GetChannelCount(), GetHorizontalAngle(), LidarMeasurement(), Reset(), carla::sensor::s11n::LidarSerializer::Serialize(), SetHorizontalAngle(), and WritePoint().
std::vector<float> carla::sensor::s11n::LidarMeasurement::_points private
Definition at line 93 of file s11n/LidarMeasurement.h.
Referenced by Reset(), carla::sensor::s11n::LidarSerializer::Serialize(), and WritePoint().
The documentation for this class was generated from the following file:
s11n/LidarMeasurement.h