CARLA: UCarlaStatics Class Reference
UCarlaStatics Class Reference
#include <CarlaStatics.h>
Static Public Member Functions
static TArray< FString > GetAllMapNames ()
static UCarlaSettings * GetCarlaSettings (const UObject *WorldContextObject)
static UCarlaEpisode * GetCurrentEpisode (const UObject *WorldContextObject)
static UCarlaGameInstance * GetGameInstance (const UObject *WorldContextObject)
static ACarlaGameModeBase * GetGameMode (const UObject *WorldContextObject)
static ALargeMapManager * GetLargeMapManager (const UObject *WorldContextObject)
static ACarlaRecorder * GetRecorder (const UObject *WorldContextObject)
static CarlaReplayer * GetReplayer (const UObject *WorldContextObject)
Detailed Description
Definition at line 24 of file CarlaStatics.h.
Member Function Documentation
GetAllMapNames()
TArray< FString > UCarlaStatics::GetAllMapNames () static
Definition at line 12 of file CarlaStatics.cpp.
References carla::client::detail::Get().
Referenced by FCarlaServer::FPimpl::BindActions().
GetCarlaSettings()
UCarlaSettings * UCarlaStatics::GetCarlaSettings (const UObject * WorldContextObject) inline static
Definition at line 74 of file CarlaStatics.h.
References GetGameInstance().
Referenced by SceneCaptureSensor_local_ns::GetQualitySettings().
GetCurrentEpisode()
UCarlaEpisode * UCarlaStatics::GetCurrentEpisode (const UObject * WorldContextObject) inline static
Definition at line 68 of file CarlaStatics.h.
References GetGameInstance().
Referenced by ASensor::BeginPlay(), AGnssSensor::BeginPlay(), ALargeMapManager::CheckActiveActors(), ALargeMapManager::CheckDormantActors(), ALargeMapManager::ConvertActiveToDormantActors(), ALargeMapManager::ConvertDormantToActiveActors(), ASensor::EndPlay(), GetRecorder(), GetReplayer(), ALargeMapManager::OnActorDestroyed(), ALargeMapManager::OnActorSpawned(), ALargeMapManager::PostWorldOriginOffset(), ALargeMapManager::RegisterInitialObjects(), and ATrafficLightGroup::Tick().
GetGameInstance()
UCarlaGameInstance * UCarlaStatics::GetGameInstance (const UObject * WorldContextObject) inline static
Definition at line 63 of file CarlaStatics.h.
Referenced by FCarlaServer::FPimpl::BindActions(), AOpenDriveGenerator::GenerateRoadMesh(), GetCarlaSettings(), GetCurrentEpisode(), UCarlaEpisode::LoadNewOpendriveEpisode(), ATriggerFactory::SpawnActor(), and ASensorFactory::SpawnActor().
GetGameMode()
ACarlaGameModeBase * UCarlaStatics::GetGameMode (const UObject * WorldContextObject) inline static
Definition at line 58 of file CarlaStatics.h.
Referenced by FCarlaServer::FPimpl::BindActions(), URayTracer::CastRay(), AOpenDriveGenerator::GenerateRoadMesh(), AOpenDriveGenerator::GenerateSpawnPoints(), GetLargeMapManager(), ATrafficLightManager::GetMap(), UCarlaEpisode::GetRecommendedSpawnPoints(), UOpenDrive::GetXODR(), AOpenDriveGenerator::IsOpenDriveValid(), URayTracer::ProjectPoint(), ATrafficLightManager::RegisterLightComponentFromOpenDRIVE(), FTrafficSignData::RestoreActorData(), FTrafficLightData::RestoreActorData(), ATrafficLightManager::SpawnSignals(), and ATrafficLightManager::SpawnTrafficLights().
GetLargeMapManager()
ALargeMapManager * UCarlaStatics::GetLargeMapManager (const UObject * WorldContextObject) inline static
Definition at line 100 of file CarlaStatics.h.
References GetGameMode(), and ACarlaGameModeBase::GetLMManager().
Referenced by FCarlaServer::FPimpl::BindActions(), FCarlaActor::GetActorGlobalLocation(), FCarlaActor::GetActorGlobalTransform(), FCarlaActor::GetActorLocalLocation(), FCarlaActor::GetActorLocalTransform(), FCarlaEngine::NotifyBeginEpisode(), FCarlaEngine::OnEpisodeSettingsChanged(), FShapeVisitor::operator()(), AGnssSensor::PostPhysTick(), FSparseHighDetailMap::SaveMap(), FCarlaActor::SetActorGlobalLocation(), FCarlaActor::SetActorGlobalTransform(), FCarlaActor::SetActorLocalLocation(), FCarlaActor::SetActorLocalTransform(), UCarlaEpisode::SpawnActorWithInfo(), CarlaReplayerHelper::TryToCreateReplayerActor(), and FFrameData::TryToCreateReplayerActor().
GetRecorder()
ACarlaRecorder * UCarlaStatics::GetRecorder (const UObject * WorldContextObject) inline static
Definition at line 80 of file CarlaStatics.h.
References GetCurrentEpisode().
Referenced by ATrafficLightBase::AddTimeToRecorder(), and ACarlaWheeledVehicle::ApplyVehiclePhysicsControl().
GetReplayer()
CarlaReplayer * UCarlaStatics::GetReplayer (const UObject * WorldContextObject) inline static
Definition at line 90 of file CarlaStatics.h.
References GetCurrentEpisode().
The documentation for this class was generated from the following files:
CarlaStatics.h
CarlaStatics.cpp