CARLA: carla::opendrive::parser Namespace Reference
carla::opendrive::parser Namespace Reference
Classes
class ControllerParser
struct ElevationProfile
struct Geometry
struct GeometryArc
struct GeometryParamPoly3
class GeometryParser
struct GeometryPoly3
struct GeometrySpiral
class GeoReferenceParser
class JunctionParser
struct Lane
struct LaneOffset
class LaneParser
struct LaneSection
struct LateralCrossfall
struct LateralProfile
struct LateralShape
class ObjectParser
struct Polynomial
class ProfilesParser
struct Road
class RoadParser
struct RoadTypeSpeed
class SignalParser
class TrafficGroupParser
Typedefs
using JuncId = road::JuncId
using LaneId = road::LaneId
using RoadId = road::RoadId
Functions
static void AddValidity (road::element::RoadInfoSignal *signal_reference, pugi::xml_node parent_node, const std::string &node_name, road::MapBuilder &map_builder)
static double ParseDouble (const std::string &string_value)
static geom::GeoLocation ParseGeoReference (const std::string &geo_reference_string)
static void ParseLanes (road::RoadId road_id, double s, const pugi::xml_node &parent_node, carla::road::MapBuilder &map_builder)
static road::Lane::LaneType StringToLaneType (std::string &&str)
Typedef Documentation
using carla::opendrive::parser::JuncId = typedef road::JuncId
Definition at line 22 of file RoadParser.cpp.
using carla::opendrive::parser::LaneId = typedef road::LaneId
Definition at line 21 of file RoadParser.cpp.
typedef road::RoadId carla::opendrive::parser::RoadId
Definition at line 17 of file GeometryParser.cpp.
Function Documentation
static void carla::opendrive::parser::AddValidity (road::element::RoadInfoSignal * signal_reference, pugi::xml_node parent_node, const std::string & node_name, road::MapBuilder & map_builder) static
Definition at line 17 of file SignalParser.cpp.
References carla::road::MapBuilder::AddValidityToSignalReference(), pugi::xml_node::child(), and pugi::xml_node::next_sibling().
Referenced by carla::opendrive::parser::SignalParser::Parse().
static double carla::opendrive::parser::ParseDouble (const std::string & string_value) static
Definition at line 24 of file GeoReferenceParser.cpp.
Referenced by ParseGeoReference().
static geom::GeoLocation carla::opendrive::parser::ParseGeoReference (const std::string & geo_reference_string) static
Definition at line 28 of file GeoReferenceParser.cpp.
References carla::log_debug(), carla::log_warning(), ParseDouble(), and carla::StringUtil::Split().
Referenced by carla::opendrive::parser::GeoReferenceParser::Parse().
static void carla::opendrive::parser::ParseLanes (road::RoadId road_id, double s, const pugi::xml_node & parent_node, carla::road::MapBuilder & map_builder) static
Definition at line 17 of file LaneParser.cpp.
References pugi::xml_attribute::as_double(), pugi::xml_node::attribute(), pugi::xml_node::child(), pugi::xml_node::children(), carla::road::MapBuilder::CreateLaneAccess(), carla::road::MapBuilder::CreateLaneBorder(), carla::road::MapBuilder::CreateLaneHeight(), carla::road::MapBuilder::CreateLaneMaterial(), carla::road::MapBuilder::CreateLaneRule(), carla::road::MapBuilder::CreateLaneSpeed(), carla::road::MapBuilder::CreateLaneVisibility(), carla::road::MapBuilder::CreateLaneWidth(), carla::road::MapBuilder::CreateRoadMark(), carla::road::MapBuilder::CreateRoadMarkTypeLine(), carla::road::Lane::GetId(), carla::road::MapBuilder::GetLane(), carla::road::Lane::GetRoad(), and pugi::xml_attribute::value().
Referenced by carla::opendrive::parser::LaneParser::Parse().
static road::Lane::LaneType carla::opendrive::parser::StringToLaneType (std::string && str) static
Definition at line 66 of file RoadParser.cpp.
References carla::road::Lane::Bidirectional, carla::road::Lane::Biking, carla::road::Lane::Border, carla::road::Lane::Driving, carla::road::Lane::Entry, carla::road::Lane::Exit, carla::road::Lane::Median, carla::road::Lane::None, carla::road::Lane::OffRamp, carla::road::Lane::OnRamp, carla::road::Lane::Parking, carla::road::Lane::Rail, carla::road::Lane::Restricted, carla::road::Lane::RoadWorks, carla::road::Lane::Shoulder, carla::road::Lane::Sidewalk, carla::road::Lane::Special1, carla::road::Lane::Special2, carla::road::Lane::Special3, carla::road::Lane::Stop, carla::StringUtil::ToLower(), and carla::road::Lane::Tram.
Referenced by carla::opendrive::parser::RoadParser::Parse().