CARLA: carla::streaming::Client Class Reference
carla::streaming::Client Class Reference
A client able to subscribe to multiple streams.
#include <Client.h>
Public Member Functions
void AsyncRun (size_t worker_threads)
Client ()=default
Client (const std::string &fallback_address)
void Run ()
template<typename Functor >
void Subscribe (const Token &token, Functor &&callback)
void UnSubscribe (const Token &token)
~Client ()
Private Types
using underlying_client = low_level::Client< detail::tcp::Client >
Private Attributes
underlying_client _client
ThreadPool _service
Detailed Description
A client able to subscribe to multiple streams.
Definition at line 23 of file streaming/Client.h.
Member Typedef Documentation
using carla::streaming::Client::underlying_client = low_level::Client<detail::tcp::Client> private
Definition at line 24 of file streaming/Client.h.
Constructor & Destructor Documentation
carla::streaming::Client::Client () default
carla::streaming::Client::Client (const std::string & fallback_address) inline explicit
Definition at line 29 of file streaming/Client.h.
carla::streaming::Client::~Client () inline
Definition at line 32 of file streaming/Client.h.
References _service, and carla::ThreadPool::Stop().
Member Function Documentation
void carla::streaming::Client::AsyncRun (size_t worker_threads) inline
Definition at line 51 of file streaming/Client.h.
References _service, and carla::ThreadPool::AsyncRun().
Referenced by carla::client::detail::Client::Pimpl::Pimpl(), and TEST().
void carla::streaming::Client::Run () inline
Definition at line 47 of file streaming/Client.h.
References _service, and carla::ThreadPool::Run().
template<typename Functor > void carla::streaming::Client::Subscribe (const Token & token, Functor && callback) inline
Warning
cannot subscribe twice to the same stream (even if it's a MultiStream).
Definition at line 39 of file streaming/Client.h.
References _client, _service, carla::ThreadPool::io_context(), and carla::streaming::low_level::Client< T >::Subscribe().
Referenced by TEST().
void carla::streaming::Client::UnSubscribe (const Token & token) inline
Definition at line 43 of file streaming/Client.h.
References _client, and carla::streaming::low_level::Client< T >::UnSubscribe().
Referenced by TEST().
Member Data Documentation
underlying_client carla::streaming::Client::_client private
Definition at line 61 of file streaming/Client.h.
Referenced by Subscribe(), and UnSubscribe().
ThreadPool carla::streaming::Client::_service private
Definition at line 59 of file streaming/Client.h.
Referenced by AsyncRun(), Run(), Subscribe(), and ~Client().
The documentation for this class was generated from the following file:
streaming/Client.h