CARLA: carla::client::Junction Class Reference
carla::client::Junction Class Reference
#include <Junction.h>
Public Member Functions
geom::BoundingBox GetBoundingBox () const
carla::road::JuncId GetId () const
std::vector< std::pair< SharedPtr< Waypoint >, SharedPtr< Waypoint > > > GetWaypoints (road::Lane::LaneType type=road::Lane::LaneType::Driving) const
Private Member Functions
Junction (SharedPtr< const Map > parent, const road::Junction *junction)
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Private Attributes
geom::BoundingBox _bounding_box
road::JuncId _id
SharedPtr< const Map > _parent
Friends
class Map
Detailed Description
Definition at line 23 of file client/Junction.h.
Constructor & Destructor Documentation
Junction()
carla::client::Junction::Junction (SharedPtr< const Map > parent, const road::Junction * junction) private
Definition at line 14 of file Junction.cpp.
References _bounding_box, _id, carla::road::Junction::GetBoundingBox(), and carla::road::Junction::GetId().
Member Function Documentation
GetBoundingBox()
geom::BoundingBox carla::client::Junction::GetBoundingBox () const
Definition at line 24 of file Junction.cpp.
References _bounding_box.
Referenced by GetId().
GetId()
carla::road::JuncId carla::client::Junction::GetId () const inline
Definition at line 29 of file client/Junction.h.
References _id, carla::road::Lane::Driving, GetBoundingBox(), and GetWaypoints().
Referenced by GetWaypoints().
GetWaypoints()
std::vector< std::pair< SharedPtr< Waypoint >, SharedPtr< Waypoint > > > carla::client::Junction::GetWaypoints (road::Lane::LaneType type = road::Lane::LaneType::Driving) const
Definition at line 19 of file Junction.cpp.
References _parent, and GetId().
Referenced by GetId().
Friends And Related Function Documentation
Map
friend class Map friend
Definition at line 40 of file client/Junction.h.
Member Data Documentation
_bounding_box
geom::BoundingBox carla::client::Junction::_bounding_box private
Definition at line 46 of file client/Junction.h.
Referenced by GetBoundingBox(), and Junction().
_id
road::JuncId carla::client::Junction::_id private
Definition at line 48 of file client/Junction.h.
Referenced by GetId(), and Junction().
_parent
SharedPtr<const Map> carla::client::Junction::_parent private
Definition at line 44 of file client/Junction.h.
Referenced by GetWaypoints().
The documentation for this class was generated from the following files:
client/Junction.h
Junction.cpp