CARLA: CityMapMeshTag Class Reference
CityMapMeshTag Class Reference
Helper class for working with ECityMapMeshTag.
#include <CityMapMeshTag.h>
Static Public Member Functions
static ECityMapMeshTag GetBaseMeshTag ()
Return the base mesh. The base mesh defines the unit tile for map scaling.
static constexpr uint8 GetNumberOfTags ()
Return the number of tags.
static uint32 GetRoadIntersectionSize ()
Get the size in tiles of a road intersection side.
Tag conversions
static constexpr uint8 ToUInt (ECityMapMeshTag Tag)
Convert Tag to an unsigned integer type.
static ECityMapMeshTag FromUInt (uint8 Value)
Convert an unsigned integer to a ECityMapMeshTag.
static FString ToString (ECityMapMeshTag Tag)
Get Tag name as FString.
static FString ToString (uint8 Value)
Convert Value to ECityMapMeshTag and get its name as FString.
Detailed Description
Helper class for working with ECityMapMeshTag.
Definition at line 76 of file CityMapMeshTag.h.
Member Function Documentation
static ECityMapMeshTag CityMapMeshTag::FromUInt (uint8 Value) inline static
Convert an unsigned integer to a ECityMapMeshTag.
Definition at line 101 of file CityMapMeshTag.h.
References GetNumberOfTags(), and ToString().
Referenced by ACityMapMeshHolder::ACityMapMeshHolder(), and ToString().
ECityMapMeshTag CityMapMeshTag::GetBaseMeshTag () static
Return the base mesh. The base mesh defines the unit tile for map scaling.
Definition at line 14 of file CityMapMeshTag.cpp.
Referenced by GetNumberOfTags(), and ACityMapMeshHolder::UpdateMapScale().
static constexpr uint8 CityMapMeshTag::GetNumberOfTags () inline static
Return the number of tags.
Definition at line 81 of file CityMapMeshTag.h.
References GetBaseMeshTag(), GetRoadIntersectionSize(), NUMBER_OF_TAGS, and ToUInt().
Referenced by FromUInt().
uint32 CityMapMeshTag::GetRoadIntersectionSize () static
Get the size in tiles of a road intersection side.
I.e., return N such NxN is the size of a road intersection piece.
Definition at line 19 of file CityMapMeshTag.cpp.
Referenced by ACityMapGenerator::GenerateRoadMap(), ACityMapGenerator::GenerateRoads(), and GetNumberOfTags().
FString CityMapMeshTag::ToString (ECityMapMeshTag Tag) static
Get Tag name as FString.
Definition at line 24 of file CityMapMeshTag.cpp.
Referenced by FromUInt(), ToString(), and ACityMapMeshHolder::UpdateMapScale().
static FString CityMapMeshTag::ToString (uint8 Value) inline static
Convert Value to ECityMapMeshTag and get its name as FString.
Definition at line 110 of file CityMapMeshTag.h.
References FromUInt(), and ToString().
static constexpr uint8 CityMapMeshTag::ToUInt (ECityMapMeshTag Tag) inline static
Convert Tag to an unsigned integer type.
Definition at line 96 of file CityMapMeshTag.h.
Referenced by GetNumberOfTags().
The documentation for this class was generated from the following files:
CityMapMeshTag.h
CityMapMeshTag.cpp