CARLA: traffic_manager::SimpleWaypoint Class Reference
traffic_manager::SimpleWaypoint Class Reference
This is a simple wrapper class on Carla's waypoint object.
#include <SimpleWaypoint.h>
Public Member Functions
bool CheckIntersection () const
Returns true if the object's waypoint belongs to an intersection (Doesn't use OpenDrive).
bool CheckJunction () const
Returns true if the object's waypoint belongs to an intersection.
float Distance (const cg::Location &location) const
Calculates the distance from the object's waypoint to the passed location.
float Distance (const SimpleWaypointPtr &other) const
Calculates the distance the other SimpleWaypoint object.
float DistanceSquared (const cg::Location &location) const
Calculates the square of the distance to given location.
float DistanceSquared (const SimpleWaypointPtr &other) const
Calculates the square of the distance to other waypoints.
cg::Vector3D GetForwardVector () const
Returns the vector along the waypoint's direction.
uint64_t GetId () const
Returns the unique id for the waypoint.
SimpleWaypointPtr GetLeftWaypoint ()
This method is used to get the closest left waypoint for a lane change.
cg::Location GetLocation () const
Returns the location object for this waypoint.
std::vector< SimpleWaypointPtr > GetNextWaypoint () const
Returns the list of next waypoints.
SimpleWaypointPtr GetRightWaypoint ()
This method is used to get the closest right waypoint for a lane change.
WaypointPtr GetWaypoint () const
Returns a carla::shared_ptr to carla::waypoint.
void SetLeftWaypoint (SimpleWaypointPtr waypoint)
This method is used to set the closest left waypoint for a lane change.
uint SetNextWaypoint (const std::vector< SimpleWaypointPtr > &next_waypoints)
This method is used to set the next waypoints.
void SetRightWaypoint (SimpleWaypointPtr waypoint)
This method is used to set the closest right waypoint for a lane change.
SimpleWaypoint (WaypointPtr _waypoint)
~SimpleWaypoint ()
Private Types
using SimpleWaypointPtr = std::shared_ptr< SimpleWaypoint >
Private Attributes
SimpleWaypointPtr next_left_waypoint
Pointer to left lane change waypoint.
SimpleWaypointPtr next_right_waypoint
Pointer to right lane change waypoint.
std::vector< SimpleWaypointPtr > next_waypoints
List of pointers to next connecting waypoints.
WaypointPtr waypoint
Pointer to Carla's waypoint object around which this class wraps around.
Detailed Description
This is a simple wrapper class on Carla's waypoint object.
The class is used to represent discrete samples of the world map.
Definition at line 26 of file SimpleWaypoint.h.
Member Typedef Documentation
using traffic_manager::SimpleWaypoint::SimpleWaypointPtr = std::shared_ptr<SimpleWaypoint> private
Definition at line 28 of file SimpleWaypoint.h.
Constructor & Destructor Documentation
traffic_manager::SimpleWaypoint::SimpleWaypoint (WaypointPtr _waypoint)
Definition at line 13 of file SimpleWaypoint.cpp.
References next_left_waypoint, next_right_waypoint, and waypoint.
traffic_manager::SimpleWaypoint::~SimpleWaypoint ()
Definition at line 18 of file SimpleWaypoint.cpp.
Member Function Documentation
bool traffic_manager::SimpleWaypoint::CheckIntersection () const
Returns true if the object's waypoint belongs to an intersection (Doesn't use OpenDrive).
Definition at line 97 of file SimpleWaypoint.cpp.
References next_waypoints.
bool traffic_manager::SimpleWaypoint::CheckJunction () const
Returns true if the object's waypoint belongs to an intersection.
Definition at line 93 of file SimpleWaypoint.cpp.
References waypoint.
float traffic_manager::SimpleWaypoint::Distance (const cg::Location & location) const
Calculates the distance from the object's waypoint to the passed location.
Definition at line 77 of file SimpleWaypoint.cpp.
References carla::geom::Location::Distance(), and GetLocation().
float traffic_manager::SimpleWaypoint::Distance (const SimpleWaypointPtr & other) const
Calculates the distance the other SimpleWaypoint object.
Definition at line 81 of file SimpleWaypoint.cpp.
References carla::geom::Location::Distance(), and GetLocation().
float traffic_manager::SimpleWaypoint::DistanceSquared (const cg::Location & location) const
Calculates the square of the distance to given location.
Definition at line 85 of file SimpleWaypoint.cpp.
References carla::geom::Math::DistanceSquared(), and GetLocation().
float traffic_manager::SimpleWaypoint::DistanceSquared (const SimpleWaypointPtr & other) const
Calculates the square of the distance to other waypoints.
Definition at line 89 of file SimpleWaypoint.cpp.
References carla::geom::Math::DistanceSquared(), and GetLocation().
cg::Vector3D traffic_manager::SimpleWaypoint::GetForwardVector () const
Returns the vector along the waypoint's direction.
Definition at line 44 of file SimpleWaypoint.cpp.
References waypoint.
uint64_t traffic_manager::SimpleWaypoint::GetId () const
Returns the unique id for the waypoint.
Definition at line 28 of file SimpleWaypoint.cpp.
References waypoint.
SimpleWaypointPtr traffic_manager::SimpleWaypoint::GetLeftWaypoint ()
This method is used to get the closest left waypoint for a lane change.
Definition at line 32 of file SimpleWaypoint.cpp.
References next_left_waypoint.
cg::Location traffic_manager::SimpleWaypoint::GetLocation () const
Returns the location object for this waypoint.
Definition at line 40 of file SimpleWaypoint.cpp.
References waypoint.
Referenced by Distance(), DistanceSquared(), SetLeftWaypoint(), and SetRightWaypoint().
std::vector< SimpleWaypointPtr > traffic_manager::SimpleWaypoint::GetNextWaypoint () const
Returns the list of next waypoints.
Definition at line 20 of file SimpleWaypoint.cpp.
References next_waypoints.
SimpleWaypointPtr traffic_manager::SimpleWaypoint::GetRightWaypoint ()
This method is used to get the closest right waypoint for a lane change.
Definition at line 36 of file SimpleWaypoint.cpp.
References next_right_waypoint.
WaypointPtr traffic_manager::SimpleWaypoint::GetWaypoint () const
Returns a carla::shared_ptr to carla::waypoint.
Definition at line 24 of file SimpleWaypoint.cpp.
References waypoint.
void traffic_manager::SimpleWaypoint::SetLeftWaypoint (SimpleWaypointPtr waypoint)
This method is used to set the closest left waypoint for a lane change.
Definition at line 55 of file SimpleWaypoint.cpp.
References GetLocation(), next_left_waypoint, waypoint, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
uint traffic_manager::SimpleWaypoint::SetNextWaypoint (const std::vector< SimpleWaypointPtr > & next_waypoints)
This method is used to set the next waypoints.
Definition at line 48 of file SimpleWaypoint.cpp.
References next_waypoints.
void traffic_manager::SimpleWaypoint::SetRightWaypoint (SimpleWaypointPtr waypoint)
This method is used to set the closest right waypoint for a lane change.
Definition at line 66 of file SimpleWaypoint.cpp.
References GetLocation(), next_right_waypoint, waypoint, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Member Data Documentation
SimpleWaypointPtr traffic_manager::SimpleWaypoint::next_left_waypoint private
Pointer to left lane change waypoint.
Definition at line 37 of file SimpleWaypoint.h.
Referenced by GetLeftWaypoint(), SetLeftWaypoint(), and SimpleWaypoint().
SimpleWaypointPtr traffic_manager::SimpleWaypoint::next_right_waypoint private
Pointer to right lane change waypoint.
Definition at line 39 of file SimpleWaypoint.h.
Referenced by GetRightWaypoint(), SetRightWaypoint(), and SimpleWaypoint().
std::vector<SimpleWaypointPtr> traffic_manager::SimpleWaypoint::next_waypoints private
List of pointers to next connecting waypoints.
Definition at line 35 of file SimpleWaypoint.h.
Referenced by CheckIntersection(), GetNextWaypoint(), and SetNextWaypoint().
WaypointPtr traffic_manager::SimpleWaypoint::waypoint private
Pointer to Carla's waypoint object around which this class wraps around.
Definition at line 33 of file SimpleWaypoint.h.
Referenced by CheckJunction(), GetForwardVector(), GetId(), GetLocation(), GetWaypoint(), SetLeftWaypoint(), SetRightWaypoint(), and SimpleWaypoint().
The documentation for this class was generated from the following files:
SimpleWaypoint.h
SimpleWaypoint.cpp