CARLA: ACarlaGameModeBase Class Reference
ACarlaGameModeBase Class Reference
Base class for the CARLA Game Mode.
#include <CarlaGameModeBase.h>
Public Member Functions
ACarlaGameModeBase (const FObjectInitializer &ObjectInitializer)
void CheckForEmptyMeshes ()
void DebugShowSignals (bool enable)
void EnableEnvironmentObjects (const TSet< uint64 > &EnvObjectIds, bool Enable)
void EnableOverlapEvents ()
TArray< FBoundingBox > GetAllBBsOfLevel (uint8 TagQueried=0xFF) const
const UCarlaEpisode & GetCarlaEpisode () const
TArray< FEnvironmentObject > GetEnvironmentObjects (uint8 QueriedTag=0xFF) const
const FString GetFullMapPath () const
ALargeMapManager * GetLMManager () const
const boost::optional< carla::road::Map > & GetMap () const
const FString GetRelativeMapPath () const
const TArray< FTransform > & GetSpawnPointsTransforms () const
ATrafficLightManager * GetTrafficLightManager ()
ULevel * GetULevelFromName (FString LevelName)
void LoadMapLayer (int32 MapLayers)
void OnLoadStreamLevel ()
void OnUnloadStreamLevel ()
void UnLoadMapLayer (int32 MapLayers)
Protected Member Functions
void BeginPlay () override
void EndPlay (const EEndPlayReason::Type EndPlayReason) override
void InitGame (const FString &MapName, const FString &Options, FString &ErrorMessage) override
void RestartPlayer (AController *NewPlayer) override
void Tick (float DeltaSeconds) override
Private Member Functions
void ConvertMapLayerMaskToMapNames (int32 MapLayer, TArray< FName > &OutLevelNames)
void GenerateSpawnPoints ()
void OnEpisodeSettingsChanged (const FEpisodeSettings &Settings)
void ParseOpenDrive ()
void RegisterEnvironmentObjects ()
void SpawnActorFactories ()
void StoreSpawnPoints ()
Private Attributes
TSet< TSubclassOf< ACarlaActorFactory > > ActorFactories
List of actor spawners that will be used to define and spawn the actors available in game.
TArray< ACarlaActorFactory * > ActorFactoryInstances
UCarlaSettingsDelegate * CarlaSettingsDelegate = nullptr
UCarlaEpisode * Episode = nullptr
UCarlaGameInstance * GameInstance = nullptr
int32 LatentInfoUUID = 0
ALargeMapManager * LMManager = nullptr
boost::optional< carla::road::Map > Map
UObjectRegister * ObjectRegister = nullptr
FDelegateHandle OnEpisodeSettingsChangeHandle
int PendingLevelsToLoad = 0
int PendingLevelsToUnLoad = 0
bool ReadyToRegisterObjects = false
ACarlaRecorder * Recorder = nullptr
TArray< FTransform > SpawnPointsTransforms
UTaggerDelegate * TaggerDelegate = nullptr
ATrafficLightManager * TrafficLightManager = nullptr
TSubclassOf< AWeather > WeatherClass
The class of Weather to spawn.
Detailed Description
Base class for the CARLA Game Mode.
Definition at line 33 of file CarlaGameModeBase.h.
Constructor & Destructor Documentation
ACarlaGameModeBase()
ACarlaGameModeBase::ACarlaGameModeBase (const FObjectInitializer & ObjectInitializer)
Definition at line 33 of file CarlaGameModeBase.cpp.
References CarlaSettingsDelegate, Episode, ObjectRegister, Recorder, and TaggerDelegate.
Member Function Documentation
BeginPlay()
void ACarlaGameModeBase::BeginPlay () override protected
Todo:
If semantic segmentation enabled.
Todo:
Recorder should not tick here, FCarlaEngine should do it.
Definition at line 164 of file CarlaGameModeBase.cpp.
References AWeather::ApplyWeather(), CarlaReplayer::CheckPlayAfterMapLoaded(), carla::rpc::WeatherParameters::Default, EnableOverlapEvents(), Episode, GameInstance, UCarlaGameInstance::GetCurrentMapLayer(), ACarlaRecorder::GetReplayer(), GetTrafficLightManager(), UCarlaEpisode::InitializeAtBeginPlay(), LMManager, LoadMapLayer(), UCarlaGameInstance::NotifyBeginEpisode(), PendingLevelsToLoad, ReadyToRegisterObjects, Recorder, RegisterEnvironmentObjects(), ALargeMapManager::RegisterInitialObjects(), UTaggerDelegate::SetSemanticSegmentationEnabled(), ATagger::TagActorsInLevel(), TaggerDelegate, and UCarlaEpisode::Weather.
CheckForEmptyMeshes()
void ACarlaGameModeBase::CheckForEmptyMeshes ()
Definition at line 342 of file CarlaGameModeBase.cpp.
ConvertMapLayerMaskToMapNames()
void ACarlaGameModeBase::ConvertMapLayerMaskToMapNames (int32 MapLayer, TArray< FName > & OutLevelNames) private
Definition at line 554 of file CarlaGameModeBase.cpp.
References carla::rpc::All, and carla::rpc::MapLayerToString().
Referenced by LoadMapLayer(), and UnLoadMapLayer().
DebugShowSignals()
void ACarlaGameModeBase::DebugShowSignals (bool enable)
Definition at line 375 of file CarlaGameModeBase.cpp.
References carla::geom::Math::GenerateRange(), carla::geom::Rotation::GetUpVector(), and Map.
EnableEnvironmentObjects()
void ACarlaGameModeBase::EnableEnvironmentObjects (const TSet< uint64 > & EnvObjectIds, bool Enable)
Definition at line 497 of file CarlaGameModeBase.cpp.
References UObjectRegister::EnableEnvironmentObjects(), and ObjectRegister.
Referenced by FCarlaServer::FPimpl::BindActions().
EnableOverlapEvents()
void ACarlaGameModeBase::EnableOverlapEvents ()
Definition at line 357 of file CarlaGameModeBase.cpp.
Referenced by BeginPlay().
EndPlay()
void ACarlaGameModeBase::EndPlay (const EEndPlayReason::Type EndPlayReason) override protected
Definition at line 242 of file CarlaGameModeBase.cpp.
References CarlaSettingsDelegate, UCarlaEpisode::EndPlay(), Episode, GameInstance, UCarlaGameInstance::NotifyEndEpisode(), FCarlaStaticDelegates::OnEpisodeSettingsChange, OnEpisodeSettingsChangeHandle, and UCarlaSettingsDelegate::Reset().
GenerateSpawnPoints()
void ACarlaGameModeBase::GenerateSpawnPoints () private
Definition at line 295 of file CarlaGameModeBase.cpp.
References Map, and SpawnPointsTransforms.
Referenced by StoreSpawnPoints().
GetAllBBsOfLevel()
TArray< FBoundingBox > ACarlaGameModeBase::GetAllBBsOfLevel (uint8 TagQueried = 0xFF) const
Definition at line 475 of file CarlaGameModeBase.cpp.
References UBoundingBoxCalculator::GetBoundingBoxOfActors().
Referenced by FCarlaServer::FPimpl::BindActions().
GetCarlaEpisode()
const UCarlaEpisode& ACarlaGameModeBase::GetCarlaEpisode () const inline
Definition at line 41 of file CarlaGameModeBase.h.
GetEnvironmentObjects()
TArray<FEnvironmentObject> ACarlaGameModeBase::GetEnvironmentObjects (uint8 QueriedTag = 0xFF) const inline
Definition at line 71 of file CarlaGameModeBase.h.
Referenced by FCarlaServer::FPimpl::BindActions().
GetFullMapPath()
const FString ACarlaGameModeBase::GetFullMapPath () const
Definition at line 62 of file CarlaGameModeBase.cpp.
References GetRelativeMapPath().
Referenced by FCarlaServer::FPimpl::BindActions(), and UOpenDrive::GetXODR().
GetLMManager()
ALargeMapManager* ACarlaGameModeBase::GetLMManager () const inline
Definition at line 97 of file CarlaGameModeBase.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and UCarlaStatics::GetLargeMapManager().
GetMap()
const boost::optional<carla::road::Map>& ACarlaGameModeBase::GetMap () const inline
Definition at line 47 of file CarlaGameModeBase.h.
Referenced by AOpenDriveGenerator::GenerateRoadMesh(), AOpenDriveGenerator::GenerateSpawnPoints(), ATrafficLightManager::GetMap(), AOpenDriveGenerator::IsOpenDriveValid(), FTrafficSignData::RestoreActorData(), and FTrafficLightData::RestoreActorData().
GetRelativeMapPath()
const FString ACarlaGameModeBase::GetRelativeMapPath () const
Definition at line 53 of file CarlaGameModeBase.cpp.
Referenced by GetFullMapPath().
GetSpawnPointsTransforms()
const TArray<FTransform>& ACarlaGameModeBase::GetSpawnPointsTransforms () const inline
Definition at line 63 of file CarlaGameModeBase.h.
Referenced by UCarlaEpisode::GetRecommendedSpawnPoints().
GetTrafficLightManager()
ATrafficLightManager * ACarlaGameModeBase::GetTrafficLightManager ()
Definition at line 322 of file CarlaGameModeBase.cpp.
References GetULevelFromName(), and TrafficLightManager.
Referenced by BeginPlay().
GetULevelFromName()
ULevel * ACarlaGameModeBase::GetULevelFromName (FString LevelName)
Definition at line 596 of file CarlaGameModeBase.cpp.
Referenced by GetTrafficLightManager(), ATrafficLightManager::RegisterLightComponentFromOpenDRIVE(), ATrafficLightManager::SpawnSignals(), and ATrafficLightManager::SpawnTrafficLights().
InitGame()
void ACarlaGameModeBase::InitGame (const FString & MapName, const FString & Options, FString & ErrorMessage) override protected
Definition at line 68 of file CarlaGameModeBase.cpp.
References UCarlaSettingsDelegate::ApplyQualityLevelPostRestart(), CarlaSettingsDelegate, Episode, GameInstance, ALargeMapManager::GenerateLargeMap(), ALargeMapManager::GetNumTiles(), ALargeMapManager::LargeMapName, LMManager, Map, UCarlaEpisode::MapName, UCarlaGameInstance::NotifyInitGame(), FCarlaStaticDelegates::OnEpisodeSettingsChange, OnEpisodeSettingsChanged(), OnEpisodeSettingsChangeHandle, ParseOpenDrive(), Recorder, UTaggerDelegate::RegisterSpawnHandler(), UCarlaSettingsDelegate::RegisterSpawnHandler(), ACarlaRecorder::SetEpisode(), UCarlaEpisode::SetRecorder(), SpawnActorFactories(), StoreSpawnPoints(), TaggerDelegate, UCarlaEpisode::Weather, and WeatherClass.
LoadMapLayer()
void ACarlaGameModeBase::LoadMapLayer (int32 MapLayers)
Definition at line 504 of file CarlaGameModeBase.cpp.
References ConvertMapLayerMaskToMapNames(), LatentInfoUUID, and PendingLevelsToLoad.
Referenced by BeginPlay(), and FCarlaServer::FPimpl::BindActions().
OnEpisodeSettingsChanged()
void ACarlaGameModeBase::OnEpisodeSettingsChanged (const FEpisodeSettings & Settings) private
Definition at line 641 of file CarlaGameModeBase.cpp.
References CarlaSettingsDelegate, FEpisodeSettings::MaxCullingDistance, and UCarlaSettingsDelegate::SetAllActorsDrawDistance().
Referenced by InitGame().
OnLoadStreamLevel()
void ACarlaGameModeBase::OnLoadStreamLevel ()
Definition at line 619 of file CarlaGameModeBase.cpp.
References PendingLevelsToLoad, ReadyToRegisterObjects, RegisterEnvironmentObjects(), and ATagger::TagActorsInLevel().
OnUnloadStreamLevel()
void ACarlaGameModeBase::OnUnloadStreamLevel ()
Definition at line 631 of file CarlaGameModeBase.cpp.
References PendingLevelsToUnLoad, ReadyToRegisterObjects, and RegisterEnvironmentObjects().
ParseOpenDrive()
void ACarlaGameModeBase::ParseOpenDrive () private
Definition at line 309 of file CarlaGameModeBase.cpp.
References Episode, UOpenDrive::GetXODR(), carla::opendrive::OpenDriveParser::Load(), Map, and UCarlaEpisode::MapGeoReference.
Referenced by InitGame().
RegisterEnvironmentObjects()
void ACarlaGameModeBase::RegisterEnvironmentObjects () private
Definition at line 489 of file CarlaGameModeBase.cpp.
References ObjectRegister, and UObjectRegister::RegisterObjects().
Referenced by BeginPlay(), OnLoadStreamLevel(), and OnUnloadStreamLevel().
RestartPlayer()
void ACarlaGameModeBase::RestartPlayer (AController * NewPlayer) override protected
Definition at line 154 of file CarlaGameModeBase.cpp.
References UCarlaSettingsDelegate::ApplyQualityLevelPreRestart(), and CarlaSettingsDelegate.
SpawnActorFactories()
void ACarlaGameModeBase::SpawnActorFactories () private
Definition at line 257 of file CarlaGameModeBase.cpp.
References ActorFactories, ActorFactoryInstances, Episode, and UCarlaEpisode::RegisterActorFactory().
Referenced by InitGame().
StoreSpawnPoints()
void ACarlaGameModeBase::StoreSpawnPoints () private
Definition at line 280 of file CarlaGameModeBase.cpp.
References GenerateSpawnPoints(), and SpawnPointsTransforms.
Referenced by InitGame().
Tick()
void ACarlaGameModeBase::Tick (float DeltaSeconds) override protected
Todo:
Recorder should not tick here, FCarlaEngine should do it.
Definition at line 231 of file CarlaGameModeBase.cpp.
References Recorder.
UnLoadMapLayer()
void ACarlaGameModeBase::UnLoadMapLayer (int32 MapLayers)
Definition at line 529 of file CarlaGameModeBase.cpp.
References ConvertMapLayerMaskToMapNames(), LatentInfoUUID, and PendingLevelsToUnLoad.
Referenced by FCarlaServer::FPimpl::BindActions().
Member Data Documentation
ActorFactories
TSet<TSubclassOf<ACarlaActorFactory> > ACarlaGameModeBase::ActorFactories private
List of actor spawners that will be used to define and spawn the actors available in game.
Definition at line 154 of file CarlaGameModeBase.h.
Referenced by SpawnActorFactories().
ActorFactoryInstances
TArray<ACarlaActorFactory *> ACarlaGameModeBase::ActorFactoryInstances private
Definition at line 160 of file CarlaGameModeBase.h.
Referenced by SpawnActorFactories().
CarlaSettingsDelegate
UCarlaSettingsDelegate* ACarlaGameModeBase::CarlaSettingsDelegate = nullptr private
Definition at line 136 of file CarlaGameModeBase.h.
Referenced by ACarlaGameModeBase(), EndPlay(), InitGame(), OnEpisodeSettingsChanged(), and RestartPlayer().
Episode
UCarlaEpisode* ACarlaGameModeBase::Episode = nullptr private
Definition at line 139 of file CarlaGameModeBase.h.
Referenced by ACarlaGameModeBase(), BeginPlay(), EndPlay(), InitGame(), ParseOpenDrive(), and SpawnActorFactories().
GameInstance
UCarlaGameInstance* ACarlaGameModeBase::GameInstance = nullptr private
Definition at line 130 of file CarlaGameModeBase.h.
Referenced by BeginPlay(), EndPlay(), and InitGame().
LatentInfoUUID
int32 ACarlaGameModeBase::LatentInfoUUID = 0 private
Definition at line 178 of file CarlaGameModeBase.h.
Referenced by LoadMapLayer(), and UnLoadMapLayer().
LMManager
ALargeMapManager* ACarlaGameModeBase::LMManager = nullptr private
Definition at line 165 of file CarlaGameModeBase.h.
Referenced by BeginPlay(), and InitGame().
Map
boost::optional<carla::road::Map> ACarlaGameModeBase::Map private
Definition at line 169 of file CarlaGameModeBase.h.
Referenced by DebugShowSignals(), GenerateSpawnPoints(), InitGame(), and ParseOpenDrive().
ObjectRegister
UObjectRegister* ACarlaGameModeBase::ObjectRegister = nullptr private
Definition at line 145 of file CarlaGameModeBase.h.
Referenced by ACarlaGameModeBase(), EnableEnvironmentObjects(), and RegisterEnvironmentObjects().
OnEpisodeSettingsChangeHandle
FDelegateHandle ACarlaGameModeBase::OnEpisodeSettingsChangeHandle private
Definition at line 167 of file CarlaGameModeBase.h.
Referenced by EndPlay(), and InitGame().
PendingLevelsToLoad
int ACarlaGameModeBase::PendingLevelsToLoad = 0 private
Definition at line 171 of file CarlaGameModeBase.h.
Referenced by BeginPlay(), LoadMapLayer(), and OnLoadStreamLevel().
PendingLevelsToUnLoad
int ACarlaGameModeBase::PendingLevelsToUnLoad = 0 private
Definition at line 172 of file CarlaGameModeBase.h.
Referenced by OnUnloadStreamLevel(), and UnLoadMapLayer().
ReadyToRegisterObjects
bool ACarlaGameModeBase::ReadyToRegisterObjects = false private
Definition at line 174 of file CarlaGameModeBase.h.
Referenced by BeginPlay(), OnLoadStreamLevel(), and OnUnloadStreamLevel().
Recorder
ACarlaRecorder* ACarlaGameModeBase::Recorder = nullptr private
Definition at line 142 of file CarlaGameModeBase.h.
Referenced by ACarlaGameModeBase(), BeginPlay(), InitGame(), and Tick().
SpawnPointsTransforms
TArray<FTransform> ACarlaGameModeBase::SpawnPointsTransforms private
Definition at line 157 of file CarlaGameModeBase.h.
Referenced by GenerateSpawnPoints(), and StoreSpawnPoints().
TaggerDelegate
UTaggerDelegate* ACarlaGameModeBase::TaggerDelegate = nullptr private
Definition at line 133 of file CarlaGameModeBase.h.
Referenced by ACarlaGameModeBase(), BeginPlay(), and InitGame().
TrafficLightManager
ATrafficLightManager* ACarlaGameModeBase::TrafficLightManager = nullptr private
Definition at line 163 of file CarlaGameModeBase.h.
Referenced by GetTrafficLightManager().
WeatherClass
TSubclassOf<AWeather> ACarlaGameModeBase::WeatherClass private
The class of Weather to spawn.
Definition at line 149 of file CarlaGameModeBase.h.
Referenced by InitGame().
The documentation for this class was generated from the following files:
CarlaGameModeBase.h
CarlaGameModeBase.cpp