CARLA: ListView< IT > Class Template Reference
ListView< IT > Class Template Reference
#include <ListView.h>
Public Types
using iterator = IT
Public Member Functions
iterator begin () const
bool empty () const
iterator end () const
ListView (iterator begin, iterator end)
template<typename STL_CONTAINER >
ListView (STL_CONTAINER &StlContainer)
ListView (const ListView &)=default
ListView & operator= (const ListView &)=delete
Private Attributes
const iterator Begin
const iterator End
Detailed Description
template<typename IT>
class ListView< IT >
Definition at line 10 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
Member Typedef Documentation
template<typename IT > using ListView< IT >::iterator = IT
Definition at line 14 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
Constructor & Destructor Documentation
template<typename IT > ListView< IT >::ListView (iterator begin, iterator end) inline explicit
Definition at line 16 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
Referenced by ListView< IT >::ListView().
template<typename IT > template<typename STL_CONTAINER > ListView< IT >::ListView (STL_CONTAINER & StlContainer) inline explicit
Definition at line 19 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
References ListView< IT >::ListView(), and ListView< IT >::operator=().
template<typename IT > ListView< IT >::ListView (const ListView< IT > &) default
Member Function Documentation
template<typename IT > iterator ListView< IT >::begin () const inline
Definition at line 26 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
References ListView< IT >::Begin.
template<typename IT > bool ListView< IT >::empty () const inline
Definition at line 34 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
References ListView< IT >::Begin, and ListView< IT >::End.
template<typename IT > iterator ListView< IT >::end () const inline
Definition at line 30 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
References ListView< IT >::End.
template<typename IT > ListView& ListView< IT >::operator= (const ListView< IT > &) delete
Referenced by ListView< IT >::ListView().
Member Data Documentation
template<typename IT > const iterator ListView< IT >::Begin private
Definition at line 40 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
Referenced by ListView< IT >::begin(), and ListView< IT >::empty().
template<typename IT > const iterator ListView< IT >::End private
Definition at line 42 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h.
Referenced by ListView< IT >::empty(), and ListView< IT >::end().
The documentation for this class was generated from the following file:
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Util/ListView.h