CARLA: carla::sensor::s11n::CollisionEventSerializer Class Reference
carla::sensor::s11n::CollisionEventSerializer Class Reference
Serializes the current state of the whole episode.
#include <CollisionEventSerializer.h>
Classes
struct Data
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static Data DeserializeRawData (const RawData &message)
template<typename SensorT >
static Buffer Serialize (const SensorT &, rpc::Actor self_actor, rpc::Actor other_actor, geom::Vector3D normal_impulse)
Static Public Attributes
static constexpr auto header_offset = 0u
Detailed Description
Serializes the current state of the whole episode.
Definition at line 24 of file CollisionEventSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::CollisionEventSerializer::Deserialize (RawData && data) static
Definition at line 14 of file CollisionEventSerializer.cpp.
Referenced by Serialize().
DeserializeRawData()
static Data carla::sensor::s11n::CollisionEventSerializer::DeserializeRawData (const RawData & message) inline static
Definition at line 40 of file CollisionEventSerializer.h.
References carla::sensor::RawData::begin(), and carla::sensor::RawData::size().
Serialize()
template<typename SensorT > static Buffer carla::sensor::s11n::CollisionEventSerializer::Serialize (const SensorT & , rpc::Actor self_actor, rpc::Actor other_actor, geom::Vector3D normal_impulse) inline static
Definition at line 45 of file CollisionEventSerializer.h.
References Deserialize(), carla::sensor::s11n::CollisionEventSerializer::Data::other_actor, carla::MsgPack::Pack(), and carla::sensor::s11n::CollisionEventSerializer::Data::self_actor.
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::CollisionEventSerializer::header_offset = 0u static
Definition at line 38 of file CollisionEventSerializer.h.
The documentation for this class was generated from the following files:
CollisionEventSerializer.h
CollisionEventSerializer.cpp