CARLA: CarlaRecorderEventDel Struct Reference
CarlaRecorderEventDel Struct Reference
#include <CarlaRecorderEventDel.h>
Public Member Functions
void Read (std::ifstream &InFile)
void Write (std::ofstream &OutFile) const
Public Attributes
uint32_t DatabaseId
Detailed Description
Definition at line 12 of file CarlaRecorderEventDel.h.
Member Function Documentation
Read()
void CarlaRecorderEventDel::Read (std::ifstream & InFile)
Definition at line 11 of file CarlaRecorderEventDel.cpp.
References DatabaseId.
Referenced by CarlaReplayer::ProcessEventsDel(), CarlaRecorderQuery::QueryBlocked(), CarlaRecorderQuery::QueryCollisions(), and CarlaRecorderQuery::QueryInfo().
Write()
void CarlaRecorderEventDel::Write (std::ofstream & OutFile) const
Definition at line 16 of file CarlaRecorderEventDel.cpp.
References DatabaseId.
Member Data Documentation
DatabaseId
uint32_t CarlaRecorderEventDel::DatabaseId
Definition at line 14 of file CarlaRecorderEventDel.h.
Referenced by CarlaReplayer::ProcessEventsDel(), CarlaRecorderQuery::QueryInfo(), Read(), and Write().
The documentation for this struct was generated from the following files:
CarlaRecorderEventDel.h
CarlaRecorderEventDel.cpp