CARLA: FActorData Class Reference
FActorData Class Reference
#include <ActorData.h>
Public Member Functions
FTransform GetLocalTransform (UCarlaEpisode *CarlaEpisode) const
virtual void RecordActorData (FCarlaActor *CarlaActor, UCarlaEpisode *CarlaEpisode)
virtual AActor * RespawnActor (UCarlaEpisode *CarlaEpisode, const FActorInfo &Info)
virtual void RestoreActorData (FCarlaActor *CarlaActor, UCarlaEpisode *CarlaEpisode)
virtual ~FActorData ()
Public Attributes
FVector AngularVelocity = FVector(0,0,0)
bool bSimulatePhysics = false
FDVector Location
FQuat Rotation
FVector Scale
FVector Velocity
Detailed Description
Definition at line 27 of file ActorData.h.
Constructor & Destructor Documentation
~FActorData()
virtual FActorData::~FActorData () inline virtual
Definition at line 51 of file ActorData.h.
Member Function Documentation
GetLocalTransform()
FTransform FActorData::GetLocalTransform (UCarlaEpisode * CarlaEpisode) const
Definition at line 83 of file ActorData.cpp.
References UCarlaEpisode::GetCurrentMapOrigin(), Location, Rotation, and Scale.
Referenced by RespawnActor(), FTrafficSignData::RespawnActor(), FTrafficLightData::RespawnActor(), and RestoreActorData().
RecordActorData()
void FActorData::RecordActorData (FCarlaActor * CarlaActor, UCarlaEpisode * CarlaEpisode) virtual
Reimplemented in FActorSensorData, FTrafficLightData, FTrafficSignData, FWalkerData, and FVehicleData.
Definition at line 30 of file ActorData.cpp.
References AngularVelocity, bSimulatePhysics, FCarlaActor::GetActor(), UCarlaEpisode::GetCurrentMapOrigin(), Location, Rotation, Scale, and Velocity.
Referenced by FVehicleData::RecordActorData(), FWalkerData::RecordActorData(), FTrafficSignData::RecordActorData(), FTrafficLightData::RecordActorData(), and FActorSensorData::RecordActorData().
RespawnActor()
AActor * FActorData::RespawnActor (UCarlaEpisode * CarlaEpisode, const FActorInfo & Info) virtual
Reimplemented in FTrafficLightData, and FTrafficSignData.
Definition at line 22 of file ActorData.cpp.
References FActorInfo::Description, GetLocalTransform(), and UCarlaEpisode::ReSpawnActorWithInfo().
RestoreActorData()
void FActorData::RestoreActorData (FCarlaActor * CarlaActor, UCarlaEpisode * CarlaEpisode) virtual
Reimplemented in FActorSensorData, FTrafficLightData, FTrafficSignData, FWalkerData, and FVehicleData.
Definition at line 46 of file ActorData.cpp.
References AngularVelocity, bSimulatePhysics, Character, FCarlaActor::GetActor(), GetLocalTransform(), and Velocity.
Referenced by FVehicleData::RestoreActorData(), FWalkerData::RestoreActorData(), and FActorSensorData::RestoreActorData().
Member Data Documentation
AngularVelocity
FVector FActorData::AngularVelocity = FVector(0,0,0)
Definition at line 39 of file ActorData.h.
Referenced by FWorldObserver_Serialize(), RecordActorData(), and RestoreActorData().
bSimulatePhysics
bool FActorData::bSimulatePhysics = false
Definition at line 41 of file ActorData.h.
Referenced by RecordActorData(), FVehicleData::RecordActorData(), RestoreActorData(), and FVehicleData::RestoreActorData().
Location
FDVector FActorData::Location
Definition at line 31 of file ActorData.h.
Referenced by ALargeMapManager::CheckDormantActors(), GetLocalTransform(), and RecordActorData().
Rotation
FQuat FActorData::Rotation
Definition at line 33 of file ActorData.h.
Referenced by GetLocalTransform(), and RecordActorData().
Scale
FVector FActorData::Scale
Definition at line 35 of file ActorData.h.
Referenced by GetLocalTransform(), and RecordActorData().
Velocity
FVector FActorData::Velocity
Definition at line 37 of file ActorData.h.
Referenced by FWorldObserver_Serialize(), RecordActorData(), and RestoreActorData().
The documentation for this class was generated from the following files:
ActorData.h
ActorData.cpp