CARLA: carla::logging Namespace Reference
carla::logging Namespace Reference
Functions
template<typename ... Args>
static void log (Args &&... args)
template<typename Arg , typename ... Args>
static LIBCARLA_NOINLINE void write_to_stream (std::ostream &out, Arg &&arg, Args &&... args)
Function Documentation
log()
template<typename ... Args> static void carla::logging::log (Args &&... args) inline static
Definition at line 59 of file Logging.h.
References carla::log_debug(), and write_to_stream().
Referenced by carla::nav::Navigation::AddOrUpdateVehicle(), benchmark_image(), carla::nav::Navigation::CreateCrowd(), ADVSCamera::imageToLogGray(), carla::geom::LatLonToMercator(), carla::nav::Navigation::Load(), carla::image::ColorConverter::LogarithmicLinear::operator()(), carla::profiler::detail::StaticProfiler::StaticProfiler(), and TEST().
write_to_stream()
template<typename Arg , typename ... Args> static LIBCARLA_NOINLINE void carla::logging::write_to_stream (std::ostream & out, Arg && arg, Args &&... args) static
Definition at line 52 of file Logging.h.
Referenced by carla::profiler::log(), log(), carla::log_critical(), carla::log_error(), carla::log_info(), carla::log_warning(), and Benchmark::Run().