CARLA: carla::traffic_manager::TrafficManagerBase Class Reference
carla::traffic_manager::TrafficManagerBase Class Reference abstract
The function of this class is to integrate all the various stages of the traffic manager appropriately using messengers.
#include <TrafficManagerBase.h>
Public Member Functions
virtual ActionBuffer GetActionBuffer (const ActorId &actor_id)=0
Method to get the vehicle's action buffer.
virtual carla::client::detail::EpisodeProxy & GetEpisodeProxy ()=0
Get carla episode information.
virtual Action GetNextAction (const ActorId &actor_id)=0
Method to get the vehicle's next action.
virtual void RegisterVehicles (const std::vector< ActorPtr > &actor_list)=0
This method registers a vehicle with the traffic manager.
virtual void Release ()=0
To release the traffic manager.
virtual void RemoveImportedRoute (const ActorId &actor_id, const bool remove_path)=0
Method to remove a route.
virtual void RemoveUploadPath (const ActorId &actor_id, const bool remove_path)=0
Method to remove a path.
virtual void Reset ()=0
To reset the traffic manager.
virtual void SetAutoLaneChange (const ActorPtr &actor, const bool enable)=0
Enable/disable automatic lane change on a vehicle.
virtual void SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound)=0
Method to set boundaries for respawning vehicles.
virtual void SetCollisionDetection (const ActorPtr &reference_actor, const ActorPtr &other_actor, const bool detect_collision)=0
Method to set collision detection rules between vehicles.
virtual void SetCustomPath (const ActorPtr &actor, const Path path, const bool empty_buffer)=0
Method to set our own imported path.
virtual void SetDesiredSpeed (const ActorPtr &actor, const float value)=0
Set a vehicle's exact desired velocity.
virtual void SetDistanceToLeadingVehicle (const ActorPtr &actor, const float distance)=0
Method to specify how much distance a vehicle should maintain to the leading vehicle.
virtual void SetForceLaneChange (const ActorPtr &actor, const bool direction)=0
Method to force lane change on a vehicle.
virtual void SetGlobalDistanceToLeadingVehicle (const float dist)=0
Method to set Global Distance to Leading Vehicle.
virtual void SetGlobalLaneOffset (float const offset)=0
Method to set a global lane offset displacement from the center line.
virtual void SetGlobalPercentageSpeedDifference (float const percentage)=0
Set a global % decrease in velocity with respect to the speed limit.
virtual void SetHybridPhysicsMode (const bool mode_switch)=0
Method to set hybrid physics mode.
virtual void SetHybridPhysicsRadius (const float radius)=0
Method to set hybrid physics radius.
virtual void SetImportedRoute (const ActorPtr &actor, const Route route, const bool empty_buffer)=0
Method to set our own imported route.
virtual void SetKeepRightPercentage (const ActorPtr &actor, const float percentage)=0
Method to set % to keep on the right lane.
virtual void SetLaneOffset (const ActorPtr &actor, const float offset)=0
Method to set a lane offset displacement from the center line.
virtual void SetMaxBoundaries (const float lower, const float upper)=0
Method to set limits for boundaries when respawning vehicles.
virtual void SetOSMMode (const bool mode_switch)=0
Method to set Open Street Map mode.
virtual void SetPercentageIgnoreVehicles (const ActorPtr &actor, const float perc)=0
Method to specify the % chance of ignoring collisions with any vehicle.
virtual void SetPercentageIgnoreWalkers (const ActorPtr &actor, const float perc)=0
Method to specify the % chance of ignoring collisions with any walker.
virtual void SetPercentageRunningLight (const ActorPtr &actor, const float perc)=0
Method to specify the % chance of running any traffic light.
virtual void SetPercentageRunningSign (const ActorPtr &actor, const float perc)=0
Method to specify the % chance of running any traffic sign.
virtual void SetPercentageSpeedDifference (const ActorPtr &actor, const float percentage)=0
Set a vehicle's % decrease in velocity with respect to the speed limit.
virtual void SetRandomDeviceSeed (const uint64_t seed)=0
Method to set randomization seed.
virtual void SetRandomLeftLaneChangePercentage (const ActorPtr &actor, const float percentage)=0
Method to set % to randomly do a left lane change.
virtual void SetRandomRightLaneChangePercentage (const ActorPtr &actor, const float percentage)=0
Method to set % to randomly do a right lane change.
virtual void SetRespawnDormantVehicles (const bool mode_switch)=0
Method to set automatic respawn of dormant vehicles.
virtual void SetSynchronousMode (bool mode)=0
Method to switch traffic manager into synchronous execution.
virtual void SetSynchronousModeTimeOutInMiliSecond (double time)=0
Method to set Tick timeout for synchronous execution.
virtual void SetUpdateVehicleLights (const ActorPtr &actor, const bool do_update)=0
Method to set the automatic management of the vehicle lights.
virtual void ShutDown ()=0
virtual void Start ()=0
To start the traffic manager.
virtual void Stop ()=0
To stop the traffic manager.
virtual bool SynchronousTick ()=0
Method to provide synchronous tick.
TrafficManagerBase ()
Protected constructor for singleton lifecycle management.
virtual void UnregisterVehicles (const std::vector< ActorPtr > &actor_list)=0
This method unregisters a vehicle from traffic manager.
virtual void UpdateImportedRoute (const ActorId &actor_id, const Route route)=0
Method to update an already set route.
virtual void UpdateUploadPath (const ActorId &actor_id, const Path path)=0
Method to update an already set path.
virtual ~TrafficManagerBase ()
Destructor.
Detailed Description
The function of this class is to integrate all the various stages of the traffic manager appropriately using messengers.
Definition at line 26 of file TrafficManagerBase.h.
Constructor & Destructor Documentation
TrafficManagerBase()
carla::traffic_manager::TrafficManagerBase::TrafficManagerBase () inline
Protected constructor for singleton lifecycle management.
Definition at line 42 of file TrafficManagerBase.h.
~TrafficManagerBase()
virtual carla::traffic_manager::TrafficManagerBase::~TrafficManagerBase () inline virtual
Destructor.
Definition at line 45 of file TrafficManagerBase.h.
References GetActionBuffer(), GetEpisodeProxy(), GetNextAction(), RegisterVehicles(), RemoveImportedRoute(), RemoveUploadPath(), SetAutoLaneChange(), SetBoundariesRespawnDormantVehicles(), SetCollisionDetection(), SetCustomPath(), SetDesiredSpeed(), SetDistanceToLeadingVehicle(), SetForceLaneChange(), SetGlobalDistanceToLeadingVehicle(), SetGlobalLaneOffset(), SetGlobalPercentageSpeedDifference(), SetHybridPhysicsMode(), SetHybridPhysicsRadius(), SetImportedRoute(), SetKeepRightPercentage(), SetLaneOffset(), SetMaxBoundaries(), SetOSMMode(), SetPercentageIgnoreVehicles(), SetPercentageIgnoreWalkers(), SetPercentageRunningLight(), SetPercentageRunningSign(), SetPercentageSpeedDifference(), SetRandomDeviceSeed(), SetRandomLeftLaneChangePercentage(), SetRandomRightLaneChangePercentage(), SetRespawnDormantVehicles(), SetSynchronousMode(), SetSynchronousModeTimeOutInMiliSecond(), SetUpdateVehicleLights(), ShutDown(), SynchronousTick(), UnregisterVehicles(), UpdateImportedRoute(), and UpdateUploadPath().
Member Function Documentation
GetActionBuffer()
virtual ActionBuffer carla::traffic_manager::TrafficManagerBase::GetActionBuffer (const ActorId & actor_id) pure virtual
Method to get the vehicle's action buffer.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::GetActionBuffer(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
GetEpisodeProxy()
virtual carla::client::detail::EpisodeProxy& carla::traffic_manager::TrafficManagerBase::GetEpisodeProxy () pure virtual
Get carla episode information.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
GetNextAction()
virtual Action carla::traffic_manager::TrafficManagerBase::GetNextAction (const ActorId & actor_id) pure virtual
Method to get the vehicle's next action.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::GetNextAction(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
RegisterVehicles()
virtual void carla::traffic_manager::TrafficManagerBase::RegisterVehicles (const std::vector< ActorPtr > & actor_list) pure virtual
This method registers a vehicle with the traffic manager.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::RegisterVehicles(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
Release()
virtual void carla::traffic_manager::TrafficManagerBase::Release () pure virtual
To release the traffic manager.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManagerServer::TrafficManagerServer().
RemoveImportedRoute()
virtual void carla::traffic_manager::TrafficManagerBase::RemoveImportedRoute (const ActorId & actor_id, const bool remove_path) pure virtual
Method to remove a route.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::RemoveImportedRoute(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
RemoveUploadPath()
virtual void carla::traffic_manager::TrafficManagerBase::RemoveUploadPath (const ActorId & actor_id, const bool remove_path) pure virtual
Method to remove a path.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::RemoveUploadPath(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
Reset()
virtual void carla::traffic_manager::TrafficManagerBase::Reset () pure virtual
To reset the traffic manager.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
SetAutoLaneChange()
virtual void carla::traffic_manager::TrafficManagerBase::SetAutoLaneChange (const ActorPtr & actor, const bool enable) pure virtual
Enable/disable automatic lane change on a vehicle.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetAutoLaneChange(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetBoundariesRespawnDormantVehicles()
virtual void carla::traffic_manager::TrafficManagerBase::SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound) pure virtual
Method to set boundaries for respawning vehicles.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetBoundariesRespawnDormantVehicles(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetCollisionDetection()
virtual void carla::traffic_manager::TrafficManagerBase::SetCollisionDetection (const ActorPtr & reference_actor, const ActorPtr & other_actor, const bool detect_collision) pure virtual
Method to set collision detection rules between vehicles.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetCollisionDetection(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetCustomPath()
virtual void carla::traffic_manager::TrafficManagerBase::SetCustomPath (const ActorPtr & actor, const Path path, const bool empty_buffer) pure virtual
Method to set our own imported path.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetCustomPath(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetDesiredSpeed()
virtual void carla::traffic_manager::TrafficManagerBase::SetDesiredSpeed (const ActorPtr & actor, const float value) pure virtual
Set a vehicle's exact desired velocity.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetDesiredSpeed(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetDistanceToLeadingVehicle()
virtual void carla::traffic_manager::TrafficManagerBase::SetDistanceToLeadingVehicle (const ActorPtr & actor, const float distance) pure virtual
Method to specify how much distance a vehicle should maintain to the leading vehicle.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetDistanceToLeadingVehicle(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetForceLaneChange()
virtual void carla::traffic_manager::TrafficManagerBase::SetForceLaneChange (const ActorPtr & actor, const bool direction) pure virtual
Method to force lane change on a vehicle.
Direction flag can be set to true for left and false for right.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetForceLaneChange(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetGlobalDistanceToLeadingVehicle()
virtual void carla::traffic_manager::TrafficManagerBase::SetGlobalDistanceToLeadingVehicle (const float dist) pure virtual
Method to set Global Distance to Leading Vehicle.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetGlobalDistanceToLeadingVehicle(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetGlobalLaneOffset()
virtual void carla::traffic_manager::TrafficManagerBase::SetGlobalLaneOffset (float const offset) pure virtual
Method to set a global lane offset displacement from the center line.
Positive values imply a right offset while negative ones mean a left one.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetGlobalLaneOffset(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetGlobalPercentageSpeedDifference()
virtual void carla::traffic_manager::TrafficManagerBase::SetGlobalPercentageSpeedDifference (float const percentage) pure virtual
Set a global % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetGlobalPercentageSpeedDifference(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetHybridPhysicsMode()
virtual void carla::traffic_manager::TrafficManagerBase::SetHybridPhysicsMode (const bool mode_switch) pure virtual
Method to set hybrid physics mode.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetHybridPhysicsMode(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetHybridPhysicsRadius()
virtual void carla::traffic_manager::TrafficManagerBase::SetHybridPhysicsRadius (const float radius) pure virtual
Method to set hybrid physics radius.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetHybridPhysicsRadius(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetImportedRoute()
virtual void carla::traffic_manager::TrafficManagerBase::SetImportedRoute (const ActorPtr & actor, const Route route, const bool empty_buffer) pure virtual
Method to set our own imported route.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetImportedRoute(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetKeepRightPercentage()
virtual void carla::traffic_manager::TrafficManagerBase::SetKeepRightPercentage (const ActorPtr & actor, const float percentage) pure virtual
Method to set % to keep on the right lane.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetKeepRightPercentage(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetLaneOffset()
virtual void carla::traffic_manager::TrafficManagerBase::SetLaneOffset (const ActorPtr & actor, const float offset) pure virtual
Method to set a lane offset displacement from the center line.
Positive values imply a right offset while negative ones mean a left one.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetLaneOffset(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetMaxBoundaries()
virtual void carla::traffic_manager::TrafficManagerBase::SetMaxBoundaries (const float lower, const float upper) pure virtual
Method to set limits for boundaries when respawning vehicles.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetMaxBoundaries(), and ~TrafficManagerBase().
SetOSMMode()
virtual void carla::traffic_manager::TrafficManagerBase::SetOSMMode (const bool mode_switch) pure virtual
Method to set Open Street Map mode.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetOSMMode(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetPercentageIgnoreVehicles()
virtual void carla::traffic_manager::TrafficManagerBase::SetPercentageIgnoreVehicles (const ActorPtr & actor, const float perc) pure virtual
Method to specify the % chance of ignoring collisions with any vehicle.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetPercentageIgnoreVehicles(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetPercentageIgnoreWalkers()
virtual void carla::traffic_manager::TrafficManagerBase::SetPercentageIgnoreWalkers (const ActorPtr & actor, const float perc) pure virtual
Method to specify the % chance of ignoring collisions with any walker.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetPercentageIgnoreWalkers(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetPercentageRunningLight()
virtual void carla::traffic_manager::TrafficManagerBase::SetPercentageRunningLight (const ActorPtr & actor, const float perc) pure virtual
Method to specify the % chance of running any traffic light.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetPercentageRunningLight(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetPercentageRunningSign()
virtual void carla::traffic_manager::TrafficManagerBase::SetPercentageRunningSign (const ActorPtr & actor, const float perc) pure virtual
Method to specify the % chance of running any traffic sign.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetPercentageRunningSign(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetPercentageSpeedDifference()
virtual void carla::traffic_manager::TrafficManagerBase::SetPercentageSpeedDifference (const ActorPtr & actor, const float percentage) pure virtual
Set a vehicle's % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetPercentageSpeedDifference(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetRandomDeviceSeed()
virtual void carla::traffic_manager::TrafficManagerBase::SetRandomDeviceSeed (const uint64_t seed) pure virtual
Method to set randomization seed.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetRandomDeviceSeed(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetRandomLeftLaneChangePercentage()
virtual void carla::traffic_manager::TrafficManagerBase::SetRandomLeftLaneChangePercentage (const ActorPtr & actor, const float percentage) pure virtual
Method to set % to randomly do a left lane change.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetRandomLeftLaneChangePercentage(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetRandomRightLaneChangePercentage()
virtual void carla::traffic_manager::TrafficManagerBase::SetRandomRightLaneChangePercentage (const ActorPtr & actor, const float percentage) pure virtual
Method to set % to randomly do a right lane change.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetRandomRightLaneChangePercentage(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetRespawnDormantVehicles()
virtual void carla::traffic_manager::TrafficManagerBase::SetRespawnDormantVehicles (const bool mode_switch) pure virtual
Method to set automatic respawn of dormant vehicles.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetRespawnDormantVehicles(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetSynchronousMode()
virtual void carla::traffic_manager::TrafficManagerBase::SetSynchronousMode (bool mode) pure virtual
Method to switch traffic manager into synchronous execution.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetSynchronousMode(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetSynchronousModeTimeOutInMiliSecond()
virtual void carla::traffic_manager::TrafficManagerBase::SetSynchronousModeTimeOutInMiliSecond (double time) pure virtual
Method to set Tick timeout for synchronous execution.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetSynchronousModeTimeOutInMiliSecond(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
SetUpdateVehicleLights()
virtual void carla::traffic_manager::TrafficManagerBase::SetUpdateVehicleLights (const ActorPtr & actor, const bool do_update) pure virtual
Method to set the automatic management of the vehicle lights.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SetUpdateVehicleLights(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
ShutDown()
virtual void carla::traffic_manager::TrafficManagerBase::ShutDown () pure virtual
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::ShutDown(), and ~TrafficManagerBase().
Start()
virtual void carla::traffic_manager::TrafficManagerBase::Start () pure virtual
To start the traffic manager.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Stop()
virtual void carla::traffic_manager::TrafficManagerBase::Stop () pure virtual
To stop the traffic manager.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
SynchronousTick()
virtual bool carla::traffic_manager::TrafficManagerBase::SynchronousTick () pure virtual
Method to provide synchronous tick.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManager::SynchronousTick(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ~TrafficManagerBase().
UnregisterVehicles()
virtual void carla::traffic_manager::TrafficManagerBase::UnregisterVehicles (const std::vector< ActorPtr > & actor_list) pure virtual
This method unregisters a vehicle from traffic manager.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), carla::traffic_manager::TrafficManager::UnregisterVehicles(), and ~TrafficManagerBase().
UpdateImportedRoute()
virtual void carla::traffic_manager::TrafficManagerBase::UpdateImportedRoute (const ActorId & actor_id, const Route route) pure virtual
Method to update an already set route.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), carla::traffic_manager::TrafficManager::UpdateImportedRoute(), and ~TrafficManagerBase().
UpdateUploadPath()
virtual void carla::traffic_manager::TrafficManagerBase::UpdateUploadPath (const ActorId & actor_id, const Path path) pure virtual
Method to update an already set path.
Implemented in carla::traffic_manager::TrafficManagerLocal, and carla::traffic_manager::TrafficManagerRemote.
Referenced by carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), carla::traffic_manager::TrafficManager::UpdateUploadPath(), and ~TrafficManagerBase().
The documentation for this class was generated from the following file:
TrafficManagerBase.h