CARLA: AObstacleDetectionSensor Class Reference
AObstacleDetectionSensor Class Reference
A sensor to register collisions.
#include <ObstacleDetectionSensor.h>
Public Member Functions
AObstacleDetectionSensor (const FObjectInitializer &ObjectInitializer)
virtual void PostPhysTick (UWorld *World, ELevelTick TickType, float DeltaSeconds) override
void Set (const FActorDescription &Description) override
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
virtual void BeginPlay ()
boost::optional< FActorAttribute > GetAttribute (const FString Name)
const UCarlaEpisode & GetEpisode () const
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
bool IsStreamReady ()
FDataStream MoveDataStream ()
virtual void OnFirstClientConnected ()
virtual void OnLastClientDisconnected ()
void PostPhysTickInternal (UWorld *World, ELevelTick TickType, float DeltaSeconds)
virtual void PrePhysTick (float DeltaSeconds)
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
void Tick (const float DeltaTime) final
Static Public Member Functions
static FActorDefinition GetSensorDefinition ()
Private Member Functions
void OnObstacleDetectionEvent (AActor *Actor, AActor *OtherActor, float Distance, const FHitResult &Hit)
Private Attributes
bool bDebugLineTrace = false
bool bOnlyDynamics = false
float Distance
float HitRadius
Additional Inherited Members
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
void PostActorCreated () override
Protected Attributes inherited from ASensor
bool bIsActive = false
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Detailed Description
A sensor to register collisions.
Definition at line 18 of file ObstacleDetectionSensor.h.
Constructor & Destructor Documentation
AObstacleDetectionSensor()
AObstacleDetectionSensor::AObstacleDetectionSensor (const FObjectInitializer & ObjectInitializer)
Definition at line 20 of file ObstacleDetectionSensor.cpp.
Member Function Documentation
GetSensorDefinition()
FActorDefinition AObstacleDetectionSensor::GetSensorDefinition () static
Definition at line 26 of file ObstacleDetectionSensor.cpp.
References UActorBlueprintFunctionLibrary::MakeObstacleDetectorDefinitions().
OnObstacleDetectionEvent()
void AObstacleDetectionSensor::OnObstacleDetectionEvent (AActor * Actor, AActor * OtherActor, float Distance, const FHitResult & Hit) private
Definition at line 133 of file ObstacleDetectionSensor.cpp.
References ASensor::Episode, carla::streaming::detail::token_type::get_stream_id(), ASensor::GetDataStream(), ASensor::GetEpisode(), carla::ros2::ROS2::GetInstance(), ASensor::GetToken(), ASensor::IsStreamReady(), and UCarlaEpisode::SerializeActor().
Referenced by PostPhysTick().
PostPhysTick()
void AObstacleDetectionSensor::PostPhysTick (UWorld * World, ELevelTick TickType, float DeltaSeconds) override virtual
Reimplemented from ASensor.
Definition at line 57 of file ObstacleDetectionSensor.cpp.
References bDebugLineTrace, bOnlyDynamics, Distance, HitRadius, and OnObstacleDetectionEvent().
Set()
void AObstacleDetectionSensor::Set (const FActorDescription & Description) override virtual
Reimplemented from ASensor.
Definition at line 33 of file ObstacleDetectionSensor.cpp.
References bDebugLineTrace, bOnlyDynamics, Distance, HitRadius, UActorBlueprintFunctionLibrary::RetrieveActorAttributeToBool(), UActorBlueprintFunctionLibrary::RetrieveActorAttributeToFloat(), and FActorDescription::Variations.
Member Data Documentation
bDebugLineTrace
bool AObstacleDetectionSensor::bDebugLineTrace = false private
Definition at line 49 of file ObstacleDetectionSensor.h.
Referenced by PostPhysTick(), and Set().
bOnlyDynamics
bool AObstacleDetectionSensor::bOnlyDynamics = false private
Definition at line 47 of file ObstacleDetectionSensor.h.
Referenced by PostPhysTick(), and Set().
Distance
float AObstacleDetectionSensor::Distance private
Definition at line 43 of file ObstacleDetectionSensor.h.
Referenced by PostPhysTick(), and Set().
HitRadius
float AObstacleDetectionSensor::HitRadius private
Definition at line 45 of file ObstacleDetectionSensor.h.
Referenced by PostPhysTick(), and Set().
The documentation for this class was generated from the following files:
ObstacleDetectionSensor.h
ObstacleDetectionSensor.cpp