CARLA: CarlaRecorderHelpers.h File Reference
CarlaRecorderHelpers.h File Reference
#include <fstream>
#include <vector>
Functions
std::string GetRecorderFilename (std::string Filename)
void ReadFString (std::ifstream &InFile, FString &OutObj)
void ReadFVector (std::ifstream &InFile, FVector &OutObj)
template<typename T >
void ReadStdVector (std::ifstream &InFile, std::vector< T > &OutVec)
template<typename T >
void ReadTArray (std::ifstream &InFile, TArray< T > &OutVec)
template<typename T >
void ReadValue (std::ifstream &InFile, T &OutObj)
void WriteFString (std::ofstream &OutFile, const FString &InObj)
void WriteFVector (std::ofstream &OutFile, const FVector &InObj)
template<typename T >
void WriteStdVector (std::ofstream &OutFile, const std::vector< T > &InVec)
template<typename T >
void WriteTArray (std::ofstream &OutFile, const TArray< T > &InVec)
template<typename T >
void WriteValue (std::ofstream &OutFile, const T &InObj)
Function Documentation
GetRecorderFilename()
std::string GetRecorderFilename (std::string Filename)
Definition at line 16 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderQuery::QueryBlocked(), CarlaRecorderQuery::QueryCollisions(), CarlaRecorderQuery::QueryInfo(), CarlaReplayer::ReplayFile(), and ACarlaRecorder::Start().
ReadFString()
void ReadFString (std::ifstream & InFile, FString & OutObj)
Definition at line 83 of file CarlaRecorderHelpers.cpp.
References CarlaRecorderHelperBuffer.
Referenced by CarlaRecorderInfo::Read(), CarlaRecorderEventAdd::Read(), and ReadTArray().
ReadFVector()
void ReadFVector (std::ifstream & InFile, FVector & OutObj)
Definition at line 66 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderBoundingBox::Read(), CarlaRecorderPosition::Read(), CarlaRecorderKinematics::Read(), CarlaRecorderEventAdd::Read(), and ReadTArray().
ReadStdVector()
template<typename T > void ReadStdVector (std::ifstream & InFile, std::vector< T > & OutVec)
Definition at line 66 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Read().
ReadTArray()
template<typename T > void ReadTArray (std::ifstream & InFile, TArray< T > & OutVec)
Definition at line 80 of file CarlaRecorderHelpers.h.
References ReadFString(), and ReadFVector().
ReadValue()
template<typename T > void ReadValue (std::ifstream & InFile, T & OutObj)
Definition at line 60 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Read(), and CarlaRecorderTrafficLightTime::Read().
WriteFString()
void WriteFString (std::ofstream & OutFile, const FString & InObj)
Definition at line 51 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderInfo::Write(), CarlaRecorderEventAdd::Write(), and WriteTArray().
WriteFVector()
void WriteFVector (std::ofstream & OutFile, const FVector & InObj)
Definition at line 37 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderBoundingBox::Write(), CarlaRecorderPosition::Write(), CarlaRecorderKinematics::Write(), CarlaRecorderEventAdd::Write(), and WriteTArray().
WriteStdVector()
template<typename T > void WriteStdVector (std::ofstream & OutFile, const std::vector< T > & InVec)
Definition at line 27 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Write().
WriteTArray()
template<typename T > void WriteTArray (std::ofstream & OutFile, const TArray< T > & InVec)
Definition at line 37 of file CarlaRecorderHelpers.h.
References WriteFString(), and WriteFVector().
WriteValue()
template<typename T > void WriteValue (std::ofstream & OutFile, const T & InObj)
Definition at line 21 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Write(), and CarlaRecorderTrafficLightTime::Write().