CARLA: UChronoMovementComponent Class Reference
UChronoMovementComponent Class Reference
#include <ChronoMovementComponent.h>
Static Public Member Functions
static void CreateChronoMovementComponent (ACarlaWheeledVehicle *Vehicle, uint64_t MaxSubsteps, float MaxSubstepDeltaTime, FString VehicleJSON="", FString PowertrainJSON="", FString TireJSON="", FString BaseJSONPath="")
Private Member Functions
void DisableChronoPhysics ()
void OnVehicleHit (AActor *Actor, AActor *OtherActor, FVector NormalImpulse, const FHitResult &Hit)
void OnVehicleOverlap (UPrimitiveComponent *OverlappedComponent, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)
Private Attributes
FString BaseJSONPath = ""
float MaxSubstepDeltaTime = 0.01
uint64_t MaxSubsteps = 10
FString PowertrainJSON = "hmmwv/powertrain/HMMWV_ShaftsPowertrain.json"
FString TireJSON = "hmmwv/tire/HMMWV_Pac02Tire.json"
FVehicleControl VehicleControl
FString VehicleJSON = "hmmwv/vehicle/HMMWV_Vehicle.json"
Additional Inherited Members
Public Member Functions inherited from UBaseCarlaMovementComponent
virtual void BeginPlay () override
virtual int32 GetVehicleCurrentGear () const
virtual float GetVehicleForwardSpeed () const
virtual FVector GetVelocity () const
virtual void ProcessControl (FVehicleControl &Control)
Protected Member Functions inherited from UBaseCarlaMovementComponent
void DisableUE4VehiclePhysics ()
void EnableUE4VehiclePhysics (bool bResetVelocity=true)
Protected Attributes inherited from UBaseCarlaMovementComponent
ACarlaWheeledVehicle * CarlaVehicle
Detailed Description
Definition at line 43 of file ChronoMovementComponent.h.
Member Function Documentation
CreateChronoMovementComponent()
void UChronoMovementComponent::CreateChronoMovementComponent (ACarlaWheeledVehicle * Vehicle, uint64_t MaxSubsteps, float MaxSubstepDeltaTime, FString VehicleJSON = "", FString PowertrainJSON = "", FString TireJSON = "", FString BaseJSONPath = "") static
Definition at line 21 of file ChronoMovementComponent.cpp.
References BaseJSONPath, UBaseCarlaMovementComponent::BeginPlay(), FVehicleControl::bHandBrake, FVehicleControl::Brake, FVehicleControl::bReverse, UBaseCarlaMovementComponent::CarlaVehicle, ACarlaWheeledVehicle::Control, UDefaultMovementComponent::CreateDefaultMovementComponent(), UBaseCarlaMovementComponent::DisableUE4VehiclePhysics(), UBaseCarlaMovementComponent::GetVehicleCurrentGear(), UBaseCarlaMovementComponent::GetVehicleForwardSpeed(), UBaseCarlaMovementComponent::GetVelocity(), MaxSubstepDeltaTime, MaxSubsteps, OnVehicleHit(), OnVehicleOverlap(), PowertrainJSON, UBaseCarlaMovementComponent::ProcessControl(), ACarlaWheeledVehicle::SetCarlaMovementComponent(), FVehicleControl::Steer, FVehicleControl::Throttle, TireJSON, Vehicle, VehicleControl, and VehicleJSON.
Referenced by FVehicleActor::EnableChronoPhysics().
DisableChronoPhysics()
void UChronoMovementComponent::DisableChronoPhysics () private
Definition at line 351 of file ChronoMovementComponent.cpp.
References UBaseCarlaMovementComponent::CarlaVehicle, UDefaultMovementComponent::CreateDefaultMovementComponent(), UBaseCarlaMovementComponent::EnableUE4VehiclePhysics(), carla::log_warning(), OnVehicleHit(), and OnVehicleOverlap().
Referenced by OnVehicleHit(), and OnVehicleOverlap().
OnVehicleHit()
void UChronoMovementComponent::OnVehicleHit (AActor * Actor, AActor * OtherActor, FVector NormalImpulse, const FHitResult & Hit) private
Definition at line 364 of file ChronoMovementComponent.cpp.
References DisableChronoPhysics().
Referenced by CreateChronoMovementComponent(), and DisableChronoPhysics().
OnVehicleOverlap()
void UChronoMovementComponent::OnVehicleOverlap (UPrimitiveComponent * OverlappedComponent, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) private
Definition at line 374 of file ChronoMovementComponent.cpp.
References DisableChronoPhysics().
Referenced by CreateChronoMovementComponent(), and DisableChronoPhysics().
Member Data Documentation
BaseJSONPath
FString UChronoMovementComponent::BaseJSONPath = "" private
Definition at line 59 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
MaxSubstepDeltaTime
float UChronoMovementComponent::MaxSubstepDeltaTime = 0.01 private
Definition at line 54 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
MaxSubsteps
uint64_t UChronoMovementComponent::MaxSubsteps = 10 private
Definition at line 53 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
PowertrainJSON
FString UChronoMovementComponent::PowertrainJSON = "hmmwv/powertrain/HMMWV_ShaftsPowertrain.json" private
Definition at line 57 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
TireJSON
FString UChronoMovementComponent::TireJSON = "hmmwv/tire/HMMWV_Pac02Tire.json" private
Definition at line 58 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
VehicleControl
FVehicleControl UChronoMovementComponent::VehicleControl private
Definition at line 55 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
VehicleJSON
FString UChronoMovementComponent::VehicleJSON = "hmmwv/vehicle/HMMWV_Vehicle.json" private
Definition at line 56 of file ChronoMovementComponent.h.
Referenced by CreateChronoMovementComponent().
The documentation for this class was generated from the following files:
ChronoMovementComponent.h
ChronoMovementComponent.cpp