CARLA: test_recurrent_shared_future.cpp File Reference
test_recurrent_shared_future.cpp File Reference
#include "test.h"
#include <carla/RecurrentSharedFuture.h>
#include <carla/ThreadGroup.h>
Functions
TEST (recurrent_shared_future, use_case)
TEST (recurrent_shared_future, timeout)
TEST (recurrent_shared_future, exception)
Function Documentation
TEST() [1/3]
TEST (recurrent_shared_future , use_case)
Definition at line 14 of file test_recurrent_shared_future.cpp.
References carla::ThreadGroup::CreateThreads(), carla::ThreadGroup::JoinAll(), carla::RecurrentSharedFuture< T >::SetValue(), and carla::RecurrentSharedFuture< T >::WaitFor().
TEST() [2/3]
TEST (recurrent_shared_future , timeout)
Definition at line 45 of file test_recurrent_shared_future.cpp.
References carla::RecurrentSharedFuture< T >::WaitFor().
TEST() [3/3]
TEST (recurrent_shared_future , exception)
Definition at line 52 of file test_recurrent_shared_future.cpp.
References carla::ThreadGroup::CreateThread(), carla::RecurrentSharedFuture< T >::SetException(), and carla::RecurrentSharedFuture< T >::WaitFor().