CARLA: ASceneCaptureSensor Class Reference
ASceneCaptureSensor Class Reference
Base class for sensors using a USceneCaptureComponent2D for rendering the scene.
#include <SceneCaptureSensor.h>
Public Member Functions
bool ArePostProcessingEffectsEnabled () const
ASceneCaptureSensor (const FObjectInitializer &ObjectInitializer)
void Enable16BitFormat (bool Enable=false)
void EnablePostProcessingEffects (bool Enable=true)
void EnqueueRenderSceneImmediate ()
Immediate enqueues render commands of the scene at the current time.
float GetAperture () const
int GetBladeCount () const
float GetBloomIntensity () const
USceneCaptureComponent2D * GetCaptureComponent2D ()
UTextureRenderTarget2D * GetCaptureRenderTarget ()
float GetChromAberrIntensity () const
float GetChromAberrOffset () const
float GetDepthBlurAmount () const
float GetDepthBlurRadius () const
float GetDepthOfFieldMinFstop () const
float GetExposureCalibrationConstant () const
float GetExposureCompensation () const
float GetExposureMaxBrightness () const
EAutoExposureMethod GetExposureMethod () const
float GetExposureMinBrightness () const
float GetExposureSpeedDown () const
float GetExposureSpeedUp () const
float GetFilmBlackClip () const
float GetFilmShoulder () const
float GetFilmSlope () const
float GetFilmToe () const
float GetFilmWhiteClip () const
float GetFocalDistance () const
float GetFOVAngle () const
uint32 GetImageHeight () const
uint32 GetImageWidth () const
float GetISO () const
float GetLensFlareIntensity () const
float GetMotionBlurIntensity () const
float GetMotionBlurMaxDistortion () const
float GetMotionBlurMinObjectScreenSize () const
float GetShutterSpeed () const
float GetTargetGamma () const
float GetWhiteTemp () const
float GetWhiteTint () const
bool Is16BitFormatEnabled () const
bool ReadPixels (TArray< FColor > &BitMap) const
Use for debugging purposes only.
void SaveCaptureToDisk (const FString &FilePath) const
Use for debugging purposes only.
void Set (const FActorDescription &ActorDescription) override
void SetAperture (float Aperture)
void SetBladeCount (int Count)
void SetBloomIntensity (float Intensity)
void SetChromAberrIntensity (float Intensity)
void SetChromAberrOffset (float ChromAberrOffset)
void SetDepthBlurAmount (float Amount)
void SetDepthBlurRadius (float Radius)
void SetDepthOfFieldMinFstop (float MinFstop)
void SetExposureCalibrationConstant (float Constant)
void SetExposureCompensation (float Compensation)
void SetExposureMaxBrightness (float Brightness)
void SetExposureMethod (EAutoExposureMethod Method)
void SetExposureMinBrightness (float Brightness)
void SetExposureSpeedDown (float Speed)
void SetExposureSpeedUp (float Speed)
void SetFilmBlackClip (float BlackClip)
void SetFilmShoulder (float Shoulder)
void SetFilmSlope (float Slope)
void SetFilmToe (float Toe)
void SetFilmWhiteClip (float WhiteClip)
void SetFocalDistance (float Distance)
void SetFOVAngle (float FOVAngle)
void SetImageSize (uint32 Width, uint32 Height)
void SetISO (float ISO)
void SetLensFlareIntensity (float Intensity)
void SetMotionBlurIntensity (float Intensity)
void SetMotionBlurMaxDistortion (float MaxDistortion)
void SetMotionBlurMinObjectScreenSize (float ScreenSize)
void SetShutterSpeed (float Speed)
void SetTargetGamma (float InTargetGamma)
void SetWhiteTemp (float Temp)
void SetWhiteTint (float Tint)
void WaitForRenderThreadToFinish ()
Blocks until the render thread has finished all it's tasks.
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
const UCarlaEpisode & GetEpisode () const
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
FDataStream MoveDataStream ()
virtual void OnFirstClientConnected ()
virtual void OnLastClientDisconnected ()
void PostPhysTickInternal (UWorld *World, ELevelTick TickType, float DeltaSeconds)
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
void Tick (const float DeltaTime) final
Public Attributes
struct {
FCameraGBufferUint8 CustomDepth
FCameraGBufferUint8 CustomStencil
FCameraGBufferUint8 GBufferA
FCameraGBufferUint8 GBufferB
FCameraGBufferUint8 GBufferC
FCameraGBufferUint8 GBufferD
FCameraGBufferUint8 GBufferE
FCameraGBufferUint8 GBufferF
FCameraGBufferUint8 SceneColor
FCameraGBufferUint8 SceneDepth
FCameraGBufferUint8 SceneStencil
FCameraGBufferUint8 SSAO
FCameraGBufferUint8 Velocity
} CameraGBuffers
Protected Member Functions
virtual void BeginPlay () override
void CaptureSceneExtended ()
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
virtual void PostPhysTick (UWorld *World, ELevelTick TickType, float DeltaTime) override
virtual void PrePhysTick (float DeltaSeconds) override
virtual void SendGBufferTextures (FGBufferRequest &GBuffer)
template<typename T >
void SendGBufferTexturesInternal (T &Self, FGBufferRequest &GBufferData)
virtual void SetUpSceneCaptureComponent (USceneCaptureComponent2D &SceneCapture)
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
void PostActorCreated () override
Protected Attributes
bool bEnable16BitFormat = false
Whether to change render target format to PF_A16B16G16R16, offering 16bit / channel.
bool bEnablePostProcessingEffects = true
Whether to render the post-processing effects present in the scene.
USceneCaptureComponent2D_CARLA * CaptureComponent2D = nullptr
Scene capture component.
UTextureRenderTarget2D * CaptureRenderTarget = nullptr
Render target necessary for scene capture.
uint32 ImageHeight = 600u
Image height in pixels.
uint32 ImageWidth = 800u
Image width in pixels.
float TargetGamma = 2.4f
Protected Attributes inherited from ASensor
bool bIsActive = false
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Static Private Member Functions
template<typename SensorT , typename CameraGBufferT >
static void SendGBuffer (SensorT &Self, CameraGBufferT &CameraGBuffer, FGBufferRequest &GBufferData, EGBufferTextureID TextureID)
Friends
class ACarlaGameModeBase
class FPixelReader
class FPixelReader2
Detailed Description
Base class for sensors using a USceneCaptureComponent2D for rendering the scene.
This class does not capture data, use FPixelReader::SendPixelsInRenderThread(*this) in derived classes.
To access the USceneCaptureComponent2D override the SetUpSceneCaptureComponent function.
Warning
All the setters should be called before BeginPlay.
Definition at line 126 of file SceneCaptureSensor.h.
Constructor & Destructor Documentation
ASceneCaptureSensor()
ASceneCaptureSensor::ASceneCaptureSensor (const FObjectInitializer & ObjectInitializer)
Definition at line 41 of file SceneCaptureSensor.cpp.
References CaptureComponent2D, CaptureRenderTarget, SCENE_CAPTURE_COUNTER, SceneCaptureSensor_local_ns::SetCameraDefaultOverrides(), and USceneCaptureComponent2D_CARLA::ViewActor.
Member Function Documentation
ArePostProcessingEffectsEnabled()
bool ASceneCaptureSensor::ArePostProcessingEffectsEnabled () const inline
Definition at line 159 of file SceneCaptureSensor.h.
BeginPlay()
void ASceneCaptureSensor::BeginPlay () override protected virtual
Reimplemented from ASensor.
Reimplemented in ASceneCaptureCamera.
Definition at line 543 of file SceneCaptureSensor.cpp.
References bEnable16BitFormat, bEnablePostProcessingEffects, CaptureComponent2D, CaptureRenderTarget, SceneCaptureSensor_local_ns::ConfigureShowFlags(), ASensor::GetEpisode(), UCarlaEpisode::GetWeather(), ImageHeight, ImageWidth, IsValid(), AWeather::NotifyWeather(), SetUpSceneCaptureComponent(), and TargetGamma.
CaptureSceneExtended()
void ASceneCaptureSensor::CaptureSceneExtended () protected
Definition at line 482 of file SceneCaptureSensor.cpp.
References CameraGBuffers, CaptureComponent2D, USceneCaptureComponent2D_CARLA::GetViewOwner(), Prior, and SendGBufferTextures().
Referenced by EnqueueRenderSceneImmediate().
Enable16BitFormat()
void ASceneCaptureSensor::Enable16BitFormat (bool Enable = false) inline
Definition at line 165 of file SceneCaptureSensor.h.
Referenced by ANormalsCamera::ANormalsCamera(), and AOpticalFlowCamera::AOpticalFlowCamera().
EnablePostProcessingEffects()
void ASceneCaptureSensor::EnablePostProcessingEffects (bool Enable = true) inline
Definition at line 153 of file SceneCaptureSensor.h.
Referenced by ADVSCamera::ADVSCamera(), and UActorBlueprintFunctionLibrary::SetCamera().
EndPlay()
void ASceneCaptureSensor::EndPlay (const EEndPlayReason::Type EndPlayReason) override protected virtual
Reimplemented in ASceneCaptureCamera.
Definition at line 603 of file SceneCaptureSensor.cpp.
References SCENE_CAPTURE_COUNTER.
EnqueueRenderSceneImmediate()
void ASceneCaptureSensor::EnqueueRenderSceneImmediate ()
Immediate enqueues render commands of the scene at the current time.
Definition at line 449 of file SceneCaptureSensor.cpp.
References CaptureSceneExtended().
Referenced by ADVSCamera::PostPhysTick().
GetAperture()
float ASceneCaptureSensor::GetAperture () const
Definition at line 155 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetBladeCount()
int ASceneCaptureSensor::GetBladeCount () const
Definition at line 215 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetBloomIntensity()
float ASceneCaptureSensor::GetBloomIntensity () const
Definition at line 395 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetCaptureComponent2D()
USceneCaptureComponent2D* ASceneCaptureSensor::GetCaptureComponent2D () inline
Definition at line 385 of file SceneCaptureSensor.h.
Referenced by AInstanceSegmentationCamera::PostPhysTick().
GetCaptureRenderTarget()
UTextureRenderTarget2D* ASceneCaptureSensor::GetCaptureRenderTarget () inline
Definition at line 391 of file SceneCaptureSensor.h.
GetChromAberrIntensity()
float ASceneCaptureSensor::GetChromAberrIntensity () const
Definition at line 431 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetChromAberrOffset()
float ASceneCaptureSensor::GetChromAberrOffset () const
Definition at line 443 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetDepthBlurAmount()
float ASceneCaptureSensor::GetDepthBlurAmount () const
Definition at line 179 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetDepthBlurRadius()
float ASceneCaptureSensor::GetDepthBlurRadius () const
Definition at line 191 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetDepthOfFieldMinFstop()
float ASceneCaptureSensor::GetDepthOfFieldMinFstop () const
Definition at line 203 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureCalibrationConstant()
float ASceneCaptureSensor::GetExposureCalibrationConstant () const
Definition at line 335 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureCompensation()
float ASceneCaptureSensor::GetExposureCompensation () const
Definition at line 119 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureMaxBrightness()
float ASceneCaptureSensor::GetExposureMaxBrightness () const
Definition at line 299 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureMethod()
EAutoExposureMethod ASceneCaptureSensor::GetExposureMethod () const
Definition at line 101 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureMinBrightness()
float ASceneCaptureSensor::GetExposureMinBrightness () const
Definition at line 287 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureSpeedDown()
float ASceneCaptureSensor::GetExposureSpeedDown () const
Definition at line 311 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetExposureSpeedUp()
float ASceneCaptureSensor::GetExposureSpeedUp () const
Definition at line 323 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFilmBlackClip()
float ASceneCaptureSensor::GetFilmBlackClip () const
Definition at line 263 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFilmShoulder()
float ASceneCaptureSensor::GetFilmShoulder () const
Definition at line 251 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFilmSlope()
float ASceneCaptureSensor::GetFilmSlope () const
Definition at line 227 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFilmToe()
float ASceneCaptureSensor::GetFilmToe () const
Definition at line 239 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFilmWhiteClip()
float ASceneCaptureSensor::GetFilmWhiteClip () const
Definition at line 275 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFocalDistance()
float ASceneCaptureSensor::GetFocalDistance () const
Definition at line 167 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetFOVAngle()
float ASceneCaptureSensor::GetFOVAngle () const
Definition at line 89 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetImageHeight()
uint32 ASceneCaptureSensor::GetImageHeight () const inline
Definition at line 147 of file SceneCaptureSensor.h.
Referenced by ADVSCamera::ImageToGray(), ADVSCamera::ImageToLogGray(), and ADVSCamera::Simulation().
GetImageWidth()
uint32 ASceneCaptureSensor::GetImageWidth () const inline
Definition at line 142 of file SceneCaptureSensor.h.
Referenced by ADVSCamera::ImageToGray(), ADVSCamera::ImageToLogGray(), and ADVSCamera::Simulation().
GetISO()
float ASceneCaptureSensor::GetISO () const
Definition at line 143 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetLensFlareIntensity()
float ASceneCaptureSensor::GetLensFlareIntensity () const
Definition at line 383 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetMotionBlurIntensity()
float ASceneCaptureSensor::GetMotionBlurIntensity () const
Definition at line 347 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetMotionBlurMaxDistortion()
float ASceneCaptureSensor::GetMotionBlurMaxDistortion () const
Definition at line 359 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetMotionBlurMinObjectScreenSize()
float ASceneCaptureSensor::GetMotionBlurMinObjectScreenSize () const
Definition at line 371 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetShutterSpeed()
float ASceneCaptureSensor::GetShutterSpeed () const
Definition at line 131 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetTargetGamma()
float ASceneCaptureSensor::GetTargetGamma () const inline
Definition at line 189 of file SceneCaptureSensor.h.
GetWhiteTemp()
float ASceneCaptureSensor::GetWhiteTemp () const
Definition at line 407 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
GetWhiteTint()
float ASceneCaptureSensor::GetWhiteTint () const
Definition at line 419 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Is16BitFormatEnabled()
bool ASceneCaptureSensor::Is16BitFormatEnabled () const inline
Definition at line 171 of file SceneCaptureSensor.h.
PostPhysTick()
void ASceneCaptureSensor::PostPhysTick (UWorld * World, ELevelTick TickType, float DeltaTime) override protected virtual
Reimplemented from ASensor.
Reimplemented in ADVSCamera, ASceneCaptureCamera, AInstanceSegmentationCamera, ADepthCamera, ANormalsCamera, ASemanticSegmentationCamera, and AOpticalFlowCamera.
Definition at line 598 of file SceneCaptureSensor.cpp.
PrePhysTick()
void ASceneCaptureSensor::PrePhysTick (float DeltaSeconds) override protected virtual
Reimplemented from ASensor.
Definition at line 586 of file SceneCaptureSensor.cpp.
References CaptureComponent2D, carla::client::detail::Get(), and ImageWidth.
ReadPixels()
bool ASceneCaptureSensor::ReadPixels (TArray< FColor > & BitMap) const inline
Use for debugging purposes only.
Definition at line 370 of file SceneCaptureSensor.h.
References FPixelReader::WritePixelsToArray().
Referenced by ADVSCamera::PostPhysTick().
SaveCaptureToDisk()
void ASceneCaptureSensor::SaveCaptureToDisk (const FString & FilePath) const inline
Use for debugging purposes only.
Definition at line 378 of file SceneCaptureSensor.h.
References FPixelReader::SavePixelsToDisk().
SendGBuffer()
template<typename SensorT , typename CameraGBufferT > static void ASceneCaptureSensor::SendGBuffer (SensorT & Self, CameraGBufferT & CameraGBuffer, FGBufferRequest & GBufferData, EGBufferTextureID TextureID) inline static private
Definition at line 469 of file SceneCaptureSensor.h.
References ImageUtil::DecodePixelsByFormat().
SendGBufferTextures()
void ASceneCaptureSensor::SendGBufferTextures (FGBufferRequest & GBuffer) protected virtual
Reimplemented in ASceneCaptureCamera.
Definition at line 538 of file SceneCaptureSensor.cpp.
References SendGBufferTexturesInternal().
Referenced by CaptureSceneExtended().
SendGBufferTexturesInternal()
template<typename T > void ASceneCaptureSensor::SendGBufferTexturesInternal (T & Self, FGBufferRequest & GBufferData) inline protected
Definition at line 535 of file SceneCaptureSensor.h.
Referenced by ASceneCaptureCamera::SendGBufferTextures(), and SendGBufferTextures().
Set()
void ASceneCaptureSensor::Set (const FActorDescription & ActorDescription) override virtual
Reimplemented from ASensor.
Reimplemented in AShaderBasedSensor.
Definition at line 71 of file SceneCaptureSensor.cpp.
References UActorBlueprintFunctionLibrary::SetCamera().
SetAperture()
void ASceneCaptureSensor::SetAperture (float Aperture)
Definition at line 149 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetBladeCount()
void ASceneCaptureSensor::SetBladeCount (int Count)
Definition at line 209 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetBloomIntensity()
void ASceneCaptureSensor::SetBloomIntensity (float Intensity)
Definition at line 389 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetChromAberrIntensity()
void ASceneCaptureSensor::SetChromAberrIntensity (float Intensity)
Definition at line 425 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetChromAberrOffset()
void ASceneCaptureSensor::SetChromAberrOffset (float ChromAberrOffset)
Definition at line 437 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetDepthBlurAmount()
void ASceneCaptureSensor::SetDepthBlurAmount (float Amount)
Definition at line 173 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetDepthBlurRadius()
void ASceneCaptureSensor::SetDepthBlurRadius (float Radius)
Definition at line 185 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetDepthOfFieldMinFstop()
void ASceneCaptureSensor::SetDepthOfFieldMinFstop (float MinFstop)
Definition at line 197 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureCalibrationConstant()
void ASceneCaptureSensor::SetExposureCalibrationConstant (float Constant)
Definition at line 329 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureCompensation()
void ASceneCaptureSensor::SetExposureCompensation (float Compensation)
Definition at line 107 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureMaxBrightness()
void ASceneCaptureSensor::SetExposureMaxBrightness (float Brightness)
Definition at line 293 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureMethod()
void ASceneCaptureSensor::SetExposureMethod (EAutoExposureMethod Method)
Definition at line 95 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureMinBrightness()
void ASceneCaptureSensor::SetExposureMinBrightness (float Brightness)
Definition at line 281 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureSpeedDown()
void ASceneCaptureSensor::SetExposureSpeedDown (float Speed)
Definition at line 305 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetExposureSpeedUp()
void ASceneCaptureSensor::SetExposureSpeedUp (float Speed)
Definition at line 317 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFilmBlackClip()
void ASceneCaptureSensor::SetFilmBlackClip (float BlackClip)
Definition at line 257 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFilmShoulder()
void ASceneCaptureSensor::SetFilmShoulder (float Shoulder)
Definition at line 245 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFilmSlope()
void ASceneCaptureSensor::SetFilmSlope (float Slope)
Definition at line 221 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFilmToe()
void ASceneCaptureSensor::SetFilmToe (float Toe)
Definition at line 233 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFilmWhiteClip()
void ASceneCaptureSensor::SetFilmWhiteClip (float WhiteClip)
Definition at line 269 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFocalDistance()
void ASceneCaptureSensor::SetFocalDistance (float Distance)
Definition at line 161 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetFOVAngle()
void ASceneCaptureSensor::SetFOVAngle (float FOVAngle)
Definition at line 83 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetImageSize()
void ASceneCaptureSensor::SetImageSize (uint32 Width, uint32 Height)
Definition at line 77 of file SceneCaptureSensor.cpp.
References ImageHeight, and ImageWidth.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetISO()
void ASceneCaptureSensor::SetISO (float ISO)
Definition at line 137 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetLensFlareIntensity()
void ASceneCaptureSensor::SetLensFlareIntensity (float Intensity)
Definition at line 377 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetMotionBlurIntensity()
void ASceneCaptureSensor::SetMotionBlurIntensity (float Intensity)
Definition at line 341 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetMotionBlurMaxDistortion()
void ASceneCaptureSensor::SetMotionBlurMaxDistortion (float MaxDistortion)
Definition at line 353 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetMotionBlurMinObjectScreenSize()
void ASceneCaptureSensor::SetMotionBlurMinObjectScreenSize (float ScreenSize)
Definition at line 365 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetShutterSpeed()
void ASceneCaptureSensor::SetShutterSpeed (float Speed)
Definition at line 125 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetTargetGamma()
void ASceneCaptureSensor::SetTargetGamma (float InTargetGamma) inline
Definition at line 183 of file SceneCaptureSensor.h.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetUpSceneCaptureComponent()
virtual void ASceneCaptureSensor::SetUpSceneCaptureComponent (USceneCaptureComponent2D & SceneCapture) inline protected virtual
Reimplemented in AShaderBasedSensor, and AInstanceSegmentationCamera.
Definition at line 435 of file SceneCaptureSensor.h.
Referenced by BeginPlay().
SetWhiteTemp()
void ASceneCaptureSensor::SetWhiteTemp (float Temp)
Definition at line 401 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
SetWhiteTint()
void ASceneCaptureSensor::SetWhiteTint (float Tint)
Definition at line 413 of file SceneCaptureSensor.cpp.
References CaptureComponent2D.
Referenced by UActorBlueprintFunctionLibrary::SetCamera().
WaitForRenderThreadToFinish()
void ASceneCaptureSensor::WaitForRenderThreadToFinish () inline
Blocks until the render thread has finished all it's tasks.
Definition at line 400 of file SceneCaptureSensor.h.
Referenced by ADVSCamera::PostPhysTick().
Friends And Related Function Documentation
ACarlaGameModeBase
friend class ACarlaGameModeBase friend
Definition at line 130 of file SceneCaptureSensor.h.
FPixelReader
friend class FPixelReader friend
Definition at line 131 of file SceneCaptureSensor.h.
FPixelReader2
friend class FPixelReader2 friend
Definition at line 132 of file SceneCaptureSensor.h.
Member Data Documentation
bEnable16BitFormat
bool ASceneCaptureSensor::bEnable16BitFormat = false protected
Whether to change render target format to PF_A16B16G16R16, offering 16bit / channel.
Definition at line 462 of file SceneCaptureSensor.h.
Referenced by BeginPlay().
bEnablePostProcessingEffects
bool ASceneCaptureSensor::bEnablePostProcessingEffects = true protected
Whether to render the post-processing effects present in the scene.
Definition at line 458 of file SceneCaptureSensor.h.
Referenced by BeginPlay().
CameraGBuffers
struct { ... } ASceneCaptureSensor::CameraGBuffers
Referenced by FCarlaServer::FPimpl::BindActions(), CaptureSceneExtended(), and ASensorFactory::SpawnActor().
CaptureComponent2D
USceneCaptureComponent2D_CARLA* ASceneCaptureSensor::CaptureComponent2D = nullptr protected
Scene capture component.
Definition at line 443 of file SceneCaptureSensor.h.
Referenced by ASceneCaptureSensor(), BeginPlay(), CaptureSceneExtended(), GetAperture(), GetBladeCount(), GetBloomIntensity(), GetChromAberrIntensity(), GetChromAberrOffset(), GetDepthBlurAmount(), GetDepthBlurRadius(), GetDepthOfFieldMinFstop(), GetExposureCalibrationConstant(), GetExposureCompensation(), GetExposureMaxBrightness(), GetExposureMethod(), GetExposureMinBrightness(), GetExposureSpeedDown(), GetExposureSpeedUp(), GetFilmBlackClip(), GetFilmShoulder(), GetFilmSlope(), GetFilmToe(), GetFilmWhiteClip(), GetFocalDistance(), GetFOVAngle(), GetISO(), GetLensFlareIntensity(), GetMotionBlurIntensity(), GetMotionBlurMaxDistortion(), GetMotionBlurMinObjectScreenSize(), GetShutterSpeed(), GetWhiteTemp(), GetWhiteTint(), PrePhysTick(), SetAperture(), SetBladeCount(), SetBloomIntensity(), SetChromAberrIntensity(), SetChromAberrOffset(), SetDepthBlurAmount(), SetDepthBlurRadius(), SetDepthOfFieldMinFstop(), SetExposureCalibrationConstant(), SetExposureCompensation(), SetExposureMaxBrightness(), SetExposureMethod(), SetExposureMinBrightness(), SetExposureSpeedDown(), SetExposureSpeedUp(), SetFilmBlackClip(), SetFilmShoulder(), SetFilmSlope(), SetFilmToe(), SetFilmWhiteClip(), SetFocalDistance(), SetFOVAngle(), SetISO(), SetLensFlareIntensity(), SetMotionBlurIntensity(), SetMotionBlurMaxDistortion(), SetMotionBlurMinObjectScreenSize(), SetShutterSpeed(), SetWhiteTemp(), and SetWhiteTint().
CaptureRenderTarget
UTextureRenderTarget2D* ASceneCaptureSensor::CaptureRenderTarget = nullptr protected
Render target necessary for scene capture.
Definition at line 439 of file SceneCaptureSensor.h.
Referenced by ASceneCaptureSensor(), BeginPlay(), and ADVSCamera::PostPhysTick().
CustomDepth
FCameraGBufferUint8 ASceneCaptureSensor::CustomDepth
Definition at line 418 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
CustomStencil
FCameraGBufferUint8 ASceneCaptureSensor::CustomStencil
Definition at line 419 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
GBufferA
FCameraGBufferUint8 ASceneCaptureSensor::GBufferA
Definition at line 410 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
GBufferB
FCameraGBufferUint8 ASceneCaptureSensor::GBufferB
Definition at line 411 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
GBufferC
FCameraGBufferUint8 ASceneCaptureSensor::GBufferC
Definition at line 412 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
GBufferD
FCameraGBufferUint8 ASceneCaptureSensor::GBufferD
Definition at line 413 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
GBufferE
FCameraGBufferUint8 ASceneCaptureSensor::GBufferE
Definition at line 414 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
GBufferF
FCameraGBufferUint8 ASceneCaptureSensor::GBufferF
Definition at line 415 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
ImageHeight
uint32 ASceneCaptureSensor::ImageHeight = 600u protected
Image height in pixels.
Definition at line 454 of file SceneCaptureSensor.h.
Referenced by BeginPlay(), and SetImageSize().
ImageWidth
uint32 ASceneCaptureSensor::ImageWidth = 800u protected
Image width in pixels.
Definition at line 450 of file SceneCaptureSensor.h.
Referenced by BeginPlay(), PrePhysTick(), and SetImageSize().
SceneColor
FCameraGBufferUint8 ASceneCaptureSensor::SceneColor
Definition at line 407 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
SceneDepth
FCameraGBufferUint8 ASceneCaptureSensor::SceneDepth
Definition at line 408 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
SceneStencil
FCameraGBufferUint8 ASceneCaptureSensor::SceneStencil
Definition at line 409 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
SSAO
FCameraGBufferUint8 ASceneCaptureSensor::SSAO
Definition at line 417 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
TargetGamma
float ASceneCaptureSensor::TargetGamma = 2.4f protected
Definition at line 446 of file SceneCaptureSensor.h.
Referenced by BeginPlay().
Velocity
FCameraGBufferUint8 ASceneCaptureSensor::Velocity
Definition at line 416 of file SceneCaptureSensor.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and ASensorFactory::SpawnActor().
The documentation for this class was generated from the following files:
SceneCaptureSensor.h
SceneCaptureSensor.cpp