CARLA: fresnel.h File Reference
fresnel.h File Reference
Functions
int fresnl (double xxa, double *ssa, double *cca)
Function Documentation
int fresnl (double xxa, double * ssa, double * cca)
Definition at line 158 of file fresnl.cpp.
References cd, cn, fd, fn, FULL_PI_FRESNEL, gd, gn, HALF_PI_FRESNEL, p1evl(), polevl(), sd, and sn.
Referenced by carla::road::element::GeometrySpiral::PosFromDist().