CARLA: TrafficLightManager.cpp File Reference
TrafficLightManager.cpp File Reference
#include "TrafficLightManager.h"
#include "Game/CarlaStatics.h"
#include "StopSignComponent.h"
#include "YieldSignComponent.h"
#include "SpeedLimitComponent.h"
#include "Components/BoxComponent.h"
#include "Runtime/CoreUObject/Public/UObject/ConstructorHelpers.h"
#include "UObject/ConstructorHelpers.h"
#include <compiler/disable-ue4-macros.h>
#include <carla/rpc/String.h>
#include <carla/road/SignalType.h>
#include <carla/opendrive/OpenDriveParser.h>
#include <compiler/enable-ue4-macros.h>
#include <string>
Functions
template<typename T = ATrafficSignBase>
T * GetClosestTrafficSignActor (const carla::road::Signal &Signal, UWorld *World)
bool MatchSignalAndActor (const carla::road::Signal &Signal, ATrafficSignBase *ClosestTrafficSign)
Function Documentation
GetClosestTrafficSignActor()
template<typename T = ATrafficSignBase> T* GetClosestTrafficSignActor (const carla::road::Signal & Signal, UWorld * World)
Definition at line 458 of file TrafficLightManager.cpp.
References carla::road::Signal::GetTransform(), and MatchSignalAndActor().
Referenced by ATrafficLightManager::SpawnSignals().
MatchSignalAndActor()
bool MatchSignalAndActor (const carla::road::Signal & Signal, ATrafficSignBase * ClosestTrafficSign)
Definition at line 378 of file TrafficLightManager.cpp.
References carla::road::Signal::GetSubtype(), ATrafficSignBase::GetTrafficSignState(), carla::road::Signal::GetType(), carla::road::SignalType::IsTrafficLight(), carla::road::SignalType::MaximumSpeed(), carla::road::SignalType::StopSign(), TrafficLightGreen, TrafficLightRed, TrafficLightYellow, and carla::road::SignalType::YieldSign().
Referenced by GetClosestTrafficSignActor().