CARLA: carla::opendrive::parser::LaneParser Class Reference
carla::opendrive::parser::LaneParser Class Reference
#include <LaneParser.h>
Static Public Member Functions
static void Parse (const pugi::xml_document &xml, carla::road::MapBuilder &map_builder)
Detailed Description
Definition at line 22 of file LaneParser.h.
Member Function Documentation
Parse()
void carla::opendrive::parser::LaneParser::Parse (const pugi::xml_document & xml, carla::road::MapBuilder & map_builder) static
Definition at line 187 of file LaneParser.cpp.
References pugi::xml_attribute::as_uint(), pugi::xml_node::attribute(), pugi::xml_node::child(), pugi::xml_node::children(), and carla::opendrive::parser::ParseLanes().
Referenced by carla::opendrive::OpenDriveParser::Load().
The documentation for this class was generated from the following files:
LaneParser.h
LaneParser.cpp