CARLA: carla::client::WalkerAIController Class Reference
carla::client::WalkerAIController Class Reference
#include <WalkerAIController.h>
Public Member Functions
boost::optional< geom::Location > GetRandomLocation ()
void GoToLocation (const carla::geom::Location &destination)
void SetMaxSpeed (const float max_speed)
void Start ()
void Stop ()
WalkerAIController (ActorInitializer init)
Public Member Functions inherited from carla::client::Actor
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddForce (const geom::Vector3D &force)
Add force to the actor at its center of mass.
void AddForce (const geom::Vector3D &force, const geom::Vector3D &location)
Add force to the actor at certain location.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor at its center of mass.
void AddImpulse (const geom::Vector3D &impulse, const geom::Vector3D &location)
Add impulse to the actor at certain location.
void AddTorque (const geom::Vector3D &vector)
Add a torque to the actor.
virtual bool Destroy ()
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
void DisableConstantVelocity ()
Disable the constant velocity mode.
void EnableConstantVelocity (const geom::Vector3D &vector)
Enable a constant velocity mode.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
rpc::ActorState GetActorState () const
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
geom::Location GetLocation () const
Return the current location of the actor.
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsActive () const
bool IsAlive () const
bool IsDormant () const
const auto & Serialize () const
void SetActorDead ()
Set actor as dead and starts his life span.
void SetCollisions (bool enabled=true)
Enable or disable collisions on this actor.
void SetEnableGravity (bool enabled=true)
Enable or disable gravity on this actor.
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTargetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor before applying physics.
void SetTargetVelocity (const geom::Vector3D &vector)
Set the actor velocity before applying physics.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Additional Inherited Members
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Detailed Description
Definition at line 17 of file LibCarla/source/carla/client/WalkerAIController.h.
Constructor & Destructor Documentation
WalkerAIController()
carla::client::WalkerAIController::WalkerAIController (ActorInitializer init) explicit
Definition at line 15 of file WalkerAIController.cpp.
Member Function Documentation
GetRandomLocation()
boost::optional< geom::Location > carla::client::WalkerAIController::GetRandomLocation ()
Definition at line 47 of file WalkerAIController.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GoToLocation()
void carla::client::WalkerAIController::GoToLocation (const carla::geom::Location & destination)
Definition at line 55 of file WalkerAIController.cpp.
References carla::client::detail::ActorState::GetEpisode(), carla::client::detail::ActorState::GetParent(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::log_warning(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
SetMaxSpeed()
void carla::client::WalkerAIController::SetMaxSpeed (const float max_speed)
Definition at line 69 of file WalkerAIController.cpp.
References carla::client::detail::ActorState::GetEpisode(), carla::client::detail::ActorState::GetParent(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::log_warning().
Start()
void carla::client::WalkerAIController::Start ()
Definition at line 18 of file WalkerAIController.cpp.
References carla::client::detail::ActorState::GetEpisode(), carla::client::detail::ActorState::GetParent(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Stop()
void carla::client::WalkerAIController::Stop (void)
Definition at line 34 of file WalkerAIController.cpp.
References carla::client::detail::ActorState::GetEpisode(), carla::client::detail::ActorState::GetParent(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
The documentation for this class was generated from the following files:
LibCarla/source/carla/client/WalkerAIController.h
WalkerAIController.cpp