CARLA: carla::traffic_manager::PipelineStage Class Reference
carla::traffic_manager::PipelineStage Class Reference abstract
This class provides base functionality and template for various stages of the pipeline.
#include <PipelineStage.h>
Public Member Functions
PipelineStage (std::string stage_name)
void Start ()
void Stop ()
virtual ~PipelineStage ()
Protected Member Functions
virtual void Action ()=0
Implement this method with logic to process data inside the stage.
virtual void DataReceiver ()=0
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
virtual void DataSender ()=0
Implement this method with logic to gather results from the action threads and send to next stage(s).
Private Member Functions
void Update ()
Private Attributes
PerformanceDiagnostics performance_diagnostics
Object to track stage performance.
std::atomic< bool > run_stage
Flag to start/stop stage.
std::string stage_name
Stage name string.
std::unique_ptr< std::thread > worker_thread
Detailed Description
This class provides base functionality and template for various stages of the pipeline.
Definition at line 34 of file PipelineStage.h.
Constructor & Destructor Documentation
carla::traffic_manager::PipelineStage::PipelineStage (std::string stage_name)
Definition at line 12 of file PipelineStage.cpp.
References run_stage.
carla::traffic_manager::PipelineStage::~PipelineStage () virtual
Definition at line 18 of file PipelineStage.cpp.
References worker_thread.
Member Function Documentation
virtual void carla::traffic_manager::PipelineStage::Action () protected pure virtual
Implement this method with logic to process data inside the stage.
Implemented in carla::traffic_manager::LocalizationStage, carla::traffic_manager::CollisionStage, carla::traffic_manager::MotionPlannerStage, carla::traffic_manager::TrafficLightStage, and carla::traffic_manager::BatchControlStage.
Referenced by Update().
virtual void carla::traffic_manager::PipelineStage::DataReceiver () protected pure virtual
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
Implemented in carla::traffic_manager::LocalizationStage, carla::traffic_manager::CollisionStage, carla::traffic_manager::MotionPlannerStage, carla::traffic_manager::TrafficLightStage, and carla::traffic_manager::BatchControlStage.
Referenced by Update().
virtual void carla::traffic_manager::PipelineStage::DataSender () protected pure virtual
Implement this method with logic to gather results from the action threads and send to next stage(s).
Implemented in carla::traffic_manager::LocalizationStage, carla::traffic_manager::CollisionStage, carla::traffic_manager::MotionPlannerStage, carla::traffic_manager::TrafficLightStage, and carla::traffic_manager::BatchControlStage.
Referenced by Update().
void carla::traffic_manager::PipelineStage::Start ()
Definition at line 23 of file PipelineStage.cpp.
References run_stage, Update(), and worker_thread.
void carla::traffic_manager::PipelineStage::Stop (void)
Definition at line 28 of file PipelineStage.cpp.
References run_stage.
void carla::traffic_manager::PipelineStage::Update () private
Definition at line 32 of file PipelineStage.cpp.
References Action(), DataReceiver(), DataSender(), performance_diagnostics, carla::traffic_manager::PerformanceDiagnostics::RegisterUpdate(), and run_stage.
Referenced by Start().
Member Data Documentation
PerformanceDiagnostics carla::traffic_manager::PipelineStage::performance_diagnostics private
Object to track stage performance.
Definition at line 46 of file PipelineStage.h.
Referenced by Update().
std::atomic<bool> carla::traffic_manager::PipelineStage::run_stage private
Flag to start/stop stage.
Definition at line 40 of file PipelineStage.h.
Referenced by PipelineStage(), Start(), Stop(), and Update().
std::string carla::traffic_manager::PipelineStage::stage_name private
Stage name string.
Definition at line 42 of file PipelineStage.h.
std::unique_ptr<std::thread> carla::traffic_manager::PipelineStage::worker_thread private
Definition at line 38 of file PipelineStage.h.
Referenced by Start(), and ~PipelineStage().
The documentation for this class was generated from the following files:
PipelineStage.h
PipelineStage.cpp