CARLA: carla_msgs::msg::CollisionEventPubSubType Class Reference
carla_msgs::msg::CollisionEventPubSubType Class Reference
This class represents the TopicDataType of the type CollisionEvent defined by the user in the IDL file.
#include <CarlaCollisionEventPubSubTypes.h>
Public Types
typedef CollisionEvent type
Public Member Functions
eProsima_user_DllExport CollisionEventPubSubType ()
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~CollisionEventPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type CollisionEvent defined by the user in the IDL file.
Definition at line 47 of file CarlaCollisionEventPubSubTypes.h.
Member Typedef Documentation
type
typedef CollisionEvent carla_msgs::msg::CollisionEventPubSubType::type
Definition at line 51 of file CarlaCollisionEventPubSubTypes.h.
Constructor & Destructor Documentation
CollisionEventPubSubType()
carla_msgs::msg::CollisionEventPubSubType::CollisionEventPubSubType ()
Definition at line 32 of file CarlaCollisionEventPubSubTypes.cpp.
References carla_msgs::msg::CollisionEvent::getKeyMaxCdrSerializedSize(), carla_msgs::msg::CollisionEvent::getMaxCdrSerializedSize(), carla_msgs::msg::CollisionEvent::isKeyDefined(), and m_keyBuffer.
~CollisionEventPubSubType()
carla_msgs::msg::CollisionEventPubSubType::~CollisionEventPubSubType () override virtual
Definition at line 45 of file CarlaCollisionEventPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * carla_msgs::msg::CollisionEventPubSubType::createData () override virtual
Definition at line 122 of file CarlaCollisionEventPubSubTypes.cpp.
deleteData()
void carla_msgs::msg::CollisionEventPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file CarlaCollisionEventPubSubTypes.cpp.
deserialize()
bool carla_msgs::msg::CollisionEventPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file CarlaCollisionEventPubSubTypes.cpp.
References carla_msgs::msg::CollisionEvent::deserialize().
getKey()
bool carla_msgs::msg::CollisionEventPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file CarlaCollisionEventPubSubTypes.cpp.
References carla_msgs::msg::CollisionEvent::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and carla_msgs::msg::CollisionEvent::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> carla_msgs::msg::CollisionEventPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file CarlaCollisionEventPubSubTypes.cpp.
References carla_msgs::msg::CollisionEvent::getCdrSerializedSize().
serialize()
bool carla_msgs::msg::CollisionEventPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file CarlaCollisionEventPubSubTypes.cpp.
References carla_msgs::msg::CollisionEvent::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* carla_msgs::msg::CollisionEventPubSubType::m_keyBuffer
Definition at line 105 of file CarlaCollisionEventPubSubTypes.h.
Referenced by CollisionEventPubSubType(), getKey(), and ~CollisionEventPubSubType().
m_md5
MD5 carla_msgs::msg::CollisionEventPubSubType::m_md5
Definition at line 104 of file CarlaCollisionEventPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
CarlaCollisionEventPubSubTypes.h
CarlaCollisionEventPubSubTypes.cpp