CARLA: CarlaRecorderEventsAdd Class Reference
CarlaRecorderEventsAdd Class Reference
#include <CarlaRecorderEventAdd.h>
Public Member Functions
void Add (const CarlaRecorderEventAdd &Event)
void Clear (void)
void Write (std::ofstream &OutFile)
Private Attributes
std::vector< CarlaRecorderEventAdd > Events
Detailed Description
Definition at line 38 of file CarlaRecorderEventAdd.h.
Member Function Documentation
void CarlaRecorderEventsAdd::Add (const CarlaRecorderEventAdd & Event) inline
Definition at line 75 of file CarlaRecorderEventAdd.cpp.
Referenced by ACarlaRecorder::AddEvent().
void CarlaRecorderEventsAdd::Clear (void) inline
Definition at line 70 of file CarlaRecorderEventAdd.cpp.
Referenced by ACarlaRecorder::Clear().
void CarlaRecorderEventsAdd::Write (std::ofstream & OutFile)
Definition at line 80 of file CarlaRecorderEventAdd.cpp.
References EventAdd, and CarlaRecorderEventAdd::Write().
Referenced by ACarlaRecorder::Write().
Member Data Documentation
std::vector<CarlaRecorderEventAdd> CarlaRecorderEventsAdd::Events private
Definition at line 47 of file CarlaRecorderEventAdd.h.
The documentation for this class was generated from the following files:
CarlaRecorderEventAdd.h
CarlaRecorderEventAdd.cpp