CARLA: rosgraph::msg::ClockPubSubType Class Reference
rosgraph::msg::ClockPubSubType Class Reference
This class represents the TopicDataType of the type Clock defined by the user in the IDL file.
#include <ClockPubSubTypes.h>
Public Types
typedef Clock type
Public Member Functions
eProsima_user_DllExport ClockPubSubType ()
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~ClockPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type Clock defined by the user in the IDL file.
Definition at line 43 of file ClockPubSubTypes.h.
Member Typedef Documentation
type
typedef Clock rosgraph::msg::ClockPubSubType::type
Definition at line 47 of file ClockPubSubTypes.h.
Constructor & Destructor Documentation
ClockPubSubType()
rosgraph::msg::ClockPubSubType::ClockPubSubType ()
Definition at line 32 of file ClockPubSubTypes.cpp.
References rosgraph::msg::Clock::getKeyMaxCdrSerializedSize(), rosgraph::msg::Clock::getMaxCdrSerializedSize(), rosgraph::msg::Clock::isKeyDefined(), and m_keyBuffer.
~ClockPubSubType()
rosgraph::msg::ClockPubSubType::~ClockPubSubType () override virtual
Definition at line 45 of file ClockPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * rosgraph::msg::ClockPubSubType::createData () override virtual
Definition at line 122 of file ClockPubSubTypes.cpp.
deleteData()
void rosgraph::msg::ClockPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file ClockPubSubTypes.cpp.
deserialize()
bool rosgraph::msg::ClockPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file ClockPubSubTypes.cpp.
References rosgraph::msg::Clock::deserialize().
getKey()
bool rosgraph::msg::ClockPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file ClockPubSubTypes.cpp.
References rosgraph::msg::Clock::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and rosgraph::msg::Clock::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> rosgraph::msg::ClockPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file ClockPubSubTypes.cpp.
References rosgraph::msg::Clock::getCdrSerializedSize().
serialize()
bool rosgraph::msg::ClockPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file ClockPubSubTypes.cpp.
References rosgraph::msg::Clock::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* rosgraph::msg::ClockPubSubType::m_keyBuffer
Definition at line 100 of file ClockPubSubTypes.h.
Referenced by ClockPubSubType(), getKey(), and ~ClockPubSubType().
m_md5
MD5 rosgraph::msg::ClockPubSubType::m_md5
Definition at line 99 of file ClockPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
ClockPubSubTypes.h
ClockPubSubTypes.cpp