CARLA: CarlaRecorderAnimVehicles Class Reference
CarlaRecorderAnimVehicles Class Reference
#include <CarlaRecorderAnimVehicle.h>
Public Member Functions
void Add (const CarlaRecorderAnimVehicle &InObj)
void Clear (void)
void Write (std::ofstream &OutFile)
Private Attributes
std::vector< CarlaRecorderAnimVehicle > Vehicles
Detailed Description
Definition at line 29 of file CarlaRecorderAnimVehicle.h.
Member Function Documentation
void CarlaRecorderAnimVehicles::Add (const CarlaRecorderAnimVehicle & InObj)
Definition at line 39 of file CarlaRecorderAnimVehicle.cpp.
References Vehicles.
Referenced by ACarlaRecorder::AddAnimVehicle().
void CarlaRecorderAnimVehicles::Clear (void)
Definition at line 34 of file CarlaRecorderAnimVehicle.cpp.
References Vehicles.
Referenced by ACarlaRecorder::Clear().
void CarlaRecorderAnimVehicles::Write (std::ofstream & OutFile)
Definition at line 44 of file CarlaRecorderAnimVehicle.cpp.
References AnimVehicle, Vehicles, and CarlaRecorderAnimVehicle::Write().
Referenced by ACarlaRecorder::Write().
Member Data Documentation
std::vector<CarlaRecorderAnimVehicle> CarlaRecorderAnimVehicles::Vehicles private
Definition at line 41 of file CarlaRecorderAnimVehicle.h.
The documentation for this class was generated from the following files:
CarlaRecorderAnimVehicle.h
CarlaRecorderAnimVehicle.cpp