CARLA: CarlaRecorderPlatformTime Struct Reference
CarlaRecorderPlatformTime Struct Reference
#include <CarlaRecorderPlatformTime.h>
Public Member Functions
void Read (std::istream &InFile)
void SetStartTime ()
void UpdateTime ()
void Write (std::ostream &OutFile)
Public Attributes
std::chrono::time_point< std::chrono::system_clock > RecorderStartTime
double Time
Detailed Description
Definition at line 13 of file CarlaRecorderPlatformTime.h.
Member Function Documentation
Read()
void CarlaRecorderPlatformTime::Read (std::istream & InFile)
Definition at line 23 of file CarlaRecorderPlatformTime.cpp.
References Time.
Referenced by CarlaRecorderQuery::QueryInfo().
SetStartTime()
void CarlaRecorderPlatformTime::SetStartTime ()
Definition at line 11 of file CarlaRecorderPlatformTime.cpp.
References RecorderStartTime.
Referenced by ACarlaRecorder::Start().
UpdateTime()
void CarlaRecorderPlatformTime::UpdateTime ()
Definition at line 15 of file CarlaRecorderPlatformTime.cpp.
References RecorderStartTime, and Time.
Referenced by ACarlaRecorder::Ticking().
Write()
void CarlaRecorderPlatformTime::Write (std::ostream & OutFile)
Definition at line 28 of file CarlaRecorderPlatformTime.cpp.
References PlatformTime, and Time.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
RecorderStartTime
std::chrono::time_point<std::chrono::system_clock> CarlaRecorderPlatformTime::RecorderStartTime
Definition at line 17 of file CarlaRecorderPlatformTime.h.
Referenced by SetStartTime(), and UpdateTime().
Time
double CarlaRecorderPlatformTime::Time
Definition at line 19 of file CarlaRecorderPlatformTime.h.
Referenced by CarlaRecorderQuery::QueryInfo(), Read(), UpdateTime(), and Write().
The documentation for this struct was generated from the following files:
CarlaRecorderPlatformTime.h
CarlaRecorderPlatformTime.cpp