CARLA: carla::ros2::CarlaLineInvasionPublisher Class Reference
carla::ros2::CarlaLineInvasionPublisher Class Reference
#include <CarlaLineInvasionPublisher.h>
Public Member Functions
CarlaLineInvasionPublisher (CarlaLineInvasionPublisher &&)
CarlaLineInvasionPublisher (const CarlaLineInvasionPublisher &)
CarlaLineInvasionPublisher (const char *ros_name="", const char *parent="")
bool Init ()
CarlaLineInvasionPublisher & operator= (CarlaLineInvasionPublisher &&)
CarlaLineInvasionPublisher & operator= (const CarlaLineInvasionPublisher &)
bool Publish ()
void SetData (int32_t seconds, uint32_t nanoseconds, const int32_t *data)
const char * type () const override
~CarlaLineInvasionPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Attributes
std::shared_ptr< CarlaLineInvasionPublisherImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 17 of file CarlaLineInvasionPublisher.h.
Constructor & Destructor Documentation
CarlaLineInvasionPublisher() [1/3]
carla::ros2::CarlaLineInvasionPublisher::CarlaLineInvasionPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 164 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaLineInvasionPublisher()
carla::ros2::CarlaLineInvasionPublisher::~CarlaLineInvasionPublisher ()
Definition at line 170 of file CarlaLineInvasionPublisher.cpp.
References _impl.
CarlaLineInvasionPublisher() [2/3]
carla::ros2::CarlaLineInvasionPublisher::CarlaLineInvasionPublisher (const CarlaLineInvasionPublisher & other)
Definition at line 187 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaLineInvasionPublisher() [3/3]
carla::ros2::CarlaLineInvasionPublisher::CarlaLineInvasionPublisher (CarlaLineInvasionPublisher && other)
Definition at line 203 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
Init()
bool carla::ros2::CarlaLineInvasionPublisher::Init ()
Definition at line 42 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [1/2]
CarlaLineInvasionPublisher & carla::ros2::CarlaLineInvasionPublisher::operator= (CarlaLineInvasionPublisher && other)
Definition at line 210 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaLineInvasionPublisher & carla::ros2::CarlaLineInvasionPublisher::operator= (const CarlaLineInvasionPublisher & other)
Definition at line 194 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaLineInvasionPublisher::Publish ()
Definition at line 89 of file CarlaLineInvasionPublisher.cpp.
References _impl.
SetData()
void carla::ros2::CarlaLineInvasionPublisher::SetData (int32_t seconds, uint32_t nanoseconds, const int32_t * data)
Definition at line 151 of file CarlaLineInvasionPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
type()
const char* carla::ros2::CarlaLineInvasionPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 29 of file CarlaLineInvasionPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaLineInvasionPublisherImpl> carla::ros2::CarlaLineInvasionPublisher::_impl private
Definition at line 32 of file CarlaLineInvasionPublisher.h.
Referenced by CarlaLineInvasionPublisher(), Init(), operator=(), Publish(), SetData(), and ~CarlaLineInvasionPublisher().
The documentation for this class was generated from the following files:
CarlaLineInvasionPublisher.h
CarlaLineInvasionPublisher.cpp