CARLA: carla::traffic_manager::InMemoryMap Class Reference
carla::traffic_manager::InMemoryMap Class Reference
This class builds a discretized local map-cache.
#include <InMemoryMap.h>
Public Member Functions
NodeList GetDenseTopology () const
This method returns the full list of discrete samples of the map in the local cache.
cg::Location GetGeodesicGridCenter (GeoGridId ggid)
SimpleWaypointPtr GetPedWaypoint (cg::Location location)
SegmentId GetSegmentId (const WaypointPtr &wp) const
Computes the segment id of a given waypoint.
SegmentId GetSegmentId (const SimpleWaypointPtr &swp) const
SimpleWaypointPtr GetWaypoint (const cg::Location &location) const
This method returns the closest waypoint to a given location on the map.
SimpleWaypointPtr GetWaypointInVicinity (cg::Location location)
This method returns closest waypoint in the vicinity of the given co-ordinates.
InMemoryMap (WorldMap world_map)
void MakeGeodesiGridCenters ()
void SetUp ()
This method constructs the local map with a resolution of sampling_resolution.
~InMemoryMap ()
Private Member Functions
void FindAndLinkLaneChange (SimpleWaypointPtr reference_waypoint)
This method is used to find and place lane change links.
std::vector< SimpleWaypointPtr > GetPredecessors (const SegmentId segment_id, const SegmentTopology &segment_topology, const SegmentMap &segment_map)
std::vector< SimpleWaypointPtr > GetSuccessors (const SegmentId segment_id, const SegmentTopology &segment_topology, const SegmentMap &segment_map)
std::pair< int, int > MakeGridId (float x, float y, bool vehicle_or_pedestrian)
Method to generate the grid ids for given co-ordinates.
std::string MakeGridKey (std::pair< int, int > gird_id)
Method to generate map key for waypoint_grid.
Private Attributes
WorldMap _world_map
Object to hold the world map received by the constructor.
NodeList dense_topology
Structure to hold all custom waypoint objects after interpolation of sparse topology.
std::unordered_map< GeoGridId, cg::Location > geodesic_grid_center
Geodesic grid topology.
WaypointGrid ped_waypoint_grid
Larger localization map for all waypoints to be used for localizing pedestrians.
WaypointGrid waypoint_grid
Grid localization map for all waypoints in the system.
Detailed Description
This class builds a discretized local map-cache.
Instantiate the class with the world and run SetUp() to construct the local map.
Definition at line 49 of file InMemoryMap.h.
Constructor & Destructor Documentation
carla::traffic_manager::InMemoryMap::InMemoryMap (WorldMap world_map)
Definition at line 24 of file InMemoryMap.cpp.
carla::traffic_manager::InMemoryMap::~InMemoryMap ()
Definition at line 25 of file InMemoryMap.cpp.
Member Function Documentation
void carla::traffic_manager::InMemoryMap::FindAndLinkLaneChange (SimpleWaypointPtr reference_waypoint) private
This method is used to find and place lane change links.
Definition at line 338 of file InMemoryMap.cpp.
References carla::road::Both, GetWaypoint(), GetWaypointInVicinity(), carla::log_info(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by SetUp().
std::vector< SimpleWaypointPtr > carla::traffic_manager::InMemoryMap::GetDenseTopology () const
This method returns the full list of discrete samples of the map in the local cache.
Definition at line 334 of file InMemoryMap.cpp.
References dense_topology.
cg::Location carla::traffic_manager::InMemoryMap::GetGeodesicGridCenter (GeoGridId ggid)
Definition at line 400 of file InMemoryMap.cpp.
References geodesic_grid_center.
SimpleWaypointPtr carla::traffic_manager::InMemoryMap::GetPedWaypoint (cg::Location location)
Definition at line 288 of file InMemoryMap.cpp.
References carla::traffic_manager::MapConstants::INFINITE_DISTANCE, MakeGridId(), MakeGridKey(), ped_waypoint_grid, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles().
std::vector< SimpleWaypointPtr > carla::traffic_manager::InMemoryMap::GetPredecessors (const SegmentId segment_id, const SegmentTopology & segment_topology, const SegmentMap & segment_map) private
Definition at line 53 of file InMemoryMap.cpp.
Referenced by SetUp().
SegmentId carla::traffic_manager::InMemoryMap::GetSegmentId (const WaypointPtr & wp) const
Computes the segment id of a given waypoint.
The Id takes into account OpenDrive's road Id, lane Id and Section Id.
Definition at line 27 of file InMemoryMap.cpp.
Referenced by GetSegmentId(), and SetUp().
SegmentId carla::traffic_manager::InMemoryMap::GetSegmentId (const SimpleWaypointPtr & swp) const
Definition at line 31 of file InMemoryMap.cpp.
References GetSegmentId().
std::vector< SimpleWaypointPtr > carla::traffic_manager::InMemoryMap::GetSuccessors (const SegmentId segment_id, const SegmentTopology & segment_topology, const SegmentMap & segment_map) private
Definition at line 35 of file InMemoryMap.cpp.
Referenced by SetUp().
SimpleWaypointPtr carla::traffic_manager::InMemoryMap::GetWaypoint (const cg::Location & location) const
This method returns the closest waypoint to a given location on the map.
Definition at line 320 of file InMemoryMap.cpp.
References dense_topology, and carla::traffic_manager::MapConstants::INFINITE_DISTANCE.
Referenced by carla::traffic_manager::LocalizationStage::Action(), FindAndLinkLaneChange(), and carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles().
SimpleWaypointPtr carla::traffic_manager::InMemoryMap::GetWaypointInVicinity (cg::Location location)
This method returns closest waypoint in the vicinity of the given co-ordinates.
Definition at line 250 of file InMemoryMap.cpp.
References carla::traffic_manager::MapConstants::INFINITE_DISTANCE, MakeGridId(), MakeGridKey(), waypoint_grid, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::traffic_manager::LocalizationStage::Action(), FindAndLinkLaneChange(), and carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles().
void carla::traffic_manager::InMemoryMap::MakeGeodesiGridCenters ()
Definition at line 388 of file InMemoryMap.cpp.
References dense_topology, and geodesic_grid_center.
Referenced by SetUp().
std::pair< int, int > carla::traffic_manager::InMemoryMap::MakeGridId (float x, float y, bool vehicle_or_pedestrian) private
Method to generate the grid ids for given co-ordinates.
Definition at line 237 of file InMemoryMap.cpp.
References carla::traffic_manager::MapConstants::GRID_SIZE, and carla::traffic_manager::MapConstants::PED_GRID_SIZE.
Referenced by GetPedWaypoint(), GetWaypointInVicinity(), and SetUp().
std::string carla::traffic_manager::InMemoryMap::MakeGridKey (std::pair< int, int > gird_id) private
Method to generate map key for waypoint_grid.
Definition at line 246 of file InMemoryMap.cpp.
Referenced by GetPedWaypoint(), GetWaypointInVicinity(), and SetUp().
void carla::traffic_manager::InMemoryMap::SetUp ()
This method constructs the local map with a resolution of sampling_resolution.
Definition at line 71 of file InMemoryMap.cpp.
References _world_map, dense_topology, carla::geom::Math::DistanceSquared(), FindAndLinkLaneChange(), GetPredecessors(), GetSegmentId(), GetSuccessors(), MakeGeodesiGridCenters(), MakeGridId(), MakeGridKey(), carla::traffic_manager::MapConstants::MAX_GEODESIC_GRID_LENGTH, ped_waypoint_grid, reverse(), sort(), carla::traffic_manager::MapConstants::TOPOLOGY_DISTANCE, waypoint_grid, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Member Data Documentation
WorldMap carla::traffic_manager::InMemoryMap::_world_map private
Object to hold the world map received by the constructor.
Definition at line 54 of file InMemoryMap.h.
Referenced by SetUp().
NodeList carla::traffic_manager::InMemoryMap::dense_topology private
Structure to hold all custom waypoint objects after interpolation of sparse topology.
Definition at line 57 of file InMemoryMap.h.
Referenced by GetDenseTopology(), GetWaypoint(), MakeGeodesiGridCenters(), and SetUp().
std::unordered_map<GeoGridId, cg::Location> carla::traffic_manager::InMemoryMap::geodesic_grid_center private
Geodesic grid topology.
Definition at line 63 of file InMemoryMap.h.
Referenced by GetGeodesicGridCenter(), and MakeGeodesiGridCenters().
WaypointGrid carla::traffic_manager::InMemoryMap::ped_waypoint_grid private
Larger localization map for all waypoints to be used for localizing pedestrians.
Definition at line 61 of file InMemoryMap.h.
Referenced by GetPedWaypoint(), and SetUp().
WaypointGrid carla::traffic_manager::InMemoryMap::waypoint_grid private
Grid localization map for all waypoints in the system.
Definition at line 59 of file InMemoryMap.h.
Referenced by GetWaypointInVicinity(), and SetUp().
The documentation for this class was generated from the following files:
InMemoryMap.h
InMemoryMap.cpp