CARLA: carla::traffic_manager::MapConstants Namespace Reference
carla::traffic_manager::MapConstants Namespace Reference
Variables
static const float GRID_SIZE = 4.0f
static const float INFINITE_DISTANCE = std::numeric_limits<float>::max()
static const float MAX_GEODESIC_GRID_LENGTH = 20.0f
static const float PED_GRID_SIZE = 10.0f
Variable Documentation
const float carla::traffic_manager::MapConstants::GRID_SIZE = 4.0f static
Definition at line 15 of file InMemoryMap.cpp.
Referenced by carla::traffic_manager::InMemoryMap::MakeGridId().
const float carla::traffic_manager::MapConstants::INFINITE_DISTANCE = std::numeric_limits<float>::max() static
Definition at line 14 of file InMemoryMap.cpp.
Referenced by carla::traffic_manager::InMemoryMap::GetPedWaypoint(), carla::traffic_manager::InMemoryMap::GetWaypoint(), and carla::traffic_manager::InMemoryMap::GetWaypointInVicinity().
const float carla::traffic_manager::MapConstants::MAX_GEODESIC_GRID_LENGTH = 20.0f static
Definition at line 17 of file InMemoryMap.cpp.
Referenced by carla::traffic_manager::InMemoryMap::SetUp().
const float carla::traffic_manager::MapConstants::PED_GRID_SIZE = 10.0f static
Definition at line 16 of file InMemoryMap.cpp.
Referenced by carla::traffic_manager::InMemoryMap::MakeGridId().