CARLA: UTrafficLightController Class Reference
UTrafficLightController Class Reference
Maps a controller from OpenDrive.
#include <TrafficLightController.h>
Public Member Functions
void AddTrafficLight (UTrafficLightComponent *TrafficLight)
bool AdvanceTimeAndCycleFinished (float DeltaTime)
void EmptyTrafficLights ()
const FString & GetControllerId () const
const FTrafficLightStage & GetCurrentState () const
float GetElapsedTime () const
float GetGreenTime () const
ATrafficLightGroup * GetGroup ()
const ATrafficLightGroup * GetGroup () const
float GetRedTime () const
int GetSequence () const
const TArray< UTrafficLightComponent * > & GetTrafficLights ()
float GetYellowTime () const
bool IsCycleFinished () const
float NextState ()
void ResetState ()
void SetControllerId (const FString &Id)
void SetElapsedTime (float InElapsedTime)
void SetGreenTime (float NewTime)
void SetGroup (ATrafficLightGroup *Group)
void SetRedTime (float NewTime)
void SetSequence (int InSequence)
void SetStates (TArray< FTrafficLightStage > States)
void SetTrafficLightsState (ETrafficLightState NewState)
void SetYellowTime (float NewTime)
void StartCycle ()
UTrafficLightController ()
Private Member Functions
float GetStateTime (const ETrafficLightState State) const
void SetStateTime (const ETrafficLightState State, float NewTime)
Private Attributes
FString ControllerId = ""
int CurrentState = 0
float ElapsedTime = 0
TArray< FTrafficLightStage > LightStates
int Sequence = 0
ATrafficLightGroup * TrafficLightGroup
TArray< UTrafficLightComponent * > TrafficLights
Detailed Description
Maps a controller from OpenDrive.
Controls the asociated traffic lights and contains its cycles
Definition at line 35 of file TrafficLightController.h.
Constructor & Destructor Documentation
UTrafficLightController()
UTrafficLightController::UTrafficLightController ()
Definition at line 9 of file TrafficLightController.cpp.
Member Function Documentation
AddTrafficLight()
void UTrafficLightController::AddTrafficLight (UTrafficLightComponent * TrafficLight)
Definition at line 65 of file TrafficLightController.cpp.
References TrafficLights.
Referenced by ATrafficLightManager::RegisterLightComponentFromOpenDRIVE().
AdvanceTimeAndCycleFinished()
bool UTrafficLightController::AdvanceTimeAndCycleFinished (float DeltaTime)
Definition at line 32 of file TrafficLightController.cpp.
References ElapsedTime, GetCurrentState(), IsCycleFinished(), and NextState().
Referenced by ATrafficLightGroup::Tick().
EmptyTrafficLights()
void UTrafficLightController::EmptyTrafficLights ()
Definition at line 60 of file TrafficLightController.cpp.
References TrafficLights.
GetControllerId()
const FString & UTrafficLightController::GetControllerId () const
Definition at line 71 of file TrafficLightController.cpp.
References ControllerId.
GetCurrentState()
const FTrafficLightStage & UTrafficLightController::GetCurrentState () const
Definition at line 20 of file TrafficLightController.cpp.
References CurrentState, and LightStates.
Referenced by AdvanceTimeAndCycleFinished(), NextState(), ResetState(), and StartCycle().
GetElapsedTime()
float UTrafficLightController::GetElapsedTime () const
Definition at line 164 of file TrafficLightController.cpp.
References ElapsedTime.
Referenced by FWorldObserver_GetActorState().
GetGreenTime()
float UTrafficLightController::GetGreenTime () const
Definition at line 126 of file TrafficLightController.cpp.
References GetStateTime().
Referenced by FWorldObserver_GetActorState().
GetGroup() [1/2]
ATrafficLightGroup * UTrafficLightController::GetGroup ()
Definition at line 179 of file TrafficLightController.cpp.
References TrafficLightGroup.
GetGroup() [2/2]
const ATrafficLightGroup * UTrafficLightController::GetGroup () const
Definition at line 184 of file TrafficLightController.cpp.
References TrafficLightGroup.
GetRedTime()
float UTrafficLightController::GetRedTime () const
Definition at line 136 of file TrafficLightController.cpp.
References GetStateTime().
Referenced by FWorldObserver_GetActorState().
GetSequence()
int UTrafficLightController::GetSequence () const
Definition at line 94 of file TrafficLightController.cpp.
References Sequence.
GetStateTime()
float UTrafficLightController::GetStateTime (const ETrafficLightState State) const private
Definition at line 152 of file TrafficLightController.cpp.
References LightStates.
Referenced by GetGreenTime(), GetRedTime(), and GetYellowTime().
GetTrafficLights()
const TArray< UTrafficLightComponent * > & UTrafficLightController::GetTrafficLights ()
Definition at line 55 of file TrafficLightController.cpp.
References TrafficLights.
GetYellowTime()
float UTrafficLightController::GetYellowTime () const
Definition at line 131 of file TrafficLightController.cpp.
References GetStateTime().
Referenced by FWorldObserver_GetActorState().
IsCycleFinished()
bool UTrafficLightController::IsCycleFinished () const
Definition at line 81 of file TrafficLightController.cpp.
References CurrentState, and LightStates.
Referenced by AdvanceTimeAndCycleFinished().
NextState()
float UTrafficLightController::NextState ()
Definition at line 25 of file TrafficLightController.cpp.
References CurrentState, GetCurrentState(), LightStates, SetTrafficLightsState(), State, and FTrafficLightStage::Time.
Referenced by AdvanceTimeAndCycleFinished().
ResetState()
void UTrafficLightController::ResetState ()
Definition at line 104 of file TrafficLightController.cpp.
References CurrentState, ElapsedTime, GetCurrentState(), LightStates, SetTrafficLightsState(), and State.
Referenced by ATrafficLightManager::RegisterLightComponentFromOpenDRIVE(), and SetStates().
SetControllerId()
void UTrafficLightController::SetControllerId (const FString & Id)
Definition at line 76 of file TrafficLightController.cpp.
References ControllerId.
SetElapsedTime()
void UTrafficLightController::SetElapsedTime (float InElapsedTime)
Definition at line 169 of file TrafficLightController.cpp.
References ElapsedTime.
SetGreenTime()
void UTrafficLightController::SetGreenTime (float NewTime)
Definition at line 121 of file TrafficLightController.cpp.
References SetStateTime().
Referenced by ATrafficLightBase::SetGreenTime().
SetGroup()
void UTrafficLightController::SetGroup (ATrafficLightGroup * Group)
Definition at line 174 of file TrafficLightController.cpp.
References TrafficLightGroup.
Referenced by ATrafficLightGroup::AddController().
SetRedTime()
void UTrafficLightController::SetRedTime (float NewTime)
Definition at line 116 of file TrafficLightController.cpp.
References SetStateTime().
Referenced by ATrafficLightBase::SetRedTime().
SetSequence()
void UTrafficLightController::SetSequence (int InSequence)
Definition at line 99 of file TrafficLightController.cpp.
References Sequence.
SetStates()
void UTrafficLightController::SetStates (TArray< FTrafficLightStage > States)
Definition at line 14 of file TrafficLightController.cpp.
References LightStates, and ResetState().
SetStateTime()
void UTrafficLightController::SetStateTime (const ETrafficLightState State, float NewTime) private
Definition at line 141 of file TrafficLightController.cpp.
References LightStates.
Referenced by SetGreenTime(), SetRedTime(), and SetYellowTime().
SetTrafficLightsState()
void UTrafficLightController::SetTrafficLightsState (ETrafficLightState NewState)
Definition at line 86 of file TrafficLightController.cpp.
References TrafficLights.
Referenced by NextState(), ResetState(), and StartCycle().
SetYellowTime()
void UTrafficLightController::SetYellowTime (float NewTime)
Definition at line 111 of file TrafficLightController.cpp.
References SetStateTime().
Referenced by ATrafficLightBase::SetYellowTime().
StartCycle()
void UTrafficLightController::StartCycle ()
Definition at line 48 of file TrafficLightController.cpp.
References CurrentState, ElapsedTime, GetCurrentState(), SetTrafficLightsState(), and State.
Referenced by ATrafficLightGroup::NextController(), and ATrafficLightGroup::ResetGroup().
Member Data Documentation
ControllerId
FString UTrafficLightController::ControllerId = "" private
Definition at line 127 of file TrafficLightController.h.
Referenced by GetControllerId(), and SetControllerId().
CurrentState
int UTrafficLightController::CurrentState = 0 private
Definition at line 130 of file TrafficLightController.h.
Referenced by GetCurrentState(), IsCycleFinished(), NextState(), ResetState(), and StartCycle().
ElapsedTime
float UTrafficLightController::ElapsedTime = 0 private
Definition at line 151 of file TrafficLightController.h.
Referenced by AdvanceTimeAndCycleFinished(), GetElapsedTime(), ResetState(), SetElapsedTime(), and StartCycle().
LightStates
TArray<FTrafficLightStage> UTrafficLightController::LightStates private
Initial value:
= {
    {10, ETrafficLightState::Green},
    { 3, ETrafficLightState::Yellow},
    { 2, ETrafficLightState::Red}
  }
Definition at line 134 of file TrafficLightController.h.
Referenced by GetCurrentState(), GetStateTime(), IsCycleFinished(), NextState(), ResetState(), SetStates(), and SetStateTime().
Sequence
int UTrafficLightController::Sequence = 0 private
Definition at line 148 of file TrafficLightController.h.
Referenced by GetSequence(), and SetSequence().
TrafficLightGroup
ATrafficLightGroup* UTrafficLightController::TrafficLightGroup private
Definition at line 144 of file TrafficLightController.h.
Referenced by GetGroup(), and SetGroup().
TrafficLights
TArray<UTrafficLightComponent *> UTrafficLightController::TrafficLights private
Definition at line 141 of file TrafficLightController.h.
Referenced by AddTrafficLight(), EmptyTrafficLights(), GetTrafficLights(), and SetTrafficLightsState().
The documentation for this class was generated from the following files:
TrafficLightController.h
TrafficLightController.cpp