CARLA: FDVector Struct Reference
FDVector Struct Reference
#include <DVector.h>
Public Member Functions
FDVector ()
FDVector (float InX, float InY, float InZ)
FDVector (double InX, double InY, double InZ)
FDVector (const FVector &V)
FDVector (const FIntVector &V)
FDVector operator* (float Scale) const
FDVector operator+ (const FDVector &V) const
FDVector operator- (const FDVector &V) const
FDVector operator-= (const FIntVector &V) const
FDVector & operator-= (const FIntVector &V)
FDVector operator/ (float Scale) const
FDVector & operator= (const FDVector &Other)
bool operator== (const FDVector &Other)
double Size () const
double SizeSquared () const
FIntVector ToFIntVector () const
FVector ToFVector () const
FString ToString () const
Static Public Member Functions
static double Dist (const FDVector &V1, const FDVector &V2)
static double DistSquared (const FDVector &V1, const FDVector &V2)
Public Attributes
double X = 0.0
double Y = 0.0
double Z = 0.0
Detailed Description
Definition at line 10 of file DVector.h.
Constructor & Destructor Documentation
FDVector() [1/5]
FDVector::FDVector () inline
Definition at line 17 of file DVector.h.
Referenced by operator*(), operator+(), operator-(), operator-=(), and operator/().
FDVector() [2/5]
FDVector::FDVector (float InX, float InY, float InZ) inline
Definition at line 19 of file DVector.h.
FDVector() [3/5]
FDVector::FDVector (double InX, double InY, double InZ) inline
Definition at line 21 of file DVector.h.
FDVector() [4/5]
FDVector::FDVector (const FVector & V) inline
Definition at line 23 of file DVector.h.
FDVector() [5/5]
FDVector::FDVector (const FIntVector & V) inline
Definition at line 25 of file DVector.h.
Member Function Documentation
Dist()
static double FDVector::Dist (const FDVector & V1, const FDVector & V2) inline static
Definition at line 37 of file DVector.h.
References DistSquared().
Referenced by ALargeMapManager::PrintMapInfo().
DistSquared()
static double FDVector::DistSquared (const FDVector & V1, const FDVector & V2) inline static
Definition at line 42 of file DVector.h.
References X, Y, and Z.
Referenced by Dist().
operator*()
FDVector FDVector::operator* (float Scale) const inline
Definition at line 106 of file DVector.h.
References FDVector().
operator+()
FDVector FDVector::operator+ (const FDVector & V) const inline
Definition at line 77 of file DVector.h.
References FDVector(), X, Y, and Z.
operator-()
FDVector FDVector::operator- (const FDVector & V) const inline
Definition at line 82 of file DVector.h.
References FDVector(), X, Y, and Z.
operator-=() [1/2]
FDVector FDVector::operator-= (const FIntVector & V) const inline
Definition at line 87 of file DVector.h.
References FDVector().
operator-=() [2/2]
FDVector& FDVector::operator-= (const FIntVector & V) inline
Definition at line 92 of file DVector.h.
References X.
operator/()
FDVector FDVector::operator/ (float Scale) const inline
Definition at line 100 of file DVector.h.
References FDVector().
operator=()
FDVector& FDVector::operator= (const FDVector & Other) inline
Definition at line 62 of file DVector.h.
References X, Y, and Z.
operator==()
bool FDVector::operator== (const FDVector & Other) inline
Definition at line 70 of file DVector.h.
References X, Y, and Z.
Size()
double FDVector::Size () const inline
Definition at line 27 of file DVector.h.
SizeSquared()
double FDVector::SizeSquared () const inline
Definition at line 32 of file DVector.h.
References Z.
ToFIntVector()
FIntVector FDVector::ToFIntVector () const inline
Definition at line 57 of file DVector.h.
ToFVector()
FVector FDVector::ToFVector () const inline
Definition at line 47 of file DVector.h.
Referenced by ALargeMapManager::GlobalToLocalLocation(), ALargeMapManager::GlobalToLocalTransform(), ALargeMapManager::LocalToGlobalLocation(), and ALargeMapManager::LocalToGlobalTransform().
ToString()
FString FDVector::ToString () const inline
Definition at line 52 of file DVector.h.
Referenced by ALargeMapManager::ConvertDormantToActiveActors().
Member Data Documentation
X
double FDVector::X = 0.0
Definition at line 13 of file DVector.h.
Referenced by DistSquared(), operator+(), operator-(), operator-=(), operator=(), and operator==().
Y
double FDVector::Y = 0.0
Definition at line 14 of file DVector.h.
Referenced by DistSquared(), ALargeMapManager::GetTileLocationD(), operator+(), operator-(), operator=(), and operator==().
Z
double FDVector::Z = 0.0
Definition at line 15 of file DVector.h.
Referenced by DistSquared(), operator+(), operator-(), operator=(), operator==(), and SizeSquared().
The documentation for this struct was generated from the following file:
DVector.h