CARLA: geometry_msgs::msg::Point Class Reference
geometry_msgs::msg::Point Class Reference
This class represents the structure Point defined by the user in the IDL file.
#include <Point.h>
Public Member Functions
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const Point &x) const
Comparison operator.
eProsima_user_DllExport Point & operator= (const Point &x)
Copy assignment.
eProsima_user_DllExport Point & operator= (Point &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Point &x) const
Comparison operator.
eProsima_user_DllExport Point ()
Default constructor.
eProsima_user_DllExport Point (const Point &x)
Copy constructor.
eProsima_user_DllExport Point (Point &&x) noexcept
Move constructor.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport double & x ()
This function returns a reference to member x.
eProsima_user_DllExport double x () const
This function returns the value of member x.
eProsima_user_DllExport void x (double _x)
This function sets a value in member x.
eProsima_user_DllExport double & y ()
This function returns a reference to member y.
eProsima_user_DllExport double y () const
This function returns the value of member y.
eProsima_user_DllExport void y (double _y)
This function sets a value in member y.
eProsima_user_DllExport double & z ()
This function returns a reference to member z.
eProsima_user_DllExport double z () const
This function returns the value of member z.
eProsima_user_DllExport void z (double _z)
This function sets a value in member z.
eProsima_user_DllExport ~Point ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::Point &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
double m_x
double m_y
double m_z
Detailed Description
This class represents the structure Point defined by the user in the IDL file.
Definition at line 70 of file Point.h.
Constructor & Destructor Documentation
Point() [1/3]
geometry_msgs::msg::Point::Point ()
Default constructor.
Definition at line 40 of file Point.cpp.
~Point()
geometry_msgs::msg::Point::~Point ()
Default destructor.
Definition at line 50 of file Point.cpp.
Point() [2/3]
geometry_msgs::msg::Point::Point (const Point & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::Point that will be copied.
Definition at line 54 of file Point.cpp.
References m_x, m_y, and m_z.
Point() [3/3]
geometry_msgs::msg::Point::Point (Point && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::Point that will be copied.
Definition at line 62 of file Point.cpp.
Member Function Documentation
deserialize()
void geometry_msgs::msg::Point::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 130 of file Point.cpp.
Referenced by geometry_msgs::msg::PointPubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::Point::getCdrSerializedSize (const geometry_msgs::msg::Point & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 109 of file Point.cpp.
Referenced by geometry_msgs::msg::Pose::getCdrSerializedSize(), and geometry_msgs::msg::PointPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::Point::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 222 of file Point.cpp.
References geometry_msgs_msg_Point_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::PointPubSubType::getKey(), and geometry_msgs::msg::PointPubSubType::PointPubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::Point::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 102 of file Point.cpp.
References geometry_msgs_msg_Point_max_cdr_typesize.
Referenced by geometry_msgs::msg::PointPubSubType::PointPubSubType().
isKeyDefined()
bool geometry_msgs::msg::Point::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 229 of file Point.cpp.
Referenced by geometry_msgs::msg::PointPubSubType::PointPubSubType().
operator!=()
bool geometry_msgs::msg::Point::operator!= (const Point & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Point object to compare.
Definition at line 96 of file Point.cpp.
operator=() [1/2]
geometry_msgs::msg::Point & geometry_msgs::msg::Point::operator= (const Point & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::Point that will be copied.
Definition at line 70 of file Point.cpp.
References m_x, m_y, and m_z.
operator=() [2/2]
geometry_msgs::msg::Point & geometry_msgs::msg::Point::operator= (Point && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::Point that will be copied.
Definition at line 80 of file Point.cpp.
References m_x.
operator==()
bool geometry_msgs::msg::Point::operator== (const Point & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Point object to compare.
Definition at line 90 of file Point.cpp.
References m_x, m_y, and m_z.
serialize()
void geometry_msgs::msg::Point::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 122 of file Point.cpp.
Referenced by geometry_msgs::msg::PointPubSubType::serialize().
serializeKey()
void geometry_msgs::msg::Point::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 234 of file Point.cpp.
Referenced by geometry_msgs::msg::PointPubSubType::getKey().
x() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Point::x ()
This function returns a reference to member x.
Returns
Reference to member x
x() [2/3]
double & geometry_msgs::msg::Point::x () const
This function returns the value of member x.
This function returns a reference to member x.
Returns
Value of member x
Reference to member x
Definition at line 152 of file Point.cpp.
x() [3/3]
void geometry_msgs::msg::Point::x (double _x)
This function sets a value in member x.
Parameters
_x New value for member x
Definition at line 142 of file Point.cpp.
y() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Point::y ()
This function returns a reference to member y.
Returns
Reference to member y
y() [2/3]
double & geometry_msgs::msg::Point::y () const
This function returns the value of member y.
This function returns a reference to member y.
Returns
Value of member y
Reference to member y
Definition at line 180 of file Point.cpp.
y() [3/3]
void geometry_msgs::msg::Point::y (double _y)
This function sets a value in member y.
Parameters
_y New value for member y
Definition at line 170 of file Point.cpp.
z() [1/3]
eProsima_user_DllExport double& geometry_msgs::msg::Point::z ()
This function returns a reference to member z.
Returns
Reference to member z
z() [2/3]
double & geometry_msgs::msg::Point::z () const
This function returns the value of member z.
This function returns a reference to member z.
Returns
Value of member z
Reference to member z
Definition at line 208 of file Point.cpp.
z() [3/3]
void geometry_msgs::msg::Point::z (double _z)
This function sets a value in member z.
Parameters
_z New value for member z
Definition at line 198 of file Point.cpp.
Member Data Documentation
m_x
double geometry_msgs::msg::Point::m_x private
Definition at line 238 of file Point.h.
Referenced by operator=(), operator==(), and Point().
m_y
double geometry_msgs::msg::Point::m_y private
Definition at line 239 of file Point.h.
Referenced by operator=(), operator==(), and Point().
m_z
double geometry_msgs::msg::Point::m_z private
Definition at line 240 of file Point.h.
Referenced by operator=(), operator==(), and Point().
The documentation for this class was generated from the following files:
Point.h
Point.cpp