CARLA: carla::client::Light Class Reference
carla::client::Light Class Reference
#include <Light.h>
Public Member Functions
Color GetColor () const
LightId GetId () const
float GetIntensity () const
LightGroup GetLightGroup () const
LightState GetLightState () const
const geom::Location GetLocation () const
bool IsOff () const
bool IsOn () const
Light ()
void SetColor (Color color)
void SetIntensity (float intensity)
void SetLightGroup (LightGroup group)
void SetLightState (const LightState &state)
void TurnOff ()
void TurnOn ()
Private Types
using LightGroup = rpc::LightState::LightGroup
Private Member Functions
Light (SharedPtr< LightManager > light_manager, geom::Location location, LightId id)
Private Attributes
LightId _id
SharedPtr< LightManager > _light_manager
geom::Location _location
Friends
class LightManager
Detailed Description
Definition at line 21 of file Light.h.
Member Typedef Documentation
LightGroup
using carla::client::Light::LightGroup = rpc::LightState::LightGroup private
Definition at line 23 of file Light.h.
Constructor & Destructor Documentation
Light() [1/2]
carla::client::Light::Light () inline
Definition at line 27 of file Light.h.
References GetColor().
Light() [2/2]
carla::client::Light::Light (SharedPtr< LightManager > light_manager, geom::Location location, LightId id) inline private
Definition at line 65 of file Light.h.
Member Function Documentation
GetColor()
Color carla::client::Light::GetColor () const
Definition at line 18 of file Light.cpp.
References _id, and _light_manager.
Referenced by Light().
GetId()
LightId carla::client::Light::GetId () const inline
Definition at line 31 of file Light.h.
References _id, and GetIntensity().
GetIntensity()
float carla::client::Light::GetIntensity () const
Definition at line 23 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetId().
GetLightGroup()
LightGroup carla::client::Light::GetLightGroup () const
Definition at line 28 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
GetLightState()
LightState carla::client::Light::GetLightState () const
Definition at line 33 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
GetLocation()
const geom::Location carla::client::Light::GetLocation () const inline
Definition at line 37 of file Light.h.
References _location, GetLightGroup(), GetLightState(), IsOff(), IsOn(), SetColor(), SetIntensity(), SetLightGroup(), SetLightState(), TurnOff(), and TurnOn().
IsOff()
bool carla::client::Light::IsOff () const
Definition at line 43 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
IsOn()
bool carla::client::Light::IsOn () const
Definition at line 38 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
SetColor()
void carla::client::Light::SetColor (Color color)
Definition at line 48 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
SetIntensity()
void carla::client::Light::SetIntensity (float intensity)
Definition at line 53 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
SetLightGroup()
void carla::client::Light::SetLightGroup (LightGroup group)
Definition at line 58 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
SetLightState()
void carla::client::Light::SetLightState (const LightState & state)
Definition at line 63 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
TurnOff()
void carla::client::Light::TurnOff ()
Definition at line 73 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
TurnOn()
void carla::client::Light::TurnOn ()
Definition at line 68 of file Light.cpp.
References _id, and _light_manager.
Referenced by GetLocation().
Friends And Related Function Documentation
LightManager
friend class LightManager friend
Definition at line 63 of file Light.h.
Member Data Documentation
_id
LightId carla::client::Light::_id private
Definition at line 75 of file Light.h.
Referenced by GetColor(), GetId(), GetIntensity(), GetLightGroup(), GetLightState(), IsOff(), IsOn(), SetColor(), SetIntensity(), SetLightGroup(), SetLightState(), TurnOff(), and TurnOn().
_light_manager
SharedPtr<LightManager> carla::client::Light::_light_manager private
Definition at line 72 of file Light.h.
Referenced by GetColor(), GetIntensity(), GetLightGroup(), GetLightState(), IsOff(), IsOn(), SetColor(), SetIntensity(), SetLightGroup(), SetLightState(), TurnOff(), and TurnOn().
_location
geom::Location carla::client::Light::_location private
Definition at line 73 of file Light.h.
Referenced by GetLocation().
The documentation for this class was generated from the following files:
Light.h
Light.cpp