CARLA: carla::geom::Rotation Class Reference
carla::geom::Rotation Class Reference
#include <Rotation.h>
Public Member Functions
Vector3D GetForwardVector () const
Vector3D GetRightVector () const
Vector3D GetUpVector () const
void InverseRotateVector (Vector3D &in_point) const
MSGPACK_DEFINE_ARRAY (pitch, yaw, roll)
bool operator!= (const Rotation &rhs) const
bool operator== (const Rotation &rhs) const
void RotateVector (Vector3D &in_point) const
Rotation ()=default
Rotation (float p, float y, float r)
Public Attributes
float pitch = 0.0f
float roll = 0.0f
float yaw = 0.0f
Detailed Description
Definition at line 20 of file Rotation.h.
Constructor & Destructor Documentation
Rotation() [1/2]
carla::geom::Rotation::Rotation () default
Referenced by operator!=().
Rotation() [2/2]
carla::geom::Rotation::Rotation (float p, float y, float r) inline
Definition at line 41 of file Rotation.h.
Member Function Documentation
GetForwardVector()
Vector3D carla::geom::Rotation::GetForwardVector () const inline
Definition at line 50 of file Rotation.h.
References carla::geom::Math::GetForwardVector().
Referenced by carla::geom::Transform::GetForwardVector(), and TEST().
GetRightVector()
Vector3D carla::geom::Rotation::GetRightVector () const inline
Definition at line 54 of file Rotation.h.
References carla::geom::Math::GetRightVector().
Referenced by carla::geom::Transform::GetRightVector().
GetUpVector()
Vector3D carla::geom::Rotation::GetUpVector () const inline
Definition at line 58 of file Rotation.h.
References carla::geom::Math::GetUpVector().
Referenced by ACarlaGameModeBase::DebugShowSignals(), and carla::geom::Transform::GetUpVector().
InverseRotateVector()
void carla::geom::Rotation::InverseRotateVector (Vector3D & in_point) const inline
Definition at line 90 of file Rotation.h.
References carla::geom::Math::ToRadians(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::rss::RssCheck::GetSpeed(), and carla::geom::Transform::InverseTransformPoint().
MSGPACK_DEFINE_ARRAY()
carla::geom::Rotation::MSGPACK_DEFINE_ARRAY (pitch , yaw , roll)
operator!=()
bool carla::geom::Rotation::operator!= (const Rotation & rhs) const inline
Definition at line 127 of file Rotation.h.
References pitch, Rotation(), and yaw.
operator==()
bool carla::geom::Rotation::operator== (const Rotation & rhs) const inline
Definition at line 123 of file Rotation.h.
References pitch, roll, and yaw.
RotateVector()
void carla::geom::Rotation::RotateVector (Vector3D & in_point) const inline
Definition at line 62 of file Rotation.h.
References carla::geom::Math::ToRadians(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::geom::Transform::TransformPoint().
Member Data Documentation
pitch
float carla::geom::Rotation::pitch = 0.0f
Definition at line 27 of file Rotation.h.
Referenced by carla::road::Lane::ComputeTransform(), carla::geom::Math::GetForwardVector(), carla::geom::Transform::GetInverseMatrix(), carla::geom::Transform::GetMatrix(), carla::geom::Math::GetRightVector(), carla::geom::Math::GetUpVector(), operator!=(), and operator==().
roll
float carla::geom::Rotation::roll = 0.0f
Definition at line 31 of file Rotation.h.
Referenced by carla::geom::Transform::GetInverseMatrix(), carla::geom::Transform::GetMatrix(), carla::geom::Math::GetRightVector(), carla::geom::Math::GetUpVector(), and operator==().
yaw
float carla::geom::Rotation::yaw = 0.0f
Definition at line 29 of file Rotation.h.
Referenced by carla::nav::Navigation::AddOrUpdateVehicle(), carla::road::Lane::ComputeTransform(), carla::road::Map::GetAllCrosswalkZones(), carla::geom::Math::GetForwardVector(), carla::geom::Transform::GetInverseMatrix(), carla::geom::Transform::GetMatrix(), carla::geom::Math::GetRightVector(), carla::geom::Math::GetUpVector(), carla::nav::Navigation::GetWalkerTransform(), carla::client::LaneInvasionCallback::MakeBounds(), operator!=(), and operator==().
The documentation for this class was generated from the following file:
Rotation.h