CARLA: moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP Struct Reference
moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP Struct Reference
Public Member Functions
ImplicitProducerKVP ()
ImplicitProducerKVP (ImplicitProducerKVP &&other) MOODYCAMEL_NOEXCEPT
ImplicitProducerKVP & operator= (ImplicitProducerKVP &&other) MOODYCAMEL_NOEXCEPT
void swap (ImplicitProducerKVP &other) MOODYCAMEL_NOEXCEPT
Public Attributes
std::atomic< details::thread_id_t > key
ImplicitProducer * value
Detailed Description
template<typename T, typename Traits = ConcurrentQueueDefaultTraits>
struct moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP
Definition at line 3218 of file ConcurrentQueue.h.
Constructor & Destructor Documentation
template<typename T, typename Traits = ConcurrentQueueDefaultTraits> moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::ImplicitProducerKVP () inline
Definition at line 3223 of file ConcurrentQueue.h.
template<typename T, typename Traits = ConcurrentQueueDefaultTraits> moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::ImplicitProducerKVP (ImplicitProducerKVP && other) inline
Definition at line 3225 of file ConcurrentQueue.h.
Member Function Documentation
template<typename T, typename Traits = ConcurrentQueueDefaultTraits> ImplicitProducerKVP& moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::operator= (ImplicitProducerKVP && other) inline
Definition at line 3231 of file ConcurrentQueue.h.
References moodycamel::swap().
template<typename T, typename Traits = ConcurrentQueueDefaultTraits> void moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::swap (ImplicitProducerKVP & other) inline
Definition at line 3237 of file ConcurrentQueue.h.
References MOODYCAMEL_NOEXCEPT, moodycamel::swap(), swap(), and moodycamel::details::swap_relaxed().
Member Data Documentation
template<typename T, typename Traits = ConcurrentQueueDefaultTraits> std::atomic<details::thread_id_t> moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::key
Definition at line 3220 of file ConcurrentQueue.h.
template<typename T, typename Traits = ConcurrentQueueDefaultTraits> ImplicitProducer* moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::value
Definition at line 3221 of file ConcurrentQueue.h.
The documentation for this struct was generated from the following file:
ConcurrentQueue.h