CARLA: carla::rpc::Color Class Reference
carla::rpc::Color Class Reference
#include <Color.h>
Public Member Functions
Color ()=default
Color (const Color &)=default
Color (uint8_t r, uint8_t g, uint8_t b)
MSGPACK_DEFINE_ARRAY (r, g, b)
Color & operator= (const Color &)=default
Public Attributes
uint8_t b = 0u
uint8_t g = 0u
uint8_t r = 0u
Detailed Description
Definition at line 20 of file rpc/Color.h.
Constructor & Destructor Documentation
carla::rpc::Color::Color () default
Referenced by Color().
carla::rpc::Color::Color (const Color &) default
carla::rpc::Color::Color (uint8_t r, uint8_t g, uint8_t b) inline
Definition at line 30 of file rpc/Color.h.
References Color(), g, MSGPACK_DEFINE_ARRAY(), operator=(), and r.
Member Function Documentation
carla::rpc::Color::MSGPACK_DEFINE_ARRAY (r , g , b)
Referenced by Color().
Color& carla::rpc::Color::operator= (const Color &) default
Referenced by Color().
Member Data Documentation
uint8_t carla::rpc::Color::b = 0u
Definition at line 25 of file rpc/Color.h.
uint8_t carla::rpc::Color::g = 0u
Definition at line 24 of file rpc/Color.h.
Referenced by Color().
uint8_t carla::rpc::Color::r = 0u
Definition at line 23 of file rpc/Color.h.
Referenced by Color().
The documentation for this class was generated from the following file:
rpc/Color.h