CARLA: traffic_manager::InMemoryMap Class Reference
traffic_manager::InMemoryMap Class Reference
This class builds a discretized local map-cache.
#include <InMemoryMap.h>
Public Member Functions
NodeList GetDenseTopology () const
This method returns the full list of discrete samples of the map in the local cache.
SimpleWaypointPtr GetWaypoint (const cg::Location &location) const
This method returns the closest waypoint to a given location on the map.
SimpleWaypointPtr GetWaypointInVicinity (cg::Location location)
This method returns closest waypoint in the vicinity of the given co-ordinates.
InMemoryMap (TopologyList topology)
void SetUp (float sampling_resolution)
This method constructs the local map with a resolution of sampling_resolution.
~InMemoryMap ()
Private Member Functions
void FindAndLinkLaneChange (SimpleWaypointPtr reference_waypoint)
This method is used to find and place lane change links.
std::pair< int, int > MakeGridId (float x, float y)
Method to generate the grid ids for given co-ordinates.
std::string MakeGridKey (std::pair< int, int > gird_id)
Method to generate map key for waypoint_grid.
Private Attributes
TopologyList _topology
Object to hold sparse topology received by the constructor.
NodeList dense_topology
Structure to hold all custom waypoint objects after interpolation of sparse topology.
std::unordered_map< std::string, std::unordered_set< SimpleWaypointPtr > > waypoint_grid
Grid localization map for all waypoints in the system.
Detailed Description
This class builds a discretized local map-cache.
Instantiate the class with map topology from the simulator and run SetUp() to construct the local map.
Definition at line 38 of file InMemoryMap.h.
Constructor & Destructor Documentation
traffic_manager::InMemoryMap::InMemoryMap (TopologyList topology)
Definition at line 25 of file InMemoryMap.cpp.
traffic_manager::InMemoryMap::~InMemoryMap ()
Definition at line 28 of file InMemoryMap.cpp.
Member Function Documentation
void traffic_manager::InMemoryMap::FindAndLinkLaneChange (SimpleWaypointPtr reference_waypoint) private
This method is used to find and place lane change links.
Definition at line 209 of file InMemoryMap.cpp.
References carla::log_info(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
std::vector< SimpleWaypointPtr > traffic_manager::InMemoryMap::GetDenseTopology () const
This method returns the full list of discrete samples of the map in the local cache.
Definition at line 205 of file InMemoryMap.cpp.
SimpleWaypointPtr traffic_manager::InMemoryMap::GetWaypoint (const cg::Location & location) const
This method returns the closest waypoint to a given location on the map.
Definition at line 191 of file InMemoryMap.cpp.
References traffic_manager::MapConstants::INFINITE_DISTANCE.
Referenced by traffic_manager::LocalizationStage::Action().
SimpleWaypointPtr traffic_manager::InMemoryMap::GetWaypointInVicinity (cg::Location location)
This method returns closest waypoint in the vicinity of the given co-ordinates.
Definition at line 151 of file InMemoryMap.cpp.
References traffic_manager::MapConstants::INFINITE_DISTANCE, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by traffic_manager::LocalizationStage::Action().
std::pair< int, int > traffic_manager::InMemoryMap::MakeGridId (float x, float y) private
Method to generate the grid ids for given co-ordinates.
Definition at line 143 of file InMemoryMap.cpp.
References traffic_manager::MapConstants::GRID_SIZE.
std::string traffic_manager::InMemoryMap::MakeGridKey (std::pair< int, int > gird_id) private
Method to generate map key for waypoint_grid.
Definition at line 147 of file InMemoryMap.cpp.
void traffic_manager::InMemoryMap::SetUp (float sampling_resolution)
This method constructs the local map with a resolution of sampling_resolution.
Definition at line 30 of file InMemoryMap.cpp.
References carla::geom::Math::DistanceSquared(), carla::geom::Math::Dot(), traffic_manager::MapConstants::INFINITE_DISTANCE, traffic_manager::MapConstants::LANE_CHANGE_ANGULAR_THRESHOLD, traffic_manager::MapConstants::LANE_CHANGE_LOOK_AHEAD, carla::geom::Vector3D::MakeUnitVector(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and traffic_manager::MapConstants::ZERO_LENGTH.
Member Data Documentation
TopologyList traffic_manager::InMemoryMap::_topology private
Object to hold sparse topology received by the constructor.
Definition at line 43 of file InMemoryMap.h.
NodeList traffic_manager::InMemoryMap::dense_topology private
Structure to hold all custom waypoint objects after interpolation of sparse topology.
Definition at line 46 of file InMemoryMap.h.
std::unordered_map<std::string, std::unordered_set<SimpleWaypointPtr> > traffic_manager::InMemoryMap::waypoint_grid private
Grid localization map for all waypoints in the system.
Definition at line 48 of file InMemoryMap.h.
The documentation for this class was generated from the following files:
InMemoryMap.h
InMemoryMap.cpp