CARLA: carla::sensor::Deserializer Class Reference
carla::sensor::Deserializer Class Reference
Deserializes a Buffer containing data generated by a sensor and creates the appropriate SensorData class that contains the sensor's measurement.
#include <Deserializer.h>
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (Buffer &&buffer)
Detailed Description
Deserializes a Buffer containing data generated by a sensor and creates the appropriate SensorData class that contains the sensor's measurement.
This class encapsulates the SensorRegistry to avoid including all the serializers and SensorData classes.
Definition at line 22 of file Deserializer.h.
Member Function Documentation
SharedPtr< SensorData > carla::sensor::Deserializer::Deserialize (Buffer && buffer) static
Definition at line 14 of file Deserializer.cpp.
References carla::sensor::CompositeSerializer< Items >::Deserialize().
Referenced by carla::client::detail::Episode::Listen(), and carla::client::detail::Simulator::SubscribeToSensor().
The documentation for this class was generated from the following files:
Deserializer.h
Deserializer.cpp