CARLA: carla::client::GnssCallback Class Reference
carla::client::GnssCallback Class Reference
Public Member Functions
GnssCallback (ActorId sensor_id, geom::GeoLocation geo_reference, Sensor::CallbackFunctionType &&user_callback)
void operator() (const WorldSnapshot &snapshot) const
Private Attributes
Sensor::CallbackFunctionType _callback
geom::GeoLocation _geo_reference
ActorId _sensor_id
Detailed Description
Definition at line 23 of file LibCarla/source/carla/client/GnssSensor.cpp.
Constructor & Destructor Documentation
carla::client::GnssCallback::GnssCallback (ActorId sensor_id, geom::GeoLocation geo_reference, Sensor::CallbackFunctionType && user_callback) inline
Definition at line 26 of file LibCarla/source/carla/client/GnssSensor.cpp.
References operator()().
Referenced by carla::client::GnssSensor::Listen().
Member Function Documentation
void carla::client::GnssCallback::operator() (const WorldSnapshot & snapshot) const
Definition at line 45 of file LibCarla/source/carla/client/GnssSensor.cpp.
References _callback, _geo_reference, _sensor_id, carla::client::Timestamp::elapsed_seconds, carla::client::WorldSnapshot::Find(), carla::client::Timestamp::frame, carla::client::WorldSnapshot::GetTimestamp(), carla::log_error(), and carla::geom::GeoLocation::Transform().
Referenced by GnssCallback().
Member Data Documentation
Sensor::CallbackFunctionType carla::client::GnssCallback::_callback private
Definition at line 42 of file LibCarla/source/carla/client/GnssSensor.cpp.
Referenced by operator()().
geom::GeoLocation carla::client::GnssCallback::_geo_reference private
Definition at line 40 of file LibCarla/source/carla/client/GnssSensor.cpp.
Referenced by operator()().
ActorId carla::client::GnssCallback::_sensor_id private
Definition at line 38 of file LibCarla/source/carla/client/GnssSensor.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
LibCarla/source/carla/client/GnssSensor.cpp