CARLA: std_msgs::msg::Float32 Class Reference
std_msgs::msg::Float32 Class Reference
This class represents the structure Float32 defined by the user in the IDL file.
#include <Float32.h>
Public Member Functions
eProsima_user_DllExport float & data ()
This function returns a reference to member data.
eProsima_user_DllExport float data () const
This function returns the value of member data.
eProsima_user_DllExport void data (float _data)
This function sets a value in member data.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport Float32 ()
Default constructor.
eProsima_user_DllExport Float32 (const Float32 &x)
Copy constructor.
eProsima_user_DllExport Float32 (Float32 &&x) noexcept
Move constructor.
eProsima_user_DllExport bool operator!= (const Float32 &x) const
Comparison operator.
eProsima_user_DllExport Float32 & operator= (const Float32 &x)
Copy assignment.
eProsima_user_DllExport Float32 & operator= (Float32 &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Float32 &x) const
Comparison operator.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport ~Float32 ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const std_msgs::msg::Float32 &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
float m_data
Detailed Description
This class represents the structure Float32 defined by the user in the IDL file.
Definition at line 70 of file Float32.h.
Constructor & Destructor Documentation
Float32() [1/3]
std_msgs::msg::Float32::Float32 ()
Default constructor.
Definition at line 40 of file Float32.cpp.
~Float32()
std_msgs::msg::Float32::~Float32 ()
Default destructor.
Definition at line 45 of file Float32.cpp.
Float32() [2/3]
std_msgs::msg::Float32::Float32 (const Float32 & x)
Copy constructor.
Parameters
x Reference to the object std_msgs::msg::Float32 that will be copied.
Definition at line 49 of file Float32.cpp.
References m_data.
Float32() [3/3]
std_msgs::msg::Float32::Float32 (Float32 && x) noexcept
Move constructor.
Parameters
x Reference to the object std_msgs::msg::Float32 that will be copied.
Definition at line 55 of file Float32.cpp.
Member Function Documentation
data() [1/3]
eProsima_user_DllExport float& std_msgs::msg::Float32::data ()
This function returns a reference to member data.
Returns
Reference to member data
data() [2/3]
float & std_msgs::msg::Float32::data () const
This function returns the value of member data.
This function returns a reference to member data.
Returns
Value of member data
Reference to member data
Definition at line 130 of file Float32.cpp.
data() [3/3]
void std_msgs::msg::Float32::data (float _data)
This function sets a value in member data.
Parameters
_data New value for member data
Definition at line 120 of file Float32.cpp.
deserialize()
void std_msgs::msg::Float32::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 110 of file Float32.cpp.
Referenced by std_msgs::msg::Float32PubSubType::deserialize().
getCdrSerializedSize()
size_t std_msgs::msg::Float32::getCdrSerializedSize (const std_msgs::msg::Float32 & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 94 of file Float32.cpp.
Referenced by std_msgs::msg::Float32PubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t std_msgs::msg::Float32::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 144 of file Float32.cpp.
References std_msgs_msg_Float32_max_key_cdr_typesize.
Referenced by std_msgs::msg::Float32PubSubType::Float32PubSubType(), and std_msgs::msg::Float32PubSubType::getKey().
getMaxCdrSerializedSize()
size_t std_msgs::msg::Float32::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 87 of file Float32.cpp.
References std_msgs_msg_Float32_max_cdr_typesize.
Referenced by std_msgs::msg::Float32PubSubType::Float32PubSubType().
isKeyDefined()
bool std_msgs::msg::Float32::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 151 of file Float32.cpp.
Referenced by std_msgs::msg::Float32PubSubType::Float32PubSubType().
operator!=()
bool std_msgs::msg::Float32::operator!= (const Float32 & x) const
Comparison operator.
Parameters
x std_msgs::msg::Float32 object to compare.
Definition at line 81 of file Float32.cpp.
operator=() [1/2]
std_msgs::msg::Float32 & std_msgs::msg::Float32::operator= (const Float32 & x)
Copy assignment.
Parameters
x Reference to the object std_msgs::msg::Float32 that will be copied.
Definition at line 61 of file Float32.cpp.
References m_data.
operator=() [2/2]
std_msgs::msg::Float32 & std_msgs::msg::Float32::operator= (Float32 && x) noexcept
Move assignment.
Parameters
x Reference to the object std_msgs::msg::Float32 that will be copied.
Definition at line 68 of file Float32.cpp.
References m_data.
operator==()
bool std_msgs::msg::Float32::operator== (const Float32 & x) const
Comparison operator.
Parameters
x std_msgs::msg::Float32 object to compare.
Definition at line 75 of file Float32.cpp.
References m_data.
serialize()
void std_msgs::msg::Float32::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 104 of file Float32.cpp.
Referenced by std_msgs::msg::Float32PubSubType::serialize().
serializeKey()
void std_msgs::msg::Float32::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 156 of file Float32.cpp.
Referenced by std_msgs::msg::Float32PubSubType::getKey().
Member Data Documentation
m_data
float std_msgs::msg::Float32::m_data private
Definition at line 199 of file Float32.h.
Referenced by Float32(), operator=(), and operator==().
The documentation for this class was generated from the following files:
Float32.h
Float32.cpp