CARLA: carla::image::io Namespace Reference
carla::image::io Namespace Reference
Namespaces
detail
Classes
struct any
struct jpeg
struct png
struct tiff
Functions
constexpr bool has_jpeg_support ()
constexpr bool has_png_support ()
constexpr bool has_tiff_support ()
Function Documentation
constexpr bool carla::image::io::has_jpeg_support ()
Definition at line 81 of file ImageIOConfig.h.
References LIBCARLA_IMAGE_WITH_JPEG_SUPPORT.
Referenced by has_tiff_support(), and TEST().
constexpr bool carla::image::io::has_png_support ()
Definition at line 77 of file ImageIOConfig.h.
References LIBCARLA_IMAGE_WITH_PNG_SUPPORT.
Referenced by has_tiff_support(), and TEST().
constexpr bool carla::image::io::has_tiff_support ()
Definition at line 85 of file ImageIOConfig.h.
References has_jpeg_support(), has_png_support(), and LIBCARLA_IMAGE_WITH_TIFF_SUPPORT.
Referenced by TEST().