CARLA: carla::streaming::Server Class Reference
carla::streaming::Server Class Reference
A streaming server.
#include <Server.h>
Public Member Functions
void AsyncRun (size_t worker_threads)
auto GetLocalEndpoint () const
Stream MakeStream ()
void Run ()
Server (uint16_t port)
Server (const std::string &address, uint16_t port)
Server (const std::string &address, uint16_t port, const std::string &external_address, uint16_t external_port)
void SetTimeout (time_duration timeout)
~Server ()
Private Types
using protocol_type = low_level::Server< detail::tcp::Server >::protocol_type
using underlying_server = low_level::Server< detail::tcp::Server >
Private Attributes
ThreadPool _pool
underlying_server _server
Detailed Description
A streaming server.
Each new stream has a token associated, this token can be used by a client to subscribe to the stream.
Definition at line 20 of file streaming/Server.h.
Member Typedef Documentation
protocol_type
using carla::streaming::Server::protocol_type = low_level::Server<detail::tcp::Server>::protocol_type private
Definition at line 22 of file streaming/Server.h.
underlying_server
using carla::streaming::Server::underlying_server = low_level::Server<detail::tcp::Server> private
Definition at line 21 of file streaming/Server.h.
Constructor & Destructor Documentation
Server() [1/3]
carla::streaming::Server::Server (uint16_t port) inline explicit
Definition at line 25 of file streaming/Server.h.
Server() [2/3]
carla::streaming::Server::Server (const std::string & address, uint16_t port) inline explicit
Definition at line 28 of file streaming/Server.h.
Server() [3/3]
carla::streaming::Server::Server (const std::string & address, uint16_t port, const std::string & external_address, uint16_t external_port) inline explicit
Definition at line 31 of file streaming/Server.h.
~Server()
carla::streaming::Server::~Server () inline
Definition at line 39 of file streaming/Server.h.
References _pool, and carla::ThreadPool::Stop().
Member Function Documentation
AsyncRun()
void carla::streaming::Server::AsyncRun (size_t worker_threads) inline
Definition at line 59 of file streaming/Server.h.
References _pool, and carla::ThreadPool::AsyncRun().
GetLocalEndpoint()
auto carla::streaming::Server::GetLocalEndpoint () const inline
Definition at line 43 of file streaming/Server.h.
References _server, and carla::streaming::low_level::Server< T >::GetLocalEndpoint().
MakeStream()
Stream carla::streaming::Server::MakeStream () inline
Definition at line 51 of file streaming/Server.h.
References _server, and carla::streaming::low_level::Server< T >::MakeStream().
Run()
void carla::streaming::Server::Run () inline
Definition at line 55 of file streaming/Server.h.
References _pool, and carla::ThreadPool::Run().
SetTimeout()
void carla::streaming::Server::SetTimeout (time_duration timeout) inline
Definition at line 47 of file streaming/Server.h.
References _server, and carla::streaming::low_level::Server< T >::SetTimeout().
Member Data Documentation
_pool
ThreadPool carla::streaming::Server::_pool private
Definition at line 67 of file streaming/Server.h.
Referenced by AsyncRun(), Run(), and ~Server().
_server
underlying_server carla::streaming::Server::_server private
Definition at line 69 of file streaming/Server.h.
Referenced by GetLocalEndpoint(), MakeStream(), and SetTimeout().
The documentation for this class was generated from the following file:
streaming/Server.h