CARLA: sensor_msgs::msg::RegionOfInterestPubSubType Class Reference
sensor_msgs::msg::RegionOfInterestPubSubType Class Reference
This class represents the TopicDataType of the type RegionOfInterest defined by the user in the IDL file.
#include <RegionOfInterestPubSubTypes.h>
Public Types
typedef RegionOfInterest type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport RegionOfInterestPubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~RegionOfInterestPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type RegionOfInterest defined by the user in the IDL file.
Definition at line 73 of file RegionOfInterestPubSubTypes.h.
Member Typedef Documentation
type
typedef RegionOfInterest sensor_msgs::msg::RegionOfInterestPubSubType::type
Definition at line 77 of file RegionOfInterestPubSubTypes.h.
Constructor & Destructor Documentation
RegionOfInterestPubSubType()
sensor_msgs::msg::RegionOfInterestPubSubType::RegionOfInterestPubSubType ()
Definition at line 32 of file RegionOfInterestPubSubTypes.cpp.
References sensor_msgs::msg::RegionOfInterest::getKeyMaxCdrSerializedSize(), sensor_msgs::msg::RegionOfInterest::getMaxCdrSerializedSize(), sensor_msgs::msg::RegionOfInterest::isKeyDefined(), and m_keyBuffer.
~RegionOfInterestPubSubType()
sensor_msgs::msg::RegionOfInterestPubSubType::~RegionOfInterestPubSubType () override virtual
Definition at line 45 of file RegionOfInterestPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * sensor_msgs::msg::RegionOfInterestPubSubType::createData () override virtual
Definition at line 122 of file RegionOfInterestPubSubTypes.cpp.
deleteData()
void sensor_msgs::msg::RegionOfInterestPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file RegionOfInterestPubSubTypes.cpp.
deserialize()
bool sensor_msgs::msg::RegionOfInterestPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file RegionOfInterestPubSubTypes.cpp.
References sensor_msgs::msg::RegionOfInterest::deserialize().
getKey()
bool sensor_msgs::msg::RegionOfInterestPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file RegionOfInterestPubSubTypes.cpp.
References sensor_msgs::msg::RegionOfInterest::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and sensor_msgs::msg::RegionOfInterest::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> sensor_msgs::msg::RegionOfInterestPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file RegionOfInterestPubSubTypes.cpp.
References sensor_msgs::msg::RegionOfInterest::getCdrSerializedSize().
is_plain_impl()
static constexpr bool sensor_msgs::msg::RegionOfInterestPubSubType::is_plain_impl () inline static constexpr private
Definition at line 135 of file RegionOfInterestPubSubTypes.h.
serialize()
bool sensor_msgs::msg::RegionOfInterestPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file RegionOfInterestPubSubTypes.cpp.
References sensor_msgs::msg::RegionOfInterest::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* sensor_msgs::msg::RegionOfInterestPubSubType::m_keyBuffer
Definition at line 131 of file RegionOfInterestPubSubTypes.h.
Referenced by getKey(), RegionOfInterestPubSubType(), and ~RegionOfInterestPubSubType().
m_md5
MD5 sensor_msgs::msg::RegionOfInterestPubSubType::m_md5
Definition at line 130 of file RegionOfInterestPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
RegionOfInterestPubSubTypes.h
RegionOfInterestPubSubTypes.cpp