CARLA: carla::rss Namespace Reference
carla::rss Namespace Reference
Classes
struct ActorConstellationData
struct ActorConstellationResult
Struct defining the configuration for RSS processing of a given actor.
struct EgoDynamicsOnRoute
struct defining the ego vehicles current dynamics in respect to the current route
class RssCheck
class implementing the actual RSS checks based on CARLA world description
class RssRestrictor
class implementing the RSS restrictions within CARLA
Enumerations
enum RoadBoundariesMode { RoadBoundariesMode::Off, RoadBoundariesMode::On }
struct defining the different supported handling of road boundaries
Functions
std::shared_ptr< spdlog::logger > getLogger ()
std::shared_ptr< spdlog::logger > getTimingLogger ()
void printRoute (std::string const &route_descr,::ad::map::route::FullRoute const &route)
Variables
constexpr float to_radians = static_cast<float>(M_PI) / 180.0f
Enumeration Type Documentation
enum carla::rss::RoadBoundariesMode strong
struct defining the different supported handling of road boundaries
Enumerator
Off
On
No road boundaries considered by RSS check.
The road boundaries of the current route are considered by RSS check
Definition at line 28 of file RssCheck.h.
Function Documentation
std::shared_ptr<spdlog::logger> carla::rss::getLogger ()
Definition at line 78 of file RssCheck.cpp.
Referenced by carla::rss::RssCheck::RssCheck(), and carla::rss::RssCheck::SetLogLevel().
std::shared_ptr<spdlog::logger> carla::rss::getTimingLogger ()
Definition at line 83 of file RssCheck.cpp.
Referenced by carla::rss::RssCheck::RssCheck().
void carla::rss::printRoute (std::string const & route_descr, ::ad::map::route::FullRoute const & route)
Definition at line 40 of file RssCheck.cpp.
Variable Documentation
constexpr float carla::rss::to_radians = static_cast<float>(M_PI) / 180.0f
Definition at line 53 of file RssCheck.cpp.