CARLA: carla::client::ServerSideSensor Class Reference
carla::client::ServerSideSensor Class Reference final
#include <ServerSideSensor.h>
Public Member Functions
bool Destroy () override
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
bool IsListening () const override
Return whether this Sensor instance is currently listening to the associated sensor in the simulator.
void Listen (CallbackFunctionType callback) override
Register a callback to be executed each time a new measurement is received.
void Stop () override
Stop listening for new measurements.
~ServerSideSensor ()
Public Member Functions inherited from carla::client::Actor
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
geom::Location GetLocation () const
Return the current location of the actor.
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsAlive () const
const auto & Serialize () const
void SetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor.
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
void SetVelocity (const geom::Vector3D &vector)
Set the actor velocity.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Private Attributes
bool _is_listening = false
Additional Inherited Members
Public Types inherited from carla::client::Sensor
using CallbackFunctionType = std::function< void(SharedPtr< sensor::SensorData >)>
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Detailed Description
Definition at line 14 of file ServerSideSensor.h.
Constructor & Destructor Documentation
~ServerSideSensor()
carla::client::ServerSideSensor::~ServerSideSensor ()
Definition at line 19 of file ServerSideSensor.cpp.
References carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), carla::client::Actor::IsAlive(), IsListening(), IsValid(), carla::log_error(), carla::log_warning(), and Stop().
Member Function Documentation
Destroy()
bool carla::client::ServerSideSensor::Destroy () override virtual
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
Note
It has no effect if the Actor was already successfully destroyed.
Warning
This function blocks until the destruction operation is completed by the simulator.
Additionally stop listening.
Reimplemented from carla::client::Actor.
Definition at line 52 of file ServerSideSensor.cpp.
References carla::client::Actor::Destroy(), IsListening(), and Stop().
Referenced by IsListening().
IsListening()
bool carla::client::ServerSideSensor::IsListening () const inline override virtual
Return whether this Sensor instance is currently listening to the associated sensor in the simulator.
Implements carla::client::Sensor.
Definition at line 35 of file ServerSideSensor.h.
References _is_listening, and Destroy().
Referenced by Destroy(), and ~ServerSideSensor().
Listen()
void carla::client::ServerSideSensor::Listen (CallbackFunctionType callback) override virtual
Register a callback to be executed each time a new measurement is received.
Warning
Calling this function on a sensor that is already listening steals the data stream from the previously set callback. Note that several instances of Sensor (even in different processes) may point to the same sensor in the simulator.
Implements carla::client::Sensor.
Definition at line 35 of file ServerSideSensor.cpp.
References _is_listening, carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::log_debug().
Stop()
void carla::client::ServerSideSensor::Stop (void) override virtual
Stop listening for new measurements.
Implements carla::client::Sensor.
Definition at line 41 of file ServerSideSensor.cpp.
References _is_listening, carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::log_warning().
Referenced by Destroy(), and ~ServerSideSensor().
Member Data Documentation
_is_listening
bool carla::client::ServerSideSensor::_is_listening = false private
Definition at line 46 of file ServerSideSensor.h.
Referenced by IsListening(), Listen(), and Stop().
The documentation for this class was generated from the following files:
ServerSideSensor.h
ServerSideSensor.cpp