CARLA: carla::streaming::low_level::Server< T > Class Template Reference
carla::streaming::low_level::Server< T > Class Template Reference
A low-level streaming server.
#include <Server.h>
Public Types
using protocol_type = typename underlying_server::protocol_type
using underlying_server = T
Public Member Functions
underlying_server::endpoint GetLocalEndpoint () const
carla::streaming::detail::token_type GetToken (carla::streaming::detail::stream_id_type sensor_id)
Stream MakeStream ()
template<typename InternalEPType , typename ExternalEPType >
Server (boost::asio::io_context &io_context, detail::EndPoint< protocol_type, InternalEPType > internal_ep, detail::EndPoint< protocol_type, ExternalEPType > external_ep)
template<typename InternalEPType >
Server (boost::asio::io_context &io_context, detail::EndPoint< protocol_type, InternalEPType > internal_ep)
template<typename... EPArgs>
Server (boost::asio::io_context &io_context, EPArgs &&... args)
void SetSynchronousMode (bool is_synchro)
void SetTimeout (time_duration timeout)
Private Member Functions
void StartServer ()
Private Attributes
detail::Dispatcher _dispatcher
underlying_server _server
Detailed Description
template<typename T>
class carla::streaming::low_level::Server< T >
A low-level streaming server.
Each new stream has a token associated, this token can be used by a client to subscribe to the stream. This server requires an external io_context running.
Warning
This server cannot be destructed before its io_context is stopped.
Definition at line 26 of file streaming/low_level/Server.h.
Member Typedef Documentation
protocol_type
template<typename T> using carla::streaming::low_level::Server< T >::protocol_type = typename underlying_server::protocol_type
Definition at line 31 of file streaming/low_level/Server.h.
underlying_server
template<typename T> using carla::streaming::low_level::Server< T >::underlying_server = T
Definition at line 29 of file streaming/low_level/Server.h.
Constructor & Destructor Documentation
Server() [1/3]
template<typename T> template<typename InternalEPType , typename ExternalEPType > carla::streaming::low_level::Server< T >::Server (boost::asio::io_context & io_context, detail::EndPoint< protocol_type, InternalEPType > internal_ep, detail::EndPoint< protocol_type, ExternalEPType > external_ep) inline explicit
Definition at line 34 of file streaming/low_level/Server.h.
Server() [2/3]
template<typename T> template<typename InternalEPType > carla::streaming::low_level::Server< T >::Server (boost::asio::io_context & io_context, detail::EndPoint< protocol_type, InternalEPType > internal_ep) inline explicit
Definition at line 44 of file streaming/low_level/Server.h.
Server() [3/3]
template<typename T> template<typename... EPArgs> carla::streaming::low_level::Server< T >::Server (boost::asio::io_context & io_context, EPArgs &&... args) inline explicit
Definition at line 53 of file streaming/low_level/Server.h.
Member Function Documentation
GetLocalEndpoint()
template<typename T> underlying_server::endpoint carla::streaming::low_level::Server< T >::GetLocalEndpoint () const inline
Definition at line 56 of file streaming/low_level/Server.h.
Referenced by carla::streaming::Server::GetLocalEndpoint().
GetToken()
template<typename T> carla::streaming::detail::token_type carla::streaming::low_level::Server< T >::GetToken (carla::streaming::detail::stream_id_type sensor_id) inline
Definition at line 72 of file streaming/low_level/Server.h.
Referenced by carla::streaming::Server::GetToken().
MakeStream()
template<typename T> Stream carla::streaming::low_level::Server< T >::MakeStream () inline
Definition at line 64 of file streaming/low_level/Server.h.
Referenced by carla::streaming::Server::MakeStream(), and TEST().
SetSynchronousMode()
template<typename T> void carla::streaming::low_level::Server< T >::SetSynchronousMode (bool is_synchro) inline
Definition at line 68 of file streaming/low_level/Server.h.
Referenced by carla::streaming::Server::SetSynchronousMode().
SetTimeout()
template<typename T> void carla::streaming::low_level::Server< T >::SetTimeout (time_duration timeout) inline
Definition at line 60 of file streaming/low_level/Server.h.
Referenced by carla::streaming::Server::SetTimeout(), and TEST().
StartServer()
template<typename T> void carla::streaming::low_level::Server< T >::StartServer () inline private
Definition at line 78 of file streaming/low_level/Server.h.
Referenced by carla::streaming::low_level::Server< detail::tcp::Server >::Server().
Member Data Documentation
_dispatcher
template<typename T> detail::Dispatcher carla::streaming::low_level::Server< T >::_dispatcher private
Definition at line 92 of file streaming/low_level/Server.h.
Referenced by carla::streaming::low_level::Server< detail::tcp::Server >::GetToken(), carla::streaming::low_level::Server< detail::tcp::Server >::MakeStream(), and carla::streaming::low_level::Server< detail::tcp::Server >::StartServer().
_server
template<typename T> underlying_server carla::streaming::low_level::Server< T >::_server private
Definition at line 90 of file streaming/low_level/Server.h.
Referenced by carla::streaming::low_level::Server< detail::tcp::Server >::GetLocalEndpoint(), carla::streaming::low_level::Server< detail::tcp::Server >::SetSynchronousMode(), carla::streaming::low_level::Server< detail::tcp::Server >::SetTimeout(), and carla::streaming::low_level::Server< detail::tcp::Server >::StartServer().
The documentation for this class was generated from the following file:
streaming/low_level/Server.h