CARLA: carla::traffic_manager::VicinityGrid Class Reference
carla::traffic_manager::VicinityGrid Class Reference
This class maintains vehicle positions in grid segments.
#include <VicinityGrid.h>
Public Member Functions
void EraseActor (ActorId actor_id)
Removes actor.
std::unordered_set< ActorId > GetActors (Actor actor)
Returns a set of actors in the vicinity of a given actor.
std::pair< int, int > UpdateGrid (Actor actor)
Updates the grid position of the given actor and returns new grid id.
VicinityGrid ()
~VicinityGrid ()
Private Member Functions
std::string MakeKey (std::pair< int, int > grid_ids)
Key generator for a given grid.
Private Attributes
std::unordered_map< ActorId, std::string > actor_to_grid_id
Map connecting actor id to grid key.
std::unordered_map< std::string, std::unordered_set< ActorId > > grid_to_actor_id
Map connecting grid id to set of actor ids.
std::shared_timed_mutex modification_mutex
Mutex to manage contention between modifiers and readers.
Detailed Description
This class maintains vehicle positions in grid segments.
This is used in the collision stage to filter vehicles.
Definition at line 36 of file VicinityGrid.h.
Constructor & Destructor Documentation
carla::traffic_manager::VicinityGrid::VicinityGrid ()
Definition at line 14 of file VicinityGrid.cpp.
carla::traffic_manager::VicinityGrid::~VicinityGrid ()
Definition at line 16 of file VicinityGrid.cpp.
Member Function Documentation
void carla::traffic_manager::VicinityGrid::EraseActor (ActorId actor_id)
Removes actor.
Definition at line 90 of file VicinityGrid.cpp.
References actor_to_grid_id, and grid_to_actor_id.
Referenced by carla::traffic_manager::CollisionStage::Action().
std::unordered_set< carla::ActorId > carla::traffic_manager::VicinityGrid::GetActors (Actor actor)
Returns a set of actors in the vicinity of a given actor.
Definition at line 68 of file VicinityGrid.cpp.
References grid_to_actor_id, MakeKey(), modification_mutex, and UpdateGrid().
Referenced by carla::traffic_manager::CollisionStage::GetPotentialVehicleObstacles().
std::string carla::traffic_manager::VicinityGrid::MakeKey (std::pair< int, int > grid_ids) private
Key generator for a given grid.
Definition at line 18 of file VicinityGrid.cpp.
Referenced by GetActors(), and UpdateGrid().
std::pair< int, int > carla::traffic_manager::VicinityGrid::UpdateGrid (Actor actor)
Updates the grid position of the given actor and returns new grid id.
Definition at line 22 of file VicinityGrid.cpp.
References actor_to_grid_id, grid_to_actor_id, MakeKey(), modification_mutex, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by carla::traffic_manager::CollisionStage::Action(), GetActors(), and carla::traffic_manager::CollisionStage::GetPotentialVehicleObstacles().
Member Data Documentation
std::unordered_map<ActorId, std::string> carla::traffic_manager::VicinityGrid::actor_to_grid_id private
Map connecting actor id to grid key.
Definition at line 45 of file VicinityGrid.h.
Referenced by EraseActor(), and UpdateGrid().
std::unordered_map<std::string, std::unordered_set<ActorId> > carla::traffic_manager::VicinityGrid::grid_to_actor_id private
Map connecting grid id to set of actor ids.
Definition at line 43 of file VicinityGrid.h.
Referenced by EraseActor(), GetActors(), and UpdateGrid().
std::shared_timed_mutex carla::traffic_manager::VicinityGrid::modification_mutex private
Mutex to manage contention between modifiers and readers.
Definition at line 41 of file VicinityGrid.h.
Referenced by GetActors(), and UpdateGrid().
The documentation for this class was generated from the following files:
VicinityGrid.h
VicinityGrid.cpp