CARLA: Simplify.h File Reference
Simplify.h File Reference
#include <iostream>
#include <fstream>
#include <algorithm>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>
#include <float.h>
Classes
struct Simplify::Ref
class SymetricMatrix
struct Simplify::Triangle
struct vec3f
struct vector3
struct Simplify::Vertex
Namespaces
Simplify
Macros
#define loopi(start_l, end_l) for (int i = start_l; i < end_l; ++i)
#define loopi(start_l, end_l) for (int i = start_l; i < end_l; ++i)
#define loopj(start_l, end_l) for (int j = start_l; j < end_l; ++j)
#define loopk(start_l, end_l) for (int k = start_l; k < end_l; ++k)
Enumerations
enum Simplify::Attributes { Simplify::NONE, Simplify::NORMAL = 2, Simplify::TEXCOORD = 4, Simplify::COLOR = 8 }
Functions
vec3f barycentric (const vec3f &p, const vec3f &a, const vec3f &b, const vec3f &c)
double Simplify::calculate_error (int id_v1, int id_v2, vec3f &p_result)
void Simplify::compact_mesh ()
bool Simplify::flipped (vec3f p, int i0, int i1, Vertex &v0, Vertex &v1, std::vector< int > &deleted)
vec3f interpolate (const vec3f &p, const vec3f &a, const vec3f &b, const vec3f &c, const vec3f attrs[3])
void Simplify::load_obj (const char *filename, bool process_uv=false)
double min (double v1, double v2)
void Simplify::simplify_mesh (int target_count, double agressiveness=7, bool verbose=false)
void Simplify::simplify_mesh_lossless (bool verbose=false)
char * Simplify::trimwhitespace (char *str)
void Simplify::update_mesh (int iteration)
void Simplify::update_triangles (int i0, Vertex &v, std::vector< int > &deleted, int &deleted_triangles)
void Simplify::update_uvs (int i0, const Vertex &v, const vec3f &p, std::vector< int > &deleted)
double Simplify::vertex_error (SymetricMatrix q, double x, double y, double z)
void Simplify::write_obj (const char *filename)
Variables
std::vector< std::string > Simplify::materials
std::string Simplify::mtllib
std::vector< Ref > Simplify::refs
std::vector< Triangle > Simplify::triangles
std::vector< Vertex > Simplify::vertices
Macro Definition Documentation
loopi [1/2]
#define loopi (start_l, end_l) for (int i = start_l; i < end_l; ++i)
Definition at line 29 of file Simplify.h.
Referenced by Simplify::compact_mesh(), Simplify::load_obj(), Simplify::simplify_mesh(), Simplify::simplify_mesh_lossless(), SymetricMatrix::SymetricMatrix(), Simplify::update_mesh(), and Simplify::write_obj().
loopi [2/2]
#define loopi (start_l, end_l) for (int i = start_l; i < end_l; ++i)
Definition at line 29 of file Simplify.h.
loopj
#define loopj (start_l, end_l) for (int j = start_l; j < end_l; ++j)
Definition at line 30 of file Simplify.h.
Referenced by Simplify::compact_mesh(), Simplify::load_obj(), Simplify::simplify_mesh(), Simplify::simplify_mesh_lossless(), and Simplify::update_mesh().
loopk
#define loopk (start_l, end_l) for (int k = start_l; k < end_l; ++k)
Definition at line 31 of file Simplify.h.
Referenced by Simplify::flipped(), Simplify::update_mesh(), Simplify::update_triangles(), and Simplify::update_uvs().
Function Documentation
barycentric()
vec3f barycentric (const vec3f & p, const vec3f & a, const vec3f & b, const vec3f & c)
Definition at line 263 of file Simplify.h.
References vec3f::dot().
Referenced by interpolate().
interpolate()
vec3f interpolate (const vec3f & p, const vec3f & a, const vec3f & b, const vec3f & c, const vec3f attrs[3])
Definition at line 280 of file Simplify.h.
References barycentric(), vec3f::x, vec3f::y, and vec3f::z.
Referenced by Simplify::update_uvs().
min()
double min (double v1, double v2)
Definition at line 290 of file Simplify.h.
Referenced by Simplify::calculate_error(), carla::geom::Math::Clamp(), vec3f::clamp(), carla::traffic_manager::MotionPlanStage::CollisionHandling(), carla::road::Map::CreateRtree(), carla::traffic_manager::DeviationDotProduct(), carla::road::Map::GenerateChunkedMesh(), ACityMapGenerator::GenerateRoads(), FHeightMapData::GetHeight(), carla::traffic_manager::MotionPlanStage::GetLandmarkTargetVelocity(), MapGen::getRotation(), carla::nav::Navigation::GetWalkerTransform(), carla::image::ColorConverter::LogarithmicLinear::operator()(), carla::rss::RssRestrictor::RestrictVehicleControl(), carla::rss::RssCheck::RssCheck(), carla::traffic_manager::PID::RunStep(), FSparseHighDetailMap::SaveMap(), carla::traffic_manager::Parameters::SetGlobalPercentageSpeedDifference(), carla::traffic_manager::Parameters::SetPercentageSpeedDifference(), util::buffer::to_hex_string(), carla::traffic_manager::MotionPlanStage::Update(), FSparseHighDetailMap::Update(), Simplify::update_mesh(), and Simplify::update_triangles().