CARLA: carla::road::element::LaneCrossingCalculator Class Reference
carla::road::element::LaneCrossingCalculator Class Reference
#include <LaneCrossingCalculator.h>
Static Public Member Functions
static std::vector< LaneMarking > Calculate (const Map &map, const geom::Location &origin, const geom::Location &destination)
Detailed Description
Definition at line 21 of file LaneCrossingCalculator.h.
Member Function Documentation
std::vector< LaneMarking > carla::road::element::LaneCrossingCalculator::Calculate (const Map & map, const geom::Location & origin, const geom::Location & destination) static
Todo:
This case should also be handled.
Definition at line 60 of file LaneCrossingCalculator.cpp.
References carla::road::Map::ComputeTransform(), carla::road::element::CrossingAtSameSection(), carla::road::Map::GetClosestWaypointOnRoad(), carla::road::Map::IsJunction(), carla::road::element::IsOffRoad(), carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by carla::road::Map::CalculateCrossedLanes().
The documentation for this class was generated from the following files:
LaneCrossingCalculator.h
LaneCrossingCalculator.cpp