CARLA: std_msgs::msg::HeaderPubSubType Class Reference
std_msgs::msg::HeaderPubSubType Class Reference
This class represents the TopicDataType of the type Header defined by the user in the IDL file.
#include <HeaderPubSubTypes.h>
Public Types
typedef Header type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport HeaderPubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~HeaderPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type Header defined by the user in the IDL file.
Definition at line 43 of file HeaderPubSubTypes.h.
Member Typedef Documentation
type
typedef Header std_msgs::msg::HeaderPubSubType::type
Definition at line 47 of file HeaderPubSubTypes.h.
Constructor & Destructor Documentation
HeaderPubSubType()
std_msgs::msg::HeaderPubSubType::HeaderPubSubType ()
Definition at line 32 of file HeaderPubSubTypes.cpp.
References std_msgs::msg::Header::getKeyMaxCdrSerializedSize(), std_msgs::msg::Header::getMaxCdrSerializedSize(), std_msgs::msg::Header::isKeyDefined(), and m_keyBuffer.
~HeaderPubSubType()
std_msgs::msg::HeaderPubSubType::~HeaderPubSubType () override virtual
Definition at line 45 of file HeaderPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * std_msgs::msg::HeaderPubSubType::createData () override virtual
Definition at line 104 of file HeaderPubSubTypes.cpp.
deleteData()
void std_msgs::msg::HeaderPubSubType::deleteData (void * data) override virtual
Definition at line 109 of file HeaderPubSubTypes.cpp.
deserialize()
bool std_msgs::msg::HeaderPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 72 of file HeaderPubSubTypes.cpp.
References std_msgs::msg::Header::deserialize().
getKey()
bool std_msgs::msg::HeaderPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 115 of file HeaderPubSubTypes.cpp.
References std_msgs::msg::Header::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and std_msgs::msg::Header::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> std_msgs::msg::HeaderPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 94 of file HeaderPubSubTypes.cpp.
References std_msgs::msg::Header::getCdrSerializedSize().
serialize()
bool std_msgs::msg::HeaderPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file HeaderPubSubTypes.cpp.
References std_msgs::msg::Header::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* std_msgs::msg::HeaderPubSubType::m_keyBuffer
Definition at line 101 of file HeaderPubSubTypes.h.
Referenced by getKey(), HeaderPubSubType(), and ~HeaderPubSubType().
m_md5
MD5 std_msgs::msg::HeaderPubSubType::m_md5
Definition at line 100 of file HeaderPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
HeaderPubSubTypes.h
HeaderPubSubTypes.cpp