CARLA: geometry_msgs::msg::Point32PubSubType Class Reference
geometry_msgs::msg::Point32PubSubType Class Reference
This class represents the TopicDataType of the type Point32 defined by the user in the IDL file.
#include <Point32PubSubTypes.h>
Public Types
typedef Point32 type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport Point32PubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~Point32PubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type Point32 defined by the user in the IDL file.
Definition at line 72 of file Point32PubSubTypes.h.
Member Typedef Documentation
type
typedef Point32 geometry_msgs::msg::Point32PubSubType::type
Definition at line 76 of file Point32PubSubTypes.h.
Constructor & Destructor Documentation
Point32PubSubType()
geometry_msgs::msg::Point32PubSubType::Point32PubSubType ()
Definition at line 32 of file Point32PubSubTypes.cpp.
References geometry_msgs::msg::Point32::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::Point32::getMaxCdrSerializedSize(), geometry_msgs::msg::Point32::isKeyDefined(), and m_keyBuffer.
~Point32PubSubType()
geometry_msgs::msg::Point32PubSubType::~Point32PubSubType () override virtual
Definition at line 45 of file Point32PubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::Point32PubSubType::createData () override virtual
Definition at line 122 of file Point32PubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::Point32PubSubType::deleteData (void * data) override virtual
Definition at line 127 of file Point32PubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::Point32PubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file Point32PubSubTypes.cpp.
References geometry_msgs::msg::Point32::deserialize().
getKey()
bool geometry_msgs::msg::Point32PubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file Point32PubSubTypes.cpp.
References geometry_msgs::msg::Point32::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::Point32::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::Point32PubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file Point32PubSubTypes.cpp.
References geometry_msgs::msg::Point32::getCdrSerializedSize().
is_plain_impl()
static constexpr bool geometry_msgs::msg::Point32PubSubType::is_plain_impl () inline static private
Definition at line 131 of file Point32PubSubTypes.h.
serialize()
bool geometry_msgs::msg::Point32PubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file Point32PubSubTypes.cpp.
References geometry_msgs::msg::Point32::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::Point32PubSubType::m_keyBuffer
Definition at line 129 of file Point32PubSubTypes.h.
Referenced by getKey(), Point32PubSubType(), and ~Point32PubSubType().
m_md5
MD5 geometry_msgs::msg::Point32PubSubType::m_md5
Definition at line 128 of file Point32PubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
Point32PubSubTypes.h
Point32PubSubTypes.cpp