CARLA: AWalkerController Class Reference
AWalkerController Class Reference
#include <WalkerController.h>
Classes
class ControlTickVisitor
Public Member Functions
void ApplyWalkerControl (const FWalkerControl &InControl)
void ApplyWalkerControl (const FWalkerBoneControl &InBoneControl)
AWalkerController (const FObjectInitializer &ObjectInitializer)
const FWalkerBoneControl GetBoneWalkerControl () const
float GetMaximumWalkSpeed () const
Maximum walk speed allowed in centimetres per second.
const FWalkerControl GetWalkerControl () const
void OnPossess (APawn *InPawn) override
void SetManualBones (const bool bIsEnabled)
void Tick (float DeltaSeconds) override
Private Attributes
bool bManualBones
boost::variant< FWalkerControl, FWalkerBoneControl > Control
Detailed Description
Definition at line 22 of file WalkerController.h.
Constructor & Destructor Documentation
AWalkerController()
AWalkerController::AWalkerController (const FObjectInitializer & ObjectInitializer)
Definition at line 18 of file WalkerController.cpp.
Member Function Documentation
ApplyWalkerControl() [1/2]
void AWalkerController::ApplyWalkerControl (const FWalkerControl & InControl)
Definition at line 61 of file WalkerController.cpp.
References bManualBones, Control, and SetManualBones().
ApplyWalkerControl() [2/2]
void AWalkerController::ApplyWalkerControl (const FWalkerBoneControl & InBoneControl)
Definition at line 70 of file WalkerController.cpp.
References bManualBones, Control, and SetManualBones().
GetBoneWalkerControl()
const FWalkerBoneControl AWalkerController::GetBoneWalkerControl () const inline
Definition at line 71 of file WalkerController.h.
GetMaximumWalkSpeed()
float AWalkerController::GetMaximumWalkSpeed () const inline
Maximum walk speed allowed in centimetres per second.
Definition at line 54 of file WalkerController.h.
Referenced by OnPossess().
GetWalkerControl()
const FWalkerControl AWalkerController::GetWalkerControl () const inline
Definition at line 65 of file WalkerController.h.
OnPossess()
void AWalkerController::OnPossess (APawn * InPawn) override
Definition at line 24 of file WalkerController.cpp.
References Character, and GetMaximumWalkSpeed().
SetManualBones()
void AWalkerController::SetManualBones (const bool bIsEnabled)
Definition at line 79 of file WalkerController.cpp.
References AddNewBoneComponent(), bManualBones, and Character.
Referenced by ApplyWalkerControl().
Tick()
void AWalkerController::Tick (float DeltaSeconds) override
Definition at line 145 of file WalkerController.cpp.
References Control.
Member Data Documentation
bManualBones
bool AWalkerController::bManualBones private
Definition at line 83 of file WalkerController.h.
Referenced by ApplyWalkerControl(), and SetManualBones().
Control
boost::variant<FWalkerControl, FWalkerBoneControl> AWalkerController::Control private
Definition at line 81 of file WalkerController.h.
Referenced by ApplyWalkerControl(), and Tick().
The documentation for this class was generated from the following files:
WalkerController.h
WalkerController.cpp