CARLA: ATrafficSignBase Class Reference
ATrafficSignBase Class Reference
#include <TrafficSignBase.h>
Public Member Functions
ATrafficSignBase (const FObjectInitializer &ObjectInitializer)
ETrafficSignState GetTrafficSignState () const
UBoxComponent * GetTriggerVolume () const
TArray< UBoxComponent * > GetTriggerVolumes () const
void SetTrafficSignState (ETrafficSignState State)
Private Attributes
ETrafficSignState TrafficSignState = ETrafficSignState::UNKNOWN
Detailed Description
Definition at line 35 of file TrafficSignBase.h.
Constructor & Destructor Documentation
ATrafficSignBase()
ATrafficSignBase::ATrafficSignBase (const FObjectInitializer & ObjectInitializer)
Definition at line 11 of file TrafficSignBase.cpp.
Member Function Documentation
GetTrafficSignState()
ETrafficSignState ATrafficSignBase::GetTrafficSignState () const inline
Definition at line 44 of file TrafficSignBase.h.
Referenced by UCarlaEpisode::InitializeAtBeginPlay(), and MatchSignalAndActor().
GetTriggerVolume()
UBoxComponent* ATrafficSignBase::GetTriggerVolume () const
Referenced by GetTriggerVolumes().
GetTriggerVolumes()
TArray< UBoxComponent * > ATrafficSignBase::GetTriggerVolumes () const
Definition at line 20 of file TrafficSignBase.cpp.
References GetTriggerVolume().
Referenced by ACarlaRecorder::AddTriggerVolume().
SetTrafficSignState()
void ATrafficSignBase::SetTrafficSignState (ETrafficSignState State) inline
Definition at line 50 of file TrafficSignBase.h.
References State.
Referenced by ATrafficLightBase::ATrafficLightBase().
Member Data Documentation
TrafficSignState
ETrafficSignState ATrafficSignBase::TrafficSignState = ETrafficSignState::UNKNOWN private
Definition at line 63 of file TrafficSignBase.h.
The documentation for this class was generated from the following files:
TrafficSignBase.h
TrafficSignBase.cpp