CARLA: pugi::xml_attribute Class Reference
pugi::xml_attribute Class Reference
#include <pugixml.hpp>
Public Member Functions
bool as_bool (bool def=false) const
double as_double (double def=0) const
float as_float (float def=0) const
int as_int (int def=0) const
const char_t * as_string (const char_t *def=PUGIXML_TEXT("")) const
unsigned int as_uint (unsigned int def=0) const
bool empty () const
size_t hash_value () const
xml_attribute_struct * internal_object () const
const char_t * name () const
xml_attribute next_attribute () const
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const xml_attribute &r) const
bool operator< (const xml_attribute &r) const
bool operator<= (const xml_attribute &r) const
xml_attribute & operator= (const char_t *rhs)
xml_attribute & operator= (int rhs)
xml_attribute & operator= (unsigned int rhs)
xml_attribute & operator= (long rhs)
xml_attribute & operator= (unsigned long rhs)
xml_attribute & operator= (double rhs)
xml_attribute & operator= (float rhs)
xml_attribute & operator= (bool rhs)
bool operator== (const xml_attribute &r) const
bool operator> (const xml_attribute &r) const
bool operator>= (const xml_attribute &r) const
xml_attribute previous_attribute () const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
bool set_value (int rhs)
bool set_value (unsigned int rhs)
bool set_value (long rhs)
bool set_value (unsigned long rhs)
bool set_value (double rhs)
bool set_value (float rhs)
bool set_value (bool rhs)
const char_t * value () const
xml_attribute ()
xml_attribute (xml_attribute_struct *attr)
Private Types
typedef void(* unspecified_bool_type) (xml_attribute ***)
Private Attributes
xml_attribute_struct * _attr
Friends
class xml_attribute_iterator
class xml_node
Detailed Description
Definition at line 344 of file pugixml.hpp.
Member Typedef Documentation
typedef void(* pugi::xml_attribute::unspecified_bool_type) (xml_attribute ***) private
Definition at line 352 of file pugixml.hpp.
Constructor & Destructor Documentation
PUGI__FN pugi::xml_attribute::xml_attribute ()
Definition at line 5101 of file pugixml.cpp.
Referenced by next_attribute(), and previous_attribute().
PUGI__FN pugi::xml_attribute::xml_attribute (xml_attribute_struct * attr) explicit
Definition at line 5105 of file pugixml.cpp.
Member Function Documentation
PUGI__FN bool pugi::xml_attribute::as_bool (bool def = false) const
Definition at line 5188 of file pugixml.cpp.
References _attr, get_value_bool(), PUGI__FN, and pugi::xml_attribute_struct::value.
PUGI__FN double pugi::xml_attribute::as_double (double def = 0) const
Definition at line 5178 of file pugixml.cpp.
References _attr, get_value_double(), and pugi::xml_attribute_struct::value.
Referenced by carla::opendrive::parser::GeometryParser::Parse(), carla::opendrive::parser::SignalParser::Parse(), carla::opendrive::parser::RoadParser::Parse(), and carla::opendrive::parser::ParseLanes().
PUGI__FN float pugi::xml_attribute::as_float (float def = 0) const
Definition at line 5183 of file pugixml.cpp.
References _attr, get_value_float(), and pugi::xml_attribute_struct::value.
PUGI__FN int pugi::xml_attribute::as_int (int def = 0) const
Definition at line 5168 of file pugixml.cpp.
References _attr, get_value_int(), and pugi::xml_attribute_struct::value.
Referenced by carla::opendrive::parser::RoadParser::Parse(), and test_junctions().
PUGI__FN const char_t * pugi::xml_attribute::as_string (const char_t * def = PUGIXML_TEXT("")) const
Definition at line 5163 of file pugixml.cpp.
References _attr, and pugi::xml_attribute_struct::value.
Referenced by carla::opendrive::parser::ObjectParser::Parse().
PUGI__FN unsigned int pugi::xml_attribute::as_uint (unsigned int def = 0) const
Definition at line 5173 of file pugixml.cpp.
References _attr, get_value_uint(), and pugi::xml_attribute_struct::value.
Referenced by carla::opendrive::parser::LaneParser::Parse(), carla::opendrive::parser::ObjectParser::Parse(), carla::opendrive::parser::SignalParser::Parse(), carla::opendrive::parser::RoadParser::Parse(), test_geometry(), and test_road_elevation().
PUGI__FN bool pugi::xml_attribute::empty () const
Definition at line 5205 of file pugixml.cpp.
References _attr.
PUGI__FN size_t pugi::xml_attribute::hash_value () const
Definition at line 5220 of file pugixml.cpp.
References _attr.
PUGI__FN xml_attribute_struct * pugi::xml_attribute::internal_object () const
Definition at line 5225 of file pugixml.cpp.
References _attr.
PUGI__FN const char_t * pugi::xml_attribute::name () const
Definition at line 5210 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::name, and PUGIXML_TEXT.
PUGI__FN xml_attribute pugi::xml_attribute::next_attribute () const
Definition at line 5153 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::next_attribute, and xml_attribute().
Referenced by pugi::xml_node::find_attribute().
PUGI__FN pugi::xml_attribute::operator xml_attribute::unspecified_bool_type () const
Definition at line 5113 of file pugixml.cpp.
References _attr, and pugi::unspecified_bool_xml_attribute().
PUGI__FN bool pugi::xml_attribute::operator! () const
Definition at line 5118 of file pugixml.cpp.
References _attr.
PUGI__FN bool pugi::xml_attribute::operator!= (const xml_attribute & r) const
Definition at line 5128 of file pugixml.cpp.
References _attr.
PUGI__FN bool pugi::xml_attribute::operator< (const xml_attribute & r) const
Definition at line 5133 of file pugixml.cpp.
References _attr.
PUGI__FN bool pugi::xml_attribute::operator<= (const xml_attribute & r) const
Definition at line 5143 of file pugixml.cpp.
References _attr.
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (const char_t * rhs)
Definition at line 5230 of file pugixml.cpp.
References set_value().
Referenced by operator=().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (int rhs)
Definition at line 5236 of file pugixml.cpp.
References set_value().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (unsigned int rhs)
Definition at line 5242 of file pugixml.cpp.
References set_value().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (long rhs)
Definition at line 5248 of file pugixml.cpp.
References set_value().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (unsigned long rhs)
Definition at line 5254 of file pugixml.cpp.
References set_value().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (double rhs)
Definition at line 5260 of file pugixml.cpp.
References set_value().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (float rhs)
Definition at line 5266 of file pugixml.cpp.
References set_value().
PUGI__FN xml_attribute & pugi::xml_attribute::operator= (bool rhs)
Definition at line 5272 of file pugixml.cpp.
References operator=(), PUGI__FN, and set_value().
PUGI__FN bool pugi::xml_attribute::operator== (const xml_attribute & r) const
Definition at line 5123 of file pugixml.cpp.
References _attr.
PUGI__FN bool pugi::xml_attribute::operator> (const xml_attribute & r) const
Definition at line 5138 of file pugixml.cpp.
References _attr.
PUGI__FN bool pugi::xml_attribute::operator>= (const xml_attribute & r) const
Definition at line 5148 of file pugixml.cpp.
References _attr.
PUGI__FN xml_attribute pugi::xml_attribute::previous_attribute () const
Definition at line 5158 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::next_attribute, pugi::xml_attribute_struct::prev_attribute_c, and xml_attribute().
Referenced by pugi::xml_attribute_iterator::operator--().
PUGI__FN bool pugi::xml_attribute::set_name (const char_t * rhs)
Definition at line 5292 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, pugi::xml_attribute_struct::name, strcpy_insitu(), strlength(), and xml_memory_page_name_allocated_mask.
Referenced by pugi::xml_node::append_attribute(), pugi::xml_node::insert_attribute_after(), pugi::xml_node::insert_attribute_before(), and pugi::xml_node::prepend_attribute().
PUGI__FN bool pugi::xml_attribute::set_value (const char_t * rhs)
Definition at line 5299 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, strcpy_insitu(), strlength(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
Referenced by operator=(), and set_value().
PUGI__FN bool pugi::xml_attribute::set_value (int rhs)
Definition at line 5306 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN bool pugi::xml_attribute::set_value (unsigned int rhs)
Definition at line 5313 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN bool pugi::xml_attribute::set_value (long rhs)
Definition at line 5320 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN bool pugi::xml_attribute::set_value (unsigned long rhs)
Definition at line 5327 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN bool pugi::xml_attribute::set_value (double rhs)
Definition at line 5334 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, set_value_convert(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN bool pugi::xml_attribute::set_value (float rhs)
Definition at line 5341 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, set_value_convert(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN bool pugi::xml_attribute::set_value (bool rhs)
Definition at line 5348 of file pugixml.cpp.
References _attr, pugi::xml_attribute_struct::header, PUGI__FN, set_value(), set_value_bool(), pugi::xml_attribute_struct::value, and xml_memory_page_value_allocated_mask.
PUGI__FN const char_t * pugi::xml_attribute::value () const
Definition at line 5215 of file pugixml.cpp.
References _attr, PUGIXML_TEXT, and pugi::xml_attribute_struct::value.
Referenced by namespace_uri(), carla::opendrive::parser::GeometryParser::Parse(), carla::opendrive::parser::RoadParser::Parse(), and carla::opendrive::parser::ParseLanes().
Friends And Related Function Documentation
friend class xml_attribute_iterator friend
Definition at line 346 of file pugixml.hpp.
friend class xml_node friend
Definition at line 347 of file pugixml.hpp.
Member Data Documentation
xml_attribute_struct* pugi::xml_attribute::_attr private
Definition at line 350 of file pugixml.hpp.
Referenced by pugi::xml_node::append_attribute(), pugi::xml_node::append_copy(), as_bool(), as_double(), as_float(), as_int(), as_string(), as_uint(), pugi::xml_node::attribute(), empty(), hash_value(), pugi::xml_node::insert_attribute_after(), pugi::xml_node::insert_attribute_before(), pugi::xml_node::insert_copy_after(), pugi::xml_node::insert_copy_before(), internal_object(), name(), next_attribute(), operator unspecified_bool_type(), operator!(), operator!=(), pugi::xml_attribute_iterator::operator!=(), pugi::xml_attribute_iterator::operator*(), pugi::xml_attribute_iterator::operator++(), pugi::xml_attribute_iterator::operator--(), pugi::xml_attribute_iterator::operator->(), operator<(), operator<=(), operator==(), pugi::xml_attribute_iterator::operator==(), operator>(), operator>=(), pugi::xml_node::prepend_attribute(), pugi::xml_node::prepend_copy(), previous_attribute(), pugi::xml_node::remove_attribute(), set_name(), set_value(), and value().
The documentation for this class was generated from the following files:
pugixml.hpp
pugixml.cpp