CARLA: sensor_msgs::msg::PointField Class Reference
sensor_msgs::msg::PointField Class Reference
This class represents the structure PointField defined by the user in the IDL file.
#include <PointField.h>
Public Member Functions
eProsima_user_DllExport uint32_t & count ()
This function returns a reference to member count.
eProsima_user_DllExport uint32_t count () const
This function returns the value of member count.
eProsima_user_DllExport void count (uint32_t _count)
This function sets a value in member count.
eProsima_user_DllExport uint8_t & datatype ()
This function returns a reference to member datatype.
eProsima_user_DllExport uint8_t datatype () const
This function returns the value of member datatype.
eProsima_user_DllExport void datatype (uint8_t _datatype)
This function sets a value in member datatype.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport std::string & name ()
This function returns a reference to member name.
const eProsima_user_DllExport std::string & name () const
This function returns a constant reference to member name.
eProsima_user_DllExport void name (const std::string &_name)
This function copies the value in member name.
eProsima_user_DllExport void name (std::string &&_name)
This function moves the value in member name.
eProsima_user_DllExport uint32_t & offset ()
This function returns a reference to member offset.
eProsima_user_DllExport uint32_t offset () const
This function returns the value of member offset.
eProsima_user_DllExport void offset (uint32_t _offset)
This function sets a value in member offset.
eProsima_user_DllExport bool operator!= (const PointField &x) const
Comparison operator.
eProsima_user_DllExport PointField & operator= (const PointField &x)
Copy assignment.
eProsima_user_DllExport PointField & operator= (PointField &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const PointField &x) const
Comparison operator.
eProsima_user_DllExport PointField ()
Default constructor.
eProsima_user_DllExport PointField (const PointField &x)
Copy constructor.
eProsima_user_DllExport PointField (PointField &&x) noexcept
Move constructor.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport ~PointField ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const sensor_msgs::msg::PointField &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
uint32_t m_count
uint8_t m_datatype
std::string m_name
uint32_t m_offset
Detailed Description
This class represents the structure PointField defined by the user in the IDL file.
Definition at line 79 of file PointField.h.
Constructor & Destructor Documentation
PointField() [1/3]
sensor_msgs::msg::PointField::PointField ()
Default constructor.
Definition at line 40 of file PointField.cpp.
~PointField()
sensor_msgs::msg::PointField::~PointField ()
Default destructor.
Definition at line 52 of file PointField.cpp.
PointField() [2/3]
sensor_msgs::msg::PointField::PointField (const PointField & x)
Copy constructor.
Parameters
x Reference to the object sensor_msgs::msg::PointField that will be copied.
Definition at line 56 of file PointField.cpp.
References m_count, m_datatype, m_name, and m_offset.
PointField() [3/3]
sensor_msgs::msg::PointField::PointField (PointField && x) noexcept
Move constructor.
Parameters
x Reference to the object sensor_msgs::msg::PointField that will be copied.
Definition at line 65 of file PointField.cpp.
Member Function Documentation
count() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::PointField::count ()
This function returns a reference to member count.
Returns
Reference to member count
count() [2/3]
uint32_t & sensor_msgs::msg::PointField::count () const
This function returns the value of member count.
This function returns a reference to member count.
Returns
Value of member count
Reference to member count
Definition at line 254 of file PointField.cpp.
count() [3/3]
void sensor_msgs::msg::PointField::count (uint32_t _count)
This function sets a value in member count.
Parameters
_count New value for member count
Definition at line 244 of file PointField.cpp.
Referenced by carla::ros2::CarlaLidarPublisher::SetData(), carla::ros2::CarlaSemanticLidarPublisher::SetData(), carla::ros2::CarlaRadarPublisher::SetData(), and carla::ros2::CarlaDVSCameraPublisher::SetPointCloudData().
datatype() [1/3]
eProsima_user_DllExport uint8_t& sensor_msgs::msg::PointField::datatype ()
This function returns a reference to member datatype.
Returns
Reference to member datatype
datatype() [2/3]
uint8_t & sensor_msgs::msg::PointField::datatype () const
This function returns the value of member datatype.
This function returns a reference to member datatype.
Returns
Value of member datatype
Reference to member datatype
Definition at line 226 of file PointField.cpp.
datatype() [3/3]
void sensor_msgs::msg::PointField::datatype (uint8_t _datatype)
This function sets a value in member datatype.
Parameters
_datatype New value for member datatype
Definition at line 216 of file PointField.cpp.
Referenced by carla::ros2::CarlaLidarPublisher::SetData(), carla::ros2::CarlaSemanticLidarPublisher::SetData(), carla::ros2::CarlaRadarPublisher::SetData(), and carla::ros2::CarlaDVSCameraPublisher::SetPointCloudData().
deserialize()
void sensor_msgs::msg::PointField::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 137 of file PointField.cpp.
Referenced by sensor_msgs::msg::PointFieldPubSubType::deserialize().
getCdrSerializedSize()
size_t sensor_msgs::msg::PointField::getCdrSerializedSize (const sensor_msgs::msg::PointField & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 115 of file PointField.cpp.
References name().
Referenced by sensor_msgs::msg::PointCloud2::getCdrSerializedSize(), and sensor_msgs::msg::PointFieldPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t sensor_msgs::msg::PointField::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 268 of file PointField.cpp.
References sensor_msgs_msg_PointField_max_key_cdr_typesize.
Referenced by sensor_msgs::msg::PointFieldPubSubType::getKey(), and sensor_msgs::msg::PointFieldPubSubType::PointFieldPubSubType().
getMaxCdrSerializedSize()
size_t sensor_msgs::msg::PointField::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 108 of file PointField.cpp.
References sensor_msgs_msg_PointField_max_cdr_typesize.
Referenced by sensor_msgs::msg::PointFieldPubSubType::PointFieldPubSubType().
isKeyDefined()
bool sensor_msgs::msg::PointField::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 275 of file PointField.cpp.
Referenced by sensor_msgs::msg::PointFieldPubSubType::PointFieldPubSubType().
name() [1/4]
eProsima_user_DllExport std::string& sensor_msgs::msg::PointField::name ()
This function returns a reference to member name.
Returns
Reference to member name
name() [2/4]
std::string & sensor_msgs::msg::PointField::name () const
This function returns a constant reference to member name.
This function returns a reference to member name.
Returns
Constant reference to member name
Reference to member name
Definition at line 170 of file PointField.cpp.
name() [3/4]
void sensor_msgs::msg::PointField::name (const std::string & _name)
This function copies the value in member name.
Parameters
_name New value to be copied in member name
Definition at line 150 of file PointField.cpp.
Referenced by getCdrSerializedSize(), carla::ros2::CarlaSemanticLidarPublisher::SetData(), carla::ros2::CarlaLidarPublisher::SetData(), carla::ros2::CarlaRadarPublisher::SetData(), and carla::ros2::CarlaDVSCameraPublisher::SetPointCloudData().
name() [4/4]
void sensor_msgs::msg::PointField::name (std::string && _name)
This function moves the value in member name.
Parameters
_name New value to be moved in member name
Definition at line 160 of file PointField.cpp.
offset() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::PointField::offset ()
This function returns a reference to member offset.
Returns
Reference to member offset
offset() [2/3]
uint32_t & sensor_msgs::msg::PointField::offset () const
This function returns the value of member offset.
This function returns a reference to member offset.
Returns
Value of member offset
Reference to member offset
Definition at line 198 of file PointField.cpp.
offset() [3/3]
void sensor_msgs::msg::PointField::offset (uint32_t _offset)
This function sets a value in member offset.
Parameters
_offset New value for member offset
Definition at line 188 of file PointField.cpp.
Referenced by carla::ros2::CarlaLidarPublisher::SetData(), carla::ros2::CarlaSemanticLidarPublisher::SetData(), carla::ros2::CarlaRadarPublisher::SetData(), and carla::ros2::CarlaDVSCameraPublisher::SetPointCloudData().
operator!=()
bool sensor_msgs::msg::PointField::operator!= (const PointField & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::PointField object to compare.
Definition at line 102 of file PointField.cpp.
operator=() [1/2]
sensor_msgs::msg::PointField & sensor_msgs::msg::PointField::operator= (const PointField & x)
Copy assignment.
Parameters
x Reference to the object sensor_msgs::msg::PointField that will be copied.
Definition at line 74 of file PointField.cpp.
References m_count, m_datatype, m_name, and m_offset.
operator=() [2/2]
sensor_msgs::msg::PointField & sensor_msgs::msg::PointField::operator= (PointField && x) noexcept
Move assignment.
Parameters
x Reference to the object sensor_msgs::msg::PointField that will be copied.
Definition at line 85 of file PointField.cpp.
operator==()
bool sensor_msgs::msg::PointField::operator== (const PointField & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::PointField object to compare.
Definition at line 96 of file PointField.cpp.
References m_count, m_datatype, m_name, and m_offset.
serialize()
void sensor_msgs::msg::PointField::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 128 of file PointField.cpp.
Referenced by sensor_msgs::msg::PointFieldPubSubType::serialize().
serializeKey()
void sensor_msgs::msg::PointField::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 280 of file PointField.cpp.
Referenced by sensor_msgs::msg::PointFieldPubSubType::getKey().
Member Data Documentation
m_count
uint32_t sensor_msgs::msg::PointField::m_count private
Definition at line 275 of file PointField.h.
Referenced by operator=(), operator==(), and PointField().
m_datatype
uint8_t sensor_msgs::msg::PointField::m_datatype private
Definition at line 274 of file PointField.h.
Referenced by operator=(), operator==(), and PointField().
m_name
std::string sensor_msgs::msg::PointField::m_name private
Definition at line 272 of file PointField.h.
Referenced by operator=(), operator==(), and PointField().
m_offset
uint32_t sensor_msgs::msg::PointField::m_offset private
Definition at line 273 of file PointField.h.
Referenced by operator=(), operator==(), and PointField().
The documentation for this class was generated from the following files:
PointField.h
PointField.cpp