CARLA: MapGen::DoublyConnectedEdgeList::Node Struct Reference
MapGen::DoublyConnectedEdgeList::Node Struct Reference
#include <DoublyConnectedEdgeList.h>
Public Member Functions
const DoublyConnectedEdgeList::Position & GetPosition () const
Node (const Position &Pos)
Node & operator= (const Node &)=delete
Public Attributes
friend DoublyConnectedEdgeList
Private Attributes
HalfEdge * LeavingHalfEdge = nullptr
DoublyConnectedEdgeList::Position Position
Detailed Description
Definition at line 34 of file DoublyConnectedEdgeList.h.
Constructor & Destructor Documentation
MapGen::DoublyConnectedEdgeList::Node::Node (const Position & Pos) inline
Definition at line 38 of file DoublyConnectedEdgeList.h.
Member Function Documentation
const DoublyConnectedEdgeList::Position& MapGen::DoublyConnectedEdgeList::Node::GetPosition () const inline
Definition at line 42 of file DoublyConnectedEdgeList.h.
Referenced by MapGen::DoublyConnectedEdgeList::GetAngle(), MapGen::getSourcePosition(), and MapGen::getTargetPosition().
Node& MapGen::DoublyConnectedEdgeList::Node::operator= (const Node &) delete
Member Data Documentation
friend MapGen::DoublyConnectedEdgeList::Node::DoublyConnectedEdgeList
Definition at line 36 of file DoublyConnectedEdgeList.h.
HalfEdge* MapGen::DoublyConnectedEdgeList::Node::LeavingHalfEdge = nullptr private
Definition at line 49 of file DoublyConnectedEdgeList.h.
Referenced by MapGen::DoublyConnectedEdgeList::GetLeavingHalfEdge().
DoublyConnectedEdgeList::Position MapGen::DoublyConnectedEdgeList::Node::Position private
Definition at line 48 of file DoublyConnectedEdgeList.h.
The documentation for this struct was generated from the following file:
DoublyConnectedEdgeList.h