CARLA: carla::client::TrafficLight Class Reference
carla::client::TrafficLight Class Reference
#include <TrafficLight.h>
Public Member Functions
void Freeze (bool freeze)
std::vector< SharedPtr< Waypoint > > GetAffectedLaneWaypoints () const
float GetElapsedTime () const
float GetGreenTime () const
std::vector< SharedPtr< TrafficLight > > GetGroupTrafficLights ()
Return all traffic lights in the group this one belongs to.
std::vector< geom::BoundingBox > GetLightBoxes () const
road::SignId GetOpenDRIVEID () const
uint32_t GetPoleIndex ()
Returns the index of the pole in the traffic light group.
float GetRedTime () const
rpc::TrafficLightState GetState () const
Return the current state of the traffic light.
std::vector< SharedPtr< Waypoint > > GetStopWaypoints () const
float GetYellowTime () const
bool IsFrozen () const
void ResetGroup ()
void SetGreenTime (float green_time)
void SetRedTime (float red_time)
void SetState (rpc::TrafficLightState state)
void SetYellowTime (float yellow_time)
TrafficLight (ActorInitializer init)
Public Member Functions inherited from carla::client::TrafficSign
carla::road::SignId GetSignId () const
const geom::BoundingBox & GetTriggerVolume () const
TrafficSign (ActorInitializer init)
Public Member Functions inherited from carla::client::Actor
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddForce (const geom::Vector3D &force)
Add force to the actor at its center of mass.
void AddForce (const geom::Vector3D &force, const geom::Vector3D &location)
Add force to the actor at certain location.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor at its center of mass.
void AddImpulse (const geom::Vector3D &impulse, const geom::Vector3D &location)
Add impulse to the actor at certain location.
void AddTorque (const geom::Vector3D &vector)
Add a torque to the actor.
virtual bool Destroy ()
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
void DisableConstantVelocity ()
Disable the constant velocity mode.
void EnableConstantVelocity (const geom::Vector3D &vector)
Enable a constant velocity mode.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
rpc::ActorState GetActorState () const
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
geom::Location GetLocation () const
Return the current location of the actor.
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsActive () const
bool IsAlive () const
bool IsDormant () const
const auto & Serialize () const
void SetEnableGravity (bool enabled=true)
Enable or disable gravity on this actor.
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTargetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor before applying physics.
void SetTargetVelocity (const geom::Vector3D &vector)
Set the actor velocity before applying physics.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Additional Inherited Members
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Detailed Description
Definition at line 18 of file TrafficLight.h.
Constructor & Destructor Documentation
TrafficLight()
carla::client::TrafficLight::TrafficLight (ActorInitializer init) inline explicit
Definition at line 22 of file TrafficLight.h.
References Freeze(), GetAffectedLaneWaypoints(), GetElapsedTime(), GetGreenTime(), GetGroupTrafficLights(), GetLightBoxes(), GetOpenDRIVEID(), GetPoleIndex(), GetRedTime(), GetState(), GetStopWaypoints(), GetYellowTime(), IsFrozen(), ResetGroup(), SetGreenTime(), SetRedTime(), SetState(), and SetYellowTime().
Member Function Documentation
Freeze()
void carla::client::TrafficLight::Freeze (bool freeze)
Definition at line 53 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetAffectedLaneWaypoints()
std::vector< SharedPtr< Waypoint > > carla::client::TrafficLight::GetAffectedLaneWaypoints () const
Definition at line 81 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), GetOpenDRIVEID(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetElapsedTime()
float carla::client::TrafficLight::GetElapsedTime () const
Note
This function does not call the simulator, it returns the data received in the last tick.
Definition at line 49 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetGreenTime()
float carla::client::TrafficLight::GetGreenTime () const
Note
This function does not call the simulator, it returns the data received in the last tick.
Definition at line 29 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetGroupTrafficLights()
std::vector< SharedPtr< TrafficLight > > carla::client::TrafficLight::GetGroupTrafficLights ()
Return all traffic lights in the group this one belongs to.
Note
This function calls the simulator
Definition at line 67 of file TrafficLight.cpp.
References carla::client::World::GetActors(), carla::client::detail::ActorState::GetEpisode(), carla::client::detail::ActorState::GetWorld(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetLightBoxes()
std::vector< geom::BoundingBox > carla::client::TrafficLight::GetLightBoxes () const
Definition at line 107 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetOpenDRIVEID()
road::SignId carla::client::TrafficLight::GetOpenDRIVEID () const
Definition at line 111 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by GetAffectedLaneWaypoints(), and TrafficLight().
GetPoleIndex()
uint32_t carla::client::TrafficLight::GetPoleIndex ()
Returns the index of the pole in the traffic light group.
Definition at line 62 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetRedTime()
float carla::client::TrafficLight::GetRedTime () const
Note
This function does not call the simulator, it returns the data received in the last tick.
Definition at line 45 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetState()
rpc::TrafficLightState carla::client::TrafficLight::GetState () const
Return the current state of the traffic light.
Note
This function does not call the simulator, it returns the data received in the last tick.
Definition at line 21 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
GetStopWaypoints()
std::vector< SharedPtr< Waypoint > > carla::client::TrafficLight::GetStopWaypoints () const
Definition at line 115 of file TrafficLight.cpp.
References carla::geom::BoundingBox::extent, carla::client::detail::ActorState::GetEpisode(), carla::geom::Transform::GetForwardVector(), carla::client::Actor::GetTransform(), carla::client::TrafficSign::GetTriggerVolume(), carla::geom::BoundingBox::location, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::geom::Transform::TransformPoint(), and carla::geom::Vector3D::x.
Referenced by TrafficLight().
GetYellowTime()
float carla::client::TrafficLight::GetYellowTime () const
Note
This function does not call the simulator, it returns the data received in the last tick.
Definition at line 37 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
IsFrozen()
bool carla::client::TrafficLight::IsFrozen () const
Note
This function does not call the simulator, it returns the data received in the last tick.
Definition at line 58 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
ResetGroup()
void carla::client::TrafficLight::ResetGroup ()
Definition at line 77 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
SetGreenTime()
void carla::client::TrafficLight::SetGreenTime (float green_time)
Definition at line 25 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
SetRedTime()
void carla::client::TrafficLight::SetRedTime (float red_time)
Definition at line 41 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
SetState()
void carla::client::TrafficLight::SetState (rpc::TrafficLightState state)
Definition at line 17 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
SetYellowTime()
void carla::client::TrafficLight::SetYellowTime (float yellow_time)
Definition at line 33 of file TrafficLight.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by TrafficLight().
The documentation for this class was generated from the following files:
TrafficLight.h
TrafficLight.cpp