CARLA: FShapeVisitor Struct Reference
FShapeVisitor Struct Reference
Public Types
using Shape = carla::rpc::DebugShape
Public Member Functions
FShapeVisitor (UWorld &InWorld, FColor InColor, float InLifeTime, bool bInPersistentLines)
void operator() (const Shape::Point &Point) const
void operator() (const Shape::Line &Line) const
void operator() (const Shape::Arrow &Arrow) const
void operator() (const Shape::Box &Box) const
void operator() (const Shape::String &Str) const
Private Attributes
bool bPersistentLines
FLinearColor Color
uint8 DepthPriority = SDPG_World
float LifeTime
UWorld * World
Static Private Attributes
static constexpr double BrightMultiplier = 1.0
Detailed Description
Definition at line 23 of file DebugShapeDrawer.cpp.
Member Typedef Documentation
Shape
using FShapeVisitor::Shape = carla::rpc::DebugShape
Definition at line 25 of file DebugShapeDrawer.cpp.
Constructor & Destructor Documentation
FShapeVisitor()
FShapeVisitor::FShapeVisitor (UWorld & InWorld, FColor InColor, float InLifeTime, bool bInPersistentLines) inline
Definition at line 27 of file DebugShapeDrawer.cpp.
References World.
Referenced by FDebugShapeDrawer::Draw().
Member Function Documentation
operator()() [1/5]
void FShapeVisitor::operator() (const Shape::Point & Point) const inline
Definition at line 36 of file DebugShapeDrawer.cpp.
References Color, DepthPriority, UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalLocation(), LifeTime, carla::rpc::DebugShape::Point::location, carla::rpc::DebugShape::Point::size, and World.
operator()() [2/5]
void FShapeVisitor::operator() (const Shape::Line & Line) const inline
Definition at line 52 of file DebugShapeDrawer.cpp.
References carla::rpc::DebugShape::Line::begin, Color, DepthPriority, carla::rpc::DebugShape::Line::end, UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalLocation(), LifeTime, carla::rpc::DebugShape::Line::thickness, and World.
operator()() [3/5]
void FShapeVisitor::operator() (const Shape::Arrow & Arrow) const inline
Definition at line 71 of file DebugShapeDrawer.cpp.
References carla::rpc::DebugShape::Arrow::arrow_size, carla::rpc::DebugShape::Line::begin, Color, DepthPriority, carla::rpc::DebugShape::Line::end, UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalLocation(), LifeTime, carla::rpc::DebugShape::Arrow::line, carla::rpc::DebugShape::Line::thickness, and World.
operator()() [4/5]
void FShapeVisitor::operator() (const Shape::Box & Box) const inline
Definition at line 129 of file DebugShapeDrawer.cpp.
References carla::rpc::DebugShape::Box::box, Color, DepthPriority, carla::geom::BoundingBox::extent, UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalTransform(), LifeTime, carla::geom::BoundingBox::location, carla::rpc::DebugShape::Box::rotation, carla::rpc::DebugShape::Box::thickness, World, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
operator()() [5/5]
void FShapeVisitor::operator() (const Shape::String & Str) const inline
Definition at line 194 of file DebugShapeDrawer.cpp.
References ACarlaHUD::AddHUDString(), Color, UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalLocation(), LifeTime, carla::rpc::DebugShape::String::location, carla::rpc::DebugShape::String::text, and World.
Member Data Documentation
bPersistentLines
bool FShapeVisitor::bPersistentLines private
Definition at line 220 of file DebugShapeDrawer.cpp.
BrightMultiplier
constexpr double FShapeVisitor::BrightMultiplier = 1.0 static private
Definition at line 231 of file DebugShapeDrawer.cpp.
Color
FLinearColor FShapeVisitor::Color private
Definition at line 216 of file DebugShapeDrawer.cpp.
Referenced by operator()().
DepthPriority
uint8 FShapeVisitor::DepthPriority = SDPG_World private
Definition at line 222 of file DebugShapeDrawer.cpp.
Referenced by operator()().
LifeTime
float FShapeVisitor::LifeTime private
Definition at line 218 of file DebugShapeDrawer.cpp.
Referenced by operator()().
World
UWorld* FShapeVisitor::World private
Definition at line 214 of file DebugShapeDrawer.cpp.
Referenced by FDebugShapeDrawer::Draw(), FShapeVisitor(), and operator()().
The documentation for this struct was generated from the following file:
DebugShapeDrawer.cpp