CARLA: carla::traffic_manager::TrafficManagerServer Class Reference
carla::traffic_manager::TrafficManagerServer Class Reference
#include <TrafficManagerServer.h>
Public Member Functions
TrafficManagerServer & operator= (const TrafficManagerServer &)=default
TrafficManagerServer & operator= (TrafficManagerServer &&)=default
uint16_t port () const
TrafficManagerServer (const TrafficManagerServer &)=default
TrafficManagerServer (TrafficManagerServer &&)=default
TrafficManagerServer (uint16_t &RPCPort, carla::traffic_manager::TrafficManagerBase *tm)
Here RPCPort is the traffic manager local instance RPC server port where it can listen to remote traffic managers and apply the changes to local instance through a TrafficManagerBase pointer.
~TrafficManagerServer ()
Private Attributes
uint16_t _RPCPort
Traffic manager server RPC port.
::rpc::server * server = nullptr
Server instance.
Detailed Description
Definition at line 25 of file TrafficManagerServer.h.
Constructor & Destructor Documentation
TrafficManagerServer() [1/3]
carla::traffic_manager::TrafficManagerServer::TrafficManagerServer (const TrafficManagerServer &) default
TrafficManagerServer() [2/3]
carla::traffic_manager::TrafficManagerServer::TrafficManagerServer (TrafficManagerServer &&) default
TrafficManagerServer() [3/3]
carla::traffic_manager::TrafficManagerServer::TrafficManagerServer (uint16_t & RPCPort, carla::traffic_manager::TrafficManagerBase * tm) inline
Here RPCPort is the traffic manager local instance RPC server port where it can listen to remote traffic managers and apply the changes to local instance through a TrafficManagerBase pointer.
Create server instance.
Update port number and try again.
If server created.
If server still not created throw a runtime exception.
If the server creation was successful we are binding a lambda function to the name "register_vehicle".
Binding a lambda function to the name "unregister_vehicle".
Method to set a vehicle's % decrease in velocity with respect to the speed limit. If less than 0, it's a % increase.
Method to set a global % decrease in velocity with respect to the speed limit. If less than 0, it's a % increase.
Method to set collision detection rules between vehicles.
Method to force lane change on a vehicle. Direction flag can be set to true for left and false for right.
Enable/disable automatic lane change on a vehicle.
Method to specify how much distance a vehicle should maintain to the leading vehicle.
Method to the Global Distance to Leading vehicle
Method to specify the % chance of running any traffic light.
Method to specify the % chance of running any traffic sign.
Method to specify the % chance of ignoring collisions with any walker.
Method to specify the % chance of ignoring collisions with any vehicle.
Method to specify the % chance of ignoring collisions with any vehicle.
Method to set hybrid physics mode.
Method to set hybrid physics radius.
Method to set hybrid physics radius.
Method to set synchronous mode.
Method to set tick timeout for synchronous execution.
Method to set randomization seed.
Method to provide synchronous tick.
Method to check server is alive or not.
Run traffic manager server to respond of any user client in asynchronous mode.
Definition at line 37 of file TrafficManagerServer.h.
References carla::client::detail::Get(), carla::client::detail::ActorVariant::Get(), carla::traffic_manager::TrafficManagerBase::GetEpisodeProxy(), carla::traffic_manager::constants::Networking::MIN_TRY_COUNT, carla::traffic_manager::TrafficManagerBase::RegisterVehicles(), carla::traffic_manager::TrafficManagerBase::SetAutoLaneChange(), carla::traffic_manager::TrafficManagerBase::SetCollisionDetection(), carla::traffic_manager::TrafficManagerBase::SetDistanceToLeadingVehicle(), carla::traffic_manager::TrafficManagerBase::SetForceLaneChange(), carla::traffic_manager::TrafficManagerBase::SetGlobalDistanceToLeadingVehicle(), carla::traffic_manager::TrafficManagerBase::SetGlobalPercentageSpeedDifference(), carla::traffic_manager::TrafficManagerBase::SetHybridPhysicsMode(), carla::traffic_manager::TrafficManagerBase::SetHybridPhysicsRadius(), carla::traffic_manager::TrafficManagerBase::SetKeepRightPercentage(), carla::traffic_manager::TrafficManagerBase::SetPercentageIgnoreVehicles(), carla::traffic_manager::TrafficManagerBase::SetPercentageIgnoreWalkers(), carla::traffic_manager::TrafficManagerBase::SetPercentageRunningLight(), carla::traffic_manager::TrafficManagerBase::SetPercentageRunningSign(), carla::traffic_manager::TrafficManagerBase::SetPercentageSpeedDifference(), carla::traffic_manager::TrafficManagerBase::SetRandomDeviceSeed(), carla::traffic_manager::TrafficManagerBase::SetSynchronousMode(), carla::traffic_manager::TrafficManagerBase::SetSynchronousModeTimeOutInMiliSecond(), carla::traffic_manager::TrafficManagerBase::SynchronousTick(), carla::throw_exception(), and carla::traffic_manager::TrafficManagerBase::UnregisterVehicles().
~TrafficManagerServer()
carla::traffic_manager::TrafficManagerServer::~TrafficManagerServer () inline
Definition at line 201 of file TrafficManagerServer.h.
Member Function Documentation
operator=() [1/2]
TrafficManagerServer& carla::traffic_manager::TrafficManagerServer::operator= (const TrafficManagerServer &) default
operator=() [2/2]
TrafficManagerServer& carla::traffic_manager::TrafficManagerServer::operator= (TrafficManagerServer &&) default
port()
uint16_t carla::traffic_manager::TrafficManagerServer::port () const inline
Definition at line 209 of file TrafficManagerServer.h.
Referenced by carla::traffic_manager::TrafficManagerLocal::~TrafficManagerLocal().
Member Data Documentation
_RPCPort
uint16_t carla::traffic_manager::TrafficManagerServer::_RPCPort private
Traffic manager server RPC port.
Definition at line 216 of file TrafficManagerServer.h.
server
::rpc::server* carla::traffic_manager::TrafficManagerServer::server = nullptr private
Server instance.
Definition at line 219 of file TrafficManagerServer.h.
The documentation for this class was generated from the following file:
TrafficManagerServer.h