CARLA: test_listview.cpp File Reference
test_listview.cpp File Reference
#include "test.h"
#include <carla/ListView.h>
#include <array>
#include <cstring>
#include <list>
#include <set>
#include <string>
#include <vector>
Functions
TEST (listview, sequence)
TEST (listview, string)
template<typename Iterator >
static void TestSequence (carla::ListView< Iterator > view)
Function Documentation
TEST() [1/2]
TEST (listview , sequence)
Definition at line 30 of file test_listview.cpp.
References carla::MakeListView(), and TestSequence().
TEST() [2/2]
TEST (listview , string)
Definition at line 43 of file test_listview.cpp.
References carla::MakeListView().
TestSequence()
template<typename Iterator > static void TestSequence (carla::ListView< Iterator > view) static
Definition at line 21 of file test_listview.cpp.
Referenced by TEST().