CARLA: UCarSimManagerComponent Class Reference
UCarSimManagerComponent Class Reference
#include <CarSimManagerComponent.h>
Public Member Functions
virtual void BeginPlay () override
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
int32 GetVehicleCurrentGear () const override
float GetVehicleForwardSpeed () const override
FVector GetVelocity () const override
void ProcessControl (FVehicleControl &Control) override
virtual void TickComponent (float DeltaTime, ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
void UseCarSimRoad (bool bEnabled)
Static Public Member Functions
static void CreateCarsimComponent (ACarlaWheeledVehicle *Vehicle, FString Simfile)
Public Attributes
FString SimfilePath = ""
Private Member Functions
void OnCarSimEndOverlap (UPrimitiveComponent *OverlappedComponent, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex)
void OnCarSimHit (AActor *Actor, AActor *OtherActor, FVector NormalImpulse, const FHitResult &Hit)
void OnCarSimOverlap (UPrimitiveComponent *OverlappedComponent, AActor *OtherActor, UPrimitiveComponent *OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult &SweepResult)
Additional Inherited Members
Protected Member Functions inherited from UBaseCarlaMovementComponent
void DisableUE4VehiclePhysics ()
void EnableUE4VehiclePhysics (bool bResetVelocity=true)
Protected Attributes inherited from UBaseCarlaMovementComponent
ACarlaWheeledVehicle * CarlaVehicle
Detailed Description
Definition at line 22 of file CarSimManagerComponent.h.
Member Function Documentation
BeginPlay()
void UCarSimManagerComponent::BeginPlay () override virtual
Reimplemented from UBaseCarlaMovementComponent.
Definition at line 31 of file CarSimManagerComponent.cpp.
References UBaseCarlaMovementComponent::CarlaVehicle, ACarlaWheeledVehicle::CarSimOriginOffset, carla::log_warning(), OnCarSimEndOverlap(), OnCarSimHit(), OnCarSimOverlap(), and SimfilePath.
CreateCarsimComponent()
void UCarSimManagerComponent::CreateCarsimComponent (ACarlaWheeledVehicle * Vehicle, FString Simfile) static
Definition at line 18 of file CarSimManagerComponent.cpp.
References ACarlaWheeledVehicle::SetCarlaMovementComponent(), SimfilePath, and Vehicle.
Referenced by FVehicleActor::EnableCarSim().
EndPlay()
void UCarSimManagerComponent::EndPlay (const EEndPlayReason::Type EndPlayReason) override virtual
Definition at line 185 of file CarSimManagerComponent.cpp.
References UBaseCarlaMovementComponent::CarlaVehicle, OnCarSimEndOverlap(), OnCarSimHit(), and OnCarSimOverlap().
GetVehicleCurrentGear()
int32 UCarSimManagerComponent::GetVehicleCurrentGear () const override virtual
Reimplemented from UBaseCarlaMovementComponent.
Definition at line 216 of file CarSimManagerComponent.cpp.
GetVehicleForwardSpeed()
float UCarSimManagerComponent::GetVehicleForwardSpeed () const override virtual
Reimplemented from UBaseCarlaMovementComponent.
Definition at line 225 of file CarSimManagerComponent.cpp.
GetVelocity()
FVector UCarSimManagerComponent::GetVelocity () const override virtual
Reimplemented from UBaseCarlaMovementComponent.
Definition at line 207 of file CarSimManagerComponent.cpp.
OnCarSimEndOverlap()
void UCarSimManagerComponent::OnCarSimEndOverlap (UPrimitiveComponent * OverlappedComponent, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex) private
Definition at line 168 of file CarSimManagerComponent.cpp.
Referenced by BeginPlay(), and EndPlay().
OnCarSimHit()
void UCarSimManagerComponent::OnCarSimHit (AActor * Actor, AActor * OtherActor, FVector NormalImpulse, const FHitResult & Hit) private
Definition at line 106 of file CarSimManagerComponent.cpp.
References UBaseCarlaMovementComponent::CarlaVehicle, UDefaultMovementComponent::CreateDefaultMovementComponent(), carla::log_warning(), and ACarlaWheeledVehicle::RestoreVehiclePhysicsControl().
Referenced by BeginPlay(), and EndPlay().
OnCarSimOverlap()
void UCarSimManagerComponent::OnCarSimOverlap (UPrimitiveComponent * OverlappedComponent, AActor * OtherActor, UPrimitiveComponent * OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult & SweepResult) private
Definition at line 134 of file CarSimManagerComponent.cpp.
References UBaseCarlaMovementComponent::CarlaVehicle, UDefaultMovementComponent::CreateDefaultMovementComponent(), carla::log_warning(), and ACarlaWheeledVehicle::RestoreVehiclePhysicsControl().
Referenced by BeginPlay(), and EndPlay().
ProcessControl()
void UCarSimManagerComponent::ProcessControl (FVehicleControl & Control) override virtual
Reimplemented from UBaseCarlaMovementComponent.
Definition at line 92 of file CarSimManagerComponent.cpp.
References FVehicleControl::bHandBrake, FVehicleControl::Brake, FVehicleControl::Gear, FVehicleControl::Steer, and FVehicleControl::Throttle.
TickComponent()
void UCarSimManagerComponent::TickComponent (float DeltaTime, ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
Definition at line 88 of file CarSimManagerComponent.cpp.
UseCarSimRoad()
void UCarSimManagerComponent::UseCarSimRoad (bool bEnabled)
Definition at line 175 of file CarSimManagerComponent.cpp.
Referenced by FVehicleActor::UseCarSimRoad().
Member Data Documentation
SimfilePath
FString UCarSimManagerComponent::SimfilePath = ""
Definition at line 37 of file CarSimManagerComponent.h.
Referenced by BeginPlay(), and CreateCarsimComponent().
The documentation for this class was generated from the following files:
CarSimManagerComponent.h
CarSimManagerComponent.cpp