CARLA: UOpenDrive Class Reference
UOpenDrive Class Reference
#include <OpenDrive.h>
Static Public Member Functions
static FString FindPathToXODRFile (const FString &MapName)
Find the path to the XODR file associated to MapName.
static UOpenDriveMap * LoadCurrentOpenDriveMap (const UObject *WorldContextObject)
Load OpenDriveMap associated to the currently loaded map.
static UOpenDriveMap * LoadOpenDriveMap (const FString &MapName)
Load OpenDriveMap associated to the given MapName.
static FString LoadXODR (const FString &MapName)
Return the OpenDrive XML associated to MapName, or empty if the file is not found.
Detailed Description
Definition at line 16 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.h.
Member Function Documentation
FString UOpenDrive::FindPathToXODRFile (const FString & MapName) static
Find the path to the XODR file associated to MapName.
Return empty if no such file is found.
Definition at line 12 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp.
References carla::client::detail::Get(), and UCarlaEpisode::MapName.
Referenced by LoadXODR().
UOpenDriveMap * UOpenDrive::LoadCurrentOpenDriveMap (const UObject * WorldContextObject) static
Load OpenDriveMap associated to the currently loaded map.
Return nullptr if no XODR can be found that matches the current map.
Definition at line 87 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp.
References LoadOpenDriveMap().
UOpenDriveMap * UOpenDrive::LoadOpenDriveMap (const FString & MapName) static
Load OpenDriveMap associated to the given MapName.
Return nullptr if no XODR can be found with same MapName.
Definition at line 75 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp.
References UOpenDriveMap::Load(), and LoadXODR().
Referenced by LoadCurrentOpenDriveMap().
FString UOpenDrive::LoadXODR (const FString & MapName) static
Return the OpenDrive XML associated to MapName, or empty if the file is not found.
Definition at line 53 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp.
References FindPathToXODRFile().
Referenced by AOpenDriveGenerator::BeginPlay(), FCarlaServer::FPimpl::BindActions(), AOpenDriveActor::BuildRoutes(), ATrafficLightManager::GetMap(), LoadOpenDriveMap(), and ACarlaGameModeBase::ParseOpenDrive().
The documentation for this class was generated from the following files:
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.h
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDrive.cpp