CARLA: pugi::xml_document Class Reference
pugi::xml_document Class Reference
#include <pugixml.hpp>
Public Member Functions
xml_node document_element () const
xml_parse_result load (std::basic_istream< char, std::char_traits< char > > &stream, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load (std::basic_istream< wchar_t, std::char_traits< wchar_t > > &stream, unsigned int options=parse_default)
PUGIXML_DEPRECATED xml_parse_result load (const char_t *contents, unsigned int options=parse_default)
xml_parse_result load_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer_inplace (void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_buffer_inplace_own (void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_file (const char *path, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_file (const wchar_t *path, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_parse_result load_string (const char_t *contents, unsigned int options=parse_default)
void reset ()
void reset (const xml_document &proto)
void save (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
void save (std::basic_ostream< char, std::char_traits< char > > &stream, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
void save (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &stream, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default) const
bool save_file (const char *path, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
bool save_file (const wchar_t *path, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto) const
xml_document ()
~xml_document ()
Public Member Functions inherited from pugi::xml_node
xml_attribute append_attribute (const char_t *name)
xml_parse_result append_buffer (const void *contents, size_t size, unsigned int options=parse_default, xml_encoding encoding=encoding_auto)
xml_node append_child (xml_node_type type=node_element)
xml_node append_child (const char_t *name)
xml_attribute append_copy (const xml_attribute &proto)
xml_node append_copy (const xml_node &proto)
xml_node append_move (const xml_node &moved)
xml_attribute attribute (const char_t *name) const
xml_attribute attribute (const char_t *name, xml_attribute &hint) const
xml_object_range< xml_attribute_iterator > attributes () const
attribute_iterator attributes_begin () const
attribute_iterator attributes_end () const
iterator begin () const
xml_node child (const char_t *name) const
const char_t * child_value () const
const char_t * child_value (const char_t *name) const
xml_object_range< xml_node_iterator > children () const
xml_object_range< xml_named_node_iterator > children (const char_t *name) const
bool empty () const
iterator end () const
template<typename Predicate >
xml_attribute find_attribute (Predicate pred) const
template<typename Predicate >
xml_node find_child (Predicate pred) const
xml_node find_child_by_attribute (const char_t *name, const char_t *attr_name, const char_t *attr_value) const
xml_node find_child_by_attribute (const char_t *attr_name, const char_t *attr_value) const
template<typename Predicate >
xml_node find_node (Predicate pred) const
xml_attribute first_attribute () const
xml_node first_child () const
xml_node first_element_by_path (const char_t *path, char_t delimiter= '/') const
size_t hash_value () const
xml_attribute insert_attribute_after (const char_t *name, const xml_attribute &attr)
xml_attribute insert_attribute_before (const char_t *name, const xml_attribute &attr)
xml_node insert_child_after (xml_node_type type, const xml_node &node)
xml_node insert_child_after (const char_t *name, const xml_node &node)
xml_node insert_child_before (xml_node_type type, const xml_node &node)
xml_node insert_child_before (const char_t *name, const xml_node &node)
xml_attribute insert_copy_after (const xml_attribute &proto, const xml_attribute &attr)
xml_node insert_copy_after (const xml_node &proto, const xml_node &node)
xml_attribute insert_copy_before (const xml_attribute &proto, const xml_attribute &attr)
xml_node insert_copy_before (const xml_node &proto, const xml_node &node)
xml_node insert_move_after (const xml_node &moved, const xml_node &node)
xml_node insert_move_before (const xml_node &moved, const xml_node &node)
xml_node_struct * internal_object () const
xml_attribute last_attribute () const
xml_node last_child () const
const char_t * name () const
xml_node next_sibling () const
xml_node next_sibling (const char_t *name) const
ptrdiff_t offset_debug () const
operator unspecified_bool_type () const
bool operator! () const
bool operator!= (const xml_node &r) const
bool operator< (const xml_node &r) const
bool operator<= (const xml_node &r) const
bool operator== (const xml_node &r) const
bool operator> (const xml_node &r) const
bool operator>= (const xml_node &r) const
xml_node parent () const
string_t path (char_t delimiter= '/') const
xml_attribute prepend_attribute (const char_t *name)
xml_node prepend_child (xml_node_type type=node_element)
xml_node prepend_child (const char_t *name)
xml_attribute prepend_copy (const xml_attribute &proto)
xml_node prepend_copy (const xml_node &proto)
xml_node prepend_move (const xml_node &moved)
xml_node previous_sibling () const
xml_node previous_sibling (const char_t *name) const
void print (xml_writer &writer, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< char, std::char_traits< char > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, xml_encoding encoding=encoding_auto, unsigned int depth=0) const
void print (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > &os, const char_t *indent=PUGIXML_TEXT("\t"), unsigned int flags=format_default, unsigned int depth=0) const
bool remove_attribute (const xml_attribute &a)
bool remove_attribute (const char_t *name)
bool remove_child (const xml_node &n)
bool remove_child (const char_t *name)
xml_node root () const
xpath_node select_node (const char_t *query, xpath_variable_set *variables=0) const
xpath_node select_node (const xpath_query &query) const
xpath_node_set select_nodes (const char_t *query, xpath_variable_set *variables=0) const
xpath_node_set select_nodes (const xpath_query &query) const
PUGIXML_DEPRECATED xpath_node select_single_node (const char_t *query, xpath_variable_set *variables=0) const
PUGIXML_DEPRECATED xpath_node select_single_node (const xpath_query &query) const
bool set_name (const char_t *rhs)
bool set_value (const char_t *rhs)
xml_text text () const
bool traverse (xml_tree_walker &walker)
xml_node_type type () const
const char_t * value () const
xml_node ()
xml_node (xml_node_struct *p)
Private Member Functions
void _create ()
void _destroy ()
void _move (xml_document &rhs) PUGIXML_NOEXCEPT_IF_NOT_COMPACT
xml_document & operator= (const xml_document &)
xml_document (const xml_document &)
Private Attributes
char_t * _buffer
char _memory [192]
Additional Inherited Members
Public Types inherited from pugi::xml_node
typedef xml_attribute_iterator attribute_iterator
typedef xml_node_iterator iterator
Protected Types inherited from pugi::xml_node
typedef void(* unspecified_bool_type) (xml_node ***)
Protected Attributes inherited from pugi::xml_node
xml_node_struct * _root
Detailed Description
Definition at line 996 of file pugixml.hpp.
Constructor & Destructor Documentation
pugi::xml_document::xml_document (const xml_document &) private
PUGI__FN pugi::xml_document::xml_document ()
Definition at line 6843 of file pugixml.cpp.
References _create().
Referenced by ~xml_document().
PUGI__FN pugi::xml_document::~xml_document ()
Definition at line 6848 of file pugixml.cpp.
References _buffer, _create(), _destroy(), _move(), operator=(), PUGI__FN, PUGIXML_NOEXCEPT_IF_NOT_COMPACT, and xml_document().
Member Function Documentation
PUGI__FN void pugi::xml_document::_create () private
Definition at line 6886 of file pugixml.cpp.
References _memory, pugi::xml_node::_root, pugi::xml_node_struct::prev_sibling_c, PUGI__STATIC_ASSERT, and xml_memory_page_size.
Referenced by reset(), xml_document(), and ~xml_document().
PUGI__FN void pugi::xml_document::_destroy () private
Definition at line 6929 of file pugixml.cpp.
References _buffer, _memory, _move(), pugi::xml_node::_root, pugi::xml_node_struct::first_child, pugi::xml_node_struct::next_sibling, PUGI__FN, PUGI__GETPAGE, and PUGIXML_NOEXCEPT_IF_NOT_COMPACT.
Referenced by reset(), and ~xml_document().
void pugi::xml_document::_move (xml_document & rhs) private
Referenced by _destroy(), and ~xml_document().
PUGI__FN xml_node pugi::xml_document::document_element () const
Definition at line 7209 of file pugixml.cpp.
References pugi::xml_node::_root, pugi::xml_node_struct::first_child, pugi::xml_node_struct::next_sibling, pugi::node_element, PUGI__NODETYPE, and pugi::xml_node::xml_node().
PUGI__FN xml_parse_result pugi::xml_document::load (std::basic_istream< char, std::char_traits< char > > & stream, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 7076 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_stream_impl(), and reset().
PUGI__FN xml_parse_result pugi::xml_document::load (std::basic_istream< wchar_t, std::char_traits< wchar_t > > & stream, unsigned int options = parse_default)
Definition at line 7083 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, pugi::encoding_wchar, load_stream_impl(), and reset().
PUGI__FN xml_parse_result pugi::xml_document::load (const char_t * contents, unsigned int options = parse_default)
Definition at line 7103 of file pugixml.cpp.
References load_string().
PUGI__FN xml_parse_result pugi::xml_document::load_buffer (const void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 7128 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_buffer_impl(), and reset().
Referenced by load_string().
PUGI__FN xml_parse_result pugi::xml_document::load_buffer_inplace (void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 7135 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_buffer_impl(), and reset().
PUGI__FN xml_parse_result pugi::xml_document::load_buffer_inplace_own (void * contents, size_t size, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 7142 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, load_buffer_impl(), and reset().
PUGI__FN xml_parse_result pugi::xml_document::load_file (const char * path, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 7108 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, close_file(), auto_deleter< T >::data, load_file_impl(), and reset().
Referenced by TEST().
PUGI__FN xml_parse_result pugi::xml_document::load_file (const wchar_t * path, unsigned int options = parse_default, xml_encoding encoding = encoding_auto)
Definition at line 7118 of file pugixml.cpp.
References _buffer, pugi::xml_node::_root, close_file(), auto_deleter< T >::data, load_file_impl(), open_file_wide(), and reset().
PUGI__FN xml_parse_result pugi::xml_document::load_string (const char_t * contents, unsigned int options = parse_default)
Definition at line 7091 of file pugixml.cpp.
References pugi::encoding_utf8, pugi::encoding_wchar, load_buffer(), and strlength().
Referenced by carla::opendrive::OpenDriveParser::Load(), and load().
xml_document& pugi::xml_document::operator= (const xml_document &) private
Referenced by ~xml_document().
PUGI__FN void pugi::xml_document::reset ()
Definition at line 6872 of file pugixml.cpp.
References _create(), and _destroy().
Referenced by load(), load_buffer(), load_buffer_inplace(), load_buffer_inplace_own(), load_file(), and reset().
PUGI__FN void pugi::xml_document::reset (const xml_document & proto)
Definition at line 6878 of file pugixml.cpp.
References pugi::xml_node::append_copy(), pugi::xml_node::first_child(), pugi::xml_node::next_sibling(), and reset().
PUGI__FN void pugi::xml_document::save (xml_writer & writer, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 7149 of file pugixml.cpp.
References pugi::xml_node::_root, pugi::encoding_latin1, pugi::format_no_declaration, pugi::format_raw, pugi::format_write_bom, has_declaration(), node_output(), and PUGIXML_TEXT.
Referenced by save().
PUGI__FN void pugi::xml_document::save (std::basic_ostream< char, std::char_traits< char > > & stream, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 7178 of file pugixml.cpp.
References save().
PUGI__FN void pugi::xml_document::save (std::basic_ostream< wchar_t, std::char_traits< wchar_t > > & stream, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default) const
Definition at line 7185 of file pugixml.cpp.
References pugi::encoding_wchar, and save().
PUGI__FN bool pugi::xml_document::save_file (const char * path, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 7193 of file pugixml.cpp.
References close_file(), auto_deleter< T >::data, pugi::format_save_file_text, and save_file_impl().
PUGI__FN bool pugi::xml_document::save_file (const wchar_t * path, const char_t * indent = PUGIXML_TEXT("\t"), unsigned int flags = format_default, xml_encoding encoding = encoding_auto) const
Definition at line 7201 of file pugixml.cpp.
References close_file(), auto_deleter< T >::data, pugi::format_save_file_text, open_file_wide(), and save_file_impl().
Member Data Documentation
char_t* pugi::xml_document::_buffer private
Definition at line 999 of file pugixml.hpp.
Referenced by _destroy(), xpath_string::c_str(), xpath_string::data(), load(), load_buffer(), load_buffer_inplace(), load_buffer_inplace_own(), load_file(), and ~xml_document().
char pugi::xml_document::_memory[192] private
Definition at line 1001 of file pugixml.hpp.
Referenced by _create(), and _destroy().
The documentation for this class was generated from the following files:
pugixml.hpp
pugixml.cpp