CARLA: MapGen::RoadSegmentBuilder Class Reference
MapGen::RoadSegmentBuilder Class Reference
Public Member Functions
void Add (Graph::HalfEdge &edge)
void Close ()
RoadSegmentBuilder (const Graph &graph)
Public Attributes
std::vector< TUniquePtr< RoadSegmentDescription > > Segments
Private Member Functions
bool insert (Graph::HalfEdge &edge)
Insert both half-edges only if they haven't been visited yet.
Private Attributes
const Graph & _graph
bool _handlingInitial = true
std::vector< const Graph::HalfEdge * > _initial
std::unordered_set< const Graph::HalfEdge * > _visitedEdges
Detailed Description
Definition at line 92 of file GraphParser.cpp.
Constructor & Destructor Documentation
MapGen::RoadSegmentBuilder::RoadSegmentBuilder (const Graph & graph) inline explicit
Definition at line 97 of file GraphParser.cpp.
Member Function Documentation
void MapGen::RoadSegmentBuilder::Add (Graph::HalfEdge & edge) inline
Definition at line 99 of file GraphParser.cpp.
References _handlingInitial, _initial, MapGen::DoublyConnectedEdgeList::GetSource(), and insert().
Referenced by MapGen::GraphParser::GraphParser().
void MapGen::RoadSegmentBuilder::Close () inline
Definition at line 113 of file GraphParser.cpp.
References _handlingInitial, and _initial.
Referenced by MapGen::GraphParser::GraphParser().
bool MapGen::RoadSegmentBuilder::insert (Graph::HalfEdge & edge) inline private
Insert both half-edges only if they haven't been visited yet.
Definition at line 123 of file GraphParser.cpp.
References _visitedEdges, and MapGen::DoublyConnectedEdgeList::GetPair().
Referenced by Add().
Member Data Documentation
const Graph& MapGen::RoadSegmentBuilder::_graph private
Definition at line 128 of file GraphParser.cpp.
bool MapGen::RoadSegmentBuilder::_handlingInitial = true private
Definition at line 132 of file GraphParser.cpp.
Referenced by Add(), and Close().
std::vector<const Graph::HalfEdge *> MapGen::RoadSegmentBuilder::_initial private
Definition at line 134 of file GraphParser.cpp.
Referenced by Add(), and Close().
std::unordered_set<const Graph::HalfEdge *> MapGen::RoadSegmentBuilder::_visitedEdges private
Definition at line 130 of file GraphParser.cpp.
Referenced by insert().
std::vector<TUniquePtr<RoadSegmentDescription> > MapGen::RoadSegmentBuilder::Segments
Definition at line 95 of file GraphParser.cpp.
Referenced by MapGen::GraphParser::GraphParser().
The documentation for this class was generated from the following file:
GraphParser.cpp