CARLA: carla::client::Map Class Reference
carla::client::Map Class Reference
#include <Map.h>
Public Types
using TopologyList = std::vector< std::pair< SharedPtr< Waypoint >, SharedPtr< Waypoint >>>
Public Member Functions
std::vector< road::element::LaneMarking > CalculateCrossedLanes (const geom::Location &origin, const geom::Location &destination) const
std::vector< SharedPtr< Waypoint > > GenerateWaypoints (double distance) const
std::vector< geom::Location > GetAllCrosswalkZones () const
const geom::GeoLocation & GetGeoReference () const
SharedPtr< Junction > GetJunction (const Waypoint &waypoint) const
std::vector< std::pair< SharedPtr< Waypoint >, SharedPtr< Waypoint > > > GetJunctionWaypoints (road::JuncId id, road::Lane::LaneType type) const
Returns a pair of waypoints (start and end) for each lane in the junction.
const road::Map & GetMap () const
const std::string & GetName () const
const std::string & GetOpenDrive () const
const std::vector< geom::Transform > & GetRecommendedSpawnPoints () const
TopologyList GetTopology () const
SharedPtr< Waypoint > GetWaypoint (const geom::Location &location, bool project_to_road=true, uint32_t lane_type=static_cast< uint32_t >(road::Lane::LaneType::Driving)) const
SharedPtr< Waypoint > GetWaypointXODR (carla::road::RoadId road_id, carla::road::LaneId lane_id, float s) const
Map (rpc::MapInfo description)
Map (std::string name, std::string xodr_content)
~Map ()
Private Attributes
const rpc::MapInfo _description
const road::Map _map
Additional Inherited Members
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Detailed Description
Definition at line 26 of file client/Map.h.
Member Typedef Documentation
using carla::client::Map::TopologyList = std::vector<std::pair<SharedPtr<Waypoint>, SharedPtr<Waypoint>>>
Definition at line 63 of file client/Map.h.
Constructor & Destructor Documentation
carla::client::Map::Map (rpc::MapInfo description) explicit
Definition at line 29 of file client/Map.cpp.
carla::client::Map::Map (std::string name, std::string xodr_content) explicit
Definition at line 33 of file client/Map.cpp.
References ~Map().
carla::client::Map::~Map () default
Referenced by Map().
Member Function Documentation
std::vector< road::element::LaneMarking > carla::client::Map::CalculateCrossedLanes (const geom::Location & origin, const geom::Location & destination) const
Definition at line 102 of file client/Map.cpp.
References _map, and carla::road::Map::CalculateCrossedLanes().
std::vector< SharedPtr< Waypoint > > carla::client::Map::GenerateWaypoints (double distance) const
Definition at line 92 of file client/Map.cpp.
References _map, and carla::road::Map::GenerateWaypoints().
std::vector< geom::Location > carla::client::Map::GetAllCrosswalkZones () const
Definition at line 112 of file client/Map.cpp.
References _map, and carla::road::Map::GetAllCrosswalkZones().
const geom::GeoLocation & carla::client::Map::GetGeoReference () const
Definition at line 108 of file client/Map.cpp.
References _map, and carla::road::Map::GetGeoReference().
SharedPtr< Junction > carla::client::Map::GetJunction (const Waypoint & waypoint) const
Definition at line 116 of file client/Map.cpp.
References carla::road::Map::GetJunction(), carla::client::Waypoint::GetJunctionId(), and GetMap().
std::vector< std::pair< SharedPtr< Waypoint >, SharedPtr< Waypoint > > > carla::client::Map::GetJunctionWaypoints (road::JuncId id, road::Lane::LaneType type) const
Returns a pair of waypoints (start and end) for each lane in the junction.
Definition at line 122 of file client/Map.cpp.
References carla::road::Map::GetJunctionWaypoints(), and GetMap().
const road::Map& carla::client::Map::GetMap () const inline
Definition at line 41 of file client/Map.h.
Referenced by GetJunction(), and GetJunctionWaypoints().
const std::string& carla::client::Map::GetName () const inline
Definition at line 37 of file client/Map.h.
const std::string& carla::client::Map::GetOpenDrive () const inline
Definition at line 45 of file client/Map.h.
const std::vector<geom::Transform>& carla::client::Map::GetRecommendedSpawnPoints () const inline
Definition at line 49 of file client/Map.h.
References carla::road::Lane::Driving.
Map::TopologyList carla::client::Map::GetTopology () const
Definition at line 67 of file client/Map.cpp.
References _map, and carla::road::Map::GenerateTopology().
SharedPtr< Waypoint > carla::client::Map::GetWaypoint (const geom::Location & location, bool project_to_road = true, uint32_t lane_type = static_cast<uint32_t>(road::Lane::LaneType::Driving)) const
Definition at line 41 of file client/Map.cpp.
References _map, carla::road::Map::GetClosestWaypointOnRoad(), and carla::road::Map::GetWaypoint().
SharedPtr< Waypoint > carla::client::Map::GetWaypointXODR (carla::road::RoadId road_id, carla::road::LaneId lane_id, float s) const
Definition at line 56 of file client/Map.cpp.
References _map, and carla::road::Map::GetWaypoint().
Member Data Documentation
const rpc::MapInfo carla::client::Map::_description private
Definition at line 86 of file client/Map.h.
const road::Map carla::client::Map::_map private
Definition at line 88 of file client/Map.h.
Referenced by CalculateCrossedLanes(), GenerateWaypoints(), GetAllCrosswalkZones(), GetGeoReference(), GetTopology(), GetWaypoint(), and GetWaypointXODR().
The documentation for this class was generated from the following files:
client/Map.h
client/Map.cpp