CARLA: FVehicleData Class Reference
FVehicleData Class Reference
#include <ActorData.h>
Public Member Functions
virtual void RecordActorData (FCarlaActor *CarlaActor, UCarlaEpisode *CarlaEpisode) override
virtual void RestoreActorData (FCarlaActor *CarlaActor, UCarlaEpisode *CarlaEpisode) override
Public Member Functions inherited from FActorData
FTransform GetLocalTransform (UCarlaEpisode *CarlaEpisode) const
virtual AActor * RespawnActor (UCarlaEpisode *CarlaEpisode, const FActorInfo &Info)
virtual ~FActorData ()
Public Attributes
FVehicleAckermannControl AckermannControl
FAckermannControllerSettings AckermannControllerSettings
bool bAckermannControlActive = false
FVehicleControl Control
carla::rpc::VehicleFailureState FailureState
FVehicleLightState LightState
FVehiclePhysicsControl PhysicsControl
float SpeedLimit = 30
Public Attributes inherited from FActorData
FVector AngularVelocity = FVector(0,0,0)
bool bSimulatePhysics = false
FDVector Location
FQuat Rotation
FVector Scale
FVector Velocity
Detailed Description
Definition at line 55 of file ActorData.h.
Member Function Documentation
RecordActorData()
void FVehicleData::RecordActorData (FCarlaActor * CarlaActor, UCarlaEpisode * CarlaEpisode) override virtual
Reimplemented from FActorData.
Definition at line 89 of file ActorData.cpp.
References FActorData::bSimulatePhysics, ACarlaWheeledVehicle::GetAckermannControllerSettings(), FCarlaActor::GetActor(), ACarlaWheeledVehicle::GetFailureState(), ACarlaWheeledVehicle::GetVehicleAckermannControl(), ACarlaWheeledVehicle::GetVehicleControl(), ACarlaWheeledVehicle::GetVehicleLightState(), ACarlaWheeledVehicle::GetVehiclePhysicsControl(), ACarlaWheeledVehicle::IsAckermannControlActive(), PhysicsControl, FActorData::RecordActorData(), and Vehicle.
RestoreActorData()
void FVehicleData::RestoreActorData (FCarlaActor * CarlaActor, UCarlaEpisode * CarlaEpisode) override virtual
Reimplemented from FActorData.
Definition at line 111 of file ActorData.cpp.
References ACarlaWheeledVehicle::ApplyAckermannControllerSettings(), ACarlaWheeledVehicle::ApplyVehicleAckermannControl(), ACarlaWheeledVehicle::ApplyVehicleControl(), ACarlaWheeledVehicle::ApplyVehiclePhysicsControl(), FActorData::bSimulatePhysics, FCarlaActor::GetActor(), PhysicsControl, FActorData::RestoreActorData(), ACarlaWheeledVehicle::SetFailureState(), ACarlaWheeledVehicle::SetSimulatePhysics(), ACarlaWheeledVehicle::SetVehicleLightState(), and Vehicle.
Member Data Documentation
AckermannControl
FVehicleAckermannControl FVehicleData::AckermannControl
Definition at line 63 of file ActorData.h.
Referenced by FVehicleActor::ApplyAckermannControlToVehicle(), and FVehicleActor::GetVehicleAckermannControl().
AckermannControllerSettings
FAckermannControllerSettings FVehicleData::AckermannControllerSettings
Definition at line 67 of file ActorData.h.
Referenced by FVehicleActor::ApplyAckermannControllerSettings(), and FVehicleActor::GetAckermannControllerSettings().
bAckermannControlActive
bool FVehicleData::bAckermannControlActive = false
Definition at line 65 of file ActorData.h.
Referenced by FVehicleActor::ApplyAckermannControlToVehicle(), and FVehicleActor::ApplyControlToVehicle().
Control
FVehicleControl FVehicleData::Control
Definition at line 61 of file ActorData.h.
Referenced by FVehicleActor::ApplyControlToVehicle(), FWorldObserver_GetDormantActorState(), and FVehicleActor::GetVehicleControl().
FailureState
carla::rpc::VehicleFailureState FVehicleData::FailureState
Definition at line 73 of file ActorData.h.
Referenced by FVehicleActor::GetFailureState().
LightState
FVehicleLightState FVehicleData::LightState
Definition at line 69 of file ActorData.h.
Referenced by FVehicleActor::GetVehicleLightState(), and FVehicleActor::SetVehicleLightState().
PhysicsControl
FVehiclePhysicsControl FVehicleData::PhysicsControl
Definition at line 59 of file ActorData.h.
Referenced by FVehicleActor::ApplyPhysicsControl(), and FVehicleActor::GetPhysicsControl().
SpeedLimit
float FVehicleData::SpeedLimit = 30
Definition at line 71 of file ActorData.h.
Referenced by FWorldObserver_GetDormantActorState().
The documentation for this class was generated from the following files:
ActorData.h
ActorData.cpp