CARLA: MapGen::GraphParser Class Reference
MapGen::GraphParser Class Reference
#include <GraphParser.h>
Public Member Functions
size_t CityAreaCount () const
const CityAreaDescription & GetCityAreaAt (size_t i) const
const RoadSegmentDescription & GetRoadSegmentAt (size_t i) const
GraphParser (DoublyConnectedEdgeList &Dcel)
bool HasCityAreas () const
bool HasRoadSegments () const
TUniquePtr< CityAreaDescription > PopCityArea ()
TUniquePtr< RoadSegmentDescription > PopRoadSegment ()
size_t RoadSegmentCount () const
Private Types
using CityAreaList = std::vector< TUniquePtr< CityAreaDescription >>
using RoadSegmentList = std::vector< TUniquePtr< RoadSegmentDescription >>
Private Attributes
CityAreaList CityAreas
RoadSegmentList RoadSegments
Additional Inherited Members
Private Member Functions inherited from NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
void operator= (const NonCopyable &)=delete
Detailed Description
Definition at line 19 of file GraphParser.h.
Member Typedef Documentation
using MapGen::GraphParser::CityAreaList = std::vector<TUniquePtr<CityAreaDescription>> private
Definition at line 65 of file GraphParser.h.
using MapGen::GraphParser::RoadSegmentList = std::vector<TUniquePtr<RoadSegmentDescription>> private
Definition at line 63 of file GraphParser.h.
Constructor & Destructor Documentation
MapGen::GraphParser::GraphParser (DoublyConnectedEdgeList & Dcel) explicit
Definition at line 141 of file GraphParser.cpp.
References MapGen::CityAreaDescription::Add(), MapGen::RoadSegmentBuilder::Add(), MapGen::RoadSegmentBuilder::Close(), MapGen::DoublyConnectedEdgeList::CountFaces(), MapGen::DoublyConnectedEdgeList::CountHalfEdges(), MapGen::DoublyConnectedEdgeList::CountNodes(), MapGen::fixGraphData(), MapGen::DoublyConnectedEdgeList::GetFaces(), MapGen::DoublyConnectedEdgeList::GetHalfEdge(), MapGen::DoublyConnectedEdgeList::GetNextInFace(), MapGen::DoublyConnectedEdgeList::GetSource(), and MapGen::RoadSegmentBuilder::Segments.
Member Function Documentation
size_t MapGen::GraphParser::CityAreaCount () const inline
Definition at line 37 of file GraphParser.h.
References CityAreas.
const CityAreaDescription& MapGen::GraphParser::GetCityAreaAt (size_t i) const inline
Definition at line 45 of file GraphParser.h.
References CityAreas.
const RoadSegmentDescription& MapGen::GraphParser::GetRoadSegmentAt (size_t i) const inline
Definition at line 41 of file GraphParser.h.
References RoadSegments.
bool MapGen::GraphParser::HasCityAreas () const inline
Definition at line 29 of file GraphParser.h.
References CityAreas.
bool MapGen::GraphParser::HasRoadSegments () const inline
Definition at line 25 of file GraphParser.h.
References RoadSegments.
TUniquePtr<CityAreaDescription> MapGen::GraphParser::PopCityArea () inline
Definition at line 55 of file GraphParser.h.
References CityAreas.
TUniquePtr<RoadSegmentDescription> MapGen::GraphParser::PopRoadSegment () inline
Definition at line 49 of file GraphParser.h.
References RoadSegments.
size_t MapGen::GraphParser::RoadSegmentCount () const inline
Definition at line 33 of file GraphParser.h.
References RoadSegments.
Member Data Documentation
CityAreaList MapGen::GraphParser::CityAreas private
Definition at line 69 of file GraphParser.h.
Referenced by CityAreaCount(), GetCityAreaAt(), HasCityAreas(), and PopCityArea().
RoadSegmentList MapGen::GraphParser::RoadSegments private
Definition at line 67 of file GraphParser.h.
Referenced by GetRoadSegmentAt(), HasRoadSegments(), PopRoadSegment(), and RoadSegmentCount().
The documentation for this class was generated from the following files:
GraphParser.h
GraphParser.cpp