CARLA: traffic_manager::TrackTraffic Class Reference
traffic_manager::TrackTraffic Class Reference
#include <LocalizationUtils.h>
Public Member Functions
ActorIdSet GetOverlappingVehicles (ActorId actor_id)
ActorIdSet GetPassingVehicles (uint64_t waypoint_id)
void RemoveOverlappingVehicle (ActorId actor_id, ActorId other_id)
void RemovePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
TrackTraffic ()
void UpdateOverlappingVehicle (ActorId actor_id, ActorId other_id)
Methods to update, remove and retrieve vehicles with overlapping vehicles.
void UpdatePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
Methods to update, remove and retrieve vehicles passing through a waypoint.
Private Types
using WaypointOverlap = std::unordered_map< uint64_t, ActorIdSet >
Structure to keep track of overlapping waypoints between vehicles.
Private Attributes
ActorIdSet actor_id_set_record
Stored vehicle id set record.
std::unordered_map< ActorId, ActorIdSet > overlapping_vehicles
Structure to keep track of vehicles with overlapping paths.
WaypointOverlap waypoint_overlap_tracker
Detailed Description
Definition at line 26 of file LocalizationUtils.h.
Member Typedef Documentation
using traffic_manager::TrackTraffic::WaypointOverlap = std::unordered_map<uint64_t, ActorIdSet> private
Structure to keep track of overlapping waypoints between vehicles.
Definition at line 30 of file LocalizationUtils.h.
Constructor & Destructor Documentation
traffic_manager::TrackTraffic::TrackTraffic ()
Definition at line 53 of file LocalizationUtils.cpp.
Member Function Documentation
ActorIdSet traffic_manager::TrackTraffic::GetOverlappingVehicles (ActorId actor_id)
Definition at line 77 of file LocalizationUtils.cpp.
References overlapping_vehicles.
Referenced by traffic_manager::LocalizationStage::Action(), traffic_manager::LocalizationStage::AssignLaneChange(), and traffic_manager::LocalizationStage::PopWaypoint().
ActorIdSet traffic_manager::TrackTraffic::GetPassingVehicles (uint64_t waypoint_id)
Definition at line 117 of file LocalizationUtils.cpp.
References waypoint_overlap_tracker.
Referenced by traffic_manager::LocalizationStage::AssignLaneChange(), traffic_manager::LocalizationStage::PopWaypoint(), and traffic_manager::LocalizationStage::PushWaypoint().
void traffic_manager::TrackTraffic::RemoveOverlappingVehicle (ActorId actor_id, ActorId other_id)
Definition at line 67 of file LocalizationUtils.cpp.
References overlapping_vehicles.
Referenced by traffic_manager::LocalizationStage::Action(), and traffic_manager::LocalizationStage::PopWaypoint().
void traffic_manager::TrackTraffic::RemovePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
Definition at line 102 of file LocalizationUtils.cpp.
References waypoint_overlap_tracker.
Referenced by traffic_manager::LocalizationStage::PopWaypoint().
void traffic_manager::TrackTraffic::UpdateOverlappingVehicle (ActorId actor_id, ActorId other_id)
Methods to update, remove and retrieve vehicles with overlapping vehicles.
Definition at line 55 of file LocalizationUtils.cpp.
References overlapping_vehicles.
Referenced by traffic_manager::LocalizationStage::PushWaypoint().
void traffic_manager::TrackTraffic::UpdatePassingVehicle (uint64_t waypoint_id, ActorId actor_id)
Methods to update, remove and retrieve vehicles passing through a waypoint.
Definition at line 87 of file LocalizationUtils.cpp.
References waypoint_overlap_tracker.
Referenced by traffic_manager::LocalizationStage::PushWaypoint().
Member Data Documentation
ActorIdSet traffic_manager::TrackTraffic::actor_id_set_record private
Stored vehicle id set record.
Definition at line 35 of file LocalizationUtils.h.
std::unordered_map<ActorId, ActorIdSet> traffic_manager::TrackTraffic::overlapping_vehicles private
Structure to keep track of vehicles with overlapping paths.
Definition at line 33 of file LocalizationUtils.h.
Referenced by GetOverlappingVehicles(), RemoveOverlappingVehicle(), and UpdateOverlappingVehicle().
WaypointOverlap traffic_manager::TrackTraffic::waypoint_overlap_tracker private
Definition at line 31 of file LocalizationUtils.h.
Referenced by GetPassingVehicles(), RemovePassingVehicle(), and UpdatePassingVehicle().
The documentation for this class was generated from the following files:
LocalizationUtils.h
LocalizationUtils.cpp