CARLA: carla::road::Signal Class Reference
carla::road::Signal Class Reference
#include <Signal.h>
Public Member Functions
const std::set< ContId > & GetControllers () const
const std::string & GetCountry () const
const std::vector< SignalDependency > & GetDependencies ()
bool GetDynamic () const
double GetHeight () const
double GetHOffset () const
const std::string & GetName () const
SignalOrientation GetOrientation () const
double GetPitch () const
RoadId GetRoadId () const
double GetRoll () const
double GetS () const
const SignId & GetSignalId () const
const std::string & GetSubtype () const
double GetT () const
const std::string & GetText () const
const geom::Transform & GetTransform () const
const std::string & GetType () const
const std::string & GetUnit () const
double GetValue () const
double GetWidth () const
double GetZOffset () const
Signal (RoadId road_id, SignId signal_id, double s, double t, std::string name, std::string dynamic, std::string orientation, double zOffset, std::string country, std::string type, std::string subtype, double value, std::string unit, double height, double width, std::string text, double hOffset, double pitch, double roll)
Private Attributes
std::set< ContId > _controllers
std::string _country
std::vector< SignalDependency > _dependencies
std::string _dynamic
double _height
double _hOffset
std::string _name
std::string _orientation
double _pitch
RoadId _road_id
double _roll
double _s
SignId _signal_id
std::string _subtype
double _t
std::string _text
geom::Transform _transform
std::string _type
std::string _unit
double _value
double _width
double _zOffset
friend MapBuilder
Additional Inherited Members
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Detailed Description
Definition at line 39 of file Signal.h.
Constructor & Destructor Documentation
Signal()
carla::road::Signal::Signal (RoadId road_id, SignId signal_id, double s, double t, std::string name, std::string dynamic, std::string orientation, double zOffset, std::string country, std::string type, std::string subtype, double value, std::string unit, double height, double width, std::string text, double hOffset, double pitch, double roll) inline
Definition at line 41 of file Signal.h.
Member Function Documentation
GetControllers()
const std::set<ContId>& carla::road::Signal::GetControllers () const inline
Definition at line 176 of file Signal.h.
Referenced by carla::client::Map::GetLandmarkGroup().
GetCountry()
const std::string& carla::road::Signal::GetCountry () const inline
Definition at line 123 of file Signal.h.
Referenced by carla::client::Landmark::GetCountry().
GetDependencies()
const std::vector<SignalDependency>& carla::road::Signal::GetDependencies () inline
Definition at line 168 of file Signal.h.
GetDynamic()
bool carla::road::Signal::GetDynamic () const inline
Definition at line 97 of file Signal.h.
Referenced by carla::road::element::RoadInfoSignal::IsDynamic().
GetHeight()
double carla::road::Signal::GetHeight () const inline
Definition at line 143 of file Signal.h.
Referenced by carla::client::Landmark::GetHeight().
GetHOffset()
double carla::road::Signal::GetHOffset () const inline
Definition at line 155 of file Signal.h.
Referenced by carla::client::Landmark::GethOffset().
GetName()
const std::string& carla::road::Signal::GetName () const inline
Definition at line 105 of file Signal.h.
Referenced by carla::client::Landmark::GetName().
GetOrientation()
SignalOrientation carla::road::Signal::GetOrientation () const inline
Definition at line 109 of file Signal.h.
References carla::road::Both, carla::road::Negative, and carla::road::Positive.
GetPitch()
double carla::road::Signal::GetPitch () const inline
Definition at line 159 of file Signal.h.
Referenced by carla::client::Landmark::GetPitch().
GetRoadId()
RoadId carla::road::Signal::GetRoadId () const inline
Definition at line 81 of file Signal.h.
GetRoll()
double carla::road::Signal::GetRoll () const inline
Definition at line 163 of file Signal.h.
Referenced by carla::client::Landmark::GetRoll().
GetS()
double carla::road::Signal::GetS () const inline
Definition at line 89 of file Signal.h.
GetSignalId()
const SignId& carla::road::Signal::GetSignalId () const inline
Definition at line 85 of file Signal.h.
GetSubtype()
const std::string& carla::road::Signal::GetSubtype () const inline
Definition at line 131 of file Signal.h.
Referenced by carla::client::Landmark::GetSubType(), and MatchSignalAndActor().
GetT()
double carla::road::Signal::GetT () const inline
Definition at line 93 of file Signal.h.
GetText()
const std::string& carla::road::Signal::GetText () const inline
Definition at line 151 of file Signal.h.
Referenced by carla::client::Landmark::GetText().
GetTransform()
const geom::Transform& carla::road::Signal::GetTransform () const inline
Definition at line 172 of file Signal.h.
Referenced by GetClosestTrafficSignActor(), and carla::client::Landmark::GetTransform().
GetType()
const std::string& carla::road::Signal::GetType () const inline
Definition at line 127 of file Signal.h.
References carla::road::SignalDependency::_type.
Referenced by carla::client::Landmark::GetType(), and MatchSignalAndActor().
GetUnit()
const std::string& carla::road::Signal::GetUnit () const inline
Definition at line 139 of file Signal.h.
Referenced by carla::client::Landmark::GetUnit().
GetValue()
double carla::road::Signal::GetValue () const inline
Definition at line 135 of file Signal.h.
Referenced by carla::client::Landmark::GetValue().
GetWidth()
double carla::road::Signal::GetWidth () const inline
Definition at line 147 of file Signal.h.
Referenced by carla::client::Landmark::GetWidth().
GetZOffset()
double carla::road::Signal::GetZOffset () const inline
Definition at line 119 of file Signal.h.
Referenced by carla::client::Landmark::GetZOffset().
Member Data Documentation
_controllers
std::set<ContId> carla::road::Signal::_controllers private
Definition at line 225 of file Signal.h.
_country
std::string carla::road::Signal::_country private
Definition at line 199 of file Signal.h.
_dependencies
std::vector<SignalDependency> carla::road::Signal::_dependencies private
Definition at line 221 of file Signal.h.
_dynamic
std::string carla::road::Signal::_dynamic private
Definition at line 193 of file Signal.h.
_height
double carla::road::Signal::_height private
Definition at line 209 of file Signal.h.
_hOffset
double carla::road::Signal::_hOffset private
Definition at line 215 of file Signal.h.
_name
std::string carla::road::Signal::_name private
Definition at line 191 of file Signal.h.
_orientation
std::string carla::road::Signal::_orientation private
Definition at line 195 of file Signal.h.
_pitch
double carla::road::Signal::_pitch private
Definition at line 217 of file Signal.h.
_road_id
RoadId carla::road::Signal::_road_id private
Definition at line 183 of file Signal.h.
_roll
double carla::road::Signal::_roll private
Definition at line 219 of file Signal.h.
_s
double carla::road::Signal::_s private
Definition at line 187 of file Signal.h.
_signal_id
SignId carla::road::Signal::_signal_id private
Definition at line 185 of file Signal.h.
_subtype
std::string carla::road::Signal::_subtype private
Definition at line 203 of file Signal.h.
_t
double carla::road::Signal::_t private
Definition at line 189 of file Signal.h.
_text
std::string carla::road::Signal::_text private
Definition at line 213 of file Signal.h.
_transform
geom::Transform carla::road::Signal::_transform private
Definition at line 223 of file Signal.h.
_type
std::string carla::road::Signal::_type private
Definition at line 201 of file Signal.h.
_unit
std::string carla::road::Signal::_unit private
Definition at line 207 of file Signal.h.
_value
double carla::road::Signal::_value private
Definition at line 205 of file Signal.h.
_width
double carla::road::Signal::_width private
Definition at line 211 of file Signal.h.
_zOffset
double carla::road::Signal::_zOffset private
Definition at line 197 of file Signal.h.
MapBuilder
friend carla::road::Signal::MapBuilder private
Definition at line 181 of file Signal.h.
The documentation for this class was generated from the following file:
Signal.h