CARLA: ASceneCaptureCamera Class Reference
ASceneCaptureCamera Class Reference
A sensor that captures images from the scene.
#include <SceneCaptureCamera.h>
Public Member Functions
ASceneCaptureCamera (const FObjectInitializer &ObjectInitializer)
Public Member Functions inherited from AShaderBasedSensor
bool AddPostProcessingMaterial (const FString &Path)
Load the UMaterialInstanceDynamic at the given Path and append it to the list of shaders with Weight.
void AddShader (const FSensorShader &Shader)
Add a post-processing shader.
AShaderBasedSensor (const FObjectInitializer &ObjectInitializer)
void Set (const FActorDescription &ActorDescription) override
void SetFloatShaderParameter (uint8_t ShaderIndex, const FName &ParameterName, float Value)
Public Member Functions inherited from ASceneCaptureSensor
bool ArePostProcessingEffectsEnabled () const
ASceneCaptureSensor (const FObjectInitializer &ObjectInitializer)
void EnablePostProcessingEffects (bool Enable=true)
float GetAperture () const
int GetBladeCount () const
float GetChromAberrIntensity () const
float GetChromAberrOffset () const
float GetDepthBlurAmount () const
float GetDepthBlurRadius () const
float GetDepthOfFieldMinFstop () const
float GetExposureCalibrationConstant () const
float GetExposureCompensation () const
float GetExposureMaxBrightness () const
EAutoExposureMethod GetExposureMethod () const
float GetExposureMinBrightness () const
float GetExposureSpeedDown () const
float GetExposureSpeedUp () const
float GetFilmBlackClip () const
float GetFilmShoulder () const
float GetFilmSlope () const
float GetFilmToe () const
float GetFilmWhiteClip () const
float GetFocalDistance () const
float GetFOVAngle () const
uint32 GetImageHeight () const
uint32 GetImageWidth () const
float GetISO () const
float GetMotionBlurIntensity () const
float GetMotionBlurMaxDistortion () const
float GetMotionBlurMinObjectScreenSize () const
float GetShutterSpeed () const
float GetTargetGamma () const
float GetWhiteTemp () const
float GetWhiteTint () const
bool ReadPixels (TArray< FColor > &BitMap) const
Use for debugging purposes only.
void SaveCaptureToDisk (const FString &FilePath) const
Use for debugging purposes only.
void SetAperture (float Aperture)
void SetBladeCount (int Count)
void SetChromAberrIntensity (float Intensity)
void SetChromAberrOffset (float Offset)
void SetDepthBlurAmount (float Amount)
void SetDepthBlurRadius (float Radius)
void SetDepthOfFieldMinFstop (float MinFstop)
void SetExposureCalibrationConstant (float Constant)
void SetExposureCompensation (float Compensation)
void SetExposureMaxBrightness (float Brightness)
void SetExposureMethod (EAutoExposureMethod Method)
void SetExposureMinBrightness (float Brightness)
void SetExposureSpeedDown (float Speed)
void SetExposureSpeedUp (float Speed)
void SetFilmBlackClip (float BlackClip)
void SetFilmShoulder (float Shoulder)
void SetFilmSlope (float Slope)
void SetFilmToe (float Toe)
void SetFilmWhiteClip (float WhiteClip)
void SetFocalDistance (float Distance)
void SetFOVAngle (float FOVAngle)
void SetImageSize (uint32 Width, uint32 Height)
void SetISO (float ISO)
void SetMotionBlurIntensity (float Intensity)
void SetMotionBlurMaxDistortion (float MaxDistortion)
void SetMotionBlurMinObjectScreenSize (float ScreenSize)
void SetShutterSpeed (float Speed)
void SetTargetGamma (float InTargetGamma)
void SetWhiteTemp (float Temp)
void SetWhiteTint (float Tint)
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
Static Public Member Functions
static FActorDefinition GetSensorDefinition ()
Protected Member Functions
void Tick (float DeltaTime) override
Protected Member Functions inherited from AShaderBasedSensor
void SetUpSceneCaptureComponent (USceneCaptureComponent2D &SceneCapture) override
Protected Member Functions inherited from ASceneCaptureSensor
virtual void BeginPlay () override
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason) override
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
const UCarlaEpisode & GetEpisode () const
void PostActorCreated () override
Additional Inherited Members
Protected Attributes inherited from ASensor
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Detailed Description
A sensor that captures images from the scene.
Definition at line 17 of file SceneCaptureCamera.h.
Constructor & Destructor Documentation
ASceneCaptureCamera::ASceneCaptureCamera (const FObjectInitializer & ObjectInitializer)
Definition at line 18 of file SceneCaptureCamera.cpp.
References AShaderBasedSensor::AddPostProcessingMaterial().
Member Function Documentation
FActorDefinition ASceneCaptureCamera::GetSensorDefinition () static
Definition at line 10 of file SceneCaptureCamera.cpp.
References UActorBlueprintFunctionLibrary::MakeCameraDefinition().
void ASceneCaptureCamera::Tick (float DeltaTime) override protected virtual
Reimplemented from ASceneCaptureSensor.
Definition at line 25 of file SceneCaptureCamera.cpp.
References FPixelReader::SendPixelsInRenderThread().
The documentation for this class was generated from the following files:
SceneCaptureCamera.h
SceneCaptureCamera.cpp