CARLA: carla::traffic_manager::MotionPlanStage Class Reference
carla::traffic_manager::MotionPlanStage Class Reference
#include <MotionPlanStage.h>
Public Member Functions
MotionPlanStage (const std::vector< ActorId > &vehicle_id_list, const SimulationState &simulation_state, const Parameters &parameters, const BufferMap &buffer_map, const TrackTraffic &track_traffic, const std::vector< float > &urban_longitudinal_parameters, const std::vector< float > &highway_longitudinal_parameters, const std::vector< float > &urban_lateral_parameters, const std::vector< float > &highway_lateral_parameters, const LocalizationFrame &localization_frame, const CollisionFrame &collision_frame, const TLFrame &tl_frame, ControlFrame &output_array)
void RemoveActor (const ActorId actor_id)
void Reset ()
void Update (const unsigned long index)
Private Member Functions
std::pair< bool, float > CollisionHandling (const CollisionHazardData &collision_hazard, const bool tl_hazard, const cg::Vector3D ego_velocity, const cg::Vector3D ego_heading, const float max_target_velocity)
bool SafeAfterJunction (const LocalizationData &localization, const bool tl_hazard, const bool collision_emergency_stop)
Private Member Functions inherited from carla::traffic_manager::Stage
Stage ()
Stage (const Stage &)
virtual ~Stage ()
Private Attributes
const BufferMap & buffer_map
const CollisionFrame & collision_frame
const std::vector< float > highway_lateral_parameters
const std::vector< float > highway_longitudinal_parameters
const LocalizationFrame & localization_frame
ControlFrame & output_array
const Parameters & parameters
std::unordered_map< ActorId, StateEntry > pid_state_map
const SimulationState & simulation_state
std::unordered_map< ActorId, TimeInstance > teleportation_instance
const TLFrame & tl_frame
const TrackTraffic & track_traffic
const std::vector< float > urban_lateral_parameters
const std::vector< float > urban_longitudinal_parameters
const std::vector< ActorId > & vehicle_id_list
Detailed Description
Definition at line 17 of file MotionPlanStage.h.
Constructor & Destructor Documentation
carla::traffic_manager::MotionPlanStage::MotionPlanStage (const std::vector< ActorId > & vehicle_id_list, const SimulationState & simulation_state, const Parameters & parameters, const BufferMap & buffer_map, const TrackTraffic & track_traffic, const std::vector< float > & urban_longitudinal_parameters, const std::vector< float > & highway_longitudinal_parameters, const std::vector< float > & urban_lateral_parameters, const std::vector< float > & highway_lateral_parameters, const LocalizationFrame & localization_frame, const CollisionFrame & collision_frame, const TLFrame & tl_frame, ControlFrame & output_array)
Definition at line 16 of file MotionPlanStage.cpp.
Member Function Documentation
std::pair< bool, float > carla::traffic_manager::MotionPlanStage::CollisionHandling (const CollisionHazardData & collision_hazard, const bool tl_hazard, const cg::Vector3D ego_velocity, const cg::Vector3D ego_heading, const float max_target_velocity) private
Definition at line 232 of file MotionPlanStage.cpp.
References carla::traffic_manager::CollisionHazardData::available_distance_margin, carla::traffic_manager::constants::MotionPlan::CRITICAL_BRAKING_MARGIN, carla::geom::Math::Dot(), carla::traffic_manager::constants::MotionPlan::EPSILON_RELATIVE_SPEED, carla::traffic_manager::constants::MotionPlan::FOLLOW_DISTANCE_RATE, carla::traffic_manager::SimulationState::GetVelocity(), carla::traffic_manager::CollisionHazardData::hazard, carla::traffic_manager::CollisionHazardData::hazard_actor_id, carla::traffic_manager::constants::MotionPlan::MIN_FOLLOW_LEAD_DISTANCE, carla::traffic_manager::constants::MotionPlan::RELATIVE_APPROACH_SPEED, and simulation_state.
Referenced by Update().
void carla::traffic_manager::MotionPlanStage::RemoveActor (const ActorId actor_id) virtual
Implements carla::traffic_manager::Stage.
Definition at line 279 of file MotionPlanStage.cpp.
References pid_state_map, and teleportation_instance.
Referenced by carla::traffic_manager::ALSM::RemoveActor().
void carla::traffic_manager::MotionPlanStage::Reset (void) virtual
Implements carla::traffic_manager::Stage.
Definition at line 284 of file MotionPlanStage.cpp.
References pid_state_map, and teleportation_instance.
Referenced by carla::traffic_manager::TrafficManagerLocal::Stop().
bool carla::traffic_manager::MotionPlanStage::SafeAfterJunction (const LocalizationData & localization, const bool tl_hazard, const bool collision_emergency_stop) private
Definition at line 188 of file MotionPlanStage.cpp.
References carla::traffic_manager::constants::SpeedThreshold::AFTER_JUNCTION_MIN_SPEED, carla::geom::Math::DistanceSquared(), carla::traffic_manager::SimulationState::GetLocation(), carla::traffic_manager::TrackTraffic::GetPassingVehicles(), carla::traffic_manager::SimulationState::GetVelocity(), carla::traffic_manager::LocalizationData::is_at_junction_entrance, carla::traffic_manager::LocalizationData::junction_end_point, carla::traffic_manager::constants::MotionPlan::MAX_JUNCTION_BLOCK_DISTANCE, carla::traffic_manager::constants::WaypointSelection::MIN_SAFE_INTERVAL_LENGTH, carla::traffic_manager::LocalizationData::safe_point, simulation_state, SQUARE, carla::geom::Vector3D::SquaredLength(), and track_traffic.
Referenced by Update().
void carla::traffic_manager::MotionPlanStage::Update (const unsigned long index) virtual
Implements carla::traffic_manager::Stage.
Definition at line 44 of file MotionPlanStage.cpp.
References carla::rpc::VehicleControl::brake, buffer_map, collision_frame, CollisionHandling(), carla::traffic_manager::StateEntry::deviation_integral, carla::traffic_manager::DeviationCrossProduct(), carla::traffic_manager::DeviationDotProduct(), carla::geom::Transform::GetForwardVector(), carla::traffic_manager::SimulationState::GetHeading(), carla::traffic_manager::SimulationState::GetLocation(), carla::traffic_manager::SimulationState::GetRotation(), carla::traffic_manager::SimulationState::GetSpeedLimit(), carla::traffic_manager::Parameters::GetSynchronousMode(), carla::traffic_manager::GetTargetWaypoint(), carla::traffic_manager::Parameters::GetVehicleTargetVelocity(), carla::traffic_manager::SimulationState::GetVelocity(), highway_lateral_parameters, highway_longitudinal_parameters, carla::traffic_manager::constants::SpeedThreshold::HIGHWAY_SPEED, carla::traffic_manager::constants::HybridMode::HYBRID_MODE_DT, carla::traffic_manager::SimulationState::IsPhysicsEnabled(), carla::geom::Vector3D::Length(), localization_frame, carla::geom::Transform::location, output_array, parameters, pid_state_map, carla::geom::Transform::rotation, carla::traffic_manager::PID::RunStep(), SafeAfterJunction(), simulation_state, carla::traffic_manager::PID::StateUpdate(), carla::rpc::VehicleControl::steer, carla::traffic_manager::constants::WaypointSelection::TARGET_WAYPOINT_HORIZON_LENGTH, carla::traffic_manager::constants::WaypointSelection::TARGET_WAYPOINT_TIME_HORIZON, teleportation_instance, carla::rpc::VehicleControl::throttle, tl_frame, urban_lateral_parameters, urban_longitudinal_parameters, vehicle_id_list, and carla::traffic_manager::StateEntry::velocity_integral.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run().
Member Data Documentation
const BufferMap& carla::traffic_manager::MotionPlanStage::buffer_map private
Definition at line 22 of file MotionPlanStage.h.
Referenced by Update().
const CollisionFrame& carla::traffic_manager::MotionPlanStage::collision_frame private
Definition at line 30 of file MotionPlanStage.h.
Referenced by Update().
const std::vector<float> carla::traffic_manager::MotionPlanStage::highway_lateral_parameters private
Definition at line 28 of file MotionPlanStage.h.
Referenced by Update().
const std::vector<float> carla::traffic_manager::MotionPlanStage::highway_longitudinal_parameters private
Definition at line 26 of file MotionPlanStage.h.
Referenced by Update().
const LocalizationFrame& carla::traffic_manager::MotionPlanStage::localization_frame private
Definition at line 29 of file MotionPlanStage.h.
Referenced by Update().
ControlFrame& carla::traffic_manager::MotionPlanStage::output_array private
Definition at line 37 of file MotionPlanStage.h.
Referenced by Update().
const Parameters& carla::traffic_manager::MotionPlanStage::parameters private
Definition at line 21 of file MotionPlanStage.h.
Referenced by Update().
std::unordered_map<ActorId, StateEntry> carla::traffic_manager::MotionPlanStage::pid_state_map private
Definition at line 33 of file MotionPlanStage.h.
Referenced by RemoveActor(), Reset(), and Update().
const SimulationState& carla::traffic_manager::MotionPlanStage::simulation_state private
Definition at line 20 of file MotionPlanStage.h.
Referenced by CollisionHandling(), SafeAfterJunction(), and Update().
std::unordered_map<ActorId, TimeInstance> carla::traffic_manager::MotionPlanStage::teleportation_instance private
Definition at line 36 of file MotionPlanStage.h.
Referenced by RemoveActor(), Reset(), and Update().
const TLFrame& carla::traffic_manager::MotionPlanStage::tl_frame private
Definition at line 31 of file MotionPlanStage.h.
Referenced by Update().
const TrackTraffic& carla::traffic_manager::MotionPlanStage::track_traffic private
Definition at line 23 of file MotionPlanStage.h.
Referenced by SafeAfterJunction().
const std::vector<float> carla::traffic_manager::MotionPlanStage::urban_lateral_parameters private
Definition at line 27 of file MotionPlanStage.h.
Referenced by Update().
const std::vector<float> carla::traffic_manager::MotionPlanStage::urban_longitudinal_parameters private
Definition at line 25 of file MotionPlanStage.h.
Referenced by Update().
const std::vector<ActorId>& carla::traffic_manager::MotionPlanStage::vehicle_id_list private
Definition at line 19 of file MotionPlanStage.h.
Referenced by Update().
The documentation for this class was generated from the following files:
MotionPlanStage.h
MotionPlanStage.cpp