CARLA: nav_msgs::msg::OdometryPubSubType Class Reference
nav_msgs::msg::OdometryPubSubType Class Reference
This class represents the TopicDataType of the type Odometry defined by the user in the IDL file.
#include <OdometryPubSubTypes.h>
Public Types
typedef Odometry type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport OdometryPubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~OdometryPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type Odometry defined by the user in the IDL file.
Definition at line 47 of file OdometryPubSubTypes.h.
Member Typedef Documentation
type
typedef Odometry nav_msgs::msg::OdometryPubSubType::type
Definition at line 51 of file OdometryPubSubTypes.h.
Constructor & Destructor Documentation
OdometryPubSubType()
nav_msgs::msg::OdometryPubSubType::OdometryPubSubType ()
Definition at line 32 of file OdometryPubSubTypes.cpp.
References nav_msgs::msg::Odometry::getKeyMaxCdrSerializedSize(), nav_msgs::msg::Odometry::getMaxCdrSerializedSize(), nav_msgs::msg::Odometry::isKeyDefined(), and m_keyBuffer.
~OdometryPubSubType()
nav_msgs::msg::OdometryPubSubType::~OdometryPubSubType () override virtual
Definition at line 45 of file OdometryPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * nav_msgs::msg::OdometryPubSubType::createData () override virtual
Definition at line 122 of file OdometryPubSubTypes.cpp.
deleteData()
void nav_msgs::msg::OdometryPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file OdometryPubSubTypes.cpp.
deserialize()
bool nav_msgs::msg::OdometryPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file OdometryPubSubTypes.cpp.
References nav_msgs::msg::Odometry::deserialize().
getKey()
bool nav_msgs::msg::OdometryPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file OdometryPubSubTypes.cpp.
References nav_msgs::msg::Odometry::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and nav_msgs::msg::Odometry::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> nav_msgs::msg::OdometryPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file OdometryPubSubTypes.cpp.
References nav_msgs::msg::Odometry::getCdrSerializedSize().
serialize()
bool nav_msgs::msg::OdometryPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file OdometryPubSubTypes.cpp.
References nav_msgs::msg::Odometry::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* nav_msgs::msg::OdometryPubSubType::m_keyBuffer
Definition at line 104 of file OdometryPubSubTypes.h.
Referenced by getKey(), OdometryPubSubType(), and ~OdometryPubSubType().
m_md5
MD5 nav_msgs::msg::OdometryPubSubType::m_md5
Definition at line 103 of file OdometryPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
OdometryPubSubTypes.h
OdometryPubSubTypes.cpp