CARLA: carla_msgs::msg::CarlaCollisionEvent Class Reference
carla_msgs::msg::CarlaCollisionEvent Class Reference
This class represents the structure CarlaCollisionEvent defined by the user in the IDL file.
#include <CarlaCollisionEvent.h>
Public Member Functions
eProsima_user_DllExport CarlaCollisionEvent ()
Default constructor.
eProsima_user_DllExport CarlaCollisionEvent (CarlaCollisionEvent &&x) noexcept
Move constructor.
eProsima_user_DllExport CarlaCollisionEvent (const CarlaCollisionEvent &x)
Copy constructor.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport std_msgs::msg::Header & header ()
This function returns a reference to member header.
const eProsima_user_DllExport std_msgs::msg::Header & header () const
This function returns a constant reference to member header.
eProsima_user_DllExport void header (const std_msgs::msg::Header &_header)
This function copies the value in member header.
eProsima_user_DllExport void header (std_msgs::msg::Header &&_header)
This function moves the value in member header.
eProsima_user_DllExport geometry_msgs::msg::Vector3 & normal_impulse ()
This function returns a reference to member normal_impulse.
const eProsima_user_DllExport geometry_msgs::msg::Vector3 & normal_impulse () const
This function returns a constant reference to member normal_impulse.
eProsima_user_DllExport void normal_impulse (const geometry_msgs::msg::Vector3 &_normal_impulse)
This function copies the value in member normal_impulse.
eProsima_user_DllExport void normal_impulse (geometry_msgs::msg::Vector3 &&_normal_impulse)
This function moves the value in member normal_impulse.
eProsima_user_DllExport bool operator!= (const CarlaCollisionEvent &x) const
Comparison operator.
eProsima_user_DllExport CarlaCollisionEvent & operator= (CarlaCollisionEvent &&x) noexcept
Move assignment.
eProsima_user_DllExport CarlaCollisionEvent & operator= (const CarlaCollisionEvent &x)
Copy assignment.
eProsima_user_DllExport bool operator== (const CarlaCollisionEvent &x) const
Comparison operator.
eProsima_user_DllExport uint32_t & other_actor_id ()
This function returns a reference to member other_actor_id.
eProsima_user_DllExport uint32_t other_actor_id () const
This function returns the value of member other_actor_id.
eProsima_user_DllExport void other_actor_id (uint32_t _other_actor_id)
This function sets a value in member other_actor_id.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport ~CarlaCollisionEvent ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const carla_msgs::msg::CarlaCollisionEvent &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
std_msgs::msg::Header m_header
geometry_msgs::msg::Vector3 m_normal_impulse
uint32_t m_other_actor_id
Detailed Description
This class represents the structure CarlaCollisionEvent defined by the user in the IDL file.
Definition at line 74 of file CarlaCollisionEvent.h.
Constructor & Destructor Documentation
CarlaCollisionEvent() [1/3]
carla_msgs::msg::CarlaCollisionEvent::CarlaCollisionEvent ()
Default constructor.
Definition at line 46 of file CarlaCollisionEvent.cpp.
~CarlaCollisionEvent()
carla_msgs::msg::CarlaCollisionEvent::~CarlaCollisionEvent ()
Default destructor.
Definition at line 54 of file CarlaCollisionEvent.cpp.
CarlaCollisionEvent() [2/3]
carla_msgs::msg::CarlaCollisionEvent::CarlaCollisionEvent (const CarlaCollisionEvent & x)
Copy constructor.
Parameters
x Reference to the object carla_msgs::msg::CarlaCollisionEvent that will be copied.
Definition at line 58 of file CarlaCollisionEvent.cpp.
References m_header, m_normal_impulse, and m_other_actor_id.
CarlaCollisionEvent() [3/3]
carla_msgs::msg::CarlaCollisionEvent::CarlaCollisionEvent (CarlaCollisionEvent && x) noexcept
Move constructor.
Parameters
x Reference to the object carla_msgs::msg::CarlaCollisionEvent that will be copied.
Definition at line 66 of file CarlaCollisionEvent.cpp.
Member Function Documentation
deserialize()
void carla_msgs::msg::CarlaCollisionEvent::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 133 of file CarlaCollisionEvent.cpp.
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::deserialize().
getCdrSerializedSize()
size_t carla_msgs::msg::CarlaCollisionEvent::getCdrSerializedSize (const carla_msgs::msg::CarlaCollisionEvent & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 113 of file CarlaCollisionEvent.cpp.
References std_msgs::msg::Header::getCdrSerializedSize(), geometry_msgs::msg::Vector3::getCdrSerializedSize(), header(), and normal_impulse().
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t carla_msgs::msg::CarlaCollisionEvent::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 245 of file CarlaCollisionEvent.cpp.
References carla_msgs_msg_CarlaCollisionEvent_max_key_cdr_typesize.
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::CarlaCollisionEventPubSubType(), and carla_msgs::msg::CarlaCollisionEventPubSubType::getKey().
getMaxCdrSerializedSize()
size_t carla_msgs::msg::CarlaCollisionEvent::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 106 of file CarlaCollisionEvent.cpp.
References carla_msgs_msg_CarlaCollisionEvent_max_cdr_typesize.
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::CarlaCollisionEventPubSubType().
header() [1/4]
eProsima_user_DllExport std_msgs::msg::Header& carla_msgs::msg::CarlaCollisionEvent::header ()
This function returns a reference to member header.
Returns
Reference to member header
header() [2/4]
std_msgs::msg::Header & carla_msgs::msg::CarlaCollisionEvent::header () const
This function returns a constant reference to member header.
This function returns a reference to member header.
Returns
Constant reference to member header
Reference to member header
Definition at line 165 of file CarlaCollisionEvent.cpp.
header() [3/4]
void carla_msgs::msg::CarlaCollisionEvent::header (const std_msgs::msg::Header & _header)
This function copies the value in member header.
Parameters
_header New value to be copied in member header
Definition at line 145 of file CarlaCollisionEvent.cpp.
Referenced by getCdrSerializedSize().
header() [4/4]
void carla_msgs::msg::CarlaCollisionEvent::header (std_msgs::msg::Header && _header)
This function moves the value in member header.
Parameters
_header New value to be moved in member header
Definition at line 155 of file CarlaCollisionEvent.cpp.
isKeyDefined()
bool carla_msgs::msg::CarlaCollisionEvent::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 252 of file CarlaCollisionEvent.cpp.
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::CarlaCollisionEventPubSubType().
normal_impulse() [1/4]
eProsima_user_DllExport geometry_msgs::msg::Vector3& carla_msgs::msg::CarlaCollisionEvent::normal_impulse ()
This function returns a reference to member normal_impulse.
Returns
Reference to member normal_impulse
normal_impulse() [2/4]
geometry_msgs::msg::Vector3 & carla_msgs::msg::CarlaCollisionEvent::normal_impulse () const
This function returns a constant reference to member normal_impulse.
This function returns a reference to member normal_impulse.
Returns
Constant reference to member normal_impulse
Reference to member normal_impulse
Definition at line 231 of file CarlaCollisionEvent.cpp.
normal_impulse() [3/4]
void carla_msgs::msg::CarlaCollisionEvent::normal_impulse (const geometry_msgs::msg::Vector3 & _normal_impulse)
This function copies the value in member normal_impulse.
Parameters
_normal_impulse New value to be copied in member normal_impulse
Definition at line 211 of file CarlaCollisionEvent.cpp.
Referenced by getCdrSerializedSize().
normal_impulse() [4/4]
void carla_msgs::msg::CarlaCollisionEvent::normal_impulse (geometry_msgs::msg::Vector3 && _normal_impulse)
This function moves the value in member normal_impulse.
Parameters
_normal_impulse New value to be moved in member normal_impulse
Definition at line 221 of file CarlaCollisionEvent.cpp.
operator!=()
bool carla_msgs::msg::CarlaCollisionEvent::operator!= (const CarlaCollisionEvent & x) const
Comparison operator.
Parameters
x carla_msgs::msg::CarlaCollisionEvent object to compare.
Definition at line 100 of file CarlaCollisionEvent.cpp.
operator=() [1/2]
carla_msgs::msg::CarlaCollisionEvent & carla_msgs::msg::CarlaCollisionEvent::operator= (CarlaCollisionEvent && x) noexcept
Move assignment.
Parameters
x Reference to the object carla_msgs::msg::CarlaCollisionEvent that will be copied.
Definition at line 84 of file CarlaCollisionEvent.cpp.
operator=() [2/2]
carla_msgs::msg::CarlaCollisionEvent & carla_msgs::msg::CarlaCollisionEvent::operator= (const CarlaCollisionEvent & x)
Copy assignment.
Parameters
x Reference to the object carla_msgs::msg::CarlaCollisionEvent that will be copied.
Definition at line 74 of file CarlaCollisionEvent.cpp.
References m_header, m_normal_impulse, and m_other_actor_id.
operator==()
bool carla_msgs::msg::CarlaCollisionEvent::operator== (const CarlaCollisionEvent & x) const
Comparison operator.
Parameters
x carla_msgs::msg::CarlaCollisionEvent object to compare.
Definition at line 94 of file CarlaCollisionEvent.cpp.
References m_header, m_normal_impulse, and m_other_actor_id.
other_actor_id() [1/3]
eProsima_user_DllExport uint32_t& carla_msgs::msg::CarlaCollisionEvent::other_actor_id ()
This function returns a reference to member other_actor_id.
Returns
Reference to member other_actor_id
other_actor_id() [2/3]
uint32_t & carla_msgs::msg::CarlaCollisionEvent::other_actor_id () const
This function returns the value of member other_actor_id.
This function returns a reference to member other_actor_id.
Returns
Value of member other_actor_id
Reference to member other_actor_id
Definition at line 193 of file CarlaCollisionEvent.cpp.
other_actor_id() [3/3]
void carla_msgs::msg::CarlaCollisionEvent::other_actor_id (uint32_t _other_actor_id)
This function sets a value in member other_actor_id.
Parameters
_other_actor_id New value for member other_actor_id
Definition at line 183 of file CarlaCollisionEvent.cpp.
serialize()
void carla_msgs::msg::CarlaCollisionEvent::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 125 of file CarlaCollisionEvent.cpp.
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::serialize().
serializeKey()
void carla_msgs::msg::CarlaCollisionEvent::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 257 of file CarlaCollisionEvent.cpp.
Referenced by carla_msgs::msg::CarlaCollisionEventPubSubType::getKey().
Member Data Documentation
m_header
std_msgs::msg::Header carla_msgs::msg::CarlaCollisionEvent::m_header private
Definition at line 255 of file CarlaCollisionEvent.h.
Referenced by CarlaCollisionEvent(), operator=(), and operator==().
m_normal_impulse
geometry_msgs::msg::Vector3 carla_msgs::msg::CarlaCollisionEvent::m_normal_impulse private
Definition at line 257 of file CarlaCollisionEvent.h.
Referenced by CarlaCollisionEvent(), operator=(), and operator==().
m_other_actor_id
uint32_t carla_msgs::msg::CarlaCollisionEvent::m_other_actor_id private
Definition at line 256 of file CarlaCollisionEvent.h.
Referenced by CarlaCollisionEvent(), operator=(), and operator==().
The documentation for this class was generated from the following files:
CarlaCollisionEvent.h
CarlaCollisionEvent.cpp