CARLA: carla::road::Junction Class Reference
carla::road::Junction Class Reference
#include <Junction.h>
Classes
struct Connection
struct LaneLink
Public Member Functions
carla::geom::BoundingBox GetBoundingBox () const
const std::unordered_set< RoadId > & GetConflictsOfRoad (RoadId road_id) const
Connection * GetConnection (ConId id)
std::unordered_map< ConId, Connection > & GetConnections ()
std::unordered_map< ConId, Connection > GetConnections () const
JuncId GetId () const
Junction (const JuncId id, const std::string name)
bool RoadHasConflicts (RoadId road_id) const
Private Attributes
carla::geom::BoundingBox _bounding_box
std::unordered_map< ConId, Connection > _connections
std::set< ContId > _controllers
JuncId _id
std::string _name
std::unordered_map< RoadId, std::unordered_set< RoadId > > _road_conflicts
friend MapBuilder
Additional Inherited Members
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Detailed Description
Definition at line 23 of file road/Junction.h.
Constructor & Destructor Documentation
carla::road::Junction::Junction (const JuncId id, const std::string name) inline
Definition at line 48 of file road/Junction.h.
Member Function Documentation
carla::geom::BoundingBox carla::road::Junction::GetBoundingBox () const inline
Definition at line 73 of file road/Junction.h.
References _bounding_box.
Referenced by carla::road::Map::ComputeJunctionConflicts(), and carla::client::Junction::Junction().
const std::unordered_set<RoadId>& carla::road::Junction::GetConflictsOfRoad (RoadId road_id) const inline
Definition at line 81 of file road/Junction.h.
References _road_conflicts.
Connection* carla::road::Junction::GetConnection (ConId id) inline
Definition at line 57 of file road/Junction.h.
References _connections.
std::unordered_map<ConId, Connection>& carla::road::Junction::GetConnections () inline
Definition at line 65 of file road/Junction.h.
References _connections.
Referenced by carla::road::Map::GetJunctionWaypoints().
std::unordered_map<ConId, Connection> carla::road::Junction::GetConnections () const inline
Definition at line 69 of file road/Junction.h.
References _connections.
JuncId carla::road::Junction::GetId () const inline
Definition at line 53 of file road/Junction.h.
References _id.
Referenced by carla::client::Junction::Junction().
bool carla::road::Junction::RoadHasConflicts (RoadId road_id) const inline
Definition at line 77 of file road/Junction.h.
References _road_conflicts.
Member Data Documentation
carla::geom::BoundingBox carla::road::Junction::_bounding_box private
Definition at line 100 of file road/Junction.h.
Referenced by GetBoundingBox().
std::unordered_map<ConId, Connection> carla::road::Junction::_connections private
Definition at line 93 of file road/Junction.h.
Referenced by GetConnection(), GetConnections(), and carla::road::MapBuilder::GetJunctionLanes().
std::set<ContId> carla::road::Junction::_controllers private
Definition at line 95 of file road/Junction.h.
JuncId carla::road::Junction::_id private
Definition at line 89 of file road/Junction.h.
Referenced by GetId().
std::string carla::road::Junction::_name private
Definition at line 91 of file road/Junction.h.
std::unordered_map<RoadId, std::unordered_set<RoadId> > carla::road::Junction::_road_conflicts private
Definition at line 98 of file road/Junction.h.
Referenced by GetConflictsOfRoad(), and RoadHasConflicts().
friend carla::road::Junction::MapBuilder private
Definition at line 87 of file road/Junction.h.
The documentation for this class was generated from the following file:
road/Junction.h