CARLA: carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers > Class Template Reference
carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers > Class Template Reference
Serialization of a set of buffers to be sent over a TCP socket as a single message.
#include <Message.h>
Public Member Functions
bool empty () const noexcept
auto GetBufferSequence () const
template<typename... Buffers>
MessageTmpl (Buffer &&buf, Buffers &&...buffers)
auto size () const noexcept
Size in bytes of the message excluding the header.
Static Public Member Functions
static constexpr size_t max_size ()
Private Member Functions
MessageTmpl (size_t)
template<typename... Buffers>
MessageTmpl (size_t size, Buffer &&buffer, Buffers &&...buffers)
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Private Attributes
std::array< boost::asio::const_buffer, MaxNumberOfBuffers+1u > _buffer_views
std::array< Buffer, MaxNumberOfBuffers > _buffers
message_size_type _number_of_buffers = 0u
message_size_type _total_size = 0u
Detailed Description
template<size_t MaxNumberOfBuffers>
class carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >
Serialization of a set of buffers to be sent over a TCP socket as a single message.
Template paramenter MaxNumberOfBuffers imposes a compile-time limit on the maximum number of buffers that can be included in a single message.
Definition at line 33 of file Message.h.
Constructor & Destructor Documentation
template<size_t MaxNumberOfBuffers> carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl (size_t) inline private
Definition at line 44 of file Message.h.
template<size_t MaxNumberOfBuffers> template<typename... Buffers> carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl (size_t size, Buffer && buffer, Buffers &&... buffers) inline private
Definition at line 47 of file Message.h.
References carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_buffer_views, carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_buffers, carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_number_of_buffers, and carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_total_size.
template<size_t MaxNumberOfBuffers> template<typename... Buffers> carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl (Buffer && buf, Buffers &&... buffers) inline
Definition at line 58 of file Message.h.
References carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_buffer_views, carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_total_size, and carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::max_size().
Member Function Documentation
template<size_t MaxNumberOfBuffers> bool carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::empty () const inline noexcept
Definition at line 69 of file Message.h.
References carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::size().
template<size_t MaxNumberOfBuffers> auto carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::GetBufferSequence () const inline
Definition at line 73 of file Message.h.
References carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_buffer_views, carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_number_of_buffers, and carla::MakeListView().
template<size_t MaxNumberOfBuffers> static constexpr size_t carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::max_size () inline static
Definition at line 38 of file Message.h.
Referenced by carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl().
template<size_t MaxNumberOfBuffers> auto carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::size () const inline noexcept
Size in bytes of the message excluding the header.
Definition at line 65 of file Message.h.
References carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_total_size.
Referenced by carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::empty().
Member Data Documentation
template<size_t MaxNumberOfBuffers> std::array<boost::asio::const_buffer, MaxNumberOfBuffers + 1u> carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_buffer_views private
Definition at line 86 of file Message.h.
Referenced by carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::GetBufferSequence(), and carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl().
template<size_t MaxNumberOfBuffers> std::array<Buffer, MaxNumberOfBuffers> carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_buffers private
Definition at line 84 of file Message.h.
Referenced by carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl().
template<size_t MaxNumberOfBuffers> message_size_type carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_number_of_buffers = 0u private
Definition at line 80 of file Message.h.
Referenced by carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::GetBufferSequence(), and carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl().
template<size_t MaxNumberOfBuffers> message_size_type carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::_total_size = 0u private
Definition at line 82 of file Message.h.
Referenced by carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::MessageTmpl(), and carla::streaming::detail::tcp::MessageTmpl< MaxNumberOfBuffers >::size().
The documentation for this class was generated from the following file:
Message.h