CARLA: carla::client Namespace Reference
carla::client Namespace Reference
Namespaces
detail
Classes
class Actor
Represents an actor in the simulation.
class ActorAttribute
An attribute of an ActorBlueprint.
class ActorAttributeValue
class ActorAttributeValueAccess
class ActorBlueprint
Contains all the necessary information for spawning an Actor.
class ActorInitializer
Used to initialize Actor classes.
class ActorList
struct ActorSnapshot
class BadAttributeCast
Exception thrown when the value of an ActorAttribute cannot be cast to the requested type.
class BlueprintLibrary
class Client
class ClientSideSensor
class DebugHelper
class FileTransfer
class InvalidAttributeValue
Exception thrown when the value given to an ActorAttribute cannot be converted to its type.
class Junction
class Landmark
Class containing a reference to RoadInfoSignal.
class LaneInvasionCallback
class LaneInvasionSensor
class Light
class LightManager
struct LightState
class Map
class RssSensor
The RSS Sensor class implementing the carla::client::Sensor interface This class is a proxy to the RssCheck class.
class Sensor
class ServerSideSensor
class TimeoutException
class Timestamp
class TrafficLight
class TrafficSign
class Vehicle
class Walker
class WalkerAIController
class Waypoint
class World
class WorldSnapshot
Typedefs
using Color = sensor::data::Color
using LightGroup = rpc::LightState::LightGroup
using LightId = uint32_t
using Shape = rpc::DebugShape
Enumerations
enum GarbageCollectionPolicy { GarbageCollectionPolicy::Disabled, GarbageCollectionPolicy::Enabled, GarbageCollectionPolicy::Inherit }
Functions
template<>
auto ActorAttributeValueAccess::As< rpc::ActorAttributeType::Bool > () const
template<>
auto ActorAttributeValueAccess::As< rpc::ActorAttributeType::Float > () const
template<>
auto ActorAttributeValueAccess::As< rpc::ActorAttributeType::Int > () const
template<>
auto ActorAttributeValueAccess::As< rpc::ActorAttributeType::RGBColor > () const
template<>
auto ActorAttributeValueAccess::As< rpc::ActorAttributeType::String > () const
template<>
sensor::data::Color ActorAttributeValueAccess::As< sensor::data::Color > () const
template<>
std::string ActorAttributeValueAccess::As< std::string > () const
template<typename T >
static void DrawShape (detail::EpisodeProxy &episode, const T &primitive, rpc::Color color, float life_time, bool persistent_lines)
template<typename Map , typename Container >
static void FillMap (Map &destination, Container &source)
template<typename AttributesT >
static bool GetControlIsSticky (const AttributesT &attributes)
static auto MakeMap (const std::string &opendrive_contents)
template<typename EnumT >
static EnumT operator & (EnumT lhs, EnumT rhs)
template<typename EnumT >
static EnumT operator| (EnumT lhs, EnumT rhs)
static geom::Location Rotate (float yaw, const geom::Location &location)
Typedef Documentation
Color
using carla::client::Color = typedef sensor::data::Color
Definition at line 15 of file client/LightState.h.
LightGroup
typedef rpc::LightState::LightGroup carla::client::LightGroup
Definition at line 16 of file Light.cpp.
LightId
using carla::client::LightId = typedef uint32_t
Definition at line 16 of file client/LightState.h.
Shape
using carla::client::Shape = typedef rpc::DebugShape
Definition at line 15 of file DebugHelper.cpp.
Enumeration Type Documentation
GarbageCollectionPolicy
enum carla::client::GarbageCollectionPolicy strong
Enumerator
Disabled
Enabled
Inherit
Definition at line 12 of file GarbageCollectionPolicy.h.
Function Documentation
ActorAttributeValueAccess::As< rpc::ActorAttributeType::Bool >()
template<> auto carla::client::ActorAttributeValueAccess::As< rpc::ActorAttributeType::Bool > () const inline
Definition at line 105 of file LibCarla/source/carla/client/ActorAttribute.h.
ActorAttributeValueAccess::As< rpc::ActorAttributeType::Float >()
template<> auto carla::client::ActorAttributeValueAccess::As< rpc::ActorAttributeType::Float > () const inline
Definition at line 115 of file LibCarla/source/carla/client/ActorAttribute.h.
ActorAttributeValueAccess::As< rpc::ActorAttributeType::Int >()
template<> auto carla::client::ActorAttributeValueAccess::As< rpc::ActorAttributeType::Int > () const inline
Definition at line 110 of file LibCarla/source/carla/client/ActorAttribute.h.
ActorAttributeValueAccess::As< rpc::ActorAttributeType::RGBColor >()
template<> auto carla::client::ActorAttributeValueAccess::As< rpc::ActorAttributeType::RGBColor > () const inline
Definition at line 125 of file LibCarla/source/carla/client/ActorAttribute.h.
ActorAttributeValueAccess::As< rpc::ActorAttributeType::String >()
template<> auto carla::client::ActorAttributeValueAccess::As< rpc::ActorAttributeType::String > () const inline
Definition at line 120 of file LibCarla/source/carla/client/ActorAttribute.h.
ActorAttributeValueAccess::As< sensor::data::Color >()
template<> sensor::data::Color carla::client::ActorAttributeValueAccess::As< sensor::data::Color > () const
Definition at line 70 of file ActorAttribute.cpp.
References carla::client::ActorAttribute::GetValue(), LIBCARLA_THROW_BAD_VALUE_CAST, LIBCARLA_THROW_INVALID_VALUE, carla::log_error(), RGBColor, and carla::StringUtil::Split().
ActorAttributeValueAccess::As< std::string >()
template<> std::string carla::client::ActorAttributeValueAccess::As< std::string > () const
Definition at line 64 of file ActorAttribute.cpp.
References carla::client::ActorAttribute::GetValue(), LIBCARLA_THROW_BAD_VALUE_CAST, and String.
DrawShape()
template<typename T > static void carla::client::DrawShape (detail::EpisodeProxy & episode, const T & primitive, rpc::Color color, float life_time, bool persistent_lines) static
Definition at line 18 of file DebugHelper.cpp.
References carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::client::DebugHelper::DrawArrow(), carla::client::DebugHelper::DrawBox(), carla::client::DebugHelper::DrawLine(), carla::client::DebugHelper::DrawPoint(), and carla::client::DebugHelper::DrawString().
FillMap()
template<typename Map , typename Container > static void carla::client::FillMap (Map & destination, Container & source) static
Definition at line 18 of file ActorBlueprint.cpp.
Referenced by carla::client::ActorBlueprint::ActorBlueprint().
GetControlIsSticky()
template<typename AttributesT > static bool carla::client::GetControlIsSticky (const AttributesT & attributes) static
Definition at line 25 of file Vehicle.cpp.
MakeMap()
static auto carla::client::MakeMap (const std::string & opendrive_contents) static
Definition at line 21 of file client/Map.cpp.
References carla::opendrive::OpenDriveParser::Load(), and carla::throw_exception().
operator &()
template<typename EnumT > static EnumT carla::client::operator& (EnumT lhs, EnumT rhs) static
Definition at line 163 of file client/Waypoint.cpp.
Referenced by xml_allocator::allocate_memory_oob().
operator|()
template<typename EnumT > static EnumT carla::client::operator| (EnumT lhs, EnumT rhs) static
Definition at line 170 of file client/Waypoint.cpp.
Rotate()
static geom::Location carla::client::Rotate (float yaw, const geom::Location & location) static
Definition at line 26 of file LibCarla/source/carla/client/LaneInvasionSensor.cpp.
References carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::client::LaneInvasionCallback::MakeBounds().