CARLA: UBoundingBoxCalculator Class Reference
UBoundingBoxCalculator Class Reference
#include <BoundingBoxCalculator.h>
Static Public Member Functions
static FBoundingBox CombineBBs (const TArray< FBoundingBox > &BBsToCombine)
static void CombineBBsOfActor (const AActor *Actor, TArray< FBoundingBox > &OutBB, TArray< uint8 > &OutTag, const float DistanceThreshold=0.0f, uint8 TagToCombine=0xFF)
static FBoundingBox GetActorBoundingBox (const AActor *Actor, uint8 InTagQueried=0xFF)
Compute the bounding box of the given Carla actor.
static TArray< FBoundingBox > GetBBsOfActor (const AActor *Actor, uint8 InTagQueried=0xFF)
static void GetBBsOfSkeletalMeshComponents (const TArray< USkeletalMeshComponent *> &SkeletalMeshComps, TArray< FBoundingBox > &OutBB, TArray< uint8 > &OutTag, uint8 InTagQueried=0xFF)
static void GetBBsOfStaticMeshComponents (const TArray< UStaticMeshComponent *> &StaticMeshComps, TArray< FBoundingBox > &OutBB, TArray< uint8 > &OutTag, uint8 InTagQueried=0xFF)
static TArray< FBoundingBox > GetBoundingBoxOfActors (const TArray< AActor *> &Actors, uint8 InTagQueried=0xFF)
static FBoundingBox GetCharacterBoundingBox (const ACharacter *Character, uint8 InTagQueried=0xFF)
static void GetISMBoundingBox (UInstancedStaticMeshComponent *ISMComp, TArray< FBoundingBox > &OutBoundingBox)
static void GetMeshCompsFromActorBoundingBox (const AActor *Actor, const FBoundingBox &InBB, TArray< UStaticMeshComponent *> &OutStaticMeshComps)
static FBoundingBox GetSkeletalMeshBoundingBox (const USkeletalMesh *SkeletalMesh)
static FBoundingBox GetStaticMeshBoundingBox (const UStaticMesh *StaticMesh)
static void GetTrafficLightBoundingBox (const ATrafficLightBase *TrafficLight, TArray< FBoundingBox > &OutBB, TArray< uint8 > &OutTag, uint8 InTagQueried=0xFF)
static FBoundingBox GetVehicleBoundingBox (const ACarlaWheeledVehicle *Vehicle, uint8 InTagQueried=0xFF)
Detailed Description
Definition at line 18 of file BoundingBoxCalculator.h.
Member Function Documentation
CombineBBs()
FBoundingBox UBoundingBoxCalculator::CombineBBs (const TArray< FBoundingBox > & BBsToCombine) static
Definition at line 571 of file BoundingBoxCalculator.cpp.
Referenced by CombineBBsOfActor(), and GetActorBoundingBox().
CombineBBsOfActor()
void UBoundingBoxCalculator::CombineBBsOfActor (const AActor * Actor, TArray< FBoundingBox > & OutBB, TArray< uint8 > & OutTag, const float DistanceThreshold = 0.0f, uint8 TagToCombine = 0xFF) static
Definition at line 503 of file BoundingBoxCalculator.cpp.
References CombineBBs(), GetBBsOfStaticMeshComponents(), FBoundingBox::Origin, and FBoundingBox::Rotation.
Referenced by GetTrafficLightBoundingBox().
GetActorBoundingBox()
FBoundingBox UBoundingBoxCalculator::GetActorBoundingBox (const AActor * Actor, uint8 InTagQueried = 0xFF) static
Compute the bounding box of the given Carla actor.
Warning
If the actor type is not supported a default initialized bounding box is returned.
Traffic signs return its trigger box instead.
Definition at line 38 of file BoundingBoxCalculator.cpp.
References Character, CombineBBs(), GetBBsOfActor(), FBoundingBox::Origin, FBoundingBox::Rotation, TriggerVolume, and Vehicle.
Referenced by FActorRegistry::MakeCarlaActor(), and UCarlaEpisode::SerializeActor().
GetBBsOfActor()
TArray< FBoundingBox > UBoundingBoxCalculator::GetBBsOfActor (const AActor * Actor, uint8 InTagQueried = 0xFF) static
Definition at line 427 of file BoundingBoxCalculator.cpp.
References carla::rpc::Any, BoundingBox, Character, FBoundingBox::Extent, GetBBsOfSkeletalMeshComponents(), GetBBsOfStaticMeshComponents(), GetCharacterBoundingBox(), GetISMBoundingBox(), ATagger::GetTagOfTaggedComponent(), GetTrafficLightBoundingBox(), GetVehicleBoundingBox(), TrafficLight, and Vehicle.
Referenced by GetActorBoundingBox(), and GetBoundingBoxOfActors().
GetBBsOfSkeletalMeshComponents()
void UBoundingBoxCalculator::GetBBsOfSkeletalMeshComponents (const TArray< USkeletalMeshComponent *> & SkeletalMeshComps, TArray< FBoundingBox > & OutBB, TArray< uint8 > & OutTag, uint8 InTagQueried = 0xFF) static
Definition at line 380 of file BoundingBoxCalculator.cpp.
References carla::rpc::Any, ApplyTransformToBB(), BoundingBox, FBoundingBox::Extent, GetSkeletalMeshBoundingBox(), and ATagger::GetTagOfTaggedComponent().
Referenced by GetBBsOfActor(), and UObjectRegister::RegisterSKMComponents().
GetBBsOfStaticMeshComponents()
void UBoundingBoxCalculator::GetBBsOfStaticMeshComponents (const TArray< UStaticMeshComponent *> & StaticMeshComps, TArray< FBoundingBox > & OutBB, TArray< uint8 > & OutTag, uint8 InTagQueried = 0xFF) static
Definition at line 342 of file BoundingBoxCalculator.cpp.
References carla::rpc::Any, ApplyTransformToBB(), BoundingBox, GetStaticMeshBoundingBox(), and ATagger::GetTagOfTaggedComponent().
Referenced by CombineBBsOfActor(), GetBBsOfActor(), GetMeshCompsFromActorBoundingBox(), and UObjectRegister::RegisterSMComponents().
GetBoundingBoxOfActors()
TArray< FBoundingBox > UBoundingBoxCalculator::GetBoundingBoxOfActors (const TArray< AActor *> & Actors, uint8 InTagQueried = 0xFF) static
Definition at line 413 of file BoundingBoxCalculator.cpp.
References GetBBsOfActor().
Referenced by ACarlaGameModeBase::GetAllBBsOfLevel().
GetCharacterBoundingBox()
FBoundingBox UBoundingBoxCalculator::GetCharacterBoundingBox (const ACharacter * Character, uint8 InTagQueried = 0xFF) static
Definition at line 183 of file BoundingBoxCalculator.cpp.
References carla::rpc::Any, ApplyTransformToBB(), BoundingBox, FBoundingBox::Extent, and FBoundingBox::Origin.
Referenced by GetBBsOfActor(), and UObjectRegister::RegisterCharacter().
GetISMBoundingBox()
void UBoundingBoxCalculator::GetISMBoundingBox (UInstancedStaticMeshComponent * ISMComp, TArray< FBoundingBox > & OutBoundingBox) static
Definition at line 309 of file BoundingBoxCalculator.cpp.
References ApplyTransformToBB(), BoundingBox, and GetStaticMeshBoundingBox().
Referenced by GetBBsOfActor(), and UObjectRegister::RegisterISMComponents().
GetMeshCompsFromActorBoundingBox()
void UBoundingBoxCalculator::GetMeshCompsFromActorBoundingBox (const AActor * Actor, const FBoundingBox & InBB, TArray< UStaticMeshComponent *> & OutStaticMeshComps) static
Definition at line 605 of file BoundingBoxCalculator.cpp.
References GetBBsOfStaticMeshComponents(), and FBoundingBox::Origin.
Referenced by UObjectRegister::RegisterTrafficLight().
GetSkeletalMeshBoundingBox()
FBoundingBox UBoundingBoxCalculator::GetSkeletalMeshBoundingBox (const USkeletalMesh * SkeletalMesh) static
Definition at line 250 of file BoundingBoxCalculator.cpp.
Referenced by GetBBsOfSkeletalMeshComponents(), and GetVehicleBoundingBox().
GetStaticMeshBoundingBox()
FBoundingBox UBoundingBoxCalculator::GetStaticMeshBoundingBox (const UStaticMesh * StaticMesh) static
Definition at line 296 of file BoundingBoxCalculator.cpp.
Referenced by GetBBsOfStaticMeshComponents(), and GetISMBoundingBox().
GetTrafficLightBoundingBox()
void UBoundingBoxCalculator::GetTrafficLightBoundingBox (const ATrafficLightBase * TrafficLight, TArray< FBoundingBox > & OutBB, TArray< uint8 > & OutTag, uint8 InTagQueried = 0xFF) static
Definition at line 214 of file BoundingBoxCalculator.cpp.
References carla::rpc::Any, CombineBBsOfActor(), and carla::rpc::TrafficLight.
Referenced by FCarlaServer::FPimpl::BindActions(), GetBBsOfActor(), and UObjectRegister::RegisterTrafficLight().
GetVehicleBoundingBox()
FBoundingBox UBoundingBoxCalculator::GetVehicleBoundingBox (const ACarlaWheeledVehicle * Vehicle, uint8 InTagQueried = 0xFF) static
Definition at line 95 of file BoundingBoxCalculator.cpp.
References carla::rpc::Any, ApplyTransformToBB(), BoundingBox, FBoundingBox::Extent, GetSkeletalMeshBoundingBox(), ATagger::GetTagOfTaggedComponent(), and FBoundingBox::Origin.
Referenced by ACarlaWheeledVehicle::AdjustVehicleBounds(), GetBBsOfActor(), and UObjectRegister::RegisterVehicle().
The documentation for this class was generated from the following files:
BoundingBoxCalculator.h
BoundingBoxCalculator.cpp