CARLA: geometry_msgs::msg::TransformPubSubType Class Reference
geometry_msgs::msg::TransformPubSubType Class Reference
This class represents the TopicDataType of the type Transform defined by the user in the IDL file.
#include <TransformPubSubTypes.h>
Public Types
typedef Transform type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport TransformPubSubType ()
virtual eProsima_user_DllExport ~TransformPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type Transform defined by the user in the IDL file.
Definition at line 76 of file TransformPubSubTypes.h.
Member Typedef Documentation
type
typedef Transform geometry_msgs::msg::TransformPubSubType::type
Definition at line 80 of file TransformPubSubTypes.h.
Constructor & Destructor Documentation
TransformPubSubType()
geometry_msgs::msg::TransformPubSubType::TransformPubSubType ()
Definition at line 32 of file TransformPubSubTypes.cpp.
References geometry_msgs::msg::Transform::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::Transform::getMaxCdrSerializedSize(), geometry_msgs::msg::Transform::isKeyDefined(), and m_keyBuffer.
~TransformPubSubType()
geometry_msgs::msg::TransformPubSubType::~TransformPubSubType () override virtual
Definition at line 45 of file TransformPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::TransformPubSubType::createData () override virtual
Definition at line 122 of file TransformPubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::TransformPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file TransformPubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::TransformPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file TransformPubSubTypes.cpp.
References geometry_msgs::msg::Transform::deserialize().
getKey()
bool geometry_msgs::msg::TransformPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file TransformPubSubTypes.cpp.
References geometry_msgs::msg::Transform::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::Transform::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::TransformPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file TransformPubSubTypes.cpp.
References geometry_msgs::msg::Transform::getCdrSerializedSize().
is_plain_impl()
static constexpr bool geometry_msgs::msg::TransformPubSubType::is_plain_impl () inline static constexpr private
Definition at line 135 of file TransformPubSubTypes.h.
serialize()
bool geometry_msgs::msg::TransformPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file TransformPubSubTypes.cpp.
References geometry_msgs::msg::Transform::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::TransformPubSubType::m_keyBuffer
Definition at line 133 of file TransformPubSubTypes.h.
Referenced by getKey(), TransformPubSubType(), and ~TransformPubSubType().
m_md5
MD5 geometry_msgs::msg::TransformPubSubType::m_md5
Definition at line 132 of file TransformPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
TransformPubSubTypes.h
TransformPubSubTypes.cpp