CARLA: sensor_msgs::msg::NavSatFix Class Reference
sensor_msgs::msg::NavSatFix Class Reference
This class represents the structure NavSatFix defined by the user in the IDL file.
#include <NavSatFix.h>
Public Member Functions
eProsima_user_DllExport double & altitude ()
This function returns a reference to member altitude.
eProsima_user_DllExport double altitude () const
This function returns the value of member altitude.
eProsima_user_DllExport void altitude (double _altitude)
This function sets a value in member altitude.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport std_msgs::msg::Header & header ()
This function returns a reference to member header.
const eProsima_user_DllExport std_msgs::msg::Header & header () const
This function returns a constant reference to member header.
eProsima_user_DllExport void header (const std_msgs::msg::Header &_header)
This function copies the value in member header.
eProsima_user_DllExport void header (std_msgs::msg::Header &&_header)
This function moves the value in member header.
eProsima_user_DllExport double & latitude ()
This function returns a reference to member latitude.
eProsima_user_DllExport double latitude () const
This function returns the value of member latitude.
eProsima_user_DllExport void latitude (double _latitude)
This function sets a value in member latitude.
eProsima_user_DllExport double & longitude ()
This function returns a reference to member longitude.
eProsima_user_DllExport double longitude () const
This function returns the value of member longitude.
eProsima_user_DllExport void longitude (double _longitude)
This function sets a value in member longitude.
eProsima_user_DllExport NavSatFix ()
Default constructor.
eProsima_user_DllExport NavSatFix (const NavSatFix &x)
Copy constructor.
eProsima_user_DllExport NavSatFix (NavSatFix &&x) noexcept
Move constructor.
eProsima_user_DllExport bool operator!= (const NavSatFix &x) const
Comparison operator.
eProsima_user_DllExport NavSatFix & operator= (const NavSatFix &x)
Copy assignment.
eProsima_user_DllExport NavSatFix & operator= (NavSatFix &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const NavSatFix &x) const
Comparison operator.
eProsima_user_DllExport sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 & position_covariance ()
This function returns a reference to member position_covariance.
const eProsima_user_DllExport sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 & position_covariance () const
This function returns a constant reference to member position_covariance.
eProsima_user_DllExport void position_covariance (const sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 &_position_covariance)
This function copies the value in member position_covariance.
eProsima_user_DllExport void position_covariance (sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 &&_position_covariance)
This function moves the value in member position_covariance.
eProsima_user_DllExport uint8_t & position_covariance_type ()
This function returns a reference to member position_covariance_type.
eProsima_user_DllExport uint8_t position_covariance_type () const
This function returns the value of member position_covariance_type.
eProsima_user_DllExport void position_covariance_type (uint8_t _position_covariance_type)
This function sets a value in member position_covariance_type.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport sensor_msgs::msg::NavSatStatus & status ()
This function returns a reference to member status.
const eProsima_user_DllExport sensor_msgs::msg::NavSatStatus & status () const
This function returns a constant reference to member status.
eProsima_user_DllExport void status (const sensor_msgs::msg::NavSatStatus &_status)
This function copies the value in member status.
eProsima_user_DllExport void status (sensor_msgs::msg::NavSatStatus &&_status)
This function moves the value in member status.
eProsima_user_DllExport ~NavSatFix ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const sensor_msgs::msg::NavSatFix &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
double m_altitude
std_msgs::msg::Header m_header
double m_latitude
double m_longitude
sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 m_position_covariance
uint8_t m_position_covariance_type
sensor_msgs::msg::NavSatStatus m_status
Detailed Description
This class represents the structure NavSatFix defined by the user in the IDL file.
Definition at line 78 of file NavSatFix.h.
Constructor & Destructor Documentation
NavSatFix() [1/3]
sensor_msgs::msg::NavSatFix::NavSatFix ()
Default constructor.
Definition at line 47 of file NavSatFix.cpp.
~NavSatFix()
sensor_msgs::msg::NavSatFix::~NavSatFix ()
Default destructor.
Definition at line 65 of file NavSatFix.cpp.
NavSatFix() [2/3]
sensor_msgs::msg::NavSatFix::NavSatFix (const NavSatFix & x)
Copy constructor.
Parameters
x Reference to the object sensor_msgs::msg::NavSatFix that will be copied.
Definition at line 69 of file NavSatFix.cpp.
References m_altitude, m_header, m_latitude, m_longitude, m_position_covariance, m_position_covariance_type, and m_status.
NavSatFix() [3/3]
sensor_msgs::msg::NavSatFix::NavSatFix (NavSatFix && x) noexcept
Move constructor.
Parameters
x Reference to the object sensor_msgs::msg::NavSatFix that will be copied.
Definition at line 81 of file NavSatFix.cpp.
Member Function Documentation
altitude() [1/3]
eProsima_user_DllExport double& sensor_msgs::msg::NavSatFix::altitude ()
This function returns a reference to member altitude.
Returns
Reference to member altitude
altitude() [2/3]
double & sensor_msgs::msg::NavSatFix::altitude () const
This function returns the value of member altitude.
This function returns a reference to member altitude.
Returns
Value of member altitude
Reference to member altitude
Definition at line 326 of file NavSatFix.cpp.
altitude() [3/3]
void sensor_msgs::msg::NavSatFix::altitude (double _altitude)
This function sets a value in member altitude.
Parameters
_altitude New value for member altitude
Definition at line 316 of file NavSatFix.cpp.
deserialize()
void sensor_msgs::msg::NavSatFix::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 168 of file NavSatFix.cpp.
Referenced by sensor_msgs::msg::NavSatFixPubSubType::deserialize().
getCdrSerializedSize()
size_t sensor_msgs::msg::NavSatFix::getCdrSerializedSize (const sensor_msgs::msg::NavSatFix & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 140 of file NavSatFix.cpp.
References sensor_msgs::msg::NavSatStatus::getCdrSerializedSize(), std_msgs::msg::Header::getCdrSerializedSize(), header(), and status().
Referenced by sensor_msgs::msg::NavSatFixPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t sensor_msgs::msg::NavSatFix::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 405 of file NavSatFix.cpp.
References sensor_msgs_msg_NavSatFix_max_key_cdr_typesize.
Referenced by sensor_msgs::msg::NavSatFixPubSubType::getKey(), and sensor_msgs::msg::NavSatFixPubSubType::NavSatFixPubSubType().
getMaxCdrSerializedSize()
size_t sensor_msgs::msg::NavSatFix::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 133 of file NavSatFix.cpp.
References sensor_msgs_msg_NavSatFix_max_cdr_typesize.
Referenced by sensor_msgs::msg::NavSatFixPubSubType::NavSatFixPubSubType().
header() [1/4]
eProsima_user_DllExport std_msgs::msg::Header& sensor_msgs::msg::NavSatFix::header ()
This function returns a reference to member header.
Returns
Reference to member header
header() [2/4]
std_msgs::msg::Header & sensor_msgs::msg::NavSatFix::header () const
This function returns a constant reference to member header.
This function returns a reference to member header.
Returns
Constant reference to member header
Reference to member header
Definition at line 204 of file NavSatFix.cpp.
header() [3/4]
void sensor_msgs::msg::NavSatFix::header (const std_msgs::msg::Header & _header)
This function copies the value in member header.
Parameters
_header New value to be copied in member header
Definition at line 184 of file NavSatFix.cpp.
Referenced by getCdrSerializedSize().
header() [4/4]
void sensor_msgs::msg::NavSatFix::header (std_msgs::msg::Header && _header)
This function moves the value in member header.
Parameters
_header New value to be moved in member header
Definition at line 194 of file NavSatFix.cpp.
isKeyDefined()
bool sensor_msgs::msg::NavSatFix::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 412 of file NavSatFix.cpp.
Referenced by sensor_msgs::msg::NavSatFixPubSubType::NavSatFixPubSubType().
latitude() [1/3]
eProsima_user_DllExport double& sensor_msgs::msg::NavSatFix::latitude ()
This function returns a reference to member latitude.
Returns
Reference to member latitude
latitude() [2/3]
double & sensor_msgs::msg::NavSatFix::latitude () const
This function returns the value of member latitude.
This function returns a reference to member latitude.
Returns
Value of member latitude
Reference to member latitude
Definition at line 270 of file NavSatFix.cpp.
latitude() [3/3]
void sensor_msgs::msg::NavSatFix::latitude (double _latitude)
This function sets a value in member latitude.
Parameters
_latitude New value for member latitude
Definition at line 260 of file NavSatFix.cpp.
longitude() [1/3]
eProsima_user_DllExport double& sensor_msgs::msg::NavSatFix::longitude ()
This function returns a reference to member longitude.
Returns
Reference to member longitude
longitude() [2/3]
double & sensor_msgs::msg::NavSatFix::longitude () const
This function returns the value of member longitude.
This function returns a reference to member longitude.
Returns
Value of member longitude
Reference to member longitude
Definition at line 298 of file NavSatFix.cpp.
longitude() [3/3]
void sensor_msgs::msg::NavSatFix::longitude (double _longitude)
This function sets a value in member longitude.
Parameters
_longitude New value for member longitude
Definition at line 288 of file NavSatFix.cpp.
operator!=()
bool sensor_msgs::msg::NavSatFix::operator!= (const NavSatFix & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::NavSatFix object to compare.
Definition at line 127 of file NavSatFix.cpp.
operator=() [1/2]
sensor_msgs::msg::NavSatFix & sensor_msgs::msg::NavSatFix::operator= (const NavSatFix & x)
Copy assignment.
Parameters
x Reference to the object sensor_msgs::msg::NavSatFix that will be copied.
Definition at line 93 of file NavSatFix.cpp.
References m_altitude, m_header, m_latitude, m_longitude, m_position_covariance, m_position_covariance_type, and m_status.
operator=() [2/2]
sensor_msgs::msg::NavSatFix & sensor_msgs::msg::NavSatFix::operator= (NavSatFix && x) noexcept
Move assignment.
Parameters
x Reference to the object sensor_msgs::msg::NavSatFix that will be copied.
Definition at line 107 of file NavSatFix.cpp.
operator==()
bool sensor_msgs::msg::NavSatFix::operator== (const NavSatFix & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::NavSatFix object to compare.
Definition at line 121 of file NavSatFix.cpp.
References m_altitude, m_header, m_latitude, m_longitude, m_position_covariance, m_position_covariance_type, and m_status.
position_covariance() [1/4]
eProsima_user_DllExport sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9& sensor_msgs::msg::NavSatFix::position_covariance ()
This function returns a reference to member position_covariance.
Returns
Reference to member position_covariance
position_covariance() [2/4]
sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 & sensor_msgs::msg::NavSatFix::position_covariance () const
This function returns a constant reference to member position_covariance.
This function returns a reference to member position_covariance.
Returns
Constant reference to member position_covariance
Reference to member position_covariance
Definition at line 364 of file NavSatFix.cpp.
position_covariance() [3/4]
void sensor_msgs::msg::NavSatFix::position_covariance (const sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 & _position_covariance)
This function copies the value in member position_covariance.
Parameters
_position_covariance New value to be copied in member position_covariance
Definition at line 344 of file NavSatFix.cpp.
position_covariance() [4/4]
void sensor_msgs::msg::NavSatFix::position_covariance (sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 && _position_covariance)
This function moves the value in member position_covariance.
Parameters
_position_covariance New value to be moved in member position_covariance
Definition at line 354 of file NavSatFix.cpp.
position_covariance_type() [1/3]
eProsima_user_DllExport uint8_t& sensor_msgs::msg::NavSatFix::position_covariance_type ()
This function returns a reference to member position_covariance_type.
Returns
Reference to member position_covariance_type
position_covariance_type() [2/3]
uint8_t & sensor_msgs::msg::NavSatFix::position_covariance_type () const
This function returns the value of member position_covariance_type.
This function returns a reference to member position_covariance_type.
Returns
Value of member position_covariance_type
Reference to member position_covariance_type
Definition at line 391 of file NavSatFix.cpp.
position_covariance_type() [3/3]
void sensor_msgs::msg::NavSatFix::position_covariance_type (uint8_t _position_covariance_type)
This function sets a value in member position_covariance_type.
Parameters
_position_covariance_type New value for member position_covariance_type
Definition at line 381 of file NavSatFix.cpp.
serialize()
void sensor_msgs::msg::NavSatFix::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 156 of file NavSatFix.cpp.
Referenced by sensor_msgs::msg::NavSatFixPubSubType::serialize().
serializeKey()
void sensor_msgs::msg::NavSatFix::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 417 of file NavSatFix.cpp.
Referenced by sensor_msgs::msg::NavSatFixPubSubType::getKey().
status() [1/4]
eProsima_user_DllExport sensor_msgs::msg::NavSatStatus& sensor_msgs::msg::NavSatFix::status ()
This function returns a reference to member status.
Returns
Reference to member status
status() [2/4]
sensor_msgs::msg::NavSatStatus & sensor_msgs::msg::NavSatFix::status () const
This function returns a constant reference to member status.
This function returns a reference to member status.
Returns
Constant reference to member status
Reference to member status
Definition at line 242 of file NavSatFix.cpp.
status() [3/4]
void sensor_msgs::msg::NavSatFix::status (const sensor_msgs::msg::NavSatStatus & _status)
This function copies the value in member status.
Parameters
_status New value to be copied in member status
Definition at line 222 of file NavSatFix.cpp.
Referenced by getCdrSerializedSize().
status() [4/4]
void sensor_msgs::msg::NavSatFix::status (sensor_msgs::msg::NavSatStatus && _status)
This function moves the value in member status.
Parameters
_status New value to be moved in member status
Definition at line 232 of file NavSatFix.cpp.
Member Data Documentation
m_altitude
double sensor_msgs::msg::NavSatFix::m_altitude private
Definition at line 344 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
m_header
std_msgs::msg::Header sensor_msgs::msg::NavSatFix::m_header private
Definition at line 340 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
m_latitude
double sensor_msgs::msg::NavSatFix::m_latitude private
Definition at line 342 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
m_longitude
double sensor_msgs::msg::NavSatFix::m_longitude private
Definition at line 343 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
m_position_covariance
sensor_msgs::msg::sensor_msgs__NavSatFix__double_array_9 sensor_msgs::msg::NavSatFix::m_position_covariance private
Definition at line 345 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
m_position_covariance_type
uint8_t sensor_msgs::msg::NavSatFix::m_position_covariance_type private
Definition at line 346 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
m_status
sensor_msgs::msg::NavSatStatus sensor_msgs::msg::NavSatFix::m_status private
Definition at line 341 of file NavSatFix.h.
Referenced by NavSatFix(), operator=(), and operator==().
The documentation for this class was generated from the following files:
NavSatFix.h
NavSatFix.cpp