CARLA: CarlaRecorderCollisions Class Reference
CarlaRecorderCollisions Class Reference
#include <CarlaRecorderCollision.h>
Public Member Functions
void Add (const CarlaRecorderCollision &Collision)
void Clear (void)
void Write (std::ofstream &OutFile)
Private Attributes
std::unordered_set< CarlaRecorderCollision > Collisions
Detailed Description
Definition at line 45 of file CarlaRecorderCollision.h.
Member Function Documentation
void CarlaRecorderCollisions::Add (const CarlaRecorderCollision & Collision)
Definition at line 45 of file CarlaRecorderCollision.cpp.
Referenced by ACarlaRecorder::AddCollision().
void CarlaRecorderCollisions::Clear (void)
Definition at line 40 of file CarlaRecorderCollision.cpp.
Referenced by ACarlaRecorder::Clear().
void CarlaRecorderCollisions::Write (std::ofstream & OutFile)
Definition at line 50 of file CarlaRecorderCollision.cpp.
References Collision.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
std::unordered_set<CarlaRecorderCollision> CarlaRecorderCollisions::Collisions private
Definition at line 53 of file CarlaRecorderCollision.h.
The documentation for this class was generated from the following files:
CarlaRecorderCollision.h
CarlaRecorderCollision.cpp