CARLA: FCarlaModule Class Reference
FCarlaModule Class Reference
#include <Carla.h>
Public Member Functions
virtual void ShutdownModule () override
virtual void StartupModule () override
IModuleInterface implementation.
Private Member Functions
bool HandleSettingsSaved ()
void RegisterSettings ()
void UnregisterSettings ()
Detailed Description
Definition at line 36 of file Carla.h.
Member Function Documentation
HandleSettingsSaved()
bool FCarlaModule::HandleSettingsSaved () private
Definition at line 69 of file Carla.cpp.
Referenced by RegisterSettings().
RegisterSettings()
void FCarlaModule::RegisterSettings () private
Definition at line 27 of file Carla.cpp.
References HandleSettingsSaved().
Referenced by StartupModule().
ShutdownModule()
void FCarlaModule::ShutdownModule () override virtual
Definition at line 19 of file Carla.cpp.
References UnregisterSettings().
StartupModule()
void FCarlaModule::StartupModule () override virtual
IModuleInterface implementation.
Definition at line 14 of file Carla.cpp.
References RegisterSettings().
UnregisterSettings()
void FCarlaModule::UnregisterSettings () private
Definition at line 58 of file Carla.cpp.
Referenced by ShutdownModule().
The documentation for this class was generated from the following files:
Carla.h
Carla.cpp