CARLA: carla::road::InformationSet Class Reference
carla::road::InformationSet Class Reference
#include <InformationSet.h>
Public Member Functions
template<typename T >
const T * GetInfo (const double s) const
Returns single info given a type and a distance (s) from the start of the road.
template<typename T >
std::vector< const T * > GetInfos () const
Return all infos given a type from the start of the road.
template<typename T >
std::vector< const T * > GetInfos (const double min_s, const double max_s) const
Return all infos given a type in a given range of the road.
InformationSet ()=default
InformationSet (std::vector< std::unique_ptr< element::RoadInfo >> &&vec)
Private Attributes
RoadElementSet< std::unique_ptr< element::RoadInfo > > _road_set
Additional Inherited Members
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Detailed Description
Definition at line 20 of file InformationSet.h.
Constructor & Destructor Documentation
InformationSet() [1/2]
carla::road::InformationSet::InformationSet () default
InformationSet() [2/2]
carla::road::InformationSet::InformationSet (std::vector< std::unique_ptr< element::RoadInfo >> && vec) inline
Definition at line 25 of file InformationSet.h.
Member Function Documentation
GetInfo()
template<typename T > const T* carla::road::InformationSet::GetInfo (const double s) const inline
Returns single info given a type and a distance (s) from the start of the road.
Definition at line 42 of file InformationSet.h.
References _road_set.
Referenced by carla::road::Road::GetDirectedPointIn(), carla::road::Road::GetDirectedPointInNoLaneOffset(), carla::road::Lane::GetInfo(), and carla::road::Road::GetInfo().
GetInfos() [1/2]
template<typename T > std::vector<const T *> carla::road::InformationSet::GetInfos () const inline
Return all infos given a type from the start of the road.
Definition at line 30 of file InformationSet.h.
References _road_set.
Referenced by carla::road::Lane::GetInfos(), carla::road::Road::GetInfos(), carla::road::Road::GetInfosInRange(), and carla::road::Road::GetNearestPoint().
GetInfos() [2/2]
template<typename T > std::vector<const T *> carla::road::InformationSet::GetInfos (const double min_s, const double max_s) const inline
Return all infos given a type in a given range of the road.
Definition at line 49 of file InformationSet.h.
References _road_set.
Member Data Documentation
_road_set
RoadElementSet<std::unique_ptr<element::RoadInfo> > carla::road::InformationSet::_road_set private
Definition at line 69 of file InformationSet.h.
Referenced by GetInfo(), and GetInfos().
The documentation for this class was generated from the following file:
InformationSet.h