CARLA: carla::traffic_manager::CollisionStage Class Reference
carla::traffic_manager::CollisionStage Class Reference
This class is the thread executable for the collision detection stage and is responsible for checking possible collisions with other cars along the vehicle's trajectory.
#include <CollisionStage.h>
Public Member Functions
void Action () override
Implement this method with logic to process data inside the stage.
CollisionStage (std::string stage_name, std::shared_ptr< LocalizationToCollisionMessenger > localization_messenger, std::shared_ptr< CollisionToPlannerMessenger > planner_messenger, Parameters &parameters, cc::DebugHelper &debug_helper)
void DataReceiver () override
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
void DataSender () override
Implement this method with logic to gather results from the action threads and send to next stage(s).
~CollisionStage ()
Public Member Functions inherited from carla::traffic_manager::PipelineStage
PipelineStage (const std::string &stage_name)
void Start ()
void Stop ()
virtual ~PipelineStage ()
Private Member Functions
void DrawBoundary (const LocationList &boundary)
A simple method used to draw bounding boxes around vehicles.
LocationList GetBoundary (const Actor &actor, const cg::Location &location, const cg::Vector3D velocity)
Returns the bounding box corners of the vehicle passed to the method.
float GetBoundingBoxExtention (const ActorId actor_id, const cg::Vector3D velocity_vector, const cg::Vector3D heading_vector)
Method to calculate the speed dependent bounding box extention for a vehicle.
LocationList GetGeodesicBoundary (const Actor &actor, const cg::Location &location, const cg::Vector3D velocity)
Returns the extrapolated bounding box of the vehicle along its trajectory.
GeometryComparisonCache GetGeometryBetweenActors (const Actor &reference_vehicle, const Actor &other_vehicle, const cg::Location &reference_location, const cg::Location &other_location, const cg::Vector3D reference_velocity, const cg::Vector3D other_velocity)
Method to compute Geometry result between two vehicles.
Polygon GetPolygon (const LocationList &boundary)
Method to construct a boost polygon object.
bool IsLocationAfterJunctionSafe (const Actor &ego_actor, const Actor &overlapped_actor, const SimpleWaypointPtr safe_point, const cg::Location &other_location, const cg::Vector3D other_velocity)
At intersections, used to see if there is space after the junction.
std::pair< bool, float > NegotiateCollision (const Actor &ego_vehicle, const Actor &other_vehicle, const cg::Location &reference_location, const cg::Location &other_location, const SimpleWaypointPtr &closest_point, const SimpleWaypointPtr &junction_look_ahead, const cg::Vector3D reference_velocity, const cg::Vector3D other_velocity)
The method returns true if ego_vehicle should stop and wait for other_vehicle to pass.
Private Attributes
std::unordered_map< ActorId, CollisionLock > collision_locks
Structure to keep track of collision locking.
cc::DebugHelper & debug_helper
Reference to Carla's debug helper object.
bool frame_selector
Selection key for switching between output frames.
std::unordered_map< ActorId, LocationList > geodesic_boundaries
Structure to hold the geodesic boundaries during one iteration.
chr::time_point< chr::system_clock, chr::nanoseconds > last_world_actors_pass_instance
An object used to keep track of time between checking for all world actors.
std::shared_ptr< LocalizationToCollisionFrame > localization_frame
Pointer to data received from localization stage.
std::shared_ptr< LocalizationToCollisionMessenger > localization_messenger
Pointers to messenger objects.
uint64_t number_of_vehicles
Number of vehicles registered with the traffic manager.
Parameters & parameters
Runtime parameterization object.
std::shared_ptr< CollisionToPlannerFrame > planner_frame_a
Pointers to output frames to be shared with motion planner stage.
std::shared_ptr< CollisionToPlannerFrame > planner_frame_b
std::shared_ptr< CollisionToPlannerMessenger > planner_messenger
SnippetProfiler snippet_profiler
Snippet profiler for measuring execution time.
std::unordered_map< std::string, GeometryComparisonCache > vehicle_cache
Geometry data for the vehicle.
std::unordered_map< ActorId, uint64_t > vehicle_id_to_index
The map used to connect actor ids to the array index of data frames.
Additional Inherited Members
Protected Attributes inherited from carla::traffic_manager::PipelineStage
std::atomic< bool > run_stage
Flag to start/stop stage.
std::string stage_name
Stage name string.
Detailed Description
This class is the thread executable for the collision detection stage and is responsible for checking possible collisions with other cars along the vehicle's trajectory.
Definition at line 75 of file CollisionStage.h.
Constructor & Destructor Documentation
carla::traffic_manager::CollisionStage::CollisionStage (std::string stage_name, std::shared_ptr< LocalizationToCollisionMessenger > localization_messenger, std::shared_ptr< CollisionToPlannerMessenger > planner_messenger, Parameters & parameters, cc::DebugHelper & debug_helper)
Definition at line 33 of file CollisionStage.cpp.
References frame_selector, last_world_actors_pass_instance, and number_of_vehicles.
carla::traffic_manager::CollisionStage::~CollisionStage ()
Definition at line 56 of file CollisionStage.cpp.
Member Function Documentation
void carla::traffic_manager::CollisionStage::Action () override virtual
Implement this method with logic to process data inside the stage.
Implements carla::traffic_manager::PipelineStage.
Definition at line 58 of file CollisionStage.cpp.
References carla::traffic_manager::LocalizationToCollisionData::actor, carla::geom::Math::Clamp(), carla::traffic_manager::LocalizationToCollisionData::closest_waypoint, carla::traffic_manager::CollisionToPlannerData::distance_to_other_vehicle, carla::geom::Math::DistanceSquared(), frame_selector, carla::traffic_manager::Parameters::GetCollisionDetection(), carla::traffic_manager::Parameters::GetPercentageIgnoreVehicles(), carla::traffic_manager::Parameters::GetPercentageIgnoreWalkers(), carla::traffic_manager::CollisionToPlannerData::hazard, IsLocationAfterJunctionSafe(), carla::traffic_manager::LocalizationToCollisionData::junction_look_ahead_waypoint, carla::geom::Vector3D::Length(), localization_frame, carla::log_info(), carla::traffic_manager::CollisionStageConstants::MAX_COLLISION_RADIUS, carla::traffic_manager::CollisionStageConstants::MIN_COLLISION_RADIUS, NegotiateCollision(), number_of_vehicles, carla::traffic_manager::CollisionToPlannerData::other_vehicle_velocity, carla::traffic_manager::LocalizationToCollisionData::overlapping_actors, parameters, planner_frame_a, planner_frame_b, carla::traffic_manager::LocalizationToCollisionData::safe_point_after_junction, vehicle_cache, carla::traffic_manager::LocalizationToCollisionData::velocity, carla::traffic_manager::CollisionStageConstants::VERTICAL_OVERLAP_THRESHOLD, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
void carla::traffic_manager::CollisionStage::DataReceiver () override virtual
Implement this method with the logic to receive data from the previous stage(s) and distribute to Action() threads.
Implements carla::traffic_manager::PipelineStage.
Definition at line 149 of file CollisionStage.cpp.
References geodesic_boundaries, localization_frame, localization_messenger, number_of_vehicles, planner_frame_a, planner_frame_b, and vehicle_id_to_index.
void carla::traffic_manager::CollisionStage::DataSender () override virtual
Implement this method with logic to gather results from the action threads and send to next stage(s).
Implements carla::traffic_manager::PipelineStage.
Definition at line 182 of file CollisionStage.cpp.
References frame_selector, localization_messenger, planner_frame_a, planner_frame_b, and planner_messenger.
void carla::traffic_manager::CollisionStage::DrawBoundary (const LocationList & boundary) private
A simple method used to draw bounding boxes around vehicles.
Definition at line 524 of file CollisionStage.cpp.
References debug_helper, and carla::client::DebugHelper::DrawLine().
LocationList carla::traffic_manager::CollisionStage::GetBoundary (const Actor & actor, const cg::Location & location, const cg::Vector3D velocity) private
Returns the bounding box corners of the vehicle passed to the method.
Definition at line 441 of file CollisionStage.cpp.
References carla::geom::BoundingBox::extent, carla::geom::Vector3D::Length(), carla::geom::Vector3D::MakeUnitVector(), carla::traffic_manager::CollisionStageConstants::WALKER_TIME_EXTENSION, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by GetGeodesicBoundary(), GetGeometryBetweenActors(), and IsLocationAfterJunctionSafe().
float carla::traffic_manager::CollisionStage::GetBoundingBoxExtention (const ActorId actor_id, const cg::Vector3D velocity_vector, const cg::Vector3D heading_vector) private
Method to calculate the speed dependent bounding box extention for a vehicle.
Definition at line 413 of file CollisionStage.cpp.
References carla::traffic_manager::CollisionStageConstants::ARBITRARY_MAX_SPEED, carla::traffic_manager::CollisionStageConstants::BOUNDARY_EXTENSION_MAXIMUM, carla::traffic_manager::CollisionStageConstants::BOUNDARY_EXTENSION_MINIMUM, collision_locks, carla::traffic_manager::CollisionLock::distance_to_lead_vehicle, carla::geom::Math::Dot(), carla::traffic_manager::CollisionLock::initial_lock_distance, carla::traffic_manager::CollisionStageConstants::LOCKING_DISTANCE_PADDING, and carla::traffic_manager::CollisionStageConstants::MAX_LOCKING_EXTENSION.
Referenced by GetGeodesicBoundary(), and NegotiateCollision().
LocationList carla::traffic_manager::CollisionStage::GetGeodesicBoundary (const Actor & actor, const cg::Location & location, const cg::Vector3D velocity) private
Returns the extrapolated bounding box of the vehicle along its trajectory.
Definition at line 322 of file CollisionStage.cpp.
References carla::traffic_manager::CollisionStageConstants::COS_10_DEGREES, carla::geom::Math::Dot(), carla::geom::BoundingBox::extent, geodesic_boundaries, GetBoundary(), carla::client::detail::ActorState::GetBoundingBox(), GetBoundingBoxExtention(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), localization_frame, carla::geom::Vector3D::MakeUnitVector(), MAX, parameters, reverse(), vehicle_id_to_index, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by GetGeometryBetweenActors().
GeometryComparisonCache carla::traffic_manager::CollisionStage::GetGeometryBetweenActors (const Actor & reference_vehicle, const Actor & other_vehicle, const cg::Location & reference_location, const cg::Location & other_location, const cg::Vector3D reference_velocity, const cg::Vector3D other_velocity) private
Method to compute Geometry result between two vehicles.
Definition at line 533 of file CollisionStage.cpp.
References GetBoundary(), GetGeodesicBoundary(), GetPolygon(), and vehicle_cache.
Referenced by NegotiateCollision().
traffic_manager::Polygon carla::traffic_manager::CollisionStage::GetPolygon (const LocationList & boundary) private
Method to construct a boost polygon object.
Definition at line 311 of file CollisionStage.cpp.
Referenced by GetGeometryBetweenActors(), and IsLocationAfterJunctionSafe().
bool carla::traffic_manager::CollisionStage::IsLocationAfterJunctionSafe (const Actor & ego_actor, const Actor & overlapped_actor, const SimpleWaypointPtr safe_point, const cg::Location & other_location, const cg::Vector3D other_velocity) private
At intersections, used to see if there is space after the junction.
Definition at line 480 of file CollisionStage.cpp.
References carla::traffic_manager::CollisionStageConstants::EPSILON_VELOCITY, GetBoundary(), GetPolygon(), carla::traffic_manager::CollisionStageConstants::INTER_BBOX_DISTANCE_THRESHOLD, carla::geom::Vector3D::Length(), carla::geom::Vector3D::MakeUnitVector(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by Action().
std::pair< bool, float > carla::traffic_manager::CollisionStage::NegotiateCollision (const Actor & ego_vehicle, const Actor & other_vehicle, const cg::Location & reference_location, const cg::Location & other_location, const SimpleWaypointPtr & closest_point, const SimpleWaypointPtr & junction_look_ahead, const cg::Vector3D reference_velocity, const cg::Vector3D other_velocity) private
The method returns true if ego_vehicle should stop and wait for other_vehicle to pass.
Definition at line 190 of file CollisionStage.cpp.
References carla::traffic_manager::CollisionStageConstants::BOUNDARY_EXTENSION_MINIMUM, collision_locks, carla::traffic_manager::CollisionLock::distance_to_lead_vehicle, carla::geom::Math::DistanceSquared(), carla::geom::Math::Dot(), carla::geom::BoundingBox::extent, carla::client::detail::ActorState::GetBoundingBox(), GetBoundingBoxExtention(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), GetGeometryBetweenActors(), carla::rpc::Green, carla::traffic_manager::GeometryComparisonCache::inter_bbox_distance, carla::traffic_manager::GeometryComparisonCache::inter_geodesic_distance, carla::traffic_manager::CollisionLock::lead_vehicle_id, carla::geom::Vector3D::MakeUnitVector(), MAX, carla::traffic_manager::GeometryComparisonCache::other_vehicle_to_reference_geodesic, parameters, carla::traffic_manager::GeometryComparisonCache::reference_vehicle_to_other_geodesic, carla::traffic_manager::CollisionStageConstants::SQUARE_ROOT_OF_TWO, and carla::geom::Vector3D::x.
Referenced by Action().
Member Data Documentation
std::unordered_map<ActorId, CollisionLock> carla::traffic_manager::CollisionStage::collision_locks private
Structure to keep track of collision locking.
Definition at line 105 of file CollisionStage.h.
Referenced by GetBoundingBoxExtention(), and NegotiateCollision().
cc::DebugHelper& carla::traffic_manager::CollisionStage::debug_helper private
Reference to Carla's debug helper object.
Definition at line 94 of file CollisionStage.h.
Referenced by DrawBoundary().
bool carla::traffic_manager::CollisionStage::frame_selector private
Selection key for switching between output frames.
Definition at line 82 of file CollisionStage.h.
Referenced by Action(), CollisionStage(), and DataSender().
std::unordered_map<ActorId, LocationList> carla::traffic_manager::CollisionStage::geodesic_boundaries private
Structure to hold the geodesic boundaries during one iteration.
Definition at line 103 of file CollisionStage.h.
Referenced by DataReceiver(), and GetGeodesicBoundary().
chr::time_point<chr::system_clock, chr::nanoseconds> carla::traffic_manager::CollisionStage::last_world_actors_pass_instance private
An object used to keep track of time between checking for all world actors.
Definition at line 99 of file CollisionStage.h.
Referenced by CollisionStage().
std::shared_ptr<LocalizationToCollisionFrame> carla::traffic_manager::CollisionStage::localization_frame private
Pointer to data received from localization stage.
Definition at line 84 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), and GetGeodesicBoundary().
std::shared_ptr<LocalizationToCollisionMessenger> carla::traffic_manager::CollisionStage::localization_messenger private
Pointers to messenger objects.
Definition at line 89 of file CollisionStage.h.
Referenced by DataReceiver(), and DataSender().
uint64_t carla::traffic_manager::CollisionStage::number_of_vehicles private
Number of vehicles registered with the traffic manager.
Definition at line 101 of file CollisionStage.h.
Referenced by Action(), CollisionStage(), and DataReceiver().
Parameters& carla::traffic_manager::CollisionStage::parameters private
Runtime parameterization object.
Definition at line 92 of file CollisionStage.h.
Referenced by Action(), GetGeodesicBoundary(), and NegotiateCollision().
std::shared_ptr<CollisionToPlannerFrame> carla::traffic_manager::CollisionStage::planner_frame_a private
Pointers to output frames to be shared with motion planner stage.
Definition at line 86 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<CollisionToPlannerFrame> carla::traffic_manager::CollisionStage::planner_frame_b private
Definition at line 87 of file CollisionStage.h.
Referenced by Action(), DataReceiver(), and DataSender().
std::shared_ptr<CollisionToPlannerMessenger> carla::traffic_manager::CollisionStage::planner_messenger private
Definition at line 90 of file CollisionStage.h.
Referenced by DataSender().
SnippetProfiler carla::traffic_manager::CollisionStage::snippet_profiler private
Snippet profiler for measuring execution time.
Definition at line 107 of file CollisionStage.h.
std::unordered_map<std::string, GeometryComparisonCache> carla::traffic_manager::CollisionStage::vehicle_cache private
Geometry data for the vehicle.
Definition at line 80 of file CollisionStage.h.
Referenced by Action(), and GetGeometryBetweenActors().
std::unordered_map<ActorId, uint64_t> carla::traffic_manager::CollisionStage::vehicle_id_to_index private
The map used to connect actor ids to the array index of data frames.
Definition at line 96 of file CollisionStage.h.
Referenced by DataReceiver(), and GetGeodesicBoundary().
The documentation for this class was generated from the following files:
CollisionStage.h
CollisionStage.cpp