CARLA: traffic_manager::MapConstants Namespace Reference
traffic_manager::MapConstants Namespace Reference
Variables
static const float GRID_SIZE = 4.0f
static const float INFINITE_DISTANCE = std::numeric_limits<float>::max()
static const float LANE_CHANGE_ANGULAR_THRESHOLD = 0.5f
static const uint LANE_CHANGE_LOOK_AHEAD = 5u
static const float ZERO_LENGTH = 0.0001f
Variable Documentation
const float traffic_manager::MapConstants::GRID_SIZE = 4.0f static
Definition at line 19 of file InMemoryMap.cpp.
Referenced by traffic_manager::InMemoryMap::MakeGridId().
const float traffic_manager::MapConstants::INFINITE_DISTANCE = std::numeric_limits<float>::max() static
Definition at line 15 of file InMemoryMap.cpp.
Referenced by traffic_manager::InMemoryMap::GetWaypoint(), traffic_manager::InMemoryMap::GetWaypointInVicinity(), and traffic_manager::InMemoryMap::SetUp().
const float traffic_manager::MapConstants::LANE_CHANGE_ANGULAR_THRESHOLD = 0.5f static
Definition at line 18 of file InMemoryMap.cpp.
Referenced by traffic_manager::InMemoryMap::SetUp().
const uint traffic_manager::MapConstants::LANE_CHANGE_LOOK_AHEAD = 5u static
Definition at line 16 of file InMemoryMap.cpp.
Referenced by traffic_manager::InMemoryMap::SetUp().
const float traffic_manager::MapConstants::ZERO_LENGTH = 0.0001f static
Definition at line 14 of file InMemoryMap.cpp.
Referenced by traffic_manager::InMemoryMap::SetUp().