CARLA: carla::sensor::data::LaneInvasionEvent Class Reference
carla::sensor::data::LaneInvasionEvent Class Reference
A change of lane event.
#include <LaneInvasionEvent.h>
Public Types
using LaneMarking = road::element::LaneMarking
Public Member Functions
SharedPtr< client::Actor > GetActor () const
Get "self" actor. Actor that invaded another lane.
const std::vector< LaneMarking > & GetCrossedLaneMarkings () const
List of lane markings that have been crossed.
LaneInvasionEvent (size_t frame, double timestamp, const rpc::Transform &sensor_transform, ActorId parent, std::vector< LaneMarking > crossed_lane_markings)
Public Member Functions inherited from carla::sensor::SensorData
size_t GetFrame () const
Frame count when the data was generated.
const rpc::Transform & GetSensorTransform () const
Sensor's transform when the data was generated.
double GetTimestamp () const
Simulation-time when the data was generated.
virtual ~SensorData ()=default
Private Attributes
std::vector< LaneMarking > _crossed_lane_markings
ActorId _parent
Additional Inherited Members
Protected Member Functions inherited from carla::sensor::SensorData
const auto & GetEpisode () const
SensorData (size_t frame, double timestamp, const rpc::Transform &sensor_transform)
SensorData (const RawData &data)
Detailed Description
A change of lane event.
Definition at line 22 of file LaneInvasionEvent.h.
Member Typedef Documentation
LaneMarking
using carla::sensor::data::LaneInvasionEvent::LaneMarking = road::element::LaneMarking
Definition at line 25 of file LaneInvasionEvent.h.
Constructor & Destructor Documentation
LaneInvasionEvent()
carla::sensor::data::LaneInvasionEvent::LaneInvasionEvent (size_t frame, double timestamp, const rpc::Transform & sensor_transform, ActorId parent, std::vector< LaneMarking > crossed_lane_markings) inline explicit
Definition at line 27 of file LaneInvasionEvent.h.
References GetActor().
Member Function Documentation
GetActor()
SharedPtr< client::Actor > carla::sensor::data::LaneInvasionEvent::GetActor () const
Get "self" actor. Actor that invaded another lane.
Definition at line 16 of file LaneInvasionEvent.cpp.
References _parent, carla::sensor::SensorData::GetEpisode(), and carla::throw_exception().
Referenced by LaneInvasionEvent().
GetCrossedLaneMarkings()
const std::vector<LaneMarking>& carla::sensor::data::LaneInvasionEvent::GetCrossedLaneMarkings () const inline
List of lane markings that have been crossed.
Definition at line 41 of file LaneInvasionEvent.h.
References _crossed_lane_markings.
Member Data Documentation
_crossed_lane_markings
std::vector<LaneMarking> carla::sensor::data::LaneInvasionEvent::_crossed_lane_markings private
Definition at line 49 of file LaneInvasionEvent.h.
Referenced by GetCrossedLaneMarkings().
_parent
ActorId carla::sensor::data::LaneInvasionEvent::_parent private
Definition at line 47 of file LaneInvasionEvent.h.
Referenced by GetActor().
The documentation for this class was generated from the following files:
LaneInvasionEvent.h
LaneInvasionEvent.cpp