CARLA: carla::sensor::data::LidarMeasurement Class Reference
carla::sensor::data::LidarMeasurement Class Reference
Measurement produced by a Lidar.
#include <LidarMeasurement.h>
Public Member Functions
auto GetChannelCount () const
Number of channels of the Lidar.
auto GetHorizontalAngle () const
Horizontal angle of the Lidar at the time of the measurement.
auto GetPointCount (size_t channel) const
Retrieve the number of points that channel generated.
Public Member Functions inherited from carla::sensor::data::Array< data::LidarDetection >
reference at (size_type pos)
const_reference at (size_type pos) const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
value_type * data ()
const value_type * data () const
bool empty () const
iterator end ()
const_iterator end () const
reference operator[] (size_type pos)
const_reference operator[] (size_type pos) const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
Public Member Functions inherited from carla::sensor::SensorData
size_t GetFrame () const
Frame count when the data was generated.
const rpc::Transform & GetSensorTransform () const
Sensor's transform when the data was generated.
double GetTimestamp () const
Simulation-time when the data was generated.
virtual ~SensorData ()=default
Protected Types
using Serializer = s11n::LidarSerializer
Protected Member Functions
LidarMeasurement (RawData &&data)
Protected Member Functions inherited from carla::sensor::data::Array< data::LidarDetection >
Array (RawData &&data, FuncT get_offset)
Array (size_t offset, RawData &&data)
const RawData & GetRawData () const
Protected Member Functions inherited from carla::sensor::SensorData
const auto & GetEpisode () const
SensorData (size_t frame, double timestamp, const rpc::Transform &sensor_transform)
SensorData (const RawData &data)
Protected Attributes
friend Serializer
Private Types
using Super = Array< data::LidarDetection >
Private Member Functions
auto GetHeader () const
Additional Inherited Members
Public Types inherited from carla::sensor::data::Array< data::LidarDetection >
using const_iterator = typename std::add_const< value_type >::type *
using const_pointer = typename std::add_const< value_type >::type *
using const_reference = typename std::add_const< value_type >::type &
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using iterator = value_type *
using pointer = value_type *
using reference = value_type &
using reverse_iterator = std::reverse_iterator< iterator >
using size_type = size_t
using value_type = data::LidarDetection
Detailed Description
Measurement produced by a Lidar.
Consists of an array of 3D points plus some extra meta-information about the Lidar.
Definition at line 20 of file LidarMeasurement.h.
Member Typedef Documentation
using carla::sensor::data::LidarMeasurement::Serializer = s11n::LidarSerializer protected
Definition at line 25 of file LidarMeasurement.h.
using carla::sensor::data::LidarMeasurement::Super = Array<data::LidarDetection> private
Definition at line 22 of file LidarMeasurement.h.
Constructor & Destructor Documentation
carla::sensor::data::LidarMeasurement::LidarMeasurement (RawData && data) inline explicit protected
Definition at line 29 of file LidarMeasurement.h.
References carla::sensor::s11n::LidarSerializer::GetHeaderOffset().
Member Function Documentation
auto carla::sensor::data::LidarMeasurement::GetChannelCount () const inline
Number of channels of the Lidar.
Definition at line 47 of file LidarMeasurement.h.
References GetHeader().
auto carla::sensor::data::LidarMeasurement::GetHeader () const inline private
Definition at line 36 of file LidarMeasurement.h.
References carla::sensor::s11n::LidarSerializer::DeserializeHeader(), and carla::sensor::data::Array< data::LidarDetection >::GetRawData().
Referenced by GetChannelCount(), GetHorizontalAngle(), and GetPointCount().
auto carla::sensor::data::LidarMeasurement::GetHorizontalAngle () const inline
Horizontal angle of the Lidar at the time of the measurement.
Definition at line 42 of file LidarMeasurement.h.
References GetHeader().
auto carla::sensor::data::LidarMeasurement::GetPointCount (size_t channel) const inline
Retrieve the number of points that channel generated.
Points are sorted by channel, so this method allows to identify the channel that generated each point.
Definition at line 54 of file LidarMeasurement.h.
References GetHeader().
Member Data Documentation
friend carla::sensor::data::LidarMeasurement::Serializer protected
Definition at line 27 of file LidarMeasurement.h.
The documentation for this class was generated from the following file:
LidarMeasurement.h