CARLA: carla::traffic_manager::TrafficManagerClient Class Reference
carla::traffic_manager::TrafficManagerClient Class Reference
Provides communication with the rpc of TrafficManagerServer.
#include <TrafficManagerClient.h>
Public Member Functions
ActionBuffer GetActionBuffer (const ActorId &actor_id)
Method to get the vehicle's action buffer.
Action GetNextAction (const ActorId &actor_id)
Method to get the vehicle's next action.
void getServerDetails (std::string &_host, uint16_t &_port)
Get parameters.
void HealthCheckRemoteTM ()
Check if remote traffic manager is alive.
TrafficManagerClient & operator= (const TrafficManagerClient &)=default
TrafficManagerClient & operator= (TrafficManagerClient &&)=default
void RegisterVehicle (const std::vector< carla::rpc::Actor > &actor_list)
Register vehicles to remote traffic manager server via RPC client.
void RemoveImportedRoute (const ActorId &actor_id, const bool remove_path)
Method to remove a route.
void RemoveUploadPath (const ActorId &actor_id, const bool remove_path)
Method to remove a list of points.
void SetAutoLaneChange (const carla::rpc::Actor &actor, const bool enable)
Enable/disable automatic lane change on a vehicle.
void SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound)
Method to set boundaries for respawning vehicles.
void SetCollisionDetection (const carla::rpc::Actor &reference_actor, const carla::rpc::Actor &other_actor, const bool detect_collision)
Method to set collision detection rules between vehicles.
void SetCustomPath (const carla::rpc::Actor &actor, const Path path, const bool empty_buffer)
Method to set our own imported path.
void SetDesiredSpeed (const carla::rpc::Actor &_actor, const float value)
Set a vehicle's exact desired velocity.
void SetDistanceToLeadingVehicle (const carla::rpc::Actor &actor, const float distance)
Method to specify how much distance a vehicle should maintain to the leading vehicle.
void SetForceLaneChange (const carla::rpc::Actor &actor, const bool direction)
Method to force lane change on a vehicle.
void SetGlobalDistanceToLeadingVehicle (const float distance)
Method to specify how much distance a vehicle should maintain to the Global leading vehicle.
void SetGlobalLaneOffset (const float offset)
Method to set a global lane offset displacement from the center line.
void SetGlobalPercentageSpeedDifference (const float percentage)
Method to set a global % decrease in velocity with respect to the speed limit.
void SetHybridPhysicsMode (const bool mode_switch)
Method to set hybrid physics mode.
void SetHybridPhysicsRadius (const float radius)
Method to set hybrid physics mode.
void SetImportedRoute (const carla::rpc::Actor &actor, const Route route, const bool empty_buffer)
Method to set our own imported route.
void SetKeepRightPercentage (const carla::rpc::Actor &actor, const float percentage)
Method to set % to keep on the right lane.
void SetLaneOffset (const carla::rpc::Actor &_actor, const float offset)
Method to set a lane offset displacement from the center line.
void SetMaxBoundaries (const float lower, const float upper)
Method to set boundaries for respawning vehicles.
void SetOSMMode (const bool mode_switch)
Method to set Open Street Map mode.
void SetPercentageIgnoreVehicles (const carla::rpc::Actor &actor, const float percentage)
Method to specify the % chance of ignoring collisions with any vehicle.
void SetPercentageIgnoreWalkers (const carla::rpc::Actor &actor, const float percentage)
Method to specify the % chance of ignoring collisions with any walker.
void SetPercentageRunningLight (const carla::rpc::Actor &actor, const float percentage)
Method to specify the % chance of running a traffic sign.
void SetPercentageRunningSign (const carla::rpc::Actor &actor, const float percentage)
Method to specify the % chance of running any traffic sign.
void SetPercentageSpeedDifference (const carla::rpc::Actor &_actor, const float percentage)
Method to set a vehicle's % decrease in velocity with respect to the speed limit.
void SetRandomDeviceSeed (const uint64_t seed)
Method to set randomization seed.
void SetRandomLeftLaneChangePercentage (const carla::rpc::Actor &actor, const float percentage)
Method to set % to randomly do a left lane change.
void SetRandomRightLaneChangePercentage (const carla::rpc::Actor &actor, const float percentage)
Method to set % to randomly do a right lane change.
void SetRespawnDormantVehicles (const bool mode_switch)
Method to set automatic respawn of dormant vehicles.
void setServerDetails (const std::string &_host, const uint16_t &_port)
Set parameters.
void SetSynchronousMode (const bool mode)
Method to switch traffic manager into synchronous execution.
void SetSynchronousModeTimeOutInMiliSecond (const double time)
Method to set tick timeout for synchronous execution.
void SetUpdateVehicleLights (const carla::rpc::Actor &_actor, const bool do_update)
Method to set the automatic management of the vehicle lights.
void ShutDown ()
bool SynchronousTick ()
Method to provide synchronous tick.
TrafficManagerClient (const std::string &_host, const uint16_t &_port)
Parametric constructor to initialize the parameters.
TrafficManagerClient (const TrafficManagerClient &)=default
TrafficManagerClient (TrafficManagerClient &&)=default
void UnregisterVehicle (const std::vector< carla::rpc::Actor > &actor_list)
Unregister vehicles to remote traffic manager server via RPC client.
void UpdateImportedRoute (const ActorId &actor_id, const Route route)
Method to update an already set list of points.
void UpdateUploadPath (const ActorId &actor_id, const Path path)
Method to update an already set list of points.
~TrafficManagerClient ()
Destructor method.
Private Attributes
::rpc::client * _client = nullptr
RPC client.
std::string tmhost
Server port and host.
uint16_t tmport
Detailed Description
Provides communication with the rpc of TrafficManagerServer.
Definition at line 21 of file TrafficManagerClient.h.
Constructor & Destructor Documentation
TrafficManagerClient() [1/3]
carla::traffic_manager::TrafficManagerClient::TrafficManagerClient (const TrafficManagerClient &) default
TrafficManagerClient() [2/3]
carla::traffic_manager::TrafficManagerClient::TrafficManagerClient (TrafficManagerClient &&) default
TrafficManagerClient() [3/3]
carla::traffic_manager::TrafficManagerClient::TrafficManagerClient (const std::string & _host, const uint16_t & _port) inline
Parametric constructor to initialize the parameters.
Create client instance.
Definition at line 32 of file TrafficManagerClient.h.
References _client, carla::traffic_manager::constants::Networking::TM_TIMEOUT, tmhost, and tmport.
~TrafficManagerClient()
carla::traffic_manager::TrafficManagerClient::~TrafficManagerClient () inline
Destructor method.
Definition at line 46 of file TrafficManagerClient.h.
References _client.
Member Function Documentation
GetActionBuffer()
ActionBuffer carla::traffic_manager::TrafficManagerClient::GetActionBuffer (const ActorId & actor_id) inline
Method to get the vehicle's action buffer.
Definition at line 302 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::GetActionBuffer().
GetNextAction()
Action carla::traffic_manager::TrafficManagerClient::GetNextAction (const ActorId & actor_id) inline
Method to get the vehicle's next action.
Definition at line 295 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::GetNextAction().
getServerDetails()
void carla::traffic_manager::TrafficManagerClient::getServerDetails (std::string & _host, uint16_t & _port) inline
Get parameters.
Definition at line 60 of file TrafficManagerClient.h.
References tmhost, and tmport.
Referenced by carla::traffic_manager::TrafficManagerRemote::Start().
HealthCheckRemoteTM()
void carla::traffic_manager::TrafficManagerClient::HealthCheckRemoteTM () inline
Check if remote traffic manager is alive.
Definition at line 186 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::HealthCheckRemoteTM(), and carla::traffic_manager::TrafficManagerRemote::Start().
operator=() [1/2]
TrafficManagerClient& carla::traffic_manager::TrafficManagerClient::operator= (const TrafficManagerClient &) default
operator=() [2/2]
TrafficManagerClient& carla::traffic_manager::TrafficManagerClient::operator= (TrafficManagerClient &&) default
RegisterVehicle()
void carla::traffic_manager::TrafficManagerClient::RegisterVehicle (const std::vector< carla::rpc::Actor > & actor_list) inline
Register vehicles to remote traffic manager server via RPC client.
Definition at line 66 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::RegisterVehicles().
RemoveImportedRoute()
void carla::traffic_manager::TrafficManagerClient::RemoveImportedRoute (const ActorId & actor_id, const bool remove_path) inline
Method to remove a route.
Definition at line 265 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::RemoveImportedRoute().
RemoveUploadPath()
void carla::traffic_manager::TrafficManagerClient::RemoveUploadPath (const ActorId & actor_id, const bool remove_path) inline
Method to remove a list of points.
Definition at line 247 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::RemoveUploadPath().
SetAutoLaneChange()
void carla::traffic_manager::TrafficManagerClient::SetAutoLaneChange (const carla::rpc::Actor & actor, const bool enable) inline
Enable/disable automatic lane change on a vehicle.
Definition at line 131 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetAutoLaneChange().
SetBoundariesRespawnDormantVehicles()
void carla::traffic_manager::TrafficManagerClient::SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound) inline
Method to set boundaries for respawning vehicles.
Definition at line 283 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetBoundariesRespawnDormantVehicles().
SetCollisionDetection()
void carla::traffic_manager::TrafficManagerClient::SetCollisionDetection (const carla::rpc::Actor & reference_actor, const carla::rpc::Actor & other_actor, const bool detect_collision) inline
Method to set collision detection rules between vehicles.
Definition at line 118 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetCollisionDetection().
SetCustomPath()
void carla::traffic_manager::TrafficManagerClient::SetCustomPath (const carla::rpc::Actor & actor, const Path path, const bool empty_buffer) inline
Method to set our own imported path.
Definition at line 241 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetCustomPath().
SetDesiredSpeed()
void carla::traffic_manager::TrafficManagerClient::SetDesiredSpeed (const carla::rpc::Actor & _actor, const float value) inline
Set a vehicle's exact desired velocity.
Definition at line 92 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetDesiredSpeed().
SetDistanceToLeadingVehicle()
void carla::traffic_manager::TrafficManagerClient::SetDistanceToLeadingVehicle (const carla::rpc::Actor & actor, const float distance) inline
Method to specify how much distance a vehicle should maintain to the leading vehicle.
Definition at line 138 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetDistanceToLeadingVehicle().
SetForceLaneChange()
void carla::traffic_manager::TrafficManagerClient::SetForceLaneChange (const carla::rpc::Actor & actor, const bool direction) inline
Method to force lane change on a vehicle.
Direction flag can be set to true for left and false for right.
Definition at line 125 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetForceLaneChange().
SetGlobalDistanceToLeadingVehicle()
void carla::traffic_manager::TrafficManagerClient::SetGlobalDistanceToLeadingVehicle (const float distance) inline
Method to specify how much distance a vehicle should maintain to the Global leading vehicle.
Definition at line 193 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetGlobalDistanceToLeadingVehicle().
SetGlobalLaneOffset()
void carla::traffic_manager::TrafficManagerClient::SetGlobalLaneOffset (const float offset) inline
Method to set a global lane offset displacement from the center line.
Positive values imply a right offset while negative ones mean a left one.
Definition at line 106 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetGlobalLaneOffset().
SetGlobalPercentageSpeedDifference()
void carla::traffic_manager::TrafficManagerClient::SetGlobalPercentageSpeedDifference (const float percentage) inline
Method to set a global % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Definition at line 99 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetGlobalPercentageSpeedDifference().
SetHybridPhysicsMode()
void carla::traffic_manager::TrafficManagerClient::SetHybridPhysicsMode (const bool mode_switch) inline
Method to set hybrid physics mode.
Definition at line 217 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetHybridPhysicsMode().
SetHybridPhysicsRadius()
void carla::traffic_manager::TrafficManagerClient::SetHybridPhysicsRadius (const float radius) inline
Method to set hybrid physics mode.
Definition at line 223 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetHybridPhysicsRadius().
SetImportedRoute()
void carla::traffic_manager::TrafficManagerClient::SetImportedRoute (const carla::rpc::Actor & actor, const Route route, const bool empty_buffer) inline
Method to set our own imported route.
Definition at line 259 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetImportedRoute().
SetKeepRightPercentage()
void carla::traffic_manager::TrafficManagerClient::SetKeepRightPercentage (const carla::rpc::Actor & actor, const float percentage) inline
Method to set % to keep on the right lane.
Definition at line 199 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetKeepRightPercentage().
SetLaneOffset()
void carla::traffic_manager::TrafficManagerClient::SetLaneOffset (const carla::rpc::Actor & _actor, const float offset) inline
Method to set a lane offset displacement from the center line.
Positive values imply a right offset while negative ones mean a left one.
Definition at line 86 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetLaneOffset().
SetMaxBoundaries()
void carla::traffic_manager::TrafficManagerClient::SetMaxBoundaries (const float lower, const float upper) inline
Method to set boundaries for respawning vehicles.
Definition at line 289 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetMaxBoundaries().
SetOSMMode()
void carla::traffic_manager::TrafficManagerClient::SetOSMMode (const bool mode_switch) inline
Method to set Open Street Map mode.
Definition at line 235 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetOSMMode().
SetPercentageIgnoreVehicles()
void carla::traffic_manager::TrafficManagerClient::SetPercentageIgnoreVehicles (const carla::rpc::Actor & actor, const float percentage) inline
Method to specify the % chance of ignoring collisions with any vehicle.
Definition at line 150 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetPercentageIgnoreVehicles().
SetPercentageIgnoreWalkers()
void carla::traffic_manager::TrafficManagerClient::SetPercentageIgnoreWalkers (const carla::rpc::Actor & actor, const float percentage) inline
Method to specify the % chance of ignoring collisions with any walker.
Definition at line 144 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetPercentageIgnoreWalkers().
SetPercentageRunningLight()
void carla::traffic_manager::TrafficManagerClient::SetPercentageRunningLight (const carla::rpc::Actor & actor, const float percentage) inline
Method to specify the % chance of running a traffic sign.
Definition at line 156 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetPercentageRunningLight().
SetPercentageRunningSign()
void carla::traffic_manager::TrafficManagerClient::SetPercentageRunningSign (const carla::rpc::Actor & actor, const float percentage) inline
Method to specify the % chance of running any traffic sign.
Definition at line 162 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetPercentageRunningSign().
SetPercentageSpeedDifference()
void carla::traffic_manager::TrafficManagerClient::SetPercentageSpeedDifference (const carla::rpc::Actor & _actor, const float percentage) inline
Method to set a vehicle's % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Definition at line 79 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetPercentageSpeedDifference().
SetRandomDeviceSeed()
void carla::traffic_manager::TrafficManagerClient::SetRandomDeviceSeed (const uint64_t seed) inline
Method to set randomization seed.
Definition at line 229 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetRandomDeviceSeed().
SetRandomLeftLaneChangePercentage()
void carla::traffic_manager::TrafficManagerClient::SetRandomLeftLaneChangePercentage (const carla::rpc::Actor & actor, const float percentage) inline
Method to set % to randomly do a left lane change.
Definition at line 205 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetRandomLeftLaneChangePercentage().
SetRandomRightLaneChangePercentage()
void carla::traffic_manager::TrafficManagerClient::SetRandomRightLaneChangePercentage (const carla::rpc::Actor & actor, const float percentage) inline
Method to set % to randomly do a right lane change.
Definition at line 211 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetRandomRightLaneChangePercentage().
SetRespawnDormantVehicles()
void carla::traffic_manager::TrafficManagerClient::SetRespawnDormantVehicles (const bool mode_switch) inline
Method to set automatic respawn of dormant vehicles.
Definition at line 277 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetRespawnDormantVehicles().
setServerDetails()
void carla::traffic_manager::TrafficManagerClient::setServerDetails (const std::string & _host, const uint16_t & _port) inline
Set parameters.
Definition at line 54 of file TrafficManagerClient.h.
References tmhost, and tmport.
SetSynchronousMode()
void carla::traffic_manager::TrafficManagerClient::SetSynchronousMode (const bool mode) inline
Method to switch traffic manager into synchronous execution.
Definition at line 168 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetSynchronousMode().
SetSynchronousModeTimeOutInMiliSecond()
void carla::traffic_manager::TrafficManagerClient::SetSynchronousModeTimeOutInMiliSecond (const double time) inline
Method to set tick timeout for synchronous execution.
Definition at line 174 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetSynchronousModeTimeOutInMiliSecond().
SetUpdateVehicleLights()
void carla::traffic_manager::TrafficManagerClient::SetUpdateVehicleLights (const carla::rpc::Actor & _actor, const bool do_update) inline
Method to set the automatic management of the vehicle lights.
Definition at line 112 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::SetUpdateVehicleLights().
ShutDown()
void carla::traffic_manager::TrafficManagerClient::ShutDown () inline
Definition at line 308 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::ShutDown().
SynchronousTick()
bool carla::traffic_manager::TrafficManagerClient::SynchronousTick () inline
Method to provide synchronous tick.
Definition at line 180 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
UnregisterVehicle()
void carla::traffic_manager::TrafficManagerClient::UnregisterVehicle (const std::vector< carla::rpc::Actor > & actor_list) inline
Unregister vehicles to remote traffic manager server via RPC client.
Definition at line 72 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::UnregisterVehicles().
UpdateImportedRoute()
void carla::traffic_manager::TrafficManagerClient::UpdateImportedRoute (const ActorId & actor_id, const Route route) inline
Method to update an already set list of points.
Definition at line 271 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::UpdateImportedRoute().
UpdateUploadPath()
void carla::traffic_manager::TrafficManagerClient::UpdateUploadPath (const ActorId & actor_id, const Path path) inline
Method to update an already set list of points.
Definition at line 253 of file TrafficManagerClient.h.
References _client, and DEBUG_ASSERT.
Referenced by carla::traffic_manager::TrafficManagerRemote::UpdateUploadPath().
Member Data Documentation
_client
::rpc::client* carla::traffic_manager::TrafficManagerClient::_client = nullptr private
RPC client.
Definition at line 316 of file TrafficManagerClient.h.
Referenced by GetActionBuffer(), GetNextAction(), HealthCheckRemoteTM(), RegisterVehicle(), RemoveImportedRoute(), RemoveUploadPath(), SetAutoLaneChange(), SetBoundariesRespawnDormantVehicles(), SetCollisionDetection(), SetCustomPath(), SetDesiredSpeed(), SetDistanceToLeadingVehicle(), SetForceLaneChange(), SetGlobalDistanceToLeadingVehicle(), SetGlobalLaneOffset(), SetGlobalPercentageSpeedDifference(), SetHybridPhysicsMode(), SetHybridPhysicsRadius(), SetImportedRoute(), SetKeepRightPercentage(), SetLaneOffset(), SetMaxBoundaries(), SetOSMMode(), SetPercentageIgnoreVehicles(), SetPercentageIgnoreWalkers(), SetPercentageRunningLight(), SetPercentageRunningSign(), SetPercentageSpeedDifference(), SetRandomDeviceSeed(), SetRandomLeftLaneChangePercentage(), SetRandomRightLaneChangePercentage(), SetRespawnDormantVehicles(), SetSynchronousMode(), SetSynchronousModeTimeOutInMiliSecond(), SetUpdateVehicleLights(), ShutDown(), SynchronousTick(), TrafficManagerClient(), UnregisterVehicle(), UpdateImportedRoute(), UpdateUploadPath(), and ~TrafficManagerClient().
tmhost
std::string carla::traffic_manager::TrafficManagerClient::tmhost private
Server port and host.
Definition at line 319 of file TrafficManagerClient.h.
Referenced by getServerDetails(), setServerDetails(), and TrafficManagerClient().
tmport
uint16_t carla::traffic_manager::TrafficManagerClient::tmport private
Definition at line 320 of file TrafficManagerClient.h.
Referenced by getServerDetails(), setServerDetails(), and TrafficManagerClient().
The documentation for this class was generated from the following file:
TrafficManagerClient.h