CARLA: carla::ros2::CarlaOpticalFlowCameraPublisher Class Reference
carla::ros2::CarlaOpticalFlowCameraPublisher Class Reference
#include <CarlaOpticalFlowCameraPublisher.h>
Public Member Functions
CarlaOpticalFlowCameraPublisher (CarlaOpticalFlowCameraPublisher &&)
CarlaOpticalFlowCameraPublisher (const CarlaOpticalFlowCameraPublisher &)
CarlaOpticalFlowCameraPublisher (const char *ros_name="", const char *parent="")
bool HasBeenInitialized () const
bool Init ()
void InitInfoData (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify)
CarlaOpticalFlowCameraPublisher & operator= (CarlaOpticalFlowCameraPublisher &&)
CarlaOpticalFlowCameraPublisher & operator= (const CarlaOpticalFlowCameraPublisher &)
bool Publish ()
void SetCameraInfoData (int32_t seconds, uint32_t nanoseconds)
void SetImageData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, const float *data)
const char * type () const override
~CarlaOpticalFlowCameraPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Member Functions
bool InitImage ()
bool InitInfo ()
bool PublishImage ()
bool PublishInfo ()
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > &&data)
void SetInfoRegionOfInterest (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify)
Private Attributes
std::shared_ptr< CarlaOpticalFlowCameraPublisherImpl > _impl
std::shared_ptr< CarlaCameraInfoPublisherImpl > _impl_info
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 19 of file CarlaOpticalFlowCameraPublisher.h.
Constructor & Destructor Documentation
CarlaOpticalFlowCameraPublisher() [1/3]
carla::ros2::CarlaOpticalFlowCameraPublisher::CarlaOpticalFlowCameraPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 422 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaOpticalFlowCameraPublisher()
carla::ros2::CarlaOpticalFlowCameraPublisher::~CarlaOpticalFlowCameraPublisher ()
Definition at line 429 of file CarlaOpticalFlowCameraPublisher.cpp.
References _impl, and _impl_info.
CarlaOpticalFlowCameraPublisher() [2/3]
carla::ros2::CarlaOpticalFlowCameraPublisher::CarlaOpticalFlowCameraPublisher (const CarlaOpticalFlowCameraPublisher & other)
Definition at line 461 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaOpticalFlowCameraPublisher() [3/3]
carla::ros2::CarlaOpticalFlowCameraPublisher::CarlaOpticalFlowCameraPublisher (CarlaOpticalFlowCameraPublisher && other)
Definition at line 479 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
HasBeenInitialized()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::HasBeenInitialized () const
Definition at line 59 of file CarlaOpticalFlowCameraPublisher.cpp.
References _impl_info.
Init()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::Init ()
Definition at line 69 of file CarlaOpticalFlowCameraPublisher.cpp.
References InitImage(), and InitInfo().
InitImage()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::InitImage () private
Definition at line 73 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Referenced by Init().
InitInfo()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::InitInfo () private
Definition at line 122 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Referenced by Init().
InitInfoData()
void carla::ros2::CarlaOpticalFlowCameraPublisher::InitInfoData (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify)
Definition at line 63 of file CarlaOpticalFlowCameraPublisher.cpp.
References _impl_info, and SetInfoRegionOfInterest().
operator=() [1/2]
CarlaOpticalFlowCameraPublisher & carla::ros2::CarlaOpticalFlowCameraPublisher::operator= (CarlaOpticalFlowCameraPublisher && other)
Definition at line 488 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaOpticalFlowCameraPublisher & carla::ros2::CarlaOpticalFlowCameraPublisher::operator= (const CarlaOpticalFlowCameraPublisher & other)
Definition at line 469 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::Publish ()
Definition at line 170 of file CarlaOpticalFlowCameraPublisher.cpp.
References PublishImage(), and PublishInfo().
PublishImage()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::PublishImage () private
Definition at line 174 of file CarlaOpticalFlowCameraPublisher.cpp.
References _impl.
Referenced by Publish().
PublishInfo()
bool carla::ros2::CarlaOpticalFlowCameraPublisher::PublishInfo () private
Definition at line 236 of file CarlaOpticalFlowCameraPublisher.cpp.
References _impl_info.
Referenced by Publish().
SetCameraInfoData()
void carla::ros2::CarlaOpticalFlowCameraPublisher::SetCameraInfoData (int32_t seconds, uint32_t nanoseconds)
Definition at line 411 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl_info, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
SetData()
void carla::ros2::CarlaOpticalFlowCameraPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > && data) private
Definition at line 393 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
Referenced by SetImageData().
SetImageData()
void carla::ros2::CarlaOpticalFlowCameraPublisher::SetImageData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, const float * data)
Definition at line 298 of file CarlaOpticalFlowCameraPublisher.cpp.
References carla::logging::log(), and SetData().
SetInfoRegionOfInterest()
void carla::ros2::CarlaOpticalFlowCameraPublisher::SetInfoRegionOfInterest (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify) private
Definition at line 383 of file CarlaOpticalFlowCameraPublisher.cpp.
References _impl_info, sensor_msgs::msg::RegionOfInterest::do_rectify(), sensor_msgs::msg::RegionOfInterest::height(), sensor_msgs::msg::RegionOfInterest::width(), sensor_msgs::msg::RegionOfInterest::x_offset(), and sensor_msgs::msg::RegionOfInterest::y_offset().
Referenced by InitInfoData().
type()
const char* carla::ros2::CarlaOpticalFlowCameraPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 35 of file CarlaOpticalFlowCameraPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaOpticalFlowCameraPublisherImpl> carla::ros2::CarlaOpticalFlowCameraPublisher::_impl private
Definition at line 47 of file CarlaOpticalFlowCameraPublisher.h.
Referenced by CarlaOpticalFlowCameraPublisher(), InitImage(), operator=(), PublishImage(), SetData(), and ~CarlaOpticalFlowCameraPublisher().
_impl_info
std::shared_ptr<CarlaCameraInfoPublisherImpl> carla::ros2::CarlaOpticalFlowCameraPublisher::_impl_info private
Definition at line 48 of file CarlaOpticalFlowCameraPublisher.h.
Referenced by CarlaOpticalFlowCameraPublisher(), HasBeenInitialized(), InitInfo(), InitInfoData(), operator=(), PublishInfo(), SetCameraInfoData(), SetInfoRegionOfInterest(), and ~CarlaOpticalFlowCameraPublisher().
The documentation for this class was generated from the following files:
CarlaOpticalFlowCameraPublisher.h
CarlaOpticalFlowCameraPublisher.cpp