CARLA: carla::streaming::detail::Dispatcher Class Reference
carla::streaming::detail::Dispatcher Class Reference
Keeps the mapping between streams and sessions.
#include <Dispatcher.h>
Public Member Functions
void DeregisterSession (std::shared_ptr< Session > session)
template<typename Protocol , typename EndPointType >
Dispatcher (const EndPoint< Protocol, EndPointType > &ep)
carla::streaming::MultiStream MakeMultiStream ()
carla::streaming::Stream MakeStream ()
bool RegisterSession (std::shared_ptr< Session > session)
~Dispatcher ()
Private Member Functions
void ClearExpiredStreams ()
Private Attributes
token_type _cached_token
std::mutex _mutex
std::unordered_map< stream_id_type, std::weak_ptr< StreamStateBase > > _stream_map
Detailed Description
Keeps the mapping between streams and sessions.
Definition at line 25 of file Dispatcher.h.
Constructor & Destructor Documentation
template<typename Protocol , typename EndPointType > carla::streaming::detail::Dispatcher::Dispatcher (const EndPoint< Protocol, EndPointType > & ep) inline explicit
Definition at line 29 of file Dispatcher.h.
References ClearExpiredStreams(), DeregisterSession(), MakeMultiStream(), MakeStream(), RegisterSession(), and ~Dispatcher().
carla::streaming::detail::Dispatcher::~Dispatcher ()
Definition at line 30 of file Dispatcher.cpp.
References _stream_map, and carla::log_error().
Referenced by Dispatcher().
Member Function Documentation
void carla::streaming::detail::Dispatcher::ClearExpiredStreams () private
Definition at line 90 of file Dispatcher.cpp.
References _stream_map.
Referenced by DeregisterSession(), and Dispatcher().
void carla::streaming::detail::Dispatcher::DeregisterSession (std::shared_ptr< Session > session)
Definition at line 77 of file Dispatcher.cpp.
References _mutex, _stream_map, ClearExpiredStreams(), and DEBUG_ASSERT.
Referenced by Dispatcher(), and carla::streaming::low_level::Server< detail::tcp::Server >::StartServer().
carla::streaming::MultiStream carla::streaming::detail::Dispatcher::MakeMultiStream ()
Definition at line 56 of file Dispatcher.cpp.
References _cached_token, _mutex, _stream_map, carla::streaming::detail::token_type::_token, and carla::streaming::detail::token_data::stream_id.
Referenced by Dispatcher(), and carla::streaming::low_level::Server< detail::tcp::Server >::MakeMultiStream().
carla::streaming::Stream carla::streaming::detail::Dispatcher::MakeStream ()
Definition at line 50 of file Dispatcher.cpp.
References _cached_token, _mutex, _stream_map, carla::streaming::detail::token_type::_token, and carla::streaming::detail::token_data::stream_id.
Referenced by Dispatcher(), carla::streaming::low_level::Server< detail::tcp::Server >::MakeStream(), and TEST().
bool carla::streaming::detail::Dispatcher::RegisterSession (std::shared_ptr< Session > session)
Definition at line 62 of file Dispatcher.cpp.
References _mutex, _stream_map, DEBUG_ASSERT, and carla::log_error().
Referenced by Dispatcher(), and carla::streaming::low_level::Server< detail::tcp::Server >::StartServer().
Member Data Documentation
token_type carla::streaming::detail::Dispatcher::_cached_token private
Definition at line 50 of file Dispatcher.h.
Referenced by MakeMultiStream(), and MakeStream().
std::mutex carla::streaming::detail::Dispatcher::_mutex private
Definition at line 48 of file Dispatcher.h.
Referenced by DeregisterSession(), MakeMultiStream(), MakeStream(), and RegisterSession().
std::unordered_map< stream_id_type, std::weak_ptr<StreamStateBase> > carla::streaming::detail::Dispatcher::_stream_map private
Definition at line 54 of file Dispatcher.h.
Referenced by ClearExpiredStreams(), DeregisterSession(), MakeMultiStream(), MakeStream(), RegisterSession(), and ~Dispatcher().
The documentation for this class was generated from the following files:
Dispatcher.h
Dispatcher.cpp