CARLA: carla::sensor::s11n::IMUSerializer Class Reference
carla::sensor::s11n::IMUSerializer Class Reference
#include <IMUSerializer.h>
Classes
struct Data
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static Data DeserializeRawData (const RawData &message)
template<typename SensorT >
static Buffer Serialize (const SensorT &sensor, const geom::Vector3D &accelerometer, const geom::Vector3D &gyroscope, const float compass)
Detailed Description
Definition at line 20 of file IMUSerializer.h.
Member Function Documentation
SharedPtr< SensorData > carla::sensor::s11n::IMUSerializer::Deserialize (RawData && data) static
Definition at line 14 of file IMUSerializer.cpp.
Referenced by DeserializeRawData().
static Data carla::sensor::s11n::IMUSerializer::DeserializeRawData (const RawData & message) inline static
Definition at line 42 of file IMUSerializer.h.
References carla::sensor::RawData::begin(), Deserialize(), and carla::sensor::RawData::size().
template<typename SensorT > Buffer carla::sensor::s11n::IMUSerializer::Serialize (const SensorT & sensor, const geom::Vector3D & accelerometer, const geom::Vector3D & gyroscope, const float compass) inline static
Definition at line 50 of file IMUSerializer.h.
References carla::sensor::s11n::IMUSerializer::Data::accelerometer, carla::sensor::s11n::IMUSerializer::Data::gyroscope, and carla::MsgPack::Pack().
The documentation for this class was generated from the following files:
IMUSerializer.h
IMUSerializer.cpp