CARLA: wchar_decoder Struct Reference
wchar_decoder Struct Reference
Public Types
typedef wchar_t type
Static Public Member Functions
template<typename Traits >
static Traits::value_type process (const wchar_t *data, size_t size, typename Traits::value_type result, Traits traits)
Detailed Description
Definition at line 1812 of file pugixml.cpp.
Member Typedef Documentation
type
typedef wchar_t wchar_decoder::type
Definition at line 1814 of file pugixml.cpp.
Member Function Documentation
process()
template<typename Traits > static Traits::value_type wchar_decoder::process (const wchar_t * data, size_t size, typename Traits::value_type result, Traits traits) inline static
Definition at line 1816 of file pugixml.cpp.
References endian_swap(), PUGI__FN, PUGI__NS_BEGIN, and PUGI__NS_END.
Referenced by as_utf8_begin(), and as_utf8_end().
The documentation for this struct was generated from the following file:
pugixml.cpp