CARLA: RoutePlanner.cpp File Reference
RoutePlanner.cpp File Reference
#include "Carla.h"
#include "RoutePlanner.h"
#include "Util/RandomEngine.h"
#include "Vehicle/CarlaWheeledVehicle.h"
#include "Vehicle/WheeledVehicleAIController.h"
#include "Engine/CollisionProfile.h"
#include "DrawDebugHelpers.h"
Functions
static AWheeledVehicleAIController * GetVehicleController (AActor *Actor)
static bool IsSplineValid (const USplineComponent *SplineComponent)
static const USplineComponent * PickARoute (URandomEngine &RandomEngine, const TArray< USplineComponent *> &Routes, const TArray< float > &Probabilities)
Function Documentation
GetVehicleController()
static AWheeledVehicleAIController* GetVehicleController (AActor * Actor) static
Definition at line 23 of file RoutePlanner.cpp.
References Vehicle.
Referenced by ARoutePlanner::OnTriggerBeginOverlap().
IsSplineValid()
static bool IsSplineValid (const USplineComponent * SplineComponent) static
Definition at line 17 of file RoutePlanner.cpp.
Referenced by ARoutePlanner::Init().
PickARoute()
static const USplineComponent* PickARoute (URandomEngine & RandomEngine, const TArray< USplineComponent *> & Routes, const TArray< float > & Probabilities) static
Definition at line 31 of file RoutePlanner.cpp.
References URandomEngine::GetIntWithWeight().
Referenced by ARoutePlanner::AssignRandomRoute().