CARLA: traffic_manager Namespace Reference
traffic_manager Namespace Reference
Namespaces
CollisionStageConstants
LocalizationConstants
MapConstants
PIDControllerConstants
PlannerConstants
Classes
struct ActuationSignal
Structure to hold the actuation signals.
class AtomicActorSet
class AtomicMap
class BatchControlStage
This class receives actuation signals (throttle, brake, steer) from MotionPlannerStage class and communicates these signals to the simulator in batches to control vehicles' movement.
class CarlaDataAccessLayer
This class is responsible for retrieving data from the server.
struct ChangeLaneInfo
class CollisionStage
This class is the thread executable for the collision detection stage.
struct CollisionToPlannerData
Type of data sent by the collision stage to the motion planner stage.
struct DataPacket
class InMemoryMap
This class builds a discretized local map-cache.
class LocalizationStage
This class is responsible for maintaining a horizon of waypoints ahead of the vehicle for it to follow.
struct LocalizationToCollisionData
Type of data sent by the localization stage to the collision stage.
struct LocalizationToPlannerData
Data types.
struct LocalizationToTrafficLightData
Type of data sent by the localization stage to the traffic light stage.
class Messenger
This class is the template for messaging functionality between different stage classes to send and receive data.
class MotionPlannerStage
The class is responsible for aggregating information from various stages like the localization stage, traffic light stage, collision detection stage and actuation signals from the PID controller and makes decisions on how to move the vehicle to follow it's trajectory safely.
class Parameters
class PerformanceDiagnostics
class PIDController
This class calculates PID actuation signals to control the vehicle such that the vehicle maintains a target velocity and aligns its orientation along its trajectory.
class PipelineStage
This class provides base functionality and template for various stages of the pipeline.
struct PlannerToControlData
Type of data sent by the motion planner stage to the batch control stage.
class SimpleWaypoint
This is a simple wrapper class on Carla's waypoint object.
struct StateEntry
Structure to hold the controller state.
class TrackTraffic
class TrafficLightStage
This class provides the information about the Traffic Lights at the junctions.
struct TrafficLightToPlannerData
Type of data sent by the traffic light stage to the motion planner stage.
class TrafficManager
The function of this class is to integrate all the various stages of the traffic manager appropriately using messengers.
class VicinityGrid
This class maintains vehicle positions in grid segments.
Typedefs
using Actor = carla::SharedPtr< cc::Actor >
using ActorId = carla::ActorId
using ActorIdSet = std::unordered_set< ActorId >
using ActorPtr = carla::SharedPtr< cc::Actor >
using Buffer = std::deque< SimpleWaypointPtr >
Convenience typing.
using BufferList = std::vector< Buffer >
Alias used for the list of buffers in the localization stage.
using CollisionToPlannerFrame = std::vector< CollisionToPlannerData >
using CollisionToPlannerMessenger = Messenger< std::shared_ptr< CollisionToPlannerFrame >>
using JunctionID = carla::road::JuncId
using LocalizationToCollisionFrame = std::vector< LocalizationToCollisionData >
using LocalizationToCollisionMessenger = Messenger< std::shared_ptr< LocalizationToCollisionFrame >>
using LocalizationToPlannerFrame = std::vector< LocalizationToPlannerData >
Data frame types.
using LocalizationToPlannerMessenger = Messenger< std::shared_ptr< LocalizationToPlannerFrame >>
Messenger types.
using LocalizationToTrafficLightFrame = std::vector< LocalizationToTrafficLightData >
using LocalizationToTrafficLightMessenger = Messenger< std::shared_ptr< LocalizationToTrafficLightFrame >>
using LocationList = std::vector< cg::Location >
using NodeList = std::vector< SimpleWaypointPtr >
using PlannerToControlFrame = std::vector< PlannerToControlData >
using PlannerToControlMessenger = Messenger< std::shared_ptr< PlannerToControlFrame >>
using Polygon = bg::model::polygon< bg::model::d2::point_xy< double >>
using SimpleWaypointPtr = std::shared_ptr< SimpleWaypoint >
using TimeInstance = chr::time_point< chr::_V2::system_clock, chr::nanoseconds >
using TLGroup = std::vector< carla::SharedPtr< cc::TrafficLight >>
using TLS = carla::rpc::TrafficLightState
using TopologyList = std::vector< std::pair< WaypointPtr, WaypointPtr >>
using TrafficLight = carla::SharedPtr< cc::TrafficLight >
using TrafficLightToPlannerFrame = std::vector< TrafficLightToPlannerData >
using TrafficLightToPlannerMessenger = Messenger< std::shared_ptr< TrafficLightToPlannerFrame >>
using WaypointPtr = carla::SharedPtr< cc::Waypoint >
Functions
float DeviationCrossProduct (Actor actor, const cg::Location &target_location)
Returns the cross product (z component value) between the vehicle's heading vector and the vector along the direction to the next target waypoint on the horizon.
float DeviationDotProduct (Actor actor, const cg::Location &target_location, bool rear_offset=false)
Returns the dot product between the vehicle's heading vector and the vector along the direction to the next target waypoint on the horizon.
Variables
static const float GRID_SIZE = 10.0f
static const uint NO_SIGNAL_PASSTHROUGH_INTERVAL = 5u
Typedef Documentation
typedef carla::SharedPtr< cc::Actor > traffic_manager::Actor
Definition at line 45 of file CollisionStage.h.
typedef carla::ActorId traffic_manager::ActorId
Definition at line 20 of file AtomicActorSet.h.
typedef std::unordered_set< ActorId > traffic_manager::ActorIdSet
Definition at line 41 of file LocalizationStage.h.
typedef carla::SharedPtr< cc::Actor > traffic_manager::ActorPtr
Definition at line 19 of file AtomicActorSet.h.
typedef std::deque< SimpleWaypointPtr > traffic_manager::Buffer
Convenience typing.
Alias for waypoint buffer used in the localization stage.
Definition at line 24 of file LocalizationUtils.h.
using traffic_manager::BufferList = typedef std::vector<Buffer>
Alias used for the list of buffers in the localization stage.
Definition at line 28 of file MessengerAndDataTypes.h.
using traffic_manager::CollisionToPlannerFrame = typedef std::vector<CollisionToPlannerData>
Definition at line 80 of file MessengerAndDataTypes.h.
using traffic_manager::CollisionToPlannerMessenger = typedef Messenger<std::shared_ptr<CollisionToPlannerFrame>>
Definition at line 89 of file MessengerAndDataTypes.h.
using traffic_manager::JunctionID = typedef carla::road::JuncId
Definition at line 34 of file TrafficLightStage.h.
using traffic_manager::LocalizationToCollisionFrame = typedef std::vector<LocalizationToCollisionData>
Definition at line 78 of file MessengerAndDataTypes.h.
using traffic_manager::LocalizationToCollisionMessenger = typedef Messenger<std::shared_ptr<LocalizationToCollisionFrame>>
Definition at line 87 of file MessengerAndDataTypes.h.
using traffic_manager::LocalizationToPlannerFrame = typedef std::vector<LocalizationToPlannerData>
Data frame types.
Array types of data flowing between stages.
Definition at line 76 of file MessengerAndDataTypes.h.
using traffic_manager::LocalizationToPlannerMessenger = typedef Messenger<std::shared_ptr<LocalizationToPlannerFrame>>
Messenger types.
Definition at line 85 of file MessengerAndDataTypes.h.
using traffic_manager::LocalizationToTrafficLightFrame = typedef std::vector<LocalizationToTrafficLightData>
Definition at line 79 of file MessengerAndDataTypes.h.
using traffic_manager::LocalizationToTrafficLightMessenger = typedef Messenger<std::shared_ptr<LocalizationToTrafficLightFrame>>
Definition at line 88 of file MessengerAndDataTypes.h.
using traffic_manager::LocationList = typedef std::vector<cg::Location>
Definition at line 47 of file CollisionStage.h.
using traffic_manager::NodeList = typedef std::vector<SimpleWaypointPtr>
Definition at line 33 of file InMemoryMap.h.
using traffic_manager::PlannerToControlFrame = typedef std::vector<PlannerToControlData>
Definition at line 77 of file MessengerAndDataTypes.h.
using traffic_manager::PlannerToControlMessenger = typedef Messenger<std::shared_ptr<PlannerToControlFrame>>
Definition at line 86 of file MessengerAndDataTypes.h.
using traffic_manager::Polygon = typedef bg::model::polygon<bg::model::d2::point_xy<double>>
Definition at line 46 of file CollisionStage.h.
typedef std::shared_ptr< SimpleWaypoint > traffic_manager::SimpleWaypointPtr
Definition at line 48 of file CollisionStage.h.
typedef chr::time_point< chr::_V2::system_clock, chr::nanoseconds > traffic_manager::TimeInstance
Definition at line 16 of file PIDController.h.
using traffic_manager::TLGroup = typedef std::vector<carla::SharedPtr<cc::TrafficLight>>
Definition at line 40 of file TrafficManager.h.
typedef carla::rpc::TrafficLightState traffic_manager::TLS
Definition at line 49 of file CollisionStage.h.
using traffic_manager::TopologyList = typedef std::vector<std::pair<WaypointPtr, WaypointPtr>>
Definition at line 31 of file InMemoryMap.h.
using traffic_manager::TrafficLight = typedef carla::SharedPtr<cc::TrafficLight>
Definition at line 36 of file TrafficLightStage.h.
using traffic_manager::TrafficLightToPlannerFrame = typedef std::vector<TrafficLightToPlannerData>
Definition at line 81 of file MessengerAndDataTypes.h.
using traffic_manager::TrafficLightToPlannerMessenger = typedef Messenger<std::shared_ptr<TrafficLightToPlannerFrame>>
Definition at line 90 of file MessengerAndDataTypes.h.
typedef carla::SharedPtr< cc::Waypoint > traffic_manager::WaypointPtr
Definition at line 15 of file CarlaDataAccessLayer.cpp.
Function Documentation
float traffic_manager::DeviationCrossProduct (Actor actor, const cg::Location & target_location)
Returns the cross product (z component value) between the vehicle's heading vector and the vector along the direction to the next target waypoint on the horizon.
Definition at line 11 of file LocalizationUtils.cpp.
References carla::geom::Vector3D::Length(), carla::geom::Vector3D::MakeUnitVector(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by traffic_manager::LocalizationStage::Action().
float traffic_manager::DeviationDotProduct (Actor actor, const cg::Location & target_location, bool rear_offset = false)
Returns the dot product between the vehicle's heading vector and the vector along the direction to the next target waypoint on the horizon.
Definition at line 27 of file LocalizationUtils.cpp.
References carla::geom::Math::Dot(), carla::geom::BoundingBox::extent, carla::client::detail::ActorState::GetBoundingBox(), carla::geom::Vector3D::Length(), carla::geom::Vector3D::MakeUnitVector(), carla::geom::Vector3D::x, and carla::geom::Vector3D::z.
Referenced by traffic_manager::LocalizationStage::Action(), and traffic_manager::LocalizationStage::AssignLaneChange().
Variable Documentation
const float traffic_manager::GRID_SIZE = 10.0f static
Definition at line 11 of file VicinityGrid.cpp.
const uint traffic_manager::NO_SIGNAL_PASSTHROUGH_INTERVAL = 5u static
Definition at line 13 of file TrafficLightStage.cpp.
Referenced by traffic_manager::TrafficLightStage::Action().