CARLA: rosgraph::msg::Clock Class Reference
rosgraph::msg::Clock Class Reference
This class represents the structure Clock defined by the user in the IDL file.
#include <Clock.h>
Public Member Functions
eProsima_user_DllExport Clock ()
Default constructor.
eProsima_user_DllExport Clock (const Clock &x)
Copy constructor.
eProsima_user_DllExport Clock (Clock &&x) noexcept
Move constructor.
eProsima_user_DllExport void clock (const builtin_interfaces::msg::Time &_clock)
This function copies the value in member clock.
eProsima_user_DllExport void clock (builtin_interfaces::msg::Time &&_clock)
This function moves the value in member clock.
eProsima_user_DllExport const builtin_interfaces::msg::Time & clock () const
This function returns a constant reference to member clock.
eProsima_user_DllExport builtin_interfaces::msg::Time & clock ()
This function returns a reference to member clock.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const Clock &x) const
Comparison operator.
eProsima_user_DllExport Clock & operator= (const Clock &x)
Copy assignment.
eProsima_user_DllExport Clock & operator= (Clock &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Clock &x) const
Comparison operator.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport ~Clock ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const rosgraph::msg::Clock &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
builtin_interfaces::msg::Time m_clock
Detailed Description
This class represents the structure Clock defined by the user in the IDL file.
Definition at line 72 of file Clock.h.
Constructor & Destructor Documentation
Clock() [1/3]
rosgraph::msg::Clock::Clock ()
Default constructor.
Definition at line 42 of file Clock.cpp.
~Clock()
rosgraph::msg::Clock::~Clock ()
Default destructor.
Definition at line 46 of file Clock.cpp.
Clock() [2/3]
rosgraph::msg::Clock::Clock (const Clock & x)
Copy constructor.
Parameters
x Reference to the object rosgraph::msg::Clock that will be copied.
Definition at line 50 of file Clock.cpp.
References m_clock.
Clock() [3/3]
rosgraph::msg::Clock::Clock (Clock && x) noexcept
Move constructor.
Parameters
x Reference to the object rosgraph::msg::Clock that will be copied.
Definition at line 56 of file Clock.cpp.
Member Function Documentation
clock() [1/4]
void rosgraph::msg::Clock::clock (const builtin_interfaces::msg::Time & _clock)
This function copies the value in member clock.
Parameters
_clock New value to be copied in member clock
Definition at line 124 of file Clock.cpp.
Referenced by getCdrSerializedSize().
clock() [2/4]
void rosgraph::msg::Clock::clock (builtin_interfaces::msg::Time && _clock)
This function moves the value in member clock.
Parameters
_clock New value to be moved in member clock
Definition at line 134 of file Clock.cpp.
clock() [3/4]
const builtin_interfaces::msg::Time & rosgraph::msg::Clock::clock () const
This function returns a constant reference to member clock.
Returns
Constant reference to member clock
Definition at line 144 of file Clock.cpp.
clock() [4/4]
builtin_interfaces::msg::Time & rosgraph::msg::Clock::clock ()
This function returns a reference to member clock.
Returns
Reference to member clock
Definition at line 153 of file Clock.cpp.
deserialize()
void rosgraph::msg::Clock::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 114 of file Clock.cpp.
Referenced by rosgraph::msg::ClockPubSubType::deserialize().
getCdrSerializedSize()
size_t rosgraph::msg::Clock::getCdrSerializedSize (const rosgraph::msg::Clock & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 95 of file Clock.cpp.
References clock(), and builtin_interfaces::msg::Time::getCdrSerializedSize().
Referenced by rosgraph::msg::ClockPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t rosgraph::msg::Clock::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 158 of file Clock.cpp.
References rosgraph_msg_Clock_max_key_cdr_typesize.
Referenced by rosgraph::msg::ClockPubSubType::ClockPubSubType(), and rosgraph::msg::ClockPubSubType::getKey().
getMaxCdrSerializedSize()
size_t rosgraph::msg::Clock::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 88 of file Clock.cpp.
References rosgraph_msg_Clock_max_cdr_typesize.
Referenced by rosgraph::msg::ClockPubSubType::ClockPubSubType().
isKeyDefined()
bool rosgraph::msg::Clock::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 165 of file Clock.cpp.
Referenced by rosgraph::msg::ClockPubSubType::ClockPubSubType().
operator!=()
bool rosgraph::msg::Clock::operator!= (const Clock & x) const
Comparison operator.
Parameters
x rosgraph::msg::Clock object to compare.
Definition at line 82 of file Clock.cpp.
operator=() [1/2]
rosgraph::msg::Clock & rosgraph::msg::Clock::operator= (const Clock & x)
Copy assignment.
Parameters
x Reference to the object rosgraph::msg::Clock that will be copied.
Definition at line 62 of file Clock.cpp.
References m_clock.
operator=() [2/2]
rosgraph::msg::Clock & rosgraph::msg::Clock::operator= (Clock && x) noexcept
Move assignment.
Parameters
x Reference to the object rosgraph::msg::Clock that will be copied.
Definition at line 69 of file Clock.cpp.
References m_clock.
operator==()
bool rosgraph::msg::Clock::operator== (const Clock & x) const
Comparison operator.
Parameters
x rosgraph::msg::Clock object to compare.
Definition at line 76 of file Clock.cpp.
References m_clock.
serialize()
void rosgraph::msg::Clock::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 108 of file Clock.cpp.
Referenced by rosgraph::msg::ClockPubSubType::serialize().
serializeKey()
void rosgraph::msg::Clock::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 170 of file Clock.cpp.
Referenced by rosgraph::msg::ClockPubSubType::getKey().
Member Data Documentation
m_clock
builtin_interfaces::msg::Time rosgraph::msg::Clock::m_clock private
Definition at line 209 of file Clock.h.
Referenced by Clock(), operator=(), and operator==().
The documentation for this class was generated from the following files:
Clock.h
Clock.cpp