CARLA: FVehicleActor Class Reference
FVehicleActor Class Reference
#include <CarlaActor.h>
Public Member Functions
virtual ECarlaServerResponse ApplyControlToVehicle (const FVehicleControl &, const EVehicleInputPriority &) final
virtual ECarlaServerResponse ApplyPhysicsControl (const FVehiclePhysicsControl &PhysicsControl) final
virtual ECarlaServerResponse DisableActorConstantVelocity () final
virtual ECarlaServerResponse EnableActorConstantVelocity (const FVector &Velocity) final
virtual ECarlaServerResponse EnableCarSim (const FString &SimfilePath) final
virtual ECarlaServerResponse EnableChronoPhysics (uint64_t MaxSubsteps, float MaxSubstepDeltaTime, const FString &VehicleJSON, const FString &PowertrainJSON, const FString &TireJSON, const FString &BaseJSONPath) final
FVehicleActor (IdType ActorId, AActor *Actor, TSharedPtr< const FActorInfo > Info, carla::rpc::ActorState InState, UWorld *World)
virtual ECarlaServerResponse GetPhysicsControl (FVehiclePhysicsControl &PhysicsControl) final
virtual ECarlaServerResponse GetVehicleControl (FVehicleControl &) final
virtual ECarlaServerResponse GetVehicleLightState (FVehicleLightState &LightState) final
virtual ECarlaServerResponse GetWheelSteerAngle (const EVehicleWheelLocation &WheelLocation, float &Angle)
virtual ECarlaServerResponse SetActorAutopilot (bool bEnabled, bool bKeepState=false) final
virtual ECarlaServerResponse SetActorSimulatePhysics (bool bSimulatePhysics) final
virtual ECarlaServerResponse SetVehicleLightState (const FVehicleLightState &LightState) final
virtual ECarlaServerResponse SetWheelSteerDirection (const EVehicleWheelLocation &WheelLocation, float AngleInDeg) final
virtual ECarlaServerResponse ShowVehicleDebugTelemetry (bool bEnabled) final
virtual ECarlaServerResponse UseCarSimRoad (bool bEnabled) final
Public Member Functions inherited from FCarlaActor
ECarlaServerResponse AddActorAngularImpulse (const FVector &AngularInpulse)
ECarlaServerResponse AddActorForce (const FVector &Force)
ECarlaServerResponse AddActorForceAtLocation (const FVector &Force, const FVector &Location)
ECarlaServerResponse AddActorImpulse (const FVector &Impulse)
ECarlaServerResponse AddActorImpulseAtLocation (const FVector &Impulse, const FVector &Location)
ECarlaServerResponse AddActorTorque (const FVector &Torque)
void AddChildren (IdType ChildId)
virtual ECarlaServerResponse ApplyBoneControlToWalker (const FWalkerBoneControl &)
virtual ECarlaServerResponse ApplyControlToWalker (const FWalkerControl &)
void BuildActorData ()
FCarlaActor ()=default
FCarlaActor (IdType ActorId, AActor *Actor, TSharedPtr< const FActorInfo > Info, carla::rpc::ActorState InState, UWorld *World)
virtual ECarlaServerResponse FreezeTrafficLight (bool)
AActor * GetActor ()
const AActor * GetActor () const
FVector GetActorAngularVelocity () const
FActorData * GetActorData ()
const FActorData * GetActorData () const
template<typename T >
T * GetActorData ()
template<typename T >
const T * GetActorData () const
FVector GetActorGlobalLocation () const
FTransform GetActorGlobalTransform () const
IdType GetActorId () const
const FActorInfo * GetActorInfo () const
FVector GetActorLocalLocation () const
FTransform GetActorLocalTransform () const
carla::rpc::ActorState GetActorState () const
ActorType GetActorType () const
FVector GetActorVelocity () const
carla::rpc::AttachmentType GetAttachmentType () const
const TArray< IdType > & GetChildren () const
IdType GetParent () const
virtual UTrafficLightController * GetTrafficLightController ()
virtual ETrafficLightState GetTrafficLightState () const
virtual ECarlaServerResponse GetWalkerControl (FWalkerControl &)
bool IsActive () const
bool IsAlive () const
bool IsDormant () const
bool IsInValid () const
bool IsPendingKill () const
void PutActorToSleep (UCarlaEpisode *CarlaEpisode)
void RemoveChildren (IdType ChildId)
virtual ECarlaServerResponse ResetTrafficLightGroup ()
virtual ECarlaServerResponse SetActorEnableGravity (bool bEnabled)
void SetActorGlobalLocation (const FVector &Location, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorGlobalTransform (const FTransform &Transform, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorLocalLocation (const FVector &Location, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorLocalTransform (const FTransform &Transform, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorState (carla::rpc::ActorState InState)
ECarlaServerResponse SetActorTargetAngularVelocity (const FVector &AngularVelocity)
ECarlaServerResponse SetActorTargetVelocity (const FVector &Velocity)
void SetAttachmentType (carla::rpc::AttachmentType InAttachmentType)
virtual ECarlaServerResponse SetLightGreenTime (float)
virtual ECarlaServerResponse SetLightRedTime (float)
virtual ECarlaServerResponse SetLightYellowTime (float)
void SetParent (IdType InParentId)
virtual ECarlaServerResponse SetTrafficLightState (const ETrafficLightState &)
virtual ECarlaServerResponse SetWalkerState (const FTransform &Transform, carla::rpc::WalkerControl WalkerControl)
void WakeActorUp (UCarlaEpisode *CarlaEpisode)
virtual ~FCarlaActor ()
Additional Inherited Members
Public Types inherited from FCarlaActor
enum ActorType : uint8 {
ActorType::Other, ActorType::Vehicle, ActorType::Walker, ActorType::TrafficLight,
ActorType::TrafficSign, ActorType::Sensor, ActorType::INVALID
}
using IdType = uint32
Static Public Member Functions inherited from FCarlaActor
static TSharedPtr< FCarlaActor > ConstructCarlaActor (IdType ActorId, AActor *Actor, TSharedPtr< const FActorInfo > Info, ActorType Type, carla::rpc::ActorState InState, UWorld *World)
Protected Attributes inherited from FCarlaActor
TSharedPtr< FActorData > ActorData = nullptr
ActorType Type = ActorType::INVALID
UWorld * World = nullptr
Detailed Description
Definition at line 413 of file CarlaActor.h.
Constructor & Destructor Documentation
FVehicleActor()
FVehicleActor::FVehicleActor (IdType ActorId, AActor * Actor, TSharedPtr< const FActorInfo > Info, carla::rpc::ActorState InState, UWorld * World)
Definition at line 50 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FCarlaActor::Type, and FCarlaActor::Vehicle.
Member Function Documentation
ApplyControlToVehicle()
ECarlaServerResponse FVehicleActor::ApplyControlToVehicle (const FVehicleControl & Control, const EVehicleInputPriority & Priority) final virtual
Reimplemented from FCarlaActor.
Definition at line 766 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FVehicleData::Control, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
ApplyPhysicsControl()
ECarlaServerResponse FVehicleActor::ApplyPhysicsControl (const FVehiclePhysicsControl & PhysicsControl) final virtual
Reimplemented from FCarlaActor.
Definition at line 670 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, FVehicleData::PhysicsControl, PhysicsControl, Success, and Vehicle.
DisableActorConstantVelocity()
ECarlaServerResponse FVehicleActor::DisableActorConstantVelocity () final virtual
Reimplemented from FCarlaActor.
Definition at line 614 of file CarlaActor.cpp.
References FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NullActor, and Success.
EnableActorConstantVelocity()
ECarlaServerResponse FVehicleActor::EnableActorConstantVelocity (const FVector & Velocity) final virtual
Reimplemented from FCarlaActor.
Definition at line 597 of file CarlaActor.cpp.
References FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NullActor, and Success.
EnableCarSim()
ECarlaServerResponse FVehicleActor::EnableCarSim (const FString & SimfilePath) final virtual
Reimplemented from FCarlaActor.
Definition at line 844 of file CarlaActor.cpp.
References UCarSimManagerComponent::CreateCarsimComponent(), FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
EnableChronoPhysics()
ECarlaServerResponse FVehicleActor::EnableChronoPhysics (uint64_t MaxSubsteps, float MaxSubstepDeltaTime, const FString & VehicleJSON, const FString & PowertrainJSON, const FString & TireJSON, const FString & BaseJSONPath) final virtual
Reimplemented from FCarlaActor.
Definition at line 886 of file CarlaActor.cpp.
References UChronoMovementComponent::CreateChronoMovementComponent(), FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
GetPhysicsControl()
ECarlaServerResponse FVehicleActor::GetPhysicsControl (FVehiclePhysicsControl & PhysicsControl) final virtual
Reimplemented from FCarlaActor.
Definition at line 631 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, FVehicleData::PhysicsControl, Success, and Vehicle.
GetVehicleControl()
ECarlaServerResponse FVehicleActor::GetVehicleControl (FVehicleControl & VehicleControl) final virtual
Reimplemented from FCarlaActor.
Definition at line 786 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FVehicleData::Control, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
GetVehicleLightState()
ECarlaServerResponse FVehicleActor::GetVehicleLightState (FVehicleLightState & LightState) final virtual
Reimplemented from FCarlaActor.
Definition at line 650 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), FVehicleData::LightState, NotAVehicle, Success, and Vehicle.
GetWheelSteerAngle()
ECarlaServerResponse FVehicleActor::GetWheelSteerAngle (const EVehicleWheelLocation & WheelLocation, float & Angle) virtual
Reimplemented from FCarlaActor.
Definition at line 729 of file CarlaActor.cpp.
References FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
SetActorAutopilot()
ECarlaServerResponse FVehicleActor::SetActorAutopilot (bool bEnabled, bool bKeepState = false) final virtual
Reimplemented from FCarlaActor.
Definition at line 805 of file CarlaActor.cpp.
References AutoPilotNotSupported, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), Success, and Vehicle.
SetActorSimulatePhysics()
ECarlaServerResponse FVehicleActor::SetActorSimulatePhysics (bool bSimulatePhysics) final virtual
Reimplemented from FCarlaActor.
Definition at line 748 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, and Success.
SetVehicleLightState()
ECarlaServerResponse FVehicleActor::SetVehicleLightState (const FVehicleLightState & LightState) final virtual
Reimplemented from FCarlaActor.
Definition at line 691 of file CarlaActor.cpp.
References FCarlaActor::ActorData, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), FVehicleData::LightState, NotAVehicle, Success, and Vehicle.
SetWheelSteerDirection()
ECarlaServerResponse FVehicleActor::SetWheelSteerDirection (const EVehicleWheelLocation & WheelLocation, float AngleInDeg) final virtual
Reimplemented from FCarlaActor.
Definition at line 712 of file CarlaActor.cpp.
References FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
ShowVehicleDebugTelemetry()
ECarlaServerResponse FVehicleActor::ShowVehicleDebugTelemetry (bool bEnabled) final virtual
Reimplemented from FCarlaActor.
Definition at line 827 of file CarlaActor.cpp.
References FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, and Vehicle.
UseCarSimRoad()
ECarlaServerResponse FVehicleActor::UseCarSimRoad (bool bEnabled) final virtual
Reimplemented from FCarlaActor.
Definition at line 861 of file CarlaActor.cpp.
References CarSimPluginNotEnabled, FCarlaActor::GetActor(), FCarlaActor::IsDormant(), NotAVehicle, Success, UCarSimManagerComponent::UseCarSimRoad(), and Vehicle.
The documentation for this class was generated from the following files:
CarlaActor.h
CarlaActor.cpp