CARLA: moodycamel::details Namespace Reference
moodycamel::details Namespace Reference
Classes
struct _hash_32_or_64
struct _hash_32_or_64< 1 >
struct ConcurrentQueueProducerTypelessBase
struct const_numeric_max
struct hash_32_or_64
struct is_trivially_destructible
union max_align_t
struct nomove_if
struct nomove_if< false >
struct static_is_lock_free
struct static_is_lock_free< bool >
struct static_is_lock_free< U * >
struct static_is_lock_free_num
struct static_is_lock_free_num< int >
struct static_is_lock_free_num< long >
struct static_is_lock_free_num< long long >
struct static_is_lock_free_num< short >
struct static_is_lock_free_num< signed char >
struct thread_id_converter
Typedefs
typedef std::max_align_t std_max_align_t
typedef std::uintptr_t thread_id_t
Functions
template<typename U >
static char * align_for (char *ptr)
template<typename T >
static T ceil_to_pow_2 (T x)
template<typename T >
static bool circular_less_than (T a, T b)
template<typename It >
static auto deref_noexcept (It &it) MOODYCAMEL_NOEXCEPT-> decltype(*it)
static size_t hash_thread_id (thread_id_t id)
static bool() likely (bool x)
template<typename T >
static T const & nomove (T const &x)
template<typename T >
static void swap_relaxed (std::atomic< T > &left, std::atomic< T > &right)
static thread_id_t thread_id ()
static bool() unlikely (bool x)
Variables
static const thread_id_t invalid_thread_id = 0
static const thread_id_t invalid_thread_id2 = 1
Typedef Documentation
typedef std::max_align_t moodycamel::details::std_max_align_t
Definition at line 257 of file ConcurrentQueue.h.
typedef std::uintptr_t moodycamel::details::thread_id_t
Definition at line 147 of file ConcurrentQueue.h.
Function Documentation
template<typename U > static char* moodycamel::details::align_for (char * ptr) inline static
Definition at line 432 of file ConcurrentQueue.h.
template<typename T > static T moodycamel::details::ceil_to_pow_2 (T x) inline static
Definition at line 439 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< T, Traits >::ExplicitProducer::ExplicitProducer().
template<typename T > static bool moodycamel::details::circular_less_than (T a, T b) inline static
Definition at line 418 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< T, Traits >::ProducerBase::size_approx(), and moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducer::~ImplicitProducer().
template<typename It > static auto moodycamel::details::deref_noexcept (It & it) -> decltype(*it) inline static
Definition at line 491 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< T, Traits >::ExplicitProducer::dequeue_bulk(), moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducer::dequeue_bulk(), moodycamel::ConcurrentQueue< T, Traits >::ExplicitProducer::enqueue_bulk(), and moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducer::enqueue_bulk().
static size_t moodycamel::details::hash_thread_id (thread_id_t id) inline static
Definition at line 410 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< carla::Buffer >::get_or_add_implicit_producer().
static bool() moodycamel::details::likely (bool x) inline static
Definition at line 235 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< T, Traits >::ExplicitProducer::dequeue(), moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducer::dequeue(), and moodycamel::ConcurrentQueue< carla::Buffer >::try_dequeue().
template<typename T > static T const& moodycamel::details::nomove (T const & x) inline static
Definition at line 464 of file ConcurrentQueue.h.
template<typename T > static void moodycamel::details::swap_relaxed (std::atomic< T > & left, std::atomic< T > & right) inline static
Definition at line 456 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< T, Traits >::FreeList< moodycamel::ConcurrentQueue::Block >::swap(), moodycamel::ConcurrentQueue< T, Traits >::ImplicitProducerKVP::swap(), moodycamel::ConcurrentQueue< carla::Buffer >::swap_implicit_producer_hashes(), and moodycamel::ConcurrentQueue< carla::Buffer >::swap_internal().
static thread_id_t moodycamel::details::thread_id () inline static
Definition at line 150 of file ConcurrentQueue.h.
References MOODYCAMEL_THREADLOCAL.
Referenced by moodycamel::ConcurrentQueue< carla::Buffer >::get_or_add_implicit_producer(), and moodycamel::details::thread_id_converter< thread_id_t >::prehash().
static bool() moodycamel::details::unlikely (bool x) inline static
Definition at line 236 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< carla::Buffer >::update_current_producer_after_rotation().
Variable Documentation
const thread_id_t moodycamel::details::invalid_thread_id = 0 static
Definition at line 148 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< carla::Buffer >::get_or_add_implicit_producer(), moodycamel::ConcurrentQueue< carla::Buffer >::populate_initial_implicit_producer_hash(), and moodycamel::details::thread_id_converter< thread_id_t >::prehash().
const thread_id_t moodycamel::details::invalid_thread_id2 = 1 static
Definition at line 149 of file ConcurrentQueue.h.
Referenced by moodycamel::ConcurrentQueue< carla::Buffer >::get_or_add_implicit_producer(), and moodycamel::details::thread_id_converter< thread_id_t >::prehash().