CARLA: geometry_msgs::msg::TransformStamped Class Reference
geometry_msgs::msg::TransformStamped Class Reference
This class represents the structure TransformStamped defined by the user in the IDL file.
#include <TransformStamped.h>
Public Member Functions
eProsima_user_DllExport std::string & child_frame_id ()
This function returns a reference to member child_frame_id.
const eProsima_user_DllExport std::string & child_frame_id () const
This function returns a constant reference to member child_frame_id.
eProsima_user_DllExport void child_frame_id (const std::string &_child_frame_id)
This function copies the value in member child_frame_id.
eProsima_user_DllExport void child_frame_id (std::string &&_child_frame_id)
This function moves the value in member child_frame_id.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport std_msgs::msg::Header & header ()
This function returns a reference to member header.
const eProsima_user_DllExport std_msgs::msg::Header & header () const
This function returns a constant reference to member header.
eProsima_user_DllExport void header (const std_msgs::msg::Header &_header)
This function copies the value in member header.
eProsima_user_DllExport void header (std_msgs::msg::Header &&_header)
This function moves the value in member header.
eProsima_user_DllExport bool operator!= (const TransformStamped &x) const
Comparison operator.
eProsima_user_DllExport TransformStamped & operator= (const TransformStamped &x)
Copy assignment.
eProsima_user_DllExport TransformStamped & operator= (TransformStamped &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const TransformStamped &x) const
Comparison operator.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport geometry_msgs::msg::Transform & transform ()
This function returns a reference to member transform.
const eProsima_user_DllExport geometry_msgs::msg::Transform & transform () const
This function returns a constant reference to member transform.
eProsima_user_DllExport void transform (const geometry_msgs::msg::Transform &_transform)
This function copies the value in member transform.
eProsima_user_DllExport void transform (geometry_msgs::msg::Transform &&_transform)
This function moves the value in member transform.
eProsima_user_DllExport TransformStamped ()
Default constructor.
eProsima_user_DllExport TransformStamped (const TransformStamped &x)
Copy constructor.
eProsima_user_DllExport TransformStamped (TransformStamped &&x) noexcept
Move constructor.
eProsima_user_DllExport ~TransformStamped ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::TransformStamped &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
std::string m_child_frame_id
std_msgs::msg::Header m_header
geometry_msgs::msg::Transform m_transform
Detailed Description
This class represents the structure TransformStamped defined by the user in the IDL file.
Definition at line 73 of file TransformStamped.h.
Constructor & Destructor Documentation
TransformStamped() [1/3]
geometry_msgs::msg::TransformStamped::TransformStamped ()
Default constructor.
Definition at line 50 of file TransformStamped.cpp.
~TransformStamped()
geometry_msgs::msg::TransformStamped::~TransformStamped ()
Default destructor.
Definition at line 59 of file TransformStamped.cpp.
TransformStamped() [2/3]
geometry_msgs::msg::TransformStamped::TransformStamped (const TransformStamped & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::TransformStamped that will be copied.
Definition at line 63 of file TransformStamped.cpp.
References m_child_frame_id, m_header, and m_transform.
TransformStamped() [3/3]
geometry_msgs::msg::TransformStamped::TransformStamped (TransformStamped && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::TransformStamped that will be copied.
Definition at line 71 of file TransformStamped.cpp.
Member Function Documentation
child_frame_id() [1/4]
eProsima_user_DllExport std::string& geometry_msgs::msg::TransformStamped::child_frame_id ()
This function returns a reference to member child_frame_id.
Returns
Reference to member child_frame_id
child_frame_id() [2/4]
std::string & geometry_msgs::msg::TransformStamped::child_frame_id () const
This function returns a constant reference to member child_frame_id.
This function returns a reference to member child_frame_id.
Returns
Constant reference to member child_frame_id
Reference to member child_frame_id
Definition at line 208 of file TransformStamped.cpp.
child_frame_id() [3/4]
void geometry_msgs::msg::TransformStamped::child_frame_id (const std::string & _child_frame_id)
This function copies the value in member child_frame_id.
Parameters
_child_frame_id New value to be copied in member child_frame_id
Definition at line 188 of file TransformStamped.cpp.
Referenced by getCdrSerializedSize(), and carla::ros2::CarlaTransformPublisher::SetData().
child_frame_id() [4/4]
void geometry_msgs::msg::TransformStamped::child_frame_id (std::string && _child_frame_id)
This function moves the value in member child_frame_id.
Parameters
_child_frame_id New value to be moved in member child_frame_id
Definition at line 198 of file TransformStamped.cpp.
deserialize()
void geometry_msgs::msg::TransformStamped::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 138 of file TransformStamped.cpp.
Referenced by geometry_msgs::msg::TransformStampedPubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::TransformStamped::getCdrSerializedSize (const geometry_msgs::msg::TransformStamped & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 118 of file TransformStamped.cpp.
References child_frame_id(), std_msgs::msg::Header::getCdrSerializedSize(), geometry_msgs::msg::Transform::getCdrSerializedSize(), header(), and transform().
Referenced by tf2_msgs::msg::TFMessage::getCdrSerializedSize(), and geometry_msgs::msg::TransformStampedPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::TransformStamped::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 260 of file TransformStamped.cpp.
References geometry_msgs_msg_TransformStamped_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::TransformStampedPubSubType::getKey(), and geometry_msgs::msg::TransformStampedPubSubType::TransformStampedPubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::TransformStamped::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 111 of file TransformStamped.cpp.
References geometry_msgs_msg_TransformStamped_max_cdr_typesize.
Referenced by geometry_msgs::msg::TransformStampedPubSubType::TransformStampedPubSubType().
header() [1/4]
eProsima_user_DllExport std_msgs::msg::Header& geometry_msgs::msg::TransformStamped::header ()
This function returns a reference to member header.
Returns
Reference to member header
header() [2/4]
std_msgs::msg::Header & geometry_msgs::msg::TransformStamped::header () const
This function returns a constant reference to member header.
This function returns a reference to member header.
Returns
Constant reference to member header
Reference to member header
Definition at line 170 of file TransformStamped.cpp.
header() [3/4]
void geometry_msgs::msg::TransformStamped::header (const std_msgs::msg::Header & _header)
This function copies the value in member header.
Parameters
_header New value to be copied in member header
Definition at line 150 of file TransformStamped.cpp.
Referenced by getCdrSerializedSize(), and carla::ros2::CarlaTransformPublisher::SetData().
header() [4/4]
void geometry_msgs::msg::TransformStamped::header (std_msgs::msg::Header && _header)
This function moves the value in member header.
Parameters
_header New value to be moved in member header
Definition at line 160 of file TransformStamped.cpp.
isKeyDefined()
bool geometry_msgs::msg::TransformStamped::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 267 of file TransformStamped.cpp.
Referenced by geometry_msgs::msg::TransformStampedPubSubType::TransformStampedPubSubType().
operator!=()
bool geometry_msgs::msg::TransformStamped::operator!= (const TransformStamped & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::TransformStamped object to compare.
Definition at line 105 of file TransformStamped.cpp.
operator=() [1/2]
geometry_msgs::msg::TransformStamped & geometry_msgs::msg::TransformStamped::operator= (const TransformStamped & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::TransformStamped that will be copied.
Definition at line 79 of file TransformStamped.cpp.
References m_child_frame_id, m_header, and m_transform.
operator=() [2/2]
geometry_msgs::msg::TransformStamped & geometry_msgs::msg::TransformStamped::operator= (TransformStamped && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::TransformStamped that will be copied.
Definition at line 89 of file TransformStamped.cpp.
operator==()
bool geometry_msgs::msg::TransformStamped::operator== (const TransformStamped & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::TransformStamped object to compare.
Definition at line 99 of file TransformStamped.cpp.
References m_child_frame_id, m_header, and m_transform.
serialize()
void geometry_msgs::msg::TransformStamped::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 130 of file TransformStamped.cpp.
Referenced by geometry_msgs::msg::TransformStampedPubSubType::serialize().
serializeKey()
void geometry_msgs::msg::TransformStamped::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 272 of file TransformStamped.cpp.
Referenced by geometry_msgs::msg::TransformStampedPubSubType::getKey().
transform() [1/4]
eProsima_user_DllExport geometry_msgs::msg::Transform& geometry_msgs::msg::TransformStamped::transform ()
This function returns a reference to member transform.
Returns
Reference to member transform
transform() [2/4]
geometry_msgs::msg::Transform & geometry_msgs::msg::TransformStamped::transform () const
This function returns a constant reference to member transform.
This function returns a reference to member transform.
Returns
Constant reference to member transform
Reference to member transform
Definition at line 246 of file TransformStamped.cpp.
transform() [3/4]
void geometry_msgs::msg::TransformStamped::transform (const geometry_msgs::msg::Transform & _transform)
This function copies the value in member transform.
Parameters
_transform New value to be copied in member transform
Definition at line 226 of file TransformStamped.cpp.
Referenced by getCdrSerializedSize(), and carla::ros2::CarlaTransformPublisher::SetData().
transform() [4/4]
void geometry_msgs::msg::TransformStamped::transform (geometry_msgs::msg::Transform && _transform)
This function moves the value in member transform.
Parameters
_transform New value to be moved in member transform
Definition at line 236 of file TransformStamped.cpp.
Member Data Documentation
m_child_frame_id
std::string geometry_msgs::msg::TransformStamped::m_child_frame_id private
Definition at line 261 of file TransformStamped.h.
Referenced by operator=(), operator==(), and TransformStamped().
m_header
std_msgs::msg::Header geometry_msgs::msg::TransformStamped::m_header private
Definition at line 260 of file TransformStamped.h.
Referenced by operator=(), operator==(), and TransformStamped().
m_transform
geometry_msgs::msg::Transform geometry_msgs::msg::TransformStamped::m_transform private
Definition at line 262 of file TransformStamped.h.
Referenced by operator=(), operator==(), and TransformStamped().
The documentation for this class was generated from the following files:
TransformStamped.h
TransformStamped.cpp