CARLA: UActorDispatcher Class Reference
UActorDispatcher Class Reference
Object in charge of binding ActorDefinitions to spawn functions, as well as keeping the registry of all the actors spawned.
#include <ActorDispatcher.h>
Public Types
using SpawnFunctionType = TFunction< FActorSpawnResult(const FTransform &, const FActorDescription &)>
Public Member Functions
void Bind (FActorDefinition Definition, SpawnFunctionType SpawnFunction)
Bind a definition to a spawn function.
void Bind (ACarlaActorFactory &ActorFactory)
Bind all the definitions of ActorFactory to its spawn function.
bool DestroyActor (AActor *Actor)
Destroys an actor, properly removing it from the registry.
const TArray< FActorDefinition > & GetActorDefinitions () const
const FActorRegistry & GetActorRegistry () const
FActorView RegisterActor (AActor &Actor, FActorDescription ActorDescription, FActorRegistry::IdType DesiredId=0)
Register an actor that was not created using "SpawnActor" function but that should be kept in the registry.
TPair< EActorSpawnResultStatus, FActorView > SpawnActor (const FTransform &Transform, FActorDescription ActorDescription, FActorView::IdType DesiredId=0)
Spawns an actor based on ActorDescription at Transform.
Private Member Functions
void OnActorDestroyed (AActor *Actor)
Private Attributes
TArray< TSubclassOf< AActor > > Classes
TArray< FActorDefinition > Definitions
FActorRegistry Registry
TArray< SpawnFunctionType > SpawnFunctions
Detailed Description
Object in charge of binding ActorDefinitions to spawn functions, as well as keeping the registry of all the actors spawned.
Definition at line 24 of file ActorDispatcher.h.
Member Typedef Documentation
SpawnFunctionType
using UActorDispatcher::SpawnFunctionType = TFunction<FActorSpawnResult(const FTransform &, const FActorDescription &)>
Definition at line 30 of file ActorDispatcher.h.
Member Function Documentation
Bind() [1/2]
void UActorDispatcher::Bind (FActorDefinition Definition, SpawnFunctionType SpawnFunction)
Bind a definition to a spawn function.
When SpawnActor is called with a matching description Functor is called.
Warning
Invalid definitions are ignored.
Definition at line 17 of file ActorDispatcher.cpp.
References UActorBlueprintFunctionLibrary::CheckActorDefinition(), FActorDefinition::Class, Classes, Definitions, FActorDefinition::Id, SpawnFunctions, and FActorDefinition::UId.
Referenced by Bind().
Bind() [2/2]
void UActorDispatcher::Bind (ACarlaActorFactory & ActorFactory)
Bind all the definitions of ActorFactory to its spawn function.
Warning
Invalid definitions are ignored.
Definition at line 32 of file ActorDispatcher.cpp.
References Bind(), ACarlaActorFactory::GetDefinitions(), and ACarlaActorFactory::SpawnActor().
DestroyActor()
bool UActorDispatcher::DestroyActor (AActor * Actor)
Destroys an actor, properly removing it from the registry.
Return true if the Actor is destroyed or already marked for destruction, false if indestructible or nullptr.
Definition at line 80 of file ActorDispatcher.cpp.
References FActorRegistry::Find(), and Registry.
GetActorDefinitions()
const TArray<FActorDefinition>& UActorDispatcher::GetActorDefinitions () const inline
Definition at line 64 of file ActorDispatcher.h.
GetActorRegistry()
const FActorRegistry& UActorDispatcher::GetActorRegistry () const inline
Definition at line 69 of file ActorDispatcher.h.
OnActorDestroyed()
void UActorDispatcher::OnActorDestroyed (AActor * Actor) inline private
Definition at line 77 of file ActorDispatcher.h.
References FActorRegistry::Deregister().
Referenced by RegisterActor().
RegisterActor()
FActorView UActorDispatcher::RegisterActor (AActor & Actor, FActorDescription ActorDescription, FActorRegistry::IdType DesiredId = 0)
Register an actor that was not created using "SpawnActor" function but that should be kept in the registry.
Definition at line 118 of file ActorDispatcher.cpp.
References OnActorDestroyed(), FActorRegistry::Register(), and Registry.
Referenced by UCarlaEpisode::InitializeAtBeginPlay(), and SpawnActor().
SpawnActor()
TPair< EActorSpawnResultStatus, FActorView > UActorDispatcher::SpawnActor (const FTransform & Transform, FActorDescription ActorDescription, FActorView::IdType DesiredId = 0)
Spawns an actor based on ActorDescription at Transform.
To properly despawn an actor created with this function call DestroyActor.
Returns
A pair containing the result of the spawn function and a view over the actor and its properties. If the status is different of Success the view is invalid.
Definition at line 42 of file ActorDispatcher.cpp.
References FActorDescription::Class, Classes, FActorDescription::Id, RegisterActor(), SpawnFunctions, ATagger::TagActor(), and FActorDescription::UId.
Member Data Documentation
Classes
TArray<TSubclassOf<AActor> > UActorDispatcher::Classes private
Definition at line 86 of file ActorDispatcher.h.
Referenced by Bind(), and SpawnActor().
Definitions
TArray<FActorDefinition> UActorDispatcher::Definitions private
Definition at line 82 of file ActorDispatcher.h.
Referenced by Bind().
Registry
FActorRegistry UActorDispatcher::Registry private
Definition at line 88 of file ActorDispatcher.h.
Referenced by DestroyActor(), and RegisterActor().
SpawnFunctions
TArray<SpawnFunctionType> UActorDispatcher::SpawnFunctions private
Definition at line 84 of file ActorDispatcher.h.
Referenced by Bind(), and SpawnActor().
The documentation for this class was generated from the following files:
ActorDispatcher.h
ActorDispatcher.cpp