CARLA: std_msgs::msg::StringPubSubType Class Reference
std_msgs::msg::StringPubSubType Class Reference
This class represents the TopicDataType of the type String defined by the user in the IDL file.
#include <StringPubSubTypes.h>
Public Types
typedef String type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport StringPubSubType ()
virtual eProsima_user_DllExport ~StringPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type String defined by the user in the IDL file.
Definition at line 44 of file StringPubSubTypes.h.
Member Typedef Documentation
type
typedef String std_msgs::msg::StringPubSubType::type
Definition at line 48 of file StringPubSubTypes.h.
Constructor & Destructor Documentation
StringPubSubType()
std_msgs::msg::StringPubSubType::StringPubSubType ()
Definition at line 32 of file StringPubSubTypes.cpp.
References std_msgs::msg::String::getKeyMaxCdrSerializedSize(), std_msgs::msg::String::getMaxCdrSerializedSize(), std_msgs::msg::String::isKeyDefined(), and m_keyBuffer.
~StringPubSubType()
std_msgs::msg::StringPubSubType::~StringPubSubType () override virtual
Definition at line 45 of file StringPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * std_msgs::msg::StringPubSubType::createData () override virtual
Definition at line 122 of file StringPubSubTypes.cpp.
deleteData()
void std_msgs::msg::StringPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file StringPubSubTypes.cpp.
deserialize()
bool std_msgs::msg::StringPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file StringPubSubTypes.cpp.
References std_msgs::msg::String::deserialize().
getKey()
bool std_msgs::msg::StringPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file StringPubSubTypes.cpp.
References std_msgs::msg::String::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and std_msgs::msg::String::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> std_msgs::msg::StringPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file StringPubSubTypes.cpp.
References std_msgs::msg::String::getCdrSerializedSize().
serialize()
bool std_msgs::msg::StringPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file StringPubSubTypes.cpp.
References std_msgs::msg::String::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* std_msgs::msg::StringPubSubType::m_keyBuffer
Definition at line 101 of file StringPubSubTypes.h.
Referenced by getKey(), StringPubSubType(), and ~StringPubSubType().
m_md5
MD5 std_msgs::msg::StringPubSubType::m_md5
Definition at line 100 of file StringPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
StringPubSubTypes.h
StringPubSubTypes.cpp