CARLA: PropAttributes Namespace Reference
PropAttributes Namespace Reference
Variables
static const FString MESH_PATH = TEXT("path")
static const FString NAME = TEXT("name")
static const FString REGISTRY_FORMAT = TEXT(".Package.json")
static const FString SIZE = TEXT("size")
Variable Documentation
const FString PropAttributes::MESH_PATH = TEXT("path") static
Definition at line 25 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), and UCarlaBlueprintRegistry::LoadPropDefinitions().
const FString PropAttributes::NAME = TEXT("name") static
Definition at line 24 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), and UCarlaBlueprintRegistry::LoadPropDefinitions().
const FString PropAttributes::REGISTRY_FORMAT = TEXT(".Package.json") static
Definition at line 23 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), and UCarlaBlueprintRegistry::LoadPropDefinitions().
const FString PropAttributes::SIZE = TEXT("size") static
Definition at line 26 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), carla::sensor::s11n::LidarSerializer::GetHeaderOffset(), carla::sensor::s11n::LidarHeaderView::GetPointCount(), FActorDefinitionValidator::IsValid(), UCarlaBlueprintRegistry::LoadPropDefinitions(), carla::sensor::s11n::LidarMeasurement::Reset(), FActorSpawnResult::StatusToString(), and carla::sensor::s11n::LidarMeasurement::WritePoint().