CARLA: UBaseCarlaMovementComponent Class Reference
UBaseCarlaMovementComponent Class Reference
#include <BaseCarlaMovementComponent.h>
Public Member Functions
virtual void BeginPlay () override
virtual int32 GetVehicleCurrentGear () const
virtual float GetVehicleForwardSpeed () const
virtual FVector GetVelocity () const
virtual void ProcessControl (FVehicleControl &Control)
Protected Member Functions
void DisableUE4VehiclePhysics ()
void EnableUE4VehiclePhysics (bool bResetVelocity=true)
Protected Attributes
ACarlaWheeledVehicle * CarlaVehicle
Detailed Description
Definition at line 17 of file BaseCarlaMovementComponent.h.
Member Function Documentation
BeginPlay()
void UBaseCarlaMovementComponent::BeginPlay () override virtual
Reimplemented in UCarSimManagerComponent, and UDefaultMovementComponent.
Definition at line 15 of file BaseCarlaMovementComponent.cpp.
References CarlaVehicle, and Vehicle.
Referenced by UChronoMovementComponent::CreateChronoMovementComponent().
DisableUE4VehiclePhysics()
void UBaseCarlaMovementComponent::DisableUE4VehiclePhysics () protected
Definition at line 53 of file BaseCarlaMovementComponent.cpp.
References CarlaVehicle.
Referenced by UChronoMovementComponent::CreateChronoMovementComponent().
EnableUE4VehiclePhysics()
void UBaseCarlaMovementComponent::EnableUE4VehiclePhysics (bool bResetVelocity = true) protected
Definition at line 70 of file BaseCarlaMovementComponent.cpp.
References CarlaVehicle, GetVelocity(), carla::log_warning(), and ACarlaWheeledVehicle::RestoreVehiclePhysicsControl().
Referenced by UChronoMovementComponent::DisableChronoPhysics().
GetVehicleCurrentGear()
int32 UBaseCarlaMovementComponent::GetVehicleCurrentGear () const virtual
Reimplemented in UCarSimManagerComponent, and UDefaultMovementComponent.
Definition at line 43 of file BaseCarlaMovementComponent.cpp.
Referenced by UChronoMovementComponent::CreateChronoMovementComponent(), and ACarlaWheeledVehicle::GetVehicleCurrentGear().
GetVehicleForwardSpeed()
float UBaseCarlaMovementComponent::GetVehicleForwardSpeed () const virtual
Reimplemented in UCarSimManagerComponent, and UDefaultMovementComponent.
Definition at line 48 of file BaseCarlaMovementComponent.cpp.
Referenced by UChronoMovementComponent::CreateChronoMovementComponent(), and ACarlaWheeledVehicle::GetVehicleForwardSpeed().
GetVelocity()
FVector UBaseCarlaMovementComponent::GetVelocity () const virtual
Reimplemented in UCarSimManagerComponent.
Definition at line 34 of file BaseCarlaMovementComponent.cpp.
References CarlaVehicle.
Referenced by UChronoMovementComponent::CreateChronoMovementComponent(), EnableUE4VehiclePhysics(), and ACarlaWheeledVehicle::GetVelocity().
ProcessControl()
void UBaseCarlaMovementComponent::ProcessControl (FVehicleControl & Control) virtual
Reimplemented in UCarSimManagerComponent, and UDefaultMovementComponent.
Definition at line 29 of file BaseCarlaMovementComponent.cpp.
Referenced by UChronoMovementComponent::CreateChronoMovementComponent(), and ACarlaWheeledVehicle::FlushVehicleControl().
Member Data Documentation
CarlaVehicle
ACarlaWheeledVehicle* UBaseCarlaMovementComponent::CarlaVehicle protected
Definition at line 24 of file BaseCarlaMovementComponent.h.
Referenced by BeginPlay(), UCarSimManagerComponent::BeginPlay(), UChronoMovementComponent::CreateChronoMovementComponent(), UChronoMovementComponent::DisableChronoPhysics(), DisableUE4VehiclePhysics(), EnableUE4VehiclePhysics(), UCarSimManagerComponent::EndPlay(), UDefaultMovementComponent::GetVehicleCurrentGear(), UDefaultMovementComponent::GetVehicleForwardSpeed(), GetVelocity(), UCarSimManagerComponent::OnCarSimHit(), UCarSimManagerComponent::OnCarSimOverlap(), and UDefaultMovementComponent::ProcessControl().
The documentation for this class was generated from the following files:
BaseCarlaMovementComponent.h
BaseCarlaMovementComponent.cpp