CARLA: carla::client::Waypoint Class Reference
carla::client::Waypoint Class Reference
#include <Waypoint.h>
Public Member Functions
std::vector< SharedPtr< Landmark > > GetAllLandmakrsInDistance (double distance, bool stop_at_junction=false) const
Returns a list of landmarks from the current position to a certain distance.
auto GetDistance () const
uint64_t GetId () const
Returns an unique Id identifying this waypoint.
SharedPtr< Junction > GetJunction () const
road::JuncId GetJunctionId () const
std::vector< SharedPtr< Landmark > > GetLandmakrsOfTypeInDistance (double distance, std::string filter_type, bool stop_at_junction=false) const
Returns a list of landmarks from the current position to a certain distance Filters by specified type.
road::element::LaneMarking::LaneChange GetLaneChange () const
auto GetLaneId () const
double GetLaneWidth () const
SharedPtr< Waypoint > GetLeft () const
boost::optional< road::element::LaneMarking > GetLeftLaneMarking () const
std::vector< SharedPtr< Waypoint > > GetNext (double distance) const
std::vector< SharedPtr< Waypoint > > GetNextUntilLaneEnd (double distance) const
Returns a list of waypoints separated by distance from the current waypoint to the end of the lane.
std::vector< SharedPtr< Waypoint > > GetPrevious (double distance) const
std::vector< SharedPtr< Waypoint > > GetPreviousUntilLaneStart (double distance) const
Returns a list of waypoints separated by distance from the current waypoint to the start of the lane.
SharedPtr< Waypoint > GetRight () const
boost::optional< road::element::LaneMarking > GetRightLaneMarking () const
auto GetRoadId () const
auto GetSectionId () const
const geom::Transform & GetTransform () const
road::Lane::LaneType GetType () const
bool IsJunction () const
~Waypoint ()
Private Member Functions
Waypoint (SharedPtr< const Map > parent, road::element::Waypoint waypoint)
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Private Attributes
std::pair< const road::element::RoadInfoMarkRecord *, const road::element::RoadInfoMarkRecord * > _mark_record
SharedPtr< const Map > _parent
geom::Transform _transform
road::element::Waypoint _waypoint
Friends
class Map
Detailed Description
Definition at line 27 of file client/Waypoint.h.
Constructor & Destructor Documentation
carla::client::Waypoint::~Waypoint () default
Referenced by Waypoint().
carla::client::Waypoint::Waypoint (SharedPtr< const Map > parent, road::element::Waypoint waypoint) private
Definition at line 18 of file client/Waypoint.cpp.
References ~Waypoint().
Referenced by GetAllLandmakrsInDistance(), GetLandmakrsOfTypeInDistance(), GetLeft(), GetNext(), GetPrevious(), and GetRight().
Member Function Documentation
std::vector< SharedPtr< Landmark > > carla::client::Waypoint::GetAllLandmakrsInDistance (double distance, bool stop_at_junction = false) const
Returns a list of landmarks from the current position to a certain distance.
Definition at line 210 of file client/Waypoint.cpp.
References _parent, _waypoint, and Waypoint().
Referenced by GetTransform().
auto carla::client::Waypoint::GetDistance () const inline
Definition at line 54 of file client/Waypoint.h.
References _waypoint, and carla::road::element::Waypoint::s.
Referenced by GetNextUntilLaneEnd(), and GetPreviousUntilLaneStart().
uint64_t carla::client::Waypoint::GetId () const inline
Returns an unique Id identifying this waypoint.
The Id takes into account OpenDrive's road Id, lane Id, and s distance on its road segment up to half-centimetre precision.
Definition at line 38 of file client/Waypoint.h.
References _waypoint.
SharedPtr< Junction > carla::client::Waypoint::GetJunction () const
Definition at line 34 of file client/Waypoint.cpp.
References _parent, and IsJunction().
Referenced by GetTransform().
road::JuncId carla::client::Waypoint::GetJunctionId () const
Definition at line 26 of file client/Waypoint.cpp.
References _parent, _waypoint, and carla::road::element::Waypoint::road_id.
Referenced by carla::client::Map::GetJunction(), and GetTransform().
std::vector< SharedPtr< Landmark > > carla::client::Waypoint::GetLandmakrsOfTypeInDistance (double distance, std::string filter_type, bool stop_at_junction = false) const
Returns a list of landmarks from the current position to a certain distance Filters by specified type.
Definition at line 228 of file client/Waypoint.cpp.
References _parent, _waypoint, and Waypoint().
Referenced by GetTransform().
road::element::LaneMarking::LaneChange carla::client::Waypoint::GetLaneChange () const
Definition at line 168 of file client/Waypoint.cpp.
References _mark_record, _waypoint, carla::road::Both, and carla::road::element::Waypoint::lane_id.
Referenced by GetTransform().
auto carla::client::Waypoint::GetLaneId () const inline
Definition at line 50 of file client/Waypoint.h.
References _waypoint, and carla::road::element::Waypoint::lane_id.
double carla::client::Waypoint::GetLaneWidth () const
Definition at line 41 of file client/Waypoint.cpp.
References _parent, and _waypoint.
Referenced by GetTransform().
SharedPtr< Waypoint > carla::client::Waypoint::GetLeft () const
Definition at line 131 of file client/Waypoint.cpp.
References _parent, _waypoint, and Waypoint().
Referenced by GetTransform().
boost::optional< road::element::LaneMarking > carla::client::Waypoint::GetLeftLaneMarking () const
Definition at line 147 of file client/Waypoint.cpp.
References _mark_record.
Referenced by GetTransform().
std::vector< SharedPtr< Waypoint > > carla::client::Waypoint::GetNext (double distance) const
Definition at line 50 of file client/Waypoint.cpp.
References _parent, _waypoint, and Waypoint().
Referenced by GetNextUntilLaneEnd(), and GetTransform().
std::vector< SharedPtr< Waypoint > > carla::client::Waypoint::GetNextUntilLaneEnd (double distance) const
Returns a list of waypoints separated by distance from the current waypoint to the end of the lane.
Definition at line 70 of file client/Waypoint.cpp.
References _parent, _waypoint, GetDistance(), GetNext(), GetRoadId(), and carla::road::element::Waypoint::lane_id.
Referenced by GetTransform().
std::vector< SharedPtr< Waypoint > > carla::client::Waypoint::GetPrevious (double distance) const
Definition at line 60 of file client/Waypoint.cpp.
References _parent, _waypoint, and Waypoint().
Referenced by GetPreviousUntilLaneStart(), and GetTransform().
std::vector< SharedPtr< Waypoint > > carla::client::Waypoint::GetPreviousUntilLaneStart (double distance) const
Returns a list of waypoints separated by distance from the current waypoint to the start of the lane.
Definition at line 95 of file client/Waypoint.cpp.
References _parent, _waypoint, GetDistance(), GetPrevious(), GetRoadId(), and carla::road::element::Waypoint::lane_id.
Referenced by GetTransform().
SharedPtr< Waypoint > carla::client::Waypoint::GetRight () const
Definition at line 122 of file client/Waypoint.cpp.
References _parent, _waypoint, and Waypoint().
Referenced by GetTransform().
boost::optional< road::element::LaneMarking > carla::client::Waypoint::GetRightLaneMarking () const
Definition at line 140 of file client/Waypoint.cpp.
References _mark_record.
Referenced by GetTransform().
auto carla::client::Waypoint::GetRoadId () const inline
Definition at line 42 of file client/Waypoint.h.
References _waypoint, and carla::road::element::Waypoint::road_id.
Referenced by GetNextUntilLaneEnd(), and GetPreviousUntilLaneStart().
auto carla::client::Waypoint::GetSectionId () const inline
Definition at line 46 of file client/Waypoint.h.
References _waypoint, and carla::road::element::Waypoint::section_id.
const geom::Transform& carla::client::Waypoint::GetTransform () const inline
Definition at line 58 of file client/Waypoint.h.
References _transform, GetAllLandmakrsInDistance(), GetJunction(), GetJunctionId(), GetLandmakrsOfTypeInDistance(), GetLaneChange(), GetLaneWidth(), GetLeft(), GetLeftLaneMarking(), GetNext(), GetNextUntilLaneEnd(), GetPrevious(), GetPreviousUntilLaneStart(), GetRight(), GetRightLaneMarking(), GetType(), and IsJunction().
road::Lane::LaneType carla::client::Waypoint::GetType () const
Definition at line 46 of file client/Waypoint.cpp.
References _parent, and _waypoint.
Referenced by GetTransform().
bool carla::client::Waypoint::IsJunction () const
Definition at line 30 of file client/Waypoint.cpp.
References _parent, _waypoint, and carla::road::element::Waypoint::road_id.
Referenced by GetJunction(), and GetTransform().
Friends And Related Function Documentation
friend class Map friend
Definition at line 105 of file client/Waypoint.h.
Member Data Documentation
std::pair< const road::element::RoadInfoMarkRecord *, const road::element::RoadInfoMarkRecord *> carla::client::Waypoint::_mark_record private
Definition at line 118 of file client/Waypoint.h.
Referenced by GetLaneChange(), GetLeftLaneMarking(), and GetRightLaneMarking().
SharedPtr<const Map> carla::client::Waypoint::_parent private
Definition at line 109 of file client/Waypoint.h.
Referenced by GetAllLandmakrsInDistance(), GetJunction(), GetJunctionId(), GetLandmakrsOfTypeInDistance(), GetLaneWidth(), GetLeft(), GetNext(), GetNextUntilLaneEnd(), GetPrevious(), GetPreviousUntilLaneStart(), GetRight(), GetType(), and IsJunction().
geom::Transform carla::client::Waypoint::_transform private
Definition at line 113 of file client/Waypoint.h.
Referenced by GetTransform().
road::element::Waypoint carla::client::Waypoint::_waypoint private
Definition at line 111 of file client/Waypoint.h.
Referenced by GetAllLandmakrsInDistance(), GetDistance(), GetId(), GetJunctionId(), GetLandmakrsOfTypeInDistance(), GetLaneChange(), GetLaneId(), GetLaneWidth(), GetLeft(), GetNext(), GetNextUntilLaneEnd(), GetPrevious(), GetPreviousUntilLaneStart(), GetRight(), GetRoadId(), GetSectionId(), GetType(), and IsJunction().
The documentation for this class was generated from the following files:
client/Waypoint.h
client/Waypoint.cpp