CARLA: FActorView Class Reference
FActorView Class Reference
A view over an actor and its properties.
#include <ActorView.h>
Public Types
enum ActorType : uint8 {
ActorType::Other, ActorType::Vehicle, ActorType::Walker, ActorType::TrafficLight,
ActorType::TrafficSign, ActorType::INVALID
}
using IdType = uint32
Public Member Functions
FActorView ()=default
FActorView (const FActorView &)=default
FActorView (FActorView &&)=default
AActor * GetActor ()
const AActor * GetActor () const
IdType GetActorId () const
const FActorInfo * GetActorInfo () const
ActorType GetActorType () const
bool IsValid () const
Private Member Functions
FActorView (IdType ActorId, AActor &Actor, TSharedPtr< const FActorInfo > Info)
Private Attributes
IdType Id = 0u
TSharedPtr< const FActorInfo > Info = nullptr
AActor * TheActor = nullptr
ActorType Type = ActorType::Other
Friends
class FActorRegistry
Detailed Description
A view over an actor and its properties.
Definition at line 14 of file ActorView.h.
Member Typedef Documentation
using FActorView::IdType = uint32
Definition at line 18 of file ActorView.h.
Member Enumeration Documentation
enum FActorView::ActorType : uint8 strong
Enumerator
Other
Vehicle
Walker
TrafficLight
TrafficSign
INVALID
Definition at line 20 of file ActorView.h.
Constructor & Destructor Documentation
FActorView::FActorView () default
FActorView::FActorView (const FActorView &) default
FActorView::FActorView (FActorView &&) default
FActorView::FActorView (IdType ActorId, AActor & Actor, TSharedPtr< const FActorInfo > Info) inline private
Definition at line 68 of file ActorView.h.
Member Function Documentation
AActor* FActorView::GetActor () inline
Definition at line 49 of file ActorView.h.
References TheActor.
Referenced by ACarlaRecorder::AddActorBoundingBox(), ACarlaRecorder::AddActorKinematics(), ACarlaRecorder::AddActorPosition(), ACarlaRecorder::AddTrafficLightState(), ACarlaRecorder::AddVehicleAnimation(), ACarlaRecorder::AddVehicleLight(), ACarlaRecorder::AddWalkerAnimation(), ACarlaRecorder::CreateRecorderEventAdd(), FActorRegistry::Deregister(), FActorRegistry_GetActorType(), FWorldObserver_GetActorState(), CarlaReplayerHelper::ProcessReplayerAnimVehicle(), CarlaReplayerHelper::ProcessReplayerEventDel(), CarlaReplayerHelper::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerLightVehicle(), CarlaReplayerHelper::ProcessReplayerPosition(), CarlaReplayerHelper::ProcessReplayerStateTrafficLight(), UCarlaEpisode::SerializeActor(), CarlaReplayerHelper::SetActorAutopilot(), CarlaReplayerHelper::SetActorSimulatePhysics(), CarlaReplayerHelper::SetActorVelocity(), CarlaReplayerHelper::SetCameraPosition(), and CarlaReplayerHelper::SetWalkerSpeed().
const AActor* FActorView::GetActor () const inline
Definition at line 54 of file ActorView.h.
References TheActor.
IdType FActorView::GetActorId () const inline
Definition at line 39 of file ActorView.h.
References Id.
Referenced by ACarlaRecorder::AddActorBoundingBox(), ACarlaRecorder::AddActorKinematics(), ACarlaRecorder::AddActorPosition(), ACarlaRecorder::AddCollision(), ACarlaRecorder::AddPhysicsControl(), ACarlaRecorder::AddTrafficLightState(), ACarlaRecorder::AddTrafficLightTime(), ACarlaRecorder::AddTriggerVolume(), ACarlaRecorder::AddVehicleAnimation(), ACarlaRecorder::AddVehicleLight(), ACarlaRecorder::AddWalkerAnimation(), UCarlaEpisode::AttachActors(), and UCarlaEpisode::SerializeActor().
const FActorInfo* FActorView::GetActorInfo () const inline
Definition at line 59 of file ActorView.h.
References Info.
Referenced by ACarlaRecorder::AddActorBoundingBox(), ACarlaRecorder::AddCollision(), ARayCastSemanticLidar::ComputeRawDetection(), FWorldObserver_GetAcceleration(), and UCarlaEpisode::SerializeActor().
ActorType FActorView::GetActorType () const inline
Definition at line 44 of file ActorView.h.
References Type.
Referenced by FWorldObserver_GetActorState(), and ACarlaRecorder::Ticking().
bool FActorView::IsValid () const inline
Definition at line 34 of file ActorView.h.
References TheActor.
Referenced by ARayCastSemanticLidar::ComputeRawDetection(), FActorRegistry_GetActorType(), UCarlaEpisode::SerializeActor(), CarlaReplayerHelper::SetActorAutopilot(), CarlaReplayerHelper::SetActorSimulatePhysics(), and CarlaReplayerHelper::SetActorVelocity().
Friends And Related Function Documentation
friend class FActorRegistry friend
Definition at line 66 of file ActorView.h.
Member Data Documentation
IdType FActorView::Id = 0u private
Definition at line 73 of file ActorView.h.
Referenced by GetActorId().
TSharedPtr<const FActorInfo> FActorView::Info = nullptr private
Definition at line 79 of file ActorView.h.
Referenced by GetActorInfo().
AActor* FActorView::TheActor = nullptr private
Definition at line 77 of file ActorView.h.
Referenced by GetActor(), and IsValid().
ActorType FActorView::Type = ActorType::Other private
Definition at line 75 of file ActorView.h.
Referenced by GetActorType().
The documentation for this class was generated from the following file:
ActorView.h