CARLA: carla::profiler::LifetimeProfiler Class Reference
carla::profiler::LifetimeProfiler Class Reference
Public Member Functions
void Deregister (void *object)
void Register (void *object, std::string display_name)
~LifetimeProfiler ()
Private Attributes
std::mutex _mutex
std::unordered_map< void *, std::string > _objects
Detailed Description
Definition at line 26 of file LifetimeProfiled.cpp.
Constructor & Destructor Documentation
carla::profiler::LifetimeProfiler::~LifetimeProfiler () inline
Definition at line 29 of file LifetimeProfiled.cpp.
References _mutex, _objects, DEBUG_ERROR, and carla::profiler::log().
Member Function Documentation
void carla::profiler::LifetimeProfiler::Deregister (void * object) inline
Definition at line 48 of file LifetimeProfiled.cpp.
References _mutex, _objects, DEBUG_ASSERT, and carla::profiler::log().
Referenced by carla::profiler::LifetimeProfiled::LifetimeProfiled().
void carla::profiler::LifetimeProfiler::Register (void * object, std::string display_name) inline
Definition at line 40 of file LifetimeProfiled.cpp.
References _mutex, _objects, and carla::profiler::log().
Referenced by carla::profiler::LifetimeProfiled::LifetimeProfiled().
Member Data Documentation
std::mutex carla::profiler::LifetimeProfiler::_mutex private
Definition at line 60 of file LifetimeProfiled.cpp.
Referenced by Deregister(), Register(), and ~LifetimeProfiler().
std::unordered_map<void *, std::string> carla::profiler::LifetimeProfiler::_objects private
Definition at line 62 of file LifetimeProfiled.cpp.
Referenced by Deregister(), Register(), and ~LifetimeProfiler().
The documentation for this class was generated from the following file:
LifetimeProfiled.cpp