CARLA: carla::client::FileTransfer Class Reference
carla::client::FileTransfer Class Reference
#include <FileTransfer.h>
Public Member Functions
FileTransfer ()=delete
Static Public Member Functions
static bool FileExists (std::string file)
static const std::string & GetFilesBaseFolder ()
static std::vector< uint8_t > ReadFile (std::string path)
static bool SetFilesBaseFolder (const std::string &path)
static bool WriteFile (std::string path, std::vector< uint8_t > content)
Static Private Attributes
static std::string _filesBaseFolder = std::string(getenv("HOME")) + "/carlaCache/"
Detailed Description
Definition at line 19 of file FileTransfer.h.
Constructor & Destructor Documentation
FileTransfer()
carla::client::FileTransfer::FileTransfer () delete
Member Function Documentation
FileExists()
bool carla::client::FileTransfer::FileExists (std::string file) static
Definition at line 34 of file FIleTransfer.cpp.
References _filesBaseFolder.
Referenced by carla::client::detail::Simulator::GetCurrentMap(), and carla::client::detail::Client::GetRequiredFiles().
GetFilesBaseFolder()
const std::string & carla::client::FileTransfer::GetFilesBaseFolder () static
Definition at line 30 of file FIleTransfer.cpp.
References _filesBaseFolder.
ReadFile()
std::vector< uint8_t > carla::client::FileTransfer::ReadFile (std::string path) static
Definition at line 69 of file FIleTransfer.cpp.
References _filesBaseFolder.
Referenced by carla::client::detail::Client::GetCacheFile().
SetFilesBaseFolder()
bool carla::client::FileTransfer::SetFilesBaseFolder (const std::string & path) static
Definition at line 19 of file FIleTransfer.cpp.
References _filesBaseFolder.
Referenced by carla::client::detail::Client::SetFilesBaseFolder().
WriteFile()
bool carla::client::FileTransfer::WriteFile (std::string path, std::vector< uint8_t > content) static
Definition at line 46 of file FIleTransfer.cpp.
References _filesBaseFolder, and carla::FileSystem::ValidateFilePath().
Referenced by carla::client::detail::Client::RequestFile().
Member Data Documentation
_filesBaseFolder
std::string carla::client::FileTransfer::_filesBaseFolder = std::string(getenv("HOME")) + "/carlaCache/" static private
Definition at line 37 of file FileTransfer.h.
Referenced by FileExists(), GetFilesBaseFolder(), ReadFile(), SetFilesBaseFolder(), and WriteFile().
The documentation for this class was generated from the following files:
FileTransfer.h
FIleTransfer.cpp