CARLA: traffic_manager::AtomicMap< Key, Value > Class Template Reference
traffic_manager::AtomicMap< Key, Value > Class Template Reference
#include <AtomicMap.h>
Public Member Functions
void AddEntry (const std::pair< Key, Value > &entry)
AtomicMap ()
bool Contains (const Key &key)
Value & GetValue (const Key &key)
void RemoveEntry (const Key &key)
Private Attributes
std::unordered_map< Key, Value > map
std::mutex map_mutex
Detailed Description
template<typename Key, typename Value>
class traffic_manager::AtomicMap< Key, Value >
Definition at line 15 of file AtomicMap.h.
Constructor & Destructor Documentation
template<typename Key, typename Value> traffic_manager::AtomicMap< Key, Value >::AtomicMap () inline
Definition at line 24 of file AtomicMap.h.
Member Function Documentation
template<typename Key, typename Value> void traffic_manager::AtomicMap< Key, Value >::AddEntry (const std::pair< Key, Value > & entry) inline
Definition at line 26 of file AtomicMap.h.
Referenced by traffic_manager::Parameters::SetAutoLaneChange(), traffic_manager::Parameters::SetDistanceToLeadingVehicle(), traffic_manager::Parameters::SetPercentageIgnoreActors(), traffic_manager::Parameters::SetPercentageRunningLight(), and traffic_manager::Parameters::SetPercentageSpeedDifference().
template<typename Key, typename Value> bool traffic_manager::AtomicMap< Key, Value >::Contains (const Key & key) inline
Definition at line 32 of file AtomicMap.h.
Referenced by traffic_manager::Parameters::GetAutoLaneChange(), traffic_manager::Parameters::GetDistanceToLeadingVehicle(), traffic_manager::Parameters::GetPercentageIgnoreActors(), traffic_manager::Parameters::GetPercentageRunningLight(), and traffic_manager::Parameters::GetVehicleTargetVelocity().
template<typename Key, typename Value> Value& traffic_manager::AtomicMap< Key, Value >::GetValue (const Key & key) inline
Definition at line 38 of file AtomicMap.h.
Referenced by traffic_manager::Parameters::GetAutoLaneChange(), traffic_manager::Parameters::GetDistanceToLeadingVehicle(), traffic_manager::Parameters::GetPercentageIgnoreActors(), traffic_manager::Parameters::GetPercentageRunningLight(), and traffic_manager::Parameters::GetVehicleTargetVelocity().
template<typename Key, typename Value> void traffic_manager::AtomicMap< Key, Value >::RemoveEntry (const Key & key) inline
Definition at line 44 of file AtomicMap.h.
Member Data Documentation
template<typename Key, typename Value> std::unordered_map<Key, Value> traffic_manager::AtomicMap< Key, Value >::map private
Definition at line 20 of file AtomicMap.h.
template<typename Key, typename Value> std::mutex traffic_manager::AtomicMap< Key, Value >::map_mutex private
Definition at line 19 of file AtomicMap.h.
The documentation for this class was generated from the following file:
AtomicMap.h