CARLA: SymetricMatrix Class Reference
SymetricMatrix Class Reference
#include <Simplify.h>
Public Member Functions
double det (int a11, int a12, int a13, int a21, int a22, int a23, int a31, int a32, int a33)
const SymetricMatrix operator+ (const SymetricMatrix &n) const
SymetricMatrix & operator+= (const SymetricMatrix &n)
double operator[] (int c) const
SymetricMatrix (double a, double b, double c, double d)
SymetricMatrix (double c=0)
SymetricMatrix (double m11, double m12, double m13, double m14, double m22, double m23, double m24, double m33, double m34, double m44)
Public Attributes
double m [10]
Detailed Description
Definition at line 299 of file Simplify.h.
Constructor & Destructor Documentation
SymetricMatrix() [1/3]
SymetricMatrix::SymetricMatrix (double c = 0) inline
Definition at line 305 of file Simplify.h.
References loopi, and m.
Referenced by operator+().
SymetricMatrix() [2/3]
SymetricMatrix::SymetricMatrix (double m11, double m12, double m13, double m14, double m22, double m23, double m24, double m33, double m34, double m44) inline
Definition at line 307 of file Simplify.h.
References m.
SymetricMatrix() [3/3]
SymetricMatrix::SymetricMatrix (double a, double b, double c, double d) inline
Definition at line 326 of file Simplify.h.
References m.
Member Function Documentation
det()
double SymetricMatrix::det (int a11, int a12, int a13, int a21, int a22, int a23, int a31, int a32, int a33) inline
Definition at line 344 of file Simplify.h.
References m.
Referenced by Simplify::SimplificationObject::calculate_error().
operator+()
const SymetricMatrix SymetricMatrix::operator+ (const SymetricMatrix & n) const inline
Definition at line 352 of file Simplify.h.
References m, and SymetricMatrix().
operator+=()
SymetricMatrix& SymetricMatrix::operator+= (const SymetricMatrix & n) inline
Definition at line 360 of file Simplify.h.
References m.
operator[]()
double SymetricMatrix::operator[] (int c) const inline
Definition at line 340 of file Simplify.h.
References m.
Member Data Documentation
m
double SymetricMatrix::m[10]
Definition at line 375 of file Simplify.h.
Referenced by det(), operator+(), operator+=(), operator[](), and SymetricMatrix().
The documentation for this class was generated from the following file:
Simplify.h