CARLA: carla::sensor::RawData Class Reference
carla::sensor::RawData Class Reference
Wrapper around the raw data generated by a sensor plus some useful meta-information.
#include <RawData.h>
Public Member Functions
auto begin () noexcept
Begin iterator to the data generated by the sensor.
auto begin () const noexcept
Begin iterator to the data generated by the sensor.
auto data () noexcept
Retrieve a pointer to the memory containing the data generated by the sensor.
auto data () const noexcept
Retrieve a pointer to the memory containing the data generated by the sensor.
auto end () noexcept
Past-the-end iterator to the data generated by the sensor.
auto end () const noexcept
Past-the-end iterator to the data generated by the sensor.
uint64_t GetFrame () const
Frame count when the data was generated.
const rpc::Transform & GetSensorTransform () const
Sensor's transform when the data was generated.
uint64_t GetSensorTypeId () const
Type-id of the sensor that generated the data.
double GetTimestamp () const
Timestamp when the data was generated.
size_t size () const
Size in bytes of the data generated by the sensor.
Private Types
using HeaderSerializer = s11n::SensorHeaderSerializer
Private Member Functions
const auto & GetHeader () const
RawData (Buffer &&buffer)
Private Attributes
Buffer _buffer
Friends
template<typename... Items>
class CompositeSerializer
Detailed Description
Wrapper around the raw data generated by a sensor plus some useful meta-information.
Definition at line 20 of file RawData.h.
Member Typedef Documentation
using carla::sensor::RawData::HeaderSerializer = s11n::SensorHeaderSerializer private
Definition at line 21 of file RawData.h.
Constructor & Destructor Documentation
carla::sensor::RawData::RawData (Buffer && buffer) inline private
Definition at line 92 of file RawData.h.
Member Function Documentation
auto carla::sensor::RawData::begin () inline noexcept
Begin iterator to the data generated by the sensor.
Definition at line 51 of file RawData.h.
References _buffer, carla::Buffer::begin(), and carla::sensor::s11n::SensorHeaderSerializer::header_offset.
Referenced by carla::sensor::data::Array< PixelT >::begin(), carla::sensor::data::Array< PixelT >::cbegin(), data(), carla::sensor::s11n::ImageSerializer::DeserializeHeader(), carla::sensor::s11n::EpisodeStateSerializer::DeserializeHeader(), carla::sensor::s11n::LidarSerializer::DeserializeHeader(), carla::sensor::s11n::GnssSerializer::DeserializeRawData(), carla::sensor::s11n::ObstacleDetectionEventSerializer::DeserializeRawData(), carla::sensor::s11n::CollisionEventSerializer::DeserializeRawData(), carla::sensor::s11n::IMUSerializer::DeserializeRawData(), and size().
auto carla::sensor::RawData::begin () const inline noexcept
Begin iterator to the data generated by the sensor.
Definition at line 56 of file RawData.h.
References _buffer, carla::Buffer::begin(), and carla::sensor::s11n::SensorHeaderSerializer::header_offset.
auto carla::sensor::RawData::data () inline noexcept
Retrieve a pointer to the memory containing the data generated by the sensor.
Definition at line 72 of file RawData.h.
References begin().
auto carla::sensor::RawData::data () const inline noexcept
Retrieve a pointer to the memory containing the data generated by the sensor.
Definition at line 77 of file RawData.h.
References begin().
auto carla::sensor::RawData::end () inline noexcept
Past-the-end iterator to the data generated by the sensor.
Definition at line 61 of file RawData.h.
References _buffer, and carla::Buffer::end().
Referenced by carla::sensor::data::Array< PixelT >::cend(), carla::sensor::data::Array< PixelT >::end(), and size().
auto carla::sensor::RawData::end () const inline noexcept
Past-the-end iterator to the data generated by the sensor.
Definition at line 66 of file RawData.h.
References _buffer, and carla::Buffer::end().
uint64_t carla::sensor::RawData::GetFrame () const inline
Frame count when the data was generated.
Definition at line 36 of file RawData.h.
References GetHeader().
const auto& carla::sensor::RawData::GetHeader () const inline private
Definition at line 24 of file RawData.h.
References _buffer, and carla::sensor::s11n::SensorHeaderSerializer::Deserialize().
Referenced by GetFrame(), GetSensorTransform(), GetSensorTypeId(), and GetTimestamp().
const rpc::Transform& carla::sensor::RawData::GetSensorTransform () const inline
Sensor's transform when the data was generated.
Definition at line 46 of file RawData.h.
References GetHeader().
uint64_t carla::sensor::RawData::GetSensorTypeId () const inline
Type-id of the sensor that generated the data.
Definition at line 31 of file RawData.h.
References GetHeader().
Referenced by carla::sensor::CompositeSerializer< Items >::Deserialize().
double carla::sensor::RawData::GetTimestamp () const inline
Timestamp when the data was generated.
Definition at line 41 of file RawData.h.
References GetHeader().
size_t carla::sensor::RawData::size () const inline
Size in bytes of the data generated by the sensor.
Definition at line 82 of file RawData.h.
References begin(), DEBUG_ASSERT, and end().
Referenced by carla::sensor::s11n::GnssSerializer::DeserializeRawData(), carla::sensor::s11n::ObstacleDetectionEventSerializer::DeserializeRawData(), carla::sensor::s11n::CollisionEventSerializer::DeserializeRawData(), carla::sensor::s11n::IMUSerializer::DeserializeRawData(), and carla::sensor::data::Array< PixelT >::SetOffset().
Friends And Related Function Documentation
template<typename... Items> friend class CompositeSerializer friend
Definition at line 90 of file RawData.h.
Member Data Documentation
Buffer carla::sensor::RawData::_buffer private
Definition at line 94 of file RawData.h.
Referenced by begin(), end(), and GetHeader().
The documentation for this class was generated from the following file:
RawData.h