CARLA: ATrafficLightGroup Class Reference
ATrafficLightGroup Class Reference
Class which implements the state changing of traffic lights.
#include <TrafficLightGroup.h>
Public Member Functions
ATrafficLightGroup ()
TArray< UTrafficLightController * > & GetControllers ()
float GetElapsedTime () const
int GetJunctionId () const
bool IsFrozen ()
void ResetGroup ()
void SetFrozenGroup (bool InFreeze)
Protected Member Functions
virtual void Tick (float DeltaTime) override
Private Member Functions
void NextController ()
void NextCycleStep ()
Private Attributes
friend ATrafficLightManager
bool bIsFrozen = false
TArray< UTrafficLightController * > Controllers
int CurrentController = 0
float CurrentStateTimer = 0.0f
int JunctionId = -1
USceneComponent * SceneComponent
float Timer = 0.0f
Detailed Description
Class which implements the state changing of traffic lights.
Definition at line 20 of file TrafficLightGroup.h.
Constructor & Destructor Documentation
ATrafficLightGroup::ATrafficLightGroup ()
Definition at line 12 of file TrafficLightGroup.cpp.
References SceneComponent.
Member Function Documentation
TArray<UTrafficLightController*>& ATrafficLightGroup::GetControllers () inline
Definition at line 29 of file TrafficLightGroup.h.
Referenced by ATrafficLightBase::GetGroupTrafficLights(), and ATrafficLightManager::ResetTrafficLightObjects().
float ATrafficLightGroup::GetElapsedTime () const
Definition at line 45 of file TrafficLightGroup.cpp.
References CurrentStateTimer, and Timer.
Referenced by FWorldObserver_GetActorState().
int ATrafficLightGroup::GetJunctionId () const
Definition at line 89 of file TrafficLightGroup.cpp.
References JunctionId.
bool ATrafficLightGroup::IsFrozen ()
Definition at line 25 of file TrafficLightGroup.cpp.
References bIsFrozen.
Referenced by FWorldObserver_GetActorState().
void ATrafficLightGroup::NextController () private
Definition at line 81 of file TrafficLightGroup.cpp.
References Controllers, CurrentController, CurrentStateTimer, UTrafficLightController::NextState(), and Timer.
Referenced by NextCycleStep().
void ATrafficLightGroup::NextCycleStep () private
Definition at line 68 of file TrafficLightGroup.cpp.
References Controllers, CurrentController, UTrafficLightController::IsCycleFinished(), NextController(), UTrafficLightController::NextState(), and Timer.
Referenced by Tick().
void ATrafficLightGroup::ResetGroup ()
Definition at line 30 of file TrafficLightGroup.cpp.
References Controllers, CurrentController, CurrentStateTimer, and Timer.
void ATrafficLightGroup::SetFrozenGroup (bool InFreeze)
Definition at line 20 of file TrafficLightGroup.cpp.
References bIsFrozen.
void ATrafficLightGroup::Tick (float DeltaTime) override protected virtual
Definition at line 51 of file TrafficLightGroup.cpp.
References bIsFrozen, Controllers, NextCycleStep(), and Timer.
Member Data Documentation
friend ATrafficLightGroup::ATrafficLightManager private
Definition at line 55 of file TrafficLightGroup.h.
bool ATrafficLightGroup::bIsFrozen = false private
Definition at line 79 of file TrafficLightGroup.h.
Referenced by IsFrozen(), SetFrozenGroup(), and Tick().
TArray<UTrafficLightController*> ATrafficLightGroup::Controllers private
Definition at line 61 of file TrafficLightGroup.h.
Referenced by NextController(), NextCycleStep(), ResetGroup(), and Tick().
int ATrafficLightGroup::CurrentController = 0 private
Definition at line 70 of file TrafficLightGroup.h.
Referenced by NextController(), NextCycleStep(), and ResetGroup().
float ATrafficLightGroup::CurrentStateTimer = 0.0f private
Definition at line 67 of file TrafficLightGroup.h.
Referenced by GetElapsedTime(), NextController(), and ResetGroup().
int ATrafficLightGroup::JunctionId = -1 private
Definition at line 82 of file TrafficLightGroup.h.
Referenced by GetJunctionId(), and ATrafficLightManager::RegisterLightComponent().
USceneComponent* ATrafficLightGroup::SceneComponent private
Definition at line 58 of file TrafficLightGroup.h.
Referenced by ATrafficLightGroup().
float ATrafficLightGroup::Timer = 0.0f private
Definition at line 64 of file TrafficLightGroup.h.
Referenced by GetElapsedTime(), NextController(), NextCycleStep(), ResetGroup(), and Tick().
The documentation for this class was generated from the following files:
TrafficLightGroup.h
TrafficLightGroup.cpp