CARLA: AOpenDriveActor Class Reference
AOpenDriveActor Class Reference
#include <OpenDriveActor.h>
Public Member Functions
void AddSpawners ()
AOpenDriveActor (const FObjectInitializer &ObjectInitializer)
void BuildRoutes ()
void BuildRoutes (FString MapName)
void DebugRoutes () const
void RemoveDebugRoutes () const
void RemoveRoutes ()
Remove all the existing ARoutePlanner and VehicleSpawners previously generated by this class to avoid overlapping.
void RemoveSpawners ()
Protected Attributes
UBillboardComponent * SpriteComponent
A UBillboardComponent to hold Icon sprite.
UTexture2D * SpriteTexture
Sprite for the Billboard Component.
Private Attributes
bool bAddSpawners = false
If true, spawners will be placed when generating the routes.
bool bOnIntersections = false
If true, spawners will be placed on junctions too.
float RoadAccuracy = 2.f
Distance between waypoints where the cars will drive.
TArray< ARoutePlanner * > RoutePlanners
float SpawnersHeight = 300.f
Determine the height where the spawners will be placed, relative to each RoutePlanner.
float TriggersHeight = 100.f
Trigger elevantion.
TArray< AVehicleSpawnPoint * > VehicleSpawners
Detailed Description
Definition at line 22 of file OpenDriveActor.h.
Constructor & Destructor Documentation
AOpenDriveActor::AOpenDriveActor (const FObjectInitializer & ObjectInitializer)
Definition at line 22 of file OpenDriveActor.cpp.
References AddSpawners(), bAddSpawners, BuildRoutes(), DebugRoutes(), RemoveDebugRoutes(), RemoveRoutes(), RemoveSpawners(), and SpriteComponent.
Member Function Documentation
void AOpenDriveActor::AddSpawners ()
Definition at line 267 of file OpenDriveActor.cpp.
References bOnIntersections, RoutePlanners, SpawnersHeight, and VehicleSpawners.
Referenced by AOpenDriveActor(), and UPrepareAssetsForCookingCommandlet::UPrepareAssetsForCookingCommandlet().
void AOpenDriveActor::BuildRoutes ()
Definition at line 128 of file OpenDriveActor.cpp.
Referenced by AOpenDriveActor(), and UPrepareAssetsForCookingCommandlet::UPrepareAssetsForCookingCommandlet().
void AOpenDriveActor::BuildRoutes (FString MapName)
Definition at line 133 of file OpenDriveActor.cpp.
References ARoutePlanner::AddRoute(), ARoutePlanner::bIsIntersection, carla::opendrive::OpenDriveParser::Load(), UOpenDrive::LoadXODR(), min_element(), RoadAccuracy, RoutePlanners, ARoutePlanner::SetBoxExtent(), and TriggersHeight.
void AOpenDriveActor::DebugRoutes () const
Definition at line 249 of file OpenDriveActor.cpp.
References RoutePlanners.
Referenced by AOpenDriveActor().
void AOpenDriveActor::RemoveDebugRoutes () const
Definition at line 260 of file OpenDriveActor.cpp.
Referenced by AOpenDriveActor().
void AOpenDriveActor::RemoveRoutes ()
Remove all the existing ARoutePlanner and VehicleSpawners previously generated by this class to avoid overlapping.
Definition at line 236 of file OpenDriveActor.cpp.
References RoutePlanners.
Referenced by AOpenDriveActor(), and UPrepareAssetsForCookingCommandlet::UPrepareAssetsForCookingCommandlet().
void AOpenDriveActor::RemoveSpawners ()
Definition at line 289 of file OpenDriveActor.cpp.
References VehicleSpawners.
Referenced by AOpenDriveActor(), and UPrepareAssetsForCookingCommandlet::UPrepareAssetsForCookingCommandlet().
Member Data Documentation
bool AOpenDriveActor::bAddSpawners = false private
If true, spawners will be placed when generating the routes.
Definition at line 66 of file OpenDriveActor.h.
Referenced by AOpenDriveActor().
bool AOpenDriveActor::bOnIntersections = false private
If true, spawners will be placed on junctions too.
Definition at line 70 of file OpenDriveActor.h.
Referenced by AddSpawners().
float AOpenDriveActor::RoadAccuracy = 2.f private
Distance between waypoints where the cars will drive.
Definition at line 51 of file OpenDriveActor.h.
Referenced by BuildRoutes().
TArray<ARoutePlanner *> AOpenDriveActor::RoutePlanners private
Definition at line 37 of file OpenDriveActor.h.
Referenced by AddSpawners(), BuildRoutes(), DebugRoutes(), and RemoveRoutes().
float AOpenDriveActor::SpawnersHeight = 300.f private
Determine the height where the spawners will be placed, relative to each RoutePlanner.
Definition at line 75 of file OpenDriveActor.h.
Referenced by AddSpawners().
UBillboardComponent* AOpenDriveActor::SpriteComponent protected
A UBillboardComponent to hold Icon sprite.
Definition at line 29 of file OpenDriveActor.h.
Referenced by AOpenDriveActor().
UTexture2D* AOpenDriveActor::SpriteTexture protected
Sprite for the Billboard Component.
Definition at line 32 of file OpenDriveActor.h.
float AOpenDriveActor::TriggersHeight = 100.f private
Trigger elevantion.
Definition at line 55 of file OpenDriveActor.h.
Referenced by BuildRoutes().
TArray<AVehicleSpawnPoint *> AOpenDriveActor::VehicleSpawners private
Definition at line 40 of file OpenDriveActor.h.
Referenced by AddSpawners(), and RemoveSpawners().
The documentation for this class was generated from the following files:
OpenDriveActor.h
OpenDriveActor.cpp