CARLA: carla::ros2::CarlaRadarPublisher Class Reference
carla::ros2::CarlaRadarPublisher Class Reference
#include <CarlaRadarPublisher.h>
Public Member Functions
CarlaRadarPublisher (CarlaRadarPublisher &&)
CarlaRadarPublisher (const CarlaRadarPublisher &)
CarlaRadarPublisher (const char *ros_name="", const char *parent="")
bool Init ()
CarlaRadarPublisher & operator= (CarlaRadarPublisher &&)
CarlaRadarPublisher & operator= (const CarlaRadarPublisher &)
bool Publish ()
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, size_t elements, const uint8_t *data)
const char * type () const override
~CarlaRadarPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Member Functions
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, size_t elements, std::vector< uint8_t > &&data)
Private Attributes
std::shared_ptr< CarlaRadarPublisherImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 18 of file CarlaRadarPublisher.h.
Constructor & Destructor Documentation
CarlaRadarPublisher() [1/3]
carla::ros2::CarlaRadarPublisher::CarlaRadarPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 234 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaRadarPublisher()
carla::ros2::CarlaRadarPublisher::~CarlaRadarPublisher ()
Definition at line 240 of file CarlaRadarPublisher.cpp.
References _impl.
CarlaRadarPublisher() [2/3]
carla::ros2::CarlaRadarPublisher::CarlaRadarPublisher (const CarlaRadarPublisher & other)
Definition at line 257 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaRadarPublisher() [3/3]
carla::ros2::CarlaRadarPublisher::CarlaRadarPublisher (CarlaRadarPublisher && other)
Definition at line 273 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
Init()
bool carla::ros2::CarlaRadarPublisher::Init ()
Definition at line 51 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [1/2]
CarlaRadarPublisher & carla::ros2::CarlaRadarPublisher::operator= (CarlaRadarPublisher && other)
Definition at line 280 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaRadarPublisher & carla::ros2::CarlaRadarPublisher::operator= (const CarlaRadarPublisher & other)
Definition at line 264 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaRadarPublisher::Publish ()
Definition at line 98 of file CarlaRadarPublisher.cpp.
References _impl.
SetData() [1/2]
void carla::ros2::CarlaRadarPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, size_t elements, const uint8_t * data)
Definition at line 160 of file CarlaRadarPublisher.cpp.
References carla::sensor::data::RadarDetection::altitude, carla::sensor::data::RadarDetection::azimuth, and carla::sensor::data::RadarDetection::depth.
SetData() [2/2]
void carla::ros2::CarlaRadarPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, size_t elements, std::vector< uint8_t > && data) private
Definition at line 177 of file CarlaRadarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, sensor_msgs::msg::PointField::count(), sensor_msgs::msg::PointField::datatype(), std_msgs::msg::Header::frame_id(), sensor_msgs::msg::PointField::name(), builtin_interfaces::msg::Time::nanosec(), sensor_msgs::msg::PointField::offset(), sensor_msgs::msg::PointField__FLOAT32, builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
type()
const char* carla::ros2::CarlaRadarPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 30 of file CarlaRadarPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaRadarPublisherImpl> carla::ros2::CarlaRadarPublisher::_impl private
Definition at line 36 of file CarlaRadarPublisher.h.
Referenced by CarlaRadarPublisher(), Init(), operator=(), Publish(), SetData(), and ~CarlaRadarPublisher().
The documentation for this class was generated from the following files:
CarlaRadarPublisher.h
CarlaRadarPublisher.cpp