CARLA: FSkeletonHierarchy Struct Reference
FSkeletonHierarchy Struct Reference
#include <SpringBasedVegetationComponent.h>
Public Member Functions
void AddForce (const FString &BoneName, const FVector &Force)
void Clear ()
void ClearExternalForces ()
void ComputeChildrenJointsAndBones ()
void ComputeEndJoints ()
FSkeletonJoint & GetRootJoint ()
Public Attributes
TArray< int > EndJoints
TArray< int > EndToRootOrder
TArray< FSkeletonJoint > Joints
TArray< int > RootToEndOrder
Detailed Description
Definition at line 106 of file SpringBasedVegetationComponent.h.
Member Function Documentation
AddForce()
void FSkeletonHierarchy::AddForce (const FString & BoneName, const FVector & Force)
Definition at line 213 of file SpringBasedVegetationComponent.cpp.
References Joints.
Clear()
void FSkeletonHierarchy::Clear (void)
Definition at line 136 of file SpringBasedVegetationComponent.cpp.
References EndJoints, EndToRootOrder, Joints, and RootToEndOrder.
ClearExternalForces()
void FSkeletonHierarchy::ClearExternalForces ()
Definition at line 224 of file SpringBasedVegetationComponent.cpp.
References ACC_LOG, FSkeletonJoint::AngularAcceleration, FJointProperties::AngularAcceleration, FSkeletonJoint::AngularVelocity, FJointProperties::AngularVelocity, FSkeletonJoint::bIsStatic, FSkeletonJoint::Bones, FJointCollision::CanRest, FSkeletonBone::CenterOfMass, FJointProperties::CenterOfMass, FSkeletonJoint::ChildrenIds, COLLISION_LOG, FSkeletonJoint::CollisionForceProportionalFactor, EigenToFString(), EigenVectorToRotator(), FSkeletonJoint::ExternalForces, FICT_LOG, FJointProperties::FictitiousTorque, FJointProperties::Force, GetDeltaRotator(), FSkeletonJoint::GlobalTransform, FSkeletonJoint::GolbalInverseTransform, FJointProperties::InertiaTensor, IsValid(), FJointCollision::Iteration, FSkeletonJoint::JointId, FSkeletonJoint::JointName, Joints, FJointProperties::JointToGlobalMatrix, FSkeletonBone::Length, FJointProperties::LinearAcceleration, FJointProperties::LinearVelocity, FSkeletonBone::Mass, FSkeletonJoint::Mass, FJointProperties::Mass, OTHER_LOG, OuterProduct(), FSkeletonJoint::ParentId, FSkeletonJoint::RestingAngles, RotatorToEigenVector(), ABaseVegetationActor::SetParametersToComponent(), UWalkerAnim::Snap, SOLVER_LOG, FSkeletonJoint::SpringStrength, ToEigenMatrix(), ToEigenVector(), FJointProperties::Torque, ToUnrealVector(), FSkeletonJoint::Transform, and Vehicle.
ComputeChildrenJointsAndBones()
void FSkeletonHierarchy::ComputeChildrenJointsAndBones ()
Definition at line 143 of file SpringBasedVegetationComponent.cpp.
References FSkeletonJoint::ChildrenIds, Joints, OTHER_LOG, and FSkeletonJoint::ParentId.
ComputeEndJoints()
void FSkeletonHierarchy::ComputeEndJoints ()
Definition at line 166 of file SpringBasedVegetationComponent.cpp.
References FSkeletonJoint::ChildrenIds, EndJoints, EndToRootOrder, Joints, OTHER_LOG, and RootToEndOrder.
GetRootJoint()
FSkeletonJoint& FSkeletonHierarchy::GetRootJoint () inline
Definition at line 124 of file SpringBasedVegetationComponent.h.
References FJointProperties::Force.
Member Data Documentation
EndJoints
TArray<int> FSkeletonHierarchy::EndJoints
Definition at line 113 of file SpringBasedVegetationComponent.h.
Referenced by Clear(), and ComputeEndJoints().
EndToRootOrder
TArray<int> FSkeletonHierarchy::EndToRootOrder
Definition at line 115 of file SpringBasedVegetationComponent.h.
Referenced by Clear(), and ComputeEndJoints().
Joints
TArray<FSkeletonJoint> FSkeletonHierarchy::Joints
Definition at line 111 of file SpringBasedVegetationComponent.h.
Referenced by AddForce(), Clear(), ClearExternalForces(), ComputeChildrenJointsAndBones(), and ComputeEndJoints().
RootToEndOrder
TArray<int> FSkeletonHierarchy::RootToEndOrder
Definition at line 117 of file SpringBasedVegetationComponent.h.
Referenced by Clear(), and ComputeEndJoints().
The documentation for this struct was generated from the following files:
SpringBasedVegetationComponent.h
SpringBasedVegetationComponent.cpp