CARLA: carla::Functional Class Reference
carla::Functional Class Reference
#include <Functional.h>
Classes
struct Overload
struct Overload< T >
struct Overload< T, Ts... >
struct Recursive
Static Public Member Functions
template<typename... FuncTs>
static auto MakeOverload (FuncTs &&... fs)
Creates an "overloaded callable object" out of one or more callable objects, each callable object will contribute with an overload of operator().
template<typename FuncT >
static auto MakeRecursive (FuncT &&func)
Creates a recursive callable object, where the itself is passed as first argument to func.
template<typename... FuncTs>
static auto MakeRecursiveOverload (FuncTs &&... fs)
Detailed Description
Definition at line 13 of file Functional.h.
Member Function Documentation
MakeOverload()
template<typename... FuncTs> static auto carla::Functional::MakeOverload (FuncTs &&... fs) inline static
Creates an "overloaded callable object" out of one or more callable objects, each callable object will contribute with an overload of operator().
Use case: combine several lambdas into a single lambda.
Definition at line 27 of file Functional.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and MakeRecursiveOverload().
MakeRecursive()
template<typename FuncT > static auto carla::Functional::MakeRecursive (FuncT && func) inline static
Creates a recursive callable object, where the itself is passed as first argument to func.
Use case: create recursive lambda.
Definition at line 19 of file Functional.h.
Referenced by MakeRecursiveOverload().
MakeRecursiveOverload()
template<typename... FuncTs> static auto carla::Functional::MakeRecursiveOverload (FuncTs &&... fs) inline static
See also
MakeRecursive and MakeOverload.
Definition at line 33 of file Functional.h.
References MakeOverload(), and MakeRecursive().
Referenced by FCarlaServer::FPimpl::BindActions().
The documentation for this class was generated from the following file:
Functional.h