CARLA: carla::road::Map Class Reference
carla::road::Map Class Reference
#include <Map.h>
Classes
struct SignalSearchData
Data structure for the signal search.
Public Types
using Waypoint = element::Waypoint
Public Member Functions
std::vector< element::LaneMarking > CalculateCrossedLanes (const geom::Location &origin, const geom::Location &destination) const
std::unordered_map< road::RoadId, std::unordered_set< road::RoadId > > ComputeJunctionConflicts (JuncId id) const
geom::Transform ComputeTransform (Waypoint waypoint) const
std::vector< std::unique_ptr< geom::Mesh > > GenerateChunkedMesh (const rpc::OpendriveGenerationParameters &params) const
geom::Mesh GenerateMesh (const double distance, const float extra_width=0.6f, const bool smooth_junctions=true) const
Buids a mesh based on the OpenDRIVE.
std::vector< std::pair< Waypoint, Waypoint > > GenerateTopology () const
Generate the minimum set of waypoints that define the topology of map.
geom::Mesh GenerateWalls (const double distance, const float wall_height) const
std::vector< Waypoint > GenerateWaypoints (double approx_distance) const
Generate all the waypoints in map separated by approx_distance.
std::vector< Waypoint > GenerateWaypointsInRoad (RoadId road_id, Lane::LaneType lane_type=Lane::LaneType::Driving) const
Generate waypoints at the entry of each lane of the specified road.
std::vector< Waypoint > GenerateWaypointsOnRoadEntries (Lane::LaneType lane_type=Lane::LaneType::Driving) const
Generate waypoints on each lane at the start of each road.
geom::Mesh GetAllCrosswalkMesh () const
Buids a mesh of all crosswalks based on the OpenDRIVE.
std::vector< geom::Location > GetAllCrosswalkZones () const
Returns a list of locations defining 2d areas, when a location is repeated an area is finished.
std::vector< const element::RoadInfoSignal * > GetAllSignalReferences () const
Return all RoadInfoSignal in the map.
boost::optional< element::Waypoint > GetClosestWaypointOnRoad (const geom::Location &location, uint32_t lane_type=static_cast< uint32_t >(Lane::LaneType::Driving)) const
========================================================================
– Geometry ---------------------------------------------------------—
const std::unordered_map< ContId, std::unique_ptr< Controller > > & GetControllers () const
const geom::GeoLocation & GetGeoReference () const
========================================================================
– Georeference -----------------------------------------------------—
Junction * GetJunction (JuncId id)
const Junction * GetJunction (JuncId id) const
JuncId GetJunctionId (RoadId road_id) const
std::vector< std::pair< Waypoint, Waypoint > > GetJunctionWaypoints (JuncId id, Lane::LaneType lane_type) const
Generate waypoints of the junction.
const Lane & GetLane (Waypoint waypoint) const
========================================================================
– Road information -------------------------------------------------—
Lane::LaneType GetLaneType (Waypoint waypoint) const
double GetLaneWidth (Waypoint waypoint) const
boost::optional< Waypoint > GetLeft (Waypoint waypoint) const
Return a waypoint at the lane of waypoint's left lane.
std::pair< const element::RoadInfoMarkRecord *, const element::RoadInfoMarkRecord * > GetMarkRecord (Waypoint waypoint) const
std::vector< Waypoint > GetNext (Waypoint waypoint, double distance) const
Return the list of waypoints at distance such that a vehicle at waypoint could drive to.
std::vector< Waypoint > GetPredecessors (Waypoint waypoint) const
std::vector< Waypoint > GetPrevious (Waypoint waypoint, double distance) const
Return the list of waypoints at distance in the reversed direction that a vehicle at waypoint could drive to.
boost::optional< Waypoint > GetRight (Waypoint waypoint) const
Return a waypoint at the lane of waypoint's right lane.
const std::unordered_map< SignId, std::unique_ptr< Signal > > & GetSignals () const
std::vector< SignalSearchData > GetSignalsInDistance (Waypoint waypoint, double distance, bool stop_at_junction=false) const
Searches signals from an initial waypoint until the defined distance.
std::vector< Waypoint > GetSuccessors (Waypoint waypoint) const
========================================================================
– Waypoint generation -------------------------------------------——
boost::optional< element::Waypoint > GetWaypoint (const geom::Location &location, uint32_t lane_type=static_cast< uint32_t >(Lane::LaneType::Driving)) const
boost::optional< element::Waypoint > GetWaypoint (RoadId road_id, LaneId lane_id, float s) const
bool IsJunction (RoadId road_id) const
Map (MapData m)
========================================================================
– Constructor ------------------------------------------------------—
Private Types
using Rtree = geom::SegmentCloudRtree< Waypoint >
Private Member Functions
void AddElementToRtree (std::vector< Rtree::TreeElement > &rtree_elements, geom::Transform &current_transform, geom::Transform &next_transform, Waypoint &current_waypoint, Waypoint &next_waypoint)
Helper Functions for constructing the rtree element list.
void AddElementToRtreeAndUpdateTransforms (std::vector< Rtree::TreeElement > &rtree_elements, geom::Transform &current_transform, Waypoint &current_waypoint, Waypoint &next_waypoint)
void CreateRtree ()
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Private Attributes
MapData _data
Rtree _rtree
friend MapBuilder
Detailed Description
Definition at line 27 of file road/Map.h.
Member Typedef Documentation
Rtree
using carla::road::Map::Rtree = geom::SegmentCloudRtree<Waypoint> private
Definition at line 186 of file road/Map.h.
Waypoint
using carla::road::Map::Waypoint = element::Waypoint
Definition at line 30 of file road/Map.h.
Constructor & Destructor Documentation
Map()
carla::road::Map::Map (MapData m) inline
========================================================================
– Constructor ------------------------------------------------------—
Definition at line 36 of file road/Map.h.
References CreateRtree().
Member Function Documentation
AddElementToRtree()
void carla::road::Map::AddElementToRtree (std::vector< Rtree::TreeElement > & rtree_elements, geom::Transform & current_transform, geom::Transform & next_transform, Waypoint & current_waypoint, Waypoint & next_waypoint) private
Helper Functions for constructing the rtree element list.
Definition at line 775 of file road/Map.cpp.
References carla::geom::Transform::location, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
AddElementToRtreeAndUpdateTransforms()
void carla::road::Map::AddElementToRtreeAndUpdateTransforms (std::vector< Rtree::TreeElement > & rtree_elements, geom::Transform & current_transform, Waypoint & current_waypoint, Waypoint & next_waypoint) private
Definition at line 796 of file road/Map.cpp.
CalculateCrossedLanes()
std::vector< LaneMarking > carla::road::Map::CalculateCrossedLanes (const geom::Location & origin, const geom::Location & destination) const
Definition at line 396 of file road/Map.cpp.
References carla::road::element::LaneCrossingCalculator::Calculate().
Referenced by carla::client::Map::CalculateCrossedLanes(), and GetGeoReference().
ComputeJunctionConflicts()
std::unordered_map< road::RoadId, std::unordered_set< road::RoadId > > carla::road::Map::ComputeJunctionConflicts (JuncId id) const
Definition at line 695 of file road/Map.cpp.
References carla::geom::BoundingBox::extent, carla::road::Junction::GetBoundingBox(), and carla::geom::BoundingBox::location.
Referenced by carla::road::MapBuilder::ComputeJunctionRoadConflicts().
ComputeTransform()
geom::Transform carla::road::Map::ComputeTransform (Waypoint waypoint) const
Definition at line 264 of file road/Map.cpp.
References carla::road::element::Waypoint::s.
Referenced by carla::road::element::LaneCrossingCalculator::Calculate(), carla::road::MapBuilder::CheckSignalsOnRoads(), carla::road::MapBuilder::CreateJunctionBoundingBoxes(), and GetGeoReference().
CreateRtree()
void carla::road::Map::CreateRtree () private
Definition at line 818 of file road/Map.cpp.
References carla::road::Lane::Any, carla::road::ForEachLane(), carla::geom::Transform::GetForwardVector(), carla::road::GetRemainingLength(), carla::geom::Math::GetVectorAngle(), carla::road::Lane::IsStraight(), and RELEASE_ASSERT.
Referenced by Map().
GenerateChunkedMesh()
std::vector< std::unique_ptr< geom::Mesh > > carla::road::Map::GenerateChunkedMesh (const rpc::OpendriveGenerationParameters & params) const
Definition at line 983 of file road/Map.cpp.
References carla::geom::MeshFactory::Generate(), carla::geom::MeshFactory::GenerateAllWithMaxLen(), carla::rpc::OpendriveGenerationParameters::max_road_length, carla::geom::MeshFactory::MergeAndSmooth(), carla::road::Lane::Sidewalk, carla::rpc::OpendriveGenerationParameters::smooth_junctions, carla::geom::Vector2D::x, and carla::geom::Vector2D::y.
GenerateMesh()
geom::Mesh carla::road::Map::GenerateMesh (const double distance, const float extra_width = 0.6f, const bool smooth_junctions = true) const
Buids a mesh based on the OpenDRIVE.
Definition at line 936 of file road/Map.cpp.
References carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::geom::MeshFactory::Generate(), carla::geom::MeshFactory::MergeAndSmooth(), RELEASE_ASSERT, carla::geom::MeshFactory::RoadParameters::resolution, and carla::geom::MeshFactory::road_param.
GenerateTopology()
std::vector< std::pair< Waypoint, Waypoint > > carla::road::Map::GenerateTopology () const
Generate the minimum set of waypoints that define the topology of map.
The waypoints are placed at the entrance of each lane.
Definition at line 665 of file road/Map.cpp.
References carla::road::ForEachDrivableLane().
Referenced by carla::client::Map::GetTopology().
GenerateWalls()
geom::Mesh carla::road::Map::GenerateWalls (const double distance, const float wall_height) const
GenerateWaypoints()
std::vector< Waypoint > carla::road::Map::GenerateWaypoints (double approx_distance) const
Generate all the waypoints in map separated by approx_distance.
Definition at line 589 of file road/Map.cpp.
References carla::road::EPSILON, carla::road::ForEachDrivableLaneAt(), and RELEASE_ASSERT.
Referenced by carla::client::Map::GenerateWaypoints().
GenerateWaypointsInRoad()
std::vector< Waypoint > carla::road::Map::GenerateWaypointsInRoad (RoadId road_id, Lane::LaneType lane_type = Lane::LaneType::Driving) const
Generate waypoints at the entry of each lane of the specified road.
Definition at line 633 of file road/Map.cpp.
GenerateWaypointsOnRoadEntries()
std::vector< Waypoint > carla::road::Map::GenerateWaypointsOnRoadEntries (Lane::LaneType lane_type = Lane::LaneType::Driving) const
Generate waypoints on each lane at the start of each road.
Definition at line 603 of file road/Map.cpp.
GetAllCrosswalkMesh()
geom::Mesh carla::road::Map::GetAllCrosswalkMesh () const
Buids a mesh of all crosswalks based on the OpenDRIVE.
Definition at line 1067 of file road/Map.cpp.
References carla::geom::Mesh::AddMaterial(), carla::geom::Mesh::AddTriangleFan(), and carla::geom::Mesh::EndMaterial().
GetAllCrosswalkZones()
std::vector< geom::Location > carla::road::Map::GetAllCrosswalkZones () const
Returns a list of locations defining 2d areas, when a location is repeated an area is finished.
Definition at line 402 of file road/Map.cpp.
References carla::road::element::Waypoint::lane_id, carla::geom::Transform::location, carla::road::element::Waypoint::road_id, carla::geom::Transform::rotation, carla::road::element::Waypoint::s, carla::road::element::Waypoint::section_id, carla::geom::Transform::TransformPoint(), carla::geom::Vector3D::x, and carla::geom::Rotation::yaw.
Referenced by carla::client::Map::GetAllCrosswalkZones(), and GetGeoReference().
GetAllSignalReferences()
std::vector< const element::RoadInfoSignal * > carla::road::Map::GetAllSignalReferences () const
Return all RoadInfoSignal in the map.
Definition at line 384 of file road/Map.cpp.
Referenced by carla::client::Map::GetAllLandmarks(), carla::client::Map::GetAllLandmarksOfType(), and carla::client::Map::GetLandmarksFromId().
GetClosestWaypointOnRoad()
boost::optional< Waypoint > carla::road::Map::GetClosestWaypointOnRoad (const geom::Location & location, uint32_t lane_type = static_cast<uint32_t>(Lane::LaneType::Driving)) const
========================================================================
– Geometry ---------------------------------------------------------—
Definition at line 156 of file road/Map.cpp.
References carla::geom::Math::DistanceSegmentToPoint(), carla::road::element::Waypoint::lane_id, carla::road::element::Waypoint::s, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::road::element::LaneCrossingCalculator::Calculate(), carla::road::MapBuilder::CheckSignalsOnRoads(), GetGeoReference(), and carla::client::Map::GetWaypoint().
GetControllers()
const std::unordered_map<ContId, std::unique_ptr<Controller> >& carla::road::Map::GetControllers () const inline
Definition at line 171 of file road/Map.h.
References _data, and carla::road::MapData::GetControllers().
Referenced by carla::client::Map::GetLandmarkGroup().
GetGeoReference()
const geom::GeoLocation& carla::road::Map::GetGeoReference () const inline
========================================================================
– Georeference -----------------------------------------------------—
Definition at line 44 of file road/Map.h.
References _data, CalculateCrossedLanes(), ComputeTransform(), carla::road::Lane::Driving, GetAllCrosswalkZones(), GetClosestWaypointOnRoad(), carla::road::MapData::GetGeoReference(), GetJunctionId(), GetLane(), GetLaneType(), GetLaneWidth(), GetMarkRecord(), GetWaypoint(), and IsJunction().
Referenced by carla::client::Map::GetGeoReference().
GetJunction() [1/2]
Junction * carla::road::Map::GetJunction (JuncId id)
Definition at line 928 of file road/Map.cpp.
Referenced by carla::road::MapBuilder::CreateJunctionBoundingBoxes(), and carla::client::Map::GetJunction().
GetJunction() [2/2]
const Junction * carla::road::Map::GetJunction (JuncId id) const
Definition at line 932 of file road/Map.cpp.
GetJunctionId()
JuncId carla::road::Map::GetJunctionId (RoadId road_id) const
Definition at line 289 of file road/Map.cpp.
Referenced by GetGeoReference().
GetJunctionWaypoints()
std::vector< std::pair< Waypoint, Waypoint > > carla::road::Map::GetJunctionWaypoints (JuncId id, Lane::LaneType lane_type) const
Generate waypoints of the junction.
Definition at line 678 of file road/Map.cpp.
References carla::road::ForEachLane(), carla::road::Junction::GetConnections(), carla::road::GetDistanceAtEndOfLane(), and carla::road::element::Waypoint::s.
Referenced by carla::road::MapBuilder::CreateJunctionBoundingBoxes(), and carla::client::Map::GetJunctionWaypoints().
GetLane()
const Lane & carla::road::Map::GetLane (Waypoint waypoint) const
========================================================================
– Road information -------------------------------------------------—
Definition at line 765 of file road/Map.cpp.
References carla::road::Road::GetLaneById(), carla::road::Lane::GetRoad(), carla::road::element::Waypoint::lane_id, carla::road::element::Waypoint::road_id, and carla::road::element::Waypoint::section_id.
Referenced by GetGeoReference().
GetLaneType()
Lane::LaneType carla::road::Map::GetLaneType (Waypoint waypoint) const
Definition at line 272 of file road/Map.cpp.
Referenced by GetGeoReference().
GetLaneWidth()
double carla::road::Map::GetLaneWidth (Waypoint waypoint) const
Definition at line 276 of file road/Map.cpp.
References RELEASE_ASSERT, and carla::road::element::Waypoint::s.
Referenced by carla::road::MapBuilder::CheckSignalsOnRoads(), and GetGeoReference().
GetLeft()
boost::optional< Waypoint > carla::road::Map::GetLeft (Waypoint waypoint) const
Return a waypoint at the lane of waypoint's left lane.
Definition at line 577 of file road/Map.cpp.
References carla::road::IsLanePresent(), carla::road::element::Waypoint::lane_id, and RELEASE_ASSERT.
GetMarkRecord()
std::pair< const RoadInfoMarkRecord *, const RoadInfoMarkRecord * > carla::road::Map::GetMarkRecord (Waypoint waypoint) const
Definition at line 298 of file road/Map.cpp.
References carla::road::element::Waypoint::lane_id, RELEASE_ASSERT, carla::road::element::Waypoint::s, and carla::road::element::Waypoint::section_id.
Referenced by carla::road::element::CrossingAtSameSection(), and GetGeoReference().
GetNext()
std::vector< Waypoint > carla::road::Map::GetNext (Waypoint waypoint, double distance) const
Return the list of waypoints at distance such that a vehicle at waypoint could drive to.
Definition at line 501 of file road/Map.cpp.
References carla::road::ConcatVectors(), DEBUG_ASSERT, carla::road::EPSILON, carla::road::element::Waypoint::lane_id, RELEASE_ASSERT, carla::road::element::Waypoint::road_id, carla::road::element::Waypoint::s, and carla::road::element::Waypoint::section_id.
Referenced by carla::road::MapBuilder::CreateJunctionBoundingBoxes().
GetPredecessors()
std::vector< Waypoint > carla::road::Map::GetPredecessors (Waypoint waypoint) const
Definition at line 483 of file road/Map.cpp.
References carla::road::GetDistanceAtEndOfLane(), and RELEASE_ASSERT.
GetPrevious()
std::vector< Waypoint > carla::road::Map::GetPrevious (Waypoint waypoint, double distance) const
Return the list of waypoints at distance in the reversed direction that a vehicle at waypoint could drive to.
Definition at line 534 of file road/Map.cpp.
References carla::road::ConcatVectors(), DEBUG_ASSERT, carla::road::EPSILON, carla::road::element::Waypoint::lane_id, RELEASE_ASSERT, carla::road::element::Waypoint::road_id, carla::road::element::Waypoint::s, and carla::road::element::Waypoint::section_id.
GetRight()
boost::optional< Waypoint > carla::road::Map::GetRight (Waypoint waypoint) const
Return a waypoint at the lane of waypoint's right lane.
Definition at line 567 of file road/Map.cpp.
References carla::road::IsLanePresent(), carla::road::element::Waypoint::lane_id, and RELEASE_ASSERT.
GetSignals()
const std::unordered_map<SignId, std::unique_ptr<Signal> >& carla::road::Map::GetSignals () const inline
Definition at line 167 of file road/Map.h.
References _data, and carla::road::MapData::GetSignals().
Referenced by carla::client::Map::GetLandmarkGroup().
GetSignalsInDistance()
std::vector< Map::SignalSearchData > carla::road::Map::GetSignalsInDistance (Waypoint waypoint, double distance, bool stop_at_junction = false) const
Searches signals from an initial waypoint until the defined distance.
Definition at line 321 of file road/Map.cpp.
References carla::road::ConcatVectors(), DEBUG_ASSERT, carla::road::element::RoadInfo::GetDistance(), carla::road::element::Waypoint::lane_id, carla::road::element::Waypoint::road_id, and carla::road::element::Waypoint::s.
GetSuccessors()
std::vector< Waypoint > carla::road::Map::GetSuccessors (Waypoint waypoint) const
========================================================================
– Waypoint generation -------------------------------------------——
Return the list of waypoints placed at the entrance of each drivable successor lane; i.e., the list of each waypoint in the next road segment that a vehicle could drive from waypoint.
Definition at line 465 of file road/Map.cpp.
References carla::road::GetDistanceAtStartOfLane(), and RELEASE_ASSERT.
GetWaypoint() [1/2]
boost::optional< Waypoint > carla::road::Map::GetWaypoint (const geom::Location & location, uint32_t lane_type = static_cast<uint32_t>(Lane::LaneType::Driving)) const
Definition at line 203 of file road/Map.cpp.
References carla::geom::Math::Distance2D(), carla::geom::CubicPolynomial::Evaluate(), and carla::road::element::RoadInfoLaneWidth::GetPolynomial().
Referenced by GetGeoReference(), carla::client::Map::GetWaypoint(), carla::client::Map::GetWaypointXODR(), and carla::road::element::IsOffRoad().
GetWaypoint() [2/2]
boost::optional< Waypoint > carla::road::Map::GetWaypoint (RoadId road_id, LaneId lane_id, float s) const
Definition at line 224 of file road/Map.cpp.
References carla::road::Road::GetLaneSectionsAt(), carla::road::Road::GetLength(), carla::road::element::Waypoint::lane_id, carla::road::element::Waypoint::road_id, carla::road::element::Waypoint::s, and carla::road::element::Waypoint::section_id.
IsJunction()
bool carla::road::Map::IsJunction (RoadId road_id) const
Definition at line 293 of file road/Map.cpp.
Referenced by carla::road::element::LaneCrossingCalculator::Calculate(), and GetGeoReference().
Member Data Documentation
_data
MapData carla::road::Map::_data private
Definition at line 184 of file road/Map.h.
Referenced by carla::road::MapBuilder::CheckSignalsOnRoads(), carla::road::MapBuilder::ComputeJunctionRoadConflicts(), carla::road::MapBuilder::CreateJunctionBoundingBoxes(), GetControllers(), GetGeoReference(), and GetSignals().
_rtree
Rtree carla::road::Map::_rtree private
Definition at line 187 of file road/Map.h.
MapBuilder
friend carla::road::Map::MapBuilder private
Definition at line 183 of file road/Map.h.
The documentation for this class was generated from the following files:
road/Map.h
road/Map.cpp