CARLA: carla::sensor::s11n::EpisodeStateSerializer Class Reference
carla::sensor::s11n::EpisodeStateSerializer Class Reference
Serializes the current state of the whole episode.
#include <EpisodeStateSerializer.h>
Classes
struct Header
Public Types
enum SimulationState { None = (0x0 << 0), MapChange = (0x1 << 0), PendingLightUpdate = (0x1 << 1) }
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static const Header & DeserializeHeader (const RawData &message)
template<typename SensorT >
static Buffer Serialize (const SensorT &, Buffer &&buffer)
Static Public Attributes
static constexpr auto header_offset = sizeof(Header)
Detailed Description
Serializes the current state of the whole episode.
Definition at line 27 of file EpisodeStateSerializer.h.
Member Enumeration Documentation
SimulationState
enum carla::sensor::s11n::EpisodeStateSerializer::SimulationState
Enumerator
None
MapChange
PendingLightUpdate
Definition at line 30 of file EpisodeStateSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::EpisodeStateSerializer::Deserialize (RawData && data) static
Definition at line 15 of file EpisodeStateSerializer.cpp.
Referenced by Serialize().
DeserializeHeader()
static const Header& carla::sensor::s11n::EpisodeStateSerializer::DeserializeHeader (const RawData & message) inline static
Definition at line 47 of file EpisodeStateSerializer.h.
References carla::sensor::RawData::begin().
Referenced by carla::sensor::data::RawEpisodeState::GetHeader().
Serialize()
template<typename SensorT > static Buffer carla::sensor::s11n::EpisodeStateSerializer::Serialize (const SensorT & , Buffer && buffer) inline static
Definition at line 52 of file EpisodeStateSerializer.h.
References Deserialize().
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::EpisodeStateSerializer::header_offset = sizeof(Header) static
Definition at line 45 of file EpisodeStateSerializer.h.
The documentation for this class was generated from the following files:
EpisodeStateSerializer.h
EpisodeStateSerializer.cpp