CARLA: carla::road::element::GeometrySpiral Class Reference
carla::road::element::GeometrySpiral Class Reference final
#include <Geometry.h>
Public Member Functions
std::pair< float, float > DistanceTo (const geom::Location &) const override
GeometrySpiral (double start_offset, double length, double heading, const geom::Location &start_pos, double curv_s, double curv_e)
double GetCurveEnd ()
double GetCurveStart ()
DirectedPoint PosFromDist (double dist) const override
Public Member Functions inherited from carla::road::element::Geometry
double GetHeading () const
double GetLength () const
double GetStartOffset () const
const geom::Location & GetStartPosition ()
GeometryType GetType () const
virtual ~Geometry ()=default
Private Attributes
double _curve_end
double _curve_start
Additional Inherited Members
Protected Member Functions inherited from carla::road::element::Geometry
Geometry (GeometryType type, double start_offset, double length, double heading, const geom::Location &start_pos)
Protected Attributes inherited from carla::road::element::Geometry
double _heading
double _length
geom::Location _start_position
double _start_position_offset
GeometryType _type
Detailed Description
Definition at line 164 of file Geometry.h.
Constructor & Destructor Documentation
carla::road::element::GeometrySpiral::GeometrySpiral (double start_offset, double length, double heading, const geom::Location & start_pos, double curv_s, double curv_e) inline
Definition at line 167 of file Geometry.h.
Member Function Documentation
std::pair< float, float > carla::road::element::GeometrySpiral::DistanceTo (const geom::Location & location) const override virtual
Todo:
Implements carla::road::element::Geometry.
Definition at line 103 of file Geometry.cpp.
References carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
double carla::road::element::GeometrySpiral::GetCurveEnd () inline
Definition at line 182 of file Geometry.h.
double carla::road::element::GeometrySpiral::GetCurveStart () inline
Definition at line 178 of file Geometry.h.
DirectedPoint carla::road::element::GeometrySpiral::PosFromDist (double dist) const override virtual
Implements carla::road::element::Geometry.
Definition at line 69 of file Geometry.cpp.
References carla::geom::Math::Clamp(), DEBUG_ASSERT, carla::road::element::DirectedPoint::location, odrSpiral(), carla::road::element::RotatebyAngle(), carla::road::element::DirectedPoint::tangent, carla::geom::Vector2D::x, carla::geom::Vector3D::x, carla::geom::Vector2D::y, and carla::geom::Vector3D::y.
Member Data Documentation
double carla::road::element::GeometrySpiral::_curve_end private
Definition at line 193 of file Geometry.h.
double carla::road::element::GeometrySpiral::_curve_start private
Definition at line 192 of file Geometry.h.
The documentation for this class was generated from the following files:
Geometry.h
Geometry.cpp