CARLA: UCarlaBlueprintRegistry Class Reference
UCarlaBlueprintRegistry Class Reference
#include <CarlaBlueprintRegistry.h>
Static Public Member Functions
static void AddToCarlaBlueprintRegistry (const TArray< FPropParameters > &PropParametersArray)
static void LoadPropDefinitions (TArray< FPropParameters > &PropParametersArray)
Detailed Description
Definition at line 14 of file CarlaBlueprintRegistry.h.
Member Function Documentation
void UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry (const TArray< FPropParameters > & PropParametersArray) static
Definition at line 49 of file CarlaBlueprintRegistry.cpp.
References CommonAttributes::DEFAULT, CommonAttributes::DEFINITIONS, PropAttributes::MESH_PATH, PropAttributes::NAME, CommonAttributes::PATH, PropSizeTypeToString(), PropAttributes::REGISTRY_FORMAT, and PropAttributes::SIZE.
void UCarlaBlueprintRegistry::LoadPropDefinitions (TArray< FPropParameters > & PropParametersArray) static
Definition at line 125 of file CarlaBlueprintRegistry.cpp.
References CommonAttributes::DEFAULT, CommonAttributes::DEFINITIONS, carla::client::detail::Get(), PropAttributes::MESH_PATH, PropAttributes::NAME, CommonAttributes::PATH, PropAttributes::REGISTRY_FORMAT, PropAttributes::SIZE, and StringToPropSizeType().
The documentation for this class was generated from the following files:
CarlaBlueprintRegistry.h
CarlaBlueprintRegistry.cpp