CARLA: carla::rpc::Actor Class Reference
carla::rpc::Actor Class Reference
#include <Actor.h>
Public Member Functions
Actor ()=default
MSGPACK_DEFINE_ARRAY (id, parent_id, description, bounding_box, semantic_tags, stream_token)
Public Attributes
geom::BoundingBox bounding_box
ActorDescription description
ActorId id = 0u
ActorId parent_id = 0u
std::vector< uint8_t > semantic_tags
Sensor functionality
Todo:
This is only used by sensors actually.
std::vector< unsigned char > stream_token
bool HasAStream () const
streaming::Token GetStreamToken () const
Detailed Description
Definition at line 20 of file rpc/Actor.h.
Constructor & Destructor Documentation
Actor()
carla::rpc::Actor::Actor () default
Member Function Documentation
GetStreamToken()
streaming::Token carla::rpc::Actor::GetStreamToken () const inline
Definition at line 45 of file rpc/Actor.h.
References carla::streaming::Token::data, DEBUG_ASSERT, HasAStream(), and MSGPACK_DEFINE_ARRAY().
Referenced by carla::client::detail::Simulator::SubscribeToSensor(), and carla::client::detail::Simulator::UnSubscribeFromSensor().
HasAStream()
bool carla::rpc::Actor::HasAStream () const inline
Definition at line 41 of file rpc/Actor.h.
References carla::streaming::Token::data.
Referenced by GetStreamToken(), and carla::client::detail::ActorFactory::MakeActor().
MSGPACK_DEFINE_ARRAY()
carla::rpc::Actor::MSGPACK_DEFINE_ARRAY (id , parent_id , description , bounding_box , semantic_tags , stream_token)
Referenced by GetStreamToken().
Member Data Documentation
bounding_box
geom::BoundingBox carla::rpc::Actor::bounding_box
Definition at line 31 of file rpc/Actor.h.
Referenced by carla::client::detail::ActorState::GetBoundingBox(), and TEST().
description
ActorDescription carla::rpc::Actor::description
Definition at line 29 of file rpc/Actor.h.
Referenced by carla::client::detail::ActorState::GetTypeId(), carla::client::detail::ActorVariant::GetTypeId(), carla::client::detail::ActorFactory::MakeActor(), and TEST().
id
ActorId carla::rpc::Actor::id = 0u
Definition at line 25 of file rpc/Actor.h.
Referenced by carla::client::detail::ActorState::GetId(), carla::client::detail::ActorVariant::GetId(), carla::client::detail::CachedActorList::Insert(), and TEST().
parent_id
ActorId carla::rpc::Actor::parent_id = 0u
Definition at line 27 of file rpc/Actor.h.
Referenced by carla::client::detail::ActorState::GetParentId(), carla::client::detail::ActorVariant::GetParentId(), and UCarlaEpisode::SerializeActor().
semantic_tags
std::vector<uint8_t> carla::rpc::Actor::semantic_tags
Definition at line 33 of file rpc/Actor.h.
Referenced by carla::client::detail::ActorState::GetSemanticTags().
stream_token
std::vector<unsigned char> carla::rpc::Actor::stream_token
Definition at line 39 of file rpc/Actor.h.
The documentation for this class was generated from the following file:
rpc/Actor.h