CARLA: pugi::xpath_variable_set Class Reference
pugi::xpath_variable_set Class Reference
#include <pugixml.hpp>
Public Member Functions
xpath_variable * add (const char_t *name, xpath_value_type type)
xpath_variable * get (const char_t *name)
const xpath_variable * get (const char_t *name) const
xpath_variable_set & operator= (const xpath_variable_set &rhs)
bool set (const char_t *name, bool value)
bool set (const char_t *name, double value)
bool set (const char_t *name, const char_t *value)
bool set (const char_t *name, const xpath_node_set &value)
xpath_variable_set ()
xpath_variable_set (const xpath_variable_set &rhs)
~xpath_variable_set ()
Private Member Functions
void _assign (const xpath_variable_set &rhs)
xpath_variable * _find (const char_t *name) const
void _swap (xpath_variable_set &rhs)
Static Private Member Functions
static bool _clone (xpath_variable *var, xpath_variable **out_result)
static void _destroy (xpath_variable *var)
Private Attributes
xpath_variable * _data [64]
Detailed Description
Definition at line 1140 of file pugixml.hpp.
Constructor & Destructor Documentation
xpath_variable_set() [1/2]
PUGI__FN pugi::xpath_variable_set::xpath_variable_set ()
Definition at line 12274 of file pugixml.cpp.
Referenced by operator=().
~xpath_variable_set()
PUGI__FN pugi::xpath_variable_set::~xpath_variable_set ()
Definition at line 12280 of file pugixml.cpp.
xpath_variable_set() [2/2]
PUGI__FN pugi::xpath_variable_set::xpath_variable_set (const xpath_variable_set & rhs)
Definition at line 12286 of file pugixml.cpp.
Member Function Documentation
_assign()
PUGI__FN void pugi::xpath_variable_set::_assign (const xpath_variable_set & rhs) private
Definition at line 12327 of file pugixml.cpp.
References _data.
_clone()
PUGI__FN bool pugi::xpath_variable_set::_clone (xpath_variable * var, xpath_variable ** out_result) static private
Definition at line 12362 of file pugixml.cpp.
References pugi::xpath_variable::_next, pugi::xpath_variable::_type, copy_xpath_variable(), pugi::xpath_variable::name(), and new_xpath_variable().
_destroy()
PUGI__FN void pugi::xpath_variable_set::_destroy (xpath_variable * var) static private
Definition at line 12389 of file pugixml.cpp.
References pugi::xpath_variable::_next, pugi::xpath_variable::_type, and delete_xpath_variable().
_find()
PUGI__FN xpath_variable * pugi::xpath_variable_set::_find (const char_t * name) const private
Definition at line 12349 of file pugixml.cpp.
References pugi::xpath_variable::_next, hash_string(), pugi::xpath_variable::name(), and strequal().
_swap()
PUGI__FN void pugi::xpath_variable_set::_swap (xpath_variable_set & rhs) private
Definition at line 12338 of file pugixml.cpp.
References _data.
add()
PUGI__FN xpath_variable * pugi::xpath_variable_set::add (const char_t * name, xpath_value_type type)
Definition at line 12401 of file pugixml.cpp.
References pugi::xpath_variable::_next, hash_string(), pugi::xpath_variable::name(), new_xpath_variable(), and strequal().
get() [1/2]
PUGI__FN xpath_variable * pugi::xpath_variable_set::get (const char_t * name)
Definition at line 12448 of file pugixml.cpp.
get() [2/2]
PUGI__FN const xpath_variable * pugi::xpath_variable_set::get (const char_t * name) const
Definition at line 12453 of file pugixml.cpp.
operator=()
PUGI__FN xpath_variable_set & pugi::xpath_variable_set::operator= (const xpath_variable_set & rhs)
Definition at line 12294 of file pugixml.cpp.
References PUGI__FN, PUGIXML_NOEXCEPT, and xpath_variable_set().
set() [1/4]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, bool value)
Definition at line 12424 of file pugixml.cpp.
References pugi::xpath_variable::set(), and pugi::xpath_type_boolean.
set() [2/4]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, double value)
Definition at line 12430 of file pugixml.cpp.
References pugi::xpath_variable::set(), and pugi::xpath_type_number.
set() [3/4]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, const char_t * value)
Definition at line 12436 of file pugixml.cpp.
References pugi::xpath_variable::set(), and pugi::xpath_type_string.
set() [4/4]
PUGI__FN bool pugi::xpath_variable_set::set (const char_t * name, const xpath_node_set & value)
Definition at line 12442 of file pugixml.cpp.
References pugi::xpath_variable::set(), and pugi::xpath_type_node_set.
Member Data Documentation
_data
xpath_variable* pugi::xpath_variable_set::_data[64] private
Definition at line 1143 of file pugixml.hpp.
Referenced by _assign(), and _swap().
The documentation for this class was generated from the following files:
pugixml.hpp
pugixml.cpp