CARLA: carla::client::Walker Class Reference
carla::client::Walker Class Reference
#include <Walker.h>
Public Types
using BoneControl = rpc::WalkerBoneControl
using Control = rpc::WalkerControl
Public Member Functions
void ApplyControl (const Control &control)
Apply control to this Walker.
void ApplyControl (const BoneControl &bone_control)
Control GetWalkerControl () const
Return the control last applied to this Walker.
Walker (ActorInitializer init)
Public Member Functions inherited from carla::client::Actor
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddForce (const geom::Vector3D &force)
Add force to the actor at its center of mass.
void AddForce (const geom::Vector3D &force, const geom::Vector3D &location)
Add force to the actor at certain location.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor at its center of mass.
void AddImpulse (const geom::Vector3D &impulse, const geom::Vector3D &location)
Add impulse to the actor at certain location.
void AddTorque (const geom::Vector3D &vector)
Add a torque to the actor.
virtual bool Destroy ()
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
void DisableConstantVelocity ()
Disable the constant velocity mode.
void EnableConstantVelocity (const geom::Vector3D &vector)
Enable a constant velocity mode.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
geom::Location GetLocation () const
Return the current location of the actor.
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsAlive () const
const auto & Serialize () const
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTargetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor before applying physics.
void SetTargetVelocity (const geom::Vector3D &vector)
Set the actor velocity before applying physics.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Private Attributes
Control _control
Additional Inherited Members
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Detailed Description
Definition at line 16 of file Walker.h.
Member Typedef Documentation
BoneControl
using carla::client::Walker::BoneControl = rpc::WalkerBoneControl
Definition at line 20 of file Walker.h.
Control
using carla::client::Walker::Control = rpc::WalkerControl
Definition at line 19 of file Walker.h.
Constructor & Destructor Documentation
Walker()
carla::client::Walker::Walker (ActorInitializer init) inline explicit
Definition at line 22 of file Walker.h.
References ApplyControl(), and GetWalkerControl().
Member Function Documentation
ApplyControl() [1/2]
void carla::client::Walker::ApplyControl (const Control & control)
Apply control to this Walker.
Definition at line 14 of file Walker.cpp.
References _control, carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Walker().
ApplyControl() [2/2]
void carla::client::Walker::ApplyControl (const BoneControl & bone_control)
Definition at line 21 of file Walker.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetWalkerControl()
Walker::Control carla::client::Walker::GetWalkerControl () const
Return the control last applied to this Walker.
Note
This function does not call the simulator, it returns the Control received in the last tick.
Definition at line 25 of file Walker.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Walker().
Member Data Documentation
_control
Control carla::client::Walker::_control private
Definition at line 39 of file Walker.h.
Referenced by ApplyControl().
The documentation for this class was generated from the following files:
Walker.h
Walker.cpp