CARLA: carla::profiler Namespace Reference
carla::profiler Namespace Reference
Namespaces
detail
Classes
class LifetimeProfiled
class LifetimeProfiler
Functions
template<typename... Args>
static void log (Args &&...args)
Variables
static LifetimeProfiler PROFILER
Function Documentation
template<typename... Args> static void carla::profiler::log (Args &&... args) inline static
Definition at line 22 of file LifetimeProfiled.cpp.
References carla::logging::write_to_stream().
Referenced by carla::profiler::LifetimeProfiler::Deregister(), carla::profiler::LifetimeProfiler::Register(), and carla::profiler::LifetimeProfiler::~LifetimeProfiler().
Variable Documentation
LifetimeProfiler carla::profiler::PROFILER static
Definition at line 65 of file LifetimeProfiled.cpp.