CARLA: geometry_msgs::msg::TwistWithCovariancePubSubType Class Reference
geometry_msgs::msg::TwistWithCovariancePubSubType Class Reference
This class represents the TopicDataType of the type TwistWithCovariance defined by the user in the IDL file.
#include <TwistWithCovariancePubSubTypes.h>
Public Types
typedef TwistWithCovariance type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport TwistWithCovariancePubSubType ()
virtual eProsima_user_DllExport ~TwistWithCovariancePubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type TwistWithCovariance defined by the user in the IDL file.
Definition at line 75 of file TwistWithCovariancePubSubTypes.h.
Member Typedef Documentation
type
typedef TwistWithCovariance geometry_msgs::msg::TwistWithCovariancePubSubType::type
Definition at line 79 of file TwistWithCovariancePubSubTypes.h.
Constructor & Destructor Documentation
TwistWithCovariancePubSubType()
geometry_msgs::msg::TwistWithCovariancePubSubType::TwistWithCovariancePubSubType ()
Definition at line 33 of file TwistWithCovariancePubSubTypes.cpp.
References geometry_msgs::msg::TwistWithCovariance::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::TwistWithCovariance::getMaxCdrSerializedSize(), geometry_msgs::msg::TwistWithCovariance::isKeyDefined(), and m_keyBuffer.
~TwistWithCovariancePubSubType()
geometry_msgs::msg::TwistWithCovariancePubSubType::~TwistWithCovariancePubSubType () override virtual
Definition at line 46 of file TwistWithCovariancePubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::TwistWithCovariancePubSubType::createData () override virtual
Definition at line 123 of file TwistWithCovariancePubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::TwistWithCovariancePubSubType::deleteData (void * data) override virtual
Definition at line 128 of file TwistWithCovariancePubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::TwistWithCovariancePubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 83 of file TwistWithCovariancePubSubTypes.cpp.
References geometry_msgs::msg::TwistWithCovariance::deserialize().
getKey()
bool geometry_msgs::msg::TwistWithCovariancePubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 134 of file TwistWithCovariancePubSubTypes.cpp.
References geometry_msgs::msg::TwistWithCovariance::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::TwistWithCovariance::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::TwistWithCovariancePubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 113 of file TwistWithCovariancePubSubTypes.cpp.
References geometry_msgs::msg::TwistWithCovariance::getCdrSerializedSize().
is_plain_impl()
static constexpr bool geometry_msgs::msg::TwistWithCovariancePubSubType::is_plain_impl () inline static constexpr private
Definition at line 134 of file TwistWithCovariancePubSubTypes.h.
serialize()
bool geometry_msgs::msg::TwistWithCovariancePubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 54 of file TwistWithCovariancePubSubTypes.cpp.
References geometry_msgs::msg::TwistWithCovariance::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::TwistWithCovariancePubSubType::m_keyBuffer
Definition at line 132 of file TwistWithCovariancePubSubTypes.h.
Referenced by getKey(), TwistWithCovariancePubSubType(), and ~TwistWithCovariancePubSubType().
m_md5
MD5 geometry_msgs::msg::TwistWithCovariancePubSubType::m_md5
Definition at line 131 of file TwistWithCovariancePubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
TwistWithCovariancePubSubTypes.h
TwistWithCovariancePubSubTypes.cpp