CARLA: sensor_msgs::msg::NavSatStatusPubSubType Class Reference
sensor_msgs::msg::NavSatStatusPubSubType Class Reference
This class represents the TopicDataType of the type NavSatStatus defined by the user in the IDL file.
#include <NavSatStatusPubSubTypes.h>
Public Types
typedef NavSatStatus type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport NavSatStatusPubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~NavSatStatusPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type NavSatStatus defined by the user in the IDL file.
Definition at line 72 of file NavSatStatusPubSubTypes.h.
Member Typedef Documentation
type
typedef NavSatStatus sensor_msgs::msg::NavSatStatusPubSubType::type
Definition at line 76 of file NavSatStatusPubSubTypes.h.
Constructor & Destructor Documentation
NavSatStatusPubSubType()
sensor_msgs::msg::NavSatStatusPubSubType::NavSatStatusPubSubType ()
Definition at line 32 of file NavSatStatusPubSubTypes.cpp.
References sensor_msgs::msg::NavSatStatus::getKeyMaxCdrSerializedSize(), sensor_msgs::msg::NavSatStatus::getMaxCdrSerializedSize(), sensor_msgs::msg::NavSatStatus::isKeyDefined(), and m_keyBuffer.
~NavSatStatusPubSubType()
sensor_msgs::msg::NavSatStatusPubSubType::~NavSatStatusPubSubType () override virtual
Definition at line 45 of file NavSatStatusPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * sensor_msgs::msg::NavSatStatusPubSubType::createData () override virtual
Definition at line 122 of file NavSatStatusPubSubTypes.cpp.
deleteData()
void sensor_msgs::msg::NavSatStatusPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file NavSatStatusPubSubTypes.cpp.
deserialize()
bool sensor_msgs::msg::NavSatStatusPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file NavSatStatusPubSubTypes.cpp.
References sensor_msgs::msg::NavSatStatus::deserialize().
getKey()
bool sensor_msgs::msg::NavSatStatusPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file NavSatStatusPubSubTypes.cpp.
References sensor_msgs::msg::NavSatStatus::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and sensor_msgs::msg::NavSatStatus::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> sensor_msgs::msg::NavSatStatusPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file NavSatStatusPubSubTypes.cpp.
References sensor_msgs::msg::NavSatStatus::getCdrSerializedSize().
is_plain_impl()
static constexpr bool sensor_msgs::msg::NavSatStatusPubSubType::is_plain_impl () inline static private
Definition at line 131 of file NavSatStatusPubSubTypes.h.
serialize()
bool sensor_msgs::msg::NavSatStatusPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file NavSatStatusPubSubTypes.cpp.
References sensor_msgs::msg::NavSatStatus::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* sensor_msgs::msg::NavSatStatusPubSubType::m_keyBuffer
Definition at line 129 of file NavSatStatusPubSubTypes.h.
Referenced by getKey(), NavSatStatusPubSubType(), and ~NavSatStatusPubSubType().
m_md5
MD5 sensor_msgs::msg::NavSatStatusPubSubType::m_md5
Definition at line 128 of file NavSatStatusPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
NavSatStatusPubSubTypes.h
NavSatStatusPubSubTypes.cpp