CARLA: carla::client::detail Namespace Reference
carla::client::detail Namespace Reference
Classes
class ActorFactory
class ActorState
Internal state of an Actor.
class ActorVariant
Holds an Actor, but only instantiates it when needed.
class AtomicList
Holds an atomic pointer to a list.
class CachedActorList
Keeps a list of actor descriptions to avoid requesting each time the descriptions to the server.
class CallbackList
class Client
Provides communication with the rpc and streaming servers of a CARLA simulator.
class Episode
Holds the current episode, and the current episode state.
class EpisodeProxyImpl
Provides access to the Simulator during a given episode.
struct EpisodeProxyPointerType
class EpisodeState
Represents the state of all the actors of an episode at a given frame.
struct GarbageCollector
class Simulator
Connects and controls a CARLA Simulator.
class WalkerNavigation
Typedefs
using EpisodeProxy = EpisodeProxyImpl< EpisodeProxyPointerType::Strong >
using WeakEpisodeProxy = EpisodeProxyImpl< EpisodeProxyPointerType::Weak >
Functions
_attributes (_description.description.attributes.begin(), _description.description.attributes.end())
static auto & CastData (const sensor::SensorData &data)
template<typename T >
static T Get (carla::rpc::Response< T > &response)
static bool Get (carla::rpc::Response< void > &)
template<typename RangeT >
static auto GetActorsById_Impl (Client &client, CachedActorList &actors, const RangeT &actor_ids)
static EpisodeProxyPointerType::Shared Load (EpisodeProxyPointerType::Strong ptr)
static EpisodeProxyPointerType::Shared Load (EpisodeProxyPointerType::Weak ptr)
template<typename ActorT >
static auto MakeActorImpl (ActorInitializer init, GarbageCollectionPolicy gc)
static bool SynchronizeFrame (uint64_t frame, const Episode &episode, time_duration timeout)
static void ValidateVersions (Client &client)
Typedef Documentation
EpisodeProxy
using carla::client::detail::EpisodeProxy = typedef EpisodeProxyImpl<EpisodeProxyPointerType::Strong>
Definition at line 69 of file EpisodeProxy.h.
WeakEpisodeProxy
using carla::client::detail::WeakEpisodeProxy = typedef EpisodeProxyImpl<EpisodeProxyPointerType::Weak>
Definition at line 71 of file EpisodeProxy.h.
Function Documentation
_attributes()
carla::client::detail::_attributes (_description.description.attributes. begin(), _description.description.attributes. end())
Definition at line 28 of file ActorState.cpp.
CastData()
static auto& carla::client::detail::CastData (const sensor::SensorData & data) static
Definition at line 23 of file Episode.cpp.
Referenced by carla::client::detail::Episode::Listen().
Get() [1/2]
template<typename T > static T carla::client::detail::Get (carla::rpc::Response< T > & response) static
Definition at line 36 of file client/detail/Client.cpp.
References carla::rpc::Response< T >::Get().
Referenced by FCarlaServer::AsyncRun(), FCarlaServer::FPimpl::BindActions(), carla::client::detail::Client::Pimpl::CallAndWait(), ALargeMapManager::DumpTilesTable(), UOpenDrive::FindPathToXODRFile(), UCarlaStatics::GetAllMapNames(), GetSettingsFilePathFromCommandLine(), UOpenDrive::GetXODR(), UOpenDrive::GetXODRByPath(), FNavigationMesh::Load(), UCarlaEpisode::LoadNewEpisode(), UCarlaEpisode::LoadNewOpendriveEpisode(), UCarlaBlueprintRegistry::LoadPropDefinitions(), UCarlaSettings::LoadSettings(), FCarlaEngine::OnEpisodeSettingsChanged(), AOpticalFlowCamera::PostPhysTick(), ASceneCaptureSensor::PrePhysTick(), ARoadPainterWrapper::ReadConfigFile(), UObjectRegister::RegisterObjects(), FSparseHighDetailMap::SaveMap(), carla::traffic_manager::TrafficManagerServer::TrafficManagerServer(), and ULoadAssetMaterialsCommandlet::ULoadAssetMaterialsCommandlet().
Get() [2/2]
static bool carla::client::detail::Get (carla::rpc::Response< void > &) static
Definition at line 40 of file client/detail/Client.cpp.
GetActorsById_Impl()
template<typename RangeT > static auto carla::client::detail::GetActorsById_Impl (Client & client, CachedActorList & actors, const RangeT & actor_ids) static
Definition at line 29 of file Episode.cpp.
References carla::client::detail::CachedActorList::GetActorsById(), carla::client::detail::Client::GetActorsById(), carla::client::detail::CachedActorList::GetMissingIds(), and carla::client::detail::CachedActorList::InsertRange().
Referenced by carla::client::detail::Episode::GetActors(), and carla::client::detail::Episode::GetActorsById().
Load() [1/2]
static EpisodeProxyPointerType::Shared carla::client::detail::Load (EpisodeProxyPointerType::Strong ptr) static
Definition at line 18 of file EpisodeProxy.cpp.
References carla::AtomicSharedPtr< T >::load().
Referenced by UOpenDriveMap::HasMap(), and TEST().
Load() [2/2]
static EpisodeProxyPointerType::Shared carla::client::detail::Load (EpisodeProxyPointerType::Weak ptr) static
Definition at line 22 of file EpisodeProxy.cpp.
Referenced by carla::client::detail::EpisodeProxyImpl< EpisodeProxyPointerType::Strong >::Lock(), and carla::client::detail::EpisodeProxyImpl< EpisodeProxyPointerType::Strong >::TryLock().
MakeActorImpl()
template<typename ActorT > static auto carla::client::detail::MakeActorImpl (ActorInitializer init, GarbageCollectionPolicy gc) static
Definition at line 65 of file ActorFactory.cpp.
References DEBUG_ASSERT, carla::client::Disabled, and carla::client::Enabled.
SynchronizeFrame()
static bool carla::client::detail::SynchronizeFrame (uint64_t frame, const Episode & episode, time_duration timeout) static
Definition at line 48 of file Simulator.cpp.
References carla::client::detail::Episode::GetState(), carla::traffic_manager::TrafficManager::Tick(), and carla::time_duration::to_chrono().
Referenced by carla::client::detail::Simulator::SetEpisodeSettings(), and carla::client::detail::Simulator::Tick().
ValidateVersions()
static void carla::client::detail::ValidateVersions (Client & client) static
Definition at line 36 of file Simulator.cpp.
References carla::client::detail::Client::GetClientVersion(), carla::client::detail::Client::GetServerVersion(), and carla::log_warning().
Referenced by carla::client::detail::Simulator::GetCurrentEpisode().