CARLA: carla::client::Actor Class Reference
carla::client::Actor Class Reference
Represents an actor in the simulation.
#include <Actor.h>
Public Member Functions
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddForce (const geom::Vector3D &force)
Add force to the actor at its center of mass.
void AddForce (const geom::Vector3D &force, const geom::Vector3D &location)
Add force to the actor at certain location.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor at its center of mass.
void AddImpulse (const geom::Vector3D &impulse, const geom::Vector3D &location)
Add impulse to the actor at certain location.
void AddTorque (const geom::Vector3D &vector)
Add a torque to the actor.
virtual bool Destroy ()
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
void DisableConstantVelocity ()
Disable the constant velocity mode.
void EnableConstantVelocity (const geom::Vector3D &vector)
Enable a constant velocity mode.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
rpc::ActorState GetActorState () const
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
geom::Location GetLocation () const
Return the current location of the actor.
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsActive () const
bool IsAlive () const
bool IsDormant () const
const auto & Serialize () const
void SetEnableGravity (bool enabled=true)
Enable or disable gravity on this actor.
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTargetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor before applying physics.
void SetTargetVelocity (const geom::Vector3D &vector)
Set the actor velocity before applying physics.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Private Types
using Super = detail::ActorState
Additional Inherited Members
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Private Member Functions inherited from carla::profiler::LifetimeProfiled
LifetimeProfiled ()=default
Detailed Description
Represents an actor in the simulation.
Definition at line 18 of file client/Actor.h.
Member Typedef Documentation
Super
using carla::client::Actor::Super = detail::ActorState private
Definition at line 22 of file client/Actor.h.
Constructor & Destructor Documentation
Actor()
carla::client::Actor::Actor (ActorInitializer init) inline explicit
Definition at line 25 of file client/Actor.h.
References AddAngularImpulse(), AddForce(), AddImpulse(), AddTorque(), DisableConstantVelocity(), EnableConstantVelocity(), GetAcceleration(), GetActorState(), GetAngularVelocity(), GetLocation(), GetTransform(), GetVelocity(), SetEnableGravity(), SetLocation(), SetSimulatePhysics(), SetTargetAngularVelocity(), SetTargetVelocity(), SetTransform(), and ~Actor().
~Actor()
virtual carla::client::Actor::~Actor () virtual default
Referenced by Actor().
Member Function Documentation
AddAngularImpulse()
void carla::client::Actor::AddAngularImpulse (const geom::Vector3D & vector)
Add angular impulse to the actor.
Definition at line 75 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
AddForce() [1/2]
void carla::client::Actor::AddForce (const geom::Vector3D & force)
Add force to the actor at its center of mass.
Definition at line 67 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
AddForce() [2/2]
void carla::client::Actor::AddForce (const geom::Vector3D & force, const geom::Vector3D & location)
Add force to the actor at certain location.
Definition at line 71 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
AddImpulse() [1/2]
void carla::client::Actor::AddImpulse (const geom::Vector3D & vector)
Add impulse to the actor at its center of mass.
Definition at line 59 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
AddImpulse() [2/2]
void carla::client::Actor::AddImpulse (const geom::Vector3D & impulse, const geom::Vector3D & location)
Add impulse to the actor at certain location.
Definition at line 63 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
AddTorque()
void carla::client::Actor::AddTorque (const geom::Vector3D & vector)
Add a torque to the actor.
Definition at line 79 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
Destroy()
bool carla::client::Actor::Destroy () virtual
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
Note
It has no effect if the Actor was already successfully destroyed.
Warning
This function blocks until the destruction operation is completed by the simulator.
Reimplemented in carla::client::ServerSideSensor.
Definition at line 95 of file Actor.cpp.
References GetActorState(), carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), carla::rpc::Invalid, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::log_warning().
Referenced by carla::client::ServerSideSensor::Destroy(), and IsActive().
DisableConstantVelocity()
void carla::client::Actor::DisableConstantVelocity ()
Disable the constant velocity mode.
Definition at line 55 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
EnableConstantVelocity()
void carla::client::Actor::EnableConstantVelocity (const geom::Vector3D & vector)
Enable a constant velocity mode.
Definition at line 51 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
GetAcceleration()
geom::Vector3D carla::client::Actor::GetAcceleration () const
Return the current 3D acceleration of the actor.
Note
This function does not call the simulator, it returns the acceleration calculated after the actor's velocity.
Definition at line 31 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
GetActorState()
rpc::ActorState carla::client::Actor::GetActorState () const
Definition at line 91 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor(), Destroy(), IsActive(), IsAlive(), and IsDormant().
GetAngularVelocity()
geom::Vector3D carla::client::Actor::GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
Note
This function does not call the simulator, it returns the angular velocity received in the last tick.
Definition at line 27 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor(), and carla::rss::RssCheck::GetHeadingChange().
GetLocation()
geom::Location carla::client::Actor::GetLocation () const
Return the current location of the actor.
Note
This function does not call the simulator, it returns the location received in the last tick.
Definition at line 15 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
GetTransform()
geom::Transform carla::client::Actor::GetTransform () const
Return the current transform of the actor.
Note
This function does not call the simulator, it returns the transform received in the last tick.
Definition at line 19 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor(), carla::rss::RssCheck::CreateWorldModel(), carla::rss::RssCheck::GetSpeed(), carla::client::TrafficLight::GetStopWaypoints(), and carla::client::RssSensor::TickRssSensorThreadLocked().
GetVelocity()
geom::Vector3D carla::client::Actor::GetVelocity () const
Return the current 3D velocity of the actor.
Note
This function does not call the simulator, it returns the velocity received in the last tick.
Definition at line 23 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor(), and carla::rss::RssCheck::GetSpeed().
IsActive()
bool carla::client::Actor::IsActive () const inline
Definition at line 115 of file client/Actor.h.
References carla::rpc::Active, Destroy(), GetActorState(), carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::IsValid().
IsAlive()
bool carla::client::Actor::IsAlive () const inline
Definition at line 107 of file client/Actor.h.
References GetActorState(), carla::client::detail::ActorState::GetEpisode(), carla::rpc::Invalid, carla::client::detail::EpisodeProxyImpl< PointerT >::IsValid(), and carla::rpc::PendingKill.
Referenced by carla::client::ServerSideSensor::~ServerSideSensor().
IsDormant()
bool carla::client::Actor::IsDormant () const inline
Definition at line 111 of file client/Actor.h.
References carla::rpc::Dormant, GetActorState(), carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::IsValid().
Serialize()
const auto& carla::client::Actor::Serialize () const inline
Definition at line 128 of file client/Actor.h.
SetEnableGravity()
void carla::client::Actor::SetEnableGravity (bool enabled = true)
Enable or disable gravity on this actor.
Definition at line 87 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
SetLocation()
void carla::client::Actor::SetLocation (const geom::Location & location)
Teleport the actor to location.
Definition at line 35 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
SetSimulatePhysics()
void carla::client::Actor::SetSimulatePhysics (bool enabled = true)
Enable or disable physics simulation on this actor.
Definition at line 83 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
SetTargetAngularVelocity()
void carla::client::Actor::SetTargetAngularVelocity (const geom::Vector3D & vector)
Set the angular velocity of the actor before applying physics.
Definition at line 47 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
SetTargetVelocity()
void carla::client::Actor::SetTargetVelocity (const geom::Vector3D & vector)
Set the actor velocity before applying physics.
Definition at line 43 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
SetTransform()
void carla::client::Actor::SetTransform (const geom::Transform & transform)
Teleport and rotate the actor to transform.
Definition at line 39 of file Actor.cpp.
References carla::client::detail::ActorState::GetEpisode(), and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by Actor().
The documentation for this class was generated from the following files:
client/Actor.h
Actor.cpp