CARLA: sensor_msgs::msg::RegionOfInterest Class Reference
sensor_msgs::msg::RegionOfInterest Class Reference
This class represents the structure RegionOfInterest defined by the user in the IDL file.
#include <RegionOfInterest.h>
Public Member Functions
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool & do_rectify ()
This function returns a reference to member do_rectify.
eProsima_user_DllExport bool do_rectify () const
This function returns the value of member do_rectify.
eProsima_user_DllExport void do_rectify (bool _do_rectify)
This function sets a value in member do_rectify.
eProsima_user_DllExport uint32_t & height ()
This function returns a reference to member height.
eProsima_user_DllExport uint32_t height () const
This function returns the value of member height.
eProsima_user_DllExport void height (uint32_t _height)
This function sets a value in member height.
eProsima_user_DllExport bool operator!= (const RegionOfInterest &x) const
Comparison operator.
eProsima_user_DllExport RegionOfInterest & operator= (const RegionOfInterest &x)
Copy assignment.
eProsima_user_DllExport RegionOfInterest & operator= (RegionOfInterest &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const RegionOfInterest &x) const
Comparison operator.
eProsima_user_DllExport RegionOfInterest ()
Default constructor.
eProsima_user_DllExport RegionOfInterest (const RegionOfInterest &x)
Copy constructor.
eProsima_user_DllExport RegionOfInterest (RegionOfInterest &&x) noexcept
Move constructor.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport uint32_t & width ()
This function returns a reference to member width.
eProsima_user_DllExport uint32_t width () const
This function returns the value of member width.
eProsima_user_DllExport void width (uint32_t _width)
This function sets a value in member width.
eProsima_user_DllExport uint32_t & x_offset ()
This function returns a reference to member x_offset.
eProsima_user_DllExport uint32_t x_offset () const
This function returns the value of member x_offset.
eProsima_user_DllExport void x_offset (uint32_t _x_offset)
This function sets a value in member x_offset.
eProsima_user_DllExport uint32_t & y_offset ()
This function returns a reference to member y_offset.
eProsima_user_DllExport uint32_t y_offset () const
This function returns the value of member y_offset.
eProsima_user_DllExport void y_offset (uint32_t _y_offset)
This function sets a value in member y_offset.
eProsima_user_DllExport ~RegionOfInterest ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const sensor_msgs::msg::RegionOfInterest &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
bool m_do_rectify
uint32_t m_height
uint32_t m_width
uint32_t m_x_offset
uint32_t m_y_offset
Detailed Description
This class represents the structure RegionOfInterest defined by the user in the IDL file.
Definition at line 70 of file RegionOfInterest.h.
Constructor & Destructor Documentation
RegionOfInterest() [1/3]
sensor_msgs::msg::RegionOfInterest::RegionOfInterest ()
Default constructor.
Definition at line 40 of file RegionOfInterest.cpp.
~RegionOfInterest()
sensor_msgs::msg::RegionOfInterest::~RegionOfInterest ()
Default destructor.
Definition at line 54 of file RegionOfInterest.cpp.
RegionOfInterest() [2/3]
sensor_msgs::msg::RegionOfInterest::RegionOfInterest (const RegionOfInterest & x)
Copy constructor.
Parameters
x Reference to the object sensor_msgs::msg::RegionOfInterest that will be copied.
Definition at line 58 of file RegionOfInterest.cpp.
References m_do_rectify, m_height, m_width, m_x_offset, and m_y_offset.
RegionOfInterest() [3/3]
sensor_msgs::msg::RegionOfInterest::RegionOfInterest (RegionOfInterest && x) noexcept
Move constructor.
Parameters
x Reference to the object sensor_msgs::msg::RegionOfInterest that will be copied.
Definition at line 68 of file RegionOfInterest.cpp.
Member Function Documentation
deserialize()
void sensor_msgs::msg::RegionOfInterest::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 146 of file RegionOfInterest.cpp.
Referenced by sensor_msgs::msg::RegionOfInterestPubSubType::deserialize().
do_rectify() [1/3]
eProsima_user_DllExport bool& sensor_msgs::msg::RegionOfInterest::do_rectify ()
This function returns a reference to member do_rectify.
Returns
Reference to member do_rectify
do_rectify() [2/3]
bool & sensor_msgs::msg::RegionOfInterest::do_rectify () const
This function returns the value of member do_rectify.
This function returns a reference to member do_rectify.
Returns
Value of member do_rectify
Reference to member do_rectify
Definition at line 282 of file RegionOfInterest.cpp.
do_rectify() [3/3]
void sensor_msgs::msg::RegionOfInterest::do_rectify (bool _do_rectify)
This function sets a value in member do_rectify.
Parameters
_do_rectify New value for member do_rectify
Definition at line 272 of file RegionOfInterest.cpp.
Referenced by carla::ros2::CarlaDepthCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaSSCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaOpticalFlowCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaISCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaRGBCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaNormalsCameraPublisher::SetInfoRegionOfInterest(), and carla::ros2::CarlaDVSCameraPublisher::SetInfoRegionOfInterest().
getCdrSerializedSize()
size_t sensor_msgs::msg::RegionOfInterest::getCdrSerializedSize (const sensor_msgs::msg::RegionOfInterest & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 121 of file RegionOfInterest.cpp.
Referenced by sensor_msgs::msg::CameraInfo::getCdrSerializedSize(), and sensor_msgs::msg::RegionOfInterestPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t sensor_msgs::msg::RegionOfInterest::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 296 of file RegionOfInterest.cpp.
References sensor_msgs_msg_RegionOfInterest_max_key_cdr_typesize.
Referenced by sensor_msgs::msg::RegionOfInterestPubSubType::getKey(), and sensor_msgs::msg::RegionOfInterestPubSubType::RegionOfInterestPubSubType().
getMaxCdrSerializedSize()
size_t sensor_msgs::msg::RegionOfInterest::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 114 of file RegionOfInterest.cpp.
References sensor_msgs_msg_RegionOfInterest_max_cdr_typesize.
Referenced by sensor_msgs::msg::RegionOfInterestPubSubType::RegionOfInterestPubSubType().
height() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::RegionOfInterest::height ()
This function returns a reference to member height.
Returns
Reference to member height
height() [2/3]
uint32_t & sensor_msgs::msg::RegionOfInterest::height () const
This function returns the value of member height.
This function returns a reference to member height.
Returns
Value of member height
Reference to member height
Definition at line 226 of file RegionOfInterest.cpp.
height() [3/3]
void sensor_msgs::msg::RegionOfInterest::height (uint32_t _height)
This function sets a value in member height.
Parameters
_height New value for member height
Definition at line 216 of file RegionOfInterest.cpp.
Referenced by carla::ros2::CarlaDepthCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaSSCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaOpticalFlowCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaISCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaRGBCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaNormalsCameraPublisher::SetInfoRegionOfInterest(), and carla::ros2::CarlaDVSCameraPublisher::SetInfoRegionOfInterest().
isKeyDefined()
bool sensor_msgs::msg::RegionOfInterest::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 303 of file RegionOfInterest.cpp.
Referenced by sensor_msgs::msg::RegionOfInterestPubSubType::RegionOfInterestPubSubType().
operator!=()
bool sensor_msgs::msg::RegionOfInterest::operator!= (const RegionOfInterest & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::RegionOfInterest object to compare.
Definition at line 108 of file RegionOfInterest.cpp.
operator=() [1/2]
sensor_msgs::msg::RegionOfInterest & sensor_msgs::msg::RegionOfInterest::operator= (const RegionOfInterest & x)
Copy assignment.
Parameters
x Reference to the object sensor_msgs::msg::RegionOfInterest that will be copied.
Definition at line 78 of file RegionOfInterest.cpp.
References m_do_rectify, m_height, m_width, m_x_offset, and m_y_offset.
operator=() [2/2]
sensor_msgs::msg::RegionOfInterest & sensor_msgs::msg::RegionOfInterest::operator= (RegionOfInterest && x) noexcept
Move assignment.
Parameters
x Reference to the object sensor_msgs::msg::RegionOfInterest that will be copied.
Definition at line 90 of file RegionOfInterest.cpp.
References m_x_offset.
operator==()
bool sensor_msgs::msg::RegionOfInterest::operator== (const RegionOfInterest & x) const
Comparison operator.
Parameters
x sensor_msgs::msg::RegionOfInterest object to compare.
Definition at line 102 of file RegionOfInterest.cpp.
References m_do_rectify, m_height, m_width, m_x_offset, and m_y_offset.
serialize()
void sensor_msgs::msg::RegionOfInterest::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 136 of file RegionOfInterest.cpp.
Referenced by sensor_msgs::msg::RegionOfInterestPubSubType::serialize().
serializeKey()
void sensor_msgs::msg::RegionOfInterest::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 308 of file RegionOfInterest.cpp.
Referenced by sensor_msgs::msg::RegionOfInterestPubSubType::getKey().
width() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::RegionOfInterest::width ()
This function returns a reference to member width.
Returns
Reference to member width
width() [2/3]
uint32_t & sensor_msgs::msg::RegionOfInterest::width () const
This function returns the value of member width.
This function returns a reference to member width.
Returns
Value of member width
Reference to member width
Definition at line 254 of file RegionOfInterest.cpp.
width() [3/3]
void sensor_msgs::msg::RegionOfInterest::width (uint32_t _width)
This function sets a value in member width.
Parameters
_width New value for member width
Definition at line 244 of file RegionOfInterest.cpp.
Referenced by carla::ros2::CarlaDepthCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaSSCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaOpticalFlowCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaISCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaRGBCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaNormalsCameraPublisher::SetInfoRegionOfInterest(), and carla::ros2::CarlaDVSCameraPublisher::SetInfoRegionOfInterest().
x_offset() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::RegionOfInterest::x_offset ()
This function returns a reference to member x_offset.
Returns
Reference to member x_offset
x_offset() [2/3]
uint32_t & sensor_msgs::msg::RegionOfInterest::x_offset () const
This function returns the value of member x_offset.
This function returns a reference to member x_offset.
Returns
Value of member x_offset
Reference to member x_offset
Definition at line 170 of file RegionOfInterest.cpp.
x_offset() [3/3]
void sensor_msgs::msg::RegionOfInterest::x_offset (uint32_t _x_offset)
This function sets a value in member x_offset.
Parameters
_x_offset New value for member x_offset
Definition at line 160 of file RegionOfInterest.cpp.
Referenced by carla::ros2::CarlaDepthCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaSSCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaOpticalFlowCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaISCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaRGBCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaNormalsCameraPublisher::SetInfoRegionOfInterest(), and carla::ros2::CarlaDVSCameraPublisher::SetInfoRegionOfInterest().
y_offset() [1/3]
eProsima_user_DllExport uint32_t& sensor_msgs::msg::RegionOfInterest::y_offset ()
This function returns a reference to member y_offset.
Returns
Reference to member y_offset
y_offset() [2/3]
uint32_t & sensor_msgs::msg::RegionOfInterest::y_offset () const
This function returns the value of member y_offset.
This function returns a reference to member y_offset.
Returns
Value of member y_offset
Reference to member y_offset
Definition at line 198 of file RegionOfInterest.cpp.
y_offset() [3/3]
void sensor_msgs::msg::RegionOfInterest::y_offset (uint32_t _y_offset)
This function sets a value in member y_offset.
Parameters
_y_offset New value for member y_offset
Definition at line 188 of file RegionOfInterest.cpp.
Referenced by carla::ros2::CarlaDepthCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaSSCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaOpticalFlowCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaISCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaRGBCameraPublisher::SetInfoRegionOfInterest(), carla::ros2::CarlaNormalsCameraPublisher::SetInfoRegionOfInterest(), and carla::ros2::CarlaDVSCameraPublisher::SetInfoRegionOfInterest().
Member Data Documentation
m_do_rectify
bool sensor_msgs::msg::RegionOfInterest::m_do_rectify private
Definition at line 281 of file RegionOfInterest.h.
Referenced by operator=(), operator==(), and RegionOfInterest().
m_height
uint32_t sensor_msgs::msg::RegionOfInterest::m_height private
Definition at line 279 of file RegionOfInterest.h.
Referenced by operator=(), operator==(), and RegionOfInterest().
m_width
uint32_t sensor_msgs::msg::RegionOfInterest::m_width private
Definition at line 280 of file RegionOfInterest.h.
Referenced by operator=(), operator==(), and RegionOfInterest().
m_x_offset
uint32_t sensor_msgs::msg::RegionOfInterest::m_x_offset private
Definition at line 277 of file RegionOfInterest.h.
Referenced by operator=(), operator==(), and RegionOfInterest().
m_y_offset
uint32_t sensor_msgs::msg::RegionOfInterest::m_y_offset private
Definition at line 278 of file RegionOfInterest.h.
Referenced by operator=(), operator==(), and RegionOfInterest().
The documentation for this class was generated from the following files:
RegionOfInterest.h
RegionOfInterest.cpp