CARLA: carla::ros2::CarlaLidarPublisher Class Reference
carla::ros2::CarlaLidarPublisher Class Reference
#include <CarlaLidarPublisher.h>
Public Member Functions
CarlaLidarPublisher (CarlaLidarPublisher &&)
CarlaLidarPublisher (const CarlaLidarPublisher &)
CarlaLidarPublisher (const char *ros_name="", const char *parent="")
bool Init ()
CarlaLidarPublisher & operator= (CarlaLidarPublisher &&)
CarlaLidarPublisher & operator= (const CarlaLidarPublisher &)
bool Publish ()
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, float *data)
const char * type () const override
~CarlaLidarPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Member Functions
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > &&data)
Private Attributes
std::shared_ptr< CarlaLidarPublisherImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 18 of file CarlaLidarPublisher.h.
Constructor & Destructor Documentation
CarlaLidarPublisher() [1/3]
carla::ros2::CarlaLidarPublisher::CarlaLidarPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 207 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaLidarPublisher()
carla::ros2::CarlaLidarPublisher::~CarlaLidarPublisher ()
Definition at line 213 of file CarlaLidarPublisher.cpp.
References _impl.
CarlaLidarPublisher() [2/3]
carla::ros2::CarlaLidarPublisher::CarlaLidarPublisher (const CarlaLidarPublisher & other)
Definition at line 230 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaLidarPublisher() [3/3]
carla::ros2::CarlaLidarPublisher::CarlaLidarPublisher (CarlaLidarPublisher && other)
Definition at line 246 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
Init()
bool carla::ros2::CarlaLidarPublisher::Init ()
Definition at line 42 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [1/2]
CarlaLidarPublisher & carla::ros2::CarlaLidarPublisher::operator= (CarlaLidarPublisher && other)
Definition at line 253 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaLidarPublisher & carla::ros2::CarlaLidarPublisher::operator= (const CarlaLidarPublisher & other)
Definition at line 237 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaLidarPublisher::Publish ()
Definition at line 89 of file CarlaLidarPublisher.cpp.
References _impl.
SetData() [1/2]
void carla::ros2::CarlaLidarPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, float * data)
Definition at line 152 of file CarlaLidarPublisher.cpp.
SetData() [2/2]
void carla::ros2::CarlaLidarPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > && data) private
Definition at line 165 of file CarlaLidarPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, sensor_msgs::msg::PointField::count(), sensor_msgs::msg::PointField::datatype(), std_msgs::msg::Header::frame_id(), sensor_msgs::msg::PointField::name(), builtin_interfaces::msg::Time::nanosec(), sensor_msgs::msg::PointField::offset(), sensor_msgs::msg::PointField__FLOAT32, builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
type()
const char* carla::ros2::CarlaLidarPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 30 of file CarlaLidarPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaLidarPublisherImpl> carla::ros2::CarlaLidarPublisher::_impl private
Definition at line 36 of file CarlaLidarPublisher.h.
Referenced by CarlaLidarPublisher(), Init(), operator=(), Publish(), SetData(), and ~CarlaLidarPublisher().
The documentation for this class was generated from the following files:
CarlaLidarPublisher.h
CarlaLidarPublisher.cpp