CARLA: xpath_parser Struct Reference
xpath_parser Struct Reference
Classes
struct binary_op_t
Public Member Functions
void * alloc_node ()
xpath_ast_node * alloc_node (ast_type_t type, xpath_value_type rettype, const char_t *value)
xpath_ast_node * alloc_node (ast_type_t type, xpath_value_type rettype, double value)
xpath_ast_node * alloc_node (ast_type_t type, xpath_value_type rettype, xpath_variable *value)
xpath_ast_node * alloc_node (ast_type_t type, xpath_value_type rettype, xpath_ast_node *left=0, xpath_ast_node *right=0)
xpath_ast_node * alloc_node (ast_type_t type, xpath_ast_node *left, axis_t axis, nodetest_t test, const char_t *contents)
xpath_ast_node * alloc_node (ast_type_t type, xpath_ast_node *left, xpath_ast_node *right, predicate_t test)
const char_t * alloc_string (const xpath_lexer_string &value)
xpath_ast_node * error (const char *message)
xpath_ast_node * error_oom ()
xpath_ast_node * parse ()
axis_t parse_axis_name (const xpath_lexer_string &name, bool &specified)
xpath_ast_node * parse_expression (int limit=0)
xpath_ast_node * parse_expression_rec (xpath_ast_node *lhs, int limit)
xpath_ast_node * parse_filter_expression ()
xpath_ast_node * parse_function (const xpath_lexer_string &name, size_t argc, xpath_ast_node *args[2])
xpath_ast_node * parse_location_path ()
nodetest_t parse_node_test_type (const xpath_lexer_string &name)
xpath_ast_node * parse_path_or_unary_expression ()
xpath_ast_node * parse_primary_expression ()
xpath_ast_node * parse_relative_location_path (xpath_ast_node *set)
xpath_ast_node * parse_step (xpath_ast_node *set)
xpath_parser (const char_t *query, xpath_variable_set *variables, xpath_allocator *alloc, xpath_parse_result *result)
Static Public Member Functions
static xpath_ast_node * parse (const char_t *query, xpath_variable_set *variables, xpath_allocator *alloc, xpath_parse_result *result)
Public Attributes
xpath_allocator * _alloc
xpath_lexer _lexer
const char_t * _query
xpath_parse_result * _result
char_t _scratch [32]
xpath_variable_set * _variables
Detailed Description
Definition at line 10987 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_parser()
xpath_parser::xpath_parser (const char_t * query, xpath_variable_set * variables, xpath_allocator * alloc, xpath_parse_result * result) inline
Definition at line 11859 of file pugixml.cpp.
Member Function Documentation
alloc_node() [1/7]
void* xpath_parser::alloc_node () inline
Definition at line 11015 of file pugixml.cpp.
References xpath_allocator::allocate().
alloc_node() [2/7]
xpath_ast_node* xpath_parser::alloc_node (ast_type_t type, xpath_value_type rettype, const char_t * value) inline
Definition at line 11020 of file pugixml.cpp.
alloc_node() [3/7]
xpath_ast_node* xpath_parser::alloc_node (ast_type_t type, xpath_value_type rettype, double value) inline
Definition at line 11026 of file pugixml.cpp.
alloc_node() [4/7]
xpath_ast_node* xpath_parser::alloc_node (ast_type_t type, xpath_value_type rettype, xpath_variable * value) inline
Definition at line 11032 of file pugixml.cpp.
alloc_node() [5/7]
xpath_ast_node* xpath_parser::alloc_node (ast_type_t type, xpath_value_type rettype, xpath_ast_node * left = 0, xpath_ast_node * right = 0) inline
Definition at line 11038 of file pugixml.cpp.
alloc_node() [6/7]
xpath_ast_node* xpath_parser::alloc_node (ast_type_t type, xpath_ast_node * left, axis_t axis, nodetest_t test, const char_t * contents) inline
Definition at line 11044 of file pugixml.cpp.
alloc_node() [7/7]
xpath_ast_node* xpath_parser::alloc_node (ast_type_t type, xpath_ast_node * left, xpath_ast_node * right, predicate_t test) inline
Definition at line 11050 of file pugixml.cpp.
alloc_string()
const char_t* xpath_parser::alloc_string (const xpath_lexer_string & value) inline
Definition at line 11056 of file pugixml.cpp.
References xpath_allocator::allocate(), xpath_lexer_string::begin, xpath_lexer_string::end, and PUGIXML_TEXT.
error()
xpath_ast_node* xpath_parser::error (const char * message) inline
Definition at line 10999 of file pugixml.cpp.
References xpath_lexer::current_pos().
error_oom()
xpath_ast_node* xpath_parser::error_oom () inline
Definition at line 11007 of file pugixml.cpp.
References xpath_allocator::_error.
parse() [1/2]
xpath_ast_node* xpath_parser::parse () inline
Definition at line 11863 of file pugixml.cpp.
References xpath_lexer::current(), and lex_eof.
Referenced by parse().
parse() [2/2]
static xpath_ast_node* xpath_parser::parse (const char_t * query, xpath_variable_set * variables, xpath_allocator * alloc, xpath_parse_result * result) inline static
Definition at line 11875 of file pugixml.cpp.
References parse().
parse_axis_name()
axis_t xpath_parser::parse_axis_name (const xpath_lexer_string & name, bool & specified) inline
Definition at line 11192 of file pugixml.cpp.
References axis_ancestor, axis_ancestor_or_self, axis_attribute, axis_child, axis_descendant, axis_descendant_or_self, axis_following, axis_following_sibling, axis_namespace, axis_parent, axis_preceding, axis_preceding_sibling, axis_self, xpath_lexer_string::begin, and PUGIXML_TEXT.
parse_expression()
xpath_ast_node* xpath_parser::parse_expression (int limit = 0) inline
Definition at line 11851 of file pugixml.cpp.
parse_expression_rec()
xpath_ast_node* xpath_parser::parse_expression_rec (xpath_ast_node * lhs, int limit) inline
Definition at line 11800 of file pugixml.cpp.
References ast_op_union, ast_unknown, xpath_parser::binary_op_t::asttype, xpath_lexer::next(), xpath_parser::binary_op_t::precedence, xpath_ast_node::rettype(), xpath_parser::binary_op_t::rettype, and pugi::xpath_type_node_set.
parse_filter_expression()
xpath_ast_node* xpath_parser::parse_filter_expression () inline
Definition at line 11402 of file pugixml.cpp.
References ast_filter, xpath_lexer::current(), lex_close_square_brace, lex_open_square_brace, xpath_lexer::next(), predicate_default, xpath_ast_node::rettype(), and pugi::xpath_type_node_set.
parse_function()
xpath_ast_node* xpath_parser::parse_function (const xpath_lexer_string & name, size_t argc, xpath_ast_node * args[2]) inline
Definition at line 11072 of file pugixml.cpp.
References ast_func_boolean, ast_func_ceiling, ast_func_concat, ast_func_contains, ast_func_count, ast_func_false, ast_func_floor, ast_func_id, ast_func_lang, ast_func_last, ast_func_local_name_0, ast_func_local_name_1, ast_func_name_0, ast_func_name_1, ast_func_namespace_uri_0, ast_func_namespace_uri_1, ast_func_normalize_space_0, ast_func_normalize_space_1, ast_func_not, ast_func_number_0, ast_func_number_1, ast_func_position, ast_func_round, ast_func_starts_with, ast_func_string_0, ast_func_string_1, ast_func_string_length_0, ast_func_string_length_1, ast_func_substring_2, ast_func_substring_3, ast_func_substring_after, ast_func_substring_before, ast_func_sum, ast_func_translate, ast_func_true, xpath_lexer_string::begin, PUGIXML_TEXT, pugi::xpath_type_boolean, pugi::xpath_type_node_set, pugi::xpath_type_number, and pugi::xpath_type_string.
parse_location_path()
xpath_ast_node* xpath_parser::parse_location_path () inline
Definition at line 11628 of file pugixml.cpp.
References ast_step, ast_step_root, axis_descendant_or_self, xpath_lexer::current(), lex_axis_attribute, lex_dot, lex_double_dot, lex_double_slash, lex_multiply, lex_slash, lex_string, xpath_lexer::next(), nodetest_type_node, and pugi::xpath_type_node_set.
parse_node_test_type()
nodetest_t xpath_parser::parse_node_test_type (const xpath_lexer_string & name) inline
Definition at line 11260 of file pugixml.cpp.
References xpath_lexer_string::begin, nodetest_none, nodetest_type_comment, nodetest_type_node, nodetest_type_pi, nodetest_type_text, and PUGIXML_TEXT.
parse_path_or_unary_expression()
xpath_ast_node* xpath_parser::parse_path_or_unary_expression () inline
Definition at line 11668 of file pugixml.cpp.
References ast_op_negate, ast_step, axis_descendant_or_self, xpath_lexer::contents(), ct_space, xpath_lexer::current(), lex_double_slash, lex_minus, lex_number, lex_open_brace, lex_quoted_string, lex_slash, lex_string, lex_var_ref, xpath_lexer::next(), nodetest_none, nodetest_type_node, PUGI__IS_CHARTYPE, xpath_ast_node::rettype(), xpath_lexer::state(), pugi::xpath_type_node_set, and pugi::xpath_type_number.
parse_primary_expression()
xpath_ast_node* xpath_parser::parse_primary_expression () inline
Definition at line 11296 of file pugixml.cpp.
References ast_number_constant, ast_string_constant, ast_variable, xpath_lexer_string::begin, xpath_lexer::contents(), convert_string_to_number_scratch(), xpath_lexer::current(), xpath_lexer_string::end, get_variable_scratch(), lex_close_brace, lex_comma, lex_number, lex_open_brace, lex_quoted_string, lex_string, lex_var_ref, pugi::xml_node::name(), xpath_lexer::next(), xpath_ast_node::set_next(), pugi::xml_node::value(), pugi::xpath_type_number, and pugi::xpath_type_string.
parse_relative_location_path()
xpath_ast_node* xpath_parser::parse_relative_location_path (xpath_ast_node * set) inline
Definition at line 11603 of file pugixml.cpp.
References ast_step, axis_descendant_or_self, xpath_lexer::current(), lex_double_slash, lex_slash, xpath_lexer::next(), and nodetest_type_node.
parse_step()
xpath_ast_node* xpath_parser::parse_step (xpath_ast_node * set) inline
Definition at line 11434 of file pugixml.cpp.
References ast_predicate, ast_step, axis_attribute, axis_child, axis_parent, axis_self, xpath_lexer_string::begin, xpath_lexer::contents(), xpath_lexer::current(), xpath_lexer_string::end, lex_axis_attribute, lex_close_brace, lex_close_square_brace, lex_dot, lex_double_colon, lex_double_dot, lex_multiply, lex_open_brace, lex_open_square_brace, lex_quoted_string, lex_string, xpath_lexer::next(), nodetest_all, nodetest_all_in_namespace, nodetest_name, nodetest_none, nodetest_pi, nodetest_type_node, predicate_default, PUGIXML_TEXT, xpath_ast_node::set_next(), xpath_ast_node::set_right(), and pugi::xpath_type_node_set.
Member Data Documentation
_alloc
xpath_allocator* xpath_parser::_alloc
Definition at line 10989 of file pugixml.cpp.
_lexer
xpath_lexer xpath_parser::_lexer
Definition at line 10990 of file pugixml.cpp.
_query
const char_t* xpath_parser::_query
Definition at line 10992 of file pugixml.cpp.
_result
xpath_parse_result* xpath_parser::_result
Definition at line 10995 of file pugixml.cpp.
_scratch
char_t xpath_parser::_scratch[32]
Definition at line 10997 of file pugixml.cpp.
_variables
xpath_variable_set* xpath_parser::_variables
Definition at line 10993 of file pugixml.cpp.
The documentation for this struct was generated from the following file:
pugixml.cpp