CARLA: SceneCaptureSensor_local_ns Namespace Reference
SceneCaptureSensor_local_ns Namespace Reference
Functions
static void ConfigureShowFlags (FEngineShowFlags &ShowFlags, bool bPostProcessing=true)
static auto GetQualitySettings (UWorld *World)
static void SetCameraDefaultOverrides (USceneCaptureComponent2D &CaptureComponent2D)
Function Documentation
static void SceneCaptureSensor_local_ns::ConfigureShowFlags (FEngineShowFlags & ShowFlags, bool bPostProcessing = true) static
Definition at line 561 of file SceneCaptureSensor.cpp.
Referenced by ASceneCaptureSensor::BeginPlay().
static auto SceneCaptureSensor_local_ns::GetQualitySettings (UWorld * World) static
Definition at line 33 of file SceneCaptureSensor.cpp.
References UCarlaStatics::GetCarlaSettings().
Referenced by ASceneCaptureSensor::BeginPlay().
static void SceneCaptureSensor_local_ns::SetCameraDefaultOverrides (USceneCaptureComponent2D & CaptureComponent2D) static
Definition at line 490 of file SceneCaptureSensor.cpp.
Referenced by ASceneCaptureSensor::ASceneCaptureSensor().