CARLA: Simplify Namespace Reference
Simplify Namespace Reference
Classes
struct Ref
struct Triangle
struct Vertex
Enumerations
enum Attributes { NONE, NORMAL = 2, TEXCOORD = 4, COLOR = 8 }
Functions
double calculate_error (int id_v1, int id_v2, vec3f &p_result)
void compact_mesh ()
bool flipped (vec3f p, int i0, int i1, Vertex &v0, Vertex &v1, std::vector< int > &deleted)
void load_obj (const char *filename, bool process_uv=false)
void simplify_mesh (int target_count, double agressiveness=7, bool verbose=false)
void simplify_mesh_lossless (bool verbose=false)
char * trimwhitespace (char *str)
void update_mesh (int iteration)
void update_triangles (int i0, Vertex &v, std::vector< int > &deleted, int &deleted_triangles)
void update_uvs (int i0, const Vertex &v, const vec3f &p, std::vector< int > &deleted)
double vertex_error (SymetricMatrix q, double x, double y, double z)
void write_obj (const char *filename)
Variables
std::vector< std::string > materials
std::string mtllib
std::vector< Ref > refs
std::vector< Triangle > triangles
std::vector< Vertex > vertices
Enumeration Type Documentation
Attributes
enum Simplify::Attributes
Enumerator
NONE
NORMAL
TEXCOORD
COLOR
Definition at line 378 of file Simplify.h.
Function Documentation
calculate_error()
double Simplify::calculate_error (int id_v1, int id_v2, vec3f & p_result)
Definition at line 892 of file Simplify.h.
References SymetricMatrix::det(), min(), vertex_error(), vec3f::x, vec3f::y, and vec3f::z.
Referenced by simplify_mesh(), simplify_mesh_lossless(), update_mesh(), and update_triangles().
compact_mesh()
void Simplify::compact_mesh ()
Definition at line 854 of file Simplify.h.
References loopi, loopj, and Simplify::Triangle::v.
Referenced by simplify_mesh(), and simplify_mesh_lossless().
flipped()
bool Simplify::flipped (vec3f p, int i0, int i1, Vertex & v0, Vertex & v1, std::vector< int > & deleted)
Definition at line 647 of file Simplify.h.
References vec3f::cross(), Simplify::Triangle::deleted, vec3f::dot(), loopk, Simplify::Triangle::n, vec3f::normalize(), Simplify::Vertex::tcount, Simplify::Vertex::tstart, and Simplify::Triangle::v.
Referenced by simplify_mesh(), and simplify_mesh_lossless().
load_obj()
void Simplify::load_obj (const char * filename, bool process_uv = false)
Definition at line 953 of file Simplify.h.
References Simplify::Triangle::attr, fn, loopi, loopj, Simplify::Triangle::material, Simplify::Vertex::p, TEXCOORD, trimwhitespace(), Simplify::Triangle::v, vec3f::x, vec3f::y, and vec3f::z.
simplify_mesh()
void Simplify::simplify_mesh (int target_count, double agressiveness = 7, bool verbose = false)
Definition at line 429 of file Simplify.h.
References Simplify::Triangle::attr, Simplify::Vertex::border, calculate_error(), compact_mesh(), Simplify::Triangle::deleted, Simplify::Triangle::dirty, Simplify::Triangle::err, flipped(), loopi, loopj, Simplify::Vertex::p, Simplify::Vertex::q, Simplify::Vertex::tcount, TEXCOORD, Simplify::Vertex::tstart, update_mesh(), update_triangles(), update_uvs(), and Simplify::Triangle::v.
Referenced by carla::road::Map::GenerateOrderedChunkedMesh().
simplify_mesh_lossless()
void Simplify::simplify_mesh_lossless (bool verbose = false)
Definition at line 543 of file Simplify.h.
References Simplify::Triangle::attr, Simplify::Vertex::border, calculate_error(), compact_mesh(), Simplify::Triangle::deleted, Simplify::Triangle::dirty, Simplify::Triangle::err, flipped(), loopi, loopj, Simplify::Vertex::p, Simplify::Vertex::q, Simplify::Vertex::tcount, TEXCOORD, Simplify::Vertex::tstart, update_mesh(), update_triangles(), update_uvs(), and Simplify::Triangle::v.
trimwhitespace()
char* Simplify::trimwhitespace (char * str)
Definition at line 930 of file Simplify.h.
Referenced by load_obj().
update_mesh()
void Simplify::update_mesh (int iteration)
Definition at line 730 of file Simplify.h.
References calculate_error(), vec3f::cross(), vec3f::dot(), Simplify::Triangle::err, loopi, loopj, loopk, min(), Simplify::Triangle::n, vec3f::normalize(), Simplify::Vertex::tcount, Simplify::Vertex::tstart, Simplify::Triangle::v, vec3f::x, vec3f::y, and vec3f::z.
Referenced by simplify_mesh(), and simplify_mesh_lossless().
update_triangles()
void Simplify::update_triangles (int i0, Vertex & v, std::vector< int > & deleted, int & deleted_triangles)
Definition at line 703 of file Simplify.h.
References calculate_error(), Simplify::Triangle::deleted, Simplify::Triangle::dirty, Simplify::Triangle::err, loopk, min(), Simplify::Vertex::tcount, Simplify::Ref::tid, Simplify::Vertex::tstart, Simplify::Ref::tvertex, and Simplify::Triangle::v.
Referenced by simplify_mesh(), and simplify_mesh_lossless().
update_uvs()
void Simplify::update_uvs (int i0, const Vertex & v, const vec3f & p, std::vector< int > & deleted)
Definition at line 684 of file Simplify.h.
References Simplify::Triangle::deleted, interpolate(), loopk, Simplify::Vertex::tcount, Simplify::Ref::tid, Simplify::Vertex::tstart, Simplify::Ref::tvertex, Simplify::Triangle::uvs, and Simplify::Triangle::v.
Referenced by simplify_mesh(), and simplify_mesh_lossless().
vertex_error()
double Simplify::vertex_error (SymetricMatrix q, double x, double y, double z)
Definition at line 885 of file Simplify.h.
Referenced by calculate_error().
write_obj()
void Simplify::write_obj (const char * filename)
Definition at line 1111 of file Simplify.h.
References loopi, TEXCOORD, vector3::x, and vector3::y.
Variable Documentation
materials
std::vector<std::string> Simplify::materials
Definition at line 409 of file Simplify.h.
mtllib
std::string Simplify::mtllib
Definition at line 408 of file Simplify.h.
refs
std::vector<Ref> Simplify::refs
Definition at line 407 of file Simplify.h.
Referenced by moodycamel::ConcurrentQueue< T, Traits >::FreeList< moodycamel::ConcurrentQueue::Block >::try_get().
triangles
std::vector<Triangle> Simplify::triangles
Definition at line 405 of file Simplify.h.
Referenced by carla::road::Map::GenerateOrderedChunkedMesh().
vertices
std::vector<Vertex> Simplify::vertices
Definition at line 406 of file Simplify.h.
Referenced by carla::geom::MeshFactory::Generate(), carla::road::Map::GenerateOrderedChunkedMesh(), carla::geom::MeshFactory::GenerateTesselated(), carla::road::Map::GetAllCrosswalkMesh(), and carla::geom::Mesh::Mesh().