CARLA: ActorBlueprintFunctionLibrary.cpp File Reference
ActorBlueprintFunctionLibrary.cpp File Reference
#include "Carla.h"
#include "Carla/Actor/ActorBlueprintFunctionLibrary.h"
#include "Carla/Sensor/LidarDescription.h"
#include "Carla/Sensor/SceneCaptureSensor.h"
#include "Carla/Sensor/ShaderBasedSensor.h"
#include "Carla/Util/ScopedStack.h"
#include <algorithm>
#include <limits>
#include <stack>
Classes
class FActorDefinitionValidator
Checks validity of FActorDefinition.
Macros
#define CARLA_ABFL_CHECK_ACTOR(ActorPtr) check((ActorPtr != nullptr) && !ActorPtr->IsPendingKill());
============================================================================
– Helpers to set Actors ------------------------------------------------—
Functions
static void AddRecommendedValuesForActorRoleName (FActorDefinition &Definition, TArray< FString > &&RecommendedValues)
static void AddRecommendedValuesForSensorRoleNames (FActorDefinition &Definition)
static void AddVariationsForSensor (FActorDefinition &Def)
static void AddVariationsForTrigger (FActorDefinition &Def)
static FString ColorToFString (const FColor &Color)
template<typename T , typename Functor >
static void FillActorDefinitionArray (const TArray< T > &ParameterArray, TArray< FActorDefinition > &Definitions, Functor Maker)
template<typename... TStrs>
static void FillIdAndTags (FActorDefinition &Def, TStrs &&...Strings)
============================================================================
– Helpers to create actor definitions ----------------------------------—
template<typename... ARGS>
static FString JoinStrings (const FString &Separator, ARGS &&...Args)
Macro Definition Documentation
#define CARLA_ABFL_CHECK_ACTOR (ActorPtr) check((ActorPtr != nullptr) && !ActorPtr->IsPendingKill());
============================================================================
– Helpers to set Actors ------------------------------------------------—
Definition at line 1308 of file ActorBlueprintFunctionLibrary.cpp.
Referenced by UActorBlueprintFunctionLibrary::SetCamera(), UActorBlueprintFunctionLibrary::SetGnss(), UActorBlueprintFunctionLibrary::SetIMU(), and UActorBlueprintFunctionLibrary::SetRadar().
Function Documentation
static void AddRecommendedValuesForActorRoleName (FActorDefinition & Definition, TArray< FString > && RecommendedValues) static
Definition at line 207 of file ActorBlueprintFunctionLibrary.cpp.
References FActorDefinition::Variations.
Referenced by AddRecommendedValuesForSensorRoleNames(), UActorBlueprintFunctionLibrary::MakePedestrianDefinition(), UActorBlueprintFunctionLibrary::MakePropDefinition(), and UActorBlueprintFunctionLibrary::MakeVehicleDefinition().
static void AddRecommendedValuesForSensorRoleNames (FActorDefinition & Definition) static
Definition at line 221 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForActorRoleName().
Referenced by UActorBlueprintFunctionLibrary::MakeCameraDefinition(), UActorBlueprintFunctionLibrary::MakeGenericSensorDefinition(), and UActorBlueprintFunctionLibrary::MakeLidarDefinition().
static void AddVariationsForSensor (FActorDefinition & Def) static
Definition at line 227 of file ActorBlueprintFunctionLibrary.cpp.
References FActorVariation::bRestrictToRecommended, Float, FActorVariation::Id, FActorVariation::RecommendedValues, FActorVariation::Type, and FActorDefinition::Variations.
Referenced by UActorBlueprintFunctionLibrary::MakeCameraDefinition(), UActorBlueprintFunctionLibrary::MakeGnssDefinition(), UActorBlueprintFunctionLibrary::MakeIMUDefinition(), UActorBlueprintFunctionLibrary::MakeLidarDefinition(), UActorBlueprintFunctionLibrary::MakeObstacleDetectorDefinitions(), and UActorBlueprintFunctionLibrary::MakeRadarDefinition().
static void AddVariationsForTrigger (FActorDefinition & Def) static
Definition at line 239 of file ActorBlueprintFunctionLibrary.cpp.
References FActorVariation::bRestrictToRecommended, Float, FActorVariation::Id, JoinStrings(), FActorVariation::RecommendedValues, FActorVariation::Type, and FActorDefinition::Variations.
Referenced by UActorBlueprintFunctionLibrary::MakeTriggerDefinition().
static FString ColorToFString (const FColor & Color) static
Definition at line 164 of file ActorBlueprintFunctionLibrary.cpp.
References JoinStrings().
Referenced by UActorBlueprintFunctionLibrary::MakeVehicleDefinition().
template<typename T , typename Functor > static void FillActorDefinitionArray (const TArray< T > & ParameterArray, TArray< FActorDefinition > & Definitions, Functor Maker) static
Definition at line 963 of file ActorBlueprintFunctionLibrary.cpp.
Referenced by UActorBlueprintFunctionLibrary::MakePedestrianDefinitions(), UActorBlueprintFunctionLibrary::MakePropDefinitions(), UActorBlueprintFunctionLibrary::MakeTriggerDefinitions(), and UActorBlueprintFunctionLibrary::MakeVehicleDefinitions().
template<typename... TStrs> static void FillIdAndTags (FActorDefinition & Def, TStrs &&... Strings) static
============================================================================
– Helpers to create actor definitions ----------------------------------—
Definition at line 194 of file ActorBlueprintFunctionLibrary.cpp.
References FActorVariation::bRestrictToRecommended, FActorDefinition::Id, FActorVariation::Id, JoinStrings(), FActorVariation::RecommendedValues, String, FActorDefinition::Tags, FActorVariation::Type, and FActorDefinition::Variations.
Referenced by UActorBlueprintFunctionLibrary::MakeCameraDefinition(), UActorBlueprintFunctionLibrary::MakeGenericDefinition(), UActorBlueprintFunctionLibrary::MakeGnssDefinition(), UActorBlueprintFunctionLibrary::MakeIMUDefinition(), UActorBlueprintFunctionLibrary::MakeLidarDefinition(), UActorBlueprintFunctionLibrary::MakePedestrianDefinition(), UActorBlueprintFunctionLibrary::MakePropDefinition(), UActorBlueprintFunctionLibrary::MakeRadarDefinition(), UActorBlueprintFunctionLibrary::MakeTriggerDefinition(), and UActorBlueprintFunctionLibrary::MakeVehicleDefinition().
template<typename... ARGS> static FString JoinStrings (const FString & Separator, ARGS &&... Args) static
Definition at line 159 of file ActorBlueprintFunctionLibrary.cpp.
Referenced by AddVariationsForTrigger(), ColorToFString(), and FillIdAndTags().