CARLA: ARayCastSemanticLidar Class Reference
ARayCastSemanticLidar Class Reference
A ray-cast based Lidar sensor.
#include <RayCastSemanticLidar.h>
Public Member Functions
ARayCastSemanticLidar (const FObjectInitializer &ObjectInitializer)
virtual void Set (const FActorDescription &Description) override
virtual void Set (const FLidarDescription &LidarDescription)
Public Member Functions inherited from ASensor
ASensor (const FObjectInitializer &ObjectInitializer)
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
Static Public Member Functions
static FActorDefinition GetSensorDefinition ()
Protected Types
using FSemanticDetection = carla::sensor::data::SemanticLidarDetection
using FSemanticLidarData = carla::sensor::data::SemanticLidarData
Protected Member Functions
virtual void ComputeAndSaveDetections (const FTransform &SensorTransform)
This method uses all the saved FHitResults, compute the RawDetections and then send it to the LidarData structure.
void ComputeRawDetection (const FHitResult &HitInfo, const FTransform &SensorTransf, FSemanticDetection &Detection) const
Compute all raw detection information.
void CreateLasers ()
Creates a Laser for each channel.
virtual bool PreprocessRay () const
Method that allow to preprocess the ray before shoot it.
void ResetRecordedHits (uint32_t Channels, uint32_t MaxPointsPerChannel)
Clear the recorded data structure.
bool ShootLaser (const float VerticalAngle, float HorizontalAngle, FHitResult &HitResult) const
Shoot a laser ray-trace, return whether the laser hit something.
void SimulateLidar (float DeltaTime)
Updates LidarMeasurement with the points read in DeltaTime.
virtual void Tick (float DeltaTime) override
void WritePointAsync (uint32_t Channel, FHitResult &Detection)
Saving the hits the raycast returns per channel.
Protected Member Functions inherited from ASensor
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
const UCarlaEpisode & GetEpisode () const
void PostActorCreated () override
Protected Attributes
FLidarDescription Description
TArray< float > LaserAngles
std::vector< uint32_t > PointsPerChannel
std::vector< std::vector< FHitResult > > RecordedHits
Protected Attributes inherited from ASensor
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Private Attributes
FSemanticLidarData SemanticLidarData
Detailed Description
A ray-cast based Lidar sensor.
Definition at line 25 of file RayCastSemanticLidar.h.
Member Typedef Documentation
FSemanticDetection
using ARayCastSemanticLidar::FSemanticDetection = carla::sensor::data::SemanticLidarDetection protected
Definition at line 32 of file RayCastSemanticLidar.h.
FSemanticLidarData
using ARayCastSemanticLidar::FSemanticLidarData = carla::sensor::data::SemanticLidarData protected
Definition at line 31 of file RayCastSemanticLidar.h.
Constructor & Destructor Documentation
ARayCastSemanticLidar()
ARayCastSemanticLidar::ARayCastSemanticLidar (const FObjectInitializer & ObjectInitializer)
Definition at line 29 of file RayCastSemanticLidar.cpp.
Member Function Documentation
ComputeAndSaveDetections()
void ARayCastSemanticLidar::ComputeAndSaveDetections (const FTransform & SensorTransform) protected virtual
This method uses all the saved FHitResults, compute the RawDetections and then send it to the LidarData structure.
Reimplemented in ARayCastLidar.
Definition at line 139 of file RayCastSemanticLidar.cpp.
References FLidarDescription::Channels, ComputeRawDetection(), Description, PointsPerChannel, RecordedHits, carla::sensor::data::SemanticLidarData::ResetSerPoints(), SemanticLidarData, and carla::sensor::data::SemanticLidarData::WritePointSync().
Referenced by SimulateLidar().
ComputeRawDetection()
void ARayCastSemanticLidar::ComputeRawDetection (const FHitResult & HitInfo, const FTransform & SensorTransf, FSemanticDetection & Detection) const protected
Compute all raw detection information.
Definition at line 153 of file RayCastSemanticLidar.cpp.
References carla::sensor::data::SemanticLidarDetection::cos_inc_angle, FActorInfo::Description, FActorRegistry::Find(), FActorView::GetActorInfo(), UCarlaEpisode::GetActorRegistry(), ASensor::GetEpisode(), FActorView::IsValid(), carla::rpc::None, carla::sensor::data::SemanticLidarDetection::object_idx, carla::sensor::data::SemanticLidarDetection::object_tag, carla::sensor::data::SemanticLidarDetection::point, and FActorDescription::UId.
Referenced by ComputeAndSaveDetections().
CreateLasers()
void ARayCastSemanticLidar::CreateLasers () protected
Creates a Laser for each channel.
Definition at line 51 of file RayCastSemanticLidar.cpp.
References FLidarDescription::Channels, Description, LaserAngles, FLidarDescription::LowerFovLimit, and FLidarDescription::UpperFovLimit.
Referenced by ARayCastLidar::Set(), and Set().
GetSensorDefinition()
FActorDefinition ARayCastSemanticLidar::GetSensorDefinition () static
Definition at line 24 of file RayCastSemanticLidar.cpp.
References UActorBlueprintFunctionLibrary::MakeLidarDefinition().
PreprocessRay()
virtual bool ARayCastSemanticLidar::PreprocessRay () const inline protected virtual
Method that allow to preprocess the ray before shoot it.
Reimplemented in ARayCastLidar.
Definition at line 55 of file RayCastSemanticLidar.h.
Referenced by SimulateLidar().
ResetRecordedHits()
void ARayCastSemanticLidar::ResetRecordedHits (uint32_t Channels, uint32_t MaxPointsPerChannel) protected
Clear the recorded data structure.
Definition at line 126 of file RayCastSemanticLidar.cpp.
References RecordedHits.
Referenced by SimulateLidar().
Set() [1/2]
void ARayCastSemanticLidar::Set (const FActorDescription & Description) override virtual
Reimplemented from ASensor.
Reimplemented in ARayCastLidar.
Definition at line 35 of file RayCastSemanticLidar.cpp.
References UActorBlueprintFunctionLibrary::SetLidar().
Set() [2/2]
void ARayCastSemanticLidar::Set (const FLidarDescription & LidarDescription) virtual
Reimplemented in ARayCastLidar.
Definition at line 43 of file RayCastSemanticLidar.cpp.
References FLidarDescription::Channels, CreateLasers(), Description, PointsPerChannel, and SemanticLidarData.
ShootLaser()
bool ARayCastSemanticLidar::ShootLaser (const float VerticalAngle, float HorizontalAngle, FHitResult & HitResult) const protected
Shoot a laser ray-trace, return whether the laser hit something.
Definition at line 186 of file RayCastSemanticLidar.cpp.
References Description, and FLidarDescription::Range.
Referenced by SimulateLidar().
SimulateLidar()
void ARayCastSemanticLidar::SimulateLidar (float DeltaTime) protected
Updates LidarMeasurement with the points read in DeltaTime.
Definition at line 77 of file RayCastSemanticLidar.cpp.
References FLidarDescription::Channels, ComputeAndSaveDetections(), Description, carla::sensor::data::SemanticLidarData::GetHorizontalAngle(), LaserAngles, FLidarDescription::PointsPerSecond, PreprocessRay(), ResetRecordedHits(), FLidarDescription::RotationFrequency, SemanticLidarData, carla::sensor::data::SemanticLidarData::SetHorizontalAngle(), ShootLaser(), carla::geom::Math::ToDegrees(), carla::geom::Math::ToRadians(), and WritePointAsync().
Referenced by Tick(), and ARayCastLidar::Tick().
Tick()
void ARayCastSemanticLidar::Tick (float DeltaTime) override protected virtual
Reimplemented in ARayCastLidar.
Definition at line 67 of file RayCastSemanticLidar.cpp.
References ASensor::GetDataStream(), SemanticLidarData, and SimulateLidar().
WritePointAsync()
void ARayCastSemanticLidar::WritePointAsync (uint32_t Channel, FHitResult & Detection) protected
Saving the hits the raycast returns per channel.
Definition at line 134 of file RayCastSemanticLidar.cpp.
References DEBUG_ASSERT, and RecordedHits.
Referenced by SimulateLidar().
Member Data Documentation
Description
FLidarDescription ARayCastSemanticLidar::Description protected
Definition at line 75 of file RayCastSemanticLidar.h.
Referenced by ARayCastLidar::ComputeAndSaveDetections(), ComputeAndSaveDetections(), ARayCastLidar::ComputeDetection(), ARayCastLidar::ComputeIntensity(), CreateLasers(), ARayCastLidar::PostprocessDetection(), ARayCastLidar::PreprocessRay(), ARayCastLidar::Set(), Set(), ShootLaser(), and SimulateLidar().
LaserAngles
TArray<float> ARayCastSemanticLidar::LaserAngles protected
Definition at line 77 of file RayCastSemanticLidar.h.
Referenced by CreateLasers(), and SimulateLidar().
PointsPerChannel
std::vector<uint32_t> ARayCastSemanticLidar::PointsPerChannel protected
Definition at line 80 of file RayCastSemanticLidar.h.
Referenced by ARayCastLidar::ComputeAndSaveDetections(), ComputeAndSaveDetections(), ARayCastLidar::Set(), and Set().
RecordedHits
std::vector<std::vector<FHitResult> > ARayCastSemanticLidar::RecordedHits protected
Definition at line 79 of file RayCastSemanticLidar.h.
Referenced by ARayCastLidar::ComputeAndSaveDetections(), ComputeAndSaveDetections(), ResetRecordedHits(), and WritePointAsync().
SemanticLidarData
FSemanticLidarData ARayCastSemanticLidar::SemanticLidarData private
Definition at line 83 of file RayCastSemanticLidar.h.
Referenced by ComputeAndSaveDetections(), Set(), SimulateLidar(), and Tick().
The documentation for this class was generated from the following files:
RayCastSemanticLidar.h
RayCastSemanticLidar.cpp