CARLA: UMapGenFunctionLibrary Class Reference
UMapGenFunctionLibrary Class Reference
#include <MapGenFunctionLibrary.h>
Static Public Member Functions
static FMeshDescription BuildMeshDescriptionFromData (const FProceduralCustomMesh &Data, const TArray< FProcMeshTangent > &ParamTangents, UMaterialInstance *MaterialInstance)
static void CleanupGEngine ()
static UStaticMesh * CreateMesh (const FProceduralCustomMesh &Data, const TArray< FProcMeshTangent > &ParamTangents, UMaterialInstance *MaterialInstance, FString MapName, FString FolderName, FName MeshName)
static void FlushRenderingCommandsInBlueprint ()
static FVector2D GetTransversemercProjection (float lat, float lon, float lat0, float lon0)
static void SetThreadToSleep (float seconds)
Detailed Description
Definition at line 25 of file MapGenFunctionLibrary.h.
Member Function Documentation
BuildMeshDescriptionFromData()
FMeshDescription UMapGenFunctionLibrary::BuildMeshDescriptionFromData (const FProceduralCustomMesh & Data, const TArray< FProcMeshTangent > & ParamTangents, UMaterialInstance * MaterialInstance) static
Definition at line 22 of file MapGenFunctionLibrary.cpp.
References FProceduralCustomMesh::Normals, FProceduralCustomMesh::Triangles, FProceduralCustomMesh::UV0, and FProceduralCustomMesh::Vertices.
Referenced by CreateMesh().
CleanupGEngine()
void UMapGenFunctionLibrary::CleanupGEngine () static
Definition at line 218 of file MapGenFunctionLibrary.cpp.
CreateMesh()
UStaticMesh * UMapGenFunctionLibrary::CreateMesh (const FProceduralCustomMesh & Data, const TArray< FProcMeshTangent > & ParamTangents, UMaterialInstance * MaterialInstance, FString MapName, FString FolderName, FName MeshName) static
Definition at line 138 of file MapGenFunctionLibrary.cpp.
References BuildMeshDescriptionFromData(), and carla::client::detail::Get().
FlushRenderingCommandsInBlueprint()
void UMapGenFunctionLibrary::FlushRenderingCommandsInBlueprint () static
Definition at line 213 of file MapGenFunctionLibrary.cpp.
GetTransversemercProjection()
FVector2D UMapGenFunctionLibrary::GetTransversemercProjection (float lat, float lon, float lat0, float lon0) static
Definition at line 189 of file MapGenFunctionLibrary.cpp.
References OSMToCentimetersScaleFactor.
SetThreadToSleep()
void UMapGenFunctionLibrary::SetThreadToSleep (float seconds) static
Definition at line 209 of file MapGenFunctionLibrary.cpp.
The documentation for this class was generated from the following files:
MapGenFunctionLibrary.h
MapGenFunctionLibrary.cpp