CARLA: util::buffer Namespace Reference
util::buffer Namespace Reference
Typedefs
using const_shared_buffer = std::shared_ptr< const Buffer >
using shared_buffer = std::shared_ptr< Buffer >
Functions
static std::string as_string (const Buffer &buf)
template<typename T >
static shared_buffer make (const T &buffer)
static shared_buffer make_empty (size_t size=0u)
shared_buffer make_random (size_t size)
std::string to_hex_string (const Buffer &buf, size_t length)
Typedef Documentation
using util::buffer::const_shared_buffer = typedef std::shared_ptr<const Buffer>
Definition at line 22 of file test/Buffer.h.
using util::buffer::shared_buffer = typedef std::shared_ptr<Buffer>
Definition at line 21 of file test/Buffer.h.
Function Documentation
static std::string util::buffer::as_string (const Buffer & buf) inline static
Definition at line 37 of file test/Buffer.h.
References carla::Buffer::data(), carla::Buffer::size(), and to_hex_string().
Referenced by TEST().
template<typename T > static shared_buffer util::buffer::make (const T & buffer) inline static
Definition at line 33 of file test/Buffer.h.
Referenced by carla::image::ImageView::color_converted_type< SrcView, DstP, CC >::make().
static shared_buffer util::buffer::make_empty (size_t size = 0u) inline static
Definition at line 24 of file test/Buffer.h.
References make_random().
Referenced by make_random(), and TEST().
shared_buffer util::buffer::make_random (size_t size)
Definition at line 17 of file test/Buffer.cpp.
References make_empty().
Referenced by make_empty(), and TEST().
std::string util::buffer::to_hex_string (const Buffer & buf, size_t length)
Definition at line 30 of file test/Buffer.cpp.
References carla::Buffer::data(), and carla::Buffer::size().
Referenced by as_string(), and carla::operator<<().