CARLA: carla::nav::WalkerManager Class Reference
carla::nav::WalkerManager Class Reference
#include <WalkerManager.h>
Public Member Functions
bool AddWalker (ActorId id)
create a new walker route
Navigation * GetNavigation ()
return the navigation object
bool GetWalkerCrosswalkEnd (ActorId id, carla::geom::Location &location)
get the point in the route that end current crosswalk
bool GetWalkerNextPoint (ActorId id, carla::geom::Location &location)
get the next point in the route
bool RemoveWalker (ActorId id)
remove a walker route
void SetNav (Navigation *nav)
assign the navigation module
bool SetWalkerNextPoint (ActorId id)
set the next point in the route
bool SetWalkerRoute (ActorId id)
set a new route from its current position
bool SetWalkerRoute (ActorId id, carla::geom::Location to)
bool Update (double delta)
update all routes
WalkerManager ()
~WalkerManager ()
Private Member Functions
EventResult ExecuteEvent (ActorId id, WalkerInfo &info, double delta)
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Private Attributes
Navigation * _nav { nullptr }
std::unordered_map< ActorId, WalkerInfo > _walkers
Detailed Description
Definition at line 42 of file WalkerManager.h.
Constructor & Destructor Documentation
WalkerManager()
carla::nav::WalkerManager::WalkerManager ()
Definition at line 13 of file WalkerManager.cpp.
References _nav.
~WalkerManager()
carla::nav::WalkerManager::~WalkerManager ()
Definition at line 17 of file WalkerManager.cpp.
Member Function Documentation
AddWalker()
bool carla::nav::WalkerManager::AddWalker (ActorId id)
create a new walker route
Definition at line 21 of file WalkerManager.cpp.
References _walkers, carla::nav::WalkerInfo::state, and carla::nav::WALKER_IDLE.
Referenced by carla::nav::Navigation::AddWalker().
ExecuteEvent()
EventResult carla::nav::WalkerManager::ExecuteEvent (ActorId id, WalkerInfo & info, double delta) private
Definition at line 250 of file WalkerManager.cpp.
References carla::nav::WalkerInfo::currentIndex, carla::nav::WalkerRoutePoint::event, and carla::nav::WalkerInfo::route.
Referenced by Update().
GetNavigation()
Navigation* carla::nav::WalkerManager::GetNavigation () inline
return the navigation object
Definition at line 75 of file WalkerManager.h.
Referenced by carla::nav::WalkerEventVisitor::operator()().
GetWalkerCrosswalkEnd()
bool carla::nav::WalkerManager::GetWalkerCrosswalkEnd (ActorId id, carla::geom::Location & location)
get the point in the route that end current crosswalk
Definition at line 224 of file WalkerManager.cpp.
References _nav, _walkers, carla::nav::CARLA_AREA_CROSSWALK, carla::nav::WalkerInfo::currentIndex, and carla::nav::WalkerInfo::route.
Referenced by carla::nav::WalkerEventVisitor::operator()().
GetWalkerNextPoint()
bool carla::nav::WalkerManager::GetWalkerNextPoint (ActorId id, carla::geom::Location & location)
get the next point in the route
Definition at line 202 of file WalkerManager.cpp.
References _nav, _walkers, carla::nav::WalkerInfo::currentIndex, and carla::nav::WalkerInfo::route.
RemoveWalker()
bool carla::nav::WalkerManager::RemoveWalker (ActorId id)
remove a walker route
Definition at line 32 of file WalkerManager.cpp.
References _walkers.
Referenced by carla::nav::Navigation::RemoveAgent().
SetNav()
void carla::nav::WalkerManager::SetNav (Navigation * nav) inline
assign the navigation module
Definition at line 50 of file WalkerManager.h.
References carla::nav::WalkerRoutePoint::location.
Referenced by carla::nav::Navigation::Navigation().
SetWalkerNextPoint()
bool carla::nav::WalkerManager::SetWalkerNextPoint (ActorId id)
set the next point in the route
Definition at line 167 of file WalkerManager.cpp.
References _nav, _walkers, carla::nav::WalkerInfo::currentIndex, carla::nav::Navigation::PauseAgent(), carla::nav::WalkerInfo::route, carla::nav::Navigation::SetWalkerDirectTarget(), SetWalkerRoute(), carla::nav::WalkerInfo::state, carla::nav::WALKER_STOP, and carla::nav::WALKER_WALKING.
Referenced by SetWalkerRoute(), and Update().
SetWalkerRoute() [1/2]
bool carla::nav::WalkerManager::SetWalkerRoute (ActorId id)
set a new route from its current position
Definition at line 97 of file WalkerManager.cpp.
References _nav, and carla::nav::Navigation::GetRandomLocation().
Referenced by SetWalkerNextPoint(), carla::nav::Navigation::SetWalkerTarget(), Update(), and carla::nav::Navigation::UpdateCrowd().
SetWalkerRoute() [2/2]
bool carla::nav::WalkerManager::SetWalkerRoute (ActorId id, carla::geom::Location to)
Definition at line 111 of file WalkerManager.cpp.
References _nav, _walkers, carla::nav::CARLA_AREA_CROSSWALK, carla::nav::CARLA_AREA_ROAD, carla::nav::CARLA_AREA_SIDEWALK, carla::nav::WalkerInfo::currentIndex, carla::nav::WalkerInfo::from, carla::nav::Navigation::GetAgentRoute(), carla::nav::Navigation::GetWalkerPosition(), carla::nav::WalkerInfo::route, SetWalkerNextPoint(), carla::nav::WalkerInfo::state, carla::nav::WalkerInfo::to, and carla::nav::WALKER_IDLE.
Update()
bool carla::nav::WalkerManager::Update (double delta)
update all routes
Definition at line 43 of file WalkerManager.cpp.
References _nav, _walkers, carla::nav::Continue, carla::nav::WalkerInfo::currentIndex, carla::nav::End, ExecuteEvent(), carla::nav::Navigation::GetWalkerPosition(), carla::nav::Navigation::PauseAgent(), carla::nav::WalkerInfo::route, SetWalkerNextPoint(), SetWalkerRoute(), carla::geom::Vector3D::SquaredLength(), carla::nav::WalkerInfo::state, carla::nav::TimeOut, carla::nav::WALKER_IDLE, carla::nav::WALKER_IN_EVENT, carla::nav::WALKER_STOP, carla::nav::WALKER_WALKING, carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by carla::nav::Navigation::UpdateCrowd().
Member Data Documentation
_nav
Navigation* carla::nav::WalkerManager::_nav { nullptr } private
Definition at line 82 of file WalkerManager.h.
Referenced by GetWalkerCrosswalkEnd(), GetWalkerNextPoint(), SetWalkerNextPoint(), SetWalkerRoute(), Update(), and WalkerManager().
_walkers
std::unordered_map<ActorId, WalkerInfo> carla::nav::WalkerManager::_walkers private
Definition at line 81 of file WalkerManager.h.
Referenced by AddWalker(), GetWalkerCrosswalkEnd(), GetWalkerNextPoint(), RemoveWalker(), SetWalkerNextPoint(), SetWalkerRoute(), and Update().
The documentation for this class was generated from the following files:
WalkerManager.h
WalkerManager.cpp