CARLA: carla::geom::Transform Class Reference
carla::geom::Transform Class Reference
#include <Transform.h>
Public Member Functions
Vector3D GetForwardVector () const
std::array< float, 16 > GetInverseMatrix () const
Computes the 4-matrix form of the inverse transformation.
std::array< float, 16 > GetMatrix () const
Computes the 4-matrix form of the transformation.
Vector3D GetRightVector () const
Vector3D GetUpVector () const
void InverseTransformPoint (Vector3D &in_point) const
Applies the inverse of this transformation to in_point.
MSGPACK_DEFINE_ARRAY (location, rotation)
bool operator!= (const Transform &rhs) const
bool operator== (const Transform &rhs) const
Transform ()=default
Transform (const Location &in_location)
Transform (const Location &in_location, const Rotation &in_rotation)
void TransformPoint (Vector3D &in_point) const
Applies this transformation to in_point (first translation then rotation).
void TransformVector (Vector3D &in_vector) const
Applies this transformation to in_vector (rotation only).
Public Attributes
Location location
Rotation rotation
Detailed Description
Definition at line 21 of file geom/Transform.h.
Constructor & Destructor Documentation
Transform() [1/3]
carla::geom::Transform::Transform () default
Referenced by operator!=().
Transform() [2/3]
carla::geom::Transform::Transform (const Location & in_location) inline
Definition at line 40 of file geom/Transform.h.
Transform() [3/3]
carla::geom::Transform::Transform (const Location & in_location, const Rotation & in_rotation) inline
Definition at line 44 of file geom/Transform.h.
Member Function Documentation
GetForwardVector()
Vector3D carla::geom::Transform::GetForwardVector () const inline
Definition at line 52 of file geom/Transform.h.
References carla::geom::Rotation::GetForwardVector().
Referenced by carla::road::Map::CreateRtree(), carla::client::TrafficLight::GetStopWaypoints(), carla::traffic_manager::TrafficLightStage::HandleNonSignalisedJunction(), and carla::traffic_manager::MotionPlanStage::Update().
GetInverseMatrix()
std::array<float, 16> carla::geom::Transform::GetInverseMatrix () const inline
Computes the 4-matrix form of the inverse transformation.
Definition at line 111 of file geom/Transform.h.
References InverseTransformPoint(), carla::geom::Rotation::pitch, carla::geom::Rotation::roll, carla::geom::Math::ToRadians(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, carla::geom::Rotation::yaw, and carla::geom::Vector3D::z.
GetMatrix()
std::array<float, 16> carla::geom::Transform::GetMatrix () const inline
Computes the 4-matrix form of the transformation.
Definition at line 88 of file geom/Transform.h.
References carla::geom::Rotation::pitch, carla::geom::Rotation::roll, carla::geom::Math::ToRadians(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, carla::geom::Rotation::yaw, and carla::geom::Vector3D::z.
GetRightVector()
Vector3D carla::geom::Transform::GetRightVector () const inline
Definition at line 56 of file geom/Transform.h.
References carla::geom::Rotation::GetRightVector().
GetUpVector()
Vector3D carla::geom::Transform::GetUpVector () const inline
Definition at line 60 of file geom/Transform.h.
References carla::geom::Rotation::GetUpVector().
InverseTransformPoint()
void carla::geom::Transform::InverseTransformPoint (Vector3D & in_point) const inline
Applies the inverse of this transformation to in_point.
Definition at line 80 of file geom/Transform.h.
References carla::geom::Rotation::InverseRotateVector(), and location.
Referenced by carla::geom::BoundingBox::Contains(), GetInverseMatrix(), and TEST().
MSGPACK_DEFINE_ARRAY()
carla::geom::Transform::MSGPACK_DEFINE_ARRAY (location , rotation)
operator!=()
bool carla::geom::Transform::operator!= (const Transform & rhs) const inline
Definition at line 144 of file geom/Transform.h.
References Transform().
operator==()
bool carla::geom::Transform::operator== (const Transform & rhs) const inline
Definition at line 140 of file geom/Transform.h.
References location, and rotation.
TransformPoint()
void carla::geom::Transform::TransformPoint (Vector3D & in_point) const inline
Applies this transformation to in_point (first translation then rotation).
Definition at line 65 of file geom/Transform.h.
References location, and carla::geom::Rotation::RotateVector().
Referenced by carla::road::Map::GetAllCrosswalkZones(), carla::client::TrafficLight::GetStopWaypoints(), carla::geom::BoundingBox::GetWorldVertices(), and TEST().
TransformVector()
void carla::geom::Transform::TransformVector (Vector3D & in_vector) const inline
Applies this transformation to in_vector (rotation only).
Definition at line 73 of file geom/Transform.h.
References carla::geom::Rotation::RotateVector().
Member Data Documentation
location
Location carla::geom::Transform::location
Definition at line 28 of file geom/Transform.h.
Referenced by carla::road::Map::AddElementToRtree(), carla::nav::Navigation::AddOrUpdateVehicle(), carla::rss::RssCheck::AppendRoutingTarget(), carla::road::MapBuilder::CreateJunctionBoundingBoxes(), carla::rss::RssCheck::CreateWorldModel(), carla::client::detail::Simulator::GetActorLocation(), carla::road::Map::GetAllCrosswalkZones(), carla::rss::RssCheck::GetRoutingTargets(), carla::nav::Navigation::GetWalkerTransform(), carla::traffic_manager::TrafficLightStage::HandleNonSignalisedJunction(), InverseTransformPoint(), carla::client::LaneInvasionCallback::MakeBounds(), operator==(), carla::client::detail::Client::SpawnActorWithParent(), TransformPoint(), carla::traffic_manager::MotionPlanStage::Update(), carla::traffic_manager::ALSM::UpdateData(), and carla::traffic_manager::ALSM::UpdateUnregisteredActorsData().
rotation
Rotation carla::geom::Transform::rotation
Definition at line 30 of file geom/Transform.h.
Referenced by carla::nav::Navigation::AddOrUpdateVehicle(), carla::road::Map::GetAllCrosswalkZones(), carla::rss::RssCheck::GetSpeed(), carla::nav::Navigation::GetWalkerTransform(), carla::client::LaneInvasionCallback::MakeBounds(), operator==(), carla::traffic_manager::MotionPlanStage::Update(), carla::traffic_manager::ALSM::UpdateData(), and carla::traffic_manager::ALSM::UpdateUnregisteredActorsData().
The documentation for this class was generated from the following file:
geom/Transform.h