CARLA: carla::traffic_manager::Parameters Class Reference
carla::traffic_manager::Parameters Class Reference
#include <Parameters.h>
Public Member Functions
bool GetAutoLaneChange (const ActorId &actor_id) const
Method to query auto lane change rule for a vehicle.
bool GetCollisionDetection (const ActorId &reference_actor_id, const ActorId &other_actor_id) const
Method to query collision avoidance rule between a pair of vehicles.
Path GetCustomPath (const ActorId &actor_id) const
Method to get a custom path.
float GetDistanceToLeadingVehicle (const ActorId &actor_id) const
Method to query distance to leading vehicle for a given vehicle.
ChangeLaneInfo GetForceLaneChange (const ActorId &actor_id)
Method to query lane change command for a vehicle.
bool GetHybridPhysicsMode () const
Method to retrieve hybrid physics mode.
float GetHybridPhysicsRadius () const
Method to retrieve hybrid physics radius.
Route GetImportedRoute (const ActorId &actor_id) const
Method to get a custom route.
float GetKeepRightPercentage (const ActorId &actor_id)
Method to query percentage probability of keep right rule for a vehicle.
float GetLowerBoundaryRespawnDormantVehicles () const
Method to retrieve minimum distance from hero vehicle when respawning vehicles.
bool GetOSMMode () const
Method to get Open Street Map mode.
float GetPercentageIgnoreVehicles (const ActorId &actor_id) const
Method to get % to ignore any vehicle.
float GetPercentageIgnoreWalkers (const ActorId &actor_id) const
Method to get % to ignore any walker.
float GetPercentageRunningLight (const ActorId &actor_id) const
Method to get % to run any traffic light.
float GetPercentageRunningSign (const ActorId &actor_id) const
Method to get % to run any traffic light.
float GetRandomLeftLaneChangePercentage (const ActorId &actor_id)
Method to query percentage probability of a random right lane change for a vehicle.
float GetRandomRightLaneChangePercentage (const ActorId &actor_id)
Method to query percentage probability of a random left lane change for a vehicle.
bool GetRespawnDormantVehicles () const
Method to retrieve if we are automatically respawning vehicles.
bool GetSynchronousMode () const
Method to get synchronous mode.
double GetSynchronousModeTimeOutInMiliSecond () const
Get synchronous mode time out.
bool GetUpdateVehicleLightState (const ActorId &actor_id) const
Method to get if the vehicle lights should be updates automatically.
bool GetUploadPath (const ActorId &actor_id) const
Method to get if we are uploading a path.
bool GetUploadRoute (const ActorId &actor_id) const
Method to get if we are uploading a route.
float GetUpperBoundaryRespawnDormantVehicles () const
Method to retrieve maximum distance from hero vehicle when respawning vehicles.
float GetVehicleTargetVelocity (const ActorId &actor_id, const float speed_limit) const
Method to query target velocity for a vehicle.
Parameters ()
void RemoveImportedRoute (const ActorId &actor_id, const bool remove_path)
Method to remove a route.
void RemoveUploadPath (const ActorId &actor_id, const bool remove_path)
Method to remove a list of points.
void SetAutoLaneChange (const ActorPtr &actor, const bool enable)
Enable/disable automatic lane change on a vehicle.
void SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound)
Method to set boundaries for respawning vehicles.
void SetCollisionDetection (const ActorPtr &reference_actor, const ActorPtr &other_actor, const bool detect_collision)
Method to set collision detection rules between vehicles.
void SetCustomPath (const ActorPtr &actor, const Path path, const bool empty_buffer)
Method to set our own imported path.
void SetDistanceToLeadingVehicle (const ActorPtr &actor, const float distance)
Method to specify how much distance a vehicle should maintain to the leading vehicle.
void SetForceLaneChange (const ActorPtr &actor, const bool direction)
Method to force lane change on a vehicle.
void SetGlobalDistanceToLeadingVehicle (const float dist)
Method to set the distance to leading vehicle for all registered vehicles.
void SetGlobalPercentageSpeedDifference (float const percentage)
Set a global % decrease in velocity with respect to the speed limit.
void SetHybridPhysicsMode (const bool mode_switch)
Method to set hybrid physics mode.
void SetHybridPhysicsRadius (const float radius)
Method to set hybrid physics radius.
void SetImportedRoute (const ActorPtr &actor, const Route route, const bool empty_buffer)
Method to set our own imported route.
void SetKeepRightPercentage (const ActorPtr &actor, const float percentage)
Method to set % to keep on the right lane.
void SetMaxBoundaries (const float lower, const float upper)
Method to set limits for boundaries when respawning vehicles.
void SetOSMMode (const bool mode_switch)
Method to set Open Street Map mode.
void SetPercentageIgnoreVehicles (const ActorPtr &actor, const float perc)
Method to set % to ignore any vehicle.
void SetPercentageIgnoreWalkers (const ActorPtr &actor, const float perc)
Method to set % to ignore any vehicle.
void SetPercentageRunningLight (const ActorPtr &actor, const float perc)
Method to set % to run any traffic light.
void SetPercentageRunningSign (const ActorPtr &actor, const float perc)
Method to set % to run any traffic sign.
void SetPercentageSpeedDifference (const ActorPtr &actor, const float percentage)
Set a vehicle's % decrease in velocity with respect to the speed limit.
void SetRandomLeftLaneChangePercentage (const ActorPtr &actor, const float percentage)
Method to set % to randomly do a left lane change.
void SetRandomRightLaneChangePercentage (const ActorPtr &actor, const float percentage)
Method to set % to randomly do a right lane change.
void SetRespawnDormantVehicles (const bool mode_switch)
Method to set if we are automatically respawning vehicles.
void SetSynchronousMode (const bool mode_switch=true)
Method to set synchronous mode.
void SetSynchronousModeTimeOutInMiliSecond (const double time)
Set Synchronous mode time out.
void SetUpdateVehicleLightState (const ActorPtr &actor, const bool do_update)
Method to set the automatic vehicle light state update flag.
void UpdateImportedRoute (const ActorId &actor_id, const Route route)
Method to update an already set route.
void UpdateUploadPath (const ActorId &actor_id, const Path path)
Method to update an already set list of points.
~Parameters ()
Public Attributes
std::chrono::duration< double, std::milli > synchronous_time_out
Synchronous mode time out variable.
Private Attributes
AtomicMap< ActorId, bool > auto_lane_change
Map containing auto lane change commands.
AtomicMap< ActorId, bool > auto_update_vehicle_lights
Map containing the automatic vehicle lights update flag.
AtomicMap< ActorId, Path > custom_path
Structure to hold all custom paths.
AtomicMap< ActorId, Route > custom_route
Structure to hold all custom routes.
std::atomic< float > distance_margin {2.0}
Distance margin.
AtomicMap< ActorId, float > distance_to_leading_vehicle
Map containing distance to leading vehicle command.
AtomicMap< ActorId, ChangeLaneInfo > force_lane_change
Map containing force lane change commands.
float global_percentage_difference_from_limit = 0
Global target velocity limit % difference.
std::atomic< bool > hybrid_physics_mode {false}
Hybrid physics mode switch.
std::atomic< float > hybrid_physics_radius {70.0}
Hybrid physics radius.
AtomicMap< ActorId, std::shared_ptr< AtomicActorSet > > ignore_collision
Map containing a set of actors to be ignored during collision detection.
float max_upper_bound
Maximum possible distance to respawn vehicles with respect to the hero vehicle.
float min_lower_bound
Minimum possible distance to respawn vehicles with respect to the hero vehicle.
std::atomic< bool > osm_mode {true}
Parameter specifying Open Street Map mode.
AtomicMap< ActorId, float > perc_ignore_vehicles
Map containing % of ignoring vehicles.
AtomicMap< ActorId, float > perc_ignore_walkers
Map containing % of ignoring walkers.
AtomicMap< ActorId, float > perc_keep_right
Map containing % of keep right rule.
AtomicMap< ActorId, float > perc_random_left
Map containing % of random left lane change.
AtomicMap< ActorId, float > perc_random_right
Map containing % of random right lane change.
AtomicMap< ActorId, float > perc_run_traffic_light
Map containing % of running a traffic light.
AtomicMap< ActorId, float > perc_run_traffic_sign
Map containing % of running a traffic sign.
AtomicMap< ActorId, float > percentage_difference_from_speed_limit
Target velocity map for individual vehicles.
std::atomic< bool > respawn_dormant_vehicles {false}
Automatic respawn mode switch.
std::atomic< float > respawn_lower_bound {100.0}
Minimum distance to respawn vehicles with respect to the hero vehicle.
std::atomic< float > respawn_upper_bound {1000.0}
Maximum distance to respawn vehicles with respect to the hero vehicle.
std::atomic< bool > synchronous_mode {false}
Synchronous mode switch.
AtomicMap< ActorId, bool > upload_path
Parameter specifying if importing a custom path.
AtomicMap< ActorId, bool > upload_route
Parameter specifying if importing a custom route.
Detailed Description
Definition at line 37 of file Parameters.h.
Constructor & Destructor Documentation
Parameters()
carla::traffic_manager::Parameters::Parameters ()
Set default synchronous mode time out.
Definition at line 13 of file Parameters.cpp.
References synchronous_time_out.
~Parameters()
carla::traffic_manager::Parameters::~Parameters ()
Definition at line 19 of file Parameters.cpp.
Member Function Documentation
GetAutoLaneChange()
bool carla::traffic_manager::Parameters::GetAutoLaneChange (const ActorId & actor_id) const
Method to query auto lane change rule for a vehicle.
Definition at line 301 of file Parameters.cpp.
References auto_lane_change, carla::traffic_manager::AtomicMap< Key, Value >::Contains(), and carla::traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetCollisionDetection()
bool carla::traffic_manager::Parameters::GetCollisionDetection (const ActorId & reference_actor_id, const ActorId & other_actor_id) const
Method to query collision avoidance rule between a pair of vehicles.
Definition at line 243 of file Parameters.cpp.
References ignore_collision.
Referenced by carla::traffic_manager::CollisionStage::Update().
GetCustomPath()
Path carla::traffic_manager::Parameters::GetCustomPath (const ActorId & actor_id) const
Method to get a custom path.
Definition at line 415 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), custom_path, and carla::traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetDistanceToLeadingVehicle()
float carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle (const ActorId & actor_id) const
Method to query distance to leading vehicle for a given vehicle.
Definition at line 312 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), distance_margin, distance_to_leading_vehicle, and carla::traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by carla::traffic_manager::CollisionStage::GetGeodesicBoundary(), carla::traffic_manager::CollisionStage::NegotiateCollision(), and carla::traffic_manager::CollisionStage::Update().
GetForceLaneChange()
ChangeLaneInfo carla::traffic_manager::Parameters::GetForceLaneChange (const ActorId & actor_id)
Method to query lane change command for a vehicle.
Definition at line 255 of file Parameters.cpp.
References force_lane_change.
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetHybridPhysicsMode()
bool carla::traffic_manager::Parameters::GetHybridPhysicsMode () const
Method to retrieve hybrid physics mode.
Definition at line 378 of file Parameters.cpp.
References hybrid_physics_mode.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run(), and carla::traffic_manager::ALSM::Update().
GetHybridPhysicsRadius()
float carla::traffic_manager::Parameters::GetHybridPhysicsRadius () const
Method to retrieve hybrid physics radius.
Definition at line 219 of file Parameters.cpp.
References hybrid_physics_radius.
Referenced by carla::traffic_manager::ALSM::UpdateRegisteredActorsData().
GetImportedRoute()
Route carla::traffic_manager::Parameters::GetImportedRoute (const ActorId & actor_id) const
Method to get a custom route.
Definition at line 438 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), custom_route, and carla::traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetKeepRightPercentage()
float carla::traffic_manager::Parameters::GetKeepRightPercentage (const ActorId & actor_id)
Method to query percentage probability of keep right rule for a vehicle.
Definition at line 268 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_keep_right.
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetLowerBoundaryRespawnDormantVehicles()
float carla::traffic_manager::Parameters::GetLowerBoundaryRespawnDormantVehicles () const
Method to retrieve minimum distance from hero vehicle when respawning vehicles.
Definition at line 388 of file Parameters.cpp.
References respawn_lower_bound.
Referenced by carla::traffic_manager::MotionPlanStage::Update().
GetOSMMode()
bool carla::traffic_manager::Parameters::GetOSMMode () const
Method to get Open Street Map mode.
Definition at line 399 of file Parameters.cpp.
References osm_mode.
Referenced by carla::traffic_manager::LocalizationStage::ImportPath(), carla::traffic_manager::LocalizationStage::ImportRoute(), carla::traffic_manager::LocalizationStage::Update(), and carla::traffic_manager::ALSM::Update().
GetPercentageIgnoreVehicles()
float carla::traffic_manager::Parameters::GetPercentageIgnoreVehicles (const ActorId & actor_id) const
Method to get % to ignore any vehicle.
Definition at line 367 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_ignore_vehicles.
Referenced by carla::traffic_manager::CollisionStage::Update().
GetPercentageIgnoreWalkers()
float carla::traffic_manager::Parameters::GetPercentageIgnoreWalkers (const ActorId & actor_id) const
Method to get % to ignore any walker.
Definition at line 346 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_ignore_walkers.
Referenced by carla::traffic_manager::CollisionStage::Update().
GetPercentageRunningLight()
float carla::traffic_manager::Parameters::GetPercentageRunningLight (const ActorId & actor_id) const
Method to get % to run any traffic light.
Definition at line 324 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_run_traffic_light.
Referenced by carla::traffic_manager::TrafficLightStage::Update().
GetPercentageRunningSign()
float carla::traffic_manager::Parameters::GetPercentageRunningSign (const ActorId & actor_id) const
Method to get % to run any traffic light.
Definition at line 335 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_run_traffic_sign.
Referenced by carla::traffic_manager::TrafficLightStage::Update().
GetRandomLeftLaneChangePercentage()
float carla::traffic_manager::Parameters::GetRandomLeftLaneChangePercentage (const ActorId & actor_id)
Method to query percentage probability of a random right lane change for a vehicle.
Definition at line 279 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_random_left.
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetRandomRightLaneChangePercentage()
float carla::traffic_manager::Parameters::GetRandomRightLaneChangePercentage (const ActorId & actor_id)
Method to query percentage probability of a random left lane change for a vehicle.
Definition at line 290 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and perc_random_right.
Referenced by carla::traffic_manager::LocalizationStage::Update().
GetRespawnDormantVehicles()
bool carla::traffic_manager::Parameters::GetRespawnDormantVehicles () const
Method to retrieve if we are automatically respawning vehicles.
Definition at line 383 of file Parameters.cpp.
References respawn_dormant_vehicles.
Referenced by carla::traffic_manager::MotionPlanStage::Update(), and carla::traffic_manager::ALSM::UpdateRegisteredActorsData().
GetSynchronousMode()
bool carla::traffic_manager::Parameters::GetSynchronousMode () const
Method to get synchronous mode.
Definition at line 224 of file Parameters.cpp.
References synchronous_mode.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run(), carla::traffic_manager::TrafficManagerLocal::SetSynchronousMode(), carla::traffic_manager::TrafficManagerLocal::Stop(), carla::traffic_manager::TrafficManagerLocal::SynchronousTick(), and carla::traffic_manager::MotionPlanStage::Update().
GetSynchronousModeTimeOutInMiliSecond()
double carla::traffic_manager::Parameters::GetSynchronousModeTimeOutInMiliSecond () const
Get synchronous mode time out.
Definition at line 228 of file Parameters.cpp.
References synchronous_time_out.
GetUpdateVehicleLightState()
bool carla::traffic_manager::Parameters::GetUpdateVehicleLightState (const ActorId & actor_id) const
Method to get if the vehicle lights should be updates automatically.
Definition at line 357 of file Parameters.cpp.
References auto_update_vehicle_lights, carla::traffic_manager::AtomicMap< Key, Value >::Contains(), and carla::traffic_manager::AtomicMap< Key, Value >::GetValue().
Referenced by carla::traffic_manager::VehicleLightStage::Update().
GetUploadPath()
bool carla::traffic_manager::Parameters::GetUploadPath (const ActorId & actor_id) const
Method to get if we are uploading a path.
Definition at line 404 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and upload_path.
Referenced by carla::traffic_manager::LocalizationStage::ImportPath().
GetUploadRoute()
bool carla::traffic_manager::Parameters::GetUploadRoute (const ActorId & actor_id) const
Method to get if we are uploading a route.
Definition at line 427 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and upload_route.
Referenced by carla::traffic_manager::LocalizationStage::ImportRoute().
GetUpperBoundaryRespawnDormantVehicles()
float carla::traffic_manager::Parameters::GetUpperBoundaryRespawnDormantVehicles () const
Method to retrieve maximum distance from hero vehicle when respawning vehicles.
Definition at line 393 of file Parameters.cpp.
References respawn_upper_bound.
Referenced by carla::traffic_manager::MotionPlanStage::Update().
GetVehicleTargetVelocity()
float carla::traffic_manager::Parameters::GetVehicleTargetVelocity (const ActorId & actor_id, const float speed_limit) const
Method to query target velocity for a vehicle.
Definition at line 232 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), global_percentage_difference_from_limit, and percentage_difference_from_speed_limit.
Referenced by carla::traffic_manager::MotionPlanStage::GetLandmarkTargetVelocity(), and carla::traffic_manager::MotionPlanStage::Update().
RemoveImportedRoute()
void carla::traffic_manager::Parameters::RemoveImportedRoute (const ActorId & actor_id, const bool remove_path)
Method to remove a route.
Definition at line 203 of file Parameters.cpp.
References custom_route, carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry(), and upload_route.
Referenced by carla::traffic_manager::LocalizationStage::ImportRoute(), and carla::traffic_manager::TrafficManagerLocal::RemoveImportedRoute().
RemoveUploadPath()
void carla::traffic_manager::Parameters::RemoveUploadPath (const ActorId & actor_id, const bool remove_path)
Method to remove a list of points.
Definition at line 182 of file Parameters.cpp.
References custom_path, carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry(), and upload_path.
Referenced by carla::traffic_manager::LocalizationStage::ImportPath(), and carla::traffic_manager::TrafficManagerLocal::RemoveUploadPath().
SetAutoLaneChange()
void carla::traffic_manager::Parameters::SetAutoLaneChange (const ActorPtr & actor, const bool enable)
Enable/disable automatic lane change on a vehicle.
Definition at line 112 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and auto_lane_change.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetAutoLaneChange().
SetBoundariesRespawnDormantVehicles()
void carla::traffic_manager::Parameters::SetBoundariesRespawnDormantVehicles (const float lower_bound, const float upper_bound)
Method to set boundaries for respawning vehicles.
Definition at line 38 of file Parameters.cpp.
References max_upper_bound, min_lower_bound, respawn_lower_bound, and respawn_upper_bound.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetBoundariesRespawnDormantVehicles().
SetCollisionDetection()
void carla::traffic_manager::Parameters::SetCollisionDetection (const ActorPtr & reference_actor, const ActorPtr & other_actor, const bool detect_collision)
Method to set collision detection rules between vehicles.
Definition at line 54 of file Parameters.cpp.
References ignore_collision.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetCollisionDetection().
SetCustomPath()
void carla::traffic_manager::Parameters::SetCustomPath (const ActorPtr & actor, const Path path, const bool empty_buffer)
Method to set our own imported path.
Definition at line 175 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), custom_path, and upload_path.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetCustomPath().
SetDistanceToLeadingVehicle()
void carla::traffic_manager::Parameters::SetDistanceToLeadingVehicle (const ActorPtr & actor, const float distance)
Method to specify how much distance a vehicle should maintain to the leading vehicle.
Definition at line 118 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and distance_to_leading_vehicle.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetDistanceToLeadingVehicle().
SetForceLaneChange()
void carla::traffic_manager::Parameters::SetForceLaneChange (const ActorPtr & actor, const bool direction)
Method to force lane change on a vehicle.
Direction flag can be set to true for left and false for right.
Definition at line 80 of file Parameters.cpp.
References force_lane_change.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetForceLaneChange().
SetGlobalDistanceToLeadingVehicle()
void carla::traffic_manager::Parameters::SetGlobalDistanceToLeadingVehicle (const float dist)
Method to set the distance to leading vehicle for all registered vehicles.
Definition at line 133 of file Parameters.cpp.
References distance_margin.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetGlobalDistanceToLeadingVehicle().
SetGlobalPercentageSpeedDifference()
void carla::traffic_manager::Parameters::SetGlobalPercentageSpeedDifference (float const percentage)
Set a global % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Definition at line 49 of file Parameters.cpp.
References global_percentage_difference_from_limit.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetGlobalPercentageSpeedDifference(), and carla::traffic_manager::TrafficManagerLocal::TrafficManagerLocal().
SetHybridPhysicsMode()
void carla::traffic_manager::Parameters::SetHybridPhysicsMode (const bool mode_switch)
Method to set hybrid physics mode.
Definition at line 23 of file Parameters.cpp.
References hybrid_physics_mode.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetHybridPhysicsMode().
SetHybridPhysicsRadius()
void carla::traffic_manager::Parameters::SetHybridPhysicsRadius (const float radius)
Method to set hybrid physics radius.
Definition at line 166 of file Parameters.cpp.
References hybrid_physics_radius.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetHybridPhysicsRadius().
SetImportedRoute()
void carla::traffic_manager::Parameters::SetImportedRoute (const ActorPtr & actor, const Route route, const bool empty_buffer)
Method to set our own imported route.
Definition at line 196 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), custom_route, and upload_route.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetImportedRoute().
SetKeepRightPercentage()
void carla::traffic_manager::Parameters::SetKeepRightPercentage (const ActorPtr & actor, const float percentage)
Method to set % to keep on the right lane.
Definition at line 87 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and perc_keep_right.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetKeepRightPercentage().
SetMaxBoundaries()
void carla::traffic_manager::Parameters::SetMaxBoundaries (const float lower, const float upper)
Method to set limits for boundaries when respawning vehicles.
Definition at line 33 of file Parameters.cpp.
References max_upper_bound, and min_lower_bound.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run(), and carla::traffic_manager::TrafficManagerLocal::SetMaxBoundaries().
SetOSMMode()
void carla::traffic_manager::Parameters::SetOSMMode (const bool mode_switch)
Method to set Open Street Map mode.
Definition at line 171 of file Parameters.cpp.
References osm_mode.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetOSMMode().
SetPercentageIgnoreVehicles()
void carla::traffic_manager::Parameters::SetPercentageIgnoreVehicles (const ActorPtr & actor, const float perc)
Method to set % to ignore any vehicle.
Definition at line 152 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), carla::geom::Math::Clamp(), and perc_ignore_vehicles.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetPercentageIgnoreVehicles().
SetPercentageIgnoreWalkers()
void carla::traffic_manager::Parameters::SetPercentageIgnoreWalkers (const ActorPtr & actor, const float perc)
Method to set % to ignore any vehicle.
Definition at line 159 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), carla::geom::Math::Clamp(), and perc_ignore_walkers.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetPercentageIgnoreWalkers().
SetPercentageRunningLight()
void carla::traffic_manager::Parameters::SetPercentageRunningLight (const ActorPtr & actor, const float perc)
Method to set % to run any traffic light.
Definition at line 138 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), carla::geom::Math::Clamp(), and perc_run_traffic_light.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetPercentageRunningLight().
SetPercentageRunningSign()
void carla::traffic_manager::Parameters::SetPercentageRunningSign (const ActorPtr & actor, const float perc)
Method to set % to run any traffic sign.
Definition at line 145 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), carla::geom::Math::Clamp(), and perc_run_traffic_sign.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetPercentageRunningSign().
SetPercentageSpeedDifference()
void carla::traffic_manager::Parameters::SetPercentageSpeedDifference (const ActorPtr & actor, const float percentage)
Set a vehicle's % decrease in velocity with respect to the speed limit.
If less than 0, it's a % increase.
Definition at line 43 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and percentage_difference_from_speed_limit.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetPercentageSpeedDifference().
SetRandomLeftLaneChangePercentage()
void carla::traffic_manager::Parameters::SetRandomLeftLaneChangePercentage (const ActorPtr & actor, const float percentage)
Method to set % to randomly do a left lane change.
Definition at line 93 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and perc_random_left.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetRandomLeftLaneChangePercentage().
SetRandomRightLaneChangePercentage()
void carla::traffic_manager::Parameters::SetRandomRightLaneChangePercentage (const ActorPtr & actor, const float percentage)
Method to set % to randomly do a right lane change.
Definition at line 99 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and perc_random_right.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetRandomRightLaneChangePercentage().
SetRespawnDormantVehicles()
void carla::traffic_manager::Parameters::SetRespawnDormantVehicles (const bool mode_switch)
Method to set if we are automatically respawning vehicles.
Definition at line 28 of file Parameters.cpp.
References respawn_dormant_vehicles.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetRespawnDormantVehicles().
SetSynchronousMode()
void carla::traffic_manager::Parameters::SetSynchronousMode (const bool mode_switch = true)
Method to set synchronous mode.
Definition at line 125 of file Parameters.cpp.
References synchronous_mode.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetSynchronousMode().
SetSynchronousModeTimeOutInMiliSecond()
void carla::traffic_manager::Parameters::SetSynchronousModeTimeOutInMiliSecond (const double time)
Set Synchronous mode time out.
Definition at line 129 of file Parameters.cpp.
References synchronous_time_out.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetSynchronousModeTimeOutInMiliSecond().
SetUpdateVehicleLightState()
void carla::traffic_manager::Parameters::SetUpdateVehicleLightState (const ActorPtr & actor, const bool do_update)
Method to set the automatic vehicle light state update flag.
Definition at line 106 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), and auto_update_vehicle_lights.
Referenced by carla::traffic_manager::TrafficManagerLocal::SetUpdateVehicleLights().
UpdateImportedRoute()
void carla::traffic_manager::Parameters::UpdateImportedRoute (const ActorId & actor_id, const Route route)
Method to update an already set route.
Definition at line 211 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), custom_route, and carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry().
Referenced by carla::traffic_manager::LocalizationStage::ImportRoute(), and carla::traffic_manager::TrafficManagerLocal::UpdateImportedRoute().
UpdateUploadPath()
void carla::traffic_manager::Parameters::UpdateUploadPath (const ActorId & actor_id, const Path path)
Method to update an already set list of points.
Definition at line 190 of file Parameters.cpp.
References carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), custom_path, and carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry().
Referenced by carla::traffic_manager::LocalizationStage::ImportPath(), and carla::traffic_manager::TrafficManagerLocal::UpdateUploadPath().
Member Data Documentation
auto_lane_change
AtomicMap<ActorId, bool> carla::traffic_manager::Parameters::auto_lane_change private
Map containing auto lane change commands.
Definition at line 51 of file Parameters.h.
Referenced by GetAutoLaneChange(), and SetAutoLaneChange().
auto_update_vehicle_lights
AtomicMap<ActorId, bool> carla::traffic_manager::Parameters::auto_update_vehicle_lights private
Map containing the automatic vehicle lights update flag.
Definition at line 67 of file Parameters.h.
Referenced by GetUpdateVehicleLightState(), and SetUpdateVehicleLightState().
custom_path
AtomicMap<ActorId, Path> carla::traffic_manager::Parameters::custom_path private
Structure to hold all custom paths.
Definition at line 91 of file Parameters.h.
Referenced by GetCustomPath(), RemoveUploadPath(), SetCustomPath(), and UpdateUploadPath().
custom_route
AtomicMap<ActorId, Route> carla::traffic_manager::Parameters::custom_route private
Structure to hold all custom routes.
Definition at line 95 of file Parameters.h.
Referenced by GetImportedRoute(), RemoveImportedRoute(), SetImportedRoute(), and UpdateImportedRoute().
distance_margin
std::atomic<float> carla::traffic_manager::Parameters::distance_margin {2.0} private
Distance margin.
Definition at line 71 of file Parameters.h.
Referenced by GetDistanceToLeadingVehicle(), and SetGlobalDistanceToLeadingVehicle().
distance_to_leading_vehicle
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::distance_to_leading_vehicle private
Map containing distance to leading vehicle command.
Definition at line 47 of file Parameters.h.
Referenced by GetDistanceToLeadingVehicle(), and SetDistanceToLeadingVehicle().
force_lane_change
AtomicMap<ActorId, ChangeLaneInfo> carla::traffic_manager::Parameters::force_lane_change private
Map containing force lane change commands.
Definition at line 49 of file Parameters.h.
Referenced by GetForceLaneChange(), and SetForceLaneChange().
global_percentage_difference_from_limit
float carla::traffic_manager::Parameters::global_percentage_difference_from_limit = 0 private
Global target velocity limit % difference.
Definition at line 43 of file Parameters.h.
Referenced by GetVehicleTargetVelocity(), and SetGlobalPercentageSpeedDifference().
hybrid_physics_mode
std::atomic<bool> carla::traffic_manager::Parameters::hybrid_physics_mode {false} private
Hybrid physics mode switch.
Definition at line 73 of file Parameters.h.
Referenced by GetHybridPhysicsMode(), and SetHybridPhysicsMode().
hybrid_physics_radius
std::atomic<float> carla::traffic_manager::Parameters::hybrid_physics_radius {70.0} private
Hybrid physics radius.
Definition at line 85 of file Parameters.h.
Referenced by GetHybridPhysicsRadius(), and SetHybridPhysicsRadius().
ignore_collision
AtomicMap<ActorId, std::shared_ptr<AtomicActorSet> > carla::traffic_manager::Parameters::ignore_collision private
Map containing a set of actors to be ignored during collision detection.
Definition at line 45 of file Parameters.h.
Referenced by GetCollisionDetection(), and SetCollisionDetection().
max_upper_bound
float carla::traffic_manager::Parameters::max_upper_bound private
Maximum possible distance to respawn vehicles with respect to the hero vehicle.
Definition at line 83 of file Parameters.h.
Referenced by SetBoundariesRespawnDormantVehicles(), and SetMaxBoundaries().
min_lower_bound
float carla::traffic_manager::Parameters::min_lower_bound private
Minimum possible distance to respawn vehicles with respect to the hero vehicle.
Definition at line 81 of file Parameters.h.
Referenced by SetBoundariesRespawnDormantVehicles(), and SetMaxBoundaries().
osm_mode
std::atomic<bool> carla::traffic_manager::Parameters::osm_mode {true} private
Parameter specifying Open Street Map mode.
Definition at line 87 of file Parameters.h.
Referenced by GetOSMMode(), and SetOSMMode().
perc_ignore_vehicles
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_ignore_vehicles private
Map containing % of ignoring vehicles.
Definition at line 59 of file Parameters.h.
Referenced by GetPercentageIgnoreVehicles(), and SetPercentageIgnoreVehicles().
perc_ignore_walkers
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_ignore_walkers private
Map containing % of ignoring walkers.
Definition at line 57 of file Parameters.h.
Referenced by GetPercentageIgnoreWalkers(), and SetPercentageIgnoreWalkers().
perc_keep_right
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_keep_right private
Map containing % of keep right rule.
Definition at line 61 of file Parameters.h.
Referenced by GetKeepRightPercentage(), and SetKeepRightPercentage().
perc_random_left
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_random_left private
Map containing % of random left lane change.
Definition at line 63 of file Parameters.h.
Referenced by GetRandomLeftLaneChangePercentage(), and SetRandomLeftLaneChangePercentage().
perc_random_right
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_random_right private
Map containing % of random right lane change.
Definition at line 65 of file Parameters.h.
Referenced by GetRandomRightLaneChangePercentage(), and SetRandomRightLaneChangePercentage().
perc_run_traffic_light
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_run_traffic_light private
Map containing % of running a traffic light.
Definition at line 53 of file Parameters.h.
Referenced by GetPercentageRunningLight(), and SetPercentageRunningLight().
perc_run_traffic_sign
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::perc_run_traffic_sign private
Map containing % of running a traffic sign.
Definition at line 55 of file Parameters.h.
Referenced by GetPercentageRunningSign(), and SetPercentageRunningSign().
percentage_difference_from_speed_limit
AtomicMap<ActorId, float> carla::traffic_manager::Parameters::percentage_difference_from_speed_limit private
Target velocity map for individual vehicles.
Definition at line 41 of file Parameters.h.
Referenced by GetVehicleTargetVelocity(), and SetPercentageSpeedDifference().
respawn_dormant_vehicles
std::atomic<bool> carla::traffic_manager::Parameters::respawn_dormant_vehicles {false} private
Automatic respawn mode switch.
Definition at line 75 of file Parameters.h.
Referenced by GetRespawnDormantVehicles(), and SetRespawnDormantVehicles().
respawn_lower_bound
std::atomic<float> carla::traffic_manager::Parameters::respawn_lower_bound {100.0} private
Minimum distance to respawn vehicles with respect to the hero vehicle.
Definition at line 77 of file Parameters.h.
Referenced by GetLowerBoundaryRespawnDormantVehicles(), and SetBoundariesRespawnDormantVehicles().
respawn_upper_bound
std::atomic<float> carla::traffic_manager::Parameters::respawn_upper_bound {1000.0} private
Maximum distance to respawn vehicles with respect to the hero vehicle.
Definition at line 79 of file Parameters.h.
Referenced by GetUpperBoundaryRespawnDormantVehicles(), and SetBoundariesRespawnDormantVehicles().
synchronous_mode
std::atomic<bool> carla::traffic_manager::Parameters::synchronous_mode {false} private
Synchronous mode switch.
Definition at line 69 of file Parameters.h.
Referenced by GetSynchronousMode(), and SetSynchronousMode().
synchronous_time_out
std::chrono::duration<double, std::milli> carla::traffic_manager::Parameters::synchronous_time_out
Synchronous mode time out variable.
Definition at line 275 of file Parameters.h.
Referenced by GetSynchronousModeTimeOutInMiliSecond(), Parameters(), and SetSynchronousModeTimeOutInMiliSecond().
upload_path
AtomicMap<ActorId, bool> carla::traffic_manager::Parameters::upload_path private
Parameter specifying if importing a custom path.
Definition at line 89 of file Parameters.h.
Referenced by GetUploadPath(), RemoveUploadPath(), and SetCustomPath().
upload_route
AtomicMap<ActorId, bool> carla::traffic_manager::Parameters::upload_route private
Parameter specifying if importing a custom route.
Definition at line 93 of file Parameters.h.
Referenced by GetUploadRoute(), RemoveImportedRoute(), and SetImportedRoute().
The documentation for this class was generated from the following files:
Parameters.h
Parameters.cpp