CARLA: carla::traffic_manager::RandomGenerator< T, class > Class Template Reference
carla::traffic_manager::RandomGenerator< T, class > Class Template Reference
#include <RandomGenerator.h>
Public Member Functions
T next ()
RandomGenerator ()
Private Attributes
std::uniform_real_distribution< T > dist
std::mt19937 mt
Detailed Description
template<class T = double, class = std::enable_if_t<std::is_floating_point<T>::value>>
class carla::traffic_manager::RandomGenerator< T, class >
Definition at line 10 of file RandomGenerator.h.
Constructor & Destructor Documentation
template<class T = double, class = std::enable_if_t<std::is_floating_point<T>::value>> carla::traffic_manager::RandomGenerator< T, class >::RandomGenerator () inline
Definition at line 12 of file RandomGenerator.h.
References carla::traffic_manager::RandomGenerator< T, class >::dist.
Member Function Documentation
template<class T = double, class = std::enable_if_t<std::is_floating_point<T>::value>> T carla::traffic_manager::RandomGenerator< T, class >::next () inline
Definition at line 13 of file RandomGenerator.h.
References carla::traffic_manager::RandomGenerator< T, class >::dist, and carla::traffic_manager::RandomGenerator< T, class >::mt.
Referenced by carla::traffic_manager::TrafficLightStage::Update(), carla::traffic_manager::LocalizationStage::Update(), and carla::traffic_manager::CollisionStage::Update().
Member Data Documentation
template<class T = double, class = std::enable_if_t<std::is_floating_point<T>::value>> std::uniform_real_distribution<T> carla::traffic_manager::RandomGenerator< T, class >::dist private
Definition at line 16 of file RandomGenerator.h.
Referenced by carla::traffic_manager::RandomGenerator< T, class >::next(), and carla::traffic_manager::RandomGenerator< T, class >::RandomGenerator().
template<class T = double, class = std::enable_if_t<std::is_floating_point<T>::value>> std::mt19937 carla::traffic_manager::RandomGenerator< T, class >::mt private
Definition at line 15 of file RandomGenerator.h.
Referenced by carla::traffic_manager::RandomGenerator< T, class >::next().
The documentation for this class was generated from the following file:
RandomGenerator.h