CARLA: carla::traffic_manager::ALSM Class Reference
carla::traffic_manager::ALSM Class Reference
ALSM: Agent Lifecycle and State Managerment This class has functionality to update the local cache of kinematic states and manage memory and cleanup for varying number of vehicles in the simulation.
#include <ALSM.h>
Public Member Functions
ALSM (AtomicActorSet &registered_vehicles, BufferMap &buffer_map, TrackTraffic &track_traffic, const Parameters &parameters, const cc::World &world, const LocalMapPtr &local_map, SimulationState &simulation_state, LocalizationStage &localization_stage, CollisionStage &collision_stage, TrafficLightStage &traffic_light_stage, MotionPlanStage &motion_plan_stage)
void Reset ()
void Update ()
Private Types
using ActorVector = std::vector< ActorPtr >
using DestroyeddActors = std::pair< ActorIdSet, ActorIdSet >
using IdleInfo = std::pair< ActorId, double >
Private Member Functions
DestroyeddActors IdentifyDestroyedActors (const ActorList &actor_list)
ActorVector IdentifyNewActors (const ActorList &actor_list)
bool IsVehicleStuck (const ActorId &actor_id)
void RemoveActor (const ActorId actor_id, const bool registered_actor)
void UpdateIdleTime (std::pair< ActorId, double > &max_idle_time, const ActorId &actor_id)
void UpdateRegisteredActorsData (const bool hybrid_physics_mode, IdleInfo &max_idle_time)
void UpdateUnregisteredActorsData ()
Private Attributes
BufferMap & buffer_map
CollisionStage & collision_stage
cc::Timestamp current_timestamp
double elapsed_last_actor_destruction {0.0}
ActorMap hero_actors
IdleTimeMap idle_time
const LocalMapPtr & local_map
LocalizationStage & localization_stage
MotionPlanStage & motion_plan_stage
const Parameters & parameters
AtomicActorSet & registered_vehicles
SimulationState & simulation_state
TrackTraffic & track_traffic
TrafficLightStage & traffic_light_stage
ActorMap unregistered_actors
const cc::World & world
Detailed Description
ALSM: Agent Lifecycle and State Managerment This class has functionality to update the local cache of kinematic states and manage memory and cleanup for varying number of vehicles in the simulation.
Definition at line 39 of file ALSM.h.
Member Typedef Documentation
ActorVector
using carla::traffic_manager::ALSM::ActorVector = std::vector<ActorPtr> private
Definition at line 73 of file ALSM.h.
DestroyeddActors
using carla::traffic_manager::ALSM::DestroyeddActors = std::pair<ActorIdSet, ActorIdSet> private
Definition at line 77 of file ALSM.h.
IdleInfo
using carla::traffic_manager::ALSM::IdleInfo = std::pair<ActorId, double> private
Definition at line 82 of file ALSM.h.
Constructor & Destructor Documentation
ALSM()
carla::traffic_manager::ALSM::ALSM (AtomicActorSet & registered_vehicles, BufferMap & buffer_map, TrackTraffic & track_traffic, const Parameters & parameters, const cc::World & world, const LocalMapPtr & local_map, SimulationState & simulation_state, LocalizationStage & localization_stage, CollisionStage & collision_stage, TrafficLightStage & traffic_light_stage, MotionPlanStage & motion_plan_stage)
Definition at line 17 of file ALSM.cpp.
Member Function Documentation
IdentifyDestroyedActors()
ALSM::DestroyeddActors carla::traffic_manager::ALSM::IdentifyDestroyedActors (const ActorList & actor_list) private
Definition at line 126 of file ALSM.cpp.
References carla::traffic_manager::AtomicActorSet::Contains(), carla::traffic_manager::AtomicActorSet::GetIDList(), registered_vehicles, and unregistered_actors.
Referenced by Update().
IdentifyNewActors()
std::vector< ActorPtr > carla::traffic_manager::ALSM::IdentifyNewActors (const ActorList & actor_list) private
Definition at line 113 of file ALSM.cpp.
References carla::traffic_manager::AtomicActorSet::Contains(), registered_vehicles, and unregistered_actors.
Referenced by Update().
IsVehicleStuck()
bool carla::traffic_manager::ALSM::IsVehicleStuck (const ActorId & actor_id) private
Definition at line 316 of file ALSM.cpp.
References carla::traffic_manager::constants::VehicleRemoval::BLOCKED_TIME_THRESHOLD, current_timestamp, carla::client::Timestamp::elapsed_seconds, and idle_time.
Referenced by Update().
RemoveActor()
void carla::traffic_manager::ALSM::RemoveActor (const ActorId actor_id, const bool registered_actor) private
Definition at line 326 of file ALSM.cpp.
References buffer_map, collision_stage, carla::traffic_manager::TrackTraffic::DeleteActor(), hero_actors, idle_time, localization_stage, motion_plan_stage, registered_vehicles, carla::traffic_manager::AtomicActorSet::Remove(), carla::traffic_manager::TrafficLightStage::RemoveActor(), carla::traffic_manager::SimulationState::RemoveActor(), carla::traffic_manager::MotionPlanStage::RemoveActor(), carla::traffic_manager::LocalizationStage::RemoveActor(), carla::traffic_manager::CollisionStage::RemoveActor(), simulation_state, track_traffic, traffic_light_stage, and unregistered_actors.
Referenced by Update().
Reset()
void carla::traffic_manager::ALSM::Reset (void)
Definition at line 345 of file ALSM.cpp.
References current_timestamp, elapsed_last_actor_destruction, carla::client::World::GetSnapshot(), carla::client::WorldSnapshot::GetTimestamp(), hero_actors, idle_time, unregistered_actors, and world.
Update()
void carla::traffic_manager::ALSM::Update ()
Definition at line 41 of file ALSM.cpp.
References current_timestamp, carla::traffic_manager::constants::VehicleRemoval::DELTA_TIME_BETWEEN_DESTRUCTIONS, carla::traffic_manager::AtomicActorSet::Destroy(), elapsed_last_actor_destruction, carla::client::Timestamp::elapsed_seconds, carla::client::World::GetActors(), carla::traffic_manager::Parameters::GetHybridPhysicsMode(), carla::client::World::GetSnapshot(), carla::client::WorldSnapshot::GetTimestamp(), hero_actors, IdentifyDestroyedActors(), IdentifyNewActors(), IsVehicleStuck(), parameters, registered_vehicles, RemoveActor(), unregistered_actors, UpdateRegisteredActorsData(), UpdateUnregisteredActorsData(), and world.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run().
UpdateIdleTime()
void carla::traffic_manager::ALSM::UpdateIdleTime (std::pair< ActorId, double > & max_idle_time, const ActorId & actor_id) private
Definition at line 300 of file ALSM.cpp.
References carla::traffic_manager::TrafficLightState::at_traffic_light, current_timestamp, carla::client::Timestamp::elapsed_seconds, carla::traffic_manager::SimulationState::GetTLS(), carla::traffic_manager::SimulationState::GetVelocity(), carla::rpc::Green, idle_time, simulation_state, SQUARE, carla::geom::Vector3D::SquaredLength(), carla::traffic_manager::constants::VehicleRemoval::STOPPED_VELOCITY_THRESHOLD, and carla::traffic_manager::TrafficLightState::tl_state.
Referenced by UpdateRegisteredActorsData().
UpdateRegisteredActorsData()
void carla::traffic_manager::ALSM::UpdateRegisteredActorsData (const bool hybrid_physics_mode, ALSM::IdleInfo & max_idle_time) private
Definition at line 158 of file ALSM.cpp.
References carla::traffic_manager::SimulationState::AddActor(), carla::traffic_manager::SimulationState::ContainsActor(), current_timestamp, carla::geom::Math::DistanceSquared(), carla::client::Timestamp::elapsed_seconds, carla::traffic_manager::Parameters::GetHybridPhysicsRadius(), carla::traffic_manager::AtomicActorSet::GetList(), carla::traffic_manager::SimulationState::GetLocation(), hero_actors, idle_time, carla::traffic_manager::constants::HybridMode::INV_HYBRID_DT, carla::geom::Transform::location, parameters, registered_vehicles, carla::geom::Transform::rotation, simulation_state, SQUARE, UpdateIdleTime(), carla::traffic_manager::SimulationState::UpdateKinematicState(), carla::traffic_manager::SimulationState::UpdateTrafficLightState(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by Update().
UpdateUnregisteredActorsData()
void carla::traffic_manager::ALSM::UpdateUnregisteredActorsData () private
Definition at line 231 of file ALSM.cpp.
References carla::traffic_manager::SimulationState::AddActor(), carla::traffic_manager::Any, carla::traffic_manager::SimulationState::ContainsActor(), carla::client::Vehicle::GetSpeedLimit(), local_map, carla::geom::Transform::location, carla::traffic_manager::Pedestrian, carla::geom::Transform::rotation, simulation_state, track_traffic, unregistered_actors, carla::traffic_manager::SimulationState::UpdateKinematicState(), carla::traffic_manager::SimulationState::UpdateTrafficLightState(), carla::traffic_manager::TrackTraffic::UpdateUnregisteredGridPosition(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Referenced by Update().
Member Data Documentation
buffer_map
BufferMap& carla::traffic_manager::ALSM::buffer_map private
Definition at line 45 of file ALSM.h.
Referenced by RemoveActor().
collision_stage
CollisionStage& carla::traffic_manager::ALSM::collision_stage private
Definition at line 56 of file ALSM.h.
Referenced by RemoveActor().
current_timestamp
cc::Timestamp carla::traffic_manager::ALSM::current_timestamp private
Definition at line 61 of file ALSM.h.
Referenced by IsVehicleStuck(), Reset(), Update(), UpdateIdleTime(), and UpdateRegisteredActorsData().
elapsed_last_actor_destruction
double carla::traffic_manager::ALSM::elapsed_last_actor_destruction {0.0} private
Definition at line 60 of file ALSM.h.
Referenced by Reset(), and Update().
hero_actors
ActorMap carla::traffic_manager::ALSM::hero_actors private
Definition at line 49 of file ALSM.h.
Referenced by RemoveActor(), Reset(), Update(), and UpdateRegisteredActorsData().
idle_time
IdleTimeMap carla::traffic_manager::ALSM::idle_time private
Definition at line 47 of file ALSM.h.
Referenced by IsVehicleStuck(), RemoveActor(), Reset(), UpdateIdleTime(), and UpdateRegisteredActorsData().
local_map
const LocalMapPtr& carla::traffic_manager::ALSM::local_map private
Definition at line 53 of file ALSM.h.
Referenced by UpdateUnregisteredActorsData().
localization_stage
LocalizationStage& carla::traffic_manager::ALSM::localization_stage private
Definition at line 55 of file ALSM.h.
Referenced by RemoveActor().
motion_plan_stage
MotionPlanStage& carla::traffic_manager::ALSM::motion_plan_stage private
Definition at line 58 of file ALSM.h.
Referenced by RemoveActor().
parameters
const Parameters& carla::traffic_manager::ALSM::parameters private
Definition at line 51 of file ALSM.h.
Referenced by Update(), and UpdateRegisteredActorsData().
registered_vehicles
AtomicActorSet& carla::traffic_manager::ALSM::registered_vehicles private
Definition at line 42 of file ALSM.h.
Referenced by IdentifyDestroyedActors(), IdentifyNewActors(), RemoveActor(), Update(), and UpdateRegisteredActorsData().
simulation_state
SimulationState& carla::traffic_manager::ALSM::simulation_state private
Definition at line 54 of file ALSM.h.
Referenced by RemoveActor(), UpdateIdleTime(), UpdateRegisteredActorsData(), and UpdateUnregisteredActorsData().
track_traffic
TrackTraffic& carla::traffic_manager::ALSM::track_traffic private
Definition at line 50 of file ALSM.h.
Referenced by RemoveActor(), and UpdateUnregisteredActorsData().
traffic_light_stage
TrafficLightStage& carla::traffic_manager::ALSM::traffic_light_stage private
Definition at line 57 of file ALSM.h.
Referenced by RemoveActor().
unregistered_actors
ActorMap carla::traffic_manager::ALSM::unregistered_actors private
Definition at line 44 of file ALSM.h.
Referenced by IdentifyDestroyedActors(), IdentifyNewActors(), RemoveActor(), Reset(), Update(), and UpdateUnregisteredActorsData().
world
const cc::World& carla::traffic_manager::ALSM::world private
Definition at line 52 of file ALSM.h.
Referenced by Reset(), and Update().
The documentation for this class was generated from the following files:
ALSM.h
ALSM.cpp