CARLA: builtin_interfaces::msg::TimePubSubType Class Reference
builtin_interfaces::msg::TimePubSubType Class Reference
This class represents the TopicDataType of the type Time defined by the user in the IDL file.
#include <TimePubSubTypes.h>
Public Types
typedef Time type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport TimePubSubType ()
virtual eProsima_user_DllExport ~TimePubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type Time defined by the user in the IDL file.
Definition at line 43 of file TimePubSubTypes.h.
Member Typedef Documentation
type
typedef Time builtin_interfaces::msg::TimePubSubType::type
Definition at line 47 of file TimePubSubTypes.h.
Constructor & Destructor Documentation
TimePubSubType()
builtin_interfaces::msg::TimePubSubType::TimePubSubType ()
Definition at line 32 of file TimePubSubTypes.cpp.
References builtin_interfaces::msg::Time::getKeyMaxCdrSerializedSize(), builtin_interfaces::msg::Time::getMaxCdrSerializedSize(), builtin_interfaces::msg::Time::isKeyDefined(), and m_keyBuffer.
~TimePubSubType()
builtin_interfaces::msg::TimePubSubType::~TimePubSubType () override virtual
Definition at line 45 of file TimePubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * builtin_interfaces::msg::TimePubSubType::createData () override virtual
Definition at line 105 of file TimePubSubTypes.cpp.
deleteData()
void builtin_interfaces::msg::TimePubSubType::deleteData (void * data) override virtual
Definition at line 110 of file TimePubSubTypes.cpp.
deserialize()
bool builtin_interfaces::msg::TimePubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 72 of file TimePubSubTypes.cpp.
References builtin_interfaces::msg::Time::deserialize().
getKey()
bool builtin_interfaces::msg::TimePubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 116 of file TimePubSubTypes.cpp.
References builtin_interfaces::msg::Time::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and builtin_interfaces::msg::Time::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> builtin_interfaces::msg::TimePubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 95 of file TimePubSubTypes.cpp.
References builtin_interfaces::msg::Time::getCdrSerializedSize().
serialize()
bool builtin_interfaces::msg::TimePubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file TimePubSubTypes.cpp.
References builtin_interfaces::msg::Time::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* builtin_interfaces::msg::TimePubSubType::m_keyBuffer
Definition at line 100 of file TimePubSubTypes.h.
Referenced by getKey(), TimePubSubType(), and ~TimePubSubType().
m_md5
MD5 builtin_interfaces::msg::TimePubSubType::m_md5
Definition at line 99 of file TimePubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
TimePubSubTypes.h
TimePubSubTypes.cpp