CARLA: carla::sensor::s11n::ObstacleDetectionEventSerializer Class Reference
carla::sensor::s11n::ObstacleDetectionEventSerializer Class Reference
Serializes the current state of the whole episode.
#include <ObstacleDetectionEventSerializer.h>
Classes
struct Data
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static Data DeserializeRawData (const RawData &message)
template<typename SensorT >
static Buffer Serialize (const SensorT &, rpc::Actor self_actor, rpc::Actor other_actor, float distance)
Static Public Attributes
static constexpr auto header_offset = 0u
Detailed Description
Serializes the current state of the whole episode.
Definition at line 23 of file ObstacleDetectionEventSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::ObstacleDetectionEventSerializer::Deserialize (RawData && data) static
Definition at line 14 of file ObstacleDetectionEventSerializer.cpp.
Referenced by Serialize().
DeserializeRawData()
static Data carla::sensor::s11n::ObstacleDetectionEventSerializer::DeserializeRawData (const RawData & message) inline static
Definition at line 39 of file ObstacleDetectionEventSerializer.h.
References carla::sensor::RawData::begin(), and carla::sensor::RawData::size().
Referenced by carla::sensor::data::ObstacleDetectionEvent::ObstacleDetectionEvent().
Serialize()
template<typename SensorT > static Buffer carla::sensor::s11n::ObstacleDetectionEventSerializer::Serialize (const SensorT & , rpc::Actor self_actor, rpc::Actor other_actor, float distance) inline static
Definition at line 44 of file ObstacleDetectionEventSerializer.h.
References Deserialize(), carla::sensor::s11n::ObstacleDetectionEventSerializer::Data::other_actor, carla::MsgPack::Pack(), and carla::sensor::s11n::ObstacleDetectionEventSerializer::Data::self_actor.
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::ObstacleDetectionEventSerializer::header_offset = 0u static
Definition at line 37 of file ObstacleDetectionEventSerializer.h.
The documentation for this class was generated from the following files:
ObstacleDetectionEventSerializer.h
ObstacleDetectionEventSerializer.cpp