CARLA: CarlaRecorderLightVehicles Struct Reference
CarlaRecorderLightVehicles Struct Reference
#include <CarlaRecorderLightVehicle.h>
Public Member Functions
void Add (const CarlaRecorderLightVehicle &InObj)
void Clear (void)
void Write (std::ofstream &OutFile)
Private Attributes
std::vector< CarlaRecorderLightVehicle > Vehicles
Detailed Description
Definition at line 28 of file CarlaRecorderLightVehicle.h.
Member Function Documentation
void CarlaRecorderLightVehicles::Add (const CarlaRecorderLightVehicle & InObj)
Definition at line 32 of file CarlaRecorderLightVehicle.cpp.
References Vehicles.
Referenced by ACarlaRecorder::AddLightVehicle().
void CarlaRecorderLightVehicles::Clear (void)
Definition at line 27 of file CarlaRecorderLightVehicle.cpp.
References Vehicles.
Referenced by ACarlaRecorder::Clear().
void CarlaRecorderLightVehicles::Write (std::ofstream & OutFile)
Definition at line 37 of file CarlaRecorderLightVehicle.cpp.
References Vehicle, VehicleLight, and Vehicles.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
std::vector<CarlaRecorderLightVehicle> CarlaRecorderLightVehicles::Vehicles private
Definition at line 40 of file CarlaRecorderLightVehicle.h.
The documentation for this struct was generated from the following files:
CarlaRecorderLightVehicle.h
CarlaRecorderLightVehicle.cpp