CARLA: PixelReader.cpp File Reference
PixelReader.cpp File Reference
#include "Carla.h"
#include "Carla/Sensor/PixelReader.h"
#include "Engine/TextureRenderTarget2D.h"
#include "HighResScreenshot.h"
#include "Runtime/ImageWriteQueue/Public/ImageWriteQueue.h"
Classes
struct LockTexture
Functions
static void WriteFloatPixelsToBuffer_Vulkan (const UTextureRenderTarget2D &RenderTarget, carla::Buffer &Buffer, uint32 Offset, FRHICommandListImmediate &InRHICmdList)
static void WritePixelsToBuffer_Vulkan (const UTextureRenderTarget2D &RenderTarget, carla::Buffer &Buffer, uint32 Offset, FRHICommandListImmediate &InRHICmdList)
Variables
TArray< FFloat16Color > gFloatPixels
TArray< FColor > gPixels
Function Documentation
WriteFloatPixelsToBuffer_Vulkan()
static void WriteFloatPixelsToBuffer_Vulkan (const UTextureRenderTarget2D & RenderTarget, carla::Buffer & Buffer, uint32 Offset, FRHICommandListImmediate & InRHICmdList) static
Definition at line 79 of file PixelReader.cpp.
References carla::Buffer::copy_from(), gFloatPixels, and LockTexture::Texture.
Referenced by FPixelReader::WritePixelsToBuffer().
WritePixelsToBuffer_Vulkan()
static void WritePixelsToBuffer_Vulkan (const UTextureRenderTarget2D & RenderTarget, carla::Buffer & Buffer, uint32 Offset, FRHICommandListImmediate & InRHICmdList) static
Definition at line 43 of file PixelReader.cpp.
References carla::Buffer::copy_from(), gPixels, and LockTexture::Texture.
Referenced by FPixelReader::WritePixelsToBuffer().
Variable Documentation
gFloatPixels
TArray<FFloat16Color> gFloatPixels
Definition at line 77 of file PixelReader.cpp.
Referenced by WriteFloatPixelsToBuffer_Vulkan().
gPixels
TArray<FColor> gPixels
Definition at line 41 of file PixelReader.cpp.
Referenced by WritePixelsToBuffer_Vulkan().