CARLA: FCarlaServer Class Reference
FCarlaServer Class Reference
#include <CarlaServer.h>
Classes
class FPimpl
Public Member Functions
void AsyncRun (uint32 NumberOfWorkerThreads)
FCarlaServer ()
std::shared_ptr< carla::multigpu::Router > GetSecondaryServer ()
carla::streaming::Server & GetStreamingServer ()
void NotifyBeginEpisode (UCarlaEpisode &Episode)
void NotifyEndEpisode ()
FDataStream OpenStream () const
void RunSome (uint32 Milliseconds)
FDataMultiStream Start (uint16_t RPCPort, uint16_t StreamingPort, uint16_t SecondaryPort)
void Stop ()
void Tick ()
bool TickCueReceived ()
~FCarlaServer ()
Private Attributes
TUniquePtr< FPimpl > Pimpl
Detailed Description
Definition at line 21 of file CarlaServer.h.
Constructor & Destructor Documentation
FCarlaServer()
FCarlaServer::FCarlaServer ()
Definition at line 2617 of file CarlaServer.cpp.
~FCarlaServer()
FCarlaServer::~FCarlaServer ()
Definition at line 2619 of file CarlaServer.cpp.
References Stop().
Member Function Documentation
AsyncRun()
void FCarlaServer::AsyncRun (uint32 NumberOfWorkerThreads)
Todo:
Define better the number of threads each server gets.
Definition at line 2652 of file CarlaServer.cpp.
References carla::client::detail::Get(), and Pimpl.
Referenced by FCarlaEngine::NotifyInitGame().
GetSecondaryServer()
std::shared_ptr< carla::multigpu::Router > FCarlaServer::GetSecondaryServer ()
Definition at line 2719 of file CarlaServer.cpp.
References Pimpl.
Referenced by FCarlaEngine::NotifyInitGame().
GetStreamingServer()
carla::streaming::Server & FCarlaServer::GetStreamingServer ()
Definition at line 2724 of file CarlaServer.cpp.
References Pimpl.
Referenced by FCarlaEngine::NotifyInitGame().
NotifyBeginEpisode()
void FCarlaServer::NotifyBeginEpisode (UCarlaEpisode & Episode)
Definition at line 2639 of file CarlaServer.cpp.
References UCarlaEpisode::GetMapName(), and Pimpl.
Referenced by FCarlaEngine::NotifyBeginEpisode().
NotifyEndEpisode()
void FCarlaServer::NotifyEndEpisode ()
Definition at line 2646 of file CarlaServer.cpp.
References Pimpl.
Referenced by FCarlaEngine::NotifyEndEpisode().
OpenStream()
FDataStream FCarlaServer::OpenStream () const
Definition at line 2713 of file CarlaServer.cpp.
References Pimpl.
Referenced by ASensorFactory::SpawnActor().
RunSome()
void FCarlaServer::RunSome (uint32 Milliseconds)
Definition at line 2684 of file CarlaServer.cpp.
References carla::time_duration::milliseconds(), and Pimpl.
Referenced by FCarlaEngine::OnPreTick().
Start()
FDataMultiStream FCarlaServer::Start (uint16_t RPCPort, uint16_t StreamingPort, uint16_t SecondaryPort)
Definition at line 2623 of file CarlaServer.cpp.
References Pimpl.
Referenced by FCarlaEngine::NotifyInitGame().
Stop()
void FCarlaServer::Stop ()
Definition at line 2704 of file CarlaServer.cpp.
References Pimpl.
Referenced by ~FCarlaServer().
Tick()
void FCarlaServer::Tick ()
Definition at line 2690 of file CarlaServer.cpp.
References Pimpl.
Referenced by FCarlaEngine::NotifyInitGame().
TickCueReceived()
bool FCarlaServer::TickCueReceived ()
Definition at line 2695 of file CarlaServer.cpp.
References Pimpl.
Referenced by FCarlaServer::FPimpl::BindActions(), and FCarlaEngine::OnPreTick().
Member Data Documentation
Pimpl
TUniquePtr<FPimpl> FCarlaServer::Pimpl private
Definition at line 53 of file CarlaServer.h.
Referenced by AsyncRun(), GetSecondaryServer(), GetStreamingServer(), NotifyBeginEpisode(), NotifyEndEpisode(), OpenStream(), RunSome(), Start(), Stop(), Tick(), and TickCueReceived().
The documentation for this class was generated from the following files:
CarlaServer.h
CarlaServer.cpp