CARLA: carla::StringUtil Class Reference
carla::StringUtil Class Reference
#include <StringUtil.h>
Static Public Member Functions
template<typename Range1T , typename Range2T >
static bool EndsWith (const Range1T &input, const Range2T &test)
static bool Match (const char *str, const char *wildcard_pattern)
Match str with the Unix shell-style wildcard_pattern.
template<typename String1T , typename String2T >
static bool Match (const String1T &str, const String2T &wildcard_pattern)
Match str with the Unix shell-style wildcard_pattern.
template<typename Container , typename Range1T , typename Range2T >
static void Split (Container &destination, const Range1T &str, const Range2T &separators)
template<typename Range1T , typename Range2T >
static bool StartsWith (const Range1T &input, const Range2T &test)
static const char * ToConstCharPtr (const char *str)
template<typename StringT >
static const char * ToConstCharPtr (const StringT &str)
template<typename WritableRangeT >
static void ToLower (WritableRangeT &str)
template<typename SequenceT >
static auto ToLowerCopy (const SequenceT &str)
template<typename WritableRangeT >
static void ToUpper (WritableRangeT &str)
template<typename SequenceT >
static auto ToUpperCopy (const SequenceT &str)
template<typename WritableRangeT >
static void Trim (WritableRangeT &str)
template<typename SequenceT >
static auto TrimCopy (const SequenceT &str)
Detailed Description
Definition at line 13 of file StringUtil.h.
Member Function Documentation
template<typename Range1T , typename Range2T > static bool carla::StringUtil::EndsWith (const Range1T & input, const Range2T & test) inline static
Definition at line 31 of file StringUtil.h.
bool carla::StringUtil::Match (const char * str, const char * wildcard_pattern) static
Match str with the Unix shell-style wildcard_pattern.
Definition at line 17 of file StringUtil.cpp.
Referenced by carla::traffic_manager::LocalizationStage::DataReceiver(), carla::client::ActorList::Filter(), carla::FileSystem::ListFolder(), Match(), carla::client::ActorBlueprint::MatchTags(), carla::traffic_manager::TrafficManagerLocal::ResetAllTrafficLights(), carla::traffic_manager::LocalizationStage::ScanUnregisteredVehicles(), and Split().
template<typename String1T , typename String2T > static bool carla::StringUtil::Match (const String1T & str, const String2T & wildcard_pattern) inline static
Match str with the Unix shell-style wildcard_pattern.
Definition at line 75 of file StringUtil.h.
References Match(), and ToConstCharPtr().
template<typename Container , typename Range1T , typename Range2T > static void carla::StringUtil::Split (Container & destination, const Range1T & str, const Range2T & separators) inline static
Definition at line 66 of file StringUtil.h.
References Match().
Referenced by carla::client::ActorAttributeValueAccess::As< sensor::data::Color >(), carla::client::ActorBlueprint::ActorBlueprint(), and carla::opendrive::parser::ParseGeoReference().
template<typename Range1T , typename Range2T > static bool carla::StringUtil::StartsWith (const Range1T & input, const Range2T & test) inline static
Definition at line 26 of file StringUtil.h.
Referenced by carla::client::detail::ActorFactory::MakeActor().
static const char* carla::StringUtil::ToConstCharPtr (const char * str) inline static
Definition at line 16 of file StringUtil.h.
Referenced by Match().
template<typename StringT > static const char* carla::StringUtil::ToConstCharPtr (const StringT & str) inline static
Definition at line 21 of file StringUtil.h.
template<typename WritableRangeT > static void carla::StringUtil::ToLower (WritableRangeT & str) inline static
Definition at line 36 of file StringUtil.h.
Referenced by carla::road::MapBuilder::CreateRoadMark(), carla::road::element::GetColor(), carla::road::element::GetType(), carla::client::ActorAttribute::Set(), and carla::opendrive::parser::StringToLaneType().
template<typename SequenceT > static auto carla::StringUtil::ToLowerCopy (const SequenceT & str) inline static
Definition at line 41 of file StringUtil.h.
Referenced by carla::client::ActorAttributeValueAccess::As().
template<typename WritableRangeT > static void carla::StringUtil::ToUpper (WritableRangeT & str) inline static
Definition at line 46 of file StringUtil.h.
template<typename SequenceT > static auto carla::StringUtil::ToUpperCopy (const SequenceT & str) inline static
Definition at line 51 of file StringUtil.h.
template<typename WritableRangeT > static void carla::StringUtil::Trim (WritableRangeT & str) inline static
Definition at line 56 of file StringUtil.h.
template<typename SequenceT > static auto carla::StringUtil::TrimCopy (const SequenceT & str) inline static
Definition at line 61 of file StringUtil.h.
The documentation for this class was generated from the following files:
StringUtil.h
StringUtil.cpp